Make open/close index API public
elastic/elasticsearch pull request #100195
Opened 2023-10-03 12:43 UTC by javanna

Certain index settings can only be updated when an index is closed, which makes close/open index API necessary.

2023-10-04 06:00 UTC, tvernum reviewed
LGTM.
I had hoped that we would be able to avoid making users manually manage indices like this, but we haven't gotten there yet, so I guess we need this.

I'd like a review from @elastic/es-distributed though, because I don't know if whether open/close is expected to work on stateless.

2023-10-04 14:01 UTC, kingherc reviewed
We do have some tests in stateless to close and open an index, but I would not say we have focused a lot on this use case. Maybe @henningandersen would be best to comment on this PR.

2023-10-05 05:44 UTC, henningandersen requested changes
We did not expose the close API, because it is potentially unsafe without further work. I'll investigate some more but wanted to put this note in.

2023-10-12 10:49 UTC, vidok commented
@henningandersen May I know more about when you plan to work on our investigation and how long it approximately take? So we can adjust our plans accordingly. Thanks.

the blocked [issue](https://github.com/elastic/enterprise-search-team/issues/5765).

2023-10-24 14:20 UTC, DianaJourdan commented
@henningandersen, @tvernum  is there any progress/ decision on this issue? We need an answer before the serverless M1 milestone, so we can at least document it as a known issue. Thanks!

2023-10-25 07:32 UTC, henningandersen commented
We'd like to avoid exposing open/close in serverless. Having to open/close in order to change a setting is bad UX. The comment [here](https://github.com/elastic/elasticsearch/issues/101031#issuecomment-1776813430) explains the direction we'd like to take for elasticsearch in general, deprecating and eventually removing open/close index as the ultimate goal. Closing an index is not entirely safe in serverless (and also has bad edge cases in stateful). Additionally, there is little testing of this in serverless and that would be warranted in order to implement close (and open). Instead we'll aim for doing index settings updates without having to close the index (as elaborated in the [linked isssue comment](https://github.com/elastic/elasticsearch/issues/101031#issuecomment-1776813430)).

2023-11-01 09:12 UTC, closed without merging