change equal methods
elastic/elasticsearch pull request #101293
Opened 2023-10-25 04:15 UTC by jww1226

Changing equal methods according to the issue https://github.com/elastic/elasticsearch/issues/100870

2023-10-30 12:14 UTC, elasticsearchmachine commented
Pinging @elastic/es-search (Team:Search)

2023-11-01 09:51 UTC, cbuescher requested changes
I don't think the three `DecayFunction` implementations need any equals or hashcode implementation, they are all three final static members so Object.equals should be sufficient. I would say lets remove them altogether.
OperationModeUpdateTask hasn't anything to do with the original issue, lets not touch it.

2024-06-24 22:44 UTC, Marcono1234 commented
Looks like this was superseded by #107415

(Thanks nonetheless for trying to fix the issue I had reported!)

2024-07-17 19:31 UTC, elasticsearchmachine commented
Pinging @elastic/es-search-relevance (Team:Search Relevance)

2025-05-15 17:11 UTC, closed without merging