Convert classes to records
elastic/elasticsearch pull request #101860
Opened 2023-11-07 09:56 UTC by idegtiarenko

This converts following classes into records:
* SnapshotsInProgress.ShardSnapshotStatus
* SnapshotsInProgress.Entry
* RestoreInProgress.ShardRestoreStatus

2023-11-07 09:57 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2023-11-07 12:34 UTC, original-brownbear approved these changes
LGTM neat :)

2023-11-07 12:43 UTC, DaveCTurner requested changes

2023-11-07 12:43 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/SnapshotsInProgress.java
> -        private Entry(
IMO there was some value in hiding the constructor of this class. It has tricky invariants and we do not want callers to just construct arbitrary values. Could you add the constructor to forbidden APIs?

2023-11-27 15:09 UTC, idegtiarenko commented
I removed `SnapshotsInProgress.Entry` as `snapshotIndices` fields are excluded from equals/hashCode. I would like not to change that yet

2023-11-27 16:13 UTC, DaveCTurner approved these changes
LGTM.

I haven't looked at `SnapshotsInProgress.Entry` in detail but if I had to guess I'd say that it's an oversight that we don't consider all the fields in the equality check.

2023-11-28 09:15 UTC, idegtiarenko commented
>I haven't looked at SnapshotsInProgress.Entry in detail but if I had to guess I'd say that it's an oversight that we don't consider all the fields in the equality check.

Possibly. However given this aspect and overall complexity of `SnapshotsInProgress.Entry` I would like to return to it separately

2023-12-11 12:39 UTC, merged