[DOCS] migrate ILM to DSL headings and TLDR
elastic/elasticsearch pull request #102068
Opened 2023-11-13 11:36 UTC by andreidan

This adds some headings and a TL;DR section to the
migration to DSL tutorial.

2023-11-13 11:36 UTC, elasticsearchmachine commented
Pinging @elastic/es-docs (Team:Docs)

2023-11-13 11:36 UTC, elasticsearchmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2023-11-22 14:06 UTC, tylerperk requested changes
Thanks for adding the summary and headers. Please also make "data stream lifecycle" always lowercase as discussed, and "Index Lifecycle Management" should always be capitalized.

2023-11-22 14:06 UTC, tylerperk commented on docs/reference/data-streams/lifecycle/tutorial-migrate-data-stream-from-ilm-to-dsl.asciidoc
> +1. Update the index template that's backing the data stream to configure <<index-lifecycle-prefer-ilm, prefer_ilm>>
```suggestion
1. Update the index template that's backing the data stream to set <<index-lifecycle-prefer-ilm, prefer_ilm>> 
```

2023-11-22 14:55 UTC, andreidan commented on docs/reference/data-streams/lifecycle/tutorial-migrate-data-stream-from-ilm-to-dsl.asciidoc
> +2. Configure the data stream lifecycle for the _existing_ data streams using
They're likely more data streams in the system. Why do you think we should be singular here?

2023-11-22 15:26 UTC, andreidan commented
@elasticmachine update branch

2023-11-23 11:18 UTC, gmarouli approved these changes
LGTM 🚀 , I love a good TLDR :) Thank you @andreidan

2023-11-23 11:18 UTC, gmarouli commented on docs/reference/data-streams/lifecycle/tutorial-migrate-data-stream-from-ilm-to-dsl.asciidoc
> +To migrate a data stream from {ilm-init} to  data stream lifecycle we'll have to execute
```suggestion
To migrate a data stream from {ilm-init} to data stream lifecycle we'll have to execute
```

2023-11-23 11:23 UTC, andreidan commented
>  I love a good TLDR

This was @tylerperk 's idea  🚀

2023-11-23 11:37 UTC, merged

2023-11-23 11:38 UTC, elasticsearchmachine commented
## 💔 Backport failed
| Status | Branch | Result |
|:------:|:------:|:------:|
| ❌ |  8.11  | Commit could not be cherrypicked due to conflicts |

You can use [sqren/backport](https://github.com/sqren/backport) to manually backport by running `backport --upstream elastic/elasticsearch --pr 102068`