Add asset-criticality index privelleges for kibana system user
elastic/elasticsearch pull request #102128
Opened 2023-11-14 09:40 UTC by nkhristinin

It introduces, the privileges for `.asset-criticality` indices for kibana-system user

2023-11-14 11:41 UTC, kc13greiner requested changes
Heya @nkhristinin!

For system indexes not owned by Kibana, the `kibana_system` user should only have `read` privileges. `.asset-*` falls under this case, but I see the `all` privilege is being added.

Can you provide any additional information why `kibana_system` needs `all` access to this index? I can then discuss it with the KB Sec team.

2023-11-14 11:59 UTC, nkhristinin commented
> Can you provide any additional information as to why `kibana_system` needs `all` access to this index? I can then discuss it with the KB Sec team.

Sure, some of the architecture for asset criticality you can find [here](https://github.com/elastic/security-team/issues/4208#issuecomment-1802713636)

But if summarised, the idea is the following:
- When the user clicks to install Risk Engine, the kibana user will create this index and mappings for asset criticality
- Writing/reading from this index is regulated by user permission

The idea is to have kibana user for that, because if we need to update mappings after release, Kibana should be able do that on Kibana start for examle

2023-11-15 00:25 UTC, kc13greiner commented
> When the user clicks to install Risk Engine, the kibana user will create this index and mappings for asset criticality

Would a less broad permission, like `create-index`, work since it only needs to create the index? 


> The idea is to have kibana user for that, because if we need to update mappings after release, Kibana should be able do that on Kibana start for example

It would be best not to proactively add too many permissions, if possible.
-  Could permissions for this case be added later on if needed?
- How likely is this scenario to happen?

2023-11-15 14:30 UTC, nkhristinin commented
Hey, thanks!

I updated permission, here is all cases when we need it:


Action | What should happen | User | priveleges
-- | -- | -- | --
Install Risk Engine for the first time | Create asset criticality index | Current User | create_index
Installed Risk Engine before, and upgraded Kibana version (or just shipped asset criticality for serverless) | Create asset criticality index on Kibana start | **Kibana user** | create_index
Installed a risk engine before with asset criticality, but we ship a new feature with new fields for asset criticality | Update mappings for asset criticality on Kibana start | **Kibana user** | manage
User want to see asset criticality in UI | call searcstrategy | Current User | read
User want to see change criticality in UI | call API | Current User | write
Risk engine tasks should use asset criticality for risk calculation | query asset criticality index | **Kibana user** | read

2023-11-16 13:08 UTC, kc13greiner commented
@nkhristinin ++ Thank you for the breakdown in the table; I think it is clear an exception can be made for this system index.

One last thing: `kibana_system` having access to the this index pattern should probably be documented somewhere so people know that the system user will have access to an index they've created if it matches the pattern.

Some examples of index patterns being documented:

- https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html
- https://www.elastic.co/guide/en/apm/guide/8.1/apm-data-streams.html
- https://www.elastic.co/guide/en/security/master/get-started-with-kspm.html

If you have a place already to add this, perfect! If not the first link is a good spot to list it.

2023-11-16 13:27 UTC, nkhristinin commented
@kc13greiner Thanks! 
I will make sure that we are put into some docs

2023-11-16 13:32 UTC, kc13greiner commented
@nkhristinin Im not familiar with where the ES docs source lives: are they in this repo & can be added to this PR? Or do you want to add a separate issue to create the docs and link it here?

2023-11-16 13:38 UTC, nkhristinin commented
> @nkhristinin I'm not familiar with where the ES docs source lives: are they in this repo & can be added to this PR? Or do you want to add a separate issue to create the docs and link it here?

We will have a separate doc issue for Asset Criticality,  which should include all info about privileges

2023-11-16 14:16 UTC, kc13greiner approved these changes
LGTM - Thanks for being so patient and working with the kb/sec team on this!

Please cc me on the docs issue/pr!

2023-11-16 14:18 UTC, elasticsearchmachine commented
Pinging @elastic/es-security (Team:Security)

2023-11-23 13:40 UTC, merged