ES|QL: Fix drop of renamed grouping
elastic/elasticsearch pull request #102282
Opened 2023-11-16 08:57 UTC by luigidellaquila

Fixes https://github.com/elastic/elasticsearch/issues/102121

Aggs groupings were not taken into account while merging aggs with projections, so they were wrongly removed in case of DROP

2023-11-16 08:58 UTC, elasticsearchmachine commented
Pinging @elastic/es-ql (Team:QL)

2023-11-16 08:58 UTC, elasticsearchmachine commented
Pinging @elastic/elasticsearch-esql (:Query Languages/ES|QL)

2023-11-16 08:58 UTC, elasticsearchmachine commented
Hi @luigidellaquila, I've created a changelog YAML for you.

2023-11-17 00:03 UTC, costin commented
Luigi, I've pushed a change to your branch that addresses the problem, that is dealing with aliases in grouping that have their definition declared in the aggregates, definition that gets removed when combining the projections.
The changes are required just in the CombineProject rule, not touching PruneColumns:

Essentially the bug can be seen in the transformation below:
```
Limit[500[INTEGER]]                                            = Limit[500[INTEGER]]
\_EsqlProject[[bar{r}#6]]                                      ! \_Aggregate[[foo{r}#4],[COUNT([2a][KEYWORD]) AS bar]]
  \_Aggregate[[foo{r}#4],[COUNT(*[KEYWORD]) AS bar, foo{r}#4]] !   \_Row[[1[INTEGER] AS a]]
    \_EsqlProject[[a{r}#2 AS foo]]                             ! 
      \_Row[[1[INTEGER] AS a]]  
```
The alias a to foo is incorporated into the grouping but then removed away so only the reference remains in the grouping causing issues.

After the fix the transformation looks as follows:
```
Limit[500[INTEGER]]                                            = Limit[500[INTEGER]]
\_EsqlProject[[bar{r}#6]]                                      ! \_Aggregate[[a{r}#2],[COUNT(*[KEYWORD]) AS bar]]
  \_Aggregate[[foo{r}#4],[COUNT(*[KEYWORD]) AS bar, foo{r}#4]] !   \_Row[[1[INTEGER] AS a]]
    \_EsqlProject[[a{r}#2 AS foo]]                             ! 
      \_Row[[1[INTEGER] AS a]]  
```
There is no need to keep the alias foo or its reference around, instead the source expression is used.

2023-11-17 00:04 UTC, costin requested changes
See my previous comment and the changed that I pushed.
This should address some of the issues seen in the other bugs.

This PR needs more tests, not just on the integration but also unit tests that try different variations and check the alias is properly replaced.

2023-11-17 00:05 UTC, costin approved these changes

2023-11-20 09:19 UTC, luigidellaquila commented
Thank you very much for looking into this @costin, I'm adding some tests and then merging with your changes

2023-11-20 11:43 UTC, merged

2023-11-20 11:47 UTC, elasticsearchmachine commented
## 💚 Backport successful
| Status | Branch | Result |
|:------:|:------:|:------:|
| ✅ |  [8.11](https://github.com/elastic/elasticsearch/pull/102375)  | [<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/102375">](https://github.com/elastic/elasticsearch/pull/102375) |