ESQL: add unit tests for conversion functions. Extend `TEXT` type support for them
elastic/elasticsearch pull request #102746
Opened 2023-11-29 11:42 UTC by bpintea

This adds the missing unit tests for the conversion functions.
It also extends the type support by adding the `TEXT` type to those functions that support `KEYWORD` already (which also simplifies the testing, actually). Some functions did have it, some didn't; they now all do.

The change also fixes two defects resulting from better testing coverage: `ToInteger` and `ToUnsignedLong` had some missing necessary exceptions declarations in the decorators for the evaluators.
It also updates `ToInteger`'s `fromDouble()` conversion to use a newly added utility, so that the failed conversions contain the right message (`out of [integer] range`, instead of the confusing `out of [long] range`).

Related: #102488, #102552.

2023-11-29 13:45 UTC, elasticsearchmachine commented
Pinging @elastic/es-ql (Team:QL)

2023-11-29 13:45 UTC, elasticsearchmachine commented
Pinging @elastic/elasticsearch-esql (:Query Languages/ES|QL)

2023-11-29 16:21 UTC, nik9000 requested changes

2023-11-30 11:05 UTC, bpintea commented on docs/reference/esql/functions/types/to_datetime.asciidoc
> +arg1 | result
Ah, yes, it makes sense! Will do it next.

2023-12-01 11:18 UTC, bpintea commented on docs/reference/esql/functions/types/to_datetime.asciidoc
> +arg1 | result
I'd updated these and merged in the geo work too, but not added the (missing) tests for those. Will do that in a subsequent PR, won't grow this one even larger.

2023-12-01 16:31 UTC, nik9000 approved these changes

2023-12-04 12:58 UTC, merged