Create a DSL health indicator as part of the health API
elastic/elasticsearch pull request #103130
Opened 2023-12-07 14:19 UTC by andreidan

This adds a health indicator named `dsl` that will detect
data stream backing indices that cannot make progress
(stagnating) due to repeatedly error-ing in their lifecycle
execution. 

The output of the indicator looks like this:
```
"dsl" : {
    "status" : "yellow",
    "symptom" : "2 backing indices have repeatedly encountered errors whilst trying to advance in its lifecycle",
    "details" : {
      "stagnating_backing_indices_count" : 2,
      "stagnating_backing_indices" : [
        {
          "index_name" : ".ds-metrics-foo-2023.12.07-000002",
          "first_occurrence_timestamp" : 1701951305340,
          "retry_count" : 4
        },
        {
          "index_name" : ".ds-metrics-foo-2023.12.07-000001",
          "first_occurrence_timestamp" : 1701951305340,
          "retry_count" : 4
        }
      ],
      "total_backing_indices_in_error" : 2
    },
    "impacts" : [
      {
        "id" : "elasticsearch:health:dsl:impact:stagnating_backing_index",
        "severity" : 3,
        "description" : "Data streams backing indices cannot make progress in their lifecycle. The performance and stability of the indices and/or the cluster could be impacted.",
        "impact_areas" : [
          "deployment_management"
        ]
      }
    ],
    "diagnosis" : [
      {
        "id" : "elasticsearch:health:dsl:diagnosis:stagnating_dsl_backing_index",
        "cause" : "Some backing indices are repeatedly encountering errors in their lifecycle execution.",
        "action" : "Check the current status of the affected indices using the [GET /<affected_index_name>/_lifecycle/explain] API. Please replace the <affected_index_name> in the API with the actual index name (or the data stream name for a wider overview).",
        "help_url" : "https://ela.st/dsl-explain",
        "affected_resources" : {
          "indices" : [
            ".ds-metrics-foo-2023.12.07-000002",
            ".ds-metrics-foo-2023.12.07-000001"
          ]
        }
      }
    ]
  }
```

Documentation will follow in a subsequent PR.

2023-12-07 14:20 UTC, elasticsearchmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2023-12-07 14:20 UTC, elasticsearchmachine commented
Hi @andreidan, I've created a changelog YAML for you.

2023-12-08 09:07 UTC, gmarouli requested changes
Thank you for working on this @andreidan , really looking forward to see it released! I have some small comments, other than them, it's in a really good shape!

2023-12-08 09:07 UTC, gmarouli commented on modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java
> +            if (masterIsStableIndicator.get(0).status() == HealthStatus.GREEN) {
Same here

2023-12-08 09:07 UTC, gmarouli commented on modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java
> +            if (masterIsStableIndicator.get(0).status() == HealthStatus.GREEN) {
Assuming you agree :p, same here.

2023-12-08 11:39 UTC, andreidan commented
@elasticmachine run elasticsearch-ci/8.11.2 / bwc-snapshots

2023-12-08 11:40 UTC, andreidan commented
@elasticmachine update branch

2023-12-08 11:59 UTC, gmarouli approved these changes
LGTM, just one leftover `yello;w` 🚀 Can't wait to see it live!

2023-12-08 11:59 UTC, gmarouli commented on modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java
> +                // the dsl indicator should turn the overall status yell;ow
I think this one was missed :)

2023-12-08 14:53 UTC, merged