Add ES|QL async delete API
elastic/elasticsearch pull request #103628
Opened 2023-12-20 15:09 UTC by ChrisHegarty

This commit adds the ES|QL async delete API, to cancel running ES|QL queries and/or remove stored results.

relates: #102455

2023-12-20 15:09 UTC, elasticsearchmachine commented
Pinging @elastic/es-ql (Team:QL)

2023-12-20 15:09 UTC, elasticsearchmachine commented
Pinging @elastic/elasticsearch-esql (:Query Languages/ES|QL)

2023-12-20 15:10 UTC, elasticsearchmachine commented
Hi @ChrisHegarty, I've created a changelog YAML for you.

2023-12-20 16:08 UTC, ChrisHegarty commented
@elasticmachine update branch

2023-12-21 15:35 UTC, ChrisHegarty commented
@elasticmachine update branch

2023-12-21 15:37 UTC, ChrisHegarty commented on x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/AbstractPausableIntegTestCase.java
> +public abstract class AbstractPausableIntegTestCase extends AbstractEsqlIntegTestCase {
This is for the most part just moved out of EsqlActionTaskIT so that it can be used in async IT tests too.

2023-12-21 15:40 UTC, ChrisHegarty commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/async/AsyncResultsService.java
> +                    refCounted.decRef();
This is an issue from async get, not from delete, but fixing here as the new tests run into it.

2023-12-22 05:29 UTC, dnhatn requested changes
Great work. Thanks @ChrisHegarty.

2023-12-22 05:29 UTC, dnhatn approved these changes

2023-12-22 05:35 UTC, dnhatn commented
Sorry, I accidentally pressed the `request changes` button. This LGTM.

2023-12-22 07:08 UTC, ChrisHegarty commented
@elasticmachine update branch

2023-12-22 09:47 UTC, bpintea approved these changes
nice!

2023-12-22 13:49 UTC, merged