ESQL: Support loading points from source into WKB blocks
elastic/elasticsearch pull request #104269
Opened 2024-01-11 15:17 UTC by iverase

Similarly to https://github.com/elastic/elasticsearch/pull/103698, this PR adds support for reading geo_shape and shape fields into wkb blocks so they can use top project the data to the result of a ES|QL query.

One of the points for discussion in this PR is the naming use to the ES|QL fields where geo_shape has been renamed to geography and shape has been renamed to geometry, to follow more closely industry standards. Although this is debatable.

Note to the reviewer: There is a limitation on csv test because they cannot deal with WKT,

2024-01-11 15:18 UTC, elasticsearchmachine commented
Hi @iverase, I've created a changelog YAML for you.

2024-01-11 15:18 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytics-geo (Team:Analytics)

2024-01-15 15:51 UTC, craigtaverner requested changes
This looks really great. Just need to add ToGeometryTests and ToGeographyTests.

2024-01-15 15:51 UTC, craigtaverner commented on docs/changelog/104269.yaml
> +summary: "ESQL: Support loading points from source into WKB blocks"
Don't you mean shapes?

2024-01-15 15:51 UTC, craigtaverner commented on docs/changelog/104269.yaml
> +area: "Geo"
All previous PRs I created used area "ES|QL", but perhaps if most future Geo work will be in ESQL, we should use area "Geo"?

2024-01-15 15:51 UTC, craigtaverner commented on server/src/main/java/org/elasticsearch/index/mapper/AbstractPointGeometryFieldMapper.java
> +        protected Object nullValueAsSource(T nullValue) {
I think we can now delete AbstractPointFieldType, as I only created that class to implement the blockLoader for points only, and disable it for shapes. Now that it exists for shapes too, we can have all code there, I assume.

2024-01-15 15:51 UTC, craigtaverner commented on server/src/main/java/org/elasticsearch/index/mapper/AbstractPointGeometryFieldMapper.java
> +        protected Object nullValueAsSource(T nullValue) {
OK, I see now your comment that we do not support null-values for shapes. So that is one reason to keep this class.

2024-01-15 15:51 UTC, craigtaverner commented on x-pack/plugin/esql/qa/testFixtures/src/main/resources/spatial_shapes.csv-spec
> +convertCartesianFromStringArray#[skip:-8.12.99, reason:spatial type geography only added in 8.13]
Perhaps you meant to type Geometry instead of Cartesian?

2024-01-15 15:51 UTC, craigtaverner commented on x-pack/plugin/esql/qa/testFixtures/src/main/resources/spatial_shapes.csv-spec
> +| WHERE pt == to_geography("POINT(42.97109630194 14.7552534413725)")
Would be nice to have equality and inequality tests on non-points too.

2024-01-15 15:51 UTC, craigtaverner commented on x-pack/plugin/esql/qa/testFixtures/src/main/resources/spatial_shapes.csv-spec
> +#simpleLoad#[skip:-8.12.99, reason:spatial type geography  only added in 8.13]
We could load the airports file here (but with header changed to geo_shape), and then add another test with polygons later.

2024-01-15 15:51 UTC, craigtaverner commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/convert/ToGeography.java
> +public class ToGeography extends AbstractConvertFunction {
I do not see `ToGeographyTests`

2024-01-15 15:51 UTC, craigtaverner commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/convert/ToGeometry.java
> +public class ToGeometry extends AbstractConvertFunction {
I do not see `ToGeometryTests`

2024-01-15 15:51 UTC, craigtaverner commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java
> +     * This specifically excludes spatial data types, which are not themselves sortable .
```suggestion
     * This specifically excludes spatial data types, which are not themselves sortable.
```

2024-01-15 15:51 UTC, craigtaverner commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java
> +        // TODO: Spatial types can be read from source into BYTES_REF, or read from doc-values
Perhaps this comment can be removed, as it was a placeholder for me to re-visit this code with the doc-values work, but that PR took another direction.

2024-01-15 15:51 UTC, craigtaverner commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java
> +        // TODO: Spatial types can be read from source into BYTES_REF, or read from doc-values
```suggestion
```

2024-01-15 15:51 UTC, craigtaverner commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java
> +        if (dataType == EsqlDataTypes.GEO_POINT
I guess we can also just use `EsqlDataTypes.isSpatial(dataType)` here too?

2024-01-15 15:51 UTC, craigtaverner commented on x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerTests.java
> +        var errorMsg = "Cannot use field [unsupported] with unsupported type [ip_range]";
Slightly awkward that the unsupported field is called `unsupported`, but on the other hand perhaps this field will never be supported, and this is perfect. 🤷

2024-01-15 15:51 UTC, craigtaverner commented on x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerTests.java
> -        verifyUnsupported("from test | eval to_string(shape)", "line 1:28: Cannot use field [shape] with unsupported type [geo_shape]");
I presume we could use `ip_range` here too, as in the other tests?

2024-01-16 17:20 UTC, craigtaverner approved these changes
LGTM

2024-01-16 17:30 UTC, craigtaverner reviewed
I noticed that you have added `types/to_geometry.asciidoc` but not the parent `to_geometry.asciidoc` that should include that, nor any additions to the function list. Am I missing something, or are the docs incomplete?

2024-01-16 17:31 UTC, iverase commented
That was generated, I did not add it.

2024-01-17 13:19 UTC, nik9000 commented
> I noticed that you have added `types/to_geometry.asciidoc` but not the parent `to_geometry.asciidoc` that should include that, nor any additions to the function list. Am I missing something, or are the docs incomplete?

If the "parent" asciidoc file is missing then the docs are incomplete. But that doesn't have a block a huge PR.

2024-01-17 13:22 UTC, nik9000 approved these changes

2024-01-17 13:22 UTC, nik9000 commented on x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java
>      );
:heart:

2024-01-17 13:55 UTC, merged