Fixes for APMAgentSettings
elastic/elasticsearch pull request #104324
Opened 2024-01-12 16:05 UTC by mosche

This contains 2 fixes for potential issues in APMAgentSettings:

1) The allow-list check was operating on the last segment extracted from the qualified setting key:
     ```java
     String[] parts = qualifiedKey.split("\\.");
     String key = parts[parts.length - 1];
     ```
     This way potential garbage settings passed the whitelist check as long as the last segment looked valid.
     This is fixed using a more robust extraction of the relative key:
     ```java
     String key = Strings.split(qualifiedKey, APM_AGENT_SETTING_PREFIX)[1];
     ```

2) Both tracing and metrics require `recording` to be enabled to work. However, if enabling tracing without enabling metrics, `recording` is not enabled. Similarly, if disabling metrics, `recording` may only be disabled if tracing is not enabled.

2024-01-12 16:06 UTC, elasticsearchmachine commented
Pinging @elastic/es-core-infra (Team:Core/Infra)

2024-01-12 16:16 UTC, mosche commented on modules/apm/src/main/java/org/elasticsearch/telemetry/apm/internal/APMAgentSettings.java
> -        this.setAgentSetting("recording", Boolean.toString(APM_ENABLED_SETTING.get(settings)));
This looks also problematic, `recording` was previously only enabled if tracing was when initially synching the agent settings.

That makes me wonder if this is needed at all? It looks like the update consumers are triggering at startup which would then typically enable `recording` (assuming metrics are generally enabled).

2024-01-12 16:42 UTC, stu-elastic commented
> String key = Strings.split(qualifiedKey, APM_AGENT_SETTING_PREFIX)[1];

This is not going to work when there are two valid prefixes.  The old apm prefix and the new telemetry prefix

2024-01-12 17:45 UTC, mosche commented
Yes, when adding the new prefix, we'd have to try splitting on the 2nd one if the 1st split returns `null`.

2024-01-17 15:03 UTC, pgomulka approved these changes
LGTM, left one question but it can be followed up if necessary separately

2024-01-17 15:03 UTC, pgomulka commented on modules/apm/src/main/java/org/elasticsearch/telemetry/apm/internal/APMAgentSettings.java
> +                // TODO figure out why those settings are kept, these should be reformatted / removed by now
I wonder what 'by now' in this todo means?
do you think we can clarify this todo?

2024-01-17 15:05 UTC, pgomulka commented
> String key = Strings.split(qualifiedKey, APM_AGENT_SETTING_PREFIX)[1];

> This is not going to work when there are two valid prefixes. The old apm prefix and the new telemetry prefix


 this probably we have to wait for https://github.com/elastic/elasticsearch/pull/104345 before merging this pr, we might need to update it. I missed this comment before approving.

2024-01-17 15:06 UTC, pgomulka requested changes
String key = Strings.split(qualifiedKey, APM_AGENT_SETTING_PREFIX)[1];

This is not going to work when there are two valid prefixes. The old apm prefix and the new telemetry prefix

this probably we have to wait for https://github.com/elastic/elasticsearch/pull/104345 before merging this pr, we might need to update it. I missed this comment before approving.

2024-01-17 15:10 UTC, mosche commented
Yes, I'll wait for #104345 👍

2024-01-30 10:31 UTC, mosche commented
I've updated this to only correctly set `recording`. The other part was already fixed in https://github.com/elastic/elasticsearch/pull/104345.

2024-01-30 14:25 UTC, stu-elastic approved these changes
LGTM with randomness removed.

2024-01-30 14:25 UTC, stu-elastic commented on modules/apm/src/test/java/org/elasticsearch/telemetry/apm/internal/APMAgentSettingsTests.java
> +        boolean metricsEnabled = randomBoolean();
No need for randomness.  We can test both cases.

2024-01-30 14:25 UTC, stu-elastic commented on modules/apm/src/test/java/org/elasticsearch/telemetry/apm/internal/APMAgentSettingsTests.java
> +        boolean tracingEnabled = randomBoolean();
No need for randomness.  We can test both cases.

2024-01-30 14:25 UTC, stu-elastic commented on modules/apm/src/test/java/org/elasticsearch/telemetry/apm/internal/APMAgentSettingsTests.java
> +        boolean metricsEnabled = randomBoolean();
No need for randomness.  We can test both cases.

2024-01-30 14:25 UTC, stu-elastic commented on modules/apm/src/test/java/org/elasticsearch/telemetry/apm/internal/APMAgentSettingsTests.java
> +        boolean tracingEnabled = randomBoolean();
No need for randomness.  We can test both cases.

2024-01-30 14:38 UTC, pgomulka approved these changes
LGTM, 
agree with the comments on not using randomisation

2024-01-30 16:29 UTC, merged