Set read timeout for fetching IMDSv2 token
elastic/elasticsearch pull request #104407
Opened 2024-01-16 13:30 UTC by arteam

Resubmit of #104397 with the fixed signature of setting the environment variable in the build

```
Use the timeout set by AWS_METADATA_SERVICE_TIMEOUT environment variable both as connect and read timeout analogous to the AWS SDK.

See https://docs.aws.amazon.com/sdkref/latest/guide/feature-ec2-instance-metadata.html
```

Resolves #104244

2024-01-16 13:31 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2024-01-16 13:31 UTC, elasticsearchmachine commented
Hi @arteam, I've created a changelog YAML for you.

2024-01-16 16:41 UTC, kingherc commented on plugins/discovery-ec2/build.gradle
> +    environment 'AWS_METADATA_SERVICE_TIMEOUT', '1'
Is there a reason for the random boolean? I thought you wanted to make the test quick in CI and that's why we set the default to 1 here.

2024-01-16 18:31 UTC, mark-vieira requested changes

2024-01-16 19:26 UTC, arteam commented
@mark-vieira That makes sense, I've removed the randomness from the build, so we will just be testing the client the default timeout of 2s.

2024-01-16 19:27 UTC, mark-vieira approved these changes

2024-01-16 23:50 UTC, ywangd commented on plugins/discovery-ec2/build.gradle
> +    environment 'AWS_METADATA_SERVICE_TIMEOUT', '1'
The code computes the timeout value based on the environment variable or falls back to a hardcoded default if the environment variable does not exist. Ideally we should be testing this behaviour as well. I see introducing this with Gradle build file is not prefered. The other alternative is dependency injection like how it is done for `CustomWebIdentityTokenCredentialsProvider`
https://github.com/elastic/elasticsearch/blob/c8fc737846e927f3caa134df395f0f9d71af66f4/modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java#L332-L335

But that requires some cascading refactoring and may _not_ be worth the effort. Hence I am ok with just testing the default behaviour in this PR.

2024-01-16 23:50 UTC, ywangd approved these changes
LGTM

2024-01-17 09:49 UTC, kingherc approved these changes
LGTM

2024-01-17 10:08 UTC, merged