Make URLHttpClient load it's http client dependency lazily
elastic/elasticsearch pull request #104590
Opened 2024-01-21 01:37 UTC by original-brownbear

No need to load the http client classes eagerly here when most deployments don't use the URL repository in the first place. Moves the overhead for having the URL repository code around but unused from 579kb to 44kb on my workstation (x86).

2024-01-21 01:38 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2024-01-21 10:07 UTC, DaveCTurner requested changes
Makes sense, but we already have the mutability we need in `org.elasticsearch.plugin.repository.url.URLRepositoryPlugin#httpClientFactory`, could we have the laziness at that level instead too?

2024-01-21 12:05 UTC, original-brownbear commented
Fair point :) How about this? No need for the whole component thing even, we can just create this thing on demand in the plugin, saving us another class to load :P

2024-01-22 09:47 UTC, DaveCTurner requested changes
If we don't declare it as a component then we don't close it on shutdown, which seems at least impolite (if only for tests)

2024-01-22 12:17 UTC, original-brownbear commented
@DaveCTurner but the plugins are closed on `Node.close()` anyway and we'll close there? Why do we need the component?

2024-01-22 12:49 UTC, DaveCTurner approved these changes
Oh sorry I missed that we also close this in `#close()`. LGTM then

2024-01-22 12:50 UTC, original-brownbear commented
Thanks David!

2024-01-22 12:50 UTC, merged