Move doc-values classes needed by ST_INTERSECTS to server
elastic/elasticsearch pull request #104980
Opened 2024-01-31 15:18 UTC by craigtaverner

These classes are needed by ESQL spatial queries, and are not licensed in a way that prevents this move. Since they depend on lucene it is not possible to move them to a library. Instead they are moved to be co-located with the GeoPoint doc-values classes that already exist in server.

2024-01-31 15:19 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytical-engine (Team:Analytics)

2024-01-31 16:25 UTC, iverase requested changes
Can we please move the under a package in ~~`org.apache.lucene`~~  `org.elasticsearch.lucene`? They are really implementing some lucene functionality.

2024-02-05 08:09 UTC, iverase commented on x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/fielddata/Tile2DVisitorTests.java
> +    private static class TestCoordinateEncoder implements CoordinateEncoder {
nice!

2024-02-05 08:09 UTC, iverase approved these changes
lgtm

2024-02-05 10:05 UTC, craigtaverner commented
@elasticsearchmachine run elasticsearch-ci/part-1

2024-02-07 14:00 UTC, merged