Add option for Append Processor to skip/allow empty values
elastic/elasticsearch pull request #105718
Opened 2024-02-22 03:48 UTC by limotova

If one is using templates to generate values, this option can be helpful to avoid adding values that resolve into empty strings

Fixes #104813

2024-03-08 18:18 UTC, joegallo requested changes
I'd like to have this mirror the `set` processor's `ignore_empty_value` option, rather than creating a new option name with no precedent -- it's functionally the same as that option, right (albeit with the opposite sense)?

2024-06-19 07:53 UTC, romulets commented
This feature is actually pretty useful. I'm my use-case, I'm appending a lot of fields. To keep checking if they are not null on context is pretty repetitive. Right now we have a painless script that removes all empty values. But would be awesome to have this out of the box.

2025-01-30 17:05 UTC, elasticsearchmachine commented
Hi @limotova, I've created a changelog YAML for you.

2025-09-05 14:34 UTC, joegallo commented
I'm resurrecting this PR and finally getting around to merging it (it is a terrible shame that I've let it sit here for so long, sorry for that!). I merged `main` in, which was a bit of a task because of the great amount of time that has passed. In the course of that I dropped the docs changes, so I'll need to resurrect those in a separate commit.

2025-09-05 15:01 UTC, joegallo commented
Oops, my one commit comment got truncated because I wasn't careful about syntax, that was intended to read:

> Rewrite another setFieldValue arity, too
>
> This one is a bit trickier, so I've lampshaded the surprising part
> with a comment, and also there's a newly added test on main via 
> #134217

2025-09-05 18:58 UTC, nik9000 commented
@limotova, the last failure looked related to some of your other work:
```
java.lang.AssertionError: 
Data mismatch:
row 0 column 0:a list containing
row 0 column 0:0: expected "0.22106409327010415" but was "0.2210640932701042"
row 1 column 0:a list containing
row 1 column 0:0: expected "0.22797190865484734" but was "0.2279719086548474"
row 3 column 0:a list containing
row 3 column 0:0: expected "0.14656141004227627" but was "0.1465614100422763"
Actual:
STD_DEV(height):double | languages:integer
0.2210640932701042     | 1
0.2279719086548474     | 2
0.18893070075713295    | 3
0.1465614100422763     | 4
0.17733860152780256    | 5
0.2486543786061287     | null
```
-----
edit by @joegallo: https://gradle-enterprise.elastic.co/s/dgldbbjtt4tk4/tests/overview here's a failure link for that one.

2025-09-05 19:06 UTC, nik9000 commented
I opened an issue: https://github.com/elastic/elasticsearch/issues/134244

2025-09-09 21:11 UTC, joegallo commented
I merged `main` into this PR again, so that brings #134217 and #134319 in. They all play nicely together on my machine but we'll see what CI has to say about it.

2025-09-09 21:15 UTC, joegallo commented
A todo list for myself of what I'd still like to see here:
- [x] I need to resurrect the docs changes in markdown rather than asciidoc, including the example(s) I promised earlier in https://github.com/elastic/elasticsearch/pull/132003#discussion_r2323497632
- [x] I need to add a test only feature, and also some rest tests
- [x] I think it makes sense to add more test coverage of `ignore_empty_values` with `copy_from` (that could probably be done with the previously mentioned rest tests)

2025-09-11 07:20 UTC, limotova reviewed
I can't approve my own PR haha but the changes look reasonable to me, thank you!

2025-09-30 02:43 UTC, joegallo approved these changes

2025-09-30 04:01 UTC, merged