fix check preTags and postTags with empty argument
elastic/elasticsearch pull request #106396
Opened 2024-03-18 03:58 UTC by white-cc

fix: https://github.com/elastic/elasticsearch/issues/69009
`"reason": {
          "type": "illegal_argument_exception",
          "reason": "preTags or postTags must not be empty"
        }`

instead of  ArrayOutOfBoundsException

2024-03-18 18:15 UTC, elasticsearchmachine commented
Pinging @elastic/es-search (Team:Search)

2024-03-18 18:35 UTC, mayya-sharipova requested changes
@white-cc Thanks for your contributions. This should be fixed for all highlighters, not only for  the`plain` highlighter.

I suggest to add the check in [AbstractHighlighterBuilder](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/AbstractHighlighterBuilder.java#L643) where there is already another check. 

Also please add rest tests into `https://github.com/elastic/elasticsearch/tree/main/rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/search.highlight` for all types of highlighters. Here is the guidance about [YAML rest tests](https://github.com/elastic/elasticsearch/blob/main/TESTING.asciidoc#testing-the-rest-layer).

2024-03-19 10:44 UTC, mayya-sharipova commented on rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/search.highlight/issue69009.yml
> +setup:
Let's add this setup section which means to skip the test for nodes with version < 8.14

setup:
  - skip:
      version: ' - 8.13.99'
      reason: 'check of preTags and postTags params for empty values was added in   8.14'

2024-03-19 10:45 UTC, mayya-sharipova commented
@elasticsearchmachine test this please

2024-03-19 10:54 UTC, mayya-sharipova commented on docs/changelog/106396.yaml
> +area: search
area: Highlighting

2024-03-20 17:29 UTC, mayya-sharipova commented
@elasticsearchmachine Test this please

2024-03-20 18:07 UTC, mayya-sharipova commented
@white-cc Thanks for your work so far, looks great. 

Are you able to access CI build failures to check and fix tests that are failing:

```

REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.index.query.InnerHitBuilderTests.testFromAndToXContent" -Dtests.seed=99449CFAF2B54821 -Dtests.locale=sr-Latn-BA -Dtests.timezone=America/Indiana/Indianapolis -Druntime.java=21
--
  |  
  | org.elasticsearch.index.query.InnerHitBuilderTests > testFromAndToXContent FAILED
  | org.elasticsearch.xcontent.XContentParseException: [1:459] [inner_hits] failed to parse field [highlight]
  | at __randomizedtesting.SeedInfo.seed([99449CFAF2B54821:DA77E6EBAE3E418C]:0)
  | at app//org.elasticsearch.xcontent.ObjectParser.throwFailedToParse(ObjectParser.java:616)
  | at app//org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:611)
  | at app//org.elasticsearch.xcontent.ObjectParser.parseSub(ObjectParser.java:629)
  | at app//org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:315)
  | at app//org.elasticsearch.index.query.InnerHitBuilder.fromXContent(InnerHitBuilder.java:597)
  | at app//org.elasticsearch.index.query.InnerHitBuilderTests.testFromAndToXContent(InnerHitBuilderTests.java:119)
  |  
  | Caused by:
  | org.elasticsearch.xcontent.XContentParseException: [1:459] [highlight] failed to parse field [fields]
  | at app//org.elasticsearch.xcontent.ObjectParser.throwFailedToParse(ObjectParser.java:616)
  | at app//org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:611)
  | at app//org.elasticsearch.xcontent.ObjectParser.parseSub(ObjectParser.java:629)
  | at app//org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:315)
  | at app//org.elasticsearch.search.fetch.subphase.highlight.AbstractHighlighterBuilder.lambda$setupParser$4(AbstractHighlighterBuilder.java:642)
  | at app//org.elasticsearch.search.fetch.subphase.highlight.HighlightBuilder.fromXContent(HighlightBuilder.java:266)
  | at app//org.elasticsearch.index.query.InnerHitBuilder.lambda$static$6(InnerHitBuilder.java:107)
  | at app//org.elasticsearch.xcontent.ObjectParser.lambda$declareField$10(ObjectParser.java:431)
  | at app//org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:609)
  | ... 4 more
  |  
  | Caused by:
  | org.elasticsearch.xcontent.XContentParseException: [1:459] [fields] failed to parse field [0_sYNHwBMlvn]
  | at app//org.elasticsearch.xcontent.ObjectParser.rethrowFieldParseFailure(ObjectParser.java:554)
  | at app//org.elasticsearch.xcontent.ObjectParser.lambda$declareNamedObjects$14(ObjectParser.java:494)
  | at app//org.elasticsearch.xcontent.ObjectParser.lambda$declareNamedObjects$15(ObjectParser.java:505)
  | at app//org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:609)
  | ... 11 more
  |  
  | Caused by:
  | org.elasticsearch.common.ParsingException: pre_tags or post_tags must not be empty


````

2024-03-21 02:44 UTC, white-cc commented
> @white-cc Thanks for your work so far, looks great.
> 
> Are you able to access CI build failures to check and fix tests that are failing:
> 
> ```
> 
> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.index.query.InnerHitBuilderTests.testFromAndToXContent" -Dtests.seed=99449CFAF2B54821 -Dtests.locale=sr-Latn-BA -Dtests.timezone=America/Indiana/Indianapolis -Druntime.java=21
> --
>   |  
>   | org.elasticsearch.index.query.InnerHitBuilderTests > testFromAndToXContent FAILED
>   | org.elasticsearch.xcontent.XContentParseException: [1:459] [inner_hits] failed to parse field [highlight]
>   | at __randomizedtesting.SeedInfo.seed([99449CFAF2B54821:DA77E6EBAE3E418C]:0)
>   | at app//org.elasticsearch.xcontent.ObjectParser.throwFailedToParse(ObjectParser.java:616)
>   | at app//org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:611)
>   | at app//org.elasticsearch.xcontent.ObjectParser.parseSub(ObjectParser.java:629)
>   | at app//org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:315)
>   | at app//org.elasticsearch.index.query.InnerHitBuilder.fromXContent(InnerHitBuilder.java:597)
>   | at app//org.elasticsearch.index.query.InnerHitBuilderTests.testFromAndToXContent(InnerHitBuilderTests.java:119)
>   |  
>   | Caused by:
>   | org.elasticsearch.xcontent.XContentParseException: [1:459] [highlight] failed to parse field [fields]
>   | at app//org.elasticsearch.xcontent.ObjectParser.throwFailedToParse(ObjectParser.java:616)
>   | at app//org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:611)
>   | at app//org.elasticsearch.xcontent.ObjectParser.parseSub(ObjectParser.java:629)
>   | at app//org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:315)
>   | at app//org.elasticsearch.search.fetch.subphase.highlight.AbstractHighlighterBuilder.lambda$setupParser$4(AbstractHighlighterBuilder.java:642)
>   | at app//org.elasticsearch.search.fetch.subphase.highlight.HighlightBuilder.fromXContent(HighlightBuilder.java:266)
>   | at app//org.elasticsearch.index.query.InnerHitBuilder.lambda$static$6(InnerHitBuilder.java:107)
>   | at app//org.elasticsearch.xcontent.ObjectParser.lambda$declareField$10(ObjectParser.java:431)
>   | at app//org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:609)
>   | ... 4 more
>   |  
>   | Caused by:
>   | org.elasticsearch.xcontent.XContentParseException: [1:459] [fields] failed to parse field [0_sYNHwBMlvn]
>   | at app//org.elasticsearch.xcontent.ObjectParser.rethrowFieldParseFailure(ObjectParser.java:554)
>   | at app//org.elasticsearch.xcontent.ObjectParser.lambda$declareNamedObjects$14(ObjectParser.java:494)
>   | at app//org.elasticsearch.xcontent.ObjectParser.lambda$declareNamedObjects$15(ObjectParser.java:505)
>   | at app//org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:609)
>   | ... 11 more
>   |  
>   | Caused by:
>   | org.elasticsearch.common.ParsingException: pre_tags or post_tags must not be empty
> ```

Yes, I tested it locally and found the exception. pre_tags is empty in this case, but it may case "Index 0 out of bounds for length 0" in my test. I will try to modify code to avoid  pre_tags empty in this uint test.
![1](https://github.com/elastic/elasticsearch/assets/55196618/7e611bb0-47e5-4ef5-b25f-1777a6ea3437)
![image](https://github.com/elastic/elasticsearch/assets/55196618/eef2a106-60c7-46ae-a515-1b0b2441591b)

2024-03-21 15:06 UTC, mayya-sharipova commented
@elasticsearchmachine test this please

2024-03-21 18:30 UTC, mayya-sharipova approved these changes
@white-cc Thanks for your contribution! This PR looks good to me. Merging for 8.14 release.

2024-03-21 18:31 UTC, merged