Fix rolling over aliases to data streams
elastic/elasticsearch pull request #106451
Opened 2024-03-19 01:09 UTC by limotova

Currently trying to rollover data streams via aliases fails. This commit fixes that by applying the rollover on the data stream directly.

Fixes #106137

2024-03-19 07:32 UTC, breskeby commented on server/build.gradle
> +  testImplementation project(path: ':modules:data-streams')
```suggestion
  testImplementation project(':modules:data-streams')
```

2024-03-19 07:33 UTC, breskeby approved these changes
minor hint on build script syntax.

2024-03-19 22:32 UTC, elasticsearchmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2024-03-22 17:45 UTC, jbaiera requested changes
Heya @limotova, thanks for putting up a fix for this!

We discussed this issue recently with the rest of the team and we think that maybe a better option here is to simply reject the request to do the rollover. Here's our thinking:

Rolling over a concrete index is not supported, but rolling over an alias that points to multiple concrete indices is since the alias is acting like a list of indices which can be extended.

Data streams can be rolled over, because like the alias case above, a data stream is essentially acting as a list of indices as well.

Since a data stream alias may have multiple data streams, it's not entirely clear semantically what the rollover should be doing. My gut check was aligned with yours at first: Just roll over the write data stream for the alias - but considering the original alias case above, one could argue that creating a new data stream and adding it to the alias is also somewhat of a valid interpretation.

Considering this, I think the best course of action is to simply reject the request with an error more friendly than the null pointer today. This would give us a table of operations like so:

|               | Index                 | Data Stream    |
---------|----------------|---------------|
| Singular | Not supported | Supported       |
| Aliased   | Supported       | Not supported |

2024-03-23 08:24 UTC, limotova commented
Hi @jbaiera, that sounds good, I'll update the PR shortly..!

2024-03-25 04:00 UTC, limotova commented
I think it would make the most sense to open a separate PR since the approach/resulting code is so different, so closing this one

2024-03-25 04:00 UTC, closed without merging