Fork when handling remote field-caps responses
elastic/elasticsearch pull request #107370
Opened 2024-04-11 16:24 UTC by dnhatn

2024-04-11 16:52 UTC, elasticsearchmachine commented
Hi @dnhatn, I've created a changelog YAML for you.

2024-04-11 16:53 UTC, elasticsearchmachine commented
Pinging @elastic/es-search (Team:Search)

2024-04-11 16:59 UTC, DaveCTurner requested changes
I think we already dispatch to the right executor on a regular response, so this change will make us fork twice. But I can see that we might not dispatch to the right executor on a connection error. That seems like something we should fix in the remote-cluster client rather than here.

2024-04-11 17:55 UTC, dnhatn commented
> I think we already dispatch to the right executor on a regular response, so this change will make us fork twice. But I can see that we might not dispatch to the right executor on a connection error.

@DaveCTurner Thanks for looking. We use the generic threadpool for notifying remote connection errors. I pushed https://github.com/elastic/elasticsearch/pull/107370/commits/2e4c59ac1e0b4a0daede6e80a75a5e18ddc60283.

2024-04-11 17:56 UTC, DaveCTurner requested changes
2e4c59ac1e0b4a0daede6e80a75a5e18ddc60283 is still going to double-fork on most exceptions (see e.g. `org.elasticsearch.transport.TransportService#getInternalSendExceptionExecutor`). Let's just fork the cases that don't already fork.

2024-04-11 18:00 UTC, DaveCTurner reviewed
Oh wait sorry I misread it, I see we're only forking exceptions from `maybeEnsureConnected`. Hmm this still isn't quite right tho, there's also `org.elasticsearch.transport.TransportService#handleSendRequestException`.

2024-04-12 07:11 UTC, DaveCTurner reviewed
Hmm I'm not too happy about introducing an `ActionListener#wrap` here (double-completion bugs abound) nor really about replicating most of that exception-dispatching `ActionRunnable` in three places. I think I'd like to spend a little more time on coming up with a better solution here but unfortunately I don't have that time right now.

Could you keep this open as a placeholder for that work, and/or open a bug report issue for me to follow up on, and go back to the original workaround of just handling this in the (exception path of) the field caps action?

2024-04-12 17:00 UTC, dnhatn commented
Thanks, David. I've narrowed down this PR to just field-caps. This should unblock our work in ES|QL. I'll also open an issue for the transport service. Could you give it another look?

2024-04-12 17:06 UTC, DaveCTurner approved these changes
LGTM (one nit)

2024-04-12 17:06 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java
> +                    // This fork is a workaround to ensure that the merging of field-caps always occurs on the search_coordinator.
nit: could you link from this comment to the issue that tracks the bug around which we're working?

2024-04-12 21:24 UTC, merged