ESQL: Introduce a casting operator, `::`
elastic/elasticsearch pull request #107409
Opened 2024-04-12 09:59 UTC by bpintea

This adds support for an "inline" casting operator, `::`. The operator can be used with literals, fields and functions.

The operator delegates to one the existing `to_xxx()` conversion functions, so only the types for which such a converter exist can be cast to with the new opeator.

For convenience, a list of type name aliases are introduced as well.

Example: `ROW 1::bool, "1"::int`

2024-04-12 10:00 UTC, elasticsearchmachine commented
Hi @bpintea, I've created a changelog YAML for you.

2024-04-12 10:00 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytical-engine (Team:Analytics)

2024-04-15 05:16 UTC, costin approved these changes
Not sure how common this is going to be however it's a nice shortcut available in Postgres.
I've tagged the UX team since it impacts them and decide if we can ship this in 8.14 or push it to 8.15.
LGTM

2024-04-15 09:37 UTC, bpintea commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/EsqlFeatures.java
> +    public static final NodeFeature CASTING_OPERATOR = new NodeFeature("esql.casting_operator");
I think so, otherwise we'll be using the Version numbers, which we'll need to leave behind; or run into issues testing Serverless.

2024-04-16 07:07 UTC, alex-spies commented
IMHO, I'd wait until 8.15 with this; as it introduces new syntax, I think we should revisit how this will interact e.g. with union types, resp. handling of cases where `from idx* | keep somefield` has a type conflict because `somefield` exists in indices `idx1` and `idx2` with different types.

2024-04-16 09:22 UTC, bpintea commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/convert/ConvertUtils.java
> +public final class ConvertUtils {
Moved it there with some minor modifications, to distinguish from the value (vs function) converters there.

2024-04-17 10:36 UTC, luigidellaquila reviewed
LGTM, but +1 to @alex-spies comment regarding union types, maybe we want to double-check how this addition can interact with that.

2024-04-17 10:36 UTC, luigidellaquila approved these changes

2024-04-17 15:10 UTC, craigtaverner requested changes
Can we consider dropping the type aliases? This is not supported by Postgresql, which is clearly the database that inspired this use of `::`, and I fear it pollutes the type namespace a bit. We could add type aliases later as an enhancement, after thinking a little more about the pros/cons?

2024-04-17 15:10 UTC, craigtaverner commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/type/EsqlDataTypes.java
> +        Map<String, DataType> map = TYPES.stream().collect(toMap(DataType::typeName, Function.identity()));
I notice that Postgresql does not support type aliases here, and this syntax is similar to Postgresql, so clearly inspired by that. Perhaps we should hold off on that.

2024-04-17 16:35 UTC, astefan approved these changes
LGTM

But, I have a similar concern with Craig's: putting something in is easy, taking it out afterwards is more difficult (bwc). So, I would take out the types aliases and consider adding them back if there is demand for them.

2024-04-17 18:22 UTC, bpintea commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/type/EsqlDataTypes.java
> +        Map<String, DataType> map = TYPES.stream().collect(toMap(DataType::typeName, Function.identity()));
We did follow Postgresql syntax, but not the implementation. This operator is much about convenience, we could leave it out entirely and still write `to_datetime()`, `to_version()` a.s.o. So while I understand that some aliases might seem too short, others should safe and useful, like `int`, `bool`, `string`, which, btw, we also have in ES SQL. Some of the type names are really long, so they'd be good candidates, but I guess I'll take everything out, except the three mentioned previously, if no stronger opposition is raised.

2024-04-18 08:26 UTC, craigtaverner commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/type/EsqlDataTypes.java
> +        Map<String, DataType> map = TYPES.stream().collect(toMap(DataType::typeName, Function.identity()));
Sounds good. Then we can add more aliases on a case-by-case basis.

2024-04-18 08:29 UTC, craigtaverner commented
> LGTM, but +1 to @alex-spies comment regarding union types, maybe we want to double-check how this addition can interact with that.

I do not see anything here that would clash with my current work on union types. At this point this seems like pure syntactic sugar over the existing ToType() functions, and there is no behavioural change, so it seems like it would work with union types exactly the same.

2024-04-18 08:45 UTC, alex-spies commented
> > LGTM, but +1 to @alex-spies comment regarding union types, maybe we want to double-check how this addition can interact with that.
> 
> I do not see anything here that would clash with my current work on union types. At this point this seems like pure syntactic sugar over the existing ToType() functions, and there is no behavioural change, so it seems like it would work with union types exactly the same.

Sorry, my comment was not clear enough.

What I meant, is:
- This PR's proposed syntax for casting via `some_field::target_type` is very elegant. Following Postgres' established standard is nice as well.
- However, in contrast to Potgres we have a more unique situation: `some_field` can have multiple types when it occurs in different indices; we haven't established a solution for this just yet (and thanks for your work on that @craigtaverner ).
- Dealing with a field having multiple types will likely profit from ergonomic syntax (and/or good syntactic sugar) as well, but we don't know how it will look like, yet. One way it could look like is that when we have `some_field` in `index1` with type `boolean` and in `index2` with type `integer`, we disambiguate between the two by writing `some_field::integer` or `some_field::boolean` (or maybe not and we do something like `index1.some_field` or so).

As we haven't fully worked that out, I'd be hesitant to add syntactic sugar _just yet_, as we won't be able to take back that decision without a breaking language change.

2024-04-18 09:26 UTC, luigidellaquila commented
> One way it could look like is that when we have some_field in index1 with type boolean and in index2 with type integer, we disambiguate between the two by writing some_field::integer or some_field::boolean (or maybe not and we do something like index1.some_field or so).

I think we have alternatives.
Using `index1.some_field` is probably hard when you have many indexes, but we can use a slightly different syntax, eg. `some_field:integer` (single `:`).
Since `::` is a well known casting operator (in Postgres, but also in ES SQL), I think this meaning should be preferred.

2024-04-18 13:19 UTC, craigtaverner requested changes
The csv-spec tests still use the aliases. I assume these tests no longer pass?

2024-04-18 13:19 UTC, craigtaverner commented on x-pack/plugin/esql/qa/testFixtures/src/main/resources/convert.csv-spec
> +ROW zero="POINT(0 0)"::geo_shape, one="POINT(1 1)"::gshape, two="POINT(2 2)"::gs
Likewise we still have gshape and gs, and I presume the cartesian equivalents too.

2024-04-18 13:41 UTC, craigtaverner approved these changes

2024-04-18 14:37 UTC, merged