Remote cluster - API key security model - cluster privileges
elastic/elasticsearch pull request #107493
Opened 2024-04-15 17:21 UTC by jakelandis

2024-04-25 22:37 UTC, elasticsearchmachine commented
Pinging @elastic/es-security (Team:Security)

2024-04-25 22:37 UTC, elasticsearchmachine commented
Hi @jakelandis, I've created a changelog YAML for you.

2024-04-25 22:38 UTC, jakelandis commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/apikey/CrossClusterApiKeyRoleDescriptorBuilder.java
> +    public static final String[] CCS_CLUSTER_PRIVILEGE_NAMES = { "cross_cluster_search", "monitor_enrich" };
I think i can remove the need to explicitly add this by changing how ES|QL calls has_privileges and will follow up in a seperate PR.

2024-04-25 22:50 UTC, jakelandis commented on x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityEsqlIT.java
> +        response = performRequestWithRemoteSearchUserViaAPIKey(request);
this isn't related to the change here ... i just forgot to test this via API key in the prior PR.

2024-04-30 10:21 UTC, slobodanadamovic requested changes
The changes look pretty good. Nice job on testing!  I appreciate the javadoc comments. 

Most of the comments I left are optional, but as discussed via chat, we still need to address BWC concern when sending remote cluster permissions to a RCS 2.0 cluster on an older version. I think this should warrant a new BWC test. As an example, you can see how `RemoteClusterSecurityBwcRestIT` is [defined](https://github.com/elastic/elasticsearch/blob/e784706b4e9ddc5ba58ac45d031c2be8dc0a6499/x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityBwcRestIT.java#L45) and [built](https://github.com/elastic/elasticsearch/blob/e784706b4e9ddc5ba58ac45d031c2be8dc0a6499/x-pack/plugin/security/qa/multi-cluster/build.gradle#L29-L41). Unfortunately, this test cannot be extended to test this scenario but it can serve as an example how to add a new BWC test.

2024-04-30 11:46 UTC, slobodanadamovic commented
Do we want to track the usage of roles with `remote_cluster` privileges like we do for `remote_indices` ([here](https://github.com/elastic/elasticsearch/blob/fd6c2677953228d909ca05833e03405686298d3f/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/NativeRolesStore.java#L393-L396) and [here](https://github.com/elastic/elasticsearch/blob/fd6c2677953228d909ca05833e03405686298d3f/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/FileRolesStore.java#L156))?

2024-04-30 20:29 UTC, jakelandis commented
>  we still need to address BWC concern when sending remote cluster permissions to a RCS 2.0 cluster on an older version. 

Good catch. I have updated the code to be remote version aware. 
* https://github.com/elastic/elasticsearch/pull/107493/commits/ed8fde7839a653b880d99d0d6cd66c6e6b6cdff4 -> plumbing needed to push the remote cluster version to check
* https://github.com/elastic/elasticsearch/pull/107493/commits/e01974a7e0c2c4aca57c6ae355b1cc8a8a1e3419 -> implement per version logic and unit test
* https://github.com/elastic/elasticsearch/pull/107493/commits/e1da2593f95c6d535c81c6e9cd0ca08e1fcba226 -> fix stuff i broke

> I think this should warrant a new BWC test. 

I don't think it does. I think a manual test is warranted, but this will likely change very infrequently, and the test would only be applicable one version back (due to when we GA RCS 2.0). There is not much nuance since it will work or it will not, due to we either send valid permissions or not, and the unit tests cover the logic for when we send permissions. There are some non-trivial costs in CPU, flakeyness, complexity, and time to write these BWC tests. In this case I think a quick spot check manually + the unit tests to ensure we send the write permission to the right version is sufficient.

2024-04-30 21:58 UTC, jakelandis commented
> Do we want to track the usage of roles with remote_cluster privileges like we do for remote_indices ([here](https://github.com/elastic/elasticsearch/blob/fd6c2677953228d909ca05833e03405686298d3f/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/NativeRolesStore.java#L393-L396) and [here](https://github.com/elastic/elasticsearch/blob/fd6c2677953228d909ca05833e03405686298d3f/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/FileRolesStore.java#L156))?

Indeed.  I already got the filestore, but missed the native store. Thanks! -> https://github.com/elastic/elasticsearch/pull/107493/commits/cdae9b85f2e5f1717a343060d59beaf7c952bc51

2024-04-30 22:08 UTC, jakelandis commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleDescriptor.java
> +                            .contains(privileges[0].trim().toLowerCase(Locale.ROOT)) == false) {
I think not trimming them is a low level bug. I will keep this here as i think that correctness > consistency here.

2024-04-30 22:10 UTC, jakelandis commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/support/SecuritySystemIndices.java
> +                    builder.startObject("remote_cluster");
good call, i missed that ! I will follow up on this one... but i think your changes for description will grandfather this one in (if not i will handle it in a follow up)

2024-04-30 22:12 UTC, jakelandis commented on x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/permission/RemoteClusterPermissionsTests.java
> +                assertArrayEquals(privileges, found);
thanks for the pointer, but will leave for now.

2024-04-30 22:12 UTC, jakelandis commented on x-pack/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/ApiKeyBackwardsCompatibilityIT.java
> +                : RemoteClusterPermissions.NONE,
see below.

2024-04-30 22:18 UTC, jakelandis commented
all 👍 code review nits included in https://github.com/elastic/elasticsearch/pull/107493/commits/9b7ab458a08b8bd682ae49bce15133e11a40cc92

2024-05-01 13:15 UTC, jeramysoucy approved these changes
Kibana security owned change LGTM. I took a look through the rest of the changes as well.

2024-05-02 13:36 UTC, slobodanadamovic commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleDescriptor.java
> +                            .contains(privileges[0].trim().toLowerCase(Locale.ROOT)) == false) {
I would be +1 on using `trim` when parsing privilege names. But here we are parsing them without trimming, which makes the check accept e.g. `monitor_enrich         ` which then fails validation later.

2024-05-02 13:43 UTC, slobodanadamovic commented
> > I think this should warrant a new BWC test.
> 
> I don't think it does. I think a manual test is warranted, but this will likely change very infrequently, and the test would only be applicable one version back (due to when we GA RCS 2.0). There is not much nuance since it will work or it will not, due to we either send valid permissions or not, and the unit tests cover the logic for when we send permissions. There are some non-trivial costs in CPU, flakeyness, complexity, and time to write these BWC tests. In this case I think a quick spot check manually + the unit tests to ensure we send the write permission to the right version is sufficient.

Good point. 👍

2024-05-02 13:43 UTC, slobodanadamovic approved these changes
LGTM 👍

2024-05-02 15:55 UTC, jakelandis commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/permission/RemoteClusterPermissions.java
> + * Represents a group of permissions for a remote cluster. This is intended to be the model for both the {@link RoleDescriptor}
thanks ! clarified with https://github.com/elastic/elasticsearch/pull/107493/commits/40a52567f0ca20f95b01ee66f67521ecc5ae1a20

2024-05-02 19:19 UTC, merged