Support negative size in `ByteSizeValue`.
elastic/elasticsearch pull request #107988
Opened 2024-04-28 14:46 UTC by howardhuanghua

For the first step in https://github.com/elastic/elasticsearch/issues/106676, support negative size in `ByteSizeValue`

2024-04-28 15:20 UTC, DaveCTurner requested changes
I don't think we can reasonably change the meaning of `ByteSizeValue` like this, sorry. This approach would have enormously far-reaching changes across all of Elasticsearch, way beyond what we could accept simply to add a new kind of column in the `GET _cat/allocation` API. Let's find a way to keep the changes constrained to just this one API instead.

2024-04-29 05:49 UTC, howardhuanghua commented
How about add a new `SignedByteSizeValue` type ?

2024-04-29 06:09 UTC, DaveCTurner commented
:+1: yes a new type makes more sense. But this can't be one which `extends ByteSizeValue` I think, for the same reasons: today we assume in various places that `ByteSizeValue` is nonnegative (except for the special value `-1`), and subclassing it like this means could pass in a `SignedByteSizeValue` instance which breaks those assumptions.

2024-04-29 06:10 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2024-09-19 07:58 UTC, DaveCTurner commented
This isn't the right direction to take for this change, I'm closing this.

2024-09-19 07:58 UTC, closed without merging