Wait for all shards to be active when creating the ML stats index
elastic/elasticsearch pull request #108202
Opened 2024-05-02 15:21 UTC by davidkyle

Several tests have started failing recently with the dread `no_shard_available_action_exception` when querying the `.ml-stats` index. The error occurs when an index is accessed directly after creation before any shards have become active. See   #65846 for more details.

The recent failures stem from the change to invalidate the model cache in #106988. The cache is invalidated on PUT model which causes the models to be evicted and on eviction they persists stats to the `.ml-stats` index. The failing tests create a model causing the cache eviction and triggering a write to `.ml-stats`, immediately after the test clean up kicks in and during the model deletion the `.ml-stats` index is queried throwing the `no_shard_available_action_exception`.

The fix is to wait for all shard to become active when creating the index

Closes #106652
Closes #107815
Closes #107777
Closes #107505
Closes #80703

2024-05-02 15:21 UTC, elasticsearchmachine commented
Pinging @elastic/ml-core (Team:ML)

2024-05-06 13:33 UTC, przemekwitek approved these changes
LGTM

2024-05-24 12:40 UTC, prwhelan requested changes

2024-05-24 12:40 UTC, prwhelan commented on x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/integration/MlRestTestStateCleaner.java
> +        ESRestTestCase.ensureHealth(".ml-stats-*", (request) -> {
This should fix the failing tests? It looks like it's failing on 403s: 
```
{"error":{"root_cause":[{"type":"security_exception","reason":"action [cluster:monitor/health] is unauthorized for user [no_ml] with effective roles [minimal], this action is granted by the cluster privileges [monitor,manage,all]"}],"type":"security_exception","reason":"action [cluster:monitor/health] is unauthorized for user [no_ml] with effective roles [minimal], this action is granted by the cluster privileges [monitor,manage,all]"},"status":403}
```
```suggestion
        ESRestTestCase.ensureHealth(adminClient, ".ml-stats-*", (request) -> {
```

2024-07-25 21:15 UTC, maxhniebergall commented
This fix seemed super close to being done, so I just merged main into it and added Pat's change. I was able to reproduce the test failures before this change, and not after, so everything LGTM

2024-10-29 17:25 UTC, maxhniebergall commented
@elasticmachine merge upstream

2024-10-30 14:43 UTC, prwhelan approved these changes

2024-10-30 14:48 UTC, merged

2024-10-30 14:49 UTC, elasticsearchmachine commented
## 💚 Backport successful
| Status | Branch | Result |
|:------:|:------:|:------:|
| ✅ |  [8.x](https://github.com/elastic/elasticsearch/pull/115947)  | [<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/115947">](https://github.com/elastic/elasticsearch/pull/115947) |