[DOCS] Reinforce connection between rollover and index age
elastic/elasticsearch pull request #108588
Opened 2024-05-13 20:23 UTC by shainaraskas

- Fixes https://github.com/elastic/elasticsearch/issues/85651
- Adds notes to rollover + ilm tutorials that explains how the index creation date and therefore its `min_age` is impacted by rollover
- Links to [How `min_age` is calculated](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-lifecycle-error-handling.html#_how_min_age_is_calculated) as the source of truth

2024-05-14 13:31 UTC, elasticsearchmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2024-05-14 17:24 UTC, dakrone requested changes

2024-05-14 17:24 UTC, dakrone commented on docs/reference/ilm/actions/ilm-rollover.asciidoc
> +<<min-age-calculation,Learn more>>.
I think the "This" in the second sentence is ambiguous. For instance, after an index is rolled over, there is no "downstream ILM `max_age`" condition, the only time comparison is for the `min_age` of phase definitions.

I think we could clarify this to something like:
```suggestion
When an index is rolled over, a new index is created with a new `creation_date` while the previous index
is updated with a timestamp that reflects the rollover time. This rollover time impacts the calculation of downstream {ilm} `min_age` phase calculations. 
<<min-age-calculation,Learn more>>.
```

(feel free to change this, I just put it here as a suggestion)

2024-05-14 19:47 UTC, dakrone commented on docs/reference/ilm/actions/ilm-rollover.asciidoc
> +<<min-age-calculation,Learn more>>.
> isn't it the `creation_date` that's used in `min_age` phase calculation?

No, ILM uses the rollover time (the time at which the index was rolled over). In your suggestion it makes it sound as though the new index has a `creation_date` which then gets used for ILM `min_age` phase calculations, when it's really the _old_ write index that has a new "time" set (the rollover time) that is used for the `min_age` calculations. The newly created index is back at the beginning again, so it's likely back to the `rollover` step.

For example, if a user has a policy where the `hot` phase is configured with a rollover action for `max_docs: 1`, and a `warm` phase with a `min_age: 1h`. Say it takes 10 minutes before a single document is indexed (to meet the `max_docs: 1` condition), so it rolls over at the 10 minute mark. The index records the time it rolls over, then waits an additional 30 minutes from this time (for a total of 40 minutes) before entering the `warm` phase.

2024-05-16 17:54 UTC, shainaraskas commented
hey @dakrone, I've taken another shot at this. Looks like the original explanation in the docs might have been wrong so I made some additional updates. thanks for your explanation and your patience!

2024-05-17 16:00 UTC, dakrone approved these changes
LGTM, thanks for clarifying this! I left two comments about typos that I saw but otherwise it looks great.

2024-05-17 16:00 UTC, dakrone commented on docs/reference/ilm/index-rollover.asciidoc
> +When an index is rolled over, previous index's age is updated to reflect the rollover time.
```suggestion
When an index is rolled over, the previous index's age is updated to reflect the rollover time. 
```

2024-05-17 16:28 UTC, shainaraskas commented on docs/reference/ilm/actions/ilm-rollover.asciidoc
> +When an index is rolled over, previous index's age is updated to reflect the rollover time.
great catch! ty

2024-05-17 16:52 UTC, merged

2024-06-13 17:40 UTC, shainaraskas commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.14|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/109693">](https://github.com/elastic/elasticsearch/pull/109693)|
|✅|8.13|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/109694">](https://github.com/elastic/elasticsearch/pull/109694)|

Note: Successful backport PRs will be merged automatically after passing CI.

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

<!--- Backport version: 9.5.1 -->