set default value of cluster.routing.allocation.cluster_concurrent_rebalance to -1
elastic/elasticsearch pull request #109210
Opened 2024-05-30 13:05 UTC by madhava-sridhar

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
   ✅ 
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
   ✅ 
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
  ✅ 
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
✅ 
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2024-05-30 13:10 UTC, madhava-sridhar commented on server/src/test/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceReconcilerTests.java
> +                lessThanOrEqualTo(numberOfNodes)
number of concurrent rebalance now is controlled by `cluster.routing.allocation.node_concurrent_incoming_recoveries / cluster.routing.allocation.node_concurrent_outgoing_recoveries`

which has default value  = number of nodes.

2024-05-30 13:11 UTC, madhava-sridhar commented on server/src/test/java/org/elasticsearch/cluster/routing/allocation/AddIncrementallyTests.java
> +            .put("cluster.routing.allocation.node_initial_primaries_recoveries", 100)
test case conditions assume previous default value of 2 for `cluster.routing.allocation.cluster_concurrent_rebalance`

planning to add new test for new behaviour as per new default .

2024-05-30 13:15 UTC, DaveCTurner requested changes
I don't think it's so simple unfortunately - as mentioned in #97750 we want to limit rebalance activity at the node level (by default 1 per node) so that we don't use up all the concurrent-recovery slots (by default 2 per node) on rebalancing.

2024-05-30 14:54 UTC, madhava-sridhar commented
default settings for cluster.routing.allocation.cluster_concurrent_rebalance before was "2" with "NodeScope". I'm confused about  definition of NodeScope. Below is from Setting.java

```
" /**
         * Cluster-level or configuration file-level setting. Not an index setting.
         */
        NodeScope,"
```

2024-05-31 13:16 UTC, henningandersen requested changes
There is more work to do here.

2024-06-20 07:21 UTC, closed without merging