Fix ilm race condition
elastic/elasticsearch pull request #109230
Opened 2024-05-31 06:16 UTC by sscimff

Fixes race condition in ILM Shrink action (#109206). Ensures ILM execution state is copied before execution, improving stability.

2024-05-31 10:08 UTC, henningandersen requested changes
> Ensures ILM execution state is copied before execution, improving stability

I am not sure I understand this, can you elaborate? This does not look like it copies execution state, rather it waits for an always true condition AFAICS.

We also need a test demonstrating the issue, will you add that too?

2024-05-31 10:08 UTC, henningandersen commented on server/src/main/java/org/elasticsearch/cluster/ClusterStateObserver.java
> +    public static org.elasticsearch.xpack.core.ml.MlMetadata.Builder ChangePredicate;
Can we revert this?

2024-05-31 10:08 UTC, henningandersen commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/ShrinkStep.java
> +        return indexMetadata != null && indexMetadata.getState() == IndexMetadata.State.OPEN;
This does not ensure that the index is allocated, only that it exists and is open.

2024-05-31 10:08 UTC, henningandersen commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/ShrinkStep.java
> +                public void onNewClusterState(ClusterState state) {
This is not the right way to use an observer, instead you should pass the condition as a predicate to `waitForNextChange`.

2024-05-31 11:49 UTC, elasticsearchmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2024-06-20 14:11 UTC, nielsbauman commented
Hi @sscimff, thank you for your interest in Elasticsearch and for taking the time to open a PR! I see you haven't addressed @henningandersen's comments yet. Are you still planning to work on this PR? The reason I'm asking is that we've discussed this issue (https://github.com/elastic/elasticsearch/issues/109206) internally, and we're inclined to go with a different approach from the one you've taken here.

If you're still interested in fixing this issue, I'm happy to explain our proposed solution to you. Otherwise, I'll close your PR and open one of my own.

2024-06-20 14:53 UTC, sscimff commented
Hi @nielsbauman thank you for the message. If you have another approach and decide to implement it. Please go ahead and close this PR.

2024-08-26 14:42 UTC, nielsbauman commented
We've decided internally on a different approach for this issue (see https://github.com/elastic/elasticsearch/issues/109206#issuecomment-2310376610). We'll be picking this up internally as well.

I'm going to close this PR, thanks nonetheless for your efforts @sscimff!

2024-08-26 14:42 UTC, closed without merging