ESQL: Adds a test and fixes running the CsvTestsDataLoader.main
elastic/elasticsearch pull request #109836
Opened 2024-06-18 06:50 UTC by astefan

Following the changes in https://github.com/elastic/elasticsearch/pull/109552 running the `main` method of the csv loader (`gradlew :x-pack:plugin:esql:qa:testFixtures:loadCsvSpecData`) fails with `java.lang.NoClassDefFoundError: org/elasticsearch/xpack/esql/plan/logical/local/LocalRelation`.

This PR changes the gradle file and adds a test.

2024-06-18 20:40 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytical-engine (Team:Analytics)

2024-06-18 20:51 UTC, astefan commented
@elasticmachine run elasticsearch-ci/part-3

2024-06-18 20:59 UTC, mark-vieira reviewed
@breskeby can you sanity check this?

2024-06-19 08:15 UTC, breskeby approved these changes

2024-06-19 08:16 UTC, breskeby commented
looking at that jarHell issue

2024-06-19 09:20 UTC, breskeby commented on x-pack/plugin/esql/qa/testFixtures/build.gradle
> +    api(project(':x-pack:plugin:esql'))
can we make that 'implementation'

2024-06-19 09:20 UTC, breskeby commented on x-pack/plugin/esql/qa/testFixtures/build.gradle
>      api "net.sf.supercsv:super-csv:${versions.supercsv}"
think this should be 'implementation' too

2024-06-19 09:22 UTC, breskeby requested changes
two minor remarks added. 

Also to fix the jarHell issue in `:xpack:plugin:esql` you need to tweak the testFixtures dependency declaration too exclude itself:

```
  testImplementation(project('qa:testFixtures')) {
    exclude(group:"org.elasticsearch.plugin", module: "esql")
  }
```

2024-06-19 13:54 UTC, astefan commented
Thank you @breskeby. I've made the changes. Things (as in the `loadCsvSpecData` gradle task and the test I just added) work locally. Let's see if CI is happy as well.

2024-06-20 11:43 UTC, breskeby approved these changes

2024-06-20 11:49 UTC, merged