Reword exception message
elastic/elasticsearch pull request #110481
Opened 2024-07-04 14:13 UTC by idegtiarenko

Rewords the exception message to make it clear the documents limit is per shard, not per index.

2024-07-04 14:13 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2024-07-05 14:39 UTC, kingherc approved these changes
LGTM

2024-07-08 13:58 UTC, DaveCTurner requested changes
Could we just call it `shard` instead of `index shard`? I know we call it `IndexShard` internally but I don't think this is something users would generally understand.

2024-07-09 08:10 UTC, DaveCTurner approved these changes
LGTM

2024-07-09 09:57 UTC, merged