Short-circuit single slice searches in ContextIndexSearcher
elastic/elasticsearch pull request #111126
Opened 2024-07-20 04:44 UTC by original-brownbear

Even with the recent Lucene improvements in
https://github.com/apache/lucene/pull/13472 there is no need to go through all the Lucene machinery for a single slice here. The task executor allocates a bunch of objects and runs into some memory barriers that the JVM can't necessarily compile away. Let's save that overhead for the single slice case and get some of that Lucene 9.12.0 fork-saving behaviour right away. (I am aware this changes the load distribution across search and search_worker a little, but I think it's irrelevant practically because forking and joining a task will probably as expensive as executing it outright in a lot of cases anyway)

Also this PR removes the pointless list of collectors that we were building.
Lastly, a neat side-effect of this change is that it makes whether or not forking has happened a little easier to spot in profiling in the current ES version.

2024-07-20 04:45 UTC, elasticsearchmachine commented
Pinging @elastic/es-search (Team:Search)

2024-07-22 13:52 UTC, elasticsearchmachine commented
Pinging @elastic/es-search-foundations (Team:Search Foundations)

2024-07-23 13:22 UTC, javanna requested changes
I don't think we should make this type of changes. If we see value in these optimizations, we should make improvements in Lucene directly. We already have too much custom search logic in ContextIndexSearcher, that I wish we would look into removing as opposed to making more complex over time.

2024-07-26 08:33 UTC, original-brownbear commented
Fair point, this can actually go into Lucene for a small win. Easier to benchmark there as well :) incoming!

2024-07-26 08:33 UTC, closed without merging