Get rid of blocking `Engine#close` calls
elastic/elasticsearch pull request #111582
Opened 2024-08-05 08:53 UTC by arteam

Stacked on top of #111116

2024-08-06 14:02 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2024-08-06 16:12 UTC, DaveCTurner requested changes
Unfortunately I think this approach will have the same deadlock concerns as the original, albeit if we block on a `ReentrantLock` rather than a `Future` we won't trip the assertion that tells us the danger. We could be in a state where all the threads are waiting to acquire an `engineMutex` that's currently locked and can only be released by one of those same threads.

I think we need to do something nonblocking here instead.

2024-08-08 09:05 UTC, arteam commented
I think that's a valid concern, too. I'm not sure that getting rid of `engineMutex` is really possible, you would need to completely re-design `IndexShard` that heavily relies on it. I'm going to put the issue on hold and think about the best way forward.

2024-08-15 08:53 UTC, arteam commented
@elasticmachine update branch

2024-08-19 09:22 UTC, arteam commented
@elasticmachine update branch

2024-08-21 08:37 UTC, arteam commented
@elasticmachine update branch

2024-08-22 13:29 UTC, arteam commented on server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
> +            engineMutex.unlock();
I guess this only works because the listener completes on the same thread that acquired the mutex? It's generally not safe.

2024-10-24 15:26 UTC, closed without merging