Update knn-query.asciidoc
elastic/elasticsearch pull request #111784
Opened 2024-08-11 08:52 UTC by Barry1915

the knn query use param "num_candidates" instead of "k"

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2024-08-14 08:32 UTC, elasticsearchmachine commented
Pinging @elastic/es-search-relevance (Team:Search Relevance)

2024-09-02 03:02 UTC, Makan39 commented
Perfect

2024-09-02 03:10 UTC, Makan39 reviewed
Perfect

2024-09-02 06:55 UTC, carlosdelest commented
`k` refers to the number of top retrieved results by shard. `num_candidates` is number of nearest neighbour candidates to consider per shard, not the ones actually returned.

The documentation example is correct, there is no need to change it.

2024-09-03 13:56 UTC, benwtrent requested changes
This change doesn't make sense to me & isn't necessary.

See: https://github.com/elastic/elasticsearch/pull/110233

I am going to close this PR

2024-09-03 13:56 UTC, closed without merging