Improve performance of grok pattern cycle detection
elastic/elasticsearch pull request #111947
Opened 2024-08-16 17:12 UTC by masseyke

We perform cycle detection on the bank of grok patterns that a user provides for the GrokProcessor. But it currently has some pretty severe performance problems (and bugs). This fixes that.

2024-08-16 17:12 UTC, elasticsearchmachine commented
Hi @masseyke, I've created a changelog YAML for you.

2024-08-16 18:45 UTC, elasticsearchmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2024-08-22 14:51 UTC, joegallo commented on libs/grok/src/main/java/org/elasticsearch/grok/PatternBank.java
> +            } else if (bracketIndex != -1) {
For future GitHub archaeologists: this change looks out of place but isn't, IntelliJ warns that `columnIndex != -1` is always true here, so it's safe to have removed this.

2024-08-22 20:51 UTC, joegallo requested changes
```
        {
            Map<String, String> bank = new HashMap<>();
            bank.put("NAME1", "!!!%{NAME2} %{NAME3}!!!");
            bank.put("NAME2", "!!!%{NAME4} %{NAME5}!!!");
            bank.put("NAME3", "!!!!!!");
            bank.put("NAME4", "!!!!!!");
            bank.put("NAME5", "!!!%{NAME1}!!!");
            PatternBank.forbidCircularReferences(bank);
        }
```

This correctly detects a cycle (and fails) but the cycle explanation it returns with the `->`s isn't actually correct.

2024-08-23 19:27 UTC, masseyke commented
> ```
>         {
>             Map<String, String> bank = new HashMap<>();
>             bank.put("NAME1", "!!!%{NAME2} %{NAME3}!!!");
>             bank.put("NAME2", "!!!%{NAME4} %{NAME5}!!!");
>             bank.put("NAME3", "!!!!!!");
>             bank.put("NAME4", "!!!!!!");
>             bank.put("NAME5", "!!!%{NAME1}!!!");
>             PatternBank.forbidCircularReferences(bank);
>         }
> ```
> 
> This correctly detects a cycle (and fails) but the cycle explanation it returns with the `->`s isn't actually correct.

There is now a test for this (and it passes).

2024-08-26 18:23 UTC, joegallo approved these changes
🚀

2024-08-26 18:39 UTC, merged

2024-08-26 18:41 UTC, elasticsearchmachine commented
## 💚 Backport successful
| Status | Branch | Result |
|:------:|:------:|:------:|
| ✅ |  [8.15](https://github.com/elastic/elasticsearch/pull/112219)  | [<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/112219">](https://github.com/elastic/elasticsearch/pull/112219) |