Ignore AlreadyClosedException on background merges
elastic/elasticsearch pull request #112490
Opened 2024-09-04 08:28 UTC by arteam

If we encounter an `AlreadyClosedException` when doing background merges, it means the service is being shut down. We can safely ignore the exception and avoid failing the index writer and creating noise in logs.

2024-09-04 10:54 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2024-09-04 11:11 UTC, idegtiarenko commented on server/src/main/java/org/elasticsearch/index/engine/ElasticsearchConcurrentMergeScheduler.java
> +            // Intentially ignored in order not to fail `IndexWriter` when we already shutting down the service.
I wonder if we should have at least a `logger.debug` here.It proved to be helpful while debugging unexpected segment count

2024-09-05 01:21 UTC, ywangd commented on x-pack/plugin/blob-cache/src/main/java/org/elasticsearch/blobcache/shared/SharedBytes.java
> +                throw new AlreadyClosedException("Cache has been closed", e);
Is this still going to be caught by SearchIndexInput which leads to fallback to reading from the object store?

2024-09-05 06:32 UTC, henningandersen requested changes
I would like to instead wait for shards to close - including the async-close part - in `IndicesService.doStop()`. From other conversations, I understand the case where this does not happen to be when an index/shard is first closed/removed, then the `IndicesService` is stopped - we'll then not wait for the first shard's closure. This seems like an oversight more than as expected. I'll note that the engine close is async, including waiting for open-refs (i.e., some ops completion). Not waiting for engine (async) close before taking other components down could lead to all sorts of exceptions, not only during merging.

2024-09-20 14:08 UTC, arteam commented
@elasticmachine update branch

2024-09-23 08:20 UTC, arteam commented
@elasticmachine update branch

2024-09-23 08:24 UTC, closed without merging