Fix AvgTests error on -0.0 avg
elastic/elasticsearch pull request #113272
Opened 2024-09-20 14:31 UTC by ivancea

Fixes https://github.com/elastic/elasticsearch/issues/113225

2024-09-20 14:31 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytical-engine (Team:Analytics)

2024-09-24 12:22 UTC, not-napoleon commented
Maybe I'm reading this wrong, but it looks to me like this will accept `-0.0` as the correct output.  We really shouldn't be returning negative zeros from any operations.  (In fact, probably `AbstractAggregatorTestCase#extractResultsFromAggregator` should assert that we never return a forbidden double value).

2024-09-25 12:56 UTC, ivancea commented
> Maybe I'm reading this wrong, but it looks to me like this will accept `-0.0` as the correct output. We really shouldn't be returning negative zeros from any operations.

@not-napoleon `TestCaseSupplier` provides -0.0 values, so if it can be an input, it should also be an output.

In ES, I see this: https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html#_which_type_should_i_use (Just above that anchor)

> The double, float and half_float types consider that -0.0 and +0.0 are different values.

So if ES also allows it, I would allow it too. And for this case, the avg of -0.0 should be -0.0 too (IMO) to be as precise as possible.

I don't have an specific opinion on this topic, I'm just basing my thought process on what we currently have

2024-09-27 15:38 UTC, not-napoleon requested changes
> to be as precise as possible.

It's not more precise, it's just more confusing. The IEEE spec for floating points says that the two zeros should be considered equal when possible.  Java honors this with it's binary comparison operators (`==` and friends), but not with `Double.equals()`.  You can read the docs on the [double class](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Double.html) to get an understanding for why this is the case.  Practically, this means that if we start allowing negative zeros in the language, we need to be VERY clear on where they compare via `==` and where they compare via `Double.equals()` or `Number.equals()`.  It becomes extremely trappy for users if that behavior is not entirely consistent.

We made the decision early on to not allow `-0.0`, positive or negative infinity, or `NaN` as possible values in ESQL.  We should be consistent with that here.  /cc @costin

2024-09-27 15:39 UTC, not-napoleon commented
> so if it can be an input, it should also be an output.

It's an input on the test precisely to test that it isn't an output.

2024-09-27 17:15 UTC, nik9000 commented
> We made the decision early on to not allow `-0.0`, positive or negative infinity, or `NaN` as possible values in ESQL. We should be consistent with that here. /cc @costin

I think we should be consistent with this decision. Our functions should never receive any of those forbidden doubles. We could (should?) add an assertion to the generated code that reads `double`s for EVAL and STATS that `assert`s that we don't receive those numbers. They should always come in as `null`. And they should always be emitted as `null`.

ES might support these but they are all `null` to ESQL. One day we may change this but that's a difficult thing to change at the moment.

2024-09-27 17:19 UTC, not-napoleon commented
> ES might support these but they are all null to ESQL. One day we may change this but that's a difficult thing to change at the moment.

Well, the infinities and `NaN` are null; `-0.0` is `0`.

2024-09-30 11:58 UTC, ivancea commented
Ok, so:
- To ensure it's not an output, I'll add a check to tests like we have to NaN and infinities
- I'll revert the changes on AvgTests for now

Then, if we have to keep the -0.0 as a potential input in tests, but forbid it as an output, as many functions are currently returning it (Max, MvMax, Min, Values...), I'll fix them by doing a conversion (-0.0 -> 0.0).
I could add it in the agg/evaluator implementers, but it would affect even functions never emitting -0.0. So I'll see first how many functions are failing with this

2024-10-11 14:35 UTC, ivancea commented
@not-napoleon After some checks and talks about this:
- Added some "discoveries" about -0.0 here, to tackle whenever we want to work on this: https://github.com/elastic/elasticsearch/issues/104866#issuecomment-2407370445
- Restored this PR with the Avg fix. It does nothing around -0.0 directly, so I think it's safe to merge whatever the decision we take. Right now, it's agnostic.
  - I left the little refactor on tests: removing repeated code, and adding test cases of single values to aggs, as they are handled differently (This test was failing 1/1000 times because of this)

2024-10-22 13:06 UTC, not-napoleon commented on x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/AbstractFunctionTestCase.java
> +    protected final void assertTestCaseResultAndWarnings(Object result) {
Javadoc would be nice here.

2024-10-22 13:10 UTC, not-napoleon approved these changes
This is fine for now.

2024-10-22 15:17 UTC, ivancea commented on x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/AbstractFunctionTestCase.java
> +    protected final void assertTestCaseResultAndWarnings(Object result) {
Added!

2024-10-22 17:53 UTC, merged

2024-10-22 17:54 UTC, elasticsearchmachine commented
## 💔 Backport failed
| Status | Branch | Result |
|:------:|:------:|:------:|
| ❌ |  8.x  | Commit could not be cherrypicked due to conflicts |

You can use [sqren/backport](https://github.com/sqren/backport) to manually backport by running `backport --upstream elastic/elasticsearch --pr 113272`