ESQL: Move expression translators
elastic/elasticsearch pull request #113893
Opened 2024-10-01 19:18 UTC by nik9000

This moves `ExpressionTranslator` implementations that we use from esql-core into esql. It moves the classes into their own file and deletes the translators we don't currently use.

2024-10-01 19:19 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytical-engine (Team:Analytics)

2024-10-01 22:05 UTC, bpintea commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsqlExpressionTranslators.java
> -        new ExpressionTranslators.MultiMatches(),
I suppose they've just been kept [from before](https://github.com/elastic/elasticsearch/blob/c4758956e9358d5f708cb055e27b8d21f2f3b066/x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java#L95), but aren't used (yet?).

2024-10-01 22:05 UTC, bpintea approved these changes
Lgtm

2024-10-02 09:07 UTC, alex-spies requested changes
I agree with the refactoring, but think that removing the MultiMatches and StringQueries translators may be better done in a separate PR as it may interfere with ongoing work on MATCH.

Also note that as part of https://github.com/elastic/elasticsearch/issues/106679, we wanted to go over all (used) expression translators and double check if they're actually properly tested. This refactoring is mechanical so it's unlikely to cause a bug, but if it does tests are not 100% going to catch it.

2024-10-02 12:10 UTC, nik9000 commented
I'm happy either way. I can keep the files.

2024-10-02 13:23 UTC, alex-spies approved these changes
Thanks Nik!

2024-10-02 15:39 UTC, closed without merging