Rollback Semantic Query Inner Hits
elastic/elasticsearch pull request #113986
Opened 2024-10-02 21:44 UTC by Mikep86

2024-10-02 21:44 UTC, elasticsearchmachine commented
Pinging @elastic/search-eng (Team:SearchOrg)

2024-10-02 23:01 UTC, kderusso approved these changes

2024-10-03 06:21 UTC, carlosdelest requested changes
Hey @Mikep86 , I think you need to roll back the changes to the semantic-query.asciidoc file [here](https://github.com/elastic/elasticsearch/pull/113693/files#diff-ff6ccdace233b5fac01e0d564baa813e8e9d940aebb52ef214e57931cba30816).

The rest LGTM 👍

2024-10-03 06:29 UTC, carlosdelest approved these changes
Ah, I see you removed docs in a [different PR](https://github.com/elastic/elasticsearch/pull/113984). LGTM!

2024-10-03 14:12 UTC, merged

2024-10-03 14:13 UTC, elasticsearchmachine commented
## 💚 Backport successful
| Status | Branch | Result |
|:------:|:------:|:------:|
| ✅ |  [8.x](https://github.com/elastic/elasticsearch/pull/114027)  | [<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/114027">](https://github.com/elastic/elasticsearch/pull/114027) |