ES|QL: remove dead code for LIKE operator
elastic/elasticsearch pull request #115037
Opened 2024-10-17 17:05 UTC by luigidellaquila

We inherited two versions of LIKE operator from QL, respectively `Like` and `WildcardLike`. We only use the second one.

This change removes the first one (unused) and improves test coverage for the second one: we had tests for string patterns only for the wrong one.

2024-10-17 17:05 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytical-engine (Team:Analytics)

2024-10-17 17:15 UTC, luigidellaquila commented
@elasticmachine update branch

2024-10-18 09:31 UTC, alex-spies requested changes
Generally LGTM but I found a couple of small mistakes in the test "translation" that I think we should fix.

2024-10-18 09:31 UTC, alex-spies commented on x-pack/plugin/esql-core/src/test/java/org/elasticsearch/xpack/esql/core/expression/predicate/regex/StringPatternTests.java
> +        assertTrue(likeMatchesAll("*"));
This looks like a typo:
```suggestion
        assertTrue(likeMatchesAll("**"));
```

2024-10-18 09:31 UTC, alex-spies commented on x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceRegexMatchTests.java
> -        for (String s : asList("ab", "ab0%", "ab0_c")) {
Hm, this is not a _perfect_ duplicate of the test below; `testExactMatchWildcardLike` does not test escaping like this one does.

Should we expand `testExactMatchWildcardLike` to include the (actually exact) string patterns `ab\*` and `ab\?c`?

2024-10-18 09:31 UTC, alex-spies commented on x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceRegexMatchTests.java
On a related note, I think we need to expand the docs for LIKE to mention escaping, ideally with an example.

I just ran `FROM test | where a like "?\\?"` (with curl it was actually 4 backslashes for correct escaping) locally and it correctly found `a?` but not `b*`. Then I did the converse and used the pattern `?\\*`, which found `b*` but not `a?`.

Should we open a doc issue to do this in a follow up?

2024-10-18 09:31 UTC, alex-spies commented on x-pack/plugin/esql-core/src/test/java/org/elasticsearch/xpack/esql/core/expression/predicate/regex/StringPatternTests.java
> +        assertFalse(likeMatchesAll("*_"));
I think this should be
```suggestion
        assertFalse(likeMatchesAll("*?"));
```
As the underscore in SQL `LIKE` is not a literal underscore, but "any character", like `WildcardLike`'s "?", no?

Applies similarly below.

2024-10-18 09:31 UTC, alex-spies commented on x-pack/plugin/esql-core/src/test/java/org/elasticsearch/xpack/esql/core/expression/predicate/regex/StringPatternTests.java
> +        assertFalse(likeMatchesAll("0%"));
I believe this should be
```suggestion
        assertFalse(likeMatchesAll("\\*"));
```
(A singly escaped `*`, so actually `\*`, but becomes `"\\*"` due to another layer of escaping for the Java string.)

2024-10-18 09:31 UTC, alex-spies commented on x-pack/plugin/esql-core/src/test/java/org/elasticsearch/xpack/esql/core/expression/predicate/regex/StringPatternTests.java
> +        assertTrue(likeExactMatch("1230_"));
```suggestion
        assertTrue(likeExactMatch("123\\?"));
```

2024-10-18 09:31 UTC, alex-spies commented on x-pack/plugin/esql-core/src/test/java/org/elasticsearch/xpack/esql/core/expression/predicate/regex/StringPatternTests.java
> +        assertTrue(likeExactMatch("1230_321"));
```suggestion
        assertTrue(likeExactMatch("123\\?321"));
```

2024-10-21 07:34 UTC, luigidellaquila commented on x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceRegexMatchTests.java
Good point!
I have an open issue about documenting [how we escape regex](https://github.com/elastic/elasticsearch/issues/115051). That's for GROK, but LIKE is not different, so probably it can be part of the same effort. I'm adding a note there

2024-10-21 07:35 UTC, luigidellaquila commented
Thanks @alex-spies, that `0` as an escape character confused me a bit.
I improved the tests based on your suggestions

2024-10-21 07:56 UTC, luigidellaquila commented
@elasticmachine update branch

2024-10-21 09:27 UTC, alex-spies approved these changes
Thanks, Luigi!

2024-10-21 09:30 UTC, merged

2024-10-21 09:31 UTC, elasticsearchmachine commented
## 💚 Backport successful
| Status | Branch | Result |
|:------:|:------:|:------:|
| ✅ |  [8.x](https://github.com/elastic/elasticsearch/pull/115192)  | [<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/115192">](https://github.com/elastic/elasticsearch/pull/115192) |