Adds back snapshot build restriction for match and qstr functions
elastic/elasticsearch pull request #115253
Opened 2024-10-21 15:46 UTC by carlosdelest

This reverts https://github.com/elastic/elasticsearch/pull/114793

match() and qstr() will be back behind snapshot builds on 8.x branches until using them after LIMIT has been addressed, either in the functions themselves or in Kibana side.

2024-10-21 17:35 UTC, elasticsearchmachine commented
Pinging @elastic/es-search-relevance (Team:Search Relevance)

2024-10-22 08:18 UTC, ChrisHegarty approved these changes
LGTM

2024-10-22 11:46 UTC, carlosdelest commented
> are we not reverting on 8.17 & 8.18 so its easier to test and develop with?

@benwtrent the idea is to fix the LIMIT limitations for 8.17. We could of course be cautious and remove it from the 8.x branch - we're just thinking ahead to avoid another change for enabling this on 8.x

2024-10-22 11:56 UTC, ChrisHegarty requested changes
Please await further discussion on this revert.

2024-10-23 15:36 UTC, ChrisHegarty approved these changes

2024-10-23 15:38 UTC, carlosdelest commented on x-pack/plugin/esql/src/main/antlr/EsqlBaseLexer.g4
> -PROJECT_PARAM : {this.isDevVersion()}? PARAM -> type(PARAM);
Thanks for the catch! No they're not - fixed

2024-10-23 17:56 UTC, merged