[s3-repository] Recover in case a broken AWS HTTP client
elastic/elasticsearch pull request #115304
Opened 2024-10-22 10:15 UTC by arteam

We keep a single instance of `STSAssumeRoleWithWebIdentitySessionCredentialsProvider` in `S3Service` since it's immutable and depends only on JVM and OS environment settings.

One downside of that is that the Apache HTTP client inside `STSAssumeRoleWithWebIdentitySessionCredentialsProvider` can silently shut down on recoverable JVM errors and the only way to recover is to create a new credentials provider with a new HTTP client.

It would be nice if we had a better way to detect a broken HTTP client, we could proactively swap it.

2024-10-22 10:16 UTC, elasticsearchmachine commented
Hi @arteam, I've created a changelog YAML for you.

2024-12-09 15:14 UTC, DaveCTurner requested changes
I suspect this is trying to work around a genuine lifecycle bug in our code rather than something wrong in a dependency. I found such a bug recently and included the fix in https://github.com/elastic/elasticsearch/pull/117628 - prior to that change, we would shut down the STS client on close of _any_ `S3BlobStore` which is simply incorrect. Now that shouldn't happen. I'd like to see more evidence that there's still an issue in this area before proceeding with this change.

2025-04-07 16:06 UTC, Steven314159 commented
Any indication on when this is going to get merged in and be made available? We're impacted by the bug here and cannot use IRSA for S3 connectivity as a result:
https://github.com/elastic/elasticsearch/issues/115186#issuecomment-2565228988

That is supposedly going to be fixed with the 8.18.0 release according to the comment. 
@DaveCTurner is this still slated for that 8.18.0 release as far as you know? Thanks!

2026-07-15 11:19 UTC, DaveCTurner commented
Pretty sure this is no longer an issue, and the code in question has changed beyond recognition anyway.

2026-07-15 11:19 UTC, closed without merging