[Build] Tweak BWC tasks caching
elastic/elasticsearch pull request #117423
Opened 2024-11-24 08:56 UTC by breskeby

We do not cache BWC distro creation which potentially can safe significant time in intake / pr builds

2024-11-24 18:24 UTC, breskeby commented
Fixes more non cacheable tasks due to absolute path issues found here: https://gradle-enterprise.elastic.co/c/sbqckiuokaeim/63gegjth2anws/task-inputs?expanded=WyJ0Nm03eXl5M3pwdnRzLXJvb3RzcGVjJDEiLCJ0Nm03eXl5M3pwdnRzLXJvb3RTcGVjJDEtMC0wIl0

2024-11-24 19:19 UTC, breskeby commented
Testing on checkPart4 in PR we see avoidance of about 6 minutes: https://gradle-enterprise.elastic.co/s/t6agsebb2zbjm/timeline?details=gehydmeqowjok&project=:distribution:bwc:minor

2024-11-24 19:29 UTC, elasticsearchmachine commented
Pinging @elastic/es-delivery (Team:Delivery)

2024-11-25 09:17 UTC, jozala requested changes
Looks good in general, but I believe this one line is commented out by mistake.

2024-11-25 09:19 UTC, breskeby commented on build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/InternalDistributionBwcSetupPlugin.java
> +            // c.getOutputs().doNotCacheIf("BWC distribution caching is disabled for local builds", task -> buildParams.isCi() == false);
indeed. fixed.

2024-11-25 09:20 UTC, jozala approved these changes

2024-11-25 10:28 UTC, merged

2024-11-25 16:23 UTC, mark-vieira commented
Nice!

2026-03-31 11:46 UTC, breskeby commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/145318">](https://github.com/elastic/elasticsearch/pull/145318)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.8 -->