Updated tutorial text
elastic/elasticsearch pull request #117940
Opened 2024-12-03 22:33 UTC by satyyam11

This PR updates the Elasticsearch ILM tutorial to make things clearer and easier to follow.
I’ve cleaned up the steps for customizing ILM policies, explained the rollover, warm, and delete phases a bit more, and made sure everything’s easy to understand.
Basically, it's to help people better manage their ILM policies based on their needs, without all the confusion.

2024-12-03 22:37 UTC, satyyam11 commented
I signed the document now what

2024-12-04 19:04 UTC, satyyam11 commented
Shalll I raise a PR for image change as well?

2024-12-05 11:02 UTC, elasticsearchmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2024-12-06 01:49 UTC, elasticsearchmachine commented
Pinging @elastic/es-docs (Team:Docs)

2024-12-06 01:54 UTC, dakrone requested changes
Thanks for working on this @satyyam11, but we need to update the images as part of this PR in addition to changing the text. Could you make those image updates as well?

2024-12-06 01:54 UTC, dakrone commented on docs/reference/ilm/example-index-lifecycle-policy.asciidoc
> +Elastic Stack deployments on {ess} automatically include hot and warm tiers. If needed, you can add additional warm capacity by editing your deployment and selecting **Add capacity** for the warm dat
They do not automatically include a `warm` tier. They include a `hot` and `content` tier.
```suggestion
Elastic Stack deployments on {ess} automatically include hot and content tiers. If needed, you can add additional warm capacity by editing your deployment and selecting **Add capacity** for the warm data tier.
```

2024-12-06 01:54 UTC, dakrone commented on docs/reference/ilm/example-index-lifecycle-policy.asciidoc
> +image::images/ilm/tutorial-ilm-add-warm-data-tier.png[Add a warm data tier to your deployment]
Is there a reason you changed this image link? As part of this the pngs should be updated to show the newer UI.

2024-12-06 01:54 UTC, dakrone commented on docs/reference/ilm/example-index-lifecycle-policy.asciidoc
> +phase. Adjust the **Minimum primary shard size** and other rollover settings as needed.
A user will still need to uncheck the "Use recommended defaults" right?

2024-12-06 01:54 UTC, dakrone commented on docs/reference/ilm/example-index-lifecycle-policy.asciidoc
> +image::images/ilm/tutorial-ilm-hotphaserollover-new.png[View rollover defaults]
This image doesn't exist, do you need to add it to git so it's committed for this PR?

2024-12-06 01:54 UTC, dakrone commented on docs/reference/ilm/example-index-lifecycle-policy.asciidoc
> +--
There is a lot of unnecessary whitespace changes in this file, can you undo those?

2024-12-12 18:59 UTC, satyyam11 commented
Any updates?

2024-12-13 10:54 UTC, closed without merging