Remove pre-7.2 token serialization support
elastic/elasticsearch pull request #118057
Opened 2024-12-05 10:51 UTC by thecoop

As part of removing 7.x transport versions, remove support for pre-7.2 token serialization

2024-12-05 10:51 UTC, elasticsearchmachine commented
Pinging @elastic/es-security (Team:Security)

2024-12-06 13:43 UTC, slobodanadamovic requested changes
@thecoop Thanks for doing this! The changes look good, but I think we still have couple of things to remove:

Namely, we should nuke all classes and methods related to pre-7.2 tokens, that includes:
1. `KeyComputingRunnable` class
2. `KeyAndCache` class
3. `TokenKeys` class
4. `synchronized void refreshMetadata(TokenMetadata metadata)`
5. `private SecureString generateTokenKey()` including `KEY_BYTES` constant
6. `private void submitUnbatchedTask(String source, ClusterStateUpdateTask task)`
7. `private void installTokenMetadata(ClusterState state)`
8. `void clearActiveKeyCache()`
9. and potentially others I may have missed to name

Further, we should also try and remove all references of  `TokenMetadata`. Unfortunately, we cannot completely remove the class due to the BWC, as the cluster state can still hold the encryption keys and need to know how to deserialize it. I think it would be sufficient to simply not depend or require that encryption keys in anyway need to be in the cluster state.
In order to be able to remove it completely, we would need to run a migration and kick these keys (token metadata) from the cluster state. 

I'm writing this for posterity, but no need to address this. I think migration would be out-of-scope for this PR and should be done in a followup (which I can own).

2024-12-06 13:43 UTC, slobodanadamovic commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/TokenService.java
>      static final int LEGACY_MINIMUM_BASE64_BYTES = Double.valueOf(Math.ceil((4 * LEGACY_MINIMUM_BYTES) / 3)).intValue();
We can remove `LEGACY_MINIMUM_BASE64_BYTES` and `LEGACY_MINIMUM_BYTES` as well since they are not referenced anymore.

2024-12-06 14:09 UTC, thecoop commented
@slobodanadamovic do you want those extra removals to be done here, or are you going to manage that later (so this PR is just the transport version removal)?

2024-12-06 14:17 UTC, slobodanadamovic commented
> @slobodanadamovic do you want those extra removals to be done here, or are you going to manage that later (so this PR is just the transport version removal)?

Makes sense to keep this PR scoped to the transport version removal only, and Iwill address the removal of dead code in a followup.

2024-12-06 14:18 UTC, slobodanadamovic approved these changes
LGTM :+1:

2024-12-09 10:03 UTC, merged