Update migrate_8_16.asciidoc to include enrich.cache_size breaking ch…
elastic/elasticsearch pull request #118161
Opened 2024-12-06 14:21 UTC by ZachBrisson-Elastic

…ange

Heya, due to a bug found in https://github.com/elastic/sdh-elasticsearch/issues/8603 a new breaking change was discovered with the `enrich.cache_size` setting changed to `enrich.cache.size` parameter. A Support KB now outlines the issue, https://support.elastic.co/knowledge/4821af0d. 

This commit adds an "Ingest changes" to the breaking changes section to outline this new behavior, outlining this new behavior. The devs have not confirmed but hope in 8.16.2 for both settings to be available `enrich.cache_size` (Presently only <8.16 worked) AND `enrich.cache.size` (Presently only >8.16 works). In a support case this stopped an upgrade entirely on elastic cloud. In self-hosted environments, it would result in an error triggering during the upgrade process.

2024-12-06 14:22 UTC, elasticsearchmachine commented
@ZachBrisson-Elastic please enable the option "Allow edits and access to secrets by maintainers" on your PR. For more information, [see the documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

2024-12-10 22:46 UTC, elasticsearchmachine commented
Pinging @elastic/es-docs (Team:Docs)

2024-12-10 22:46 UTC, elasticsearchmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2024-12-11 14:59 UTC, shainaraskas commented
Hi Zach 👋 . Because we carry these migration notes forward, you need to create this PR against the 8.x branch and backport it to 8.16 and 8.17.

2024-12-11 15:03 UTC, leemthompo commented
> you need to create this PR against the 8.x branch and backport it to 8.16 and 8.17.

I think I created this confusion recently, but we can actually just slap on backport tags and the automation will cherrypick to whatever version. So shouldn't need additional PRs. :-)

2024-12-11 15:28 UTC, leemthompo approved these changes

2024-12-12 16:00 UTC, nielsbauman requested changes
Thanks for adding this, @ZachBrisson-Elastic! I left a comment regarding the phrasing of the breaking change, but I definitely agree we should add an entry.

2024-12-12 16:01 UTC, nielsbauman commented
I'm also adding @dakrone as a reviewer to pass a second pair of Data Management eyes on the change.

2024-12-12 17:56 UTC, dakrone approved these changes
LGTM, I agree with Niels' suggestions

2025-01-13 00:53 UTC, nielsbauman approved these changes

2025-01-13 01:15 UTC, merged