Remove legacy sim providers
elastic/elasticsearch pull request #118160
Opened 2024-12-06 14:18 UTC by benwtrent

These legacy models & after effects have been removed for all v8, removing legacy deprecation for v9.

2024-12-06 19:18 UTC, mayya-sharipova approved these changes
Thanks Ben, LGTM (we just need to decide what to do with archive indices)

2024-12-06 19:28 UTC, javanna requested changes
Similar comment to what I made in https://github.com/elastic/elasticsearch/pull/118154#pullrequestreview-2485692124 . Here it's a similarity change, I think that if it can be worked around on the user side, at query time, we should feel free to remove this and clean things up in main. Perhaps adding a test for archive indices that verify behaviour would be enough to merge this change.

2024-12-17 17:05 UTC, javanna commented
I went through this another time. This change affects only indices that can be imported as archive. I am supportive on removing the legacy similarity then as it does not affect support for v7 indices in v9. I am not entirely clear though on what the effect is for users interacting with indices that may rely on the legacy similarity when they are imported as archive. Could this be tested? We have this type of test under https://github.com/elastic/elasticsearch/tree/main/x-pack/qa/repository-old-versions , look for instance at `OldMappingsIT`.

2025-01-06 13:35 UTC, benwtrent commented
This indeed breaks legacy indices :(. I also don't think we can add these legacy similarity methods directly via a plugin. So, I guess the only thing to do is add a comment indicating that they cannot be removed.

2025-01-06 15:31 UTC, javanna commented
Would it be possible to add a test to legacy indices that fails if support for legacy similarities is removed?

2025-01-15 15:44 UTC, benwtrent commented
This is frankly not possible due to archive index support as we would blow up with unknown algorithms. closing

2025-01-15 15:44 UTC, closed without merging