Removing old deprecation checks for standard token filter
elastic/elasticsearch pull request #118154
Opened 2024-12-06 14:11 UTC by benwtrent

standard token filter has been removed and unusable for all of v8. Removing it and deprecation checks completely for v9

2024-12-06 14:12 UTC, elasticsearchmachine commented
Pinging @elastic/es-search-relevance (Team:Search Relevance)

2024-12-06 19:05 UTC, mayya-sharipova approved these changes
Thanks Ben, makes sense

2024-12-06 19:18 UTC, benwtrent commented on server/src/main/java/org/elasticsearch/indices/analysis/AnalysisModule.java
> -        tokenFilters.register("standard", new AnalysisProvider<TokenFilterFactory>() {
OK, talking with @javanna we might have an issue with archive indices....we will discuss to find the best way forward here to clean up the core analysis module.

2024-12-06 19:24 UTC, javanna requested changes
The old-lucene-version plugin is the only place that leverages this codepath today. That is true in 8.x as well, at least for the `before v7` case.

I would bet that we have no tests coverage for this in practice, yet it is not entirely dead code in that users are able to import indices created in 5.x and 6.x that may use removed or deprecated functionality. 

What is in practice the effect of removing these conditionals though? Archive indices cannot be written into, hence perhaps we would not break the ability to read from indices that use standard, but only queries on text fields that rely on standard token filter would break? Can that be worked around by providing the analyzer as part of the query?

We need to draw a line between compatibility that we want to maintain, and stuff that we may drop. This feels like it falls in a gray area. I'd like to clarify the user impact before making a final decision.

2024-12-18 21:29 UTC, benwtrent commented on server/src/main/java/org/elasticsearch/indices/analysis/AnalysisModule.java
> -        tokenFilters.register("standard", new AnalysisProvider<TokenFilterFactory>() {
@javanna I changed some tests locally and indeed, adding a standard filter causes opening an index to fail with:

> » [2024-12-18T16:20:46,061][WARN ][o.e.s.RestoreService     ] [5-6-16-1] could not import mappings for legacy index winlogbeat java.lang.IllegalArgumentException: Custom Analyzer [my_custom_analyzer] failed to find filter under name [standard]

:(

Is there a way to add the standard tokenizer via the plugin? That way we remove it from the main server module?

2025-01-08 16:13 UTC, benwtrent commented
Closing in deference to: https://github.com/elastic/elasticsearch/pull/119759

2025-01-08 16:13 UTC, closed without merging