Fix LookupJoin fails to push down limits
elastic/elasticsearch pull request #118252
Opened 2024-12-09 11:44 UTC by jackpan123

Fix LookupJoin fails to push down limits (Closes #117698 )

2024-12-09 14:03 UTC, jackpan123 commented
@elasticsearchmachine generate changelog

2024-12-10 22:44 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytical-engine (Team:Analytics)

2024-12-11 18:40 UTC, alex-spies requested changes
Hi @jackpan123 , I appreciate you taking a stab at this issue.

Unfortunately, the fix is not sufficient, as it special cases for the pattern
EVAL -> JOIN -> UNARY -> LIMIT
but we need to make limit pushdowns work in general cases.

Additionally, manually re-running a rule from within itself is something we normally avoid. The rules are being run in a loop, anyway.

LOOKUP JOIN is still being heavily worked on. Because of this, I'm afraid that https://github.com/elastic/elasticsearch/issues/116208 and associated issues are not the best to start work on, as they are quite ambiguous and/or ill-defined.

2024-12-11 19:20 UTC, closed without merging

2024-12-12 01:29 UTC, jackpan123 commented
@alex-spies Thank you for your patient explanation. I will continue to study and focus on understanding the process of how a LOOKUP JOIN is formed. I'll try to start with other foundational aspects first.