WIP: permissions required for stateful agentless integrations
elastic/elasticsearch pull request #118644
Opened 2024-12-13 09:12 UTC by orestisfl

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2024-12-13 09:13 UTC, elasticsearchmachine commented
@orestisfl please enable the option "Allow edits and access to secrets by maintainers" on your PR. For more information, [see the documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

2024-12-30 14:57 UTC, elasticsearchmachine commented
Pinging @elastic/es-security (Team:Security)

2025-01-07 19:56 UTC, jakelandis requested changes
It looks like the CI failure is related and will need update https://github.com/elastic/elasticsearch/blob/main/docs/reference/rest-api/security/get-service-accounts.asciidoc to account for the new privilege in response. Should be able to test and reproduce locally with `./gradlew ":docs:yamlRestTest" --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/rest-api/security/get-service-accounts/line_57}"` (not tested)

Also, ideally these indindes would be hidden, which requires an index template or explicit creation ; but that is orthogonal to the privileges being introduced here.

2025-01-09 19:18 UTC, orestisfl commented
@jakelandis managed to fix the tests and introduced the index templates, could you please take another look?

2025-01-09 22:41 UTC, jakelandis approved these changes
LGTM

2025-01-09 22:41 UTC, jakelandis commented on x-pack/plugin/core/template-resources/src/main/resources/agentless@settings.json
> +        "number_of_replicas": 1
nitpick: I would suggest to omit these (shard/replica) as they are the defaults.

2025-01-10 16:30 UTC, merged