Add ability to set "max_analyzed_offet" implicitly to "index.highlight
elastic/elasticsearch pull request #118895
Opened 2024-12-17 21:45 UTC by svilen-mihaylov-elastic

Add ability to set "max_analyzed_offet" implicitly to "index.highlight
    .max_analyzed_offset", by setting it excplicitly to "-1".

Add a yaml test.

2024-12-18 22:23 UTC, elasticsearchmachine commented
Pinging @elastic/es-search-relevance (Team:Search Relevance)

2024-12-19 17:53 UTC, john-wagster approved these changes
LGTM, I agree (based on our discussion earlier today) some additional testing would be good.  So probably worth a +1 from Mayya when she returns.  Probably worth backporting this to v8.18.0 as well; I've thrown that label on the PR and thrown on the auto-back label for when you merge this.  Feel free to take those off if you have questions or concerns for any reason.

2025-01-02 16:42 UTC, svilen-mihaylov-elastic commented on server/src/internalClusterTest/java/org/elasticsearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
> +                .setSettings(Settings.builder().put("index.highlight.max_analyzed_offset", "10").build())
Observe index offset is 10

2025-01-02 16:42 UTC, svilen-mihaylov-elastic commented on server/src/internalClusterTest/java/org/elasticsearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
> +            .highlighter(highlight().field("field1").order("score").maxAnalyzedOffset(-1));
Observe query offset is -1

2025-01-02 16:43 UTC, svilen-mihaylov-elastic commented on server/src/internalClusterTest/java/org/elasticsearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
> +                equalTo("This <em>sentence</em> contains one match, not that short. This sentence contains zero sentence matches.")
Observe only one match

2025-01-02 19:45 UTC, mayya-sharipova commented on server/src/main/java/org/elasticsearch/lucene/search/uhighlight/QueryMaxAnalyzedOffset.java
> +public class QueryMaxAnalyzedOffset {
I think it doesn't worth to create an extra class for this small logic. I think we can add this logic in `DefaultHighlighter` and `PlainHighlighter`:

```
Integer queryMaxAnalyzedOffset = fieldContext.field.fieldOptions().maxAnalyzedOffset();
if ((queryMaxAnalyzedOffset) !=null && (queryMaxAnalyzedOffset) == -1) {
     queryMaxAnalyzedOffset = maxAnalyzedOffset;
}
```

and overall changes because of this PR will be smaller.

What do you think?

2025-01-02 19:50 UTC, mayya-sharipova commented on rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/search.highlight/30_max_analyzed_offset.yml
> -  - match: { error.caused_by.reason: "[max_analyzed_offset] must be a positive integer" }
Would be nice to add another test here where query's `max_analyzed_offset` is set to 1.

2025-01-02 19:52 UTC, mayya-sharipova requested changes
@svilen-mihaylov-elastic Thanks for your work. I've left the initial review.

would be nice also to update a documentation about `max_analyzed_offset` in `highlighting.asciidoc`

2025-01-02 20:02 UTC, svilen-mihaylov-elastic commented on server/src/main/java/org/elasticsearch/lucene/search/uhighlight/QueryMaxAnalyzedOffset.java
> +public class QueryMaxAnalyzedOffset {
I considered making tactical changes and perhaps this would indeed be more expedient, but...

Since there are actually four ways that I count to use the queryMaxAnalyzedOffset, it seemed appropriate to consolidate the behavior. We want passing -1 to mean the same thing (getting the max value of the index offset) independent on the location, and centralizing the logic into a class seemed the right way.

2025-01-02 20:05 UTC, svilen-mihaylov-elastic commented on server/src/main/java/org/elasticsearch/lucene/search/uhighlight/QueryMaxAnalyzedOffset.java
> +public class QueryMaxAnalyzedOffset {
On particular problem I ran into, was that AnnotatedTextHighligtherTests, the test code graphs the constant and sends directly to Lucene, and another copy of the constant goes to another pathway... 

Anyways, if there is strong opposition I can inline

2025-01-02 20:39 UTC, mayya-sharipova commented on server/src/main/java/org/elasticsearch/lucene/search/uhighlight/QueryMaxAnalyzedOffset.java
> +public class QueryMaxAnalyzedOffset {
Thanks for the explanation, I agree with your approach, it makes sense to keep the consolidated logic.

2025-01-02 20:42 UTC, mayya-sharipova commented on server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/AbstractHighlighterBuilder.java
> +        if (maxAnalyzedOffset != null && maxAnalyzedOffset < -1) {
I think we should not allow maxAnalyzedOffset to be 0 as well.

2025-01-02 20:46 UTC, mayya-sharipova commented on server/src/internalClusterTest/java/org/elasticsearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
> +        logger.info("--> highlighting and searching on field1");
Do you intend to remove this this logger.info for this PR?

2025-01-02 22:01 UTC, svilen-mihaylov-elastic commented on rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/search.highlight/30_max_analyzed_offset.yml
> -  - match: { error.caused_by.reason: "[max_analyzed_offset] must be a positive integer" }
Added above.

2025-01-02 22:01 UTC, svilen-mihaylov-elastic commented on server/src/internalClusterTest/java/org/elasticsearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
> +        logger.info("--> highlighting and searching on field1");
Will do! Thanks for pointing this out.

2025-01-02 22:03 UTC, svilen-mihaylov-elastic commented on server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/AbstractHighlighterBuilder.java
> +        if (maxAnalyzedOffset != null && maxAnalyzedOffset < -1) {
No I havent done that, as I was not aware it was in scope. I can test for 0.

2025-01-02 22:04 UTC, svilen-mihaylov-elastic commented on server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/AbstractHighlighterBuilder.java
> +        if (maxAnalyzedOffset != null && maxAnalyzedOffset < -1) {
Just a thought though, it seems strange from usability POV that -1 is a valid value, 0 returns exception, and 1+ work.

2025-01-02 22:06 UTC, svilen-mihaylov-elastic commented on server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/AbstractHighlighterBuilder.java
> +        if (maxAnalyzedOffset != null && maxAnalyzedOffset < -1) {
The docs (updated above) state that for "non-negative" values, the highlighting should work, but in practice what does it mean to highlight up to 0 characters???

2025-01-02 22:40 UTC, svilen-mihaylov-elastic commented on rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/search.highlight/30_max_analyzed_offset.yml
> -  - match: { error.caused_by.reason: "[max_analyzed_offset] must be a positive integer" }
Also added test for 0 (it does not crash)

2025-01-02 23:55 UTC, svilen-mihaylov-elastic commented
Looking at the CI tests, it looks like the backwards compatibility tests are failing since I've changed the exception message (https://buildkite.com/elastic/elasticsearch-pull-request/builds/48659#0194292d-5312-4ee2-a6f2-a3217e270df8). Also more generally we do not throw when the value is -1 now. This seems to be running against some older branch....

What would be the way to handle this? Should we backport this commit?

2025-01-03 20:05 UTC, mayya-sharipova approved these changes
@svilen-mihaylov-elastic Thanks for a great work!

2025-01-03 20:09 UTC, mayya-sharipova commented on server/src/main/java/org/elasticsearch/rest/action/search/SearchCapabilities.java
> +    private static final String MAX_ANALYZED_OFFSET_DEFAULT = "max_analyzed_offset_default";
would be nice to add highlight here to indicate it is relevant for highlighting:

    private static final String HIGHLIGHT_MAX_ANALYZED_OFFSET_DEFAULT = "highlight_max_analyzed_offset_default";

2025-01-06 22:05 UTC, svilen-mihaylov-elastic commented
@elasticsearchmachine test this please

2025-01-06 22:42 UTC, svilen-mihaylov-elastic commented
@elasticsearchmachine test this please

2025-01-07 16:19 UTC, merged

2025-01-07 16:21 UTC, elasticsearchmachine commented
## 💔 Backport failed
| Status | Branch | Result |
|:------:|:------:|:------:|
| ❌ |  8.x  | Commit could not be cherrypicked due to conflicts |

You can use [sqren/backport](https://github.com/sqren/backport) to manually backport by running `backport --upstream elastic/elasticsearch --pr 118895`

2026-10-15 05:59 UTC, BranchSun reviewed
## Code Review 摘要

Triage passed (142 counted changed lines, no breaking-change/RFC markers, no security-core files), so this is a normal review. The change adopts a single `QueryMaxAnalyzedOffset` abstraction that resolves `-1` to the index-level `index.highlight.max_analyzed_offset`, applied consistently in `DefaultHighlighter`, `PlainHighlighter`, `CustomUnifiedHighlighter`, `CustomFieldHighlighter` and the annotated-text plugin — that consistency is good. Three things need attention: `HighlightBuilderTests.testInvalidMaxAnalyzedOffset` becomes flaky because `0` is now a valid value, the newly allowed `-1`/`0` values have no version/capability guard (they flow through the validating setter on other nodes, and the updated yaml expectation can no longer match older clusters in REST-compatibility runs), and the comment in the new class is misleading. It would also be worth describing the new `-1` semantics in the user-facing highlight reference docs, since only an internal javadoc mentions it.

**决策（policy）**: COMMENT

### 发现问题
- 🟡 medium: 3
- 🟢 low: 1

2026-10-15 05:59 UTC, BranchSun commented on server/src/test/java/org/elasticsearch/search/fetch/subphase/highlight/HighlightBuilderTests.java
> +            "{ \"max_analyzed_offset\" : " + randomIntBetween(-100, -1) + "}"
🟡 **test** (medium)

`testInvalidMaxAnalyzedOffset` feeds the builder a random value in `[-100, 0]` (inclusive of `0`) and then expects `expectThrows(IllegalArgumentException.class, ...)` to fire. This PR relaxed the validation from `maxAnalyzedOffset <= 0` to `maxAnalyzedOffset < -1`, so `0` is now a legal value: the parse succeeds, no exception is thrown, and `expectThrows` fails with "Expected exception". `randomIntBetween` includes both bounds, so this happens on roughly 1 out of every 101 runs and will show up as an intermittent CI failure.

**建议**: Keep the test only producing values that must be rejected, e.g. `randomIntBetween(-100, -2)`. If you also want `0` covered, assert separately that `0` parses successfully (the new error message "must be an integer >= -1" implies 0 is a supported value, but no test currently pins that behavior).

**证据**: `"{ \"max_analyzed_offset\" : " + randomIntBetween(-100, 0) + "}"`

2026-10-15 05:59 UTC, BranchSun commented on server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/AbstractHighlighterBuilder.java
>      @SuppressWarnings("unchecked")
🟡 **bug** (medium)

`-1` is now a value that a new-version node accepts and serializes, while older nodes reject it in the very same setter, which is also used on the deserialization path (`maxAnalyzedOffset(in.readOptionalInt())`). In a mixed-version cluster (coordinator on this build, shards on an older build), a search with `"max_analyzed_offset": -1` parses fine on the coordinator and then fails on the old shard with "[max_analyzed_offset] must be a positive integer" — previously no such value could be sent because it was rejected at parse time on every node. The same applies to the newly allowed `0`, which older nodes also reject, and it is the reason the exact new error string cannot be asserted against older clusters in REST-compatibility runs (see the related comment on the yaml test).

**建议**: Gate the new value the way other new request options are gated: expose it as a capability/transport-version check (the `Capabilities` machinery or a `TransportVersions` check) and reject `-1` (or downgrade it) when the target nodes do not support it, then add a BWC/mixed-cluster test covering the new value.

**证据**: `if (maxAnalyzedOffset != null && maxAnalyzedOffset < -1) {`

2026-10-15 05:59 UTC, BranchSun commented on rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/search.highlight/30_max_analyzed_offset.yml
> +        body: {"query" : {"match" : {"field2" : "fox"}}, "highlight" : {"type" : "plain", "fields" : {"field2" : {}}, "max_analyzed_offset": 0}}
🟡 **test** (medium)

This yaml test is part of the shared REST suite and is replayed against older clusters in REST-compatibility runs. The expected failure reason was changed to the new message produced only by this build; against an older cluster (which still answers "[max_analyzed_offset] must be a positive integer") the assertion can no longer match, so a version-independent test now asserts a version-specific string. The same file already uses `requires: cluster_features: [...]` for the `max_analyzed_offset` cases that depend on a newer stack version.

**建议**: Either keep asserting the version-independent parts (`status`, `error.*.type`) in the shared test and put the exact new message behind a `requires: cluster_features: ["gte_vX.Y.Z"]` guard, or exclude the case from REST-compatibility runs, as is done elsewhere for version-specific behavior.

**证据**: `  - match: { error.caused_by.reason: "[max_analyzed_offset] must be an integer >= -1" }`

2026-10-15 05:59 UTC, BranchSun commented on server/src/main/java/org/elasticsearch/lucene/search/uhighlight/QueryMaxAnalyzedOffset.java
> +    private QueryMaxAnalyzedOffset(final int queryMaxAnalyzedOffset) {
🟢 **maintainability** (low)

The comment sits in the private constructor, which does nothing but assign the field — it does not look anything up in the index. The fallback to `indexMaxAnalyzedOffset` actually happens in `create(...)`. A reader who trusts the comment will assume instances never hold a negative value, and may add a second construction path (or call the constructor directly) expecting a negative value to be resolved; it also hides the fact that the constructor is only safe when reached through `create`.

**建议**: Move the comment next to the `queryMaxAnalyzedOffset < 0 ? indexMaxAnalyzedOffset : queryMaxAnalyzedOffset` expression in `create` (or resolve the value there and drop the private constructor), so the explanation lives with the code that implements it.

**证据**: `        // If we have a negative value, grab value for the actual maximum from the index.`