Clarify the behavior of remote/info and resolve/cluster for connected status of remotes
elastic/elasticsearch pull request #118993
Opened 2024-12-18 17:18 UTC by quux00

End user docs improvements to clarify the behavior of remote/info and resolve/cluster
for connected status of remotes

2024-12-19 15:33 UTC, elasticsearchmachine commented
Pinging @elastic/es-search-foundations (Team:Search Foundations)

2024-12-19 15:33 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed-indexing (Team:Distributed Indexing)

2024-12-19 15:46 UTC, smalyshev approved these changes

2024-12-19 15:47 UTC, pawankartik-elastic approved these changes

2025-01-03 16:43 UTC, DaveCTurner commented on docs/reference/indices/resolve-cluster.asciidoc
> +the `connected` field in the response will indicate whether it was successful or not.
Note that https://github.com/elastic/elasticsearch/pull/119516 means this is no longer true.

2025-01-03 16:44 UTC, DaveCTurner requested changes
Needs edit to adjust for https://github.com/elastic/elasticsearch/pull/119516

2025-01-07 21:33 UTC, quux00 commented on docs/reference/indices/resolve-cluster.asciidoc
> +the `connected` field in the response will indicate whether it was successful or not.
Modified the wording in [this commit](https://github.com/elastic/elasticsearch/pull/118993/commits/277d334cf14d6a893c18c1ed526716607f7570dc).

2025-01-12 13:39 UTC, DaveCTurner submitted a review, later dismissed

2025-01-12 13:39 UTC, DaveCTurner commented on docs/reference/indices/resolve-cluster.asciidoc
> +the `connected` field in the response will indicate whether it was successful or not.
This still isn't true given the (IMO misguided) move to using `FAIL_IF_DISCONNECTED`. The `connected` field indicates whether the responding node was connected to the remote cluster at the _start_ of the check. If it's disconnected at that point then we return `connected: false` and trigger a background connection attempt (unless one was already running) in the hope that some future call will eventually return `connected: true`.

2025-01-13 13:37 UTC, quux00 commented on docs/reference/indices/resolve-cluster.asciidoc
> +the `connected` field in the response will indicate whether it was successful or not.
Thanks David. Pawan and I discussed this last week and came to a similar conclusion. We're going to revert https://github.com/elastic/elasticsearch/pull/119516 in favor of another approach. We identified a couple of options and Pawan is going to follow up with the distributed team on some of the options that are thinking of. Once that's decided, I'll revise this PR according to the new model.

2025-01-23 23:01 UTC, naj-h approved these changes
added few nitpicks, overall LGTM

2025-01-24 02:25 UTC, lcawl commented
Hi! This is a drive-by comment to make sure folks are aware that these API docs will not be carried forward to V9, so if the changes in this PR are applicable to that version, please ensure they occur in the following locations:

- https://github.com/elastic/elasticsearch-specification/tree/main/specification/indices/resolve_cluster
- https://github.com/elastic/elasticsearch-specification/tree/main/specification/cluster/info

That's how we'll be generating API documentation going forward (e.g. https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-indices-resolve-cluster and https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-cluster-info).  If you need any more info, lmk!

2025-01-29 13:55 UTC, quux00 commented on docs/reference/indices/resolve-cluster.asciidoc
> +NOTE: When querying older clusters that do not support the `_resolve/cluster` endpoint
Actually this PR needs to backport to 8.17.2 so this note doesn't belong here in this PR. I'll pull it out into a separate PR, since I need to do some docs changes for the new timeout param as well that also only goes back to 8.18.

2025-01-29 14:08 UTC, quux00 commented on docs/reference/cluster/remote-info.asciidoc
> +you are querying. The `connected` field reports whether the querying cluster is
Fixed.

2025-01-29 14:15 UTC, quux00 commented
@lcawl I don't think I understand the scope of what you are saying. These existing docs have a lot more info than just documenting the API request and response fields. Where is that information in the new docs system? For example, in the new docs, where is the equivalent of this page: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html

2025-01-29 14:18 UTC, quux00 commented on docs/reference/indices/resolve-cluster.asciidoc
> -
These deleted sections will be added back in another PR that doesn't target 8.17.2.

2025-01-29 15:08 UTC, merged

2025-01-29 15:10 UTC, elasticsearchmachine commented
## 💔 Backport failed
| Status | Branch | Result |
|:------:|:------:|:------:|
| ✅ |  [8.x](https://github.com/elastic/elasticsearch/pull/121194)  | [<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/121194">](https://github.com/elastic/elasticsearch/pull/121194) |
| ❌ |  8.17  | Commit could not be cherrypicked due to conflicts |

You can use [sqren/backport](https://github.com/sqren/backport) to manually backport by running `backport --upstream elastic/elasticsearch --pr 118993`

2025-01-29 16:00 UTC, quux00 commented
Manual backport to 8.17.2: https://github.com/elastic/elasticsearch/pull/121203

2025-01-29 21:11 UTC, lcawl commented
> @lcawl I don't think I understand the scope of what you are saying. These existing docs have a lot more info than just documenting the API request and response fields. Where is that information in the new docs system? For example, in the new docs, where is the equivalent of this page: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html

We've chatted outside the PR but just in case other folks follow, I've created https://github.com/elastic/elasticsearch-specification/pull/3654 to add content from this PR into the specification so it'll be included in the generated docs. Pages like https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html will continue to exist in the regular docs and can continue to contain the bigger-picture explanations and longer-form examples.