ESQL: Support union types/multi-index CSV tests
elastic/elasticsearch pull request #119273
Opened 2024-12-25 14:51 UTC by GalLalouche

This PR adds support for multi-index/union types in CSV tests. Previously, these were only testable using integration tests, which are slower and more annoying to debug.

2025-01-02 16:02 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytical-engine (Team:Analytics)

2025-01-02 16:29 UTC, craigtaverner requested changes
I think there are some non-test changes that are not supposed to be part of this PR

2025-01-02 16:29 UTC, craigtaverner commented on x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java
> +    private static final SingularTestDataset EMPLOYEES = new SingularTestDataset("employees", "mapping-default.json", "employees.csv")
To reduce noise in the PR it would be nicer to keep the old name for TestsDataset.

2025-01-02 16:29 UTC, craigtaverner commented on x-pack/plugin/esql/qa/testFixtures/src/main/resources/union_types.csv-spec
> -required_capability: union_types_fix_rename_resolution
I think this capability should remain, especially when we do BWC tests against older versions.

2025-01-02 16:29 UTC, craigtaverner commented on x-pack/plugin/esql/qa/testFixtures/src/main/resources/union_types.csv-spec
> -required_capability: union_types_fix_rename_resolution
As mentioned above, I think this capability should remain. There are many more places in this file where it was removed.

2025-01-02 16:29 UTC, craigtaverner commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsPhysicalOperationProviders.java
> +            this.typeConverter = TypeConverter.fromConvertFunction(convertFunction);
This is not a test change, should this really be in this PR?

2025-01-02 16:29 UTC, craigtaverner commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java
> +    public static Block.Builder blockBuilder(DataType dataType, int estimatedSize, BlockFactory blockFactory) {
This is not a test change, should this really be in this PR?

2025-01-02 16:29 UTC, craigtaverner commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/TypeConverter.java
> +class TypeConverter {
This is not a test change, should this be in this PR?

2025-01-02 19:37 UTC, GalLalouche commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsPhysicalOperationProviders.java
> +            this.typeConverter = TypeConverter.fromConvertFunction(convertFunction);
I extract this behavior so it could be used both here and in the test providers. So yes :)

2025-01-02 19:38 UTC, GalLalouche commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java
> +    public static Block.Builder blockBuilder(DataType dataType, int estimatedSize, BlockFactory blockFactory) {
Considering this is used in the test, why not?

2025-01-02 19:38 UTC, GalLalouche commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/TypeConverter.java
> +class TypeConverter {
Same comment as above: extracted for use in tests.

2025-01-02 19:39 UTC, GalLalouche commented on x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java
> +    private static final SingularTestDataset EMPLOYEES = new SingularTestDataset("employees", "mapping-default.json", "employees.csv")
Done.

2025-01-03 10:57 UTC, GalLalouche commented on x-pack/plugin/esql/qa/testFixtures/src/main/resources/union_types.csv-spec
> -required_capability: union_types_fix_rename_resolution
Readded.

2025-01-03 10:57 UTC, GalLalouche commented on x-pack/plugin/esql/qa/testFixtures/src/main/resources/union_types.csv-spec
> -required_capability: union_types_fix_rename_resolution
Readded.

2025-01-03 14:12 UTC, craigtaverner approved these changes
Approved, but did have a couple of suggestions.

2025-01-03 14:12 UTC, craigtaverner commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsPhysicalOperationProviders.java
> +            return "TypeConvertingBlockLoader[delegate=" + delegate + ", typeConverter=" + typeConverter + "]";
Perhaps we should implement the TypeConverter.toString method so we control this output?

2025-01-03 14:12 UTC, craigtaverner commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java
> +    public static Block.Builder blockBuilder(DataType dataType, int estimatedSize, BlockFactory blockFactory) {
Since it is only used in test code, perhaps it should be moved to `TestPhysicalOperationProvider`?

2025-01-03 15:25 UTC, GalLalouche commented on x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java
> +    public static Block.Builder blockBuilder(DataType dataType, int estimatedSize, BlockFactory blockFactory) {
Done.

2025-01-03 15:25 UTC, GalLalouche commented on x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java
> +    public record MultiIndexTestDataset(String indexPattern, List<TestsDataset> datasets) {
As discussed offline, Renamed `TestsDataset` to `TestsDataset`, as to not upset my English teacher.

2025-01-03 17:10 UTC, merged

2025-01-03 17:12 UTC, elasticsearchmachine commented
## 💚 Backport successful
| Status | Branch | Result |
|:------:|:------:|:------:|
| ✅ |  [8.x](https://github.com/elastic/elasticsearch/pull/119534)  | [<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/119534">](https://github.com/elastic/elasticsearch/pull/119534) |

2025-01-06 14:19 UTC, idegtiarenko commented on x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/CsvTests.java
> +        Map<String, IndexMode> indexModes = indexNames.collect(Collectors.toMap(x -> x, x -> IndexMode.STANDARD));
I would like to suggest to avoid declaring `indexNames`.
Streams may not be reused and having this variable introduces a possibility of a reuse.

2025-01-07 08:20 UTC, craigtaverner commented on x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/CsvTests.java
> +        Map<String, IndexMode> indexModes = indexNames.collect(Collectors.toMap(x -> x, x -> IndexMode.STANDARD));
I looked, but could not find that change.

2025-01-07 14:36 UTC, alex-spies commented on x-pack/plugin/esql/qa/testFixtures/src/main/resources/union_types.csv-spec
> -required_capability: union_types
I know I'm late to the party, but maybe instead of removing the capability from the test, we should have instead just removed the piece of code that makes the csv tests skip cases marked with it. The capability serves the secondary purpose of skipping test cases in bwc tests when the older node can't handle the query, yet.

2025-01-07 16:07 UTC, GalLalouche commented on x-pack/plugin/esql/qa/testFixtures/src/main/resources/union_types.csv-spec
> -required_capability: union_types
I think the TODO threw me off, since I this PR implements the better solution mentioned IIUC. Is there a way of verifying if the BWC tests failed as a result of this PR?

2025-01-07 16:08 UTC, GalLalouche commented on x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/CsvTests.java
> +        Map<String, IndexMode> indexModes = indexNames.collect(Collectors.toMap(x -> x, x -> IndexMode.STANDARD));
Ah crap, I forgot to push again [🤦](https://emojipedia.org/person-facepalming). I'll add as part of the next PR probably.

2025-01-07 18:09 UTC, alex-spies commented on x-pack/plugin/esql/qa/testFixtures/src/main/resources/union_types.csv-spec
> -required_capability: union_types
Agree, the TODO's wording was imprecise, resp. wrong for some test cases. I think we wrongly copy-pasted this onto test cases where this doesn't really apply.

Given the test has no capability requirement whatsoever now, it will be run in all bwc scenarios, including nodes with versions smaller than 8.15. Union types were introduced in 8.15 (I think), so it's unlikely the tests here can pass these scenarios. Even when the test cases actually don't need union types, they may still require a certain version due to other features that were present in 8.15 but not before. I think `MV_APPEND` is one such feature.

The annoying part is that we didn't know at the time when this was backported to 8.x, because not all tests were run. To run all bwc tests, add the label `test-full-bwc`.

To solve this, we can either re-apply the `union_types` capability requirement, or just slap a `#[skip:-8.14.99,reason:uses features from 8.15]` onto the offending test cases.