Simplify bulk request execution
elastic/elasticsearch pull request #20109
Opened 2016-08-22 22:50 UTC by areek

Currently, bulk item requests can be any ActionRequest, this PR
restricts bulk item requests to DocumentRequest. This simplifies
handling failures during bulk requests. Additionally, a new enum
is added to DocumentRequest to represent the intended operation
to be performed by a document request (`create`, `index`, `update` 
and `delete`), which was previously represented with a mix of strings 
and index request operation type.
Now, index request operation type reuses the new enum to specify 
whether the request should `create` or `index` a document.
Restricting bulk requests to DocumentRequest further simplifies
execution of shard-level bulk operations to use the same failure 
handling for index, delete and update operations.
This PR also fixes a bug which executed delete operations twice for 
replica copies while executing bulk requests.

relates https://github.com/elastic/elasticsearch/pull/19105

2016-10-05 13:19 UTC, bleskes requested changes
I went through this _very_ carefully and it looks great. It's an amazing restructuring and I'm happy you took it on yourself. I left some minor comments. I also think we can potentially simplify further and make the DocumentRequest inherit from WriteReplicationRequest  (and call DocWriteRequest) . I'm not sure but it would be great if you can give it a go.

2016-10-05 13:19 UTC, bleskes commented on core/src/main/java/org/elasticsearch/action/bulk/BulkItemResponse.java
> +        out.writeByte(opType.getId());
we need bwc here too

2016-10-06 07:03 UTC, areek commented on core/src/main/java/org/elasticsearch/action/DocumentRequest.java
> +            this.lowercase = this.toString().toLowerCase(Locale.ENGLISH);
changed it to ROOT, but there are a few places (e.g. `DocWriteResponse`) where we use ENGLISH too. maybe we should change it to ROOT as well?

2016-10-06 07:03 UTC, areek commented on core/src/main/java/org/elasticsearch/action/bulk/BulkRequest.java
>              if (request instanceof IndexRequest) {
done

2016-10-06 07:06 UTC, areek commented on core/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java
> +            if (writeResult.getResponse().getResult() != DocWriteResponse.Result.NOOP) {
I wanted to be more strict as only a noop result can be valid with a null location. changed it to be an assert instead.

2016-10-06 07:06 UTC, areek commented on core/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java
> +            if (ExceptionsHelper.status(e) == RestStatus.CONFLICT) {
fixed

2016-10-06 07:07 UTC, areek commented on core/src/main/java/org/elasticsearch/action/bulk/BulkItemResponse.java
> +        out.writeByte(opType.getId());
bwc added

2016-10-06 09:20 UTC, areek commented
Thanks @bleskes for the review :). I addressed all the minor comments. 

> I also think we can potentially simplify further and make the DocumentRequest inherit from WriteReplicationRequest (and call DocWriteRequest)

I really like the idea of making DocumentRequest inherit from WriteReplicationRequest. While giving this a go, I refactored update operation to be a replication operation (updates are a DocumentWriteRequest but does't use the replication operation instead delegates to index and delete operations for replication). This cleans up the dedicated transport update action (`TransportInstanceSingleOperationAction`) in favour of reusing replication action and duplicate code for update retry logic and translation. The one big downside is it would be difficult to implement wire bwc with 5.0. WDYT?

2016-10-09 19:02 UTC, bleskes reviewed
Thanks @areek . Let's leave the merger/inheritance of DocumentRequest and ReplicationRequest alone. None of the solutions seem ideal (update request is not a replication request and the fact it's running on the primary is not a good thing). This PR is great enough and it would be a shame to delay it. We can revisit / evaluate again when have a better idea.

I do have two small asks (next to a question I left in the comments)
- Can we rename `DocumentRequest` to `DocWriteRequest`? it will be inline with the `DocWriteResponse` we have today.
- It seems we can get rid of the `<?>` in all the `DcoumentRequest<?>` - I think it will make it simpler to read. See https://gist.github.com/bleskes/7ec26991d7be6c816103b8cac65353a4

2016-10-09 19:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java
> +                    update.setGetResult(updateHelper.extractGetResult(updateRequest, updateRequest.concreteIndex(), indexResponse.getVersion(), translate.updatedSourceAsMap(), translate.updateSourceC
why do we now return always the get result on updates? it seems to be different [before](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java#L251)

2016-10-09 19:02 UTC, bleskes commented
It also seems CI isn't happy.

2016-10-12 03:31 UTC, areek commented on core/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java
> +                    update.setGetResult(updateHelper.extractGetResult(updateRequest, updateRequest.concreteIndex(), indexResponse.getVersion(), translate.updatedSourceAsMap(), translate.updateSourceC
I changed it to match the logic in [TransportUpdateAction.shardOperation](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/update/TransportUpdateAction.java#L175) but that caused CI failures, I reverted the change to be the same as update operation in bulk

2016-10-12 03:33 UTC, areek commented
Thanks @bleskes for the feedback. I updated the PR, addressing your comments and the CI is happy. Could you take a look

2016-10-12 11:06 UTC, bleskes approved these changes

2016-10-12 11:06 UTC, bleskes commented
LGTM. Awesome @areek

2016-10-12 17:10 UTC, merged