Add rudimentary logstash and beats template BWC tests
elastic/elasticsearch pull request #20491
Opened 2016-09-14 22:26 UTC by dakrone

This tests that the templates shipped with pre-5.0 versions of Logstash
and Boats still work on an Elasticsearch 5.0+ node. We need to ensure
that ES can be upgraded prior to upgrading tools dependant on it.

This is by no means an exhaustive test of all template settings but it
is a start on #17275

2016-09-14 22:46 UTC, dakrone commented
Also relates to #18061

2016-09-20 08:43 UTC, jpountz commented on core/src/test/java/org/elasticsearch/action/admin/indices/template/put/BWCTemplateTests.java
> +        String topBeat = copyToStringFromClasspath("/org/elasticsearch/action/admin/indices/template/topbeat-1.3.template.json");
Can we have the files in the same package as the test file? ie. either move this test to the `org.elasticsearch.action.admin.indices.template` package or put the files in a sub `put` directory.

2016-09-20 08:44 UTC, jpountz requested changes
Left one comment about directory structure, otherwise LGTM!

2016-09-20 15:59 UTC, dakrone commented on core/src/test/java/org/elasticsearch/action/admin/indices/template/put/BWCTemplateTests.java
> +        String topBeat = copyToStringFromClasspath("/org/elasticsearch/action/admin/indices/template/topbeat-1.3.template.json");
Yep definitely, I'll move the test to the `org.elasticsearch.action.admin.indices.template` package

2016-09-20 16:09 UTC, dakrone commented
I cherry-picked this to 5.0 and 5.x since 6.0 doesn't have the compatibility requirements for BWC with these versions of the template. I'll open a separate PR for 6.0 that uses the 5.0 versions of the Logstash and Beats templates

2016-09-20 16:09 UTC, closed without merging