Provides a cat api endpoint for templates.
elastic/elasticsearch pull request #20545
Opened 2016-09-19 07:18 UTC by a2lin

Adds a cat api endpoint: `/_cat/templates` and its more specific version, `/_cat/templates/{name}`.

It looks something like:
```
$ curl "localhost:9200/_cat/templates?v"
name                  template     order version
sushi_california_roll *avocado*    1     1
pizza_hawaiian        *pineapples* 1
pizza_pepperoni       *pepperoni*  1
```

The specified version (only allows * globs) looks like:
```
$ curl "localhost:9200/_cat/templates/pizza*"
name            template     order version
pizza_hawaiian  *pineapples* 1
pizza_pepperoni *pepperoni*  1
```

Partially specified columns:
```
$ curl "localhost:9200/_cat/templates/pizza*?v=true&h=name,template"
name            template
pizza_hawaiian  *pineapples*
pizza_pepperoni *pepperoni*
```

The help text:
```
$ curl "localhost:9200/_cat/templates/pizza*?help"
name     | n | template name
template | t | template pattern string
order    | o | template application order number
version  | v | version
```

Closes #20467

2016-09-19 13:26 UTC, clintongormley commented
@tlrx could you review please?

2016-09-19 13:32 UTC, s1monw commented
LGTM

2016-09-19 13:32 UTC, s1monw commented
test this please

2016-09-19 13:35 UTC, tlrx commented on core/src/main/java/org/elasticsearch/rest/action/cat/RestTemplatesAction.java
> +            request.paramAsTime("master_timeout", clusterStateRequest.masterNodeTimeout()));
I think it can fit on one line

2016-09-19 13:38 UTC, tlrx commented on core/src/main/java/org/elasticsearch/rest/action/cat/RestTemplatesAction.java
> +        final String matchPattern = request.hasParam("name") ? request.param("name") : "*";
I think it could be null instead of `"*"`

2016-09-19 13:39 UTC, tlrx commented on core/src/main/java/org/elasticsearch/rest/action/cat/RestTemplatesAction.java
> +            if (Regex.simpleMatch(patternString, indexData.name())) {
And here, we check `Regex.simpleMatch()` only if the pattern if not null?

2016-09-19 13:40 UTC, tlrx commented on docs/reference/cat/templates.asciidoc
> +`templates` shows information about currently configured templates.
Maybe changed to "The `templates` command provides about existing templates" ?

2016-09-19 13:41 UTC, tlrx commented on docs/reference/cat/templates.asciidoc
> +The output shows that we have three templates active on the cluster,
three templates active -> three existing templates ? Templates cannot be active or deactivated

2016-09-19 13:42 UTC, tlrx commented on docs/reference/indices/templates.asciidoc
> +
I think you can remove this because it's going to be documented in #20407

2016-09-19 13:45 UTC, tlrx commented on rest-api-spec/src/main/resources/rest-api-spec/test/cat.templates/10_basic.yaml
> +
Can you add more than 1 template?

2016-09-19 13:47 UTC, tlrx requested changes
@a2lin Thanks for your contribution! I left some minor comments but the overall looks good.

2016-09-20 06:30 UTC, a2lin commented
@tlrx thanks for reviewing! I think I've made the requested changes.

2016-09-20 08:12 UTC, tlrx approved these changes

2016-09-20 08:14 UTC, tlrx commented
@a2lin Thanks! Can you please squash the two commits into one? Once done I'll merge this PR and backport it to 5.0/5.x if @clintongormley is OK.

2016-09-20 08:40 UTC, merged

2016-09-20 08:41 UTC, tlrx commented
@a2lin I squashed myself thanks to Github's famous merge button.

Thanks again for your contribution!

2016-09-20 11:41 UTC, tlrx commented
Backported to 5.x in 144a7ca216d6da1859644b9c1544e931c9e9f5b4