If size / offset are out of bounds just do a plain count
elastic/elasticsearch pull request #20556
Opened 2016-09-19 14:35 UTC by martijnvg

so that we at least include total hits, otherwise also total hits would be equal to zero.

PR for #20501

2016-09-20 08:39 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/fetch/subphase/InnerHitsContext.java
> +        }
This does not make sense to me: fi there are 7 inner hits and from=2 and size=1, then we should not just count?

2016-09-20 08:40 UTC, jpountz requested changes
This does not seem to fix the right bug?

2016-09-20 10:12 UTC, martijnvg commented on core/src/main/java/org/elasticsearch/search/fetch/subphase/InnerHitsContext.java
> +        }
doh... Yes, you're absolutely right.

2016-09-29 12:58 UTC, martijnvg commented on core/src/main/java/org/elasticsearch/search/fetch/subphase/InnerHitsContext.java
> +        }
@jpountz The reason I took this approach, was that `TopDocsCollector#topDocs(...)` returns a top docs with total hits set to 0 if `from` is larger than number of collected docs, which is unexpected. Instead it should just return a TopDocs with no docs but a real totalHits/maxScore?

In the search api we don't rely on `TopDocsCollector#topDocs(...)`, but rather on `TopDocs#merge`, which always set maxScore and totalHits.

2016-09-29 14:28 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/fetch/subphase/InnerHitsContext.java
> +        }
> Instead it should just return a TopDocs with no docs but a real totalHits/maxScore?

I tend to agree.

2016-10-18 08:28 UTC, clintongormley commented
@martijnvg just a reminder about this one

2017-02-23 18:14 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-04-07 23:25 UTC, dakrone commented
@martijnvg are you still working on this?

2017-04-10 11:25 UTC, martijnvg commented
This PR should have been closed as this fix is in the wrong place.

2017-04-10 11:25 UTC, closed without merging