XContentBuilder: Avoid building self-referencing objects
elastic/elasticsearch pull request #20550
Opened 2016-09-19 09:51 UTC by tlrx

Some objects like maps, iterables or arrays of objects can self-reference themselves. This is mostly due to a bug in code but the XContentBuilder should be able to detect such situations and throws an IllegalArgumentException instead of building objects over and over until a stackoverflow occurs.
    
closes #20540

2016-09-19 10:09 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java
> +    private final List<Object> ancestors = new ArrayList<>();
This should probably be an IdentityHashSet.

2016-09-19 10:11 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java
> +        ancestors.add(value);
could be just `if (ancestors.add(value) == false)` when moving to a set

2016-09-19 10:12 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java
> +    private XContentBuilder value(Map<String, ?> values) throws IOException {
why does the split help?

2016-09-19 10:15 UTC, jpountz reviewed
I like the idea but on the other hand I can see this causing issues too. For instance it forces to keep objects that are used to build the xcontent around until the builder is closed. The other thing we should look into is whether this has an impact on performance.

2016-09-19 10:52 UTC, tlrx commented on core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java
> +    private final List<Object> ancestors = new ArrayList<>();
I didn't know about this one, thanks

2016-09-19 10:53 UTC, tlrx commented on core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java
> +    private XContentBuilder value(Map<String, ?> values) throws IOException {
Oh, it's a leftover.

2016-09-19 11:23 UTC, tlrx commented
@jpountz Thanks for your review, I updated the code.

> I like the idea but on the other hand I can see this causing issues too. For instance it forces to keep objects that are used to build the xcontent around until the builder is closed. 

Yes, it is not ideal but I don't see how we could prevent endless recursive calls without it.

> The other thing we should look into is whether this has an impact on performance.

It will have some impact but I don't expect it to be big. I can run some Rally tests if you find the idea of keeping objects around acceptable...?

2016-09-19 13:38 UTC, jpountz commented
> >     For instance it forces to keep objects that are used to build the xcontent around until the builder is closed.
> >
>
>Yes, it is not ideal but I don't see how we could prevent endless recursive calls without it.

I am a bit torn about the benefit of adding this protection vs. the potential problems that retaining objects could cause. @jasontedor Maybe you have an opinion about this?

> It will have some impact but I don't expect it to be big. I can run some Rally tests if you find the idea of keeping objects around acceptable...?

For that part, I'd also be fine with just watching the nightly benchmarks to see whether there is a noticeable slow down, just wanted to mention it as I have no idea how much xcontent building is used at index time. At search time, I am pretty sure this change would be ok.

2016-09-20 09:21 UTC, clintongormley commented
Tried out this PR against master and it causes problems.  Try running the following:

    PUT t/t/1 
    {}
    
    GET _search
    {
      "script_fields": {
        "FIELD": {
          "script": {
            "lang": "painless",
            "inline": "while (true) {}"
          }
        }
      }
    }

The second request hangs and the logs show:

<details>

    [elasticsearch] [2016-09-20T11:17:03,253][INFO ][o.e.c.m.MetaDataCreateIndexService] [od38nkP] [t] creating index, cause [auto(index api)], templates [], shards [5]/[1], mappings []
    [elasticsearch] [2016-09-20T11:17:03,529][INFO ][o.e.c.m.MetaDataMappingService] [od38nkP] [t/1o_LC2B5RSmfcCOQuMo7TQ] create_mapping [t]
    [elasticsearch] [2016-09-20T11:17:20,963][DEBUG][o.e.a.s.TransportSearchAction] [od38nkP] [t][3], node[od38nkPUS6qGK4lVOJt7xA], [P], s[STARTED], a[id=Ym46EKCuQi-9Ulp2tUcmNw]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
    [elasticsearch]   "script_fields" : {
    [elasticsearch]     "FIELD" : {
    [elasticsearch]       "script" : {
    [elasticsearch]         "inline" : "while (true) {}",
    [elasticsearch]         "lang" : "painless"
    [elasticsearch]       },
    [elasticsearch]       "ignore_failure" : false
    [elasticsearch]     }
    [elasticsearch]   },
    [elasticsearch]   "ext" : { }
    [elasticsearch] }}]
    [elasticsearch] org.elasticsearch.transport.RemoteTransportException: [od38nkP][127.0.0.1:9300][indices:data/read/search[phase/query]]
    [elasticsearch] Caused by: org.elasticsearch.script.ScriptException: compile error
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.convertToScriptException(PainlessScriptEngineService.java:264) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:176) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
    [elasticsearch] Caused by: java.lang.IllegalArgumentException: While loop has no escape.
    [elasticsearch]         at org.elasticsearch.painless.Executable$Script.compile(while (true) {} @ <inline script>:1) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SWhile.analyze(SWhile.java:74) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:190) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:162) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.Compiler.compile(Compiler.java:104) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:171) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) ~[elastic [...]

2016-09-22 14:04 UTC, tlrx commented
@jpountz I changed this PR to try something slightly different. It now checks the map before building it. This way it only keeps objects references during the check. It is still not perfect but I'd like to have your opinion on this. Thanks

2016-09-23 11:14 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java
> +                it = new Iterator<Object>() {
let's use Arrays.asList?

2016-09-23 11:15 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java
> +            }
let's throw an exception in the else clause since it should never happen if I read the rest of the code correctly?

2016-09-23 11:16 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java
> +            }
and remove the below null check

2016-09-23 11:17 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java
> +                it = new Iterator<Object>() {
actually it would be easier to create an iterable than in iterator I think?

2016-09-23 11:18 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java
> +            }
otherwise I would be happy to just return in the else block and remove the instanceof check in the while loop below

2016-09-23 11:19 UTC, jpountz requested changes
I like it better. I left a couple comments.

2016-10-10 10:25 UTC, tlrx commented
@jpountz I updated the code according to your comments. Can you please have another look? Thanks

2016-10-10 13:21 UTC, jpountz approved these changes
I left one minor comment, otherwise LGTM.

2016-10-10 13:21 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java
> +            Iterable it;
can you use wildcard generics to avoid compiler warnings? (`Iterable<?>`)

2016-10-11 08:28 UTC, tlrx commented
retest this please

2016-10-11 08:34 UTC, jpountz approved these changes
LGTM

2016-10-11 09:41 UTC, merged

2016-10-11 09:42 UTC, tlrx commented
Thanks @jpountz

2016-10-11 09:50 UTC, s1monw commented
I wonder if we should only do this when assertions are enabled? it looks like there are many recursions happening etc.

2016-10-11 10:16 UTC, jpountz commented
The point seems to be about avoiding the stack overflow on production clusters, so I don't think only doing it when assertions are on would help?

2016-10-11 10:17 UTC, tlrx commented
Assertions are enabled only for tests, right? Here we want to throw an exception if we know that the `XContentBuilder` is going to enter an infinite recursive state when building a self-referencing map at runtime.

2016-10-11 10:26 UTC, s1monw commented
fair enough