Make ByteSizeUnit implements Writeable
elastic/elasticsearch pull request #20557
Opened 2016-09-19 15:39 UTC by tlrx

This commit makes `ByteSizeUnit` implement `Writeable`.

2016-09-19 15:54 UTC, javanna requested changes
left two small comments, LGTM otherwise

2016-09-19 16:18 UTC, tlrx commented on core/src/main/java/org/elasticsearch/common/unit/ByteSizeUnit.java
> +            case 0:
Yes

2016-09-19 16:18 UTC, tlrx commented on core/src/test/java/org/elasticsearch/common/unit/ByteSizeUnitTests.java
> +        IllegalArgumentException e = expectThrows(IllegalArgumentException.class, () -> ByteSizeUnit.fromId(randomId));
Ok

2016-09-19 16:18 UTC, tlrx commented
@javanna I updated the code according to your comments.

2016-09-19 16:42 UTC, javanna commented on core/src/main/java/org/elasticsearch/common/unit/ByteSizeUnit.java
> +    private final byte id;
nit: how about simply using the ordinal of the enum? we would have to be careful with the order if we add more units, which we are not likely to do. Also, in any case we would have to be careful with be comp anyways.

2016-09-19 16:43 UTC, javanna approved these changes
left a minor comment, LGTM though

2016-09-19 19:41 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java
> +    public ByteSizeUnit readByteSizeUnit() throws IOException {
I think this should just be a static method on `ByteSizeUnit`.

2016-09-19 19:41 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java
> +    public ByteSizeUnit readByteSizeUnit() throws IOException {
We do that in a lot of places in queries and aggregations.

2016-09-19 19:43 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java
> +        unit = ByteSizeUnit.BYTES;
Did you want to do the reading/writing of the unit here? That wouldn't make the PR too huge and it seems like what we want?

2016-09-19 19:43 UTC, nik9000 requested changes

2016-09-20 12:28 UTC, tlrx commented on core/src/main/java/org/elasticsearch/common/unit/ByteSizeUnit.java
> +    private final byte id;
Sure. I usually don't like to use ordinal to serialize enums but I agree, we're not going to add new units anytime soon :)

2016-09-20 12:31 UTC, tlrx commented on core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java
> +        unit = ByteSizeUnit.BYTES;
I'm changing this one thing at a time - next will be ByteSizeValue serialization. So if you're OK I'd like to keep this as it is for now and change it in a follow up PR.

2016-09-20 13:18 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java
> +        unit = ByteSizeUnit.BYTES;
Fine be me.

2016-09-20 13:19 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/common/unit/ByteSizeUnit.java
> +    private static final ByteSizeUnit[] UNITS = new ByteSizeUnit[ByteSizeUnit.values().length];
I think this is just a duplicate of `BytesSizeUnit.values()`?

2016-09-20 14:15 UTC, tlrx commented on core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java
> +        unit = ByteSizeUnit.BYTES;
Thanks Nik

2016-09-20 14:15 UTC, tlrx commented on core/src/main/java/org/elasticsearch/common/unit/ByteSizeUnit.java
> +    private static final ByteSizeUnit[] UNITS = new ByteSizeUnit[ByteSizeUnit.values().length];
Raah... yes, I blindly updated the code but this is not needed anymore.

2016-09-20 14:16 UTC, tlrx commented
retest this please

2016-09-20 14:28 UTC, nik9000 approved these changes

2016-09-22 12:42 UTC, merged

2016-09-22 12:42 UTC, tlrx commented
Thanks @nik9000 @javanna !