`index.routing.allocation.initial_recovery` limits replica allocation
elastic/elasticsearch pull request #20589
Opened 2016-09-20 20:18 UTC by bleskes

`index.routing.allocation.initial_recovery` is used with index shrinking to make sure the new index's primary is assigned to the node that holds a copy of each of the source index shards. Sadly with the introduction of `RecoverySource` a regression was introduced that limits the allocation of replicas of the new index.

2016-09-20 20:18 UTC, bleskes commented
@ywelsch or @s1monw do you mind taking a look?

2016-09-21 07:21 UTC, s1monw commented
you really need to work on your commit messages

2016-09-21 07:22 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/routing/RecoverySource.java
> +    public static boolean isInitialRecovery(RecoverySource.Type type) {
can we have a java doc comment here explaining what it does

2016-09-21 07:22 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDecider.java
> +            if (RecoverySource.isInitialRecovery(shardRouting.recoverySource().getType()) &&
just a nit, can we move the `initialRecoveryFilters != null` first since it might be able to skip the lookup then

2016-09-21 07:23 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDecider.java
> +            if (RecoverySource.isInitialRecovery(shardRouting.recoverySource().getType()) &&
I hope jit takes care of this to be honest

2016-09-21 07:23 UTC, s1monw commented on core/src/test/java/org/elasticsearch/action/admin/indices/create/CreateIndexIT.java
> +        internalCluster().ensureAtLeastNumDataNodes(4);
can we make this a `randomIntBetween(2, 4)`

2016-09-21 07:24 UTC, s1monw commented on core/src/test/java/org/elasticsearch/action/admin/indices/create/CreateIndexIT.java
> +        prepareCreate("source").setSettings(Settings.builder().put(indexSettings())
can we remove the `"number_of_replicas"` again since `indexSettings()` should take care of this

2016-09-21 07:25 UTC, s1monw requested changes
looks good I added some minors here and there

2016-09-21 07:28 UTC, bleskes commented on core/src/test/java/org/elasticsearch/action/admin/indices/create/CreateIndexIT.java
> +        prepareCreate("source").setSettings(Settings.builder().put(indexSettings())
bugger. These are left overs. Sorry for the noise.

2016-09-21 07:29 UTC, bleskes commented on core/src/test/java/org/elasticsearch/action/admin/indices/create/CreateIndexIT.java
> +        internalCluster().ensureAtLeastNumDataNodes(4);
I think putting it back to 2 is fine, because the test infra randomizes the start point. no?

2016-09-21 07:44 UTC, bleskes commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDecider.java
> +            if (RecoverySource.isInitialRecovery(shardRouting.recoverySource().getType()) &&
changed.

2016-09-21 07:44 UTC, bleskes commented on core/src/main/java/org/elasticsearch/cluster/routing/RecoverySource.java
> +    public static boolean isInitialRecovery(RecoverySource.Type type) {
updated

2016-09-21 07:45 UTC, bleskes commented
thx @s1monw . I addressed all comments. Can you take a second look?

2016-09-21 08:11 UTC, s1monw commented on core/src/test/java/org/elasticsearch/action/admin/indices/create/CreateIndexIT.java
> +        internalCluster().ensureAtLeastNumDataNodes(2);
I still think that we should rarely force 4?

2016-09-21 08:11 UTC, s1monw approved these changes
I left one comment in the test but no need to review again

2016-09-21 08:58 UTC, bleskes commented on core/src/test/java/org/elasticsearch/action/admin/indices/create/CreateIndexIT.java
> +        internalCluster().ensureAtLeastNumDataNodes(2);
I agree but isn't it taken care of by `InternalTestCluster#DEFAULT_MAX_NUM_DATA_NODES`?

2016-09-21 10:40 UTC, merged