Add test for using fuzziness parameter in multi_match query
elastic/elasticsearch pull request #20673
Opened 2016-09-27 22:05 UTC by cbuescher

There was an issue with using fuzziness parameter in multi_match query that has been reported in #18710 and was fixed in Lucene 6.2 that is now used on master. In order to verify that fix and close the original issue this PR adds the test from that issue as an integration test.

Closes #18710

2016-09-27 22:22 UTC, nik9000 requested changes

2016-09-27 22:22 UTC, nik9000 commented on core/src/test/java/org/elasticsearch/search/query/MultiMatchQueryIT.java
> +     * see https://github.com/elastic/elasticsearch/issues/18710
I'm fine with adding a link in the javadocs but could you add a short explanation so I don't have to go read the link? When I'm scanning javadocs there is 0% chance I'll go and read the link.

2016-09-27 22:22 UTC, nik9000 commented on core/src/test/java/org/elasticsearch/search/query/MultiMatchQueryIT.java
> +        indexRandom(true, false, builders);
If it is really important that these docs end up on separate shards can you add an assertion that they are on separate shards? That would explain the `true, false, builder` thing.

2016-09-28 10:04 UTC, cbuescher commented
@nik9000 thanks for the review, I added a hopefully better descrition to the test and also added checks that the two test documents live on different shards. This should communicate better that this test relies on this setup.

2016-10-12 13:49 UTC, nik9000 approved these changes

2016-10-12 13:49 UTC, nik9000 commented
Thanks for making the changes! Sorry I didn't notice that you'd made them.

2016-10-12 14:57 UTC, merged