Simplify GlobalCheckpointService and properly hook it for cluster state updates
elastic/elasticsearch pull request #20720
Opened 2016-10-03 15:06 UTC by bleskes

During a recent merge from master, we lost the bridge from IndicesClusterStateService to the GlobalCheckpointService of primary shards, notifying them of changes to the current set of active/initilizing shards. This commits add the bridge back (with unit tests). It also simplifies the GlobalCheckpoint tracking to use a simpler model (which makes use the fact that the global check point sync is done periodically).

The old integration CheckpointIT test is moved to IndexLevelReplicationTests. I also added simliar assertions to RelocationsIT, which surfaced a bug in the primary relocation logic and how it plays with global checkpoint updates. The test is currently await-fixed and will be fixed in a follow up issue.

2016-10-12 17:06 UTC, jasontedor reviewed
This is a nice simplification @bleskes. I left some nits.

2016-10-12 17:06 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/index/seqno/GlobalCheckpointTests.java
> +        Map<String, Long> tmpAllocations = randomAllocations(0, 5);
Can we call this `tmpActive` and not reuse it for the initializing as well `tmpInitializing`?

2016-10-12 17:06 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/index/seqno/GlobalCheckpointTests.java
> +            new HashSet<>(randomSubsetOf(randomInt(active.size()-1), active.keySet())),
Nit: `active.size()-1` -> `active.size() - 1`

2016-10-12 17:06 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/index/seqno/GlobalCheckpointTests.java
> +        randomSubsetOf(randomInt(initializing.size()-1),
Nit: `initializing.size()-1` -> `initializing.size() - 1`

2016-10-14 13:49 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointService.java
> +     * checkpoint back;
not semicolon , no enter. :)

2016-10-14 13:52 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointService.java
>       * notifies the service of a local checkpoint. if the checkpoint is lower than the currently known one,
Nit correction badge unlocked.

2016-10-14 13:53 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointService.java
> +                logger.trace("skipping update local checkpoint [{}], current check point is higher " +
fixed

2016-10-14 13:53 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointService.java
> +     * have been removed
fixed

2016-10-14 13:53 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointService.java
>       * where the primary knows all operation bellow the global checkpoint have been completed on this shard.
this one I will never learn.

2016-10-14 13:54 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointService.java
>              // master have change its mind and removed this allocation, ignore.
fixed.

2016-10-14 13:55 UTC, bleskes commented on core/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java
> +         * see {@link GlobalCheckpointService#updateAllocationIdsFromMaster(Set, Set)} for details.
grammar is hard.

2016-10-14 13:56 UTC, bleskes commented on core/src/test/java/org/elasticsearch/index/replication/ESIndexLevelReplicationTestCase.java
> +            PlainActionFuture<ReplicationResponse> listner = new PlainActionFuture<>();
good catch

2016-10-14 14:05 UTC, bleskes commented on core/src/test/java/org/elasticsearch/index/seqno/GlobalCheckpointTests.java
> +        if (allocations.isEmpty()) {
++

2016-10-14 14:05 UTC, bleskes commented on core/src/test/java/org/elasticsearch/index/seqno/GlobalCheckpointTests.java
> +        Map<String, Long> tmpAllocations = randomAllocations(0, 5);
agreed this is confusing. Fixed.

2016-10-14 14:09 UTC, bleskes commented
Thx @jasontedor . I address all your comments. can you take a second look?

2016-10-15 00:17 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java
> +         * see {@link GlobalCheckpointService#updateAllocationIdsFromMaster(Set, Set)} for details.
Computers are harder.

2016-10-15 00:18 UTC, jasontedor requested changes
Back to you. :smile:

2016-10-15 00:18 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointService.java
> + * has been notified of this fact, we also include shards in that have completed recovery. These shards have received
Can you fix this one?

2016-10-15 07:10 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointService.java
> + * has been notified of this fact, we also include shards in that have completed recovery. These shards have received
yep. missed it. it is fixed now.

2016-10-15 07:11 UTC, bleskes commented on core/src/test/java/org/elasticsearch/index/seqno/GlobalCheckpointTests.java
> +            new HashSet<>(randomSubsetOf(randomInt(active.size()-1), active.keySet())),
added

2016-10-15 07:12 UTC, bleskes commented
@jasontedor thx. I pushed two more commits.

2016-10-17 12:33 UTC, jasontedor approved these changes
LGTM.

2016-10-17 14:33 UTC, merged

2016-10-17 14:33 UTC, bleskes commented
thx @jasontedor