Source filtering should treat dots in field names as sub objects.
elastic/elasticsearch pull request #20736
Opened 2016-10-04 13:52 UTC by jpountz

Mappings treat dots in field names as sub objects, for instance

```
{
  "a.b": "c"
}
```

generates the same dynamic mappings as

```
{
  "a": {
    "b": "c"
  }
}
```

Source filtering should be consistent with this behaviour so that an include
list containing `a` should include fields whose name is `a.b`.

To make this change easier, source filtering was refactored to use automata.
The ability to treat dots in field names as sub objects is provided by the
`makeMatchDotsInFieldNames` method of `XContentMapValues`.

Closes #20719

2016-10-05 15:02 UTC, jbaiera commented
+1 LGTM, Thanks @jpountz

2016-10-05 22:26 UTC, jpountz commented
@mikemccand would you ming having a quick look at the usage of the Automaton API before it gets merged?

2016-10-06 00:14 UTC, nik9000 commented
If Mike doesn't get to it i can look again in the morning. I looked earlier
at it and didn't have any strong thoughts though.

On Oct 5, 2016 6:26 PM, "Adrien Grand" <notifications@github.com> wrote:

> @mikemccand <https://github.com/mikemccand> would you ming having a quick
> look at the usage of the Automaton API before it gets merged?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elastic/elasticsearch/pull/20736#issuecomment-251817747>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AANLosvwqm1p8Ri61jHxnY4k7b3NVa8cks5qxCQlgaJpZM4KNs9q>
> .
>

2016-10-06 15:41 UTC, nik9000 requested changes

2016-10-06 15:41 UTC, nik9000 commented on core/src/test/java/org/elasticsearch/common/xcontent/support/XContentMapValuesTests.java
> +        assertEquals(expected, filtered);
Could you add a test with strings longer than one char? Sadly, you probably also want on that has a character that is two java `char` wide as well. I'd be good to assert everything works right when you fail half way through the word - say you try and match `cat` against the pattern `cbs`. The `c` works, the `a` would put you in the `-1` state, etc.

2016-10-07 14:05 UTC, jpountz commented
@nik9000 I pushed more tests as requested.

2016-10-07 14:10 UTC, nik9000 approved these changes
LGTM. I was worried about the contract of step. I figured you'd got it right but that didn't leave any defense against it changing out from under us.

2016-10-10 07:32 UTC, merged

2016-10-10 16:45 UTC, mikemccand reviewed
Woops, sorry I missed my calling here ;)

I left a few small comments.

2016-10-10 16:45 UTC, mikemccand commented on core/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java
> +                include, include.getInitialState(),
The initial state is always 0 w/ Lucene's automata ... I'll fix Lucene to make this clearer :)

2016-10-10 16:45 UTC, mikemccand commented on core/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java
> +        // we want all sub properties to match as soon as an object matches
I wonder if you could use `Operations.minus`, but then union that result with another automaton that accepts any string matched by the include automaton followed by `.` (literal) followed by any suffix?  Then a single automaton could do all the matching I think?

2016-10-10 16:45 UTC, mikemccand commented on core/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java
> +        CharacterRunAutomaton matchAllAutomaton = new CharacterRunAutomaton(Automata.makeAnyString());
Isn't this invoked once per returned hit?  We should maybe (separate change) compile the automaton/a up front, and re-use that across all the hits?