Document date math use in the rollover API
elastic/elasticsearch pull request #20780
Opened 2016-10-06 15:37 UTC by clintongormley

Relates to #20709

2016-10-06 15:37 UTC, clintongormley commented
@s1monw could you take a look please?

2016-10-06 18:02 UTC, s1monw requested changes

2016-10-06 18:02 UTC, s1monw commented on docs/reference/indices/rollover-index.asciidoc
> +<2> Rolls over to a new index with today's date, e.g. `logs-2016.11.01`
sorry this is not how it works you have to create an index `<logs-{now/d}-1>` first and then when you rollover we increment the counter if it's a new day or not. So I think this entire writeup is wrong ?

2016-10-06 19:09 UTC, clintongormley commented on docs/reference/indices/rollover-index.asciidoc
> +<2> Rolls over to a new index with today's date, e.g. `logs-2016.11.01`
Doh

2016-10-06 19:09 UTC, clintongormley commented
Docs fixed to represent what actually happens in the code :)

2016-10-06 21:26 UTC, s1monw approved these changes
LGTM left one minor comment

2016-10-06 21:26 UTC, s1monw commented on docs/reference/indices/rollover-index.asciidoc
> +over. For instance:
should we also add an example how to search those indices then?

2016-10-07 13:49 UTC, clintongormley commented on docs/reference/indices/rollover-index.asciidoc
> +over. For instance:
Example added

2016-10-07 13:49 UTC, merged