Fixed writeable name from range to geo_distance
elastic/elasticsearch pull request #20860
Opened 2016-10-11 14:34 UTC by brandonkearby

Fixed writeable name from range to geo_distance

2016-10-11 14:47 UTC, s1monw commented
wow how did you figure out about this? any chance you can provide a test case. I also see you didn't sign the CLA can you do so?

2016-10-11 14:54 UTC, brandonkearby commented
Hi, @s1monw I'm currently working on a high-level rest client and was testing it against the master branch. That's how I figured it out. My unit test failed. [https://github.com/brandonkearby/elasticsearch/blob/rest-client-1.4.1/src/test/java/org/elasticsearch/client/rest/RestClientTest.java](RestClientTest)

I just signed the CLA. It's under my work email: bkearby@sprinklr.com.

2016-10-11 15:00 UTC, nik9000 commented
This looks right to me and I've tentatively labeled this as an aggregations bug. Can you add a unit or integration test or *something* that fails without the fix? `org.elasticsearch.search.aggregations.bucket.GeoDistanceIT` is an integration test with assertions about the geo distance aggregation. I'm happy to help in any way you'd like. I expect I was the one who broke this in the first place.

2016-10-11 15:01 UTC, nik9000 commented
I'll have a look at the cla thing.

2016-10-11 15:02 UTC, nik9000 commented
Poking the ticket so the CLA checker will recheck.

2016-10-11 15:05 UTC, karmi commented
Hi @brandonkearby, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/20860.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

2016-10-11 15:06 UTC, brandonkearby commented
Hi @karmi  Just added my work email to my github account as a secondary email.

2016-10-11 15:08 UTC, brandonkearby commented
Added my git commit email as well.

2016-10-11 15:09 UTC, nik9000 commented
@brandonkearby that did the trick!

2016-10-11 15:09 UTC, brandonkearby commented
WooT

2016-10-11 15:12 UTC, brandonkearby commented
Hi @nik9000, I'll work on adding a test that will fail.

2016-10-11 15:13 UTC, nik9000 commented
Thanks!

2016-10-11 17:10 UTC, nik9000 requested changes

2016-10-11 17:10 UTC, nik9000 commented on core/src/test/java/org/elasticsearch/search/geo/GeoDistanceIT.java
> +        assertNotNull(geoDistance);
Could you assert the result is correct while you are here?

2016-10-11 17:12 UTC, nik9000 commented
@brandonkearby thanks for adding the test! I've reviewed it and left a comment - just extra coverage on top of the "did it blow up" test that you added to catch this error. If it is too much trouble I'm happy to do it myself in a followup but if you can do it it'd be lovely!

2016-10-11 17:12 UTC, brandonkearby commented
Hi @nik9000, I've added a test. One interesting thing I noticed is InternalGeoDistance use to implement GeoDistance (interface). Now it no longer implements it as it's been converted to an enum. In the test provided I'm casting to InternalGeoDistance just to prove that class isn't the one we are getting.

2016-10-11 17:18 UTC, nik9000 commented
> One interesting thing I noticed is InternalGeoDistance use to implement GeoDistance (interface). Now it no longer implements it as it's been converted to an enum.

I'm not really sure what happened there. I'm not super sure what the vision of the transport API was for these classes. For now the cast is fine.

2016-10-11 17:45 UTC, brandonkearby commented
Hi @nik9000, Added asserts, but they are failing :(

2016-10-11 17:50 UTC, nik9000 commented
Fun! I'll fetch it locally in a few minutes and have a look. Thanks so much!

2016-10-11 18:22 UTC, nik9000 commented
@brandonkearby I think the second test needs to set up the mapping like this: https://gist.github.com/nik9000/29d0b18f5dde28d3e76b26d1d28f67f1

2016-10-11 19:16 UTC, brandonkearby commented
@nik9000 Yep, that fixed it! 👍

2016-10-11 19:24 UTC, nik9000 approved these changes

2016-10-11 19:24 UTC, nik9000 commented
OK! Looks good to me! I'll merge and backport it in a few minutes.

2016-10-11 19:30 UTC, brandonkearby commented
@nik9000 Perfect thanks!

2016-10-11 20:02 UTC, nik9000 commented
@brandonkearby the build fails for me because of the wildcard import - we disallow those in the code base because they make it more difficult for our non-IDE using friends to track to track down imports and it is fairly easy for those of us that do use IDEs to teach them not to add them. I'll remove the wildcard import before merging and backporting.

2016-10-11 20:02 UTC, nik9000 commented
> I'll remove the wildcard import before merging and backporting.

Or you can if you like, either way.

2016-10-11 20:55 UTC, brandonkearby commented
@nik9000 Thanks I'll change my ide settings for next time :)

2016-10-11 20:56 UTC, nik9000 commented
> @nik9000 Thanks I'll change my ide settings for next time :)

Awesome.

2016-10-11 20:56 UTC, merged

2016-10-11 21:09 UTC, nik9000 commented
OK! I've merged into master and I've staged the backports to 5.x and am running tests locally for that. I'll edit this comment with the hashes once I've pushed that and do the same for 5.0. Thanks for fixing this @brandonkearby!


master: a3908c4c406e29e38b44dd74a112ba3564898202 (+ cb8fe00b0ebd16a0bd12106ed6785eabac2b658b)
5.x:
5.0:

2016-10-12 00:23 UTC, nik9000 commented
And done! Thanks again @brandonkearby !

2016-10-12 11:38 UTC, brandonkearby commented
Anytime @nik9000 glad to help :)