Plugins: Add back user agent when downloading plugins
elastic/elasticsearch pull request #20872
Opened 2016-10-11 20:42 UTC by rjernst

This adds back a User-Agent header, which we had before large plugin
script refactorings for 5.0. The value is now `elasticsearch-plugin`
which is the name of the script.

2016-10-11 20:44 UTC, jasontedor requested changes
Any chance of a test so that it doesn't get lost in a refactoring?

2016-10-11 20:48 UTC, rjernst commented
Unfortunately we don't have any tests right now for actually *downloading* a plugin zip (all the tests are focused on what we do with a local file url). I was working on a large refactoring long ago with Robert that would add a fixture based integ test where we could check downloading official and maven based plugins, but that work is horribly out of date and has a lot of other stuff in it...(https://github.com/rjernst/elasticsearch/tree/separate_plugin_cli)

2016-10-11 20:52 UTC, jasontedor commented
Right, but can't we do something really naive right now like exposing the URL connection to tests and asserting on `URLConnection#getRequestProperties`? At least it's something?

2016-10-11 20:58 UTC, rjernst commented
I don't think it is worthwhile to do a bunch of refactoring (this is a private method, and url handling is completely inside it, there is no urlconnection in internal api anywhere) just to test for this header, when the right thing is to have real integration tests. I understand the apprehension with this as I would love to have a unit test, but I want to keep this change minimal so that it can be backported for the 5.0 release (I can open an issue about testing url downloading?).

2016-10-19 01:30 UTC, jasontedor approved these changes
Let's get this in, but open a blocker to add real tests for 6.0.0.

2016-10-19 01:36 UTC, rjernst commented
Thanks, here is a blocker issue for 6.0: #21008

2016-10-19 01:36 UTC, merged