REST API parser should fail on duplicate params/paths/methods/parts
elastic/elasticsearch pull request #20940
Opened 2016-10-14 12:39 UTC by tlrx

This PR changes the current REST API parser to make it fail and throw an exception when a REST specification file contains a duplicated parameters, or path, or method, or path part. This was suggested by @javanna in https://github.com/elastic/elasticsearch/pull/20934#pullrequestreview-4227796

2016-10-14 12:50 UTC, javanna approved these changes
thanks a lot @tlrx LGTM

2016-10-14 12:52 UTC, jasontedor requested changes
I left a comment, I don't have a good suggestion for what it should be but `IOException` feels wrong.

2016-10-14 12:52 UTC, jasontedor commented on test/framework/src/main/java/org/elasticsearch/test/rest/yaml/restspec/ClientYamlSuiteRestApiParser.java
> +                            throw new IOException("Found duplicate method [" + method + "]");
I don't think these should be IOException.

2016-10-14 12:57 UTC, tlrx commented on test/framework/src/main/java/org/elasticsearch/test/rest/yaml/restspec/ClientYamlSuiteRestApiParser.java
> +                            throw new IOException("Found duplicate method [" + method + "]");
I used the same exception type that was already used and it did not feel weird to me. We could use `ElasticsearchParseException` instead, would that be more adapted to you?

2016-10-14 13:44 UTC, javanna commented on test/framework/src/main/java/org/elasticsearch/test/rest/yaml/restspec/ClientYamlSuiteRestApiParser.java
> +                            throw new IOException("Found duplicate method [" + method + "]");
I had missed this thanks @jasontedor . IllegalArgumentException ?

2016-10-14 14:22 UTC, jasontedor commented on test/framework/src/main/java/org/elasticsearch/test/rest/yaml/restspec/ClientYamlSuiteRestApiParser.java
> +                            throw new IOException("Found duplicate method [" + method + "]");
I'm fine with `IllegalArgumentException`, in all the places of course. :smile:

2016-10-14 15:47 UTC, tlrx commented on test/framework/src/main/java/org/elasticsearch/test/rest/yaml/restspec/ClientYamlSuiteRestApiParser.java
> +                            throw new IOException("Found duplicate method [" + method + "]");
Now I feel bad because I should have seen that. `IllegalArgumentException` makes sense.

2016-10-14 15:47 UTC, tlrx commented
@jasontedor I just updated the code.

2016-10-14 15:51 UTC, javanna commented on test/framework/src/main/java/org/elasticsearch/test/rest/yaml/restspec/ClientYamlSuiteRestApiParser.java
> +                            throw new IOException("Found duplicate method [" + method + "]");
oh come one don't feel bad Tanguy :)

2016-10-14 15:51 UTC, javanna approved these changes
LGTM

2016-10-14 16:21 UTC, jasontedor approved these changes
LGTM.

2016-10-14 16:22 UTC, jasontedor commented on test/framework/src/main/java/org/elasticsearch/test/rest/yaml/restspec/ClientYamlSuiteRestApiParser.java
> +                            throw new IOException("Found duplicate method [" + method + "]");
Yeah, don't feel bad, that's what reviews are for. :smile:

2016-10-14 16:22 UTC, jasontedor commented
> I just updated the code.

Thanks @tlrx, fire at will.

2016-10-17 07:19 UTC, merged

2016-10-17 07:19 UTC, tlrx commented
Thanks @jasontedor & @javanna for the review!