delete file in finally block
elastic/elasticsearch pull request #21007
Opened 2016-10-19 01:17 UTC by liweinan0423

Move the delete to `finally` block to ensure the file will be deleted when there is a left over temp file from a crash.

2016-10-19 01:41 UTC, jasontedor commented
test this please

2016-10-19 06:03 UTC, liweinan0423 commented
The Jenkins build seems contains many other commits?

2016-10-19 09:53 UTC, bleskes requested changes

2016-10-19 09:53 UTC, bleskes commented on core/src/main/java/org/elasticsearch/env/NodeEnvironment.java
> +                Files.deleteIfExists(resolve);
can we make sure not to delete a file that wasn't created and hide the original exception?

we typically do this:
```
bool success = false;
try {
  do something
  success = true;
} finally {
  if (success) {
    clean up
  }
}
```

2016-10-23 01:11 UTC, liweinan0423 commented on core/src/main/java/org/elasticsearch/env/NodeEnvironment.java
> +                Files.deleteIfExists(resolve);
Thanks for you advice. I have pushed a new commit.

2016-10-23 19:06 UTC, bleskes commented
test this please

2016-10-24 14:38 UTC, bleskes approved these changes
LGTM. I'll merge it in. Thank you!!

2016-10-24 14:41 UTC, merged

2016-10-25 18:18 UTC, liweinan0423 commented
The tests are successful on CI - https://elasticsearch-ci.elastic.co/job/elastic-elasticsearch-pull-request/582/

Sent from my iPhone

> On 24 Oct 2016, at 3:07 AM, Boaz Leskes <notifications@github.com> wrote:
> 
> test this please
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-10-26 15:30 UTC, s1monw commented
@bleskes this change is doing exactly the same thing it was doing before. It only deletes the file if the creation was successful. I think we should revert it and make it try to delete the file even if we run into an exception this can possibly prevent the issue but if the system crashes in between there is nothing we can do about it. Either way this change is only confusing.

2016-10-26 15:43 UTC, bleskes commented
@s1monw bleh. I have no idea what I was thinking. What I was going for is not hide the original exception from the file creation. I'll fix.

2016-10-27 15:34 UTC, liweinan0423 commented
I suggest if we detect the file already exists, try to delete it first then create it again, then delete it in the finally block.