Update synonym-tokenfilter.asciidoc
elastic/elasticsearch pull request #21015
Opened 2016-10-19 10:36 UTC by leegee

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

Documents comment from Yannick Welsch in Forums:  https://discuss.elastic.co/t/500-error-synonym-file-cant-be-read/62345/3

2016-10-19 12:07 UTC, nik9000 requested changes

2016-10-19 12:07 UTC, nik9000 commented on docs/reference/analysis/tokenfilters/synonym-tokenfilter.asciidoc
> +Since the introduction of the security manager in ElasticSearch version 2.0, it is no longer possible to set a custom file path outside of the configuration directory for `path` settings in char or t
I'd prefer to expand the paragraph around line 30 with words like "absolute paths are not supported".

2016-10-19 12:11 UTC, nik9000 commented
Thanks for submitting this @leegee. I've left a comment about combining the new paragraph into the one above that already talks about synonym file location.

At some point we'll need to placate the CLA checking robot. If you haven't signed the [CLA](https://www.elastic.co/contributor-agreement) please have a look at it and sign it if you are able. We need it for all submissions. Once you've signed it if you leave a comment here the robot will recheck it. It verifies that the email address on your patch matches one in your github account matches one you added to the signature.

2017-02-23 18:14 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-03-01 15:41 UTC, clintongormley commented
No feedback. Closing

2017-03-01 15:41 UTC, closed without merging