Only allow the master to update the list of nodes in the cluster state
elastic/elasticsearch pull request #21092
Opened 2016-10-24 13:09 UTC by ywelsch

The cluster state on a node is updated either
- by incoming cluster states that are received from the active master or
- by the node itself when it notices that the master has gone.

In the second case, the node adds the NO_MASTER_BLOCK and removes the current master as active master from its cluster state. In one particular case, it would also update the list of nodes, removing the master node that just failed. In the future, we want a clear separation between actions that can be executed by a master publishing a cluster state and a node locally updating its cluster state when no active master is around.

2016-10-24 13:12 UTC, bleskes approved these changes
LGTM but let's give this some CI hours before merging...

2016-10-24 13:19 UTC, jasontedor requested changes
I left a nit. 😄

2016-10-24 13:19 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/cluster/MinimumMasterNodesIT.java
> +        // verify that both nodes still in the cluster state but no master
Nit: `both nodes still` -> `both nodes are still` and `but no master` -> `but there is no master`

2016-10-24 13:27 UTC, ywelsch commented on core/src/test/java/org/elasticsearch/cluster/MinimumMasterNodesIT.java
> +        // verify that both nodes still in the cluster state but no master
I've pushed 77fe95b. Hope this is more to your taste 🐇

2016-10-24 13:34 UTC, jasontedor approved these changes
LGTM.

2016-10-24 17:26 UTC, ywelsch commented
@bleskes @jasontedor I ran CI in the afternoon and observed one test failing. The test `testSendingShardFailure` fails as follows when using the "network unresponsive" disruption type:

- isolate node_t2 from node_t0 and node_t1 with "network unresponsive" failure type
- send shard failure from node_t2 to node_t0 which is master
- remove disruption and wait for cluster to be healed (= OK)
- wait for shard failed listener to be called (must have either failed or success).

The last step times out with the change above because the NodeConnectionsService doesn't disconnect anymore from the master during the partition. I wonder if the network failure type "network unresponsive" is unrealistic here as it just swallows the request and keeps it swallowed even after the network partition has been healed.

2016-10-25 08:45 UTC, ywelsch commented
I've opened #21107 as possible fix.

2016-10-25 09:10 UTC, bleskes commented
yes, the unresponsive network partition is not realistic and should probably be renamed to reflect it. I think in this case we can remove it's usage from the test and push this change. We can then discuss the unresponsive network partition and potential changes to shard state actions separately

2016-10-25 16:07 UTC, bleskes commented
the last change LGTM2

2016-10-26 07:24 UTC, merged

2016-10-26 07:24 UTC, ywelsch commented
thanks for the reviews @bleskes @jasontedor

2016-12-23 13:44 UTC, ywelsch commented
backported to 5.2.0