ensure the XContentBuilder is always closed in RestBuilderListener
elastic/elasticsearch pull request #21124
Opened 2016-10-26 02:27 UTC by jaymode

There may be cases where the XContentBuilder is not used and therefore it never gets closed, which can cause a leak of bytes. This change moves the creation of the builder into a try with resources block.

2016-10-26 05:23 UTC, dadoonet approved these changes

2016-10-26 05:23 UTC, dadoonet commented
I think this should go as well in 5.0 branch, no?

2016-10-26 06:49 UTC, bleskes commented
I'm not sure we want to automatically close. The current api is set up so that we expect to use the builder we give them (there is no way to  not have a builder) - if they don't it's probably a bug we're hiding (or we should give an official way to not have a builder created at all). I think we should add an assertion that verifies the builder is closed when buildResponse returns

2016-10-26 07:32 UTC, s1monw commented
@bleskes maybe both, assertion and auto close? I mean some plugins might not test this (3rd party ) and then we are leaking bytes since assertions are off?

2016-10-26 07:52 UTC, bleskes commented
@s1monw yeah , that's what I meant ++ . Keep code as is but make sure builder is closed when buildResponse returns

2016-10-26 12:58 UTC, jaymode commented
> I think this should go as well in 5.0 branch, no?

I think that makes sense, I added the 5.0.1 label.

> maybe both, assertion and auto close?

I pushed [5a17d14](https://github.com/elastic/elasticsearch/pull/21124/commits/5a17d141e1cffffd328387dfddef6b17c1628963), which adds the assertion while keeping auto close.

2016-10-26 14:02 UTC, s1monw requested changes
left two comments

2016-10-26 14:02 UTC, s1monw commented on core/src/main/java/org/elasticsearch/rest/action/RestBuilderListener.java
> +            assert assertionsEnabled == false || builder.isClosed() : "callers should ensure the XContentBuilder is closed themselves";
can you add a protected method `assert assertBuilderClosed(builder)` we can override in tests instead. this is very confusing and I hate static mutable vars

2016-10-26 14:02 UTC, s1monw commented on core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java
>      public XContentGenerator generator() {
would it be enough to only add `isClosed` to XContentGenerator? and maybe add a javadoc?

2016-10-26 14:19 UTC, jaymode commented on core/src/main/java/org/elasticsearch/rest/action/RestBuilderListener.java
> +            assert assertionsEnabled == false || builder.isClosed() : "callers should ensure the XContentBuilder is closed themselves";
++ that's a much better approach

2016-10-26 19:08 UTC, s1monw commented on core/src/main/java/org/elasticsearch/rest/action/RestBuilderListener.java
> +        return xContentBuilder.generator().isClosed();
I usually do this:
```
assert  xContentBuilder.generator().isClosed();
return true;
```

2016-10-26 19:08 UTC, s1monw approved these changes

2016-10-26 19:08 UTC, s1monw commented
left a minor LGTM otherwise

2016-11-01 10:32 UTC, s1monw commented
@jaymode can we get this in please?

2016-11-01 13:02 UTC, merged