Read indices options in indices upgrade API
elastic/elasticsearch pull request #21281
Opened 2016-11-02 19:02 UTC by javanna

With #21099 we removed support for the ignored allow_no_indices parameter in indices upgrade API. Truth is that ignore_unavailable and expand_wildcards were also ignored, in indices upgrade as well as upgrade status API. Those parameters are though supported internally and settable through java API, hence they should be all supported on the REST layer too.

2016-11-02 19:10 UTC, javanna commented
@gmarz can you have a look? Does it make sense?

2016-11-02 19:34 UTC, gmarz commented
Yea.  The only reason why it was removed from the spec was because specifying it caused an exception in ES.  We had a failing integration test that caught this.

As long as the options are actually used now, then it makes sense. 👍

2016-11-03 12:58 UTC, tlrx requested changes

2016-11-03 12:58 UTC, tlrx commented on rest-api-spec/src/main/resources/rest-api-spec/test/indices.upgrade/10_basic.yaml
> +  - is_false: upgraded_indices.test1
`is_false: upgraded_indices.does_not_exist` instead?

2016-11-03 12:58 UTC, tlrx commented on rest-api-spec/src/main/resources/rest-api-spec/test/indices.upgrade/10_basic.yaml
> +      indices.upgrade:
Same here, can we check the error message in this case? Just to verify that it reports the missing index `does_not_exist`?

2016-11-03 12:58 UTC, tlrx commented on rest-api-spec/src/main/resources/rest-api-spec/test/indices.upgrade/10_basic.yaml
> +      catch: missing
Can we check the error message in this case? Just to verify that it reports the missing index?

2016-11-03 14:37 UTC, javanna commented on rest-api-spec/src/main/resources/rest-api-spec/test/indices.upgrade/10_basic.yaml
> +  - is_false: upgraded_indices.test1
ops, you are right

2016-11-03 14:39 UTC, javanna commented on rest-api-spec/src/main/resources/rest-api-spec/test/indices.upgrade/10_basic.yaml
> +      catch: missing
catch missing means that the status code must be 404. If we check the error message we don't check the status code anymore, the two checks are mutual exclusive. Shall we keep what we have?

2016-11-03 15:02 UTC, tlrx approved these changes

2016-11-03 17:05 UTC, merged