Fixes get snapshot duplicates when asking for _all
elastic/elasticsearch pull request #21340
Opened 2016-11-04 15:01 UTC by abeyad

Before, when requesting to get the snapshots in a repository, if `_all` was
specified for the set of snapshots to get, any in-progress snapshots would
be returned twice.  This commit fixes the issue ensuring that each snapshot,
whether in-progress or completed, is only returned once when making a call to
get snapshots (GET /_snapshot/{repository_name}/_all).

Closes #21335

2016-11-04 18:21 UTC, ywelsch commented
retest this please

2016-11-04 19:02 UTC, ywelsch requested changes
Left some comments

2016-11-04 19:02 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
> +
revert ;)

2016-11-04 19:02 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java
> +            for (SnapshotInfo snapshotInfo : snapshotsService.currentSnapshots(repository)) {
guard this with `isAllSnapshots(request.snapshots()) == false`

2016-11-04 19:02 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java
> +            for (SnapshotId snapshotId : snapshotsService.snapshotIds(repository)) {
guard this with `isCurrentSnapshots(request.snapshots()) == false`

2016-11-04 19:14 UTC, abeyad commented on core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java
> +            for (SnapshotInfo snapshotInfo : snapshotsService.currentSnapshots(repository)) {
if you set `_all` (i.e. `isAllSnapshots(request.snapshots()) == true`), you still want the current snapshots too.

2016-11-04 19:14 UTC, abeyad commented on core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
> +
done

2016-11-04 19:29 UTC, abeyad commented on core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java
> +            for (SnapshotId snapshotId : snapshotsService.snapshotIds(repository)) {
Thinking about this some more, I like the idea of being able to specify `_current` in addition to other snapshots.  I can imagine a user wanting to know the state of snapshots starting with "2016-11-*" and the "current" one.  In this case, we would treat `_current` as a regex that resolves to whatever the currently running snapshots are.  What do you think about that?

2016-11-04 19:46 UTC, abeyad commented on core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java
> +            for (SnapshotId snapshotId : snapshotsService.snapshotIds(repository)) {
I pushed 14e12067cc1da984c6786e22c0f5892bbba7b41e

2016-11-07 18:17 UTC, ywelsch approved these changes
LGTM

2016-11-07 18:17 UTC, ywelsch commented on core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java
> +        assertBusy(() -> {
instead of the assertBusy, maybe use a future above with setWaitForCompletion(true).

2016-11-07 18:29 UTC, abeyad commented on core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java
> +        assertBusy(() -> {
I pushed e00a2a16758da5e49faa3a6416762a3ab31c2551 to improve this

2016-11-07 18:29 UTC, abeyad commented
thanks for the review @ywelsch !

2016-11-07 19:20 UTC, merged

2016-11-07 19:22 UTC, abeyad commented
5.x commit: ff02fb43468919f06dca90b4392c6cb5f1c4dc03
5.0 commit: 7a25b1104d66bb52f2c1b28b6bf2d9f4f35bf1df