Make ensureGreen and ensureYellow wait for cluster size consistency
elastic/elasticsearch pull request #21344
Opened 2016-11-04 17:02 UTC by ywelsch

We currently often use ensureGreen or ensureYellow to check whether the cluster is in a good state again after shutting down a node:
```
stopRandomNode(...);
ensureGreen() / ensureYellow();
```

With the change in #21092, however, it can happen that if the node that is stopped is the master node, another node will become master and publish a cluster state where it is master but where the node that was stopped hasn't been removed yet from the cluster state. It will only publish a second state thereafter where the old master is removed. If the ensureGreen/ensureYellow is timed just right, it will get to execute before the second cluster state update removing the old master and the condition ensureGreen / ensureYellow might not hold at that point anymore.

2016-11-07 12:53 UTC, bleskes requested changes
Left some very minor suggestions. I'm still on the fence if this should be done here or as a functionality of the test cluster (shut down a node -> wait for that to be processed too), where people may opt out of. Let's get this in as is and see _if_ we want to change in the future.

2016-11-07 12:53 UTC, bleskes commented on test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java
> +        if (cluster() != null) {
why is this checked? `client()` needs a cluster to be there, so it should always be non null?

2016-11-07 12:53 UTC, bleskes commented on test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java
> +            healthRequest.waitForGreenStatus();
there is a waitForStatus variant  - should be simpler.

2016-11-07 12:53 UTC, bleskes commented on test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java
> +            healthRequest.waitForNodes(Integer.toString(cluster().size()));
can you add a comment as why we do this?

2016-11-07 16:25 UTC, ywelsch commented
@bleskes I've pushed a change addressing review comments.

2016-11-07 21:09 UTC, bleskes approved these changes
LGTM. Thx @ywelsch

2016-11-07 21:09 UTC, bleskes commented on test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java
> +        if (clusterHealthStatus == ClusterHealthStatus.GREEN) {
nit: we can change this to greater than or equal relationship and check on both statuses.

2016-11-08 10:07 UTC, merged

2016-11-08 10:08 UTC, ywelsch commented
thanks @bleskes

2016-12-23 13:44 UTC, ywelsch commented
backported to 5.2.0