Reference documentation for rank evaluation API
elastic/elasticsearch pull request #21427
Opened 2016-11-09 13:52 UTC by MaineC

This adds a first page of reference documentation to the current state of the
rank evaluation API.

Closes to #21402

@cbuescher Would you mind taking a look?

2016-11-11 13:05 UTC, cbuescher requested changes
Thanks for doing this, this already reads very well. I left a few comments but think this should generally go in more or less like this as a great starting point for further docs.

2016-11-11 13:05 UTC, cbuescher commented on docs/reference/rank-eval.asciidoc
> +       "dcg": {}
Maybe document the "normalize" parameter here. Default is 'false', if set to true, not plain DCG mit nDCG is computed (see wikipedia for reference)

2016-11-16 14:19 UTC, MaineC commented
Updated. I'm wondering whether I should add a brief section explaining the response format as well though.

2016-11-16 14:52 UTC, cbuescher approved these changes

2016-11-16 14:53 UTC, cbuescher approved these changes

2016-11-16 14:56 UTC, cbuescher commented
@MaineC looks great, also +1 on also giving a brief overview about the resonse format. You could do it in this PR or open a follow up task if you want to merge this though.

2016-11-17 09:27 UTC, merged

2016-11-17 09:28 UTC, MaineC commented
Merged this one, will track adding docs for the response format in a separate PR