Null checked for source when calling sourceRef (issue #19279)
elastic/elasticsearch pull request #21431
Opened 2016-11-09 16:18 UTC by thanhtien522

`sourceRef` always throw `NullPointerException` when `source` is `null`

2016-11-09 17:25 UTC, clintongormley commented
Hi @thanhtien522 

Thanks for the PR.  Any chance we can add a failing unit test that passes with your fix in place?

2016-11-09 21:04 UTC, javanna requested changes
thanks for the PR! I left a small comment, would it also be possible to have a small unit test for this added to `InternalSearchHitTests`?

2016-11-09 21:04 UTC, javanna commented on core/src/main/java/org/elasticsearch/search/internal/InternalSearchHit.java
> +            return null;
could you please add the curly brackets around this statement? we tend to use them although not needed around a single, for better readability.

2016-11-10 01:08 UTC, nik9000 approved these changes

2016-11-10 04:26 UTC, thanhtien522 commented
retest this please

2016-11-10 08:02 UTC, javanna commented
@elasticmachine test this please

2016-11-10 09:53 UTC, javanna approved these changes
thanks @thanhtien522 !

2016-11-10 09:54 UTC, merged