Ensures cleanup of temporary index-* generational blobs during snapshotting
elastic/elasticsearch pull request #21469
Opened 2016-11-10 15:36 UTC by abeyad

This PR ensures pending index-* blobs are deleted when snapshotting.  The
index-* blobs are generational files that maintain the snapshots
in the repository.  To write these atomically, we first write a
`pending-index-*` blob, then move it to `index-*`, which also deletes
`pending-index-*` in case its not a file-system level move (e.g.
S3 repositories) .  For example, to write the 5th generation of the
index blob for the repository, we would first write the bytes to
`pending-index-5` and then move `pending-index-5` to `index-5`.  It is
possible that we fail after writing `pending-index-5`, but before
moving it to `index-5` or deleting `pending-index-5`.  In this case,
we will have a dangling `pending-index-5` blob laying around.  Since
snapshot #5 would have failed, the next snapshot assumes a generation
number of 5, so it tries to write to `index-5`, which first tries to
write to `pending-index-5` before moving the blob to `index-5`.  Since
`pending-index-5` is leftover from the previous failure, the snapshot
fails as it cannot overwrite this blob.

This commit solves the problem by first, adding a UUID to the
`pending-index-*` blobs, and secondly, strengthen the logic around
failure to write the `index-*` generational blob to ensure pending
files are deleted on cleanup.

Closes #21462

2016-11-10 15:58 UTC, ywelsch requested changes
Is it possible to add tests that show that the issue is fixed?

2016-11-10 15:58 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
> +        final String tempBlobName = "pending-" + UUIDs.randomBase64UUID() + "-" + blobName;
I wonder if it's nicer to append the random uuid.

2016-11-10 15:58 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
> +                    exceptionToThrow = e;
`exceptionToThrow` can never be null?
Maybe it's easier to just do the `ex.addSuppressed(...)`?

2016-11-10 15:58 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
> +            } catch (NoSuchFileException e) {
I don't think we should special-case this. Depending on underlying blobcontainer, a different exception might be thrown.

2016-11-10 16:00 UTC, abeyad commented
retest this please

2016-11-10 16:00 UTC, abeyad commented on core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
> +        final String tempBlobName = "pending-" + UUIDs.randomBase64UUID() + "-" + blobName;
Sure, done

2016-11-10 16:04 UTC, abeyad commented on core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
> +            } catch (NoSuchFileException e) {
Its part of the contract of the `BlobContainer` to throw a `NoSuchFileException` if the blob doesn't exist on calling `deleteBlob`, and we changed all implementations to adhere to this contract.  That said, you are right, I went through two iterations of this, and now the only way we get to this block is if an exception was thrown, in which case we don't care about the nature of the exception here.  Same with below

2016-11-10 22:18 UTC, abeyad commented
@ywelsch I pushed some commits that add a test and addresses your feedback

2016-11-10 22:57 UTC, ywelsch approved these changes
left minor comments (easy to fix). LGTM

2016-11-10 22:57 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/common/blobstore/BlobContainer.java
> +     * can only be guaranteed on an implementation-by-implementation basis.  The only current
is can

2016-11-10 22:57 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
> +            try {
maybe readd comment here (temp file creation or move failed - clean up)

2016-11-10 22:57 UTC, ywelsch commented on core/src/test/java/org/elasticsearch/snapshots/mockstore/MockRepository.java
> +                super.writeBlob(targetBlob, readBlob(sourceBlob), 0L);
`super.readBlock` instead of `readBlock` to prevent double `maybeIOExceptionOrBlock`.

2016-11-10 22:57 UTC, ywelsch commented on core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java
> +                Settings.builder().put("location", repoPath).put("random_control_io_exception_rate", 0.2)));
maybe add some randomization to the random_control_io_exception_rate?

2016-11-10 22:57 UTC, ywelsch commented on core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java
> +        } catch (Exception ex) {
can we catch a more specific exception type? IOException with the `Random IOException` string?

2016-11-11 02:03 UTC, abeyad commented on core/src/test/java/org/elasticsearch/snapshots/mockstore/MockRepository.java
> +                super.writeBlob(targetBlob, readBlob(sourceBlob), 0L);
good catch

2016-11-11 02:41 UTC, abeyad commented on core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java
> +        } catch (Exception ex) {
The issue here is that either `SnapshotCreationException` or `RepositoryException` can be thrown, but what we can do here is ensure the stack trace has the `Random IOException` in the nested stack trace.

2016-11-11 02:44 UTC, abeyad commented
@ywelsch I pushed a commit to address your latest feedback.  Thanks for reviewing!

2016-11-11 02:45 UTC, merged

2016-11-11 04:14 UTC, abeyad commented
5.x commit: 6966fa5df46d04d97cc146cdf78f66ed687e6dbe
5.0 commit: a00b58864b77ef5b6140bbfd9bb6fccba665484f

2016-11-11 08:47 UTC, ywelsch commented on core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java
> +        } catch (Exception ex) {
can be specified as `catch (SnapshotCreationException | RepositoryException ex)` in Java ;-)

2016-11-11 08:48 UTC, ywelsch commented on core/src/test/java/org/elasticsearch/snapshots/mockstore/MockRepository.java
> +                super.deleteBlob(sourceBlob);
sorry, forgot to add here that we could randomize between atomic and non-atomic move.

2016-11-11 14:15 UTC, abeyad commented on core/src/test/java/org/elasticsearch/snapshots/mockstore/MockRepository.java
> +                super.deleteBlob(sourceBlob);
I pushed adb7aaded4ee9cfe19dd59781b3d85e570df9a57 to randomize between atomic and non-atomic