[DOCS] Show EC2's auto attribute
elastic/elasticsearch pull request #21474
Opened 2016-11-10 19:09 UTC by pickypg

This documents the `aws_availability_zone` node attribute as part of the `discovery-ec2` plugin. Also fixes outdated usage of "cloud aws".

2016-11-10 21:30 UTC, dadoonet requested changes

2016-11-10 21:30 UTC, dadoonet commented on docs/plugins/discovery-ec2.asciidoc
> +can be used to isolate primary and replica shards across availability zones by using the <<allocation-awareness>> feature.
I think you need to change `<<allocation-awareness>>` with something like `{ref}/allocation-awareness.html` (you have to check the name of the page).

2016-11-21 15:12 UTC, pickypg commented
Fixed it @dadoonet.  Good catch! It was https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-awareness.html (for easier review)

2016-11-21 15:14 UTC, dadoonet approved these changes

2016-11-21 16:04 UTC, merged

2016-11-21 16:07 UTC, pickypg commented
5.x: d39ca4f54f6b2f5c3b06bd611c31dd53f507dfff
5.0: be7b3e72eb0f31c63fc6301fe8ec2e74a121c2b7