Add documentation for Logger with Transport Client
elastic/elasticsearch pull request #21477
Opened 2016-11-10 19:45 UTC by dadoonet

Closes #21331

2016-11-10 19:46 UTC, dadoonet commented
@jasontedor Could you review this doc please?

2016-11-11 11:28 UTC, jasontedor requested changes
Thanks @dadoonet. I left some important comments about the log4j version. I also left a nit about the Log4j name. This nit is for consistency with other places in the docs.

2016-11-11 11:28 UTC, jasontedor commented on docs/java-api/index.asciidoc
> +=== Log4J2 Logger
Nit: Log4J2 -> Log4j 2

2016-11-11 11:28 UTC, jasontedor commented on docs/java-api/index.asciidoc
> +You need to also include Log4J2 dependencies:
Nit: Log4J2 -> Log4j 2

2016-11-11 11:34 UTC, dadoonet commented on docs/java-api/index.asciidoc
> +    <version>2.6.2</version>
Ha right! Thanks a lot. I'll fix that.

2016-11-11 15:36 UTC, jasontedor commented
Also, it occurred to me that these versions in this doc could easily go out of date when we upgrade the Log4j version in version.properties. Could you add a commit to the line item there for Log4j to upgrade the version in these docs when a change is made to the version there?

2016-11-11 20:04 UTC, jasontedor approved these changes
LGTM.

2016-11-11 20:04 UTC, dadoonet commented
@jasontedor I updated based on your comments. Thanks!

> Could you add a commit to the line item there for Log4j to upgrade the version in these docs when a change is made to the version there?

I just added that.

Ideally, as I wrote in https://github.com/elastic/docs/issues/4, I wish we could have a real project with all the java code we added in documentation which is running for real.
From this project, using code snippet "a la maven" would be neat.

2016-11-11 20:06 UTC, merged

2016-11-11 20:24 UTC, dadoonet commented
Also added 
* 5.0: 6348e54650acba3e0188e38d8905cf037cd722c5 and d91ad4e12f28e1b0e723b6223591464ea5be9b77 (with Log4j 2.6.2 instead of 2.7)
* master (6.0): 5336e72fbb85b4d63c8466f64166b58f26a50bb5