Remove `modules/transport_netty_3` in favor of `netty_4`
elastic/elasticsearch pull request #21590
Opened 2016-11-16 10:22 UTC by s1monw

We kept `netty_3` as a fallback in the 5.x series but now that master
is 6.0 we don't need this or in other words all issues coming up with
netty 4 will be blockers for 6.0.

2016-11-16 10:35 UTC, ywelsch approved these changes
bye bye netty3 💃

2016-11-16 15:00 UTC, nik9000 commented
Is it worth running integ-test-zip tests with a two node cluster so we have something that does it? The backwards tests also run a two node cluster but that seems like a different test.

2016-11-16 15:16 UTC, jasontedor requested changes
LGTM, except for one thing.

2016-11-16 15:16 UTC, jasontedor commented on modules/transport-netty4/build.gradle
> -        numNodes = 2
I think that this should stay.

2016-11-16 15:34 UTC, jasontedor commented on modules/transport-netty4/build.gradle
> -        numNodes = 2
What I mean is, I think we should run the regular REST tests with two nodes.

2016-11-16 15:46 UTC, s1monw commented on modules/transport-netty4/build.gradle
> -        numNodes = 2
there are no regular rest tests here? there is only the one that checks that the plugin is loaded?

2016-11-16 15:53 UTC, jasontedor commented on modules/transport-netty4/build.gradle
> -        numNodes = 2
I understand that; we use to run the regular REST tests here with two nodes. I'm saying we should still run the regular REST tests with two nodes somewhere, probably as part of the regular distribution integration test. This seemed the best place to leave that thought. :smile:

2016-11-16 16:43 UTC, s1monw commented on modules/transport-netty4/build.gradle
> -        numNodes = 2
maybe `qa/smoke-test-multinode`?

2016-11-16 16:45 UTC, nik9000 commented on modules/transport-netty4/build.gradle
> -        numNodes = 2
Ah! Fine then. I think we should remove that one in favor of running with two nodes by default but that can be a thing to another PR.

2016-11-16 16:53 UTC, jasontedor approved these changes
LGTM.

2016-11-17 11:44 UTC, merged

2016-11-18 13:41 UTC, tlrx commented
Shouldn't we also adapt the bwc tests so that it does not randomize the transport type when executing bwc tests against a future 6.x minor version (like testing 6.1.0 against 6.0.1)?

2016-11-21 08:58 UTC, s1monw commented
> Shouldn't we also adapt the bwc tests so that it does not randomize the transport type when executing bwc tests against a future 6.x minor version (like testing 6.1.0 against 6.0.1)?

I don't understand what you mean, where is that randomization happening?

2016-11-21 09:04 UTC, tlrx commented
@s1monw I was referring to [this line in ExternalNode](https://github.com/elastic/elasticsearch/blob/f5daa165f12a9ef84006ba16d89c8baf1efe4b94/test/framework/src/main/java/org/elasticsearch/test/ExternalNode.java#L55) - sorry I should have pointed to this line before.

2016-11-21 09:32 UTC, s1monw commented
@tlrx this is dead code I think I will remove it soon we don't use this bwc test stuff these days