Fix compilation in Eclipse
elastic/elasticsearch pull request #21606
Opened 2016-11-16 22:13 UTC by nik9000

I'm not sure what the bug is, but ecj doesn't like this expression
unless the type is set explicitly.

2016-11-16 22:18 UTC, nik9000 commented
It gives two errors which google doesn't turn up too much for:
```
Cannot infer type argument(s) for <T> sendRequest(DiscoveryNode, String, TransportRequest, TransportRequestOptions, TransportResponseHandler<T>)	                                    TransportReplicationAction.java	/:core/java/org/elasticsearch/action/support/replication	line 1019	Java Problem
The constructed object of type TransportReplicationAction.ReplicaResponse is incompatible with the descriptor's return type: ReplicationOperation.ReplicaResponse & TransportResponse	TransportReplicationAction.java	/:core/java/org/elasticsearch/action/support/replication	line 1021	Java Problem
```

2016-11-16 22:19 UTC, nik9000 commented
> The constructed object of type TransportReplicationAction.ReplicaResponse is incompatible with the descriptor's return type: ReplicationOperation.ReplicaResponse & TransportResponse

This, btw, seems to be the real problem. It is totally compatible but eclipse doesn't like it anyway.

2016-11-16 23:11 UTC, nik9000 commented
elasticmachine, retest this please

2016-11-17 02:47 UTC, jasontedor requested changes
I left a comment. These IDE bugs are uncool (IntelliJ has had its fair share of them too).

2016-11-17 02:47 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java
> +                new ActionListenerResponseHandler<ReplicaResponse>(listener, ReplicaResponse::new));
I think that at a minimum this needs a comment explaining why, otherwise someone is going to see it and think "I'll just diamond operator that up".

2016-11-17 14:57 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java
> +                new ActionListenerResponseHandler<ReplicaResponse>(listener, ReplicaResponse::new));
Good call.

2016-11-17 16:19 UTC, nik9000 commented
@jasontedor I pushed an update.

2016-11-17 17:38 UTC, jasontedor approved these changes
LGTM.

2016-11-17 17:54 UTC, merged

2016-11-17 17:55 UTC, nik9000 commented
Thanks @jasontedor!

master: 2a1e08f76ac8200b55110864afbb72b4aff43e0d