Let ClusterStateObserver only hold onto state that's needed for change detection
elastic/elasticsearch pull request #21631
Opened 2016-11-17 17:27 UTC by ywelsch

`ClusterStateObserver`  is a utility class which simplifies interacting with the cluster state in cases where an action takes a decision based on the current cluster state but may want to wait for a new state and retry upon failure. The `ClusterStateObserver` implements its functionality by keeping a reference to the last cluster state that it observed. When a new `ClusterStateObserver` is created, it samples a cluster state from the cluster service which is subsequently used for change detection. If actions take a long time to process, however, the cluster observer can reference very old cluster states. Due to cluster observers being created very frequently and cluster states being potentially large the referenced cluster states can waste a lot of heap space. A specific example where this can make a node go out of memory is given in point 2 of #21568:
> the action listener in TransportMasterNodeAction.AsyncSingleAction has a ClusterStateObserver to coordinate the retry mechanism if the action on the master node fails due to the node not being master anymore. The ClusterStateObserver in AsyncSingleAction keeps a reference to the full cluster state when the action was initiated. If the pending tasks queue grows quite large and has older items in it lots of cluster states can possibly be referenced.

This PR builds on the observation that the cluster state referenced by the `ClusterStateObserver` is not really needed. All that's needed is some form of identity to distinguish between two states. The PR introduces such an identity: ClusterService adds a revision number to the ClusterServiceState that uniquely identifies cluster states that are being applied / have been applied to the node.

2016-11-19 18:50 UTC, bleskes requested changes
I really like the direction of the change, but I want to discuss some considerations. Will reach out on another channel.

2016-11-21 13:11 UTC, ywelsch commented
@bleskes I've reworked the ClusterStateObserver API in 4ab704a so that the ClusterServiceState is not exposed if not required.

2016-11-25 13:12 UTC, bleskes commented
@ywelsch I took a stab at implementing the other approach we discussed - i.e., cleaning the last observed state when it's no longer needed. I also decided to re-write the observer to make its state management clearer. Finally I made some changes to better hide the `ClusterServiceState` from consumers (and I think I fixed a bug or two but doing so, but need to double check). TransportHealthAction has special handling, of course. All of that is [here](https://github.com/elastic/elasticsearch/compare/master...bleskes:observer_simplification). I personally like this better (of course ..) WDYT?

2016-11-25 13:20 UTC, bleskes commented
PS I'll add tests and docs and such once we agree that's where we're going.

2016-11-25 14:02 UTC, ywelsch commented
I have taken a quick look at your solution: It reintroduces the issue of holding onto unnecessary cluster state when executing masterOperation in `TransportMasterNodeAction` (see screenshot below). Eliminating this was the main reason for me to open this PR...

<img width="1230" alt="screen shot 2016-11-25 at 14 50 26" src="https://cloud.githubusercontent.com/assets/3718355/20627172/a6c0e0d0-b31e-11e6-96e7-e463df028c45.png">

2016-11-28 08:17 UTC, bleskes commented
Thx @ywelsch for the clarification. I understood the problem to be with the observer being in "wait mode" while the master is really busy. It seems we indeed also have an issue with the observer being kept around while master operation is pending (and also when we wait on a master node we sent to *another* node).

As I explained, I have two main concerns with the current approach you have taken (while I love the attempt to simplify what it means to see cluster state progres, more on that later):
- It introduces another "history" - i.e., the time line of cluster state applications on the node. This is in contrast to the standard, master controlled, "history" of cluster state changes. I think this will be confusing and rather avoid that complexity.
- It exposes more of the ClusterServiceState to the outside world while I would rather see it being pushed into the discovery mechanism as an implementation detail, so people won't need to deal with the intricacies of cluster state changes. (and thx for making an extra effort here in your last commit).

To help with these points, I opened #21817 . With that in place, the observer won't need to deal with the status change aspect and I think we can continue with your approach but without any state in the observer (with the exception of time, but I have some ideas there). See for example [here](https://github.com/elastic/elasticsearch/pull/21817/files#diff-c41f995cbdbbdafc4169e05e1903a19bR34).  Also, I *think* we can use cluster state versions and master identity (this will go away in the future) as reference to the last state being sampled. 

I will reach out later today to discuss this further.

2016-12-20 13:05 UTC, bleskes approved these changes
LGTM.

2016-12-20 13:05 UTC, bleskes commented on core/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java
> +                    clusterService.state().getVersion());
nit: it looks like we can just capture the version here and forget about the entire cluster state

2016-12-20 14:16 UTC, merged

2016-12-20 14:16 UTC, ywelsch commented
Thanks @bleskes