Allow master to assign primary shard to node that has shard store locked during shard state fetching
elastic/elasticsearch pull request #21656
Opened 2016-11-18 13:13 UTC by ywelsch

PR #19416 added a safety mechanism to shard state fetching to only access the store when the shard lock can be acquired. This can lead to the following situation however where a shard has not fully shut down yet while the shard fetching is going on, resulting in a `ShardLockObtainFailedException`. `PrimaryShardAllocator` that decides where to allocate primary shards sees this exception and treats the shard as unusable. If this is the only shard copy in the cluster, the cluster stays red and a new shard fetching cycle will not be triggered as shard state fetching treats exceptions while opening the store as permanent failures.

This PR makes it so that `PrimaryShardAllocator` treats the locked shard as a possible allocation target (although with the least priority).

2016-11-18 17:59 UTC, dakrone approved these changes
LGTM

2016-11-18 18:09 UTC, abeyad commented
I wanted to make sure I understood correctly - if the shard that has the lock exception is the only valid copy, so the allocator decides to allocate the primary to this (currently) locked shard.  When the node receives the cluster state update that it must allocate the primary on itself, it will try to obtain the shard lock for 5 secs.  If it fails to obtain the lock within 5 secs, the failure is sent to master, which will try to reallocate to the same node again.  It will do this for up to 5 tries (by default) due to the MaxRetryAllocationDecider.  So the node must release the lock on the shard within 5 tries, each try attempting for 5 secs.  Is this understanding correct?

2016-11-18 18:43 UTC, bleskes commented on core/src/main/java/org/elasticsearch/gateway/TransportNodesListGatewayStartedShards.java
> +                        if (exception instanceof IOException && exception.getCause() instanceof ShardLockObtainFailedException) {
question - why not let `Store.tryOpenIndex` throw `ShardLockObtainFailedException` and catch it here directly, logging it and not storing it as a "store" exception? The first part will make things simpler imo. I'm fine with not going with the second part and doing it like you propose but wanted to better understand your reasoning.

2016-11-18 19:00 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/gateway/TransportNodesListGatewayStartedShards.java
> +                        if (exception instanceof IOException && exception.getCause() instanceof ShardLockObtainFailedException) {
I can directly throw `ShardLockObtainFailedException`. I wasn't sure why you wrapped that exception in the first place so I left as is.

To your second point, I left the decision on how to treat the `ShardLockObtainFailedException` to `PrimaryShardAllocator` as it has more context available to make the final decision where to allocate the shard. For example, it prioritizes another valid shard copy that has not thrown the exception. Also it allows the shard store action `/_shard_stores` to properly expose the exception as it reuses the same endpoint as the primary shard allocator.

2016-11-18 19:43 UTC, ywelsch commented
@abeyad correct (I tried it to confirm). We will have 5 iterations where 5 seconds are taken to obtain the shard lock while shard fetching and then 5 seconds to obtain the shard lock while trying to allocate the shard on the node, so 5 * 5 seconds for shard fetching + 4 * 5 seconds for shard allocation attempts  = 45 seconds :-)

Test code

```
        prepareCreate("test").setSettings(Settings.builder()
            .put(IndexMetaData.SETTING_NUMBER_OF_SHARDS, 1)
            .put(IndexMetaData.SETTING_NUMBER_OF_REPLICAS, 0)).get();
        ensureGreen("test");

        ClusterState state = client().admin().cluster().prepareState().get().getState();
        ShardRouting shardRouting = state.routingTable().shardRoutingTable("test", 0).primaryShard();
        String nodeWithPrimary = shardRouting.currentNodeId();
        String node = state.nodes().get(nodeWithPrimary).getName();
        ShardId shardId = shardRouting.shardId();

        NodeEnvironment environment = internalCluster().getInstance(Node.class, node).getNodeEnvironment();
        IndicesService indicesService = internalCluster().getInstance(IndicesService.class, node);
        indicesService.getShardOrNull(shardId).failShard("because I can", new RuntimeException("because I can"));

        ShardLock shardLock = environment.shardLock(shardId, TimeValue.timeValueSeconds(5).millis());

        assertBusy(() -> {
            assertTrue(client().admin().cluster().prepareHealth("test").get().getStatus() == ClusterHealthStatus.RED);
        }, 1, TimeUnit.MINUTES);

        ensureGreen(TimeValue.timeValueMinutes(3), "test");
        shardLock.close();
```

Output:

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -ea -Didea.launcher.port=7532 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA.app/Contents/bin" -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit-rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Users/ywelsch/dev/elasticsearch/core/build-idea/classes/test:/Users/ywelsch/dev/elasticsearch/core/build-idea/classes/main:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-core/6.3.0/d3c87ea89e2f83e401f9cc7f14e4c43945f7f1e1/lucene-core-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-analyzers-common/6.3.0/494aed699af238c3872a6b65e17939e9cb7ddbe0/lucene-analyzers-common-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-backward-codecs/6.3.0/77dede7dff1b833ca2e92d8ab137edb209354d9b/lucene-backward-codecs-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-grouping/6.3.0/2c96d59e318ea66838aeb9c5cfb8b4d27b40953c/lucene-grouping-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-highlighter/6.3.0/4f154d8badfe47fe45503c18fb30f2177f758794/lucene-highlighter-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-join/6.3.0/79b898117dcfde2981ec6806e420ff218842eca8/lucene-join-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-memory/6.3.0/89edeb404e507d640cb13903acff6953199704a2/lucene-memory-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-misc/6.3.0/2d0e1f5a9df15ac911ad495bad5ea253ab50a9f/lucene-misc-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-queries/6.3.0/eb7938233c8103223069c7b5b5f785b4d20ddafa/lucene-queries-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-queryparser/6.3.0/e979fb02155cbe81a8d335d6dc41d2ef06be68b6/lucene-queryparser-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-sandbox/6.3.0/257387c45c6fa2b77fd6931751f93fdcd798ced4/lucene-sandbox-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-spatial/6.3.0/3cf5fe5402b5e34b240b73501c9e97a82428259e/lucene-spatial-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-spatial-extras/6.3.0/1b77ef3740dc885c62d5966fbe9aea1199d344fb/lucene-spatial-extras-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-spatial3d/6.3.0/aa94b4a8636b3633008640cc5155ad354aebcea5/lucene-spatial3d-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-suggest/6.3.0/ed5d8ee5cd7edcad5d4ffca2b4540ccc844e9bb0/lucene-suggest-6.3.0.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.elasticsearch/securesm/1.1/1e423447d020041534be94c0f31a49fbdc1f2950/securesm-1.1.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/net.sf.jopt-simple/jopt-simple/5.0.2/98cafc6081d5632b61be2c9e60650b64ddbc637c/jopt-simple-5.0.2.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/com.carrotsearch/hppc/0.7.1/8b5057f74ea378c0150a1860874a3ebdcb713767/hppc-0.7.1.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/joda-time/joda-time/2.9.5/5f01da7306363fad2028b916f3eab926262de928/joda-time-2.9.5.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.15/3b132bea69e8ee099f416044970997bde80f4ea6/snakeyaml-1.15.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.8.1/fd13b1c033741d48291315c6370f7d475a42dccf/jackson-core-2.8.1.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-smile/2.8.1/5b73867bc12224946fc67fc8d49d9f5e698d7f/jackson-dataformat-smile-2.8.1.jar:/Users/ywelsch/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/2.8.1/eb63166c723b0b4b9fb5298fca232a2f6612ec34/jackson-dataform [...]

2016-11-18 19:46 UTC, abeyad commented
@ywelsch thanks for confirming

2016-11-18 20:26 UTC, ywelsch commented
Playing around with the above test case I noticed that `ShardLockObtainFailedException` was not serializable, which is fixed by d8a6b91.

2016-11-18 20:27 UTC, dakrone commented
> I noticed that ShardLockObtainFailedException was not serializable, which is fixed by d8a6b91.

Wouldn't that make this non-backport-able, since 5.0 won't have the serialization logic for this exception?

2016-11-18 20:59 UTC, ywelsch commented
> Wouldn't that make this non-backport-able, since 5.0 won't have the serialization logic for this exception?

correct 😞 We need to rethink this. Any suggestions?

2016-11-19 17:23 UTC, bleskes commented
> Any suggestions?

I think we have 3 options
1) Don't return the shard lock exception as a store exception, with the down sides you described.
2) Build a BWC layer into NodeGatewayStartedShards#writeTo translating that exception into an IOException (and the same for the read side)
3) Build a BWC layer intot he exception handling logic , which we will need at some point anyway.

Given the time frame of this and the aim to have it in 5.1, I tend towards option 2.

2016-11-21 12:18 UTC, ywelsch commented
@s1monw has added a BWC layer for exceptions in #21694. I've rebased this PR so that it includes his changes -> It's ready for review again.

2016-11-22 09:01 UTC, ywelsch commented
Can I get another review on this?

2016-11-22 13:25 UTC, bleskes requested changes
Code LGTM (left some nits). I do think we need to beef up the test a bit.

2016-11-22 13:25 UTC, bleskes commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> +                    if (nodeShardState.primary() && nodeShardState.storeException() == null) {
can we assert that the store exception is what we expect it to be?

2016-11-22 13:25 UTC, bleskes commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> +                    if (nodeShardState.primary() && nodeShardState.storeException() == null) {
same request for assertion.

2016-11-22 13:25 UTC, bleskes commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> +                        version = Long.MAX_VALUE; // shard was already selected in a 5.x cluster as primary, prefer this shard copy again.
did you run into this being a problem? how can we open an index that was created before 5.0.0 and never had insync replicas but does have allocationId? the only thing I can think of is a node network issue during shard initialization. I'm wondering if we need to optimize for this and no keep this code simple (i.e., demote shards with a lock exception)

2016-11-22 13:25 UTC, bleskes commented on core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java
> +    public void testShardLockObtainFailedException() {
can we add tests for cases with more shards? for example the case where we "prefer" other shard copies with this exception?

2016-11-22 16:08 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> +                        version = Long.MAX_VALUE; // shard was already selected in a 5.x cluster as primary, prefer this shard copy again.
We special-case this a few lines up as well (but it's not easy to do code reuse across those lines). For symmetry reasons I have kept it as is. The code is documented as well.

2016-11-22 16:09 UTC, ywelsch commented
@bleskes I've pushed 3e64d74 addressing comments.

2016-11-22 17:15 UTC, bleskes commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> -        List<NodeGatewayStartedShards> nodeShardStates = new ArrayList<>();
yay!

2016-11-22 17:15 UTC, bleskes commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> +                (NodeGatewayStartedShards state) -> inSyncAllocationIds.contains(state.allocationId())).reversed();
fancy pants.

2016-11-22 17:15 UTC, bleskes commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> +                        version = Long.MAX_VALUE; // shard was already selected in a 5.x cluster as primary, prefer this shard copy again.
fair enough

2016-11-22 17:16 UTC, bleskes approved these changes
LGTM. Thanks @ywelsch

2016-11-22 18:35 UTC, merged

2016-11-22 18:47 UTC, ywelsch commented
Thanks @bleskes @abeyad @dakrone