expand `/_cat/nodes` to return information about hard drive
elastic/elasticsearch pull request #21775
Opened 2016-11-24 09:41 UTC by agebhar1

Expand `/_cat/nodes` with already present information about
available disk space `diskAvail` (alias: `d`, `disk`) by:

* `diskTotal` (alias `dt`): total disk space
* `diskUsed` (alias `du`): used disk space (`diskTotal - diskAvail`)
* `diskUsedPercent` (alias `dup`): used disk space percentage

Note: The available disk space is the number of bytes available
to the node's Java virtual machine. The size might by smaller
than the real one. That means the used disk space (percentage)
is larger.

The value of `diskAvail` is backtracked to:
```
org.elasticsearch.monitor.fs.FsProbe:

129:    public static FsInfo.Path getFSInfo(NodePath nodePath) throws IOException {
130:        FsInfo.Path fsPath = new FsInfo.Path();
131:        fsPath.path = nodePath.path.toAbsolutePath().toString();
132:
133:        // NOTE: we use already cached (on node startup) FileStore and spins
134:        // since recomputing these once per second (default) could be costly,
135:        // and they should not change:
136:        fsPath.total = nodePath.fileStore.getTotalSpace();
137:        fsPath.free = nodePath.fileStore.getUnallocatedSpace();
138:        fsPath.available = nodePath.fileStore.getUsableSpace();
139:        fsPath.type = nodePath.fileStore.type();
140:        fsPath.mount = nodePath.fileStore.toString();
141:        fsPath.spins = nodePath.spins;
142:        return fsPath;
143:    }
```
where `nodePath.fileStore` is of type `java.nio.file.FileStore`

Closes #21679.

2016-11-24 10:20 UTC, agebhar1 commented
:thinking: ... the CLA was signed almost an hour ago

2017-04-13 10:10 UTC, mtunstill commented
I'd bump this to be pulled in. Would be handy to peak at the diskUsedPercent per node via the cat API.

2017-04-13 10:10 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-05-15 09:49 UTC, javanna commented
hi @agebhar1 I am sorry it took us ages to get back to you. Your change looks ok but I don't see any tests along with it. Could you add some tests for it? The way we test _cat api is though yaml tests, see https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/test/cat.nodes/10_basic.yaml .

2017-05-15 17:24 UTC, agebhar1 commented
hi @javanna, thanks for peer review this PR - for sure, I will add some tests asap

2017-05-21 08:50 UTC, agebhar1 commented
hi @javanna added test case for new available disk values

2017-05-26 11:45 UTC, javanna commented
jenkins test this please

2017-06-13 12:25 UTC, javanna commented
retest this please

2017-06-13 13:46 UTC, javanna commented
hi @agebhar1 did you run `gradle check` on your branch? Seems like there is a checkstyle violation in the modified `RestNodesAction`. Could you please address that?

2017-06-14 17:08 UTC, agebhar1 commented
sure @javanna - will have a look

2017-06-15 09:34 UTC, javanna commented
retest this please

2017-06-16 13:29 UTC, javanna requested changes
thanks @agebhar1 I reviewed this and left a couple of comments.

2017-06-16 13:29 UTC, javanna commented on rest-api-spec/src/main/resources/rest-api-spec/test/cat.nodes/10_basic.yml
> +          h: disk,diskAvail,diskTotal,diskUsed,diskUsedPercent
why test both diskAvail and its alias? Maybe we could do `h: diskAvail,diskTotal,diskUsed,diskUsedPercent` here and have another test for the aliases: `h: disk,dt,du,dup` ?

2017-06-16 13:29 UTC, javanna commented on core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java
> +                fsInfo.getTotal().getTotal().getBytes(), diskUsed); // prevent division by Zero
can you explain this? when total is 0 (when would that happen?) diskUsed may be negative? what would we return here?

2017-06-16 18:21 UTC, agebhar1 commented on rest-api-spec/src/main/resources/rest-api-spec/test/cat.nodes/10_basic.yml
> +          h: disk,diskAvail,diskTotal,diskUsed,diskUsedPercent
That is a pretty good idea @javanna, I removed the alias for `diskAvail` and added another test for the aliases. Should I fix up the commit or add another commit on top of this one?

2017-06-16 18:46 UTC, agebhar1 commented on core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java
> +                fsInfo.getTotal().getTotal().getBytes(), diskUsed); // prevent division by Zero
No, unfortunately I can't remember why should `fsInfo.getTotal().getTotal().getBytes()` be zero. Is it possible that `diskUsed` get negative, if so I suggest to calculate `diskUsedRatio` such that ist value is greater than 1 (> 100%).

2017-06-19 14:58 UTC, javanna commented on core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java
> +                fsInfo.getTotal().getTotal().getBytes(), diskUsed); // prevent division by Zero
maybe we should rather do what we do in `DiskUsage`:

```
if (totalBytes == 0) {
    return 100.0;
}
return 100.0 * ((double)freeBytes / totalBytes);
```

What do you think?

2017-06-19 14:59 UTC, javanna commented on core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java
> +                fsInfo.getTotal().getTotal().getBytes(), diskUsed); // prevent division by Zero
the `diskUsed` line can stay unchanged.

2017-06-20 18:22 UTC, agebhar1 commented on core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java
> +                fsInfo.getTotal().getTotal().getBytes(), diskUsed); // prevent division by Zero
I have no concerns @javanna - will update the PR immediately

2017-06-20 19:57 UTC, agebhar1 commented
@javanna updated calculation of `diskUsedRatio` as suggested, for better readability added a local variable for total disk size

... at the end, I'd like to squash all three commits

2017-06-27 09:42 UTC, javanna commented
retest this please

2017-06-27 09:45 UTC, javanna approved these changes
LGTM thanks a lot @agebhar1 I will merge this after the last tests run. Don't worry about squashing, I will take care of it.

2017-06-27 10:25 UTC, javanna commented
retest this please

2017-06-27 11:13 UTC, agebhar1 commented
@javanna  you're welcome! Also a lot of thanks from my side for your effort to finalize this PR.

2017-06-27 11:30 UTC, javanna commented on rest-api-spec/src/main/resources/rest-api-spec/test/cat.nodes/10_basic.yml
> +  - do:
one last thing that I forgot. We'd need to get this new section into its own test e.g.

```
---
"Additional disk information":
```

This way we can add a skip section to it:

```
 - skip:
    version: " - 5.5.99"
    reason:  additional disk info added in 5.6.0
```

2017-06-27 11:52 UTC, agebhar1 commented on rest-api-spec/src/main/resources/rest-api-spec/test/cat.nodes/10_basic.yml
> +  - do:
Will move the tests to the new section "Additional disk information". Should I add the skip attribute with the given values (version, reason) too?

2017-06-27 12:40 UTC, javanna commented on rest-api-spec/src/main/resources/rest-api-spec/test/cat.nodes/10_basic.yml
> +  - do:
yes please

2017-06-27 12:53 UTC, agebhar1 commented on rest-api-spec/src/main/resources/rest-api-spec/test/cat.nodes/10_basic.yml
> +  - do:
... push the squashed commits with these changes in the evening

2017-06-27 12:57 UTC, javanna commented on rest-api-spec/src/main/resources/rest-api-spec/test/cat.nodes/10_basic.yml
> +  - do:
please just add a new commit, I will squash when merging

2017-06-27 13:44 UTC, agebhar1 commented on rest-api-spec/src/main/resources/rest-api-spec/test/cat.nodes/10_basic.yml
> +  - do:
okay

2017-06-27 18:43 UTC, agebhar1 commented on rest-api-spec/src/main/resources/rest-api-spec/test/cat.nodes/10_basic.yml
> +  - do:
@javanna - I've added the commit with the additional section

2017-06-27 19:20 UTC, javanna commented
retest this please

2017-06-28 16:20 UTC, merged

2017-06-28 16:21 UTC, javanna commented
Merged, thanks a lot @agebhar1 !

2017-06-28 16:25 UTC, agebhar1 commented
awsome @javanna - thank you too!