Remove connectToNodeLight and replace it with a connection profile
elastic/elasticsearch pull request #21799
Opened 2016-11-25 15:18 UTC by s1monw

The Transport#connectToNodeLight concepts is confusing and not very flexible.
neither really testable on a unittest level. This commit cleans up the code used
to connect to nodes and simplifies transport implementations to share more code.
This also allows to connect to nodes with custom profiles if needed, for instance
future improvements can be added to connect to/from nodes that are non-data nodes without
dedicated bulks and recovery connections.

2016-11-25 16:15 UTC, s1monw commented
test this please

2016-11-25 16:46 UTC, s1monw commented on modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
> +                    future.awaitUninterruptibly((long) (connectTimeout.millis() * 1.5));
good idea, very good idea. I will create a followup for this WDYT @tlrx

2016-11-25 16:48 UTC, tlrx commented on modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
> +                    future.awaitUninterruptibly((long) (connectTimeout.millis() * 1.5));
+1

2016-11-27 07:52 UTC, s1monw commented
test this please

2016-11-27 14:58 UTC, s1monw commented on modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
> +                    future.awaitUninterruptibly((long) (connectTimeout.millis() * 1.5));
@tlrx I looked into this and one problem is that the connect timeout is per Bootstrap on the netty layer. This essentially means we need a dedicated Bootstrap for each connection timeout value. I don't think we should do that, maybe there is a better solution to this? I wonder if we should look into adding this option to netty?

2016-11-28 08:06 UTC, tlrx commented on modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
> +                    future.awaitUninterruptibly((long) (connectTimeout.millis() * 1.5));
great!

2016-11-28 13:31 UTC, s1monw commented on modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
> +                    future.awaitUninterruptibly((long) (connectTimeout.millis() * 1.5));
@tlrx is it [that](https://github.com/s1monw/elasticsearch/commit/485bba138ed18581c40cd01853939df54a59ee97) what you had in mind

2016-11-28 13:59 UTC, tlrx commented on modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
> +                    future.awaitUninterruptibly((long) (connectTimeout.millis() * 1.5));
@s1monw yes

2016-11-28 14:11 UTC, s1monw commented
as a followup I'd like to do  stuff like this:
```DIFF
diff --git a/core/src/main/java/org/elasticsearch/transport/TcpTransport.java b/core/src/main/java/org/elasticsearch/transport/TcpTransport.java
index 66dd217..e0c1d3a 100644
--- a/core/src/main/java/org/elasticsearch/transport/TcpTransport.java
+++ b/core/src/main/java/org/elasticsearch/transport/TcpTransport.java
@@ -81,6 +81,7 @@ import java.util.ArrayList;
 import java.util.Arrays;
 import java.util.Collections;
 import java.util.EnumMap;
+import java.util.EnumSet;
 import java.util.HashMap;
 import java.util.HashSet;
 import java.util.Iterator;
@@ -205,9 +206,20 @@ public abstract class TcpTransport<Channel> extends AbstractLifecycleComponent i
         ConnectionProfile.Builder builder = new ConnectionProfile.Builder();
         builder.addConnections(connectionsPerNodeBulk, TransportRequestOptions.Type.BULK);
         builder.addConnections(connectionsPerNodePing, TransportRequestOptions.Type.PING);
-        builder.addConnections(connectionsPerNodeRecovery, TransportRequestOptions.Type.RECOVERY);
-        builder.addConnections(connectionsPerNodeReg, TransportRequestOptions.Type.REG);
-        builder.addConnections(connectionsPerNodeState, TransportRequestOptions.Type.STATE);
+        Set<TransportRequestOptions.Type> regSet = EnumSet.of(TransportRequestOptions.Type.REG);
+        if (DiscoveryNode.isMasterNode(settings)) {
+            builder.addConnections(connectionsPerNodeState, TransportRequestOptions.Type.STATE);
+        } else {
+            // if we are not master eligible we don't need a dedicated channel to publish the state
+            regSet.add(TransportRequestOptions.Type.STATE);
+        }
+        if (DiscoveryNode.isDataNode(settings)) {
+            builder.addConnections(connectionsPerNodeRecovery, TransportRequestOptions.Type.RECOVERY);
+        } else {
+            // if we are not a data-node we don't need any dedicated channels for recovery
+            regSet.add(TransportRequestOptions.Type.RECOVERY);
+        }
+        builder.addConnections(connectionsPerNodeReg, regSet.toArray(new TransportRequestOptions.Type[regSet.size()]));
         defaultConnectionProfile = builder.build();
     }

```

2016-11-28 16:08 UTC, jasontedor requested changes
I like it @s1monw. I left a few comments.

2016-11-28 16:08 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/transport/ConnectionProfile.java
> +                    throw new IllegalArgumentException("type [" + type + "] is already registered");
I think that this should be an `IllegalStateException`.

2016-11-28 16:08 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/transport/ConnectionProfile.java
> +        public ConnectionProfile build() {
Can you add a Javadoc for this documenting that all types have to have been added?

2016-11-28 16:42 UTC, s1monw commented on core/src/main/java/org/elasticsearch/transport/ConnectionProfile.java
> +                    throw new IllegalArgumentException("type [" + type + "] is already registered");
my reasoning is that the argument would introduce this state but I won't let it hence the ISE

2016-11-28 16:46 UTC, s1monw commented
@jasontedor I pushed a new commit and replied to one comment

2016-11-28 17:25 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/transport/ConnectionProfile.java
> +                    throw new IllegalArgumentException("type [" + type + "] is already registered");
Okay.

2016-11-28 17:26 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/transport/ConnectionProfile.java
> +         * @throws IllegalArgumentException if any of the {@link org.elasticsearch.transport.TransportRequestOptions.Type} enum is missing
This Javadoc is incorrect; the method throws an `IllegalStateException` (which in this case I think is correct). :smile:

2016-11-28 17:27 UTC, jasontedor reviewed
I left one more comment @s1monw.

2016-11-28 17:27 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/transport/ConnectionProfile.java
> +         * @throws IllegalArgumentException if any of the {@link org.elasticsearch.transport.TransportRequestOptions.Type} enum is missing
This Javadoc is incorrect; the method throws an `IllegalStateException` (which in this case I think is correct). :smile:

2016-11-28 20:58 UTC, s1monw commented
@jasontedor fixed the javadocs issue

2016-11-28 21:01 UTC, jasontedor approved these changes
LGTM.

2016-11-29 08:35 UTC, merged