avoid repeat connections in pings every round
elastic/elasticsearch pull request #21812
Opened 2016-11-27 07:12 UTC by chengpohi

This PR is trying to fix: https://github.com/elastic/elasticsearch/issues/21739 by Option 1.

@bleskes Could you review this?

2016-11-27 09:05 UTC, bleskes requested changes
Thx @chengpohi ! I left some comments. It would also be great to have a test that the unicast host provider is only called once per pinging round. Also it would be good to have a test that pinging picks up on nodes that it discovered - i.e., if you A & C ping B , A starts pinging C as well (it got it through B). See UnicastZenPingTests for examples and where this should go.

2016-11-27 09:05 UTC, bleskes commented on core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java
> +        final List<DiscoveryNode> sortedNodesToPing = buildNodesToPing();
can we unify the resolvedDiscoveryNodes logic with the buildNodesToPing ? They are similar in the sense that they don't change during a ping cycle.

2016-11-27 17:06 UTC, chengpohi commented on core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java
> +        final List<DiscoveryNode> sortedNodesToPing = buildNodesToPing();
Hi @bleskes, I have updated this base on your suggestion, Could you review again? Thanks

2016-11-27 20:56 UTC, bleskes requested changes
Thx @chengpohi . I left some more comments

2016-11-27 20:56 UTC, bleskes commented on core/src/test/java/org/elasticsearch/discovery/zen/UnicastZenPingTests.java
> +    public void testShouldPingDiscoveredNodes() throws IOException, InterruptedException {
can we call this `testDiscoveryOfNoneConfiguredNodes` and add a comment: `test that nodes discover each other if they ping a common host` ?

This doesn't test what I intended - i.e., test that a node pings nodes that have pinged it while it was pinging. That is however non trivial to test and I don't want to delay your change for setting this test up.

2016-11-28 10:18 UTC, chengpohi commented on core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java
> +            resolvedDiscoveryNodes = resolveDiscoveryNodes(
Hi @bleskes , if we add `resolveDiscoveryNodes`, we can't guarantee *configured hosts first* ping, Does it make sense?

2016-12-21 14:25 UTC, jasontedor commented
Thanks for picking this up @chengpohi but this has now been superseded by #22277.

2016-12-21 14:25 UTC, closed without merging