refactory ShardsLimitAllocationDecider.java
elastic/elasticsearch pull request #21845
Opened 2016-11-29 03:33 UTC by makeyang

re-pull request and try to refacotry code according to this: #21641 (comment)

2016-11-30 12:52 UTC, jpountz reviewed
I left minor comments but it looks good. @jasontedor Would you mind having a look too since you commented on the original issue?

2016-11-30 12:52 UTC, jpountz commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ShardsLimitAllocationDecider.java
> +                nodeShardCount, clusterShardLimit);
can you undo all indentation changes, it adds noise to the diff

2016-11-30 12:52 UTC, jpountz commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ShardsLimitAllocationDecider.java
> +        return doDecide(shardRouting, node, allocation, (count, limit) -> { return count >= limit;});
I think `(count, limit) -> count >= limit` would work too, and be slightly simpler?

2016-12-01 03:00 UTC, jasontedor requested changes
I agree with @jpountz review, and left another comment.

2016-12-01 03:00 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ShardsLimitAllocationDecider.java
> +        return doDecide(shardRouting, node, allocation, (count, limit) -> {return count > limit;});
This predicate can be simplified to `(count, limit) -> count > limit`.

2016-12-01 03:25 UTC, jasontedor commented
Thanks @makeyang; I see that you pushed a commit incorporating our recommendations, except @jpountz was looking for you to revert all of the changes that are whitespace only changes.

2016-12-01 03:30 UTC, makeyang commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ShardsLimitAllocationDecider.java
> +        return doDecide(shardRouting, node, allocation, (count, limit) -> { return count >= limit;});
already changed.

2016-12-01 03:31 UTC, makeyang commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ShardsLimitAllocationDecider.java
> +                nodeShardCount, clusterShardLimit);
already changed.

2016-12-01 03:32 UTC, makeyang commented
@jasontedor  @jpountz  have already changed according to u guys comments. please help to review, thanks

2016-12-01 04:11 UTC, jasontedor commented
ok to test

2016-12-01 05:52 UTC, makeyang commented
@jasontedor  anything I can do for testing?

2016-12-01 13:09 UTC, jpountz approved these changes
I'll let @jasontedor have a look too but it looks good to me now!

2016-12-01 13:11 UTC, jpountz commented
@makeyang regarding testing, CI got all tests passing for this PR so I think we're good! https://elasticsearch-ci.elastic.co/job/elastic-elasticsearch-pull-request/1535/

2016-12-01 14:24 UTC, jasontedor commented
@makeyang "test this please" was a command to run this PR through our CI. :smile:

The change looks good, I'll approve this PR and merge it later.

2016-12-01 14:25 UTC, jasontedor approved these changes
LGTM. Thanks @makeyang.

2016-12-02 02:27 UTC, merged

2016-12-02 02:28 UTC, jasontedor commented
Thank you @makeyang!