Add support for "include_segment_file_sizes" in indices stats REST handler
elastic/elasticsearch pull request #21879
Opened 2016-11-30 04:18 UTC by spiegela

Fix for #21878

Adds `include_segment_file_sizes` to acceptable parameters in the `RestIndicesStatsAction` REST handler.

Thanks!

2016-11-30 04:22 UTC, jasontedor requested changes

2016-11-30 04:22 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestIndicesStatsAction.java
> +    private static final Set<String> RESPONSE_PARAMS = new HashSet<String>(Arrays.asList("level", "include_segment_file_sizes"));
This isn't the right fix, it's not a response parameter (it controls the request that the node client sends). Rather, this parameter needs to be consumed (and parsed as a boolean).

2016-11-30 04:23 UTC, jasontedor commented
I left a comment requesting a different approach. The same fix needs to be applied to node stats too.

2016-11-30 04:47 UTC, jasontedor commented
@spiegela Also, I think I'd prefer the tests to be REST tests as opposed to unit tests; please let me know if you can make these changes or if I can help guide you through this.

2016-11-30 05:10 UTC, spiegela commented on core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestIndicesStatsAction.java
> +    private static final Set<String> RESPONSE_PARAMS = new HashSet<String>(Arrays.asList("level", "include_segment_file_sizes"));
Gotcha. I see some examples of that now using the `request.paramAsBoolean`.  I'll correct it this way, and correct it in the node stats, too.

2016-11-30 05:34 UTC, spiegela commented
Thanks, @jasontedor.  I can make the fix by consuming the parameter pretty quickly. Can you point me to a REST test example?

2016-11-30 05:46 UTC, jasontedor commented
Look at `rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats` and similarly for nodes stats. And you can poke around in the sibling folders for more examples. Feel free to ping upon any questions.

2016-12-01 05:21 UTC, spiegela commented
@jasontedor I've fixed the issue by consuming the param as a bool, and switched the testing to the REST tests. I've also corrected the same issue in the node stats.

2016-12-01 22:06 UTC, jasontedor requested changes
Thanks @spiegela. Getting close.

2016-12-01 22:06 UTC, jasontedor commented on rest-api-spec/src/main/resources/rest-api-spec/api/indices.stats.json
> +          "description": "Whether report the aggregated disk usage of each one of the Lucene index files.",
Can you fix the grammar here, remove the period, and add a remark that it only applies if segments stats are requested?

2016-12-01 22:33 UTC, spiegela commented
@jasontedor Should have waited till the morning to push and caught both of those. I also cleaned up some unused imports.

2016-12-02 11:44 UTC, jasontedor commented
@spiegela I think you force pushed? The review process is easier if we go commit by commit and we can squash at the end on our side when we integrate. No worries this time, just a heads up for the future. :smile:

2016-12-02 11:45 UTC, jasontedor commented
ok to test

2016-12-15 04:29 UTC, jasontedor approved these changes
LGTM.

2016-12-15 04:29 UTC, jasontedor commented
I will merge this soon.

2016-12-15 12:29 UTC, merged

2016-12-15 12:30 UTC, jasontedor commented
Thanks @spiegela!

2016-12-16 14:34 UTC, spiegela commented
Sure thing!