Warn log deprecation warnings received from server
elastic/elasticsearch pull request #21895
Opened 2016-11-30 20:45 UTC by javanna

The warnings received via response headers get printed out in a single line:

```
WARNING: Received warnings: 1) indices query is deprecated. Instead search on the '_index' field 2) [template] query is deprecated, use search template api instead
```

2016-12-01 10:46 UTC, cbuescher commented
I was wondering about the reason why all warnings are printed on a single line. I don't know how people are parsing their logs, but I though having multi-lines would be easier to parse, e.g.

```
WARNING: Received warning: 1) indices query is deprecated. Instead search on the '_index' field
WARNING: Received warning: 2) [template] query is deprecated, use search template api instead
```

Otherwise people would need to split the line at the `x)` indicators somehow to get to the individual warnings? Also, in logs where multiple responses might be interleaved, maybe its possible to log something to tie these together? I don't know how difficult it is to build some id for a response that could be logged to keep those warnings together. 

Just my 2 cents, if one line is prefered this looks good to me.

2016-12-01 13:42 UTC, javanna commented
good question @cbuescher I tried to keep it all in a single log line because otherwise it becomes hard to understand which request returned which warnings. I could have a line per warning within the same log line, but I'm afraid that is not parser friendly.

> Otherwise people would need to split the line at the x) indicators somehow to get to the individual warnings?

I don't expect to have to log many warnings for each requests, and I think it makes sense to log them per request, I am not sure people will actually split the line to extract each single warning.

I have added now some more info about the request so one can try and trace the warnings back to the request that originated them: 

```
request [PUT http://localhost:9200/index/type/_api] returned warnings: 1) this is warning number 1 2) this is warning number 2
```

2016-12-01 21:42 UTC, javanna commented
retest this please

2016-12-01 21:42 UTC, javanna commented
@tlrx you mind having a look too please?

2016-12-02 08:38 UTC, tlrx requested changes
I left some comments. I'm fine with keeping the warnings on a single line but I'd prefer to have the total number of warnings easily parsable and then each warning enclosed in bracket or something:

```
request [PUT http://localhost:9200/index/type/_api] returned [2] warnings: [this is warning number 1][this is warning number 2]
```

2016-12-02 08:38 UTC, tlrx commented on client/rest/src/main/java/org/elasticsearch/client/RequestLogger.java
> +    static String buildWarningLine(HttpUriRequest request, HttpHost host, Header[] warnings) {
buildWarningMessage instead?

2016-12-02 08:38 UTC, tlrx commented on client/rest/src/main/java/org/elasticsearch/client/RequestLogger.java
> +        String line = "request [" + request.getMethod() + " " + host + getUri(request.getRequestLine()) + "] returned warnings:";
Can you use StringJoiner or StringBuilder?

2016-12-02 08:38 UTC, tlrx commented on client/rest/src/main/java/org/elasticsearch/client/RequestLogger.java
> +            line += " " + (i+1) + ") " + warnings[i].getValue();
Do we really need to know the number?

2016-12-02 08:38 UTC, tlrx commented on client/rest/src/test/java/org/elasticsearch/client/RequestLoggerTests.java
> +        System.out.println(expected);
Leftover

2016-12-02 09:30 UTC, javanna commented on client/rest/src/main/java/org/elasticsearch/client/RequestLogger.java
> +            line += " " + (i+1) + ") " + warnings[i].getValue();
no it was just for convenience.

2016-12-02 09:30 UTC, javanna commented on client/rest/src/main/java/org/elasticsearch/client/RequestLogger.java
> +    static String buildWarningLine(HttpUriRequest request, HttpHost host, Header[] warnings) {
sounds good

2016-12-02 09:31 UTC, javanna commented
@tlrx ++ on printing the total number of warnings. on the brackets, not sure they will help cause warnings often contain brackets too :)

2016-12-10 17:39 UTC, javanna commented
@tlrx I addressed your comments, thanks

2016-12-12 09:48 UTC, tlrx approved these changes

2016-12-12 11:11 UTC, merged