Separate cluster update tasks that are published from those that are not
elastic/elasticsearch pull request #21912
Opened 2016-12-01 13:59 UTC by ywelsch

This PR factors out the cluster state update tasks that are published to the nodes from those that are not, serving as a basis for future refactorings to separate the publishing mechanism out of cluster service.

2016-12-19 16:54 UTC, ywelsch commented
@bleskes I've simplified this PR so that it now only focuses on the generalization of the BatchResult class to a ClusterTaskResult class which has the additional option to signal "noMaster". Can you have a look?

2016-12-22 10:37 UTC, bleskes requested changes
This looks great. I left a bunch of minor comments and some questions

2016-12-22 10:37 UTC, bleskes commented on core/src/main/java/org/elasticsearch/cluster/service/ClusterService.java
> +        if (newClusterState.nodes().isLocalNodeElectedMaster()) {
++

2016-12-22 10:37 UTC, bleskes commented on core/src/main/java/org/elasticsearch/cluster/ClusterStateTaskExecutor.java
> +    class ClusterTaskResult<T> {
nit: call this ClusterTask**s**Result ?

2016-12-22 10:37 UTC, bleskes commented on core/src/main/java/org/elasticsearch/cluster/ClusterStateUpdateTask.java
> +    public final boolean runOnlyOnMaster() {
can you add a comment that this is here to make it final as ClusterStateUpdateTask should only run on the master?

2016-12-22 10:37 UTC, bleskes commented on core/src/main/java/org/elasticsearch/cluster/LocalClusterUpdateTask.java
> +        ClusterTaskResult<LocalClusterUpdateTask> result = execute(currentState);
assert that tasks is size of 1 and contains this object?

2016-12-22 10:37 UTC, bleskes commented on core/src/main/java/org/elasticsearch/cluster/LocalClusterUpdateTask.java
> +    public static ClusterTaskResult<LocalClusterUpdateTask> noMaster() {
java docs please?

2016-12-22 10:37 UTC, bleskes commented on core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java
> +    final RefreshTaskExecutor refreshExecutor = new RefreshTaskExecutor();
++

2016-12-22 10:37 UTC, bleskes commented on core/src/main/java/org/elasticsearch/discovery/zen/NodeJoinController.java
> -                .removeGlobalBlock(discoverySettings.getNoMasterBlock()).build();
discovery settings is now unused and can be removed.

2016-12-22 10:37 UTC, bleskes commented on core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java
> -        clusterService.submitStateUpdateTask("zen-disco-mini-master-nodes-changed", new ClusterStateUpdateTask(Priority.IMMEDIATE) {
LOL

2016-12-22 10:37 UTC, bleskes commented on core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java
> +            clusterService.submitStateUpdateTask("ping from another master", new LocalClusterUpdateTask(Priority.IMMEDIATE) {
hmm.. this is a funky one. It's supposed to run only on masters. On the other hand, I see the complexity involved if we want to call handleAnotherMaster from the normal cluster state processing mechanism as well (where we do need a LocalClusterUpdateTask). We can maybe make rejoin generic, and make `noMaster` and `unchanged` be part of the generic `ClusterTaskResult` but I'm not sure it's worth it. Maybe we should just check we're master within the execute method here and make it a noop if we're not ? wdyt?

2016-12-22 10:37 UTC, bleskes commented on core/src/main/java/org/elasticsearch/tribe/TribeService.java
> -        public boolean runOnlyOnMaster() {
hmm- - is this OK? what am I missing?

2016-12-22 10:37 UTC, bleskes commented on core/src/test/java/org/elasticsearch/tribe/TribeIT.java
> +        clusterService.submitStateUpdateTask("update customMetaData", new LocalClusterUpdateTask(Priority.IMMEDIATE) {
why did you change this? it seems like it supposed to publish a new cluster state?

2016-12-22 15:09 UTC, ywelsch commented on core/src/test/java/org/elasticsearch/tribe/TribeIT.java
> +        clusterService.submitStateUpdateTask("update customMetaData", new LocalClusterUpdateTask(Priority.IMMEDIATE) {
I'm not sure anymore (it might have had to do with the additional changes that I've made in an earlier version of this PR). I've changed it back.

2016-12-22 15:09 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/tribe/TribeService.java
> -        public boolean runOnlyOnMaster() {
yeah, a remnant of the earlier version of this PR. I reverted that part.

2016-12-22 15:10 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java
> +            clusterService.submitStateUpdateTask("ping from another master", new LocalClusterUpdateTask(Priority.IMMEDIATE) {
> Maybe we should just check we're master within the execute method here and make it a noop if we're not ?

sounds good

2016-12-22 15:10 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/discovery/zen/NodeJoinController.java
> -                .removeGlobalBlock(discoverySettings.getNoMasterBlock()).build();
++

2016-12-22 15:11 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/cluster/service/ClusterService.java
> +        if (newClusterState == null) {
I've changed the LocalClusterUpdateTask to put the previous state when the cluster state is null. This means that we don't have to handle this oddity in ClusterService anymore.

2016-12-22 15:11 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/cluster/service/ClusterService.java
> +                    .removeGlobalBlock(discoverySettings.getNoMasterBlock().id()) // remove block if it already exists before adding new one
I've added an assertion instead

2016-12-22 16:07 UTC, ywelsch commented
@bleskes I've updated the PR with your suggestions (and fixed some tests).

2016-12-23 10:07 UTC, bleskes approved these changes
LGTM. Thanks @ywelsch . I left one question about the tribe service change/roll back. Did you have tests fail before you restored the `runOnlyOnMaster` method?

2016-12-23 10:07 UTC, bleskes commented on core/src/main/java/org/elasticsearch/cluster/service/ClusterService.java
> +        this.discoverySettings = discoverySettings;
can we add `Objects.requireNonNull(discoverySettings, ...);` to the doStart method?

2016-12-23 10:10 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/tribe/TribeService.java
> +        public boolean runOnlyOnMaster() {
They did not pass before rolling this back. I must have pushed something different to what I tested (it was not even compiling).

2016-12-23 10:28 UTC, bleskes commented
ok. No worries - shit happens. I just wanted to make sure everything is explainable. 

> On 23 Dec 2016, at 11:10, Yannick Welsch <notifications@github.com> wrote:
> 
> @ywelsch commented on this pull request.
> 
> In core/src/main/java/org/elasticsearch/tribe/TribeService.java:
> 
> > @@ -365,8 +365,13 @@ public String describeTasks(List<ClusterChangedEvent> tasks) {
>          }
>  
>          @Override
> -        public ClusterTaskResult<ClusterChangedEvent> execute(ClusterState currentState, List<ClusterChangedEvent> tasks) throws Exception {
> -            ClusterTaskResult.Builder<ClusterChangedEvent> builder = ClusterTaskResult.builder();
> +        public boolean runOnlyOnMaster() {
> 
> They did not pass before rolling this back. I must have pushed something different to what I tested (it was not even compiling).
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-12-23 11:22 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/cluster/service/ClusterService.java
> +        this.discoverySettings = discoverySettings;
sure

2016-12-23 11:23 UTC, merged

2016-12-23 11:24 UTC, ywelsch commented
Thanks @bleskes