Fix handling of spaces in Windows paths
elastic/elasticsearch pull request #21921
Opened 2016-12-01 20:11 UTC by jasontedor

This commit fixes the handling of spaces in Windows paths. The current
mechanism works fine in a path that contains a single space, but fails
on a path that contains multiple spaces. With this commit, that is no
longer the case.

Relates #21525

2016-12-01 20:15 UTC, jasontedor commented
I've manually tested this for both running Elasticsearch from the command line and the service, and with paths that contain zero, one, two, and three spaces and everything works as expected.

2016-12-01 22:25 UTC, ngbrown requested changes
When setting environment variables, the full path should be included in the quotes.

2016-12-01 22:25 UTC, ngbrown commented on distribution/src/main/resources/bin/elasticsearch.in.bat
> +  set JAVA="%JAVA_HOME%"\bin\java.exe
The quotes should surround the entire path, including the .exe.

2016-12-01 22:25 UTC, ngbrown commented on distribution/src/main/resources/bin/elasticsearch-service.bat
> +  SET JAVA="%JAVA_HOME%"\bin\java.exe
The quotes should surround the entire path, including the .exe.

2016-12-01 22:46 UTC, jasontedor commented on distribution/src/main/resources/bin/elasticsearch-service.bat
> +  SET JAVA="%JAVA_HOME%"\bin\java.exe
Why? I tested it with this change. Do you have an example where this would break without your suggestion?

2016-12-01 23:16 UTC, rjernst commented
This LGTM. Should we consider (in a follow up) having our integ test dir which contains a space have two spaces (I did not realize it was possible to have different behavior for one vs two spaces).

2016-12-01 23:30 UTC, jasontedor commented
> Should we consider (in a follow up) having our integ test dir which contains a space have two spaces (I did not realize it was possible to have different behavior for one vs two spaces)

Yes, I was thinking the same thing. Lacking packaging tests, that's test best that we can do but it's been really effective for us in the past.

2016-12-02 00:36 UTC, merged

2016-12-02 01:41 UTC, jasontedor commented
Thanks @rjernst.

2016-12-14 07:46 UTC, yannlebel commented
When I read this it seems the issue is not closed and included in a release package but when I download the elasticsearch zip from here https://www.elastic.co/downloads/elasticsearch it's already included. Did something went wrong?

This fix in not working for me. I tested the version 5.1.1 on windows 7 (x64) and windows server 2012 R2 (x64) standard and had the same issue every time.

The quote around the %JAVA_HOME% and %JAVA% variables are not placed correctly which prevent the scripts to start the node and to detect the JVM version which always default the service installation to the x86 version.

My JAVA_HOME variable is set with the value: C:\Program Files\Java\jdk1.8.0_111\
My installation folder for elasticsearch is: D:\ELK\elasticsearch\

######Result of the elasticsearch.bat execution before the fix:
![image](https://cloud.githubusercontent.com/assets/8226325/21173345/93ff6544-c1d7-11e6-8e6c-07f6bc62c384.png)

######Result of the elasticsearch-service.bat execution before the fix:
![image](https://cloud.githubusercontent.com/assets/8226325/21173471/2b469ba2-c1d8-11e6-898a-05017e5c4ba7.png)


To fix the problem I had to do the following changes:
* In elastisearch.bat
    * Line 82
        * From: %JAVA% %ES_JAVA_OPTS% %ES_PARAMS% -cp "%ES_CLASSPATH%" "org.elasticsearch.bootstrap.Elasticsearch" !newparams!
        * To: "%JAVA%" %ES_JAVA_OPTS% %ES_PARAMS% -cp "%ES_CLASSPATH%" "org.elasticsearch.bootstrap.Elasticsearch" !newparams!
* In elasticsearch.in.bat
    * Line 4
        * From: set JAVA="%JAVA_HOME%"\bin\java.exe
        * To: set JAVA=%JAVA_HOME%\bin\java.exe
    * Line 8
        * From: IF NOT EXIST %JAVA% (
        * To: IF NOT EXIST "%JAVA%" (
* In Elasticsearch-service.bat
    * Line 32
        * From: SET JAVA="%JAVA_HOME%"\bin\java.exe
        * To: SET JAVA=%JAVA_HOME%\bin\java.exe
    * Line 36
        * From: IF NOT EXIST %JAVA% (
        * To: IF NOT EXIST "%JAVA%" (
    * Line 55
        * From: %JAVA% -Xmx50M -version > nul 2>&1
        * To: "%JAVA%" -Xmx50M -version > nul 2>&1
    * Line 62
        * From: %JAVA% -Xmx50M -version 2>&1 | "%windir%\System32\find" "64-Bit" >nul:
        * To: "%JAVA%" -Xmx50M -version 2>&1 | "%windir%\System32\find" "64-Bit" >nul:
    * Line 149
        * From: if exist "%JAVA_HOME%"\jre\bin\server\jvm.dll (
        * To: if exist "%JAVA_HOME%\jre\bin\server\jvm.dll" (
    * Line 155
        * From: if exist "%JAVA_HOME%"\bin\server\jvm.dll (
        * To: if exist "%JAVA_HOME%\bin\server\jvm.dll" (
    * Line 161
        * From: if exist "%JAVA_HOME%"\bin\client\jvm.dll (
        * To: if exist "%JAVA_HOME%\bin\client\jvm.dll" (
        

Here are the files with the fixes:

[elasticsearch-service.bat.txt](https://github.com/elastic/elasticsearch/files/650998/elasticsearch-service.bat.txt)
[elasticsearch.bat.txt](https://github.com/elastic/elasticsearch/files/650999/elasticsearch.bat.txt)
[elasticsearch.in.bat.txt](https://github.com/elastic/elasticsearch/files/650997/elasticsearch.in.bat.txt)

Hope it helps.

2016-12-14 11:48 UTC, jasontedor commented
@yannlebel If you remove the trailing backslash from `JAVA_HOME`, what is packaged today works fine. There is an open PR (#22132) to address this.

2016-12-14 12:05 UTC, yannlebel commented
Sorry my mistake I didn't read the changes in the commit correctly and thought this was the PR and #22132 was an issue. I tried without the trailing slash and indead it is working.