Replace comparator with java8 way
elastic/elasticsearch pull request #21936
Opened 2016-12-02 12:35 UTC by likel

This PR is used to upgrade ```Comparator``` with lambda of java 8 which will make the code much shorter and cleaner. Happy to hear your comments. Thanks.

2016-12-02 14:18 UTC, jpountz commented
An alternative would be to use method references instead, ie. `Comparator.comparingInt(ActionFilter::order)` rather than `(o1, o2) -> Integer.compare(o1.order(), o2.order())`. I don't have strong feelings about it, maybe a slight preference for method references. I'll wait and see what others think before merging.

2016-12-02 14:23 UTC, jasontedor commented
I was about to comment the same thing as @jpountz, I prefer the method references where possible. Also, I see at least one change that is not a comparator change (in HppcMaps); can we revert that change and any other such changes and just keep this focused on the comparators for now?

2016-12-02 14:37 UTC, jasontedor requested changes
To keep the surface area of the change smaller, can you please revert the changes that are unrelated to the comparator change which appears to be the main point of this pull request?

2016-12-02 14:37 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/discovery/zen/NodeJoinController.java
> +            joinRequestAccumulator.entrySet().forEach(e -> tasks.put(e.getKey(), new JoinTaskListener(e.getValue(), logger)));
Please revert this change.

2016-12-02 14:37 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/common/network/NetworkUtils.java
> +                list.addAll(Collections.list(intf.getInetAddresses()));
Please revert this change.

2016-12-02 14:37 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/common/collect/HppcMaps.java
> +        return () -> intersection;
Please revert this change.

2016-12-02 14:37 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> +        new Setting<>("index.recovery.initial_shards", NODE_INITIAL_SHARDS_SETTING::get, INITIAL_SHARDS_PARSER,
Please revert this change.

2016-12-02 14:37 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/ingest/IngestDocument.java
> +            valueList.forEach(list::add);
Please revert this change.

2016-12-02 14:37 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/search/query/QueryPhase.java
> +                    topDocsCallable = () -> {
Please revert this change.

2016-12-02 14:37 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/search/query/QueryPhase.java
> +                topDocsCallable = () -> new TopDocs(totalHitCountCollector.getTotalHits(), Lucene.EMPTY_SCORE_DOCS, 0);
Please revert this change.

2016-12-02 14:37 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/search/query/QueryPhase.java
> +                topDocsCallable = () -> {
Please revert this change.

2016-12-02 14:37 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/search/sort/FieldSortBuilder.java
> +        PARSER.declareField(FieldSortBuilder::missing, XContentParser::objectText,  MISSING, ValueType.VALUE);
Please revert this change.

2016-12-02 14:37 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/rest/RestFilterChainTests.java
> +        restController.registerHandler(RestRequest.Method.GET, "/", (request, channel, client) -> channel.sendResponse(new TestResponse()));
Please revert this change.

2016-12-03 04:45 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/discovery/zen/NodeJoinController.java
> +            joinRequestAccumulator.entrySet().forEach(e -> tasks.put(e.getKey(), new JoinTaskListener(e.getValue(), logger)));
None of these changes are necessary, but if we are going to get in these places and make changes, let's do it the preferred way which is with method references (where possible).

2016-12-30 11:04 UTC, closed without merging