fix bug: https://github.com/elastic/elasticsearch/issues/21710
elastic/elasticsearch pull request #21971
Opened 2016-12-05 11:15 UTC by makeyang

throw an exception when specifying include_in_all on sub-fields

2016-12-05 14:53 UTC, nik9000 requested changes
Can you add a test for this? I'd probably make an `org.elasticsearch.index.mapper.IncludeInAllMapperTests` and use `org.elasticsearch.index.mapper.CopyToMapperTests` as an example.

2016-12-05 14:53 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/index/mapper/TypeParsers.java
> +                if(parserContext.isWithinMultiField()) {
Nit: usually we put a space between `if` and `(`

2016-12-05 14:53 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/index/mapper/TypeParsers.java
> +                    throw new MapperParsingException("sub-fields shouldn't contain property: include_in_all, and current node is:" + name);
Have a look at the example below for copy_to about how we usually write these field names. We wrap all the variable bits of exception messages in `[]` almost everywhere. Right or wrong it is our habit and we should stick to it unless we have a good reason not to.

2016-12-08 03:07 UTC, makeyang commented
@nik9000  I modified code according to your comments. I'll commit test later. but I have one question related to CopyToMapperTests: it seems in this test, this exception: 
MapperParsingException("copy_to in multi fields is not allowed. Found the copy_to in field [" + name + "] which is within a multi field.")
is not test?
if so, why? if it is not the truth, tell me some details. thanks

2016-12-08 03:26 UTC, nik9000 commented
> is not test?

You mean that test doesn't exist? I suspect we just forgot to make it. If you'd like to make it while you are there that'd be lovely.

2016-12-08 11:46 UTC, makeyang commented
@nik9000  it turns out that it is tested but in another test case file:MultiFieldCopyToMapperTests. so I add this new test case file:MultiFieldIncludeInAllMapperTests
please help to review. thanks

2016-12-14 11:35 UTC, makeyang commented
@nik9000  can you help to review this?

2016-12-14 16:37 UTC, nik9000 requested changes

2016-12-14 16:37 UTC, nik9000 commented on core/src/test/java/org/elasticsearch/index/mapper/MultiFieldIncludeInAllMapperTests.java
> + * Created by makeyang on 2016/12/8.
Can you replace this with something descriptive of what it does or remove it?

2016-12-14 16:37 UTC, nik9000 commented on core/src/test/java/org/elasticsearch/index/mapper/MultiFieldIncludeInAllMapperTests.java
> +            fail("Parsing should throw an exception because the mapping contains a include_in_all in a multi field");
We tend to use `expectThrows` for this when we write new tests. It isn't required but it is a bit cleaner to read.

2016-12-15 06:34 UTC, makeyang commented
@nik9000 can you help to review this please?

2016-12-19 08:26 UTC, makeyang commented
@nik9000  can you help to review this or ask someone else to help to review it? thanks very much.

2016-12-19 18:59 UTC, nik9000 approved these changes

2016-12-19 18:59 UTC, nik9000 commented
Looks right to me!

elasticmachine, please test this.

2016-12-19 20:07 UTC, merged

2016-12-19 20:07 UTC, nik9000 commented
Thanks @makeyang! I've merged to master and will backport to 5.x:

master: 2e1d152fc0b50633e832b8785d961325e480b54e + 40b80ae10460567144bbb0d8dcb606d4a10418ac
5.x: ![backporting](http://i.imgur.com/kPvJ3By.gif)

2016-12-20 02:00 UTC, makeyang commented
@nik9000  thanks very much.

2017-03-20 13:24 UTC, mfeltscher commented
Isn't this a breaking change? This broke our mappings while upgrading from 5.1.x to 5.2.x

2017-03-20 15:47 UTC, clintongormley commented
@mfeltscher thanks for reporting and yes, this shouldn't have gone into 5.2.  i've opened https://github.com/elastic/elasticsearch/issues/23654