Introduce XContentParser#namedXObject
elastic/elasticsearch pull request #22003
Opened 2016-12-06 17:38 UTC by nik9000

Introduces XContentParser#namedXContent which works a little like `StreamInput#readNamedWriteable`: on startup components register parsers under names and a superclass. At runtime we look up the parser and call it to parse the object.
    
Right now the parsers take a `context` object they use to help with the parsing but I hope to be able to eliminate the need for this context as most what it is used for at this point is to move around parser registries which should be replaced by this method eventually. I make no effort to do so in this PR because it is big enough already. This is meant to the a start down a road that allows us to remove classes like `QueryParseContext`, `AggregatorParsers`, `IndicesQueriesRegistry`, and `ParseFieldRegistry`.

The goal here is to reduce the amount of plumbing required to allow parsing pluggable things. With this you don't have to pass registries all over the place. Instead you must pass a super registry to fewer places and use it to wrap the reader. This is the same tradeoff that we use for NamedWriteable and it allows much, much simpler binary serialization. We *think* we want that same thing for xcontent serialization.

The only parsing actually converted to this method is parsing `ScoreFunction`s inside of `FunctionScoreQuery`. I chose this because it is relatively self contained.

2016-12-06 17:40 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/node/Node.java
> +                    searchModule.getNamedXContents().stream()
I use this funny looking construct to match with the constructs above. It'll eventually have more than one module it has to stream, just like above.

2016-12-06 17:40 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/node/Node.java
> +                    b.bind(NamedXContentRegistry.class).toInstance(xContentRegistry);
I hate binding another thing but in subsequent PRs I'll use this to remove a bunch of things.

2016-12-06 17:41 UTC, nik9000 commented
I think at least @javanna, @rjernst, @martijnvg and maybe others might have an interest in this.

2016-12-06 19:09 UTC, rjernst commented
I love the concept; it has been a pain to deal with those registries like QueryParserRegistry when trying to deguice the rest side of things. I left some comments about wrapping, as I think it makes things confusing and will be used wrong (hence all the need for the extra checks you have on passing wrapped vs unwrapped parsers).

2016-12-06 19:29 UTC, nik9000 commented
> I left some comments about wrapping

They didn't stick. Do you want to make the registry required for building the XContentParser or something like that?

2016-12-06 19:30 UTC, rjernst commented on core/src/main/java/org/elasticsearch/common/xcontent/NamedXContentRegistry.java
> +        for (Entry entry : entries) {
Can you make this algorithm the same as that in the NamedWriteableRegistry? I think it is cleaner (does not require replacing the inner maps to make them unmodifiable.

2016-12-06 19:30 UTC, rjernst commented on core/src/main/java/org/elasticsearch/common/xcontent/NamedXContentRegistry.java
> +    public XContentParser wrap(XContentParser parser) {
Why isn't this inside xcontentfactory.creatParser? In fact why do we need a wrapper at all? Can't this just be native methods on XContentParser?

2016-12-06 20:16 UTC, nik9000 commented
I talked with @rjernst over another channel. I'm going to implement the suggestion to use NamedWriteableRegistry's algorithm for building the map of maps. I'm going to *try* and make the registry a required parameter for building the XContentParser. That'll balloon this PR significantly but this is the right time for it. I'll try and take some shortcuts, mostly moving where the parsers are built so we don't have thousands of spots where we build the parsers. That also means I'll remove all the methods called `wrap`.

2016-12-16 15:45 UTC, nik9000 commented
OK! I've got the code *compiling*. I've taken a bunch of shortcuts, used NamedXContentRegistry.EMPTY in a bunch of places where it probably can't be forever. I'm now working to get the tests passing. Once they pass I'll update.

2016-12-16 18:55 UTC, nik9000 commented
Everything is passing locally!

2016-12-19 00:44 UTC, imotov requested changes
Left some comments

2016-12-19 14:58 UTC, nik9000 commented
@martijnvg  and @imotov: for the unknown custom prototype stuff, would you prefer a new subclass of `ParsingException` or another version of `namedObject` that returns `Optional` and is `empty` when it can't find the right parser? I kind of prefer the former because that means I only need one method.

2016-12-19 15:01 UTC, nik9000 commented
@imotov I pushed some commits that add an explanation comment for every non-test usage of `NamedXContent.EMPTY` and removes many of the usages.

2016-12-19 15:19 UTC, imotov commented
@nik9000 @martijnvg the reason I asked to add another exception is because I think that a missing parser is still an error, but we react to this error in a different way comparing to the corrupted xcontent stream that we cannot parse. Returning Optional would work for me, but I think it wouldn't be semantically correct since in my mind it would indicate that object doesn't exist (rather than object exits but we cannot read it)

2016-12-19 15:20 UTC, nik9000 commented
I'm happy to make a new exception!

2016-12-19 18:51 UTC, nik9000 commented
@imotov, can you have another look?

2016-12-20 00:57 UTC, imotov approved these changes
Left a couple of minor comments. Otherwise LGTM.

2016-12-20 00:57 UTC, imotov commented on core/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java
> +                                                  NamedXContentRegistry xContentRegistry, SearchRequestParsers searchRequestParsers,
xContentRegistry is not used in this method

2016-12-20 02:00 UTC, nik9000 commented on core/src/test/java/org/elasticsearch/common/xcontent/BaseXContentTestCase.java
> +        // TODO when https://github.com/elastic/elasticsearch/pull/22130 is in check the warning
Yah. I'll rebase before merging and use it.

2016-12-20 15:03 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java
> +                                                  NamedXContentRegistry xContentRegistry, SearchRequestParsers searchRequestParsers,
Removed!

2016-12-20 16:05 UTC, merged

2016-12-20 16:06 UTC, nik9000 commented
Thanks for reviewing @imotov! I've merged to:

master: a04dcfb95b1defb954c7be5016ad5865e9099c97
5.x: ![backporting](http://i.imgur.com/kPvJ3By.gif)