Catch Throwable in case of major error when extracting content
elastic/elasticsearch pull request #22079
Opened 2016-12-09 15:55 UTC by dadoonet

* Send a non supported document to an ingest pipeline using `ingest-attachment`
* If Tika is not able to parse the document because of a missing class (we are not importing all jars needed by Tika), Tika throws a Throwable which is not catch.

This commit catches the Throwable and wrap it into a `ElasticsearchParseException`.

So elasticsearch is not killed anymore when you run a command like:

```
GET _ingest/pipeline/_simulate
{
  "pipeline" : {
    "processors" : [
      {
        "attachment" : {
          "field" : "file"
        }
      }
    ]  
  },
  "docs" : [
    {
      "_source" : {
        "file" : "UEsDBBQABgAIAAAAIQC0lAFevwEAAK8IAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADElklv2zAQhe8F8h8EXgOJTg5BUVjOocuxCdAU6JUmRzZRcQFnvP37Dr0IRSBHRh2hFwHSzHvv4xASNX3curZYQ0IbfC3uqokowOtgrF/U4ufLt/KjKJCUN6oNHmqxAxSPs5sP05ddBCxY7bEWS6L4SUrUS3AKqxDBc6UJySni27SQUenfagHyfjJ5kDp4Ak8lZQ8xm36BRq1aKr5u+fGBBFwjis+HvhxVC+uyflvmiuzVJGjxlUjF2FqtiOty7c0rsvJIVbFy34NLG/GWG84k5Mr5gPO6NZrtAJnDcm25uzJJbXj62emJNyZZA8WzSvRdOZbJTUhGmqBXjq2qt4F6Vhyaxmro9NktpqABkTNdW3UVp6w/TaKPQ6+QgvvlWmkJ3HMKEe+uxulMsx8kstDtxtlZ+JWbQ2L69x9GZz0IgbRrAd+f4OA7HA9ELBgD4Og8iLCB+Y/RKP4yHwRpQiAfaIzd6KwHIcCbkRhOzhfNAdL172TvFCBdmH//H/M5T81bGIPgaD0IQXwgwuF6/U7sbd6K5M79h5gP2PQPyz6dhlldxou+wF0iW1+9PsgHpgHTky33vxuzPwAAAP//AwBQSwMEFAAGAAgAAAAhAB6RGrfvAAAATgIAAAsACAJfcmVscy8ucmVscyCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsksFqwzAMQO+D/YPRvVHawRijTi9j0NsY2QcIW0lME9vYatf+/TzY2AJd6WFHy9LTk9B6c5xGdeCUXfAallUNir0J1vlew1v7vHgAlYW8pTF41nDiDJvm9mb9yiNJKcqDi1kVis8aBpH4iJjNwBPlKkT25acLaSIpz9RjJLOjnnFV1/eYfjOgmTHV1mpIW3sHqj1FvoYdus4ZfgpmP7GXMy2Qj8Lesl3EVOqTuDKNain1LBpsMC8lnJFirAoa8LzR6nqjv6fFiYUsCaEJiS/7fGZcElr+54rmGT827yFZtF/hbxucXUHzAQAA//8DAFBLAwQUAAYACAAAACEAUyT3RoEBAAByBwAAHAAIAXdvcmQvX3JlbHMvZG9jdW1lbnQueG1sLnJlbHMgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0lctOwzAQRfdI/EPkPXFToDzUtJsKqQs2UBC7yk0mqUVsR/b09fdMKU1TKBYLs/S1PPfoeuzpD9eqipZgnTQ6ZUncYRHozORSlyl7mTxc3LLIodC5qIyGlG3AseHg/Kz/BJVAOuTmsnYRVdEuZXPE+p5zl81BCRebGjTtFMYqgbS0Ja9F9i5K4N1Op8dtuwYbHNWMxnnK7Dgn/8mmhr/UNkUhMxiZbKFA4wkLLhV5U0FhS8CUKcil2IlJDKpg/DRDchkSAulsC+JzuROTmIr9BhGUweGmoptsIHZrn/1NSHvQuTbYBtgrPoSkG5KhMBonYla1rqKRfBRBIfRCzcDSYztANJI3ipAQ2cKhUW/k1kDE8UHlEkF5W7MX9l4MfmuORvJGEjSTrSXYYwSwXR/AdUj/FcyeAZHaoJVDS/Qm0fn/JLz9cBX0q/oRw17xIdyFRPgaWq3fip5ovp2Rjj/KzBpnCpy+Shqi05EVK9pI4qXL11s6fjQpBx8AAAD//wMAUEsDBBQABgAIAAAAIQCHBIL5pAwAALJAAAARAAAAd29yZC9kb2N1bWVudC54bWzsWFtv4jgUfl9p/0OUd5oLAVJUGLUU2j4NmtK3SiuTGOJtYmdtA0N//Rw7Vy7l1unLaFupCcc+3/nOHfXm288kNpaYC8Joz3SubNPANGAhofOe+TIZNXzTEBLREMWM4p65xsL81v/7r5tVN2TBIsFUGgBBRXeVBj0zkjLtWpYIIpwgcZWQgDPBZvIqYInFZjMSYGvFeGi5tmPrt5SzAAsB9gaILpEwc7jg52loIUcrUFaAnhVEiEv8s8JwzgZpWdeWvw2U7LrGUkzhcMZ4giR85HMrQfxtkTYAN0WSTElM5Bog7XYBw3rmgtNuDtEoqSiVbkYlfxQa/BS7mcp9ng5t0eI4Bg6MioikZUyTS9HgMCpAloecWCZxcW+VOt7nCuI+y0oFeAr9PJVJnDE/jOjYJ2REQZQap1DYtFkwSRChleGLQlMLrtM6D8DdAWgLfB5EK4ewxDqpWmOVzj+X5QfOFmmFRj6H9kTfSiw1r87AyqulXsHic2SeI5RCKydB92lOGUfTGBhB7g1In6EzYKguMfswTacsXKtnCgdeN0UcPYU9s+l57VZzeG9qKUwkqaSd/AekXZjc4Y+eCeybnbZ7V4ru8QwtYqlOmo7rXTvFybh2WRscc/14lusY+HSXKO6ZjxipFeCYVv/GKu9MGXtTQ+5ZwnSEqwS42AqXogQ8+2fCAq/tt52W73eUJhhUf1S4HtdphGmGpoV8D3cll/2JipPBZsaAUQkjSCgdWWkWLIY0LDnkNLW1UOaPjDTPHyNAE6CARECgyAYoJlNOFHuMhLwVBE0gxeBGQiBXj7dU6MNIvVTXtVfTIkzaMHweKOC6JGAxUx5qmWerXwUmlYWBOuuZKpk6KVo4IRRydTfK1MV7oevmgOK9suG6mSxGdF7IMG0MbuvOaNHLcx6ZPAhERUzfb7h2y3Vdx/O9DAy2+Riy+n36b+3TA4pjzNeF0k5mNlRfKPlvgTN7dTSrlgx4gbSNeeZTKHOg3cK3r+2h741UgC4v/GNVPvk+yAu9XudFIW0ScjzXvWu5ynSNUNu/7jiep/qzIuTbrfZIJ2ObkN1puc5hQrrloCjQVOTP4jDGM6lAUwZjyfPywqhd4GQe6RsxOIWhxEJWKVw3W0WbFNh7O2NvE+zrkGEuK5tkr2YgdHnn4jsS5i1E2ZgzNtttFrSQbKcJ9hf8ZnVXY6ocLWOugu62IeYdHfRZHA7gm51Rvk3WKXCb4jns5iPD6UNQQoXkEygItTa6IkUBQKYcC8yX2OwbkFTjlRmm02iaxmtkvL4brwtD2So191g+lbvAqkIlrtOP4ITHhL6ppNIgUuNmczirnBEhGV9DZWv4DZe3KjjjMnDbdnuUXc4DvbkzCqvbGa7mj+w7W8N8n9k/rzZ1z31UX18X7GOb9Ejw63FY4ekjCcNyhZ/q1VlwF7XnJYaOtez49mH4YzgyNppG9e6xrr2M0FcHcN+M+Hzuz+3li+ljGlbMrdp4+3BXu/6gNfBG5sauhm88o9vh3bDstMO7uubA/7v6y3b1sVXlH1pVv3FUutu1/OcF/cNx/RvD+EQlZ+EiUP96OhDRszfLWbonr5GzUDd3xi8AAAD//+xabXOjOBL+KxT39TZB4t23TsXGeJKq2Uoqyd59uaopDLLNBCMOsJPsr79uCTDY2Mlkk6naLc9UOUhqie6nW0+3ZBdZELKhmuWsYPmGqRfK7eiLf+dPlW8PPDQsxyKm4zjKf5fKr+dPgzgtyvyBPZcX2Movfq0/bsWflN/mnM/P8fmJza7iKGLpuZRFiffMeRrMk8hbBrnSPD28ZKBzwbIgD0qmVsI/vnB5QbH1TmMOKsbSaKsTfC6hN0/i9FG0MpyZKU/EGKD+19FQpZPxxPdcSxW9JcCLvbZFDI0S7B3kRRzdDVVNczTTmo6argmbB+ukbI2I1aV62X35kjAQ3QTJUH248QiqBfYGs6L6Ww8mbF7iohkvhqphaI1gLZDHi6WQSFgQsXyoRnw7wdVNMQOxrNauEMqnPC0LkAuKMI4flmwF+KzilOdXo7SIcQUWFOWoiIP2oF/14fgSBXtnhkXZ6h7HUSzVbjsu5AlHBwkjgnXJpUjxR91HqexJgnRR97H0l9/vaxdWcVth2vgSbUrDJQco2jvFFSrHRcnzl6FKhDvw/cJbtzk6yqOWZk3lSIVSx1FX9St2rWkHrn4kcP8moItgau/tT4DxZgOsF7OnP0UDO2r+0NwDFDJjizh9P7E1NK08r5JB8SaOd08c/5kcb42oO/Vd2uV4Q/ccV3fNj+N4/W0cT4h2Ivl3kryr/SySPyNn5ET0HwHldaoUIc+Y8nvBlDAoWHGifFc7Uf6nUr5DHDLR9S7lm9bEHE19wSEnyv+rUD75iZR/LHpPlP/22n5dKnyu3De0751oX8byifY/k/Y1jZrEcewu7du6PRr5U+PjaL/aZ6/RvuOcWP+9rI+ntZ/D+ifO/xAgJ0EZKEEaKddpyRbAJzFPT4zv0hPjfybjm1PDsDxz9/6++tdhfEu3LTpuumToU4uS8VaulQY024SheuS2JSwM7V3mByzLxGcRlR4wDEslkNDsMdGfTjTDQVVeM3GqE2Jv81zLmmpErC49gOEbC86YsTnPQUVxLgrmJWYlKg8sW74WHzM0qxT2ZMGiFT79zqHjkaE7Dir0mubuWHesSZ/mjkN0Iu72Gz9YLhmNJNq9GfoKUiuYJr5z2Vow4/xxFeSP92WQlyAaR5hX4CENkIQ7X7pJohPTEuDyO/Aey1l0C0aPcxY8imG82ihzHq3DHq6r3+YDI9bvqtTpAcr1RpZv7xxXe4GaTAx/tP1iSoYfAeduMWqjNxkbridyaYNetcIHoCfW3UfPbaF38J5/Hx+RyPrxMcYQ//rI+fFd3oKiOyKg0KaWMZWJ7xgU4pR/HAp03T4UblX/VVDUN2G7zNnW3/F005QqHUozx6bTieEaVE6/OHThto99Y+Eh+wSpVPZ94eMgrGqB/aUMOdB1oD6lEKI+huirDrTAS9vCXAb4Tmfbq9T0aHOJL+lBCre8+j2sPRoC1bK8h9r47DsL0droObiBIh32q+ZSwQ/RS9XjuDZ2gAWyYhVHDtd0bM3D/bQZFMsgY8iPCiLx7RkiTPtW2qBeyHkeFfEfgB8llqb9U3yqCgf/gh0owgfg4znLc5ZA8bQBSTgYZEG5hALx0rg0E/gg5NKVH+YzU5V5nCQM3jRXFSgu+KN8FpqIpvKdY9kBEY1FZmX4ZgB0v1oDr4lnhf0vHarxXIE0yyZ58JQqWfzMkq/Q/E8clUtFBHEjWaxXyqWmkJ5uDf5fCt5oujPgR+WSgrjY3jv9uiJgkC8UL3tN6IqJ81OPQqBSz2TrwJvt428WazqVTNfQnvmHlCJae4XzLvDoWfA5bIV8XUD+4I/Cj1A5RzEEqQgl7CsxMkKephCeMvXm8IQL8kHCw0dlg2tAgRHFIBoUGYyK6hunytc2YdnEaDs+Y6LhBpJr/6MdtFXkPCE8A93Qzpys/NdSGDugjnZGM6EcRyERdfEKEmSEB4FccAHsEAclyrgUMi11UP2br/6N3HayRvJXMxapCtSOi+vJUP13DLicYUgCB58RUOgeZ+JQV3UUGQnDh2pVTqmKXFkIE9Ogumk7Osg2ioksdV5v/OOFDJRgnm+ab8o/tukBf3fpSyPWGAHtoa+OuExKUriHRak1tXXbQB780DRIPaoZk49Ig8LG/TRY/fqlrghat4M/MxX2XULu5y+BfH8Y2CbRPH+680VyL/7Ut6nR1F1t/LsjEv+tpr34f42LcrwGqhcbGgBer6oDabJJaqGq1ICxazRl23feniDMxEsqyMmW/DI1SOFQvJDtloMPVGIuMYyp+6bDyNTSfL8Pgu6IgMC1dWIfKUo/CoLj1tGx7k+0MZ5DXrNuPNZNq7ci6Y4I66qu1zZYUwEf3mCi8t/fYNUlULX [...]

2016-12-09 16:13 UTC, jasontedor requested changes
Sorry @dadoonet.

2016-12-09 16:13 UTC, jasontedor commented on plugins/ingest-attachment/src/main/java/org/elasticsearch/ingest/attachment/AttachmentProcessor.java
> +        } catch (Throwable e) {
Let's not do this. We worked incredibly hard to remove it from the codebase, see #19231. It just hides bugs, and swallows truly fatal errors.

2016-12-12 10:57 UTC, dadoonet commented
@jasontedor Can you tell me what you think of the latest changes? Thanks!

2016-12-12 14:48 UTC, jasontedor commented
Why are we doing this instead of adding the missing dependency?

2016-12-12 16:34 UTC, javanna commented
I totally agree on not catching Throwable and the effort made to change that in our codebase. That said in this specific case it seems pretty awkward that the node crashes. Is it right to let it go down for a missing dependency problem triggered by some specific call? I guess there is no way to check for this earlier when the node is started?

2016-12-12 16:55 UTC, dadoonet commented
> Why are we doing this instead of adding the missing dependency?

Well. We reduced the number of dependencies with this PR: https://github.com/elastic/elasticsearch-mapper-attachments/pull/186.
IIRC we wanted to avoid some Security Manager issues with 3rd party libs and some JarHell issues.

We ended up saying that we will only support a subset of files. Here the user is sending a Word document which is supported but within the Word document he is having an embedded Visio Chart, which we don't support.
Probably we can fix the issue for Visio. But then, what will be the next problem? MP3?

I think that killing a node because a end user is sending a non supported format should be prevented.

@javanna No we can't check that on startup because it depends on the end user's request.

2016-12-12 17:24 UTC, rjernst commented
> Is it right to let it go down for a missing dependency

Yes, it is. We (developers) did not setup the system correctly. We didn't find the problem because of inadequate tests. Let's fix the tests, not try to mask the problems.

The underlying issue is the OOXMLParser in tika is poorly designed (all static functions) and does not allow overriding which embedded formats are supported. If we are going to handle this by catching (instead of adding the dependency), then it should be completely local and specific to this case, not general purpose for all of tika (so we don't mask other issues). OOXMLParser is subclassable, where we can catch the NCDFE, not throwable. But such a hack should only be done after opening an issue in tika (and referencing in a comment with the hacky catch).

We also desperately need more tests, ideally each type of embedded file (and there are a limited number of these that are possible, so we should try to cover each one). I believe tika has an extensive collection of files for testing, perhaps we can reuse some of those?

2016-12-12 17:28 UTC, dadoonet commented
> so we don't mask other issues

We don't mask it here. We fail the ingestion with an error message which tells what is happening.

```java
throw new ElasticsearchParseException("Missing classes to parse document in field [{}]", e, field);
```

We just don't kill anymore the node.

Definitely I don't want to hide any error.

2016-12-13 14:31 UTC, javanna commented
I think everybody agrees that we should not blindly catch Throwable in our code. We made efforts to not hide OOM errors and such, and we don't want to go back there for sure. But, maybe I didn't state it clearly, I don't think it is acceptable that a node crashes because of a missing dependency. We are currently exposing an api that can kill a node, that is a big concerning problem to me. I am not confident that this category of errors with the attachment processor can be solved by testing, cause so many things can go wrong with tika and the many formats it supports. For sure catching `NoClassDefFoundError` is not an elegant solution, it's far from ideal, but is there a better alternative that doesn't involve crashing a node then?

2016-12-13 14:45 UTC, clintongormley commented
> But, maybe I didn't state it clearly, I don't think it is acceptable that a node crashes because of a missing dependency. We are currently exposing an api that can kill a node, that is a big concerning problem to me.

+1

2016-12-13 14:56 UTC, nik9000 commented
I think if we should add the dependency we should add the dependency and consider that the bug that caused the thing to go down, not the lack of catch. If we don't want the dependency we should figure out some way to work around not having it. I don't think we should have a global "catch NoClassDefError" across all of our code because we don't want to hide other problems. If the way work around this is by catching the Error then I'm all for adding it, but I agree with @rjernst that we should file an issue with tika. If they intend for us to be able to run without the dependency then they should throw a friendlier exception. If they don't intend for us to be able to run without the dependency then we have more thinking to do....

2016-12-13 15:57 UTC, javanna commented
> I don't think we should have a global "catch NoClassDefError" across all of our code because we don't want to hide other problems.

David is introducing a catch in the `AttachmentProcessor`, that is not a global catch. Anyways, I do see how it is not the most elegant solution. Even if we are going to add this missing jar back and testing this case explicitly and filing an issue to tika, I wonder how long it will take for a similar error to arise due to another missing dependency which we haven't yet tested. Can we really make sure that we test all the possible situations here?

2016-12-13 16:01 UTC, nik9000 commented
> David is introducing a catch in the AttachmentProcessor, that is not a global catch.

Right. I'm cool with it.

> Can we really make sure that we test all the possible situations here?

That argument makes sense to me. Something along the lines of "Tika throws these instead of UnsupportedOperationException when you are missing an optional dependency." is fine reasoning for adding it. I think we should file an issue with Tika about it. I'd like to be able to remove it one day and catch something that is less likely to mask other weird stuff.

2016-12-14 08:31 UTC, dadoonet commented
So what is the outcome on this? Do we want to merge my PR?
I opened https://issues.apache.org/jira/browse/TIKA-2208 to see if they can do anything better on their side.

2016-12-14 13:19 UTC, jasontedor commented
I agree that taking a node down in this situation is bad, but I disagree with the conclusion that we should catch `NoClassDefFoundError` here. Catching `NoClassDefFoundError` is too blunt, it catches more than just a missing dependency for an embedded document format that we do not support (for example, a class initializer that throws will cause a `NoClassDefFoundError` too; [JLS 12.4.2](http://docs.oracle.com/javase/specs/jls/se8/html/jls-12.html#jls-12.4.2)):

> 5. If the `Class` object for `C` is in an erroneous state, then initialization is not possible. Release `LC` and throw a `NoClassDefFoundError`.

Like @rjernst said, we need to work this one on the Tika side.

2016-12-14 14:01 UTC, dadoonet commented
I'm going to test the workaround proposed on the JIRA and will update the PR if successful.

2016-12-14 14:25 UTC, jasontedor commented
Thanks @dadoonet.

2016-12-16 08:22 UTC, dadoonet commented
For information, the proposed workaround does not work in our case as I explained at https://issues.apache.org/jira/browse/TIKA-2208?focusedCommentId=15753790&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15753790

Basically, the Tika checks are made when Tika instance is created not when it is used.

I can obviously fix the current problem by adding the missing library but I think that it will hide potential other issues with missing JARs.
May be we can do something on Gradle side which checks that when we add an explicit dependency like `org.apache.poi:poi-ooxml:3.15`, all the needed transitive dependencies are also declared?

2016-12-16 15:02 UTC, dadoonet commented
I pushed another commit based on the latest discussions I had with Tika team.
I also changed the title and the description of the PR.

What it does now:

* We still don't support Visio files
* If an embedded Visio content exists in a Word `docx` file, its extraction is now skipped
* Which means that we don't fail anymore, we don't have any exception and cherry on the cake, the text coming from the `docx` file is extracted!

2016-12-16 19:20 UTC, nik9000 commented on plugins/ingest-attachment/src/main/java/org/elasticsearch/ingest/attachment/TikaImpl.java
> +    private static final Set<MediaType> EXCLUDES =
This is usually easier to write as `Collections.singleton("x-tika-ooxml")`.

2016-12-16 19:22 UTC, nik9000 commented on plugins/ingest-attachment/src/main/java/org/elasticsearch/ingest/attachment/TikaImpl.java
> +    private static final Set<MediaType> EXCLUDES =
Er, `Collections.singleton(MediaType.application("x-tika-ooxml"))` actually.

2016-12-16 19:23 UTC, nik9000 approved these changes
Change makes sense and is what upstream advises and tests make sense.

2016-12-17 07:56 UTC, dadoonet commented
@jasontedor Can you also please update your review? Thanks!

2016-12-17 10:54 UTC, jasontedor approved these changes
Thanks for your work on this @dadoonet, I think that we got to the right place. LGTM.

2016-12-18 13:37 UTC, dadoonet commented
So this is making our tests failing now.
I need to dig more. 

`testPPT.potm` Tika sample file is now returned with an empty content as soon as we add `Collections.singleton(MediaType.application("x-tika-ooxml")`.

2016-12-18 13:59 UTC, dadoonet commented
I checked the full suite of documents we have and only `testPPT.potm` is now failing.
I asked on [Tika project](https://issues.apache.org/jira/browse/TIKA-2208?focusedCommentId=15758867&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15758867) to see if we have a workaround.

If not, we have 2 choices I believe:

* Revert completely my change and just add missing libraries
* remove support of `potm` files

From http://www.reviversoft.com/file-extensions/potm:

> The POTM file extension is used to label macro-enabled templates created by Microsoft’s PowerPoint, a well-known software used to create presentations with the use of slide shows. 

So I think we should better add missing lib. But it will never prevent not parseable embedded content.
We can just expect that Tika is able to handle such a case instead of throwing a ClassNotFoundError.

2016-12-18 14:11 UTC, dadoonet commented
I tried to add missing libs:

```gradle
  compile "com.github.virtuald:curvesapi:1.04"
  compile "com.bbn.poi.visio:ooxml-visio-schemas:2011.1"
```

But it now fails with JarHell:

```
Caused by: java.lang.IllegalStateException: jar hell!
class: com.microsoft.schemas.office.visio.x2012.main.CellType$Factory
jar1: /Users/dpilato/.gradle/caches/modules-2/files-2.1/org.apache.poi/poi-ooxml-schemas/3.15/de4a50ca39de48a19606b35644ecadb2f733c479/poi-ooxml-schemas-3.15.jar
jar2: /Users/dpilato/.gradle/caches/modules-2/files-2.1/com.bbn.poi.visio/ooxml-visio-schemas/2011.1/5c395aefc5c1a33f517c243843c909c1f4d6b3f0/ooxml-visio-schemas-2011.1.jar
```

2017-01-23 14:56 UTC, dadoonet commented
@jasontedor Do you have any idea on how I could fix https://github.com/elastic/elasticsearch/pull/22079#issuecomment-267823297?

2017-01-23 15:30 UTC, jasontedor commented
> > The POTM file extension is used to label macro-enabled templates created by Microsoft’s PowerPoint, a well-known software used to create presentations with the use of slide shows.

Do we really need to support this, it seems obscure?

2017-02-02 18:08 UTC, sergeytkachenko commented
Hello everybody.
The error persists?
We have this problem in production ES 5.2.0

2017-02-03 10:05 UTC, dadoonet commented
@sergeytkachenko About your error here, I think we probably don't want to support indexing Visio files. At least we don't mean to support them. I'm going to try to have a proper rejection when you index a Visio file instead of killing the node like this.
But the issue we have within this thread is happening when you have a Visio content (not supported) embedded within a Word document (supported).

Thanks for sharing your Visio file BTW!

2017-02-03 11:56 UTC, dadoonet commented
Actually I was wrong. This PR removes support for Visio files even embedded. I'm going to update the PR soonish.

2017-02-03 12:05 UTC, dadoonet commented
@jasontedor So I removed support for POTM files. I rebased on master and squashed everything. Could you check again this PR?

2017-02-03 14:44 UTC, jasontedor commented
I am missing in this pull request where support for POTM files was removed?

Also, please do not squash commits in the middle of review cycles. You can merge master into your branch instead of rebasing, too.

2017-02-03 15:00 UTC, dadoonet commented
@jasontedor `POTM` is removed in the zip file. That's why you can't see it and why I opened #22958

2017-02-03 15:13 UTC, dadoonet commented
I'm going to push a new commit to my branch because I just merged #22959 so you will see in a more obvious way the POTM file removal.

2017-02-03 15:23 UTC, dadoonet commented
@jasontedor I merged with master so it's ready. Can you review it please?

2017-02-03 16:26 UTC, sergeytkachenko commented
@dadoonet thank you repaired, and now we do not have such an error!

2017-02-03 17:47 UTC, dadoonet commented
@sergeytkachenko Do you mean that you tried out that branch?

2017-02-03 18:01 UTC, sergeytkachenko commented
@dadoonet Yes! 
I build elasticsearch 6 and ingest-attachemnt 6 plugin with gradel from fix/22077-ingest-attachment branch. 
And error has gone.
Thank you very match!

2017-02-03 18:09 UTC, dadoonet commented
Thanks for testing it @sergeytkachenko. 

You can apply the same fix on 5.2.0 tag and build another version of the plugin if it's a blocker for your production.

2017-02-16 08:23 UTC, dadoonet commented
If no one objects in the meantime, I'll merge that change tomorrow morning CET.

2017-02-16 13:45 UTC, jasontedor approved these changes
LGTM.

2017-02-16 14:47 UTC, dadoonet commented
Thanks @jasontedor !

2017-02-16 15:00 UTC, merged