Add plugin for integration test with multiple clusters
elastic/elasticsearch pull request #22106
Opened 2016-12-12 06:02 UTC by areek

This commit adds a plugin that allows to specify
any number of clusters to be formed and used with
the existing `RestTestPlugin`. The plugin takes care
of creating tasks for forming additional clusters and
dependancies between test task and cluster formation tasks.

2016-12-12 06:06 UTC, areek commented
@rjernst could you take a look please?

2016-12-20 14:15 UTC, nik9000 requested changes
I found a few small things but it looks right to me.

2016-12-20 14:15 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterTask.groovy
> +        description = "create a cluster"
description is useful if you think people'll execute it on the command line but I think this task is usually a dependency for other tasks so we don't expect people to execute it. In that case the comment above the task is probably fine.

2016-12-20 14:15 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClustersTask.groovy
> +        description = "create a list of cluster"
Same here.

2016-12-20 14:15 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/MultiClusterTestPlugin.groovy
> +        RestIntegTestTask integTest = project.tasks.create('integTest', RestIntegTestTask.class)
Maybe instead apply `RestTestPlugin` and and look up this task so you can setup the dependency.

2016-12-20 14:15 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/MultiClusterTestPlugin.groovy
> +        project.gradle.projectsEvaluated {
Can you add a comment about why you need `projectsEvaluated` here? I can't tell by reading it.

2016-12-20 15:00 UTC, areek commented
thanks for the review @nik9000! I addressed your comments

2016-12-20 16:04 UTC, nik9000 reviewed
I'm starting to understand this more. I left a bunch of small things but nothing big.

2016-12-20 16:04 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/MultiClusterTestPlugin.groovy
>          integTest.cluster.distribution = 'zip' // rest tests should run with the real zip
This one comes with `RestTestPlugin` I think.

2016-12-20 16:04 UTC, nik9000 commented on qa/smoke-test-tribe-node/build.gradle
> +clusters {
I wonder if this should be `extraClusters` to make it clear that these are in addition to (not replacing) the cluster that you get from `integTest`.

2016-12-20 16:04 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterTask.groovy
> +        project.gradle.projectsEvaluated {
Can you leave a comment explaining why `projectsEvaluated` is needed here?

2016-12-20 16:04 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterTask.groovy
> +        project.gradle.projectsEvaluated {
Like, in the code.

2016-12-20 16:04 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterTask.groovy
> +        if (clusterConfiguration.numNodes > 1) {
Can you blow up before trying to execute if `numNodes` is 0? Like maybe in a `projectsEvaluated` block or something?

2016-12-20 16:04 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterTask.groovy
> +        if (clusterConfiguration.numNodes > 1) {
I don't think it is ok to have 0 nodes, right?

2016-12-20 16:04 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterTask.groovy
> +        return finalizedTaskNames.stream().toArray();
Would it be ok to return this list here?

2016-12-20 16:04 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClustersTask.groovy
> +    public String[] getFinalizedTasks() {
Same here, maybe list is ok?

2016-12-20 16:04 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterTask.groovy
> +                finalizedTaskNames.add("${name}#node${i}.stop")
Maybe always depend on the stop task rather than the stop task for each node?

2016-12-20 16:04 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/MultiClusterTestPlugin.groovy
> +        integTest.cluster.distribution = 'zip' // rest tests should run with the real zip
This should come for free from `RestTestPlugin`.

2016-12-20 16:04 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterTask.groovy
> +class ClusterTask extends DefaultTask {
Maybe `ExtraClusterTask`?

2016-12-20 16:04 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClustersTask.groovy
> +class ClustersTask extends DefaultTask {
Maybe `ExtraClustersTask`?

2016-12-20 16:04 UTC, nik9000 commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/MultiClusterTestPlugin.groovy
> +public class MultiClusterTestPlugin implements Plugin<Project> {
Maybe `ExtraClustersTestPlugin`?

2016-12-21 21:02 UTC, nik9000 approved these changes

2017-06-09 06:50 UTC, rjernst commented
The setup for integ test clusters has changed a bit (now we have the cluster and runner). I'm going to close this because I don't think @areek is interested in bring the PR to completion, and I also would want a slight change (to have there just be a `clusters` DSL which can be used to define clusters, which would also be how RestIntegTestPlugin sets up its cluster).

2017-06-09 06:50 UTC, closed without merging