Speed up filter and prefix settings operations
elastic/elasticsearch pull request #22249
Opened 2016-12-17 22:31 UTC by s1monw

Today if a settings object has many keys ie. if somebody specifies
a gazillion synonyms in-line (arrays are keys ending with ordinals) operations like
`Settings#getByPrefix` have a linear runtime. This can cause index creations to be
very slow producing lots of garbage at the same time. Yet, `Settings#getByPrefix` is called
quite frequently by group settings etc. which can cause heavy load on the system.

While it's not recommended to have synonym lists with 25k entries in-line these use-cases should
not have such a large impact on the cluster / node. This change introduces a view-like map
that filters based on the prefixes referencing the actual source map instead of copying all values
over and over again. A benchmark that adds a single key with 25k random synonyms between 2 and 5 chars
takes 16 seconds to get the synonym prefix 200 times while the filtered view takes 4 ms for the 200 iterations.

This relates to https://discuss.elastic.co/t/200-cpu-elasticsearch-5-index-creation-very-slow-with-a-huge-synonyms-list/69052

2016-12-18 12:33 UTC, jpountz requested changes
+1 to this change, but I left some comments about the impl

2016-12-18 12:33 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/settings/Settings.java
> +    private static final class FilteredMap extends AbstractMap<String, String> { // pkg private for testing
it is not pkg private

2016-12-18 12:33 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/settings/Settings.java
> +        private int size = -1; // we cache that size since we have to iterate the entire set
maybe also add a comment that it is safe to do so since the underlying map is immutable? (I think it is based on other comments?)

2016-12-18 12:33 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/settings/Settings.java
> +                        public Entry<String, String> next() {
I don't think we can assume here that hasNext was called first. Also, it should throw a NoSuchElementException if there are no more entries as per the iterator.next API contract?

2016-12-18 12:33 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/settings/Settings.java
> +                            return false;
It looks like calling hasNext twice in a row without calling next will advance the underlying iterator, meaning we could miss entries?

2016-12-18 12:33 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/settings/Settings.java
> +            String theKey = prefix == null ? key.toString() : prefix + key;
I think we should return `null` if the key is not an instance of `String` rather than converting it

2016-12-18 12:33 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/settings/Settings.java
> +            String theKey = prefix == null ? key.toString() : prefix + key;
same here

2016-12-18 12:33 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/settings/Settings.java
> +                    return size;
maybe let's just do `return FilteredMap.this.size();`?

2016-12-19 08:00 UTC, s1monw commented
@jpountz thanks for the review I pushed changes

2016-12-19 08:40 UTC, jpountz approved these changes
LGTM, only left minor comments.

2016-12-19 08:40 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/settings/Settings.java
> +        return new Settings(new FilteredMap(this.settings, (k) -> k.startsWith(prefix) && k.length() >= prefix.length(), prefix));
I think `k.length() >= prefix.length()` is always true when `k.startsWith(prefix)`?

2016-12-19 09:48 UTC, merged