Replace Socket and ServerSocket usages in tests with mocksocket versions
elastic/elasticsearch pull request #22287
Opened 2016-12-20 21:43 UTC by tbrooks8

This is related to #22116. In order to remove SocketPermissions from core we need to isolate some code that can be given SocketPermissions. The mocksocket jar includes wrapped versions of Socket and SocketServer. This is one step towards migrating permissions out of core.

2016-12-20 21:44 UTC, tbrooks8 commented
This is currently blocked from being merged on a release of the [mocksocket](https://github.com/elastic/mocksocket) project.

I should get to today or tomorrow.

2016-12-20 21:52 UTC, s1monw approved these changes
this PR LGTM provided MockSocket is available publicially

2016-12-20 22:06 UTC, jasontedor requested changes
I left one comment.

2016-12-20 22:06 UTC, jasontedor commented on modules/transport-netty4/src/test/java/org/elasticsearch/transport/netty4/Netty4SizeHeaderFrameDecoderTests.java
> +import org.elasticsearch.MockSocket;
My only comment is whether or not this should be in another package like `org.elasticsearch.mocksocket`? In general we should avoid split packages, and in a JDK 9 world, split packages are a thing that we are definitely not going to want to do. What do you think @s1monw?

2016-12-21 12:15 UTC, jasontedor commented on modules/transport-netty4/src/test/java/org/elasticsearch/transport/netty4/Netty4SizeHeaderFrameDecoderTests.java
> +import org.elasticsearch.MockSocket;
Split packages are packages that live in two jars. Yes, it needs to be fixed in mocksocket but this seemed a good place to raise the conversation.

2016-12-28 04:08 UTC, tbrooks8 commented
I made a few changes to this PR:

1. I placed the classes in a mocksocket package to attempt to address @jasontedor's concern.
2. I added wrappers for HttpServer and HttpsServer. This addresses the problem where those classes do not wrap `accept()` in `doPrivilege()`.

The mocksocket project is in MavenCentral. So once this passes an updated review, it should be good to merge in.

2017-01-02 17:22 UTC, tbrooks8 commented
I updated this PR with a new version of mocksocket that adds a [method](https://github.com/elastic/mocksocket/blob/master/src/main/java/org/elasticsearch/mocksocket/MockServerSocket.java#L77) needed for "connect" permissions.

And I rebased it on current master.

2017-01-03 09:25 UTC, s1monw commented
LGTM

2017-01-04 15:21 UTC, jasontedor approved these changes
LGTM.

2017-01-04 20:38 UTC, merged