Adds abstract test classes for serialisation
elastic/elasticsearch pull request #22281
Opened 2016-12-20 11:53 UTC by colings86

This adds test classes that can be used to test the wire serialisation and (optionally) the XContent serialisation of objects that implement Streamable/Writeable and ToXContent.

These test classes will enable classes such as InternalAggregation (or at least its implementations) to be tested in a consistent way when is comes to testing serialisation.

2016-12-20 12:06 UTC, s1monw requested changes
I really wonder if we can have at least one user of those tests?

2016-12-20 12:06 UTC, s1monw commented on test/framework/src/main/java/org/elasticsearch/test/AbstractStreamableTestCase.java
> + * ELASTICSEARCH CONFIDENTIAL
wrong header

2016-12-20 12:06 UTC, s1monw commented on test/framework/src/main/java/org/elasticsearch/test/AbstractStreamableTestCase.java
> +    protected static final int NUMBER_OF_TESTQUERIES = 20;
why don't you make it random ie instead of this constant use `randomIntBetween(1, 20)`

2016-12-20 12:06 UTC, s1monw commented on test/framework/src/main/java/org/elasticsearch/test/AbstractStreamableTestCase.java
> +                    new NamedWriteableRegistry(Collections.emptyList()))) {
will this work for all serialization classes? I mean queries need to be registered etc. I think we have to add all the ones we need for the subclass. So maybe add a factory method we can override?

2016-12-20 12:06 UTC, s1monw commented on test/framework/src/main/java/org/elasticsearch/test/AbstractStreamableXContentTestCase.java
> + * ELASTICSEARCH CONFIDENTIAL
you should run `gradle precommit`

2016-12-20 12:06 UTC, s1monw commented on test/framework/src/main/java/org/elasticsearch/test/AbstractWireSerializingTestCase.java
> +                    new NamedWriteableRegistry(Collections.emptyList()))) {
same comment as above

2016-12-20 14:09 UTC, jpountz reviewed
Agreed with Simon it would help to have one user of this class. Also some protected abstract methods would benefit from having javadocs.

2016-12-20 14:09 UTC, jpountz commented on test/framework/src/main/java/org/elasticsearch/test/AbstractStreamableTestCase.java
> +            assertTrue("query is not equal to self", secondInstance.equals(secondInstance));
maybe use assertEquals instead to have better error messages

2016-12-20 14:09 UTC, jpountz commented on test/framework/src/main/java/org/elasticsearch/test/AbstractStreamableXContentTestCase.java
> +     * {@link #testFromXContent()} test case
can the docs give an example when it is useful to do so?

2016-12-20 15:42 UTC, colings86 commented
@s1monw @jpountz I pushed commits addressing your comments. I have implemented InternalMinTests which uses `AbstractWireSerializingTestCase`. I plan in a follow up PR to convert `AbstractQueryTestCase` and `BaseAggregationTestCase` to extend `AbstractSerializingTestCase`. Not sure if it's worth keeping the `Streamable` versions of the test cases since we want to move everything to use `Writeable` anyway?

2016-12-20 15:49 UTC, colings86 commented
Also worth noting that because the test cases rely on `hashCode` and `equals` being implemented on the test class I had to add implementations to `InternalAggregation` and `InternalNumericMetricAggregation` which both declare methods that their subcleasses need to implement. In order to keep this PR mamageable and not require that I implemented `hashCode` and `equals` for all `InternalAggregation`s subclasses I added a default implementation of those declared methods which use object identity, as well as adding a `norelease` comment to them stating that they should be made abstract when all the `InternalAggregation` subclasses implement the methods

2016-12-20 17:31 UTC, jpountz reviewed
I left a comment about the way equals/hashcode are implemented, otherwise LGTM.

2016-12-20 17:31 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/aggregations/InternalAggregation.java
> +    protected boolean doEquals(Object obj) {
Can you add javadocs?

2016-12-20 17:31 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalNumericMetricsAggregation.java
> +    }
I don't like having both doEquals and innerEquals. Maybe just override equals to also include the format and still expect sub classes to implement doEquals? (Same for the hashcode)

2016-12-21 13:19 UTC, colings86 commented
@jpountz I pushed a new commit addressing your latest comments. Could you review again?

2016-12-21 14:11 UTC, jpountz approved these changes
LGTM

2016-12-22 10:49 UTC, merged