Add ingest-attachment-with-arrays section to ingest attachments doc
elastic/elasticsearch pull request #22310
Opened 2016-12-21 16:28 UTC by gameldar

Added a new section detailing how to use the attachment processor
within an array.

This reverts commit #22296 and instead links to the foreach processor.

Note this invalidates the previous pull request (#22295) which was made against the wrong branch.

2016-12-21 16:30 UTC, gameldar commented
Note this was for Issue #22294

2016-12-21 16:45 UTC, dadoonet requested changes
Left a small comment but we are getting close now! :)

2016-12-21 16:45 UTC, dadoonet commented on docs/reference/ingest/ingest-node.asciidoc
> +Another advanced example can be found in {plugins}/using-ingest-attachment.html[attachment processor documentation].
Can you change the link to `{plugins}/ingest-attachment-with-arrays.html` so people are redirected to right page automatically?

2016-12-22 12:53 UTC, dadoonet approved these changes

2016-12-22 14:16 UTC, dadoonet commented
Ok so I tried your branch and ran `gradle check` in docs dir and it failed.
Well, I forgot about this. You need to add `// NOTCONSOLE` after each snippet or `// CONSOLE` if you want it to be executed as a test.

The later is better as we are sure that any time we update the project, the doc stills accurate.

You have a great example in `analysis-icu.asciidoc` if you wish.

Thanks!

2016-12-22 14:17 UTC, dadoonet requested changes
Ok so I tried your branch and ran `gradle check` in docs dir and it failed.
Well, I forgot about this. You need to add `// NOTCONSOLE` after each snippet or `// CONSOLE` if you want it to be executed as a test.

The later is better as we are sure that any time we update the project, the doc stills accurate.

You have a great example in `analysis-icu.asciidoc` if you wish.

Thanks!

2016-12-23 09:33 UTC, dadoonet approved these changes
I tested it locally and it's great!
Thanks a lot! 
Going to merge it now.

2016-12-23 09:33 UTC, merged

2016-12-23 09:38 UTC, dadoonet commented
Backported:

* 5.x: da6fb27
* 5.1: e1c6cf2