Close and flush refresh listeners on shard close
elastic/elasticsearch pull request #22342
Opened 2016-12-23 20:59 UTC by nik9000

Right now closing a shard looks like it strands refresh listeners,
causing tests like
`delete/50_refresh/refresh=wait_for waits until changes are visible in search`
to fail. Here is a build that fails:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+multi_cluster_search+multijob-darwin-compatibility/4/console

This attempts to fix the problem by implements `Closeable` on
`RefreshListeners` and rejecting listeners when closed. More importantly
the act of closing the instance flushes all pending listeners
so we shouldn't have any stranded listeners on close.

Because it was needed for testing, this also adds the number of
pending listeners to the `CommonStats` object and all API to which
that flows: `_cat/nodes`, `_cat/indices`, `_cat/shards`, and
`_nodes/stats`.

2016-12-23 21:00 UTC, nik9000 commented
I labeled this `enhancement` because, while the goal is to fix a bug, I added an enhancement to make testing sane so this is limited to being merged into minor versions.

2016-12-23 21:00 UTC, nik9000 commented
@jasontedor, can you have a look?

2017-01-06 16:32 UTC, jasontedor requested changes
I see only one thing that bothers me, the rest looks great.

2017-01-06 16:32 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/shard/RefreshListeners.java
> +            } else if (listeners == Collections.<Tuple<Translog.Location, Consumer<Boolean>>>emptyList()) {
I don't like these reference checks to the empty list.

2017-01-06 16:32 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/shard/RefreshListeners.java
> +        return listeners != null && listeners != Collections.<Tuple<Translog.Location, Consumer<Boolean>>>emptyList();
Here's another reference check.

2017-01-06 16:32 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/shard/RefreshListeners.java
> +            // Setting refreshListeners to emptyList() "closes" it
I'd rather we used a boolean flag to indicate closed instead of a special reference.

2017-01-06 18:11 UTC, nik9000 commented
@jasontedor, I pushed a commit swapping emptyList for a volatile boolean.

2017-01-06 18:12 UTC, jasontedor approved these changes
LGTM.

2017-01-07 01:07 UTC, nik9000 commented
Thanks for reviewing @jasontedor!

5.2: 6df160d45f0a4fdd2a88c47eda4675a239a28e67
5.x: 000318e7e287536971a736e913f689b812d13035
master: 12923ef8961f40abded8341f00881a163f7c68a9

2017-01-07 01:07 UTC, merged