Disable the Netty recycler and pooled allocator
elastic/elasticsearch pull request #22452
Opened 2017-01-05 17:55 UTC by jasontedor

Netty plays a lot of games with recycling byte buffers in thread local
caches, and using a pooled byte buffer allocator to reduce pressure on
the garbage collector.

The recycler in particular appears to be fraught with peril. It appears
that there are circumstances where the recycler does not recycle quickly
enough and can exceed its capacity leading to heap exhaustion and out of
memory errors. If you spend a few minutes reading the history of the
recycler on the Netty GitHub issues, it appears it has been nothing but
a source of trouble, and the project itself has an open issue that
proposes disabling by default and possibly even removing the recycler.

The pooled byte buffer allocator has problems itself. It sizes the pool
based on the number of runtime processors and can indeed grab a very
large percentage of the heap (in some cases 50% or more). Additionally,
the Netty project continues to struggle with leaks here.

We are seeing users struggle with issues in 5.x that I think are largely
driven by some of the problems here with Netty.

This change proposes to disable the recycler, and to disable the pooled
byte buffer allocator. I think that disabling these features will return
some of the stablity that these features appear to be losing us.

I have done performance testing on my workstation with disabling these
and I do not see a difference in performance. I propose that we make
this change in master and let some nightly benchmarks run to confirm
that there is not a difference in performance. If we are comfortable
with the performance changes, I propose backporting this to all active
branches.

Relates netty/netty#5904, #22406, #22360, #22189

2017-01-05 17:57 UTC, jaymode approved these changes
LGTM

2017-01-05 18:26 UTC, jpountz approved these changes
+1

2017-01-05 21:50 UTC, Tim-Brooks approved these changes
LGTM

2017-01-06 11:32 UTC, s1monw requested changes
LGTM - man how much we gotta fiddle with this software after all...

2017-01-06 11:32 UTC, s1monw approved these changes
wrong checkbox LGTM again

2017-01-06 11:37 UTC, merged

2017-01-10 19:27 UTC, jasontedor commented
Our nightly benchmarks show a small increase in GC times in a few (but not all) of the tracks; I'm going back out the pooled to unpooled change to isolate if this is the cause and have only backported the Netty recycler change for now (as this is the most critical change for addressing the performance issues).

2017-01-11 13:32 UTC, ywelsch commented
@jasontedor can you update the version labels on this PR?

2017-01-11 14:00 UTC, jasontedor commented
Thank you @ywelsch, sorry for missing that. I've updated the labels.

2017-01-11 14:02 UTC, jasontedor commented
GC times on the few benchmarks where it increased went back down after pulling the disabling pooling change.

2017-01-12 13:06 UTC, jasontedor commented
I've updated the title and body to reflect that the disabling the pooled allocator has been reverted.

2017-01-18 07:44 UTC, duramen commented
ES5.1.1，I've added follow to config/jvm.options,and restart es.But it's still have the question.

> Dio.netty.recycler.maxCapacityPerThread=0
 Dio.netty.allocator.type=unpooled

2017-02-01 21:58 UTC, jasontedor commented
@dude0404 I glanced at your logs. I think that your issue has nothing to do with what was occurring here, I think that your heap is full. You should inspect a heap dump and see why your heap appears to be full. If you have additional questions, I suggest that you open a topic on the [forum](https://discuss.elastic.co); Elastic reserves GitHub for verified bug reports and feature requests, not general discussion.

2017-02-04 14:39 UTC, mozinrat commented
Even I am facing the same issue, with Dio.netty.recycler.maxCapacityPerThread=0
Dio.netty.allocator.type=unpooled on 5.1.1 
log attached
[es.txt](https://github.com/elastic/elasticsearch/files/752337/es.txt)

2017-02-06 18:32 UTC, jasontedor commented
It is not the case that disabling the recycler would eliminate all causes of out of memory errors in the network layer, only that it eliminated those that arose because of issues in Netty, not because, say, too much data is being pumped through Elasticsearch faster than it can be consumed. Thus, if you're still seeing out of memory issues after disabling the recycler, it means that you need to inspect a heap dump and see where your heap is being consumed.

2018-05-02 11:36 UTC, forestfantacy commented
this problem happened in es5.x & netty4,
it can solving by downgrading to netty3,
but es6.x is no longer support netty3, and netty4 don't work still, so how can i do