handler negative size/from paramter in search request
elastic/elasticsearch pull request #22579
Opened 2017-01-12 09:17 UTC by makeyang

throw exception when user set negative size or negative from paramter in search request, which is describe in : https://github.com/elastic/elasticsearch/issues/22530

2017-01-12 23:33 UTC, gaganis commented
Hello @makeyang, 

Just a quick note on your PR. I see that that with this code you make it illegal to request size of "-1".
There might be clients that knowingly or unknowingly are already using this and their code would break if this behaviour is changed. I would have kept it to return the default size of 10 which is clearly documented here [](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/search-request-from-size.html)

What I mean by unknowingly is that many people are using -1 as the uninitialized value for an int variable so it is possible in some cases this could leak through to the API. 

Giorgos

2017-01-13 02:46 UTC, makeyang commented
@gaganis actually I tought about it much when I try to fix this. and here is my decision: u just can't let -1 as the default value while throw exception for -2. this is much much ambiguous for more users than bother those who already known that -1 is default value.
we can mark breaking change if it is necessary. but the bottom line is: we really should make the right things rather than make things right.

2017-01-13 02:53 UTC, jasontedor commented
An idiom within Elasticsearch is that -1 means disabled or default or unset (depending on the context). This needs to remain as-is for this API too.

2017-01-13 03:16 UTC, makeyang commented
@jasontedor & @gaganis I just checked ES reference and definitive gudie, there is nowhere mentioned this so-called idiom. it's just the code convention.
I really don't think that is the right thing. 
but if u guys insist on, I'll modified code.
let me know u guys thouths.

2017-01-13 03:21 UTC, jasontedor requested changes
I left some comments.

2017-01-13 03:21 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java
> +    private Integer from = null;
I think that this change that introduces boxing should be reverted. This means that we need a value to represent unset, and -1 is the idiom within Elasticsearch for that.

2017-01-13 03:21 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/rest/RestRequest.java
> +    public Integer paramAsInteger(String key, Integer defaultValue) {
This method isn't needed since I think the boxing change should be reverted.

2017-01-13 03:21 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java
> +        if (request.hasParam("from")) {
I would be okay with rejecting anything negative here, on the REST layer. We still need a way to represent unset internally. Using `null` introduces boxing, we should avoid that. Let's continue to use -1, that's the idiom.

However, I would like to solicit feedback from others before you proceed with rejecting anything negative including -1 here. What do you think @javanna?

2017-01-13 09:49 UTC, clintongormley commented on core/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java
> +        if (request.hasParam("from")) {
Accepting -1 over the rest layer has never been documented, and it surprised me that it works. I'd be ok with rejecting it

2017-01-13 11:05 UTC, javanna commented on core/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java
> +        if (request.hasParam("from")) {
given our direction (REST client vs transport client) I think we are fine rejecting `-1` on the REST layer. But how about keeping the `int`, using `-1` as default, and rejecting negative values in the setters? That's how we changed some of the request validation as part of the search refactoring too.

2017-01-13 11:11 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java
> +        if (request.hasParam("from")) {
@javanna Yeah, that's exactly what I have in mind.

2017-01-13 11:11 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java
> +        if (request.hasParam("from")) {
Thank you for commenting @clintongormley and @javanna.

2017-01-13 15:39 UTC, gaganis commented
This has become a pretty interesting discussion.

It seems the discussion has revolved around two distinct points:

#### Data type of the Internal implementation 

Whether to use int with a default value of -1 for the endpoint implementing classes. On my original comment I was not thinking about that but after reading the rest of the comments I would also agree to keep the int data type and the -1 as the default value internally.

#### What to do with the undocumented behavior or the REST endpoint accepting -1

This was the focus of my initial comment. This behavior despite being undocumented was preexisting and the change could potentially break existing clients. The consensus seems to be that this is not correct and should be fixed in line with @makeyang's reasoning. 

I have done some more research and I have found the very visible and extensive section in the online documentation for changes that have the potential to break existing code and behavior. BTW That is pretty cool! 

#### In summary 

Taking into account all the comments and the availability of the breaking section in the docs, @makeyang my thoughts on this is that we should keep the int and -1 default value internally and accept rejecting -1 during the validation per your implementation.

Thanks @makeyang for the PR and @jasontedor, @clintongormley and @javanna for the comments!

They were all very informative!

2017-01-16 09:03 UTC, makeyang commented
@jasontedor can you help to review this? I have modified code according to your comments.

2017-01-16 09:07 UTC, makeyang commented
@jasontedor  @gaganis 
actually I rejecting negative values in the setters of SearchSourceBuilder.

2017-01-19 00:01 UTC, bumbu requested changes
Updates on errors wording

2017-01-19 00:01 UTC, bumbu commented on core/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java
> +            throw new IllegalArgumentException("from must be no negative but was [" + from + "]");
A better wording for the error is: `[from] can't be negative`
Changing that will require updating tests

2017-01-19 00:01 UTC, bumbu commented on core/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java
> +            throw new IllegalArgumentException("size must be no negative but was [" + size + "]");
A better wording for the error is: `[size] can't be negative`
Changing that will require updating tests

2017-03-15 20:45 UTC, olcbean commented on core/src/test/java/org/elasticsearch/search/builder/SearchSourceBuilderTests.java
> +    public void testInvalidFormAndSize() throws IOException {
A tiny typo in the test name : should be `From` instead of `Form`

2017-03-21 00:12 UTC, jasontedor commented
@makeyang Are you interested in finishing this pull request?

2017-03-21 00:12 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-03-23 03:22 UTC, makeyang commented
@jasontedor  I'll update this later this month.

2017-04-26 10:05 UTC, colings86 commented
No further feedback, closing. Please reopen if you have progress on this

2017-04-26 10:05 UTC, closed without merging