Allow comma delimited array settings to have a space after each entry
elastic/elasticsearch pull request #22591
Opened 2017-01-12 15:23 UTC by abeyad

Previously, certain settings that could take multiple comma delimited
values would pick up incorrect values for all entries but the first if
each comma separated value was followed by a whitespace character.  For
example, the multi-value "A,B,C" would be correctly parsed as
["A", "B", "C"] but the multi-value "A, B, C" would be incorrectly parsed
as ["A", " B", " C"].

This commit allows a comma separated list to have whitespace characters
after each entry.  The specific settings that were affected by this are:

  cluster.routing.allocation.awareness.attributes
  index.routing.allocation.require.*
  index.routing.allocation.include.*
  index.routing.allocation.exclude.*
  cluster.routing.allocation.require.*
  cluster.routing.allocation.include.*
  cluster.routing.allocation.exclude.*
  http.cors.allow-methods
  http.cors.allow-headers

For the allocation filtering related settings, this commit also provides
validation of each specified entry if the filtering is done by _ip,
_host_ip, or _publish_ip, to ensure that each entry is a valid IP
address.

Closes #22297

2017-01-12 15:28 UTC, s1monw requested changes
I left some questions Looks good though

2017-01-12 15:28 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodeFilters.java
> +    public static final Consumer<Settings> IP_VALIDATOR = (settings) -> {
can you put some javadocs on this

2017-01-12 15:28 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/metadata/IndexMetaData.java
> +            DiscoveryNodeFilters.IP_VALIDATOR.accept(requireGroupSettings);
why don't you use this as a validator on the actual setting?

2017-01-12 15:28 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/metadata/IndexMetaData.java
> +            DiscoveryNodeFilters.IP_VALIDATOR.accept(includeGroupSettings);
see above

2017-01-12 15:28 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/metadata/IndexMetaData.java
> +            DiscoveryNodeFilters.IP_VALIDATOR.accept(excludeGroupSettings);
see above

2017-01-12 15:28 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java
> +    private volatile String[] awarenessAttributes;
👍

2017-01-12 15:28 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDecider.java
> +        clusterSettings.addSettingsUpdateConsumer(CLUSTER_ROUTING_REQUIRE_GROUP_SETTING, this::setClusterRequireFilters, IP_VALIDATOR);
hmm use the validator on the actual setting instead?

2017-01-12 16:37 UTC, abeyad commented on core/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodeFilters.java
> +    public static final Consumer<Settings> IP_VALIDATOR = (settings) -> {
done

2017-01-12 16:38 UTC, abeyad commented on core/src/main/java/org/elasticsearch/cluster/metadata/IndexMetaData.java
> +            DiscoveryNodeFilters.IP_VALIDATOR.accept(requireGroupSettings);
thanks for alerting me to this, i didn't realize a validator could be set on group settings until you mentioned it.  I fixed this and all other occurrences below

2017-01-12 16:38 UTC, abeyad commented
@s1monw I pushed 1ca2d4771b8d479640bac53ab718952508cc388e to address your feedback

2017-01-13 10:09 UTC, s1monw approved these changes
LGTM

2017-01-13 14:57 UTC, abeyad commented
retest this please

2017-01-16 23:21 UTC, abeyad commented
@s1monw I pushed 953f016a649d87d7fde178e0eeb7474d214566d4 which also prohibits node attributes to have leading or trailing whitespace, if you can take a quick look
/cc @jasontedor

2017-01-16 23:32 UTC, jasontedor approved these changes
LGTM.

2017-01-17 13:18 UTC, s1monw approved these changes
LGTM 2

2017-01-17 14:51 UTC, merged

2017-01-17 14:56 UTC, abeyad commented
5.x commit: c763b1e822fe71968bffbe3d003062d1a83784c8

2017-01-17 14:56 UTC, abeyad commented
thanks @s1monw @jasontedor