Remove taskManager.registerChildTask
elastic/elasticsearch pull request #22590
Opened 2017-01-12 14:51 UTC by imotov

Instead of forcing each task to register all nodes where its children are running, this commit runs cancellation on all nodes. The task cancellation operation doesn't run too frequently, so this optimization doesn't seem to be worth additional complexity of the interface.

2017-01-12 15:24 UTC, nik9000 reviewed
I left a few small things. It looks like it works though.

I wonder about cancel having a "storm" effect. Imagine canceling something that has many child tasks like `_bulk`. Each one of those child tasks will also broadcast a cancel. That seems like a lot of traffic even if this is rare. Not much in MB but plenty in round trips. Is it possible for a task to mark itself as potentially having children so we can avoid some of this?

2017-01-12 15:24 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/tasks/TaskManager.java
>       * Returns a set of nodes with child tasks where this task should be cancelled if cancellation was successful, null otherwise.
Comment out of date.

2017-01-12 15:24 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/cancel/TransportCancelTasksAction.java
> +            // The task has some child tasks, we need to wait for until ban is set on all nodes
s/The tasks has/In case the task has/

2017-01-12 15:24 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/cancel/TransportCancelTasksAction.java
> +        Set<String> nodes = new HashSet<>();
It feels weird to turn the nodes list in the cluster state in set of strings and then turn it back into a node on `sendSetBanRequest`.

2017-01-12 15:24 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/cancel/TransportCancelTasksAction.java
> +        private final Set<String> nodes;
Maybe list pass the count instead?

2017-01-12 19:01 UTC, imotov commented
@nik9000 great suggestions! I pushed fixes. Could you take another look?

2017-01-17 15:36 UTC, nik9000 requested changes
I left a few minor things, on of which I think is actually pretty important.

2017-01-17 15:36 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/cancel/TransportCancelTasksAction.java
> +            // Check if node still in the cluster
I think this comment is out of date now. I think it is more of a "if not isn't in the cluster this will log a warning but that is ok".

2017-01-17 15:36 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/tasks/CancellableTask.java
> +    public CancellableTask(long id, String type, String action, String description, TaskId parentTaskId,
After seeing the mess that these kinds of "constants your children set" have caused in aggregations I'd prefer to have `shouldCancelChildrenOnCancellation` be abstract.

2017-01-17 15:36 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/tasks/TaskManager.java
> +     * Returns true if cancellation was successful, null otherwise.
It is probably also worth mentioning when the runnable is called.

2017-01-17 17:50 UTC, imotov commented
@nik9000 how about this?

2017-01-17 18:23 UTC, nik9000 approved these changes

2017-01-18 01:21 UTC, merged