NPE when no setting name passed to elasticsearch-keystore
elastic/elasticsearch pull request #22609
Opened 2017-01-13 11:20 UTC by dadoonet

```sh
$ bin/elasticsearch-keystore create
Created elasticsearch keystore in /Users/dpilato/Documents/Elasticsearch/apps/elasticsearch/elasticsearch-6.0.0-alpha1/config
$ bin/elasticsearch-keystore add
Enter value for null: xyz
Exception in thread "main" java.lang.NullPointerException: invalid null input
	at java.security.KeyStore.setEntry(KeyStore.java:1552)
	at org.elasticsearch.common.settings.KeyStoreWrapper.setString(KeyStoreWrapper.java:264)
	at org.elasticsearch.common.settings.AddStringKeyStoreCommand.execute(AddStringKeyStoreCommand.java:83)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:39)
```

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

2017-01-13 11:43 UTC, jasontedor requested changes
Since this is a command-line usage error, I think it should be reported as such.

2017-01-13 11:43 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/common/settings/AddStringKeyStoreCommand.java
> +            throw new UserException(ExitCodes.DATA_ERROR, "the setting name can not be null.");
This should be a `USAGE` error, not a `DATA_ERROR` (and the period dropped from the exception message).

2017-01-13 11:53 UTC, jasontedor approved these changes
LGTM.

2017-01-13 12:00 UTC, merged

2017-01-13 12:01 UTC, dadoonet commented
Thanks @jasontedor !

2017-02-07 17:38 UTC, rjernst commented
This should have been backported. I've inadvertently backported it with #22894 and added the 5.3 label here.