gradle run --debug-jvm is explained twice
elastic/elasticsearch pull request #22612
Opened 2017-01-13 13:43 UTC by dadoonet

We are already explaining how to debug remotely in `Debugging from an IDE` section.
We can remove one.

2017-01-13 13:57 UTC, dadoonet commented
I also added some information on how to remotely debug an elasticsearch running outside the context of Gradle.

2017-01-13 19:41 UTC, jasontedor requested changes
I left some feedback.

2017-01-13 19:41 UTC, jasontedor commented on TESTING.asciidoc
> +If you want to run elasticsearch and be able to remotely attach the process
Nit: `elasticsearch` -> `Elasticsearch`

2017-01-13 19:41 UTC, jasontedor commented on TESTING.asciidoc
> +`config/jvm.options`:
Also, this can be done from the command line using `ES_JAVA_OPTS` (I do this all the time).

2017-01-13 19:41 UTC, jasontedor commented on TESTING.asciidoc
> +-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=n
This should be `suspend=y` so that you can attach the debugger before Elasticsearch starts running.

2017-01-13 19:41 UTC, jasontedor commented on TESTING.asciidoc
> +Then start elasticsearch with `bin/elasticsearch` as usual.
Nit: `elasticsearch` -> `Elasticsearch`

2017-01-13 19:41 UTC, jasontedor commented on TESTING.asciidoc
> +If you are using IntelliJ, create a new Run/Debug configuration, choose `Remote`
Let's make this more generic and just say consult your IDE documentation for how to attach a debugger to a JVM process.

2017-01-16 13:16 UTC, jasontedor requested changes
LGTM.

2017-01-16 13:16 UTC, jasontedor approved these changes
LGTM, I clicked the wrong radio button the first time (sorry).

2017-01-16 13:19 UTC, merged

2017-01-16 13:19 UTC, dadoonet commented
:) No worries!