Add a deprecation notice to shadow replicas
elastic/elasticsearch pull request #22647
Opened 2017-01-16 22:47 UTC by bleskes

Relates to #22024

On top of documentation, the PR adds deprecation loggers and deals with the resulting warning headers.

The yaml test is set exclude versions up to 6.0. This is need to make sure bwc tests pass until this is backported to 5.2.0 . Once that's done, I will change the yaml test version limits

2017-01-16 23:48 UTC, dakrone approved these changes
LGTM

2017-01-17 11:01 UTC, jasontedor requested changes
I left some nits.

2017-01-17 11:01 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/cluster/metadata/IndexMetaData.java
> +        // don't use the settings directly, not to trigger manny deprecation logging
Nits: `settings` -> `setting` and `not to trigger manny` -> `to not trigger verbose` (it doesn't have to be exactly this, but at least fix `manny`)

2017-01-17 11:01 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/cluster/metadata/IndexMetaData.java
> +        // don't use the settings directly, not to trigger manny deprecation logging
Nits: `settings` -> `setting` and `not to trigger manny` -> `to not trigger verbose` (it doesn't have to be exactly this, but at least fix `manny`)

2017-01-17 11:01 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> +        // don't use the settings directly, not to trigger manny deprecation logging
Nits: `settings` -> `setting` and `not to trigger manny` -> `to not trigger verbose` (it doesn't have to be exactly this, but at least fix `manny`)

2017-01-17 11:01 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java
> +        return false;
Would you please add an assert guarding against this staying around after shadow replicas are removed?

2017-01-17 11:01 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
> +        return false;
Would you please add an assert guarding against this staying around after shadow replicas are removed?

2017-01-17 11:01 UTC, jasontedor commented on docs/reference/indices/shadow-replicas.asciidoc
> +deprecated[5.2.0, Shadow replicas don't see much usage and we are planning to remove them]
"Planning" or "going"?

2017-01-17 11:01 UTC, jasontedor commented on docs/reference/migration/migrate_6_0/indices.asciidoc
> +<<indices-shadow-replicas,Shadow Replicas>> don't see much usage and we are planning to remove them.
"Planning" or "going"?

2017-01-17 11:02 UTC, jasontedor commented
Thanks @bleskes. Will you open a follow-up issue for `path.shared_data`?

2017-01-17 17:03 UTC, bleskes commented on core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java
> +        return false;
I did :) that's why the java docs links to the setting in question

2017-01-17 17:03 UTC, bleskes commented on core/src/test/java/org/elasticsearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
> +        return false;
same as above

2017-01-17 17:04 UTC, bleskes commented on docs/reference/indices/shadow-replicas.asciidoc
> +deprecated[5.2.0, Shadow replicas don't see much usage and we are planning to remove them]
I don't know. Chose for a softer language here.

2017-01-17 17:07 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java
> +        return false;
Okay, I'm fine with that.

2017-01-17 17:07 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
> +        return false;
Yes, I'm also fine with it here.

2017-01-17 17:13 UTC, bleskes commented
@jasontedor I pushed another commit. Can you look?

2017-01-17 17:15 UTC, jasontedor approved these changes
LGTM.

2017-01-18 00:30 UTC, bleskes commented
retest this please

2017-01-18 07:17 UTC, bleskes commented
Retest this please

2017-01-18 08:37 UTC, bleskes commented
retest this please

2017-01-18 11:28 UTC, merged