Update recipes.asciidoc - Trying to clarify
elastic/elasticsearch pull request #22660
Opened 2017-01-17 17:22 UTC by elijahdjmarshall

Minor modifications for fluid reading.
Note:
...then it might have index statistics that are sufficiently different from the replica (which still have plenty of deleted documents) so that scores are different too...
I had to read over this several times to identify what was being compared.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

2017-04-18 02:08 UTC, nik9000 requested changes
3/4 of the changes are great. The other one is misleading.

2017-04-18 02:08 UTC, nik9000 commented on docs/reference/how-to/recipes.asciidoc
> +from the replica (which still have some documents as the sync has not completed
This is somewhere between misleading and wrong, I think. There isn't a process that syncs merges from primary to replica - the replica just does the merge as well.

2017-06-09 07:06 UTC, rjernst commented
@nik9000 What should be done about this PR?

2017-06-09 07:06 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-08-15 20:15 UTC, dakrone commented
Closing since there has been no feedback for quite a while, feel free to re-open if I have closed in error.

2017-08-15 20:15 UTC, closed without merging