Add used memory amount to CircuitBreakingException message (#22521)
elastic/elasticsearch pull request #22693
Opened 2017-01-19 15:45 UTC by bumbu

Closes #22521 

Tests don't check for the amount of used memory because that will tie-up the tests to the implementation. 
From what I saw there are no tests to check that the used memory is calculated correctly, but it may be just my lack of knowledge of the codebase. Also it is out of the scope of original ticket.

2017-01-19 16:34 UTC, dakrone commented
@bumbu thanks for this! This looks pretty good, could you add a unit test to `MemoryCircuitBreakerTests` with exact numbers so we can assert the message looks correct? (I understand you can't easily add it to the integration tests since the desired memory is not constant)

2017-01-20 13:43 UTC, bumbu commented
Hi @dakrone,

I added an assertion to `MemoryCircuitBreakerTests` to check for the numbers returned in the message. I didn't hard-code the number, instead I computed it right before the assertion. Didn't want to hard-code the number as how it is currently done gives more insight on what that number is. 

Also I tested only for the first part of the number value (aka testing only for `1024` from `[1024/1k]`) as I didn't want to add one more dependency for computing the byte size value. The assertion should cover the message pretty well as the same number as not formatted and formatted byte size value. But I can easily add that if it will bring more value. 

I squashed the commit.

2017-01-23 16:30 UTC, dakrone requested changes
It looks like there's a compilation error, @bumbu otherwise this looks good, can you fix the error and then I'll merge this?

2017-01-23 16:30 UTC, dakrone commented on core/src/test/java/org/elasticsearch/common/breaker/MemoryCircuitBreakerTests.java
> +            assertThat(cbe.getMessage().contains("would be [" + newUsed "/"), equalTo(true));
This is missing a `+` between `newUsed` and `"/"`, so it's not compiling currently

2017-01-28 19:53 UTC, bumbu commented on core/src/test/java/org/elasticsearch/common/breaker/MemoryCircuitBreakerTests.java
> +            assertThat(cbe.getMessage().contains("would be [" + newUsed "/"), equalTo(true));
My bad. I was sure that it's not possible to introduce bugs with such a small change... Lesson learned.

2017-01-28 19:55 UTC, bumbu commented
Hi @dakrone.
Sorry for the delay, I was on holidays. 
I fixed the bug, run tests, squashed commits and rebased from master. 
Please check.

2017-01-30 15:35 UTC, dakrone commented
@elasticmachine test this please

2017-01-30 18:05 UTC, merged

2017-01-30 18:05 UTC, dakrone commented
Thanks @bumbu, I've merged this!