Read ec2 discovery address from aws instance tags
elastic/elasticsearch pull request #22743
Opened 2017-01-23 12:36 UTC by dadoonet

This PR adds a new option for `host_type`: `tag:TAGNAME` where `TAGNAME` is the tag field you defined for your ec2 instance.

For example if you defined a tag `my-elasticsearch-host` in ec2 and set it to `myhostname1.mydomain.com`, then
setting `host_type: tag:my-elasticsearch-host` will tell Discovery Ec2 plugin to read the host name from the
`my-elasticsearch-host` tag. In this case, it will be resolved to `myhostname1.mydomain.com`.

Closes #22566.

2017-01-24 09:29 UTC, tlrx requested changes

2017-01-24 09:29 UTC, tlrx commented on docs/plugins/discovery-ec2.asciidoc
> +`TAGNAME` is the tag field you defined for your ec2 instance.
`where `TAGNAME` refers to a name of a tag configured for all EC2 instances.` maybe?

2017-01-24 09:29 UTC, tlrx commented on docs/plugins/discovery-ec2.asciidoc
> +`my-elasticsearch-host` tag. In this case, it will be resolved to `myhostname1.mydomain.com`.
Can we link to the AWS documentation about Tags?

2017-01-24 09:29 UTC, tlrx commented on plugins/discovery-ec2/src/main/java/org/elasticsearch/cloud/aws/AwsEc2Service.java
> +         * Can be one of private_ip, public_ip, private_dns, public_dns or meta:XXXX where
Doc refers to "meta" and not "tag"

2017-01-24 09:29 UTC, tlrx commented on plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java
> +        logger.info("started [{}] instances", nodes);
debug?

2017-01-24 09:29 UTC, tlrx commented on plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java
> +            assertThat(discoveryNode.getHostName(), isOneOf(addresses));
I think it should be:

TransportAddress address = discoveryNode.getAddress();
TransportAddress expected = poorMansDNS.get(discoveryNode.getHostName());
assertEquals(address, expected);

2017-01-24 10:00 UTC, dadoonet commented on docs/plugins/discovery-ec2.asciidoc
> +`TAGNAME` is the tag field you defined for your ec2 instance.
Good idea. Also adding 

> Instances which don't have this tag set will be ignored by the discovery process.

2017-01-24 10:00 UTC, dadoonet commented on docs/plugins/discovery-ec2.asciidoc
> +`my-elasticsearch-host` tag. In this case, it will be resolved to `myhostname1.mydomain.com`.
Good idea.

2017-01-24 10:01 UTC, dadoonet commented on plugins/discovery-ec2/src/main/java/org/elasticsearch/cloud/aws/AwsEc2Service.java
> +         * Can be one of private_ip, public_ip, private_dns, public_dns or meta:XXXX where
Nice catch. Was a leftover. Initially I used `meta` instead of `tag`.

2017-01-24 10:04 UTC, dadoonet commented on plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java
> +        logger.info("started [{}] instances", nodes);
I can. But it's a copy and paste from `testFilterByTags()` method. Also appears in `testReadHostFromTag()`. Should I change to debug everywhere?

2017-01-24 10:24 UTC, dadoonet commented
Thanks @tlrx!

I pushed a new commit based on your feedback. LMK

2017-01-24 12:30 UTC, tlrx requested changes
It's getting close. One of the comment you added makes me think that we should log a warning message if an instance doesn't have the expected tag

2017-01-24 12:30 UTC, tlrx commented on plugins/discovery-ec2/src/main/java/org/elasticsearch/cloud/aws/AwsEc2Service.java
> +         * have this tag set will be ignored by the discovery process. Defaults to private_ip.
Thinking about this again, I think we should add a warning message about them?

2017-01-24 13:32 UTC, dadoonet commented on plugins/discovery-ec2/src/main/java/org/elasticsearch/cloud/aws/AwsEc2Service.java
> +         * have this tag set will be ignored by the discovery process. Defaults to private_ip.
TBH I don't know. I put a debug message already because I think that can be intentional.

2017-01-26 09:54 UTC, tlrx commented on plugins/discovery-ec2/src/main/java/org/elasticsearch/cloud/aws/AwsEc2Service.java
> +         * have this tag set will be ignored by the discovery process. Defaults to private_ip.
Ok

2017-01-26 09:54 UTC, tlrx approved these changes

2017-01-26 16:20 UTC, dadoonet commented
@elasticmachine test this please

2017-01-26 16:21 UTC, dadoonet commented
Thanks @tlrx!

I needed to push a new change as an existing test was failing. And also to make checkstyle happy.
Could you review the last commit please?

2017-01-26 16:25 UTC, tlrx approved these changes
LGTM, I left a minor comment about using expectThrows instead of try-catch block in the test, would be nice to change this before merging.

2017-01-26 16:25 UTC, tlrx commented on plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java
> +            assertThat(e.getMessage(), containsString("does_not_exist is unknown for discovery.ec2.host_type"));
Can you use expectThrows instead?

2017-01-26 16:36 UTC, merged