Officially remove connect
elastic/elasticsearch pull request #22797
Opened 2017-01-26 04:24 UTC by tbrooks8

This permission is relegated to these modules/plugins:
- transport-netty4 module
- reindex module
- repository-url module
- discovery-azure-classic plugin
- discovery-ec2 plugin
- discovery-gce plugin
- repository-azure plugin
- repository-gcs plugin
- repository-hdfs plugin
- repository-s3 plugin

And for tests:
- mocksocket jar
- rest client
- httpcore-nio jar
- httpasyncclient jar

2017-01-26 04:30 UTC, tbrooks8 commented
A couple notes:

1. This depends on #22793
2. It's a little messy that I need to give permissions to rest client, httpcore-nio, and httpasyncclient in tests. But this is necessary for the rest integration tests. The `doPrivileged` block is at the rest client level. So the http libraries (which are called by rest) also need the permissions.
3. Due to the way tests permission are applied, some issues can be obscured. For ex: `reindex` needs `connect`. But even if I did not give it `connect`, the tests would still pass. This is because it depends on `transport-netty4` which has `connect`. And the way privileges are applied in tests, `reindex` dependencies get any permissions `transport-netty4` when the `transport-netty4` security policy is applied in `reindex` tests. I'm not sure if there is a clear way around this without changing the build significantly.

2017-01-27 09:49 UTC, s1monw approved these changes
LGTM

2017-01-27 09:49 UTC, s1monw commented on core/src/main/resources/org/elasticsearch/bootstrap/security.policy
> +  // Allow host/ip name service lookups
w00t

2017-02-02 15:59 UTC, jasontedor requested changes
I left one comment.

2017-02-02 15:59 UTC, jasontedor commented on core/src/main/resources/org/elasticsearch/bootstrap/test-framework.policy
> +grant codeBase "${codebase.httpcore-nio-4.4.5.jar}" {
Can you add comments to the places where these dependencies are defined that if the version is changed then the version needs to be updated here too? (This comment applies to all of the dependencies for which we have to supply these permissions.)

2017-02-02 16:51 UTC, jasontedor requested changes
I left one more comment.

2017-02-02 16:51 UTC, jasontedor commented on core/src/main/resources/org/elasticsearch/bootstrap/test-framework.policy
> +grant codeBase "${codebase.rest-6.0.0-alpha1-SNAPSHOT.jar}" {
Does this one deserve a comment too, above the `elasticsearch` version in version.properties?

2017-02-02 17:11 UTC, jasontedor approved these changes
LGTM.

2017-02-03 15:39 UTC, merged