Add doPrivilege blocks for socket connect ops in repository-hdfs
elastic/elasticsearch pull request #22793
Opened 2017-01-25 21:51 UTC by tbrooks8

This is related to #22116. The repository-hdfs plugin opens socket
connections. As `SocketPermission` is transitioned out of core, hdfs
will require `connect` permission. This pull request wraps operations
that require this permission in `doPrivileged` blocks.

2017-01-25 21:54 UTC, tbrooks8 commented
In hdfs we were [calling](https://github.com/elastic/elasticsearch/pull/22793/files#diff-0ec2356265a4ebf55b306a8b6d18391aR121) doPrivileged and explicitly defining the permissions. I was not sure if there was a reason we were doing this differently, so I left it as is and just added `new SocketPermission("*", "connect")`.

2017-01-25 22:07 UTC, rjernst commented
> In hdfs we are calling doPrivileged and explicitly defining the permissions

We do this to limit what craziness hdfs can do (and know exactly what it requires).

2017-01-25 22:09 UTC, rjernst approved these changes
LGTM

2017-01-27 09:32 UTC, s1monw reviewed
I left one comment looks great so far

2017-01-27 09:32 UTC, s1monw commented on plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsBlobContainer.java
> +                        return AccessController.doPrivileged((PrivilegedExceptionAction<Integer>) is::read);
can we maybe try to trigger this differently? I mean can we for instance try to call `#available()` or can we maybe read the first byte on open and wrap in a `BufferedInputStream` and then do this:

```Java

InputStream stream = is.isMarkSupported() ? is : new BufferedInputStream(is);
// do the following in doPrivileged?
stream.mark(1);
stream.skip(1);
stream.reset();
return stream;
```

2017-01-27 15:23 UTC, tbrooks8 commented
@s1monw In my testing available() was not doing the trick. So I went with the buffered, mark, skip, reset approach.

2017-01-27 15:33 UTC, s1monw requested changes
left one more comment we are close I think

2017-01-27 15:33 UTC, s1monw commented on plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsBlobContainer.java
> +            InputStream stream = is.markSupported() ? is : new BufferedInputStream(is);
if we run into an exception here we have to close the stream. 

we usually do this:

```Java
boolean success = false;
try {
 // do something with the stream
  success = true;
  return stream;
} finally {
  if (success == false) {
    IOUtils.closeWhileHandlingException(stream);
  }
}

2017-01-27 16:59 UTC, tbrooks8 commented
Note to other reviews:

Simon and I talked about this for a while and decided it was safest to return a `InputStream` implementation that wraps all of the methods.

2017-01-27 19:15 UTC, s1monw approved these changes
LGTM

2017-01-27 21:01 UTC, merged