Read ec2 discovery address from aws instance tags
elastic/elasticsearch pull request #22819
Opened 2017-01-26 17:33 UTC by dadoonet

This PR adds a new option for `host_type`: `tag:TAGNAME` where `TAGNAME` is the tag field you defined for your ec2 instance.

For example if you defined a tag `my-elasticsearch-host` in ec2 and set it to `myhostname1.mydomain.com`, then
setting `host_type: tag:my-elasticsearch-host` will tell Discovery Ec2 plugin to read the host name from the
`my-elasticsearch-host` tag. In this case, it will be resolved to `myhostname1.mydomain.com`.

Relates to #22566.
Backport of #22743 for 5.x branch (5.3)

2017-01-26 17:34 UTC, dadoonet commented
@tlrx I created a new PR for backporting #22743 in 5.x branch as I had to change some other code/tests.

Could you review it please?

2017-01-27 14:13 UTC, tlrx requested changes

2017-01-27 14:13 UTC, tlrx commented on plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java
> +            poorMansDNS.put(AmazonEC2Mock.PREFIX_PRIVATE_IP + (i+1), buildNewFakeTransportAddress());
Can we avoid the (i+1) everywhere?

2017-01-27 14:13 UTC, tlrx commented on plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java
> +            String instanceId = "node" + (i+1);
Same here

2017-01-27 14:13 UTC, tlrx commented on plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java
> +        int nodes = 2;//randomIntBetween(5, 10);
Leftover

2017-01-27 14:13 UTC, tlrx commented on plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java
> +            addresses[node] = "192.168.0." + (node + 1);
Same here... we don't really need `String[] addresses`

2017-01-27 14:13 UTC, tlrx commented on plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java
> +    private static final InetAddress META_ADDRESS;
Why "META"? Can we rename this to "ADDRESS"?

2017-01-27 14:13 UTC, tlrx commented on plugins/discovery-ec2/src/main/java/org/elasticsearch/cloud/aws/AwsEc2Service.java
> +        class HostType {
We don't need this inner class, can we drop it?

2017-01-27 14:13 UTC, tlrx commented on plugins/discovery-ec2/src/main/java/org/elasticsearch/cloud/aws/AwsEc2Service.java
>      interface DISCOVERY_EC2 {
Can we rename this? It doesn't follow the usual naming rules for interface

2017-01-27 14:28 UTC, dadoonet commented on plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java
> +    private static final InetAddress META_ADDRESS;
It's a copy and paste from here: https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/transport/TransportAddress.java#L43

I'd prefer keeping the same name as we have in master branch.

2017-01-27 14:28 UTC, dadoonet commented on plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java
> +        int nodes = 2;//randomIntBetween(5, 10);
OMG!

2017-01-27 14:29 UTC, dadoonet commented on plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java
> +            addresses[node] = "192.168.0." + (node + 1);
Indeed.

2017-01-27 14:31 UTC, dadoonet commented on plugins/discovery-ec2/src/main/java/org/elasticsearch/cloud/aws/AwsEc2Service.java
> +        class HostType {
It's what we have in master branch as well See: https://github.com/elastic/elasticsearch/blob/master/plugins/discovery-ec2/src/main/java/org/elasticsearch/cloud/aws/AwsEc2Service.java#L167-L173

2017-01-27 14:33 UTC, dadoonet commented on plugins/discovery-ec2/src/main/java/org/elasticsearch/cloud/aws/AwsEc2Service.java
>      interface DISCOVERY_EC2 {
Not within this PR. May be with a more global PR which we can apply on master branch?

2017-01-27 16:18 UTC, dadoonet commented
@tlrx I updated the tests. I did not address all your comments to keep the code consistent with what we have in master branch.

2017-01-27 16:36 UTC, tlrx approved these changes

2017-01-27 16:36 UTC, tlrx commented
@dadoonet As a follow up PR it would be great to fix the remaining inconsistencies

2017-01-27 16:43 UTC, merged