Include stale replica shard info when explaining an unassigned primary
elastic/elasticsearch pull request #22826
Opened 2017-01-26 23:46 UTC by abeyad

Currently, if a previously allocated shard has no in-sync copy in the
cluster, but there is a stale replica copy, the explain API does not
include information about the stale replica copies in its output.  This
commit includes any shard copy information available (even for stale
copies) when explaining an unassigned primary shard that was previously
allocated in the cluster.

This situation can arise as follows: imagine an index with 1 primary and
1 replica and a cluster with 2 nodes.  If the node holding the replica
is shut down, and data continues to be indexed, only the primary will
have the latest data and the replica that has gone offline will be
marked as stale.  Now, suppose the node holding the primary is shut
down.  There are no copies of the shard data in the cluster.  Now, start
the first stopped node (holding the stale replica) back up.  The cluster
is red because there is no in-sync copy available.  Running the explain
API before would inform the user that there is no valid shard copy in
the cluster for that shard, but it would not provide any information
about the existence of the stale replica that exists on the restarted
node.  With this commit, the explain API provides information about all
the stale replica copies when explaining the unassigned primary.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

2017-01-27 08:20 UTC, ywelsch requested changes
I think we should discuss whether to also add store exceptions (or even info for all nodes, like we have in other places).

2017-01-27 08:20 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/NodeAllocationResult.java
> +                    hasDecisions = true;
why this?

2017-01-27 08:20 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> +        List<NodeGatewayStartedShards> nonMatchingShardStores = explain ? new ArrayList<>() : null;
nonMatchingShardStates?

2017-01-27 08:20 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> +                    nonMatchingShardStores.add(nodeShardState);
this only choses those shard states which have an allocation id. Might also be interesting to have those that threw a store exception. I'm wondering if we should go even further and return all of them (also those where nothing was found).

2017-01-27 08:20 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> +                .map(s -> new DecidedNode(s, Decision.NO))
maybe we should add more information to this decider, saying why it is NO.

2017-01-27 18:21 UTC, abeyad commented
@ywelsch I pushed commits addressing our discussion on how to improve this PR

2017-01-27 18:46 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocateUnassignedDecision.java
> +                       .filter(result -> result.getShardStoreInfo() != null
there is a method called `anyMatch(...)`. This will also make it return true on the first occurrence found

2017-01-27 18:46 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/Decision.java
> +    public static Decision readOptional(StreamInput in) throws IOException {
use `in.readOptionalWriteable(Decision::readFrom())` instead

2017-01-27 18:46 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> +                nodesToAllocate.yesNodeShards.contains(shardData) == false
this is extremely inefficient (using contains on a list). Maybe it's sufficient to collect the `DiscoveryNode`s of yes/no/throttle into a set and do a lookup on that?

2017-01-27 18:46 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java
> +            // if there were no shard copies that were eligible for being assigned the allocation,
remove "if"

2017-01-27 20:06 UTC, abeyad commented
@ywelsch I pushed 5d4a0b8ebf1d1ecdb64508d978aded331f2e1f2c

2017-01-27 20:42 UTC, abeyad commented
retest this please

2017-01-28 14:45 UTC, ywelsch approved these changes
LGTM

2017-01-28 14:45 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocateUnassignedDecision.java
> +        if (getNodeDecisions() != null && getNodeDecisions().isEmpty() == false) {
no need for if/else,  just write
```
return getNodeDecisions() != null && getNodeDecisions().stream().anyMatch(...)
```

2017-01-28 14:45 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/NodeAllocationResult.java
> +        if (in.getVersion().before(Version.V_5_3_0_UNRELEASED)) {
this needs to be fixed before merging (as it should go to 5.2.1).

2017-01-31 22:25 UTC, abeyad commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/NodeAllocationResult.java
> +        if (in.getVersion().before(Version.V_5_3_0_UNRELEASED)) {
We now have a 5.2.1 constant, so I updated this.

2017-01-31 22:25 UTC, abeyad commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocateUnassignedDecision.java
> +        if (getNodeDecisions() != null && getNodeDecisions().isEmpty() == false) {
fixed

2017-01-31 22:28 UTC, abeyad commented
thanks for the review @ywelsch

2017-01-31 22:31 UTC, merged

2017-01-31 22:34 UTC, abeyad commented
5.x commit: c880638a45ff45603a0bec87eac086212f51c6ba
5.3 commit: 92dc5c0a115f615c438c8519a6ca53063344ddbd
5.2.1 commit: e143186a17ed4fdd6a2a116d4b796de1792feb9c