Avoid losing ops in file-based recovery
elastic/elasticsearch pull request #22945
Opened 2017-02-02 21:48 UTC by jasontedor

When a primary is relocated from an old node to a new node, it can have ops in its translog that do not have a sequence number assigned. When a file-based recovery is started, this can lead to skipping these ops when replaying the translog due to a bug in the recovery logic. This commit addresses this bug and adds a test in the BWC tests.

Relates #22484

2017-02-02 22:12 UTC, bleskes requested changes
This LGTM. It would be great to have tests added in RecoverySourceHandlerTests .

2017-02-02 22:12 UTC, bleskes commented on qa/backwards-5.0/src/test/java/org/elasticsearch/backwards/IndexingIT.java
> +            Integer.parseInt(XContentHelper.convertToMap(JsonXContent.jsonXContent, content, false).get("count").toString());
Any chance to use something like ObjectPath.evaluate(shard, "seq_no.local_checkpoint")?

2017-02-02 22:12 UTC, bleskes commented on qa/backwards-5.0/src/test/java/org/elasticsearch/backwards/IndexingIT.java
>              ensureGreen();
shall we add assert counts here too?

2017-02-02 22:55 UTC, jasontedor commented
@bleskes I pushed a unit tests in 4a010875bc988bc576bf0a9bb6cec4d9616576e5.

2017-02-02 23:03 UTC, jasontedor commented on qa/backwards-5.0/src/test/java/org/elasticsearch/backwards/IndexingIT.java
> +            Integer.parseInt(XContentHelper.convertToMap(JsonXContent.jsonXContent, content, false).get("count").toString());
I pushed 4430caa54a2b09f05f98331dc806e579d58aad52.

2017-02-02 23:10 UTC, jasontedor commented on qa/backwards-5.0/src/test/java/org/elasticsearch/backwards/IndexingIT.java
>              ensureGreen();
I pushed 0112f909a6a427f78bb9a5fcaaae7fc829863151.

2017-02-02 23:10 UTC, jasontedor commented
Thanks @bleskes. I've pushed commits in response to your comments.

2017-02-03 09:00 UTC, bleskes approved these changes
awesome

2017-02-03 09:01 UTC, bleskes commented
test this please

2017-02-03 12:15 UTC, bleskes commented
test this please

2017-02-03 13:11 UTC, merged

2017-02-03 13:12 UTC, jasontedor commented
Thanks @bleskes.