fix the index of header when build rest client
elastic/elasticsearch pull request #22976
Opened 2017-02-04 04:35 UTC by slixurd

the client header is not set properly because of missing the i++.

2017-02-04 04:35 UTC, elasticmachine commented
Can one of the admins verify this patch?

2017-02-06 20:54 UTC, jasontedor requested changes
This PR needs a test that fails without this fix.

2017-02-07 07:30 UTC, slixurd commented
@jasontedor 
Already add the unit test for this fix.
There is no check that the numbers of the headers to set  and the numbers of the headers in rest client are equal, because there is no public method to get the numbers of the headers in rest client .
But The Check in RestClient.builder() will result in NullPointerException when the headers are not set properly.

2017-06-09 07:21 UTC, rjernst commented
@jasontedor Are you happy with the test which was added?

2017-06-09 07:21 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-06-09 12:39 UTC, jasontedor requested changes
Sorry for the slow reply, I left some comments regarding the test.

2017-06-09 12:39 UTC, jasontedor commented on modules/reindex/src/test/java/org/elasticsearch/index/reindex/ReindexFromRemoteBuildRestClientTests.java
> +        System.out.println(headers.toString());
Can you remove this debugging output?

2017-06-09 12:39 UTC, jasontedor commented on modules/reindex/src/test/java/org/elasticsearch/index/reindex/ReindexFromRemoteBuildRestClientTests.java
> +        RestClient client = TransportReindexAction.buildRestClient(remoteInfo, taskId, threads);
This test should assert that the headers are correct.

2017-06-28 13:00 UTC, nik9000 requested changes

2017-06-28 13:00 UTC, nik9000 commented on modules/reindex/src/main/java/org/elasticsearch/index/reindex/TransportReindexAction.java
> +            clientHeaders[i++] = new BasicHeader(header.getKey(), header.getValue());
Yeah, that looks like the right fix....

2017-06-28 13:00 UTC, nik9000 commented on modules/reindex/src/test/java/org/elasticsearch/index/reindex/ReindexFromRemoteBuildRestClientTests.java
> +        RestClient client = TransportReindexAction.buildRestClient(remoteInfo, taskId, threads);
I agree with @jasontedor. I'd be fine with a adding `RestClient#getDefaultHeaders` which returns a copy of the `defaultHeaders` array so we can assert that they are correct. @javanna, what do you think of that?

Also, I don't think there is any need to assert on the threads in this test. The test above is careful about that already.

2017-06-28 14:52 UTC, javanna commented on modules/reindex/src/test/java/org/elasticsearch/index/reindex/ReindexFromRemoteBuildRestClientTests.java
> +        RestClient client = TransportReindexAction.buildRestClient(remoteInfo, taskId, threads);
I am ok with what you propose Nik!

2017-08-15 20:54 UTC, dakrone commented
@slixurd is this something you're still interested in pursuing? Can you address the feedback?

2017-10-10 05:10 UTC, rjernst commented
@slixurd As this PR seems to be stalled, I am going to close it. I have opened #26937 with the suggested tests, so that we can get this fix into 6.0. I hope you understand.

2017-10-10 05:10 UTC, closed without merging