Add xcontent parsing to suggestion options
elastic/elasticsearch pull request #23018
Opened 2017-02-07 14:47 UTC by cbuescher

This adds parsing from xContent to Suggestion.Entry.Option and
Termsuggestion.Entry.Option.

2017-02-08 08:31 UTC, tlrx requested changes
Thanks @cbuescher for this light PR! I left some comments.

2017-02-08 08:31 UTC, tlrx commented on core/src/main/java/org/elasticsearch/search/suggest/Suggest.java
> +                    this(text, null, score, null);
Can you revert this? I think it's fine to have ctor->ctor->ctor

2017-02-08 08:31 UTC, tlrx commented on core/src/main/java/org/elasticsearch/search/suggest/term/TermSuggestion.java
> +            private static final ConstructingObjectParser<Option, Void> PARSER = new ConstructingObjectParser<>("TermSuggestOptionParser",
Nit: can we change the name to TermSuggestionOptionParser to reflect the class name?

2017-02-08 08:31 UTC, tlrx commented on core/src/test/java/org/elasticsearch/search/suggest/SuggestionOptionTests.java
> +@Repeat(iterations=100)
Leftover?

2017-02-08 08:31 UTC, tlrx commented on core/src/test/java/org/elasticsearch/search/suggest/SuggestionOptionTests.java
> +        assertEquals(option.collateMatch(), parsed.collateMatch());
Maybe we could implement equals & hashcode easily?

2017-02-08 08:31 UTC, tlrx commented on core/src/test/java/org/elasticsearch/search/suggest/TermSuggestionOptionTests.java
> +        assertEquals(option.getFreq(), parsed.getFreq());
equals & hashcode?

2017-02-08 09:22 UTC, javanna approved these changes
I left a couple of minors, LGTM besides the comments that Tanguy already made.

2017-02-08 09:22 UTC, javanna commented on core/src/main/java/org/elasticsearch/search/suggest/Suggest.java
> +                public static class Fields {
can we get rid of this Fields inner class rather than making it public?

2017-02-08 14:22 UTC, cbuescher commented on core/src/main/java/org/elasticsearch/search/suggest/Suggest.java
> +                public static class Fields {
done.

2017-02-08 14:22 UTC, cbuescher commented on core/src/main/java/org/elasticsearch/search/suggest/term/TermSuggestion.java
> +            public static class Fields {
Sure.

2017-02-08 14:22 UTC, cbuescher commented on core/src/test/java/org/elasticsearch/search/suggest/TermSuggestionOptionTests.java
> +        assertEquals(option.getFreq(), parsed.getFreq());
Same as above, this Option uses the parent class equals/hash, don't know if thats intentional.

2017-02-08 14:22 UTC, cbuescher commented on core/src/test/java/org/elasticsearch/search/suggest/SuggestionOptionTests.java
> +        assertEquals(option.collateMatch(), parsed.collateMatch());
There already is an equals/hashCode here that only takes into account the `text` parameter. Maybe thats intentional, I would have to check with @areek about this.

2017-02-08 14:23 UTC, cbuescher commented on core/src/test/java/org/elasticsearch/search/suggest/SuggestionOptionTests.java
> +@Repeat(iterations=100)
gone.

2017-02-08 14:23 UTC, cbuescher commented on core/src/main/java/org/elasticsearch/search/suggest/term/TermSuggestion.java
> +            private static final ConstructingObjectParser<Option, Void> PARSER = new ConstructingObjectParser<>("TermSuggestOptionParser",
sure.

2017-02-08 14:23 UTC, cbuescher commented on core/src/main/java/org/elasticsearch/search/suggest/Suggest.java
> +                    this(text, null, score, null);
Sure, will change. But out of curiosity, what is wrong with directly calling the ctor directly?

2017-02-08 14:32 UTC, cbuescher commented
@tlrx @javanna thanks, I addressed the small issues you mentioned, waiting for feedback on the equals/hashCode but think that shouldn't hold this PR since its unrelated to the parsing, wdyt?

2017-02-08 14:33 UTC, tlrx commented on core/src/main/java/org/elasticsearch/search/suggest/Suggest.java
> +                    this(text, null, score, null);
Nothing wrong, just the collateMatch default value (`null`) when it's missing is defined at 2 places instead of one

2017-02-08 15:07 UTC, tlrx commented
@cbuescher Thanks! I don't think we should hold this PR, let's get this in.

2017-02-08 16:27 UTC, cbuescher commented
retest this please

2017-02-08 16:35 UTC, tlrx approved these changes

2017-02-08 18:03 UTC, merged

2017-02-09 10:25 UTC, cbuescher commented
Also merged with 5.x via 6734bca8b7a21752c5925aa4e6f72959d698de38