Remove legacy primary shard allocation mode based on versions
elastic/elasticsearch pull request #23016
Opened 2017-02-07 14:28 UTC by ywelsch

Elasticsearch v5.0.0 uses allocation IDs to safely allocate primary shards whereas prior versions of ES used a version-based mode instead. Elasticsearch v5 still has support for version-based primary shard allocation as it needs to be able to load 2.x shards. ES v6 can drop the legacy support.

2017-02-07 15:15 UTC, abeyad requested changes
I left a few comments, the stats on this PR are awesome :)

2017-02-07 15:15 UTC, abeyad commented on core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java
> +        final RoutingAllocation allocation =
The `routingAllocationWithOnePrimaryNoReplicas` method no longer needs to take a `Version` parameter, would be nice to get rid of it.

2017-02-07 15:15 UTC, abeyad commented on core/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java
> +
can we assert here that the number of replicas setting did indeed get updated?

2017-02-07 16:00 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/gateway/TransportNodesListGatewayStartedShards.java
> -            this.legacyVersion = legacyVersion;
No, it's also null if no shard info was found.

2017-02-07 16:09 UTC, ywelsch commented on core/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java
> +
sure, I've pushed 4617939

2017-02-07 16:09 UTC, ywelsch commented on core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java
> +        final RoutingAllocation allocation =
sure, I've pushed 4617939

2017-02-07 16:12 UTC, abeyad approved these changes

2017-02-07 16:12 UTC, abeyad commented
LGTM

2017-02-08 09:00 UTC, merged

2017-02-08 09:01 UTC, ywelsch commented
Thanks @abeyad