Docs: Consoleify cluster and indices settings docs
elastic/elasticsearch pull request #23030
Opened 2017-02-07 22:50 UTC by rjernst

relates #23001

2017-02-07 22:56 UTC, nik9000 requested changes
I left a few requests to fix things but everything else looks good. If you are ok with my proposals then feel free to make the changes and merge without another eview.

2017-02-07 22:56 UTC, nik9000 commented on docs/reference/cluster/update-settings.asciidoc
> +// TEST
This one is redundant.

2017-02-07 22:56 UTC, nik9000 commented on docs/reference/cluster/update-settings.asciidoc
> +// TESTRESPONSE[s/\.\.\./"acknowledged": true,/]
At this point I'd put `"acknowledged": true,` into the response you show the user instead.

2017-02-07 22:56 UTC, nik9000 commented on docs/reference/cluster/update-settings.asciidoc
> +// CONSOLE
This will cause the response to have `COPY AS CURL` and `VIEW IN CONSOLE` links which is not right. It is fine to leave it off.

2017-02-07 23:18 UTC, rjernst commented on docs/reference/cluster/update-settings.asciidoc
> +// TESTRESPONSE[s/\.\.\./"acknowledged": true,/]
I don't think it adds any value, and actually distracts from what the example is trying to point out. I tend to think anything not pertaining to what the example is explaining should not be displayed.

2017-02-08 00:21 UTC, nik9000 commented on docs/reference/cluster/update-settings.asciidoc
> +// TESTRESPONSE[s/\.\.\./"acknowledged": true,/]
Fine by me.

2017-02-08 00:21 UTC, nik9000 approved these changes

2017-02-10 22:57 UTC, merged