Expose WriteRequest.RefreshPolicy string representation
elastic/elasticsearch pull request #23106
Opened 2017-02-10 12:54 UTC by tlrx

This commit changes the `RefreshPolicy` enum so that string representation are exposed. This will help the high level rest client to simply use `refreshPolicy.getValue()` to get the corresponding parameter value of a given refresh policy.

2017-02-10 13:17 UTC, javanna requested changes
left a couple of comments

2017-02-10 13:17 UTC, javanna commented on core/src/main/java/org/elasticsearch/action/support/WriteRequest.java
> +        NONE((byte) 0, Boolean.FALSE.toString()),
nit: I am wondering if using "true" and "false" would be more readable, simply because I always forget if it's lowercase or uppercase.

2017-02-10 13:17 UTC, javanna commented on core/src/main/java/org/elasticsearch/action/support/WriteRequest.java
> +        private final byte id;
can we remove the id member and stick with the enum ordinal like we were doing before?

2017-02-10 13:17 UTC, javanna commented on core/src/main/java/org/elasticsearch/action/support/WriteRequest.java
> +            throw new IllegalArgumentException("No cluster block level matching [" + id + "]");
is this a cluster block level?

2017-02-10 13:19 UTC, tlrx commented on core/src/main/java/org/elasticsearch/action/support/WriteRequest.java
> +            throw new IllegalArgumentException("No cluster block level matching [" + id + "]");
It's a wonderful copy paste

2017-02-10 13:22 UTC, tlrx commented on core/src/main/java/org/elasticsearch/action/support/WriteRequest.java
> +        private final byte id;
Yes we can :(

2017-02-10 13:24 UTC, tlrx commented
Thanks @javanna, I updated the code.

2017-02-10 15:57 UTC, nik9000 approved these changes

2017-02-10 15:57 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/action/support/WriteRequest.java
> +            out.writeByte((byte) ordinal());        }
Nit: `}` is in a funny place.

2017-02-10 16:21 UTC, javanna approved these changes
LGTM besides nik's comment

2017-02-13 09:49 UTC, merged

2017-02-13 09:50 UTC, tlrx commented
Thanks @javanna @nik9000