Ensure network connections are restored after disruptions
elastic/elasticsearch pull request #23135
Opened 2017-02-12 19:05 UTC by bleskes

With #22977, network disruption also disconnects nodes from the transport service. That has the side effect that when the disruption is healed, the disconnected node stay disconnected until the `NodeConnectionsService` restores the connection. This can take too long for the tests. This PR adds logic to the cluster healing to restore connections immediately. 

See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/611/console for an example failure.

2017-02-13 21:41 UTC, bleskes commented
Test this please

2017-02-13 22:59 UTC, jasontedor requested changes
Looks good, but I left one request.

2017-02-13 22:59 UTC, jasontedor commented on test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java
> +        for (String node: internalCluster().getNodeNames()) {
Can you add a method to the test framework that takes an `InternalCluster` and executes this exact logic? You can invoke it here, and in `NetworkDisruption`.

2017-02-14 12:04 UTC, bleskes commented
Thx @jasontedor . I pushed another commit.

2017-02-14 21:52 UTC, jasontedor approved these changes
LGTM.

2017-02-15 09:04 UTC, merged