Migrate TermsQuery to TermInSetQuery
elastic/elasticsearch pull request #23229
Opened 2017-02-17 11:48 UTC by maddin2016

Fix #23201
This PR replace the usage of `TermsQuery` with `TermInSetQuery`. There are two tests i have commented out because i think they will no longer be needed.

2017-02-17 11:48 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-02-17 23:03 UTC, rjernst commented
@elasticmachine test this please

2017-02-20 11:26 UTC, jpountz requested changes
I left some comments.

2017-02-20 11:26 UTC, jpountz commented on core/src/test/java/org/elasticsearch/index/mapper/KeywordFieldTypeTests.java
> +    }*/
why did you comment out this test?

2017-02-20 11:26 UTC, jpountz commented on core/src/test/java/org/elasticsearch/index/mapper/TextFieldTypeTests.java
> +    //We still need this test??
yes, please. Lucene renamed the `TermsQuery` to `TermInSetQuery` but we plan on keeping support for the `terms` query in Elasticsearch, which is what this test is testing.

2017-02-20 11:26 UTC, jpountz commented on core/src/test/java/org/elasticsearch/index/query/HasChildQueryBuilderTests.java
> +        // we need to rewrite once for TermInSetQuery -> TermInSetQuery and than againt TermInSetQuery -> ConstantScoreQuery
this comment is outdated now, can you remove one of the rewrites on the line below?

2017-02-20 11:26 UTC, jpountz commented
@elasticmachine test this please

2017-02-20 12:12 UTC, maddin2016 commented
Hi @jpountz, i have rewrite the tests. I was litte bit confused by the tests name. I thought these tests where about the constructor of `TermsQuery`. So now all should be fine.

2017-02-20 13:14 UTC, jpountz approved these changes
Thanks, the diff looks great now.

2017-02-20 13:15 UTC, jpountz commented
@elasticmachine test this please

2017-02-20 13:38 UTC, maddin2016 commented
👍

2017-02-21 07:49 UTC, merged

2017-02-21 08:26 UTC, jpountz commented
Thanks @maddin2016 !