Added types options to DeleteByQueryRequest
elastic/elasticsearch pull request #23265
Opened 2017-02-20 14:47 UTC by kunal642

related to issue #21984

2017-02-20 14:47 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-02-21 15:51 UTC, nik9000 commented
I admit these requests in java are quite messy. Could you call `getSearchRequest.types(...)` instead?

2017-02-21 16:04 UTC, kunal642 commented
@nik9000 i did not get you
where do you want this call?

2017-02-21 16:15 UTC, kunal642 commented
@nik9000 from what i get from you comment, you do not want to add the types method and the user should use getSearchRequest.types(...) instead?

2017-02-21 16:35 UTC, nik9000 commented
> @nik9000 what i get from your comment is that you do not want to add the types method and the user should use getSearchRequest.types(...) instead
> am i correct?

Yes. I'm just sure it is worth adding this because that is an option.

2017-02-21 16:41 UTC, kunal642 commented
@nik9000 then the same should be followed for indices also.
getSearchRequest.indices(...) can be used to add the indices to the request and the indices method should also be removed from DeleteByQueryRequest.

2017-02-22 08:44 UTC, tlrx commented
> getSearchRequest.indices(...) can be used to add the indices to the request and the indices method should also be removed from DeleteByQueryRequest.

That would make sense I agree, but these methods come from `IndicesRequest` and must be implemented by DeleteByQueryRequest so that request execution logic knows which indices are involved in the delete by query.

2017-02-22 09:04 UTC, kunal642 commented
@tlrx The IndicesRequest can be removed because only the indices methods are present in that interface and the DeleteByQueryRequest class does not need those methods.
the SearchRequest which is passed to DeleteByQueryRequest can have the indices and types specified in it.

2017-02-22 10:21 UTC, javanna commented on core/src/test/java/org/elasticsearch/action/bulk/byscroll/DeleteByQueryRequestTests.java
> +    @Test
the Test annotation is banned in our project :) Something should fail when running the build from gradle. if the test method starts with test we are good, no need for the annotation

2017-02-22 10:23 UTC, javanna commented
hi @kunal642 , the DeleteByQueryRequest needs to implement IndicesRequest as plugins may want to retrieve/replace the indices that the request applies to. IndicesRequest allows to do it in a generic manner.

2017-02-22 11:44 UTC, kunal642 commented
@javanna removed the annotation

2017-02-23 18:12 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-02-27 10:14 UTC, kunal642 commented
@javanna is there anything else that needs changes?

2017-02-27 10:20 UTC, javanna requested changes
hi @kunal642 I had another look, left one comment, looks good otherwise

2017-02-27 10:20 UTC, javanna commented on core/src/main/java/org/elasticsearch/action/bulk/byscroll/DeleteByQueryRequest.java
> +    public IndicesRequest types(String...types) {
can you return DeleteByQueryRequest here please? Also add a whitespace between `String...` and `types`?

2017-02-27 11:46 UTC, kunal642 commented
@javanna the requested changes have been done

2017-03-01 10:42 UTC, kunal642 commented
@javanna Review this please

2017-03-02 10:14 UTC, javanna requested changes
hi @kunal642 I left a couple of comments

2017-03-02 10:14 UTC, javanna commented on core/src/test/java/org/elasticsearch/action/bulk/byscroll/DeleteByQueryRequestTests.java
> +            types[i] = randomSimpleString(random(), 1, 30);
This throws ArrayIndexOutOfBoundsException , can you fix that please?

2017-03-02 10:14 UTC, javanna commented on core/src/test/java/org/elasticsearch/action/bulk/byscroll/DeleteByQueryRequestTests.java
> +        int numIndices = between(1, 100);
do we need to test indices as well as part of this test? Maybe only test types?

2017-03-02 10:14 UTC, javanna commented on core/src/test/java/org/elasticsearch/action/bulk/byscroll/DeleteByQueryRequestTests.java
> +    public void testToDeleteByTypes() {
can you please rename to `testTypesSetter` or something along those lines ?

2017-03-02 10:49 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-03-02 10:51 UTC, kunal642 commented
@javanna the requested changes have been done.

2017-03-02 10:54 UTC, javanna approved these changes
thanks @kunal642 I will merge this.

2017-03-02 10:56 UTC, javanna commented on core/src/main/java/org/elasticsearch/action/bulk/byscroll/DeleteByQueryRequest.java
> +    public DeleteByQueryRequest types(String... types) {
sorry @kunal642 one last thing, could you also test this method please? set the types using this new method and check that the underlying search request types reflect the change?

2017-03-02 11:13 UTC, kunal642 commented
@javanna done

2017-03-02 15:52 UTC, merged