Deprecate repositories.s3 settings
elastic/elasticsearch pull request #23278
Opened 2017-02-20 22:28 UTC by dadoonet

Global repositories settings we were able to set in elasticsearch config file under `repositories.s3`
name space are now deprecated and will be removed in master (6.x) - see #23276.

This includes `repositories.s3.bucket`, `repositories.s3.server_side_encryption`,
`repositories.s3.buffer_size`, `repositories.s3.max_retries`, `repositories.s3.use_throttle_retries`,
`repositories.s3.chunk_size`, `repositories.s3.compress`, `repositories.s3.storage_class`, `repositories.s3.canned_acl`,
`repositories.s3.base_path` and `repositories.s3.path_style_access`.

We must set those settings per repository instead. Respectively `bucket`, `server_side_encryption`, `buffer_size`,
`max_retries`, `use_throttle_retries`, `chunk_size`, `compress`, `storage_class`, `canned_acl`, `base_path` and
`path_style_access`.

Related to #22800

2017-02-23 18:12 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-02-28 11:35 UTC, dadoonet commented
@rjernst This one is only deprecation. Can you review it please even if you want to hold off #23276?

2017-02-28 12:29 UTC, jasontedor requested changes
I left a comment. I didn't do a full review.

2017-02-28 12:29 UTC, jasontedor commented on plugins/repository-s3/src/test/java/org/elasticsearch/cloud/aws/AwsS3ServiceImplTests.java
> +        assertWarnings("setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes " +
You can use `ESTestCase#assertSettingDeprecations` here.

2017-02-28 16:49 UTC, dadoonet commented
@jasontedor I fixed it. It's strange that I had to fix other tests as it seems the assertWarning changed a bit. I'm going to try 5.x branch instead of mine to see if it's a regression introduced in 5.x or only something new in my branch.

2017-02-28 17:09 UTC, dadoonet commented
So apparently it's not only me: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.3+multijob-intake/87/console

2017-02-28 17:10 UTC, javanna commented
I have seen the same failure quite a few times today on my box (5.x branch)

2017-03-01 06:44 UTC, rjernst approved these changes
The change LGTM. You will need to update the latest master. See the changes Jason made there today to fix the tests.

2017-03-01 08:06 UTC, dadoonet commented
Thanks @rjernst!

@jasontedor as you requested the changes, can you review the last changes please? Thanks!

2017-03-16 10:35 UTC, dadoonet commented
@jasontedor I'm planning to merge this one hopefully next week. Any blocker on your side? Thanks!

2017-03-30 16:27 UTC, jasontedor approved these changes
LGTM.

2017-03-30 16:29 UTC, merged

2017-03-30 16:31 UTC, dadoonet commented
Thanks @jasontedor