Added examples of /etc/security/limits.conf changes
elastic/elasticsearch pull request #23277
Opened 2017-02-20 22:11 UTC by sarwarbhuiyan

- Added sections for memlock, nproc, and as
- changed links in bootstrap configs to point to limits.conf
  section

2017-02-20 22:13 UTC, sarwarbhuiyan commented
Fixes 23274

2017-02-21 09:14 UTC, clintongormley reviewed
I'll leave it to @jasontedor to comment on the correctness of the settings

2017-02-21 09:14 UTC, clintongormley commented on docs/reference/setup/bootstrap-checks.asciidoc
> +least 2048 threads. This can be done via <limits.conf,`/etc/security/limits.conf`>>
missing `<`

2017-02-21 09:14 UTC, clintongormley commented on docs/reference/setup/bootstrap-checks.asciidoc
> +address space. This can be done via <limits.conf,`/etc/security/limits.conf`>> using
missing `<`

2017-02-21 13:56 UTC, jasontedor requested changes
Thanks @sarwarbhuiyan, I left some comments.

2017-02-21 13:56 UTC, jasontedor commented on docs/reference/setup/sysconfig/configuring.asciidoc
> +We recommend setting <<bootstrap.memory_lock,`bootstrap.memory_lock`>>.
This is our last recommended way of minimizing the impact of swap. I think that we should remove the part about recommending here and only say that if you want to enable Elasticsearch to lock memory, you must permit the `elasticsearch` user to lock an unlimited amount of memory.

2017-02-21 13:56 UTC, jasontedor commented on docs/reference/setup/sysconfig/configuring.asciidoc
> +mlockall and avoid swapping, add the following line to the `limits.conf`
These days the recommended approach would be to create a file in `/etc/security/limits.d/` (e.g., `elasticsearch.conf`). I think that while we are here, we should go the extra mile and change these recommendations to be centered around this.

2017-02-23 18:12 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-02-24 08:44 UTC, sarwarbhuiyan commented
@jasontedor left some changes.

2017-06-09 07:10 UTC, rjernst commented
@jasontedor Are you happy with the updates that were made? Is this worth merging?

2017-06-09 07:10 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-08-15 20:16 UTC, dakrone commented
ping @jasontedor since this is waiting on your +1 or (currently standing) -1

2017-10-10 16:22 UTC, closed without merging

2017-10-10 16:23 UTC, jasontedor commented
Closing as the CLA is not signed. We can reopen if this changes.