Handle long overflow when adding paths' totals
elastic/elasticsearch pull request #23293
Opened 2017-02-21 17:51 UTC by dakrone

From #23093, we fixed the issue where a filesystem can be so large that it
overflows and returns a negative number. However, there is another issue when
adding a path as a sub-path to another `FsInfo.Path` object, when adding the
totals the values can still overflow.

This adds the same safety to return `Long.MAX_VALUE` instead of the negative
number, as well as a test exercising the logic.

2017-02-21 18:51 UTC, jasontedor requested changes
I left a comment.

2017-02-21 18:51 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/monitor/fs/FsProbe.java
> +    public static long adjustForHugeFilesystems(long bytes) {
Does it have to be public, can it be package-private?

2017-02-21 19:20 UTC, dakrone commented on core/src/main/java/org/elasticsearch/monitor/fs/FsProbe.java
> +    public static long adjustForHugeFilesystems(long bytes) {
Sure, I'll make it package-private, I just figured it's static, so there's no harm in it being public

Updated in 52ee78f191e1515570ae9e16d611920f336562c0

2017-02-21 19:30 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/monitor/fs/FsProbe.java
> +    public static long adjustForHugeFilesystems(long bytes) {
It becomes part of the public API.

2017-02-21 20:21 UTC, dakrone commented
retest this please

2017-02-21 23:41 UTC, dakrone commented
retest this please

2017-02-22 00:46 UTC, dakrone commented
retest this please `/sigh`

2017-02-22 17:46 UTC, jasontedor requested changes
I left some more comments.

2017-02-22 17:46 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/monitor/fs/FsProbeTests.java
> +            FsInfo.Path total = stats.getTotal();
Can you call this something other than `total`? It's really hard to read things like `total.total, total.total, total.total + total.total`.

2017-02-22 17:46 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/monitor/fs/FsProbeTests.java
> +            while ((total.total + total.total) > 0) {
If `total` is pathological (like one byte), this will take forever. Can you just add invocations of `randomNonNegativeLongs()`?

2017-02-22 18:21 UTC, dakrone commented
I pushed 11a33e48e08154ec5e92e2ea62d44451bd2dbb10 to address the comments

2017-02-22 18:30 UTC, jasontedor commented
I think there is a miscommunication; it's my fault. I mean like this:

```diff
diff --git a/core/src/test/java/org/elasticsearch/monitor/fs/FsProbeTests.java b/core/src/test/java/org/elasticsearch/monitor/fs/FsProbeTests.java
index 7cb0065628..486302ce0c 100644
--- a/core/src/test/java/org/elasticsearch/monitor/fs/FsProbeTests.java
+++ b/core/src/test/java/org/elasticsearch/monitor/fs/FsProbeTests.java
@@ -93,19 +93,21 @@ public class FsProbeTests extends ESTestCase {
     }
 
     public void testFsInfoOverflow() throws Exception {
-        FsInfo.Path pathStats = new FsInfo.Path("/foo/bar", null,
-                randomNonNegativeLong(), randomNonNegativeLong(), randomNonNegativeLong());
+        FsInfo.Path pathStats =
+                new FsInfo.Path("/foo/bar", null, randomNonNegativeLong(), randomNonNegativeLong(), randomNonNegativeLong());
 
         // While not overflowing, keep adding
-        while ((pathStats.total + pathStats.total) > 0) {
+        FsInfo.Path add = new FsInfo.Path("/baz/qux", null, randomNonNegativeLong(), randomNonNegativeLong(), randomNonNegativeLong());
+        while ((pathStats.total + add.total) > 0) {
             // Add itself as a path, to increase the total bytes until it overflows
-            logger.info("--> adding {} bytes to {}, will be: {}", pathStats.total, pathStats.total, pathStats.total + pathStats.total);
-            pathStats.add(pathStats);
+            logger.info("--> adding {} bytes to {}, will be: {}", add.total, pathStats.total, pathStats.total + add.total);
+            pathStats.add(add);
+            new FsInfo.Path("/baz/qux", null, randomNonNegativeLong(), randomNonNegativeLong(), randomNonNegativeLong());
         }
 
-        logger.info("--> adding {} bytes to {}, will be: {}", pathStats.total, pathStats.total, pathStats.total + pathStats.total);
-        assertThat(pathStats.total + pathStats.total, lessThan(0L));
-        pathStats.add(pathStats);
+        logger.info("--> adding {} bytes to {}, will be: {}", add.total, pathStats.total, pathStats.total + add.total);
+        assertThat(pathStats.total + add.total, lessThan(0L));
+        pathStats.add(add);
 
         // Even after overflowing, it should not be negative
         assertThat(pathStats.total, greaterThan(0L));
```

2017-02-22 18:41 UTC, dakrone commented
Alright, I changed it in 77128b6170a7f81662f8e49b50c9f215d7b2f484

2017-02-22 18:49 UTC, jasontedor approved these changes
LGTM.

2017-02-22 20:42 UTC, merged

2017-03-19 00:31 UTC, jasontedor commented
I backported this to 5.3 and 5.x.