Ensure that releasing listener is called
elastic/elasticsearch pull request #23310
Opened 2017-02-22 17:06 UTC by jasontedor

When sending a response to a client, we attach a releasing listener to the channel promise. If the client disappears before the response is
sent, the releasing listener was never notified. The reason the
listeners were never notified was due to a mistaken invocation of write
and flush on the channel which has two overrides: one that takes an
existing promise, and one that does not and instead creates a new
promise. When the client disappears, it is this latter promise that is
notified, which does not contain the releasing listener. This commit
addreses this issue by invoking the override that passes our channel
promise through.

2017-02-22 18:09 UTC, bleskes requested changes
Great catch. LGTM, though I left one important question about the release logic.

2017-02-22 18:09 UTC, bleskes commented on modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpChannel.java
> +            channel.writeAndFlush(msg, promise);
I think the release flag should be move after this? if we don't use the promise, it's useless no?

2017-02-22 18:09 UTC, bleskes commented on modules/transport-netty4/src/test/java/org/elasticsearch/http/netty4/Netty4HttpChannelTests.java
> +            final HttpPipelinedRequest pipelinedRequest = new HttpPipelinedRequest(request.request(), 1);
should we randomize if we use pipelining or not?

2017-02-22 18:23 UTC, jasontedor commented on modules/transport-netty4/src/test/java/org/elasticsearch/http/netty4/Netty4HttpChannelTests.java
> +            final HttpPipelinedRequest pipelinedRequest = new HttpPipelinedRequest(request.request(), 1);
I pushed 56a9f5e0b79080afd7d29173b44960a01216bef1 for this already. 😉

2017-02-22 18:23 UTC, jasontedor commented on modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpChannel.java
> +            channel.writeAndFlush(msg, promise);
I pushed d2a5ab28f716a8daa21a61decf9fa78c12b0cf07.

2017-02-22 18:25 UTC, bleskes approved these changes
LGTM

2017-02-22 18:54 UTC, merged

2017-02-22 19:00 UTC, Tim-Brooks reviewed
Looks like this was just merged, but I did just spend sometime looking at this and everything looked good to me.

2017-02-22 19:02 UTC, jasontedor commented
Thanks @bleskes and @tbrooks8.

2017-03-19 09:48 UTC, asafb-wix commented
Which versions are affected by this? we are seeing some issues with 5.2.0 that could be explained by this if this issue was present then?

2017-03-19 12:02 UTC, jasontedor commented
> Which versions are affected by this?

All versions prior to version 5.2.2.

2017-05-26 07:27 UTC, jchipmunk commented
Can you backport the pull request to Elasticsearch 5.1.x?

2017-05-26 10:12 UTC, jasontedor commented
> Can you backport the pull request to Elasticsearch 5.1.x?

Sorry, we will not do that as the 5.1 series will not see any additional releases.

2017-08-28 12:01 UTC, ebuildy commented
Can this happen on 2.4 also? What do you recommend to avoid this?

2017-08-28 12:05 UTC, jasontedor commented
No, this bug was specific to early 5.x releases.

2017-08-28 12:06 UTC, ebuildy commented
thanks you, I will post something in discuss so.

2017-10-07 21:02 UTC, ustczz commented
@jasontedor hi,thanks for fix the bug.
the bug aslo affect us , then we upgrate through rolling upgrades from 5.0.0 to 5.6.1 without search guid,but the problem Still exists. is not search guid or other method?
thank you!

2018-09-14 07:26 UTC, jasontedor commented
@nitishgoyal13 My wild guess is that has nothing to do with this issue and that that’s the accounting breaker. Check your stats, I suspect you’re running at capacity from a large number of shards.