Versioning for guava and jimfs
elastic/elasticsearch pull request #23342
Opened 2017-02-24 09:03 UTC by hendrikmuhs

This change puts guava and jimfs into versioning to fix a guava version conflict leading to jar-hell in a dependent project. For ease of use I also sorted the version file (keeping the original section, just order by alphabet inside a section) as it gets harder to read now with more and more entries.

2017-02-24 13:22 UTC, jasontedor requested changes
I don't think that we should do this for Guava.

2017-02-24 13:22 UTC, jasontedor commented on core/build.gradle
> +  testCompile "com.google.guava:guava:${versions.guava}"
I'm not comfortable with this change for Guava. Guava is a common transitive third-party dependency and there are breaking differences between releases so I don't think we should unify these transitive dependencies around a single version.

2017-02-24 13:22 UTC, jasontedor commented on plugins/repository-hdfs/build.gradle
> +  compile "com.google.guava:guava:${versions.guava}"
I'm surprised that we can get away with 16.0.1 here as Hadoop [declares a dependency on 11.0.2](https://github.com/apache/hadoop/blob/159d6c56e7f3aa3ebe45750cf88735287f047b42/hadoop-project/pom.xml#L509-L513). I've personally seen problems with using a different Guava version than the version that Hadoop expects. I'd prefer that we not make this change.

2017-02-24 13:22 UTC, jasontedor commented on buildSrc/version.properties
> +securemock        = 1.2
Please undo the unrelated changes in this file.

2017-02-24 13:31 UTC, nik9000 commented on buildSrc/version.properties
> +securemock        = 1.2
Sorting this file kind of broke the `# optional dependencies` and `#test dependencies` comments. I'd be fine with sorting the subsections, though it is probably a good idea to separate that from the Guava question.

2017-02-24 13:40 UTC, hendrikmuhs commented on core/build.gradle
> +  testCompile "com.google.guava:guava:${versions.guava}"
ok, fair enough. I can only say that it works w.r.t. API's, haven't done any intensive testing.

2017-02-24 13:42 UTC, hendrikmuhs commented on plugins/repository-hdfs/build.gradle
> +  compile "com.google.guava:guava:${versions.guava}"
off-topic, I did not change that, I only bumped 16.0.1 -> 18.0.

2017-02-24 13:43 UTC, jasontedor commented on plugins/repository-hdfs/build.gradle
> +  compile "com.google.guava:guava:${versions.guava}"
Yes, I understand that.

2017-02-24 13:43 UTC, hendrikmuhs commented on buildSrc/version.properties
> +securemock        = 1.2
no, it did not as stated in the PR. Wrong diff?

Anyway, no need to discuss further.

2017-02-24 13:49 UTC, hendrikmuhs commented
Closing this one, which means I have no fix for my downstream problem. :-(

@jasontedor any idea? Looks like it requires some sort of isolation. If I understand it correctly - correct me if I am wrong - we are already using the wrong version of guava? I am just guessing but wouldn't in this case the 1st one in the classpath win? That means we can not guarantee that the pinned version is used. Let me know, I can try to proof this theory.

2017-02-24 14:02 UTC, jasontedor commented
> I am just guessing but wouldn't in this case the 1st one in the classpath win? That means we can not guarantee that the pinned version is used. Let me know, I can try to proof this theory.

The Guava dependency in core is only a test dependency, and we have jar hell checks, I don't think this is the case.

2017-03-01 02:41 UTC, jasontedor commented
I'm going to close this pull request as I think it's been settled that we should not do this. Please correct if wrong @hendrikmuhs!

2017-03-01 02:41 UTC, closed without merging

2017-03-01 02:54 UTC, jasontedor commented on plugins/repository-hdfs/build.gradle
> +  compile "com.google.guava:guava:${versions.guava}"
I opened #23420.