Automatically release searchContext
elastic/elasticsearch pull request #23375
Opened 2017-02-26 14:37 UTC by maddin2016

Fix #23269 

This is a first approach to automatically release a search Context. To-do is to access all unique contexts from the same scroll request after that last fetch and calculate total elements in an index.

2017-02-26 14:42 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-02-27 09:27 UTC, jpountz requested changes
I left some comments.

2017-02-27 09:27 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/SearchService.java
> +    private final CopyOnWriteArrayList<Long> releasedContexts = new CopyOnWriteArrayList<>();
By keeping track of contexts in 2 different data-structures, I think you are potentially introducing race conditions, eg. if a clear scroll action is issued concurrently with an automatic release of the context due to the fact there are no more hits to process.

2017-02-27 09:27 UTC, jpountz commented on core/src/main/java/org/elasticsearch/action/search/SearchScrollQueryThenFetchAsyncAction.java
> +
why did you need to modify this class?

2017-02-27 09:27 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/SearchService.java
> +            return null;
I don't like introducing such a condition, could it instead return a proper `ScrollQuerySearchResult` instance, like it would have got before?

2017-02-27 09:27 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/SearchService.java
> +            if((context.queryResult().from() + context.queryResult().size()) >= 5){
5 looks hardcoded here?

2017-02-27 09:29 UTC, jpountz commented
In case you missed it, `ScrollContext.totalHits` should be helpful here in order to know when the context should be released.

2017-02-27 09:35 UTC, maddin2016 commented on core/src/main/java/org/elasticsearch/search/SearchService.java
> +    private final CopyOnWriteArrayList<Long> releasedContexts = new CopyOnWriteArrayList<>();
I have try to find a way to mark contexts for the reason if there are coming requests for contexts we have already released.

2017-02-27 09:36 UTC, maddin2016 commented on core/src/main/java/org/elasticsearch/search/SearchService.java
> +            if((context.queryResult().from() + context.queryResult().size()) >= 5){
Answered by you `ScrollContext.totalHits` 😃

2017-02-27 09:37 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/SearchService.java
> +    private final CopyOnWriteArrayList<Long> releasedContexts = new CopyOnWriteArrayList<>();
I haven't thought much about it but this is not an easy problem indeed...

2017-02-27 09:43 UTC, maddin2016 commented on core/src/main/java/org/elasticsearch/action/search/SearchScrollQueryThenFetchAsyncAction.java
> +
Intention was to work with the empty result if there is coming a request for a context that we have released and avoid to going into the fetch phase.

2017-02-27 09:48 UTC, maddin2016 commented on core/src/main/java/org/elasticsearch/action/search/SearchScrollQueryThenFetchAsyncAction.java
> +
i have undo the `finishHim` part. Could not estimate what happens in that `merge` phase.

2017-02-27 10:18 UTC, maddin2016 commented on core/src/main/java/org/elasticsearch/search/SearchService.java
> +            if((context.queryResult().from() + context.queryResult().size()) >= 5){
`context.scrollContext().totalHits` gives us only the total hits in that shard and not the index. Or did i use the wrong api?

2017-02-27 14:13 UTC, maddin2016 commented
Hi  @jpountz, i have change the logic a little bit when a context should be released. So now a context is released if there are no more hits in that shard `size >= totalHits`. The only thing now is, how to mark the released contexts. Maybe some new bool attribute `released`??

2017-08-15 19:39 UTC, dakrone commented
@jpountz is this still applicable?

2017-08-15 19:46 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-08-16 10:32 UTC, jpountz requested changes
Thank you @dakrone for the ping, I had missed the last update on this PR.

@maddin2016 Sorry for the late reply. The last update looks correct to me at first sight. However I'd like more inline comments about how it works since it is not obvious due to concurrency.

2017-08-16 10:32 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/SearchService.java
>      private SearchContext findContext(long id) throws SearchContextMissingException {
can you add some docs saying that this may return null if the context was already fully consumed?

2017-08-16 10:32 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/SearchService.java
> +                    freeContext(context.id());
can you add a comment about why you add to `releasedContexts` first? I think it is important for correctness?

2017-08-16 10:32 UTC, jpountz commented on core/src/main/java/org/elasticsearch/action/search/SearchScrollQueryThenFetchAsyncAction.java
> +import static java.util.Collections.EMPTY_LIST;
please remove this import now that it is not used anymore

2017-08-16 10:32 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/SearchService.java
> +    private final CopyOnWriteArrayList<Long> releasedContexts = new CopyOnWriteArrayList<>();
A `Collections.newSetFromMap(new ConcurrentHashMap<>())` would be more efficient IMO.

2017-11-06 15:42 UTC, javanna commented
hi @maddin2016 would you have a chance to address the last review comments?

2017-11-06 19:14 UTC, maddin2016 commented
Hi @javanna, sorry for the long time not working on this PR. Tommorow I will continue on this.

2017-11-10 09:38 UTC, maddin2016 commented on core/src/main/java/org/elasticsearch/search/SearchService.java
> +            return new ScrollQuerySearchResult();
Hi @javanna, i currently struggling with what we should return here. If we return `new ScrollQuerySearchResult()` i get this error for a scroll request
```
 "shard" : -1,
        "index" : null,
        "reason" : {
          "type" : "response_handler_failure_transport_exception",
          "reason" : "java.lang.NullPointerException",
          "caused_by" : {
            "type" : "null_pointer_exception",
            "reason" : null
```
I dont't find the point where we should return an empty result set.

2018-03-13 17:12 UTC, cbuescher commented
@martinscholz83 @jpountz this PR looks a bit out of date but still like something we want to have?
cc @elastic/es-search-aggs

2018-03-13 17:13 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-12-06 21:12 UTC, tomcallahan commented
Closing this as it has been open for some time.  If you'd like to re-engage, @martinscholz83, feel free to open another PR.

2018-12-06 21:12 UTC, closed without merging