ThreadedActionListener always wraps listener to preserve context
elastic/elasticsearch pull request #23390
Opened 2017-02-27 17:37 UTC by jaymode

The ThreadedActionListener may not be invoked by the same thread that creates it. When this happens, the ThreadContext from the thread that created the ThreadedActionListener should be used. This change makes the ThreadedActionListener always wrap the ActionListener in a ContextPreservingActionListener to prevent accidental loss of the ThreadContext.

Relates #23349

2017-02-27 17:57 UTC, bleskes requested changes

2017-02-27 17:57 UTC, bleskes commented on core/src/main/java/org/elasticsearch/action/support/ThreadedActionListener.java
> +        this.listener = ContextPreservingActionListener.wrap(listener, threadPool.getThreadContext(), false);
I know we talked about it but reflecting on this, I think it's too implicit to wrap things here. Better be explicit and put this as a parameter type and let the caller be aware and decide.

2017-02-28 09:21 UTC, bleskes commented on core/src/main/java/org/elasticsearch/action/support/AbstractListenableActionFuture.java
> +        listener = new ThreadedActionListener<>(logger, threadPool, ThreadPool.Names.LISTENER,
hmm.. is this correct? It's debatable what we should do here. Should we restore the context in which the listener was added or should we use the context of the thread that made the request and also keep the response headers. The way this is set up now, consumers don't have a choice. I'm starting to doubt if we should do this... @s1monw wdyt?

2017-02-28 12:05 UTC, jaymode commented on core/src/main/java/org/elasticsearch/action/support/AbstractListenableActionFuture.java
> +        listener = new ThreadedActionListener<>(logger, threadPool, ThreadPool.Names.LISTENER,
I agree and am beginning to think we should skip this change altogether for now

2017-02-28 12:51 UTC, bleskes commented on core/src/main/java/org/elasticsearch/action/support/AbstractListenableActionFuture.java
> +        listener = new ThreadedActionListener<>(logger, threadPool, ThreadPool.Names.LISTENER,
> think we should skip this change altogether

yeah. Let's just drop this. Thanks for trying..

2017-02-28 13:07 UTC, closed without merging