Azure repository: Move to named configurations as we do for S3 repository
elastic/elasticsearch pull request #23405
Opened 2017-02-28 11:27 UTC by dadoonet

We should have the same behavior for Azure repositories as we have for S3 (see #22762).

Instead of:

```yml
cloud:
    azure:
        storage:
            my_account1:
                account: your_azure_storage_account1
                key: your_azure_storage_key1
                default: true
            my_account2:
                account: your_azure_storage_account2
                key: your_azure_storage_key2
```

Support something like:

```
azure.client:
            default:
                account: your_azure_storage_account1
                key: your_azure_storage_key1
            my_account2:
                account: your_azure_storage_account2
                key: your_azure_storage_key2
```

Then instead of:

```
PUT _snapshot/my_backup3
{
    "type": "azure",
    "settings": {
        "account": "my_account2"
    }
}
```

Use:

```
PUT _snapshot/my_backup3
{
    "type": "azure",
    "settings": {
        "client": "my_account2"
    }
}
```

If someone uses:

```
PUT _snapshot/my_backup3
{
    "type": "azure"
}
```

It will use the `default` azure repository settings.

And mark as deprecated old settings.
The plan is to then remove deprecated settings as a follow up in master branch only.

Closes #22763.

2017-02-28 11:27 UTC, dadoonet commented
@rjernst Can you please look at it?

2017-02-28 12:28 UTC, jasontedor requested changes
I left a comment. I didn't do a full review, just one thing I noticed.

2017-02-28 12:28 UTC, jasontedor commented on plugins/repository-azure/src/test/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceTests.java
> +        assertWarnings("cloud.azure.storage.azure1.account", "cloud.azure.storage.azure1.key");
You can use `ESTestCase#assertSettingDeprecated` here (and throughout).

2017-03-01 06:58 UTC, rjernst commented on plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageSettings.java
> +        key -> Setting.simpleString(key, Property.NodeScope));
I don't think we should add new settings like this which are unsecured. This and `account` above should be secure settings.

2017-03-01 07:20 UTC, dadoonet commented on plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageSettings.java
> +        key -> Setting.simpleString(key, Property.NodeScope));
I agree but this is something I'm planning to do as a follow up instead of mixing it within this change.

2017-03-01 07:50 UTC, rjernst commented on plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageSettings.java
> +        key -> Setting.simpleString(key, Property.NodeScope));
That plan concerns me, as it means there is the (however distant) possibility these settings get released before being converted to secure settings.

2017-03-01 08:11 UTC, dadoonet commented on plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageSettings.java
> +        key -> Setting.simpleString(key, Property.NodeScope));
Let's do it like this.

Can you review the first phase of this PR and then I can add more commits to implement the security part? So we merge only a good version?
Like if we were having a feature branch.

WDYT?

2017-03-01 08:14 UTC, dadoonet commented on plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageSettings.java
> +        key -> Setting.simpleString(key, Property.NodeScope));
Well... Might not be a good idea. Ok. I'm going to add the commits to this PR then you will be able to review the whole change.

2017-03-01 10:04 UTC, dadoonet commented
@rjernst I secured our azure key/secret within this PR, changed the documentation accordingly and also the title/description of this PR.
LMK what you think of it. Thanks!

2017-03-16 10:33 UTC, dadoonet commented
@rjernst Could you please review this one? I'd like to merge it next week ideally.

2017-03-30 14:57 UTC, dadoonet commented
I'm planning to merge this on friday, March 31st, unless anyone objects.

2017-03-30 15:14 UTC, jasontedor commented
> I'm planning to merge this on friday, March 31st, unless anyone objects.

I object to this, this is not how we should handle missing code reviews.

2017-03-31 09:48 UTC, s1monw commented
@rjernst can you do a second pass on this please

2017-03-31 20:10 UTC, rjernst requested changes
This looks ok, but I'm still unsure about merging client settings and legacy settings into one map of client name to settings.

2017-03-31 20:10 UTC, rjernst commented on plugins/repository-azure/src/main/java/org/elasticsearch/plugin/repository/azure/AzureRepositoryPlugin.java
> +            // AzureStorageSettings.DEPRECATED_ACCOUNT_SETTING,
These should definitely be registered. Is there some other registration of a prefix that is masking validation of all of these settings?

2017-06-09 07:32 UTC, rjernst commented
@dadoonet Is this something you still want to try to get in? Can you try to refactor the change to only us a single map of client name to client settings?

2017-06-09 08:26 UTC, dadoonet commented
@rjernst Definitely yes. That's why I opened recently #25069. Now you fixed that I can move forward on this.

2017-06-19 16:21 UTC, dadoonet commented
@rjernst I updated the PR. Could you review it?

2017-06-28 08:30 UTC, dadoonet commented
@rjernst ping?

2017-07-12 21:55 UTC, rjernst approved these changes
@dadoonet I am so sorry for the long delay in re-reviewing this. I've had these comments queued up for weeks and didn't realize I had never submitted them. :(

I'm ok with these changes to go in as they are. My comments are about my uneasiness of having this internal "default name", but that is an internal detail that we/I can cleanup later.

2017-07-26 16:43 UTC, dadoonet commented on plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/blobstore/AzureBlobStore.java
> +            this.clientName = Repository.ACCOUNT_SETTING.get(metadata.settings());
Very true. Thanks!

2017-07-26 16:46 UTC, dadoonet commented on plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageService.java
> +        static final Setting<TimeValue> TIMEOUT_SETTING =
Sure.

2017-07-26 17:10 UTC, dadoonet commented on plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java
> +                // If someone did not register any settings or deprecated settings, they
Agreed.

2017-07-26 23:50 UTC, rjernst approved these changes
Still LGTM

2017-07-28 12:15 UTC, dadoonet commented
I need to iterate again a bit more as the first tests I'm doing shows that actually it's a breaking change.

With an "old" `elasticsearch.yml` configuration:

```yml
cloud.azure.storage.my_account.account: ACCOUNT
cloud.azure.storage.my_account.key: KEY
```

When creating the repository:

```sh
curl -XDELETE 127.0.0.1:9200/_snapshot/azure?pretty
curl -XPUT '127.0.0.1:9200/_snapshot/azure?pretty' -H 'Content-Type: application/json' -d'
{
  "type": "azure"
}'
```

It is failing with:

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Can not find named azure client [default]. Check your elasticsearch.yml."
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "Can not find named azure client [default]. Check your elasticsearch.yml."
  },
  "status" : 400
}
```

Which means that the default legacy account is not found anymore if the account name is not `default`.

With:

```yml
cloud.azure.storage.default.account: ACCOUNT
cloud.azure.storage.default.key: KEY
```

It works well.

I'm going to fix that.

2017-07-28 13:41 UTC, dadoonet commented
@rjernst I pushed a new commit to fix the problem I mentioned https://github.com/elastic/elasticsearch/pull/23405#issuecomment-318636885

Basically, it stores a "legacy" configuration under 2 names:

* `default` which is the one we are defaulting to if no "client" is specified
* the original name if not `default` so if someone is explicitly referencing that name in a repository configuration it will still work.

LMK

2017-08-07 09:10 UTC, dadoonet commented
@rjernst Do you agree with the changes I proposed?

2017-08-07 17:05 UTC, rjernst approved these changes
LGTM, one small request for clarity.

2017-08-07 17:05 UTC, rjernst commented on plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageSettings.java
> +    public static Map<String, AzureStorageSettings> load(Settings settings) {
Can you please rename this method and/or `parse` to make it clear this method is for the new style settings and the other one is for the legacy settings?

2017-08-08 13:16 UTC, merged

2017-08-08 13:31 UTC, dadoonet commented
Thanks @rjernst! I pushed it to master (7.0) and 6.x (6.1).
I'm going to add a follow up to remove the legacy settings in master branch (7.0).

2017-09-28 11:58 UTC, dadoonet commented
@rjernst @clintongormley I think I should also backport that one to 6.0. People will benefit from secured settings with 6.0 GA instead of having to wait for 6.1.

WDYT?

2017-09-29 09:29 UTC, clintongormley commented
@dadoonet it's too late for 6.0.  This can go into 6.1