Misspelled letter
elastic/elasticsearch pull request #23447
Opened 2017-03-02 08:28 UTC by ianomad

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

2017-03-02 08:28 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-03-02 08:33 UTC, ianomad commented
absolutely!

2017-04-18 01:55 UTC, nik9000 requested changes

2017-04-18 01:55 UTC, nik9000 commented on docs/reference/modules/discovery/zen.asciidoc
> +active master node will step down and a new master election will be begun.
I think this should be "active master node will step down and a new master election will *begin*".

2017-04-19 18:49 UTC, closed without merging