Fix for issue #22358
elastic/elasticsearch pull request #23491
Opened 2017-03-06 11:17 UTC by nilabhsagar

Closes #22358

2017-03-06 11:17 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-03-14 05:42 UTC, nilabhsagar commented
@areek Request you to look at this fix.

2017-04-04 08:21 UTC, nilabhsagar commented
Hi Requesting some one from Elasticsearch to verify this fix.

2017-04-11 07:02 UTC, rjernst requested changes
Sorry for the long delay. I left some comments.  This also needs tests.

2017-04-11 17:49 UTC, nilabhsagar commented
@rjernst Thanks for the review, I have incorporated the changes as suggested by you.

2017-04-11 17:53 UTC, rjernst reviewed
Thank you for the tests and changes! One more request for the tests, and could you also please update the PR title and description to explain what is changing.

2017-04-11 17:53 UTC, rjernst commented on core/src/test/java/org/elasticsearch/search/suggest/completion/CategoryContextMappingTests.java
> +        } catch(MapperParsingException e) {
You can use `expectThrows(MapperParsingException.class, () -> { /* code that throws */});`, then check the message on the returned exception.

2017-04-11 17:53 UTC, rjernst commented
@elasticmachine please test this

2017-04-13 01:21 UTC, nilabhsagar commented
@rjernst as suggested all changes are done. Please verify.

2017-04-13 06:42 UTC, rjernst approved these changes

2017-04-13 06:43 UTC, merged

2017-04-13 06:43 UTC, rjernst commented
Thanks @nilabhsagar

2017-04-14 01:05 UTC, nilabhsagar commented
Thanks @rjernst