removing retries from s3 blob store. Close #22845
elastic/elasticsearch pull request #23550
Opened 2017-03-12 06:36 UTC by lewischen1123

removing retries from s3 blob store. Close #22845.

2017-03-12 06:36 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-03-12 20:22 UTC, abeyad requested changes
@lewischen1123 thank you for contributing to Elasticsearch.  

I think the goal with this issue was to keep the max retry setting on the AWS S3 client (so that we can still configure the number of retries we set on the S3 client), but remove the retry logic from the `S3BlobStore` class.  That would mean getting rid of the `numberOfRetries` in the `S3BlobStore`, fixing the `S3BlobStore#readBlob()` method so retries aren't used (since they are taken care of by the S3 client), and removing the retries logic from the `S3OutputStream`.

Lastly, we will need you to kindly sign the CLA.

2017-03-16 15:30 UTC, abeyad requested changes
Also, the `S3BlobStore` class does not need any retries code anymore (don't need the class field, or anything else related to it).  The only place where the configured number of max retries needs to remain is in `S3Repository`, which passes that value to the `AwsS3Service`.

2017-03-16 15:30 UTC, abeyad commented on plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/DefaultS3OutputStream.java
> +            while (retry <= 0) {
we should get rid of the retry logic here entirely, there is no need for the while loop when we aren't retrying.

2017-03-16 15:30 UTC, abeyad commented on plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/DefaultS3OutputStream.java
> +        while ((retry <= 0) && (multipartId == null)) {
same here, all retry logic should be removed

2017-03-16 15:30 UTC, abeyad commented on plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/DefaultS3OutputStream.java
> +                if (getBlobStore().shouldRetry(e) && retry < 0) {
same here with removing retry logic

2017-03-16 15:30 UTC, abeyad commented on plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/DefaultS3OutputStream.java
> +            while (retry <= 0) {
same here with removing retry logic

2017-03-16 15:30 UTC, abeyad commented on plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/DefaultS3OutputStream.java
> +                    if (getBlobStore().shouldRetry(e) && retry < 0) {
same here with removing retry logic

2017-03-16 15:30 UTC, abeyad commented on plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/DefaultS3OutputStream.java
> +        while (retry <= 0) {
same here with removing retry logic

2017-03-16 15:30 UTC, abeyad commented on plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/DefaultS3OutputStream.java
> +                if (getBlobStore().shouldRetry(e) && retry < 0) {
same here with removing retry logic

2017-03-16 15:30 UTC, abeyad commented on plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/DefaultS3OutputStream.java
>      public DefaultS3OutputStream(S3BlobStore blobStore, String bucketName, String blobName, int bufferSizeInBytes, int numberOfRetries, boolean serverSideEncryption) {
number of retries should be removed as a constructor arg

2017-04-03 23:18 UTC, rjernst commented
@lewischen1123 Are you still interested in finishing up this PR?

2017-04-03 23:44 UTC, closed without merging