Introduce single-node discovery
elastic/elasticsearch pull request #23595
Opened 2017-03-15 18:51 UTC by jasontedor

This commit adds a single node discovery type. With this discovery type, a node will elect itself as master and never form a cluster with another node.

2017-03-15 18:51 UTC, jasontedor commented
A follow-up will reveal the true purpose of this. :wink:

2017-03-15 23:51 UTC, bleskes requested changes
Main change looks good to me. Left some minor comments.

2017-03-15 23:51 UTC, bleskes commented on core/src/main/java/org/elasticsearch/discovery/single/SingleNodeDiscovery.java
> +        return null;
I'm doubting if this should returns a `new DiscoveryStats(null)`. wdyt?

2017-03-15 23:51 UTC, bleskes commented on core/src/main/java/org/elasticsearch/discovery/single/SingleNodeDiscovery.java
> +        clusterService.submitStateUpdateTasks(
out of curiosity - why didn't you use a simple `ClusterStateUpdateTask` ?

2017-03-15 23:51 UTC, bleskes commented on core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java
> -
nit: unneeded?

2017-03-15 23:51 UTC, bleskes commented on core/src/test/java/org/elasticsearch/discovery/single/SingleNodeDiscoveryIT.java
> +    public void testDoesNotPing() throws IOException, InterruptedException, ExecutionException {
I'm a bit confused by this test - as far as I can tell it doesn't do anything with single node discovery? what are we testing here?

2017-03-15 23:51 UTC, bleskes commented on core/src/test/java/org/elasticsearch/discovery/single/SingleNodeDiscoveryTests.java
> +            discovery.startInitialJoin();
doesn't this go async? should we wait via an observer? maybe take the code from node.java ?

2017-03-16 00:01 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/discovery/single/SingleNodeDiscoveryIT.java
> +    public void testDoesNotPing() throws IOException, InterruptedException, ExecutionException {
A single node with discovery type set to `single-node` is started, and then we attempt to ping as Zen discovery would. The purpose is to test that the node will not join a cluster with Zen discovery configured. Does that make sense? Do you have an idea for a better test? Do you think that we need to test that two nodes with `single-node` configured as the discovery type will not join each other?

2017-03-16 00:11 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/discovery/single/SingleNodeDiscoveryTests.java
> +            discovery.startInitialJoin();
Good catch. I pushed 5caab7d12d367f33eaeca9ab8d41ee76cfcdce14.

2017-03-16 00:11 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java
> -
I pushed f235c8bdc7dfb8dc9ca5edc9878d5808cfb7feed.

2017-03-16 00:11 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/discovery/single/SingleNodeDiscovery.java
> +        clusterService.submitStateUpdateTasks(
No reasoning other than this is what my fingers did.

2017-03-16 00:16 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/discovery/single/SingleNodeDiscovery.java
> +        clusterService.submitStateUpdateTasks(
No, it wasn't my fingers. I see why I did this. A `ClusterStateUpdateTask` can not override `runOnlyOnMaster` which we need to set to `false` here. 😄

2017-03-16 00:18 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/discovery/single/SingleNodeDiscovery.java
> +        return null;
I pushed e10a245abc91dbb89d8c095d7d6bed1fbefa950e.

2017-03-16 00:18 UTC, jasontedor commented
Thanks @bleskes; I have responded to your feedback.

2017-03-16 00:21 UTC, bleskes approved these changes
LGTM. See if you want to bite your teeth on that test suggestion

2017-03-16 00:21 UTC, bleskes commented on core/src/test/java/org/elasticsearch/discovery/single/SingleNodeDiscoveryIT.java
> +    public void testDoesNotPing() throws IOException, InterruptedException, ExecutionException {
Oh, I see. So it's more like a "node has a good cloaking device" test. Reading the name I assumed you check that a single-node discovery doesn't ping other nodes (i.e., doesn't join). I think this test is nice (with a new name). Maybe another good test is to start two nodes with the same cluster name and port ranges that would normally cause them to find each other and see that they don't (it's a bit tricky w.r.t fixing ports but I think we can figure something out)

2017-03-16 00:21 UTC, bleskes commented on core/src/main/java/org/elasticsearch/discovery/single/SingleNodeDiscovery.java
> +        clusterService.submitStateUpdateTasks(
Oh right. I forgot about that. ++

2017-03-16 15:00 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/discovery/single/SingleNodeDiscoveryIT.java
> +    public void testDoesNotPing() throws IOException, InterruptedException, ExecutionException {
@bleskes I pushed 4c913108aac79a8cf42b05243c803eddbe159d2e to start a discussion. Let me know what you think.

2017-04-04 07:02 UTC, merged

2017-04-04 07:16 UTC, jasontedor commented
Thanks @bleskes.

2018-02-05 21:15 UTC, chitraj8 commented
I am trying to use elasticsearch version 5.6 and will need test it in a single node type. please suggest the configuration files that will require the change and get started.

2018-02-05 21:26 UTC, jasontedor commented
@chitraj8 Please check the docs, and please use the [forum](https://discuss.elastic.co) if you need more help. We reserve GitHub issues for verified bug reports and feature requests, and merged pull requests are not the place to ask general questions.