Fix MapperService StackOverflowError
elastic/elasticsearch pull request #23605
Opened 2017-03-16 02:52 UTC by jkiang13

I have been running this patch in my cluster to address issue #23604

2017-03-16 02:52 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-03-16 03:02 UTC, jasontedor commented
Thanks for the pull request @jkiang13; can you please sign the CLA and add a test case that would fail on current master and is addressed by your patch?

2017-03-16 03:11 UTC, jkiang13 commented
I did sign the CLA (perhaps I did it out of order of submitting this pull request).

I am actually not sure how to write a test case for this, as generating a StackOverflowError would kill the JVM running the test. If you look at the referenced issue I have a simple script that reproduces the issue.

2017-03-16 03:17 UTC, jasontedor commented
> I am actually not sure how to write a test case for this, as generating a StackOverflowError would kill the JVM running the test.

I think that you think this because of the uncaught exception handler. It does not apply to tests, you can write a test that produces a stack overflow without killing the JVM (I did it in a recent test even). With this information, do you want to give it a try?

> kOverflowError would kill the JVM running the test. If you look at the referenced issue I have a simple script that reproduces the issue.

I see it, and I appreciate, and it makes me think that you can write a test here. A script will not suffice though, it needs to be something we can run with every CI run.

2017-03-16 18:28 UTC, ywelsch requested changes
The stored structures don't need to be put into a fresh set on every call. The proper solution here is to only wrap the structures by unmodifiable* if they changed, i.e.

```
if (parentTypes != this.parentTypes) {
  parentTypes = Collections.unmodifiableSet(parentTypes);
}
```

2017-03-16 18:35 UTC, ywelsch commented
Also, the test here can simply be a unit test that does a mapping update that does not change parentTypes. The value returned by `getParentTypes()` should then be the same map as we had before the mapping update (reference identity).

2017-03-16 18:37 UTC, ywelsch commented
bonus points if you do the same for `fullPathObjectMappers`.

2017-03-18 03:33 UTC, jkiang13 commented
My thought was that copying the Set always up front seemed worth it for the simplicity, especially when it looks like subtlety around these collections probably contributed to this bug arising in the first place.

But I will of course defer to you folks. Take a look at the subsequent commits.

2017-03-20 10:46 UTC, ywelsch approved these changes
LGTM, thanks for the contribution.

2017-03-20 10:53 UTC, merged

2017-03-20 11:01 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?