Deprecate delete_by_query requests without an explicit query
elastic/elasticsearch pull request #23635
Opened 2017-03-17 18:38 UTC by dimitris-athanasiou

2017-03-17 19:05 UTC, jasontedor commented
It's possible to add a REST test that asserts on the warning header.

2017-03-18 20:22 UTC, dimitris-athanasiou commented
@jasontedor ++. Yaml test is now added.

2017-03-18 20:30 UTC, jasontedor requested changes
Thanks. I left some comments.

2017-03-18 20:30 UTC, jasontedor commented on modules/reindex/src/test/resources/rest-api-spec/test/delete_by_query/20_validation.yaml
> +      reason: warning headers were introduced in 5.0.1 and their format changed in 5.3.0
I think the reason should be because a DBQ with an empty body wasn't deprecated until 5.4.0.

2017-03-18 20:30 UTC, jasontedor commented on modules/reindex/src/test/resources/rest-api-spec/test/delete_by_query/20_validation.yaml
> +      version: " - 5.2.99"
I think this should be to 5.3.99. Without this, the BWC tests will fail.

2017-03-18 21:03 UTC, dimitris-athanasiou commented on modules/reindex/src/test/resources/rest-api-spec/test/delete_by_query/20_validation.yaml
> +      version: " - 5.2.99"
Cool, I thought the version/reason had to do with introducing warnings in the YAML framework :-)

2017-03-18 21:04 UTC, dimitris-athanasiou commented
@jasontedor I updated the skipping reason/version as suggested.

2017-03-22 19:07 UTC, dimitris-athanasiou commented
@jasontedor Could you have another look at this when you have time?

2017-03-23 00:38 UTC, jasontedor requested changes
Can you add a note to the breaking changes docs? It looks like at this time we do not have any for this branch. You can create a file `docs/migration/migrate_5_4.asciidoc` and mimic the structure of the existing breaking changes for the 5.3 branch.

2017-03-23 10:49 UTC, dimitris-athanasiou commented
@jasontedor Good catch! I added a doc for 5.4.

2017-03-23 11:52 UTC, jasontedor requested changes
I left one more suggestion.

2017-03-23 11:52 UTC, jasontedor commented on docs/reference/migration/migrate_5_4.asciidoc
> +[[breaking_54_delete_by_query_changes]]
I don't think we need a separate section for DBQ, maybe "REST API changes" would be better?

2017-03-23 11:52 UTC, jasontedor commented on docs/reference/migration/migrate_5_4.asciidoc
> +=== Delete By Query API changes
So I think this should be "REST API changes" and then DBQ could be a section within that.

2017-03-23 12:05 UTC, dimitris-athanasiou commented on docs/reference/migration/migrate_5_4.asciidoc
> +=== Delete By Query API changes
I wasn't sure about this either. In the 5.1 doc, it has explicitly `Indices API changes`, but in the 5.3 doc, it has `REST API changes`. I also think that the change does not impact only the REST layer. Users creating DBQ requests through Java, for example, will also have to deal with this.

Having said that, I don't have enough experience on how this is best documented.

Final call?

2017-03-23 12:17 UTC, jasontedor commented on docs/reference/migration/migrate_5_4.asciidoc
> +=== Delete By Query API changes
I think that you make a good point and it should be left how you have it.

2017-03-25 00:34 UTC, jasontedor approved these changes
LGTM.

2017-03-27 10:03 UTC, merged