Deprecate request_cache for clear-cache
elastic/elasticsearch pull request #23638
Opened 2017-03-18 00:28 UTC by StefanGor

Fixes issue #22748.
This commit deprecates the use of 'request_cache' to clear the cache. Instead, 'request' should be used.
This is my first contribution, so any feedback is appreciated, particularly around code conventions and the versioning I specified in the test case.

2017-03-18 00:28 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-03-19 10:44 UTC, StefanGor commented
I just realised that my [withPath("_cache")](https://github.com/elastic/elasticsearch/pull/23638/files#diff-b4805c97dc2b0bb10467b417d3986ac7R37) should be withPath("/_cache/clear"), but it doesn't actually make a difference to the test as I am just using the request body to instantiate a ClearIndicesCacheRequest. Should I still be including the withPath() call at all?

2017-03-20 14:15 UTC, nik9000 requested changes
> Should I still be including the withPath() call at all?

I'd drop it entirely, yeah.

2017-03-20 14:15 UTC, nik9000 commented on rest-api-spec/src/main/resources/rest-api-spec/test/indices.clear_cache/10_basic.yaml
> +      version: " - 5.2.2"
This'll be `5.4.0` rather than `5.2.2`, probably.

2017-03-20 14:35 UTC, jasontedor commented on rest-api-spec/src/main/resources/rest-api-spec/test/indices.clear_cache/10_basic.yaml
> +      version: " - 5.2.2"
Probably 5.3.99?

2017-03-20 14:42 UTC, nik9000 commented on rest-api-spec/src/main/resources/rest-api-spec/test/indices.clear_cache/10_basic.yaml
> +      version: " - 5.2.2"
Good call. I always forget the `.99` thing.

2017-03-21 15:12 UTC, nik9000 approved these changes
Looks good to me. I'll try and merge it this afternoon. I've fried my nice desktop so I'm going to have to rebuild it first....

2017-03-22 00:04 UTC, nik9000 commented
Sorry, didn't get to this yet. 🔥 💻 🔥  🚒 🚒 🚒

2017-03-22 12:28 UTC, merged

2017-03-22 15:03 UTC, nik9000 commented
I've merged this to master and 5.x. I pushed 2e3ea918dc992ece7fe7dab835b36e3db935a872 to correct some errors I saw during the backport. CI is a bit upset with this change because the 5.x build hasn't finished yet but it should calm down soon.

2017-03-22 15:03 UTC, nik9000 commented
Thanks @StefanGor!