Require explicit query in _delete_by_query API
elastic/elasticsearch pull request #23632
Opened 2017-03-17 14:14 UTC by dimitris-athanasiou

As the query of a search request defaults to match_all,
calling _delete_by_query without an explicit query may
result in deleting all data.

In order to protect users against falling into that
pitfall, this commit adds a check to require the explicit
setting of a query.

Closes #23629

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

2017-03-17 14:23 UTC, bleskes requested changes
Change looks great. Thanks!. I would be happier with a rest test to validate it rest requests are rejected as well.

2017-03-17 14:39 UTC, nik9000 commented
> Change looks great. Thanks!. I would be happier with a rest test to validate it rest requests are rejected as well.

++

2017-03-17 16:10 UTC, dimitris-athanasiou commented
@bleskes, @nik9000 I have added a YAML test. Could you have another look?

2017-03-17 16:31 UTC, nik9000 approved these changes

2017-03-17 18:39 UTC, dimitris-athanasiou commented
Related to this, I have also opened #23635.

2017-03-22 19:06 UTC, dimitris-athanasiou commented
@bleskes Could you have another look at this when you have time?

2017-03-22 22:37 UTC, bleskes approved these changes
LGTM. Sorry for the delay

2017-03-22 23:00 UTC, bleskes commented
Sorry, one more thing - since we're not back porting it to 5.x (it's breaking) - we should make sure the rest doesn't doesn't run when the cluster has a 5.x version in it. You can do it with a skip instruction. See [here](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/main/resources/rest-api-spec/test#skipping-tests) for details. Also, since it's marked as breaking, we should probably add a one liner to the migration docs [here](https://github.com/elastic/elasticsearch/tree/master/docs/reference/migration/migrate_6_0) but we probably need a new section. @nik9000 any thoughts on where to put it?

2017-03-23 10:58 UTC, dimitris-athanasiou commented
@bleskes I added the skip section. I put version "6.0.0 - ". I am not sure how this works with alphas and betas.

In regard to the docs, in #23635 I document the deprecation and warn of the breaking change in 6.0.0.

I suppose I need to actually mention the breaking change in 6.0.0 docs.

I'll get used to the process :-)

Awaiting for Nik's comment.

2017-03-23 12:39 UTC, nik9000 commented
Yeah, this should go in the breaking changes doc. I'm a bit ambivalent about where. I'd put it in the same section as you did for the deprecation.

2017-03-25 00:55 UTC, jasontedor commented
> Yeah, this should go in the breaking changes doc. I'm a bit ambivalent about where. I'd put it in the same section as you did for the deprecation.

There's already a REST section, and a Java section; maybe a comment in both?

2017-03-27 10:13 UTC, dimitris-athanasiou commented
@bleskes @nik9000 @jasontedor I pushed a commit where I document the breaking change in both the REST and the Java documents. Could you take another look?

2017-03-28 12:47 UTC, nik9000 approved these changes

2017-03-28 12:54 UTC, jasontedor approved these changes
LGTM.

2017-03-28 12:54 UTC, jasontedor commented on modules/reindex/src/test/resources/rest-api-spec/test/delete_by_query/20_validation.yaml
> +      reasone: exlpicit query is required since 6.0.0
There is a typo here, it should be `reason`.

2017-03-28 12:55 UTC, jasontedor commented on modules/reindex/src/test/resources/rest-api-spec/test/delete_by_query/20_validation.yaml
> +      version: "6.0.0 - "
I do not understand the skip, shouldn't it be " - 5.99.99" (or something like that)?

2017-03-28 12:56 UTC, jasontedor commented on modules/reindex/src/test/resources/rest-api-spec/test/delete_by_query/20_validation.yaml
> +      reasone: exlpicit query is required since 6.0.0
Another typo, less fatal than `reason` is `exlpicit` should be `explicit`.

2017-03-28 12:56 UTC, jasontedor requested changes
I noticed some things when giving it a final review.

2017-03-28 13:34 UTC, dimitris-athanasiou commented
@jasontedor Embarassing :-) I just pushed a fix for types + version. This time I actually run the tests.

2017-03-28 13:38 UTC, jasontedor approved these changes
LGTM.

2017-03-28 13:38 UTC, jasontedor commented
Let's let a CI run finish before merging. 😉

2017-03-28 14:44 UTC, merged