Adds tests for cardinality and filter aggregations
elastic/elasticsearch pull request #23826
Opened 2017-03-30 15:36 UTC by colings86

Relates to #22278

2017-03-31 08:31 UTC, jpountz requested changes
I left some minor comments.

2017-03-31 08:31 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/aggregations/metrics/cardinality/HyperLogLogPlusPlus.java
> +                values.add(runLens.get(i));
I think that should be s/i/(bucket << p)+i/

2017-03-31 08:31 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/aggregations/metrics/cardinality/HyperLogLogPlusPlus.java
> +                &&
weird indentation?

2017-03-31 08:31 UTC, jpountz commented on core/src/main/java/org/elasticsearch/search/aggregations/metrics/cardinality/HyperLogLogPlusPlus.java
> +        }
It seems to me that this is not needed anymore?

2017-03-31 08:31 UTC, jpountz commented on core/src/test/java/org/elasticsearch/search/aggregations/bucket/FilterAggregatorTests.java
> +                indexWriter.commit();
you can do `indexWriter.getReader().close()`, which will create a segment too but not do a fsync

2017-03-31 08:31 UTC, jpountz commented on core/src/test/java/org/elasticsearch/search/aggregations/metrics/cardinality/InternalCardinalityTests.java
> +    private static List<HyperLogLogPlusPlus> algos;
this variable never seems to be read?

2017-03-31 08:42 UTC, colings86 commented on core/src/test/java/org/elasticsearch/search/aggregations/metrics/cardinality/InternalCardinalityTests.java
> +    private static List<HyperLogLogPlusPlus> algos;
This is needed so we keep a reference to the HyperLogLogPlusPlus implementations we create in `createTestInstance()` so we can close them and release the appropriate `BigArray` pages after the test is complete.

2017-04-03 08:35 UTC, jpountz approved these changes
LGTM

2017-04-03 08:39 UTC, merged