Fix bulk queue_size and size in thread pool document
elastic/elasticsearch pull request #23870
Opened 2017-04-03 03:30 UTC by wyukawa

I check source code https://github.com/elastic/elasticsearch/blob/v5.3.0/core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L172

I conclude current document contains bugs.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2017-04-03 03:30 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-04-04 01:05 UTC, jasontedor requested changes
Thanks so much for noticing this and submitting a PR. The queue size fix for the bulk thread pool is correct, and this will need to be backported to 5.3, 5.x, and master (we can do this when we integrate, no need for a separate PR). However, the change to the default number of thread for a fixed thread pool should be reverted. After you make that correction, we can integrate.

2017-04-04 01:05 UTC, jasontedor commented on docs/reference/modules/threadpool.asciidoc
> +number of cores.
Let's revert this change, I do not think it's correct anyway any longer, there is no default for a fixed thread pool, it must be specified on construction of the thread pool and each thread pool is free to set its own default. Fixing this should be done in a separate change.

2017-04-04 02:25 UTC, wyukawa commented on docs/reference/modules/threadpool.asciidoc
> +number of cores.
Thank you for comments!

I fixed in bbdffc60a1dca67549b43a4e5052ee3d642aa1c5

2017-04-04 02:35 UTC, jasontedor approved these changes
LGTM. Thanks again for noticing this and fixing it!

2017-04-04 02:39 UTC, merged

2017-04-04 04:06 UTC, wyukawa commented
Thanks!