Removing unneeded getTook method
elastic/elasticsearch pull request #23923
Opened 2017-04-05 16:44 UTC by olcbean

According to https://github.com/elastic/elasticsearch/pull/23767/files/7b70704ab45eb3ba98e0c31ce4eb8e65dd963381#r109564828 `getTook()` methods should be removed from `BulkResponse` and `SearchResponse` as there is an alternative `getTookInMillis()` which can be used.

2017-04-05 16:44 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-05-08 09:40 UTC, javanna commented
@jasontedor are you good with this? It is a breaking change for the java api and I wonder if it is convenient for users to still retrieve the `TimeValue` from `getTook`. I am fine either way though.

2017-05-08 17:31 UTC, jasontedor commented
I think we only need to provide one of `getTook` and `getTookInMillis`; ultimately it does not matter to me which it is as it's easy to migrate from one to the other. I trust your judgement here @javanna.

2017-05-12 09:25 UTC, javanna requested changes
heya @olcbean thanks for your PR! I find it handier to return the `TimeValue`. Would you mind removing the `getTookInMillis` method instead of `getTook`?

2017-05-19 07:51 UTC, olcbean commented
Thanks for the review @javanna!

I just reintroduced the `getTook` and removed the `getTookInMillis`

2017-05-19 07:56 UTC, olcbean commented
@javanna as this is a `breaking-java` change, I guess some docs should be changed as well. Can you point me to them?

2017-05-19 08:18 UTC, javanna commented
right @olcbean could you add a note here: https://github.com/elastic/elasticsearch/blob/master/docs/reference/migration/migrate_6_0/java.asciidoc ? Thanks!

2017-05-19 10:55 UTC, olcbean commented
Thanks @javanna! I just added a note to the docs.

2017-05-26 10:21 UTC, javanna commented
jenkins test this please

2017-05-26 10:22 UTC, javanna commented
@olcbean sorry it has taken me a week to get to this, would you mind resolving the merge conflict in the migrate guide. Running tests as we speak, I should be able to merge this today.

2017-05-28 11:52 UTC, olcbean commented
@javanna just resolved the merge conflict and fixed a test.

2017-06-02 08:44 UTC, javanna approved these changes
LGTM I am going to merge this

2017-06-02 09:11 UTC, merged

2017-06-02 09:12 UTC, javanna commented
thanks @olcbean !