Wildcard cluster names for cross cluster search
elastic/elasticsearch pull request #23985
Opened 2017-04-07 22:25 UTC by tbrooks8

This is related to #23893. This commit allows users to use wilcards for
cluster names when executing a cross cluster search.

So instead of defining every cluster such as:

`GET one:*,two:*,three:*/_search`

A user could just search:

`GET *:*/_search`

As ":" characters are currently allowed in index names, if the first
text up to the first ":" does not match a defined cluster name, the
entire string is treated as an index name.

2017-04-07 22:28 UTC, tbrooks8 commented
This is an initial take at this functionality. But I wanted to create the PR early for early feedback.

As listed in this [comment](https://github.com/elastic/elasticsearch/issues/23893#issuecomment-292659956) there are still some questions to resolve.

Additionally, I have not modified the cross cluster qa tests for this functionality yet. However, I plan on doing that once my questions have been resolved.

2017-04-10 11:19 UTC, clintongormley commented
ping @javanna @s1monw @jasontedor

2017-04-10 13:43 UTC, tbrooks8 commented
The build failed because of I added a couple of lines >100. I'll fix that in the next revision or merge in the change back to 140.

2017-04-11 11:59 UTC, s1monw requested changes
Looks great, I left some comments nothing major

2017-04-11 11:59 UTC, s1monw commented on core/src/main/java/org/elasticsearch/action/search/RemoteClusterConnection.java
> +public final class RemoteClusterConnection extends AbstractComponent implements TransportConnectionListener, Closeable {
can we move this back to be package private?

2017-04-11 11:59 UTC, s1monw commented on core/src/main/java/org/elasticsearch/action/search/RemoteClusterService.java
> +                List<String> clusters = clusterNameResolver.resolveClusterNames(remoteClusterNames, remoteClusterName);
can we maybe return an emtpy list instead of null, I think we don't necessarily need the null invariant?

2017-04-11 11:59 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/metadata/ClusterNameExpressionResolver.java
> +public class ClusterNameExpressionResolver extends AbstractComponent {
can this be final?

2017-04-11 11:59 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/metadata/ClusterNameExpressionResolver.java
> +                return null;
maybe return the empty list?

2017-04-11 11:59 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/metadata/ClusterNameExpressionResolver.java
> +        new WildcardExpressionResolver();
this looks like a leftover

2017-04-11 11:59 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/metadata/ClusterNameExpressionResolver.java
> +            return null;
empty list?

2017-04-11 11:59 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/metadata/ClusterNameExpressionResolver.java
> +public class ClusterNameExpressionResolver extends AbstractComponent {
some basic javadocs for this please?

2017-04-11 11:59 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/metadata/ClusterNameExpressionResolver.java
> +    public List<String> resolveClusterNames(Set<String> remoteClusters, String clusterExpression) {
also please add some javadocs what this can resolve etc?

2017-04-11 15:43 UTC, s1monw requested changes
Left one comment LGTM otherwise

2017-04-11 15:43 UTC, s1monw commented on core/src/main/java/org/elasticsearch/action/search/RemoteClusterService.java
> +                if (clusters.isEmpty()) {
hmm this should be `cluster.isEmpty() == false`?

2017-04-11 15:48 UTC, s1monw approved these changes

2017-04-11 15:48 UTC, s1monw commented
LGTM

2017-04-11 18:56 UTC, merged