Restrict build info loading to ES jar, not any jar
elastic/elasticsearch pull request #24049
Opened 2017-04-11 18:54 UTC by rjernst

This change makes the build info initialization only try to load a jar
manifest if it is the elasticsearch jar. Anything else (eg a repackaged
ES for use of transport client in an uber jar) will contain "Unknown"
for the build info as it does for tests currently.

fixes #21955

2017-04-11 21:39 UTC, jasontedor approved these changes
The change looks good to me and I think we should get it in as soon as we can, but I would like to manually verify that this addresses the issues for deploying to an application container before this integrated and I opened #24050 so that having to do this manually is a one-time thing.

2017-04-12 03:18 UTC, jasontedor commented
So manual testing shows that we'll need a little more here. We can discuss tomorrow.

2017-04-12 06:29 UTC, jasontedor requested changes
Just one thing.

2017-04-12 06:29 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/Build.java
> +        if (urlStr.startsWith("file://") && (urlStr.endsWith(esPrefix + ".jar") || urlStr.endsWith(esPrefix + "-SNAPSHOT.jar"))) {
This isn't quite right. Wrap the ends with checks in parentheses.

2017-04-12 06:30 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/Build.java
> +        if (urlStr.startsWith("file://") && (urlStr.endsWith(esPrefix + ".jar") || urlStr.endsWith(esPrefix + "-SNAPSHOT.jar"))) {
So it's starts with and (ends with or ends with).

2017-04-12 06:31 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/Build.java
> +        if (urlStr.startsWith("file://") && (urlStr.endsWith(esPrefix + ".jar") || urlStr.endsWith(esPrefix + "-SNAPSHOT.jar"))) {
Also I think it is one slash only, annoyingly.

2017-04-12 06:44 UTC, rjernst commented on core/src/main/java/org/elasticsearch/Build.java
> +        if (urlStr.startsWith("file://") && (urlStr.endsWith(esPrefix + ".jar") || urlStr.endsWith(esPrefix + "-SNAPSHOT.jar"))) {
Not sure what you mean.

2017-04-12 06:47 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/Build.java
> +        if (urlStr.startsWith("file://") && (urlStr.endsWith(esPrefix + ".jar") || urlStr.endsWith(esPrefix + "-SNAPSHOT.jar"))) {
Oh, I misread it (mobile phone, sorry). The only thing that needs to change then is file:// -> file:/.

2017-04-12 18:51 UTC, jasontedor commented
I've tested this change by deploying a war that uses the `TransportClient` to Wildfly 10 and it's good.

2017-04-12 18:52 UTC, jasontedor approved these changes
LGTM.

2017-04-13 06:22 UTC, merged