Upgrade apache commons-logging to current version (1.1.3 -> 1.2)
elastic/elasticsearch pull request #24067
Opened 2017-04-12 15:03 UTC by pgier

This is a bug fix upgrade and removes support for very old JDK versions (<1.2).
More information here: https://commons.apache.org/proper/commons-logging/changes-report.html

2017-04-12 15:03 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-04-12 16:17 UTC, jasontedor requested changes
The Hadoop dependency definitely can not change, and I think that there is investigation needed before we can safely make the larger change.

2017-04-12 16:17 UTC, jasontedor commented on plugins/repository-hdfs/build.gradle
> +  compile 'commons-logging:commons-logging:1.2'
No we can't do this one, the version of Hadoop here depends on [1.1.3](https://github.com/apache/hadoop/blob/release-2.7.1/hadoop-project/pom.xml#L591-L610).

2017-04-12 16:17 UTC, jasontedor commented on buildSrc/version.properties
> +commonslogging    = 1.2
I think we need to look at what modules have a dependency on commonslogging and see if we can change it across the board like this. This also impacts downstream projects like plugins that rely on the version properties here in core to determine the version that they use.

2017-04-12 16:53 UTC, jasontedor commented on buildSrc/version.properties
> +commonslogging    = 1.2
I look at all the uses of commonslogging, and I think that going to 1.2 is safe here with the exception of the Hadoop change which as I mentioned must stay on 1.1.3.

2017-04-12 16:53 UTC, jasontedor commented
Can you please revert the repository-hdfs change and run `gradle updateSHAs` and push the resulting sha changes?

2017-04-12 17:05 UTC, jasontedor commented
test this please

2017-04-12 17:05 UTC, pgier commented
Thanks for the quick feedback!  I have pushed the requested changes.

2017-04-12 17:06 UTC, jasontedor commented
> Thanks for the quick feedback! I have pushed the requested changes.

You're welcome. Thanks for the PR and the quick iteration. I have asked our CI to kick of a build.

2017-04-18 03:11 UTC, jasontedor commented
I think that the transitive commons-logging dependency in repository-hdfs needs to be excluded.

2017-04-18 05:06 UTC, rjernst commented
@jasontedor I'm not sure that will work. When we moved repository-hdfs into ES, we did so adding each dependency (ie starting with excluding all transitive deps, and adding them one by one) until it worked. So I don't think simply dropping commons-logging will work.

2017-04-18 09:33 UTC, jasontedor commented
I meant the conflicting transitive dependency only but keeping the explicitly defined one.

2017-06-13 21:04 UTC, closed without merging