Detect remnants of path.data/default.path.data bug
elastic/elasticsearch pull request #24099
Opened 2017-04-14 02:43 UTC by jasontedor

In Elasticsearch 5.3.0 a bug was introduced in the merging of default settings when the target setting existed as an array. When this bug concerns path.data and default.path.data, we ended up in a situation where the paths specified in both settings would be used to write index data. Since our packaging sets default.path.data, users that configure multiple data paths via an array and use the packaging are subject to having shards land in paths in default.path.data when that is very likely not what they intended.

This commit is an attempt to rectify this situation. If path.data and default.path.data are configured, we check for the presence of indices there. If we find any, we log messages explaining the situation and fail the node.

Closes #23981, supersedes #24052, relates #24074, relates #24093

2017-04-14 06:46 UTC, s1monw requested changes
I am not sure this change is OK and I would like to discuss different solutions for this down the road. I'd like to not add the permission and find the possible issue earlier in the game. I think we can only do that if we ignore the nodeLockID which I think we should. It is an edgecase we are trying to solve. if we'd not look at that and only look if there is data in `default.path.data` we would do as good as this solution IMO but with much less trouble. I think this is over engineering we are trying to do here but I am ok with compromising on dropping the sophisticated method here in 6.0 since our recommendation is to upgrade to a latest version first before you upgrade even if it's a full cluster restart. We can still have a simpler check in 6.0 then. @rjernst WDYT can you review this as well?

2017-04-14 06:46 UTC, s1monw commented on core/src/main/java/org/elasticsearch/env/NodeEnvironment.java
> +    public int nodeLockId() {
can we call this `getNodeLockId()` pls

2017-04-14 06:46 UTC, s1monw commented on core/src/main/java/org/elasticsearch/node/Node.java
> +    static void checkForIndexDataInDefaultPathData(
you have 140 chars use them :)

2017-04-14 06:46 UTC, s1monw commented on core/src/main/java/org/elasticsearch/node/Node.java
> +        if (!Environment.PATH_DATA_SETTING.exists(settings) || !Environment.DEFAULT_PATH_DATA_SETTING.exists(settings)) return;
please wrap with `{}`

2017-04-14 06:46 UTC, s1monw commented on core/src/main/java/org/elasticsearch/node/Node.java
> +        if (clean) return;
please wrap {}

2017-04-14 06:46 UTC, s1monw commented on core/src/main/java/org/elasticsearch/node/Node.java
> +            if (!Files.exists(nodeDirectory)) continue;
please wrap in {} and use `== false`

2017-04-14 06:46 UTC, s1monw commented on core/src/main/java/org/elasticsearch/node/Node.java
> +            if (availableIndexFolders.isEmpty()) continue;
please wrap in {}

2017-04-14 11:25 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/node/Node.java
> +        if (!Environment.PATH_DATA_SETTING.exists(settings) || !Environment.DEFAULT_PATH_DATA_SETTING.exists(settings)) return;
I pushed b21702e7bff6b57733908b476b87598be0ad0164.

2017-04-14 11:25 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/node/Node.java
> +            if (!Files.exists(nodeDirectory)) continue;
I pushed b21702e7bff6b57733908b476b87598be0ad0164.

2017-04-14 11:25 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/node/Node.java
> +            if (availableIndexFolders.isEmpty()) continue;
I pushed b21702e7bff6b57733908b476b87598be0ad0164.

2017-04-14 11:26 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/node/Node.java
> +        if (clean) return;
I pushed b21702e7bff6b57733908b476b87598be0ad0164.

2017-04-14 11:26 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/node/Node.java
> +    static void checkForIndexDataInDefaultPathData(
I pushed b21702e7bff6b57733908b476b87598be0ad0164.

2017-04-14 11:27 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/env/NodeEnvironment.java
> +    public int nodeLockId() {
I pushed b21702e7bff6b57733908b476b87598be0ad0164.

2017-04-17 10:57 UTC, s1monw approved these changes

2017-04-17 10:59 UTC, s1monw commented
@jasontedor lets merge this and I will look into improving this in master. I think the solution is good enough and we should make progress over perfection

2017-04-17 11:03 UTC, merged