Adds nodes usage API to monitor usages of actions
elastic/elasticsearch pull request #24169
Opened 2017-04-18 22:39 UTC by colings86

The nodes usage API has 2 main endpoints

/_nodes/usage and /_nodes/{nodeIds}/usage return the usage statistics
for all nodes and the specified node(s) respectively.

At the moment only one type of usage statistics is available, the REST
actions usage. This records the number of times each REST action class is
called and when the nodes usage api is called will return a map of rest
action class name to long representing the number of times each of the action
classes has been called.

Still to do:

* [x] Create usage service to store usage statistics
* [x] Record usage in REST layer
* [x] Add Transport Actions
* [x] Add REST Actions
* [x] Tests
* [x] Documentation
* [ ] Check for references to statistics and replace with "feature usage"

2017-05-31 21:38 UTC, jaymode requested changes
left a few minor comments

2017-05-31 21:38 UTC, jaymode commented on core/src/main/java/org/elasticsearch/rest/BaseRestHandler.java
> +    public abstract String getName();
can you add javadocs about what the name should be

2017-05-31 21:38 UTC, jaymode commented on core/src/main/java/org/elasticsearch/rest/BaseRestHandler.java
> +    public long getUsageCount() {
maybe make this final?

2017-05-31 21:38 UTC, jaymode commented on core/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestNodesUsageAction.java
> +        if (metrics.size() == 1 && metrics.contains("_all")) {
should we handle the case where `_all` is sent with `rest_actions`?

2017-05-31 21:38 UTC, jaymode commented on core/src/main/java/org/elasticsearch/usage/UsageService.java
> +    private long sinceTime;
this can be final?

2017-06-01 10:51 UTC, colings86 commented
@jaymode thanks for reviewing, I updated the PR to address your comments

2017-06-01 13:52 UTC, jaymode approved these changes
LGTM

2017-06-02 07:46 UTC, merged