Add primary term to doc write response
elastic/elasticsearch pull request #24171
Opened 2017-04-19 03:10 UTC by jasontedor

This commit adds the primary term to the doc write response.

Relates #10708

2017-04-19 03:20 UTC, nik9000 commented on docs/reference/docs/bulk.asciidoc
> +// TESTRESPONSE[s/"took": 30/"took": $body.took/ s/"index_uuid": .../"index_uuid": $body.items.3.update.error.index_uuid/ s/"_seq_no" : 0/"_seq_no" : $body.items.0.index._seq_no/ s/"_primary_term" :
You can stick these onto separate lines if you like.

2017-04-19 04:09 UTC, jasontedor commented on docs/reference/docs/bulk.asciidoc
> +// TESTRESPONSE[s/"took": 30/"took": $body.took/ s/"index_uuid": .../"index_uuid": $body.items.3.update.error.index_uuid/ s/"_seq_no" : 0/"_seq_no" : $body.items.0.index._seq_no/ s/"_primary_term" :
I pushed 4c6b35cfb9c9db9de962013cf036f8e6f9056a1c.

2017-04-19 08:21 UTC, bleskes requested changes
Looks good - I left one comment about the Engine related classes.

2017-04-19 08:21 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/engine/Engine.java
> +            this(operationType, null, version, seqNo, primaryTerm);
I'm on sure about this one - the semantics we currently have is that Result represents everything that the engine decides. The primary term is part of the operation - I'm not sure we need this here?

2017-04-19 08:21 UTC, bleskes commented on docs/reference/docs/bulk.asciidoc
> +// TESTRESPONSE[s/"took": 30/"took": $body.took/]
good to know this is possible

2017-04-19 14:35 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/engine/Engine.java
> +            this(operationType, null, version, seqNo, primaryTerm);
I think you mean d4bbfcde9713a234d2e82d6ac5dba97ab696adf9?

2017-04-19 15:33 UTC, bleskes approved these changes

2017-04-19 18:31 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +                        ex, plan.versionOfDeletion, plan.seqNoOfDeletion, plan.currentlyDeleted == false);
@bleskes By the way, I think this was a bug, maybe there's a test case missing here?

2017-04-19 18:32 UTC, jasontedor commented on docs/reference/docs/bulk.asciidoc
> +// TESTRESPONSE[s/"took": 30/"took": $body.took/]
Yes, I didn't know it was until @nik9000 made the suggestion and so I went and read the source to understand the syntax behind it.

2017-04-19 18:44 UTC, merged

2017-04-19 18:44 UTC, jasontedor commented
Thanks @nik9000 and @bleskes.

2017-04-20 12:10 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +                        ex, plan.versionOfDeletion, plan.seqNoOfDeletion, plan.currentlyDeleted == false);
@areek I think that the tests in https://github.com/elastic/elasticsearch/pull/23314 don't cover the delete case (but only indexing). Can you look at this?

2017-04-20 15:05 UTC, areek commented on core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +                        ex, plan.versionOfDeletion, plan.seqNoOfDeletion, plan.currentlyDeleted == false);
@bleskes thanks for the ping, I am working on adding tests for the delete case

2017-04-20 17:48 UTC, areek commented on core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +                        ex, plan.versionOfDeletion, plan.seqNoOfDeletion, plan.currentlyDeleted == false);
I added tests for this https://github.com/elastic/elasticsearch/commit/077a6c3ee7ffe0a1b5b4ea7718adf0429409171a