Fix/24233
elastic/elasticsearch pull request #24242
Opened 2017-04-21 11:58 UTC by glefloch

Allow passing a single scroll id as string instead of array.

Close #24233

2017-04-21 11:58 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-04-21 12:17 UTC, bleskes commented
thx @glefloch . 

@jimczi do you mind taking a look?

2017-04-21 13:50 UTC, jimczi reviewed
Looks great. Thanks @glefloch 
Can you also update the docs to use the new accepted format when possible (example how to clear a single scroll id):
https://github.com/elastic/elasticsearch/blob/master/docs/reference/search/request/scroll.asciidoc

2017-04-21 14:19 UTC, glefloch commented
Yes for sure, I'm going to do that.

2017-04-21 15:13 UTC, jimczi commented
jenkins please test this

2017-04-21 18:48 UTC, jimczi requested changes
It's very close, thanks @glefloch 
The rest tests are failing due to BWC reason. I left a comment that explain how to fix it.

2017-04-21 18:48 UTC, jimczi commented on rest-api-spec/src/main/resources/rest-api-spec/test/scroll/11_clear.yaml
> +"Body params with string param scroll id override query string":
This test fails the backward compatibility check with 5.x. Can you add a skip section like in https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/test/indices.exists_template/10_basic.yaml that will disable the BWC test for this. I'll reenable them when this is back-ported to 5.x.

2017-04-24 11:02 UTC, jimczi commented
jenkins please test this

2017-04-25 11:41 UTC, jimczi approved these changes

2017-04-25 11:43 UTC, merged

2017-04-25 12:24 UTC, jimczi commented
Thanks @glefloch, this is merged to master and cherry-picked to the 5.x branch.