Provide informative error message in case of unknown suggestion context.
elastic/elasticsearch pull request #24241
Opened 2017-04-21 11:21 UTC by nilabhsagar

At present providing unknown context in a suggestion context query does not provide informative error message.
Consider below mapping and correspongding query

**Mapping**

```
{
    "mappings": {
        "products" : {
            "properties" : {
                "suggest" : {
                    "type" : "completion",
                    "contexts": [
                        { 
                            "name": "product_type",
                            "type": "category",
                            "path": "cat"
                        },
                        { 
                            "name": "product_color",
                            "type": "category",
                            "path": "cat"
                        },
                        { 
                            "name": "product_size",
                            "type": "category",
                            "path": "cat"
                        }
                    ]
                }
            }
        }
    }
}
```

**Query**

```
{
    "suggest": {
        "products_suggestion" : {
            "prefix" : "sho",
            "completion" : {
                "field" : "suggest",
                "size": 10,
                "contexts": {
                    "product_type": "casual",
                    "product_brand": "reebok"
                }
            }
        }
    }
}
```
Executing the above query will show error message as below

"Unknown context name[product_brand], must be one of 3"

This error message is not very informative as it only convey the number of context supported. However printing all the accepted contexts will be more informative, like below:

"Unknown context name[product_brand], must be one of [product_size, product_color, product_type]"

This pull request fixes the issue mentioned.

2017-04-21 11:21 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-04-21 14:58 UTC, nik9000 requested changes
I left a minor thing but it makes sense to me. If you'll make the change I can see about merging.

2017-04-21 14:58 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/search/suggest/completion/context/ContextMappings.java
> +            throw new IllegalArgumentException("Unknown context name[" + name + "], must be one of " + contextNameMap.keySet().toString());
I think we'd better sort the list of keys before adding it to the string so we get consistent error messages. This'll make testing much easier and be marginally easier on the eyes.

2017-04-21 14:58 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/search/suggest/completion/context/ContextMappings.java
> +            throw new IllegalArgumentException("Unknown context name[" + name + "], must be one of " + contextNameMap.keySet().toString());
Can you add a space between "name" and "["?

2017-04-21 15:38 UTC, nilabhsagar commented
Thanks @nik9000 I agree, sorting will have consistent behaviour. I will do both the changes as suggested and commit.

2017-04-21 17:00 UTC, nilabhsagar commented
@nik9000 changes done. Please verify

2017-04-24 13:08 UTC, nik9000 approved these changes
Looks good to me. I'll work on getting this merged.

2017-04-24 13:08 UTC, nik9000 commented
elasticmachine, test this please.

2017-04-24 14:35 UTC, merged

2017-04-24 14:38 UTC, nik9000 commented
Thanks @nilabhsagar! I've merged to master and an backporting to 5.x.

2017-04-24 14:41 UTC, nilabhsagar commented
Thanks @nik9000!