added validation for upserd request
elastic/elasticsearch pull request #24282
Opened 2017-04-24 10:09 UTC by kunal642

related to #16671

2017-04-24 10:09 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-04-25 10:58 UTC, kunal642 commented
Can someone please review this

2017-04-25 16:19 UTC, nik9000 requested changes

2017-04-25 16:19 UTC, nik9000 commented on core/src/test/java/org/elasticsearch/action/update/UpdateRequestTests.java
> +            "can't provide both upsert request and a version","type is missing","id is missing","script or doc is missing"));
Can you set the missing things so they don't throw as well?

2017-04-25 16:24 UTC, nik9000 commented
I think it is worth also writing a test for bulk requests.  They can attempt to set the version on an upsert request.

2017-04-25 16:53 UTC, kunal642 commented
@nik9000 the requested changes have been done

2017-04-25 16:55 UTC, nik9000 requested changes

2017-04-25 16:55 UTC, nik9000 commented on core/src/test/java/org/elasticsearch/action/bulk/BulkRequestTests.java
> +        BulkRequest bulkRequest = new BulkRequest();
I meant a test that uses the bulk request's overrides in `BulkRequest#add`. That way we are testing a way of "sneaking" the version into the request that is unique to bulk requests.

2017-04-26 05:58 UTC, kunal642 commented
@nik9000 changed the test case

2017-04-26 21:31 UTC, nik9000 commented
> @nik9000 changed the test case

Thanks! I've spent all day merging things and haven't gotten around to looking at this yet. I promise I'll get to it soon!

2017-04-26 21:32 UTC, nik9000 approved these changes
Actually, I did get a chance to look at it. That is perfect. I'll have a look at merging tomorrow.

2017-04-27 18:22 UTC, nik9000 requested changes
I hate to do this after approving the change but running `gradle check` caught this:
https://github.com/elastic/elasticsearch/blob/master/core/src/test/java/org/elasticsearch/update/UpdateIT.java#L535-L543

That test is now out of date. Can you remove it entirely with your PR?

You might have to merge master into your PR if you ran tests locally and didn't catch it. It is what I did before running the tests.

2017-04-27 18:31 UTC, kunal642 commented
@nik9000 i dont know how i missed it
Ill remove the marked test case

2017-04-27 19:33 UTC, kunal642 commented
@nik9000 i tried running gradle test and all the test suites related to plugins are failing.

2017-04-27 19:40 UTC, nik9000 commented
@kunal642 to be honest I never got that far. `gradle check` stopped me in core before I got to plugins.

2017-04-27 19:43 UTC, kunal642 commented
@nik9000 should i push??

2017-04-27 19:45 UTC, nik9000 commented
> @nik9000 should i push??

Sure! If you push what you have I can have a look at the failure and advise from there.

2017-04-27 19:52 UTC, kunal642 commented
@nik9000 please have a look

2017-04-27 20:19 UTC, nik9000 commented
So far all the tests seem fine to me....

2017-04-27 20:43 UTC, kunal642 commented
Thats great
I guess there is some problem in my repo

When i normally run the test cases they give me jar hell exception
In debug mode they run fine

Gradle check stalls the test cases for seconds and gives timeout exception after a while

2017-04-28 12:00 UTC, nik9000 approved these changes

2017-04-28 12:02 UTC, merged

2017-05-02 10:52 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-05-02 14:17 UTC, nik9000 commented
@elasticmachine, this PR is merged.