Fixes restore of a shrunken index when initial recovery node is gone
elastic/elasticsearch pull request #24322
Opened 2017-04-25 21:18 UTC by abeyad

When an index is shrunk using the shrink APIs, the shrink operation adds
some internal index settings to the shrink index, for example
`index.shrink.source.name|uuid` to denote the source index, as well as
`index.routing.allocation.initial_recovery._id` to denote the node on
which all shards for the source index resided when the shrunken index
was created.  However, this presents a problem when taking a snapshot of
the shrunken index and restoring it to a cluster where the initial
recovery node is not present, or restoring to the same cluster where the
initial recovery node is offline or decommissioned.  The restore
operation fails to allocate the shard in the shrunken index to a node
when the initial recovery node is not present, and a restore type of
recovery will *not* go through the PrimaryShardAllocator, meaning that
it will not have the chance to force allocate the primary to a node in
the cluster.  Rather, restore initiated shard allocation goes through
the BalancedShardAllocator which does not attempt to force allocate a
primary.

This commit fixes the aforementioned problem by not requiring allocation
to occur on the initial recovery node when the recovery type is a
restore of a snapshot.  This commit also ensures that the internal
shrink index settings are recognized and not archived (which can trip an
assertion in the restore scenario).

Closes #24257

2017-04-25 21:18 UTC, abeyad commented on core/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java
> -    private boolean snapshotIsDone(String repository, String snapshot) {
removing dead code here

2017-04-26 09:14 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/routing/RecoverySource.java
> +    private static EnumSet<RecoverySource.Type> INITIAL_RECOVERY_TYPES = EnumSet.of(Type.EMPTY_STORE, Type.LOCAL_SHARDS);
@ywelsch can you look at this one please

2017-04-26 09:22 UTC, s1monw approved these changes
I left some comments but LGTM I want @ywelsch  to look at it as well

2017-04-26 09:22 UTC, s1monw commented on core/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
> +                if (key.startsWith(IndexMetaData.INDEX_ROUTING_INITIAL_RECOVERY_GROUP_SETTING.getKey())) {
maybe use `return IndexMetaData.INDEX_ROUTING_INITIAL_RECOVERY_GROUP_SETTING.getRawKey().match(key)`

2017-04-26 09:22 UTC, s1monw commented on core/src/main/java/org/elasticsearch/cluster/routing/RecoverySource.java
> +    private static EnumSet<RecoverySource.Type> INITIAL_RECOVERY_TYPES = EnumSet.of(Type.EMPTY_STORE, Type.LOCAL_SHARDS);
@abeyad leave a comment why we dont' have snapshot in here?

2017-04-26 10:08 UTC, ywelsch requested changes
I've left a comment about the change of INITIAL_RECOVERY_TYPES. I am also debating whether a better solution would be to keep the definition as is but to automatically remove the `initial_recoveries` settings during restore (see `ignoreSettings` in `RestoreService.updateIndexSettings`).

2017-04-26 14:58 UTC, abeyad commented
@s1monw @ywelsch I pushed a6d83302d71e9e769ad4830725902b1f84f3f85b to address the feedback.

2017-04-26 17:26 UTC, ywelsch approved these changes
LGTM

2017-04-26 17:26 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDecider.java
> +    public static EnumSet<RecoverySource.Type> INITIAL_RECOVERY_TYPES =
no need to make this public; package-visible is good enough.

2017-04-26 17:30 UTC, abeyad commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDecider.java
> +    public static EnumSet<RecoverySource.Type> INITIAL_RECOVERY_TYPES =
the problem is that `FilterAllocationDeciderTests` is not part of the same package, and moving it to the same package as `FilterAllocationDecider` breaks package visibility on the `AllocationService#reroute` protected method that the test depends on.

2017-04-26 17:33 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDecider.java
> +    public static EnumSet<RecoverySource.Type> INITIAL_RECOVERY_TYPES =
just use the public one with one less parameter...

2017-04-26 17:39 UTC, abeyad commented
@ywelsch I pushed 6ad6dea0039b2a91b78b6df23407042ad8acb04c

2017-04-26 18:48 UTC, merged

2017-04-26 20:20 UTC, abeyad commented
5.x commit: 30ed3baf58936e1de8db7fda7568cd7b3f645db0
5.4 commit: 4d7aaf4179251b20df502096516d626b7add39cf

2017-04-26 20:20 UTC, abeyad commented
thanks for the review @ywelsch @s1monw