Block global checkpoint advances when recovering
elastic/elasticsearch pull request #24404
Opened 2017-04-29 11:52 UTC by jasontedor

After a replica shard finishes recovery, it will be marked as active and its local checkpoint will be considered in the calculation of the global checkpoint on the primary. If there were operations in flight during recovery, when the replica is activated its local checkpoint could be lagging behind the global checkpoint on the primary. This means that when the replica shard is activated, we can end up in a situtaion where a global checkpoint update would want to move the global checkpoint backwards, violating an invariant of the system. This only arises if a background global checkpoint sync executes, which today is only a scheduled operation and might be delayed until the in-flight operations complete and the replica catches up to the primary. Yet, we are going to move to inlining global checkpoints which cause this issue to be more likely to manifest. Additionally, the global checkpoint on the replica, which is the local knowledge on the replica updated under the mandate of the primary, could be higher than the local checkpoint on the replica, again violating an invariant of the system. This commit addresses these issues by blocking global checkpoint on the primary when a replica shard is finalizing recovery. While we have blocked global checkpoint advancement, recovery on the replica shard will not be considered complete until its local checkpoint advances to the blocked global checkpoint.

Relates #10708

2017-05-02 08:30 UTC, ywelsch requested changes
I've left smaller comments and questions and will reach out to discuss them. Note that CI seems to have found an issue.

2017-05-02 17:05 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +        this.wait(TimeUnit.SECONDS.toMillis(30));
That's an artifact of testing, I will remove.

2017-05-02 17:25 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/shard/IndexShard.java
> +            assert state() == IndexShardState.RECOVERING;
I agree, I will add a detailed comment and tighten the assertion.

2017-05-02 17:25 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +     * This map holds the last known local checkpoint for initializing shards that is undergoing recovery. Such shards do not participate
I will fix this grammar issue.

2017-05-02 18:19 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +                final long current = trackingLocalCheckpoints.get(allocationId);
I don't think that we can make any assertions here, we would have to push too much knowledge down and I don't think it's worth it. I can leave a comment explaining the situation though.

2017-05-02 19:29 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +                    inSyncLocalCheckpoints.put(allocationId, current);
I pushed 6ac2706c140960964b06d4377ceeb203025fb256.

2017-05-02 19:29 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +                final long current = trackingLocalCheckpoints.get(allocationId);
I pushed c028510a73836ed03b3198fd541c73560cb653f7.

2017-05-02 19:30 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +     * This map holds the last known local checkpoint for initializing shards that is undergoing recovery. Such shards do not participate
I pushed b6a9ce6ff5c2a8b7d177faf1928f2ebd6cc23080.

2017-05-02 19:30 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/shard/IndexShard.java
> +            assert state() == IndexShardState.RECOVERING;
I pushed 10c0f3c718c7e46c3dc7fde5e57222f60d4dcc32.

2017-05-02 19:30 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +        this.wait(TimeUnit.SECONDS.toMillis(30));
I pushed 162d8e71844f63b892be55422cad71b14a9f5bf0.

2017-05-02 19:31 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +        if (trackingLocalCheckpoints.containsKey(allocationId) == false) {
I pushed 6ac2706c140960964b06d4377ceeb203025fb256.

2017-05-02 19:37 UTC, jasontedor commented
> Note that CI seems to have found an issue.

I'm not sure what this is, there's insufficient logging to understand the issue. The logs shows this:

```
1> [2017-05-01T17:28:10,739][INFO ][o.e.i.r.IndexRecoveryIT  ] --> bump replica count
  1> [2017-05-01T17:28:10,739][INFO ][o.e.c.m.MetaDataUpdateSettingsService] [node_t0] updating number_of_replicas to [1] for indices [test-idx-1]
  1> [2017-05-01T17:28:10,958][INFO ][o.e.c.r.a.AllocationService] [node_t0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test-idx-1][0]] ...]).
```

at which point the test teardown executes from a tripped assertion:

```
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <0>
   >      but: was <1>
   > 	at __randomizedtesting.SeedInfo.seed([1B2956BE26BD615E:B682E5EA13E5031C]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.indices.recovery.IndexRecoveryIT.testRerouteRecovery(IndexRecoveryIT.java:370)
   > 	at java.lang.Thread.run(Thread.java:745)
```

This is asserting that the recovery stats show there are no targets. Given that we got to green (so the recovery had to have finished), and we previously successfully asserted that the recovery state is done, it's not clear how this tripped with there being a recovery target still. I run this 256 times and then 512 times on my CI and it never reproduced. It's also unclear to me how this PR could have impacted this?

I wonder if we can proceed and if CI finds an issue increase the logging, and if it gets noisy silence the test?

2017-05-02 19:37 UTC, jasontedor commented
@ywelsch I've responded to your feedback.

2017-05-03 08:45 UTC, ywelsch approved these changes
LGTM. On to the next one :-)

2017-05-03 10:48 UTC, merged

2017-05-03 10:48 UTC, jasontedor commented
Thanks @ywelsch.