Concattenating empty strings for the purpose of getting a string representation has poor performance. Replacing where necessary.
elastic/elasticsearch pull request #24411
Opened 2017-05-01 01:33 UTC by KoenDG

This very small PR is related to issue #24226 it is small exactly to keep it readable.

There is a single file with a large diff in this PR. I'm going to assume that Intellij did this in order to enforce the `.editorconfig` settings, which it picks up on automatically.

The file in question has a lot of trailing whitespace, which has now been removed, It seems this is not picked up by checkstyle. So if this isn't an issue, I'll revert those changes and focus only on the string concatenation.

As the title states, this PR is about code that does `field + ""` in order to get a string representation of said field. This was only necessary before Java 1.5 if I recall correctly.

Also, situations where primitive types are concatenated with an empty string have been replaced since this is not as performant as calling `String.valueOf()` on the field.

===========

1. Contributor agreement: Has been signed

2. Contributor guidelines: I have read them.

3. Gradle check: build successful.

4. PR is against master

5. The PR is not OS specific.

6. I'm not part of a class.

2017-05-01 01:33 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-05-01 01:34 UTC, KoenDG commented on modules/lang-painless/src/main/java/org/elasticsearch/painless/DefMath.java
> +            return String.valueOf(left) + right;
This is the actual change in the file with all the trailing whitespace.

2017-05-01 01:59 UTC, jasontedor commented on modules/lang-painless/src/main/java/org/elasticsearch/painless/DefMath.java
> +            return String.valueOf(left) + right;
Please revert all other changes in this file.

2017-05-01 10:53 UTC, KoenDG commented on modules/lang-painless/src/main/java/org/elasticsearch/painless/DefMath.java
> +            return String.valueOf(left) + right;
Done.

2017-05-01 11:17 UTC, jasontedor requested changes
Looks good, I left two suggestions.

2017-05-01 11:17 UTC, jasontedor commented on modules/lang-painless/src/main/java/org/elasticsearch/painless/DefMath.java
> +            return String.valueOf(left) + right;
I think I'd prefer to see this written as:

```
if (left instanceof String) {
    return (String) left + right;
} else if (right instanceof String) {
    return left + (String) right;
} else if (left instanceof Number) {
.
.
.
```

2017-05-01 11:17 UTC, jasontedor commented on modules/lang-painless/src/main/java/org/elasticsearch/painless/node/EBinary.java
> +                constant = String.valueOf(left.constant) + right.constant;
We know these are not null from the outer if-block; so:

```
constant = left.constant.toString() + right.constant.toString();
```

2017-05-01 20:58 UTC, KoenDG commented on modules/lang-painless/src/main/java/org/elasticsearch/painless/node/EBinary.java
> +                constant = String.valueOf(left.constant) + right.constant;
Both changes have been implemented.

2017-05-02 01:57 UTC, jasontedor commented
test this please

2017-05-05 17:46 UTC, KoenDG commented
Is this okay to merge?

2017-05-05 17:48 UTC, jasontedor commented
Can you merge master into this branch, push here, and we will fire off another CI run?

2017-05-05 17:52 UTC, KoenDG commented
@jasontedor done

2017-05-05 17:56 UTC, jasontedor commented
retest this please

2017-05-06 04:26 UTC, jasontedor approved these changes
LGTM.

2017-05-06 04:28 UTC, merged