Add new ip_range field type
elastic/elasticsearch pull request #24433
Opened 2017-05-02 15:07 UTC by nknize

This commit adds support for indexing and searching the new `ip_range` field type. Both IPv4 and IPv6 formats are supported and tests are updated.

TODO:

* update docs
* add tests for CIDR masks?

2017-05-03 12:54 UTC, jpountz requested changes
I left some minor comments but the change looks good to me overall.

2017-05-03 12:54 UTC, jpountz commented on core/src/main/java/org/elasticsearch/index/mapper/RangeFieldMapper.java
> +                throws IOException {
can you indent so that the throws is not indented at the same level as the content of the block? (similar issues on the below lines)

2017-05-03 12:54 UTC, jpountz commented on core/src/main/java/org/elasticsearch/index/mapper/RangeFieldMapper.java
> +                    return value instanceof InetAddress ? (InetAddress) value : InetAddress.getByName((String) value);
can you use `InetAddresses.forString` intead, which guarantees it won't do a dns lookup

2017-05-03 12:54 UTC, jpountz commented on core/src/test/java/org/elasticsearch/index/mapper/RangeFieldMapperTests.java
> +            strVal = "/192.168.1.7:/2001:db8:0:0:0:0:0:0";
I guess we get this by doing a toString on an InetAddress. Could you make sure we use `InetAddresses.toAddrString` instead?

2017-05-03 20:47 UTC, nknize commented
Thanks for the excellent feedback @jpountz. I made the changes and will go ahead and merge tomorrow unless you have any other concerns.

2017-05-04 08:06 UTC, jpountz approved these changes

2017-05-05 14:54 UTC, nknize commented
merged in 0c4eb0a02940139ca26ccc45523c03ba26c7d75b

2017-05-05 14:54 UTC, closed without merging