Make class level fields static where applicable
elastic/elasticsearch pull request #24525
Opened 2017-05-05 23:57 UTC by KoenDG

This very small PR is related to issue #24226 it is small exactly to keep it readable.

A field may be static if it is declared final, and is initialized with a constant, bringing a small performance gain.

===========

1. Contributor agreement: Has been signed

2. Contributor guidelines: I have read them.

3. Gradle check: build successful.

4. PR is against master

5. The PR is not OS specific.

6. I'm not part of a class.

2017-05-05 23:57 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-05-06 00:53 UTC, nik9000 requested changes
I believe all of these are constants. Can you change them to CONSTANT_CASE while you are making them static?

2017-05-06 14:18 UTC, KoenDG commented
@nik9000 Done as requested.

2017-05-06 14:20 UTC, jasontedor requested changes
I noticed one thing, it was probably a typo.

2017-05-06 14:20 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java
> +        private static final long MAX_NUMBER_THREADS_THRESHOLD = 1 << 12;
Please add the word "of" back.

2017-05-06 14:24 UTC, KoenDG commented
@jasontedor fixed.

2017-05-10 22:25 UTC, KoenDG commented
Master has been pushed into this branch again. Please advise further actions.

2017-05-12 02:44 UTC, merged