Add parsing for String/Long/Double Terms aggregations
elastic/elasticsearch pull request #24521
Opened 2017-05-05 20:45 UTC by tlrx

This pull request adds parsing methods for Long/Double/String terms aggregations

2017-05-08 12:09 UTC, javanna requested changes
left a few minor comments, LGTM otherwise

2017-05-08 12:09 UTC, javanna commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/ParsedTerms.java
> +    private void setSumOtherDocCount(long sumOtherDocCount) {
nit: maybe we can get rid of private setters and just set the field values where we need to set them?

2017-05-08 12:09 UTC, javanna commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/ParsedStringTerms.java
> +            return DocValueFormat.RAW.format((BytesRef) super.getKey());
remove DocValueFormat dep here too?

2017-05-08 12:09 UTC, javanna commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/ParsedLongTerms.java
> +            return DocValueFormat.RAW.format((Long) getKey());
also remove DocValueFormat usage here too?

2017-05-09 13:05 UTC, tlrx commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/ParsedLongTerms.java
> +            return DocValueFormat.RAW.format((Long) getKey());
> this casting is rather annoying. but I guess we can't do much about it as MultiBucketsAggregation.Bucket has getKey return an Object.

It also annoyed @cbuescher when he reviewed the parsing PR about histograms. I think I can remove the generic type and get rid of the casting at once, I'll do that.

2017-05-09 13:06 UTC, tlrx commented
Thanks @javanna for your review. I updated the code according to your comments. Can you please have another look?

2017-05-09 13:16 UTC, tlrx commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/ParsedTerms.java
> +        return buckets.stream().map(bucket -> (Terms.Bucket) bucket).collect(Collectors.toList());
Yes, by adding a generic type to ParsedMultiBucketAggregation

2017-05-09 13:20 UTC, javanna approved these changes
looks great @tlrx thanks a lot!

2017-05-09 13:20 UTC, javanna commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/ParsedDateHistogram.java
> +            if (key != null){
missing whitespace after the parentheses :)

2017-05-09 15:33 UTC, cbuescher approved these changes
@tlrx thanks, after looking at this I think I start to understand the structure of how we parse multi bucket aggregations a lot better. Given the already complicated inheritance structure of the aggregations & buckets it looks great in using what we already have.

2017-05-09 15:33 UTC, cbuescher commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/ParsedTerms.java
> +                    aggregations.add(XContentParserUtils.parseTypedKeysObject(parser, Aggregation.TYPED_KEYS_DELIMITER, Aggregation.class));
Side note: we talked about this earlier, if we encounter a "type#name" combination here where "type" isn't registered we will throw an exception, there is no way to ignore this at the moment. I don't know if we should add that option to `parseTypedKeysObject` and also to `parser#namedObject` 
This has nothing to do with this PR.

2017-05-10 08:12 UTC, tlrx commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/ParsedTerms.java
> +                    aggregations.add(XContentParserUtils.parseTypedKeysObject(parser, Aggregation.TYPED_KEYS_DELIMITER, Aggregation.class));
I think it's good thing that an exception is thrown. Handling uneregistered aggregation types is like handling unknown fields - for now we throw exceptions. If we want to manage those then I agree we will add to change the behavior of parseTypedKeysObject.

2017-05-10 08:17 UTC, merged

2017-05-10 08:17 UTC, tlrx commented
Thanks @javanna @cbuescher !