Deprecate Fine Grain Settings for Scripts
elastic/elasticsearch pull request #24573
Opened 2017-05-09 22:52 UTC by jdconrad

As the title says.  Will be replaced with the settings defined in #24532 in the next PR.

2017-05-09 22:59 UTC, rjernst requested changes
Looks good, but I think this is still missing deprecation on the `langAndTypeSetting` in ScriptSettings?

2017-05-09 22:59 UTC, rjernst commented on core/src/test/java/org/elasticsearch/script/ScriptModesTests.java
> +    private static Setting<?>[] buildDeprecatedSettingsArray(ScriptSettings scriptSettings, String... keys) {
This seems to be common, maybe just put it under one test class as public static?

2017-05-09 23:06 UTC, jdconrad commented on core/src/test/java/org/elasticsearch/script/ScriptModesTests.java
> +    private static Setting<?>[] buildDeprecatedSettingsArray(ScriptSettings scriptSettings, String... keys) {
Do you have a class you prefer considering all of these inherit from ESTestCase which didn't seem appropriate?

2017-05-09 23:06 UTC, jdconrad commented
@rjernst Thought langAndTypeSettng was done at line 110.  Did I miss a different place?

2017-05-09 23:18 UTC, rjernst commented
What about line 94?

2017-05-09 23:51 UTC, jdconrad commented on core/src/test/java/org/elasticsearch/script/ScriptModesTests.java
> +    private static Setting<?>[] buildDeprecatedSettingsArray(ScriptSettings scriptSettings, String... keys) {
Moved to ScriptSettingsTests

2017-05-09 23:51 UTC, jdconrad commented
Think I found them all.

2017-05-09 23:59 UTC, rjernst approved these changes
Thanks! LGTM

2017-05-10 15:52 UTC, jdconrad commented
@elasticmachine please test this

2017-05-10 20:09 UTC, merged

2017-05-10 20:09 UTC, jdconrad commented
@rjernst Thanks for the review!