Add parsing methods to Range aggregations
elastic/elasticsearch pull request #24583
Opened 2017-05-10 13:31 UTC by tlrx

This pull request adds the parsing logic to InternalRange, InternalDateRange and InternalGeoDistance aggregations.

2017-05-10 16:05 UTC, javanna approved these changes
LGTM

2017-05-10 16:05 UTC, javanna commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/range/ParsedRange.java
> +            if (!Double.isInfinite(to)) {
nit: == false?

2017-05-11 11:14 UTC, cbuescher requested changes
Looks good, but I found two edge cases around the range to/from value that might not be covered by tests yet and that might not be working as expected yet. Not entirely sure, but maybe worth taking another close look.

2017-05-11 11:14 UTC, cbuescher commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/range/ParsedRange.java
> +        protected double from;
This should probably be initialized to Double.NEGATIVE_INFINITY. If `InternalRange.from` is infinite, the "from" field won't be rendered in the xContent and I think the current parser would leave from == 0 in this case. Maybe we should also add tests for those edge cases.

2017-05-11 11:14 UTC, cbuescher commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/range/ParsedRange.java
> +        protected double to;
Same here but with Double.POSITIVE_INFINITY?

2017-05-12 14:27 UTC, tlrx commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/range/ParsedRange.java
> +        protected double from;
That's right, thanks! I added some random ranges with infinity values to the test.

2017-05-12 14:28 UTC, tlrx commented
@cbuescher I updated the code. Can you please have another look? Thanks

2017-05-12 14:34 UTC, cbuescher approved these changes
LGTM

2017-05-12 14:52 UTC, merged

2017-05-12 14:53 UTC, tlrx commented
Thanks @cbuescher @javanna