Deprecated use of + in index names
elastic/elasticsearch pull request #24585
Opened 2017-05-10 13:45 UTC by kunal642

Closes #24515

2017-05-11 13:34 UTC, kunal642 commented
@javanna Can you please have a look

2017-05-12 10:20 UTC, javanna requested changes
hi @kunal642 thanks a lot for your PR, I left a couple of comments.

2017-05-12 10:20 UTC, javanna commented on core/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java
> +              new DeprecationLogger(Loggers.getLogger(IndexNameExpressionResolver.class))
any reason why the deprecation logger is created on demand each time rather than a static field?

2017-05-12 10:20 UTC, javanna commented on core/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java
> +        assertWarnings("use of + is deprecated in index names as it is implicit");
can you add a specific test method that checks the new deprecation line and remove usages of '+' elsewhere?

2017-05-12 10:20 UTC, javanna commented on core/src/test/java/org/elasticsearch/cluster/metadata/WildcardExpressionResolverTests.java
> +        assertWarnings("use of + is deprecated in index names as it is implicit");
here as well, can you add a specific test method that checks the new deprecation line and remove usages of '+' elsewhere?

2017-05-12 10:53 UTC, kunal642 commented
@javanna Requested changes have been done. Please verify

2017-05-12 12:59 UTC, javanna requested changes
thanks, I did another round and left a couple more comments

2017-05-12 12:59 UTC, javanna commented on core/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java
>          assertThat(indexNameExpressionResolver.isPatternMatchingAllIndices(metaData, indicesOrAliases, concreteIndices), equalTo(true));
I think the tests that you deleted around '+' should be added back as a separate method. You did that for wildcard expressions but not for concrete names.

2017-05-12 12:59 UTC, javanna commented on core/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java
> +            if(isDeprecated) {
could you please add a whitespace after the `if` (before the parentheses)?

2017-05-12 12:59 UTC, javanna commented on core/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java
> +            boolean isDeprecated = false;
can you call it `plusSeen`?

2017-05-12 12:59 UTC, javanna commented on core/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java
> +              DEPRECATION_LOGGER.deprecated("use of + is deprecated in index names as it is implicit");
change the message to "Support for '+' as part of index expressions is deprecated" ?

2017-05-13 07:59 UTC, kunal642 commented
@javanna Please review again. Changes have been made

2017-05-14 19:28 UTC, javanna requested changes
I left a few very minor comments, LGTM otherwise. Thanks @kunal642

2017-05-14 19:28 UTC, javanna commented on core/src/test/java/org/elasticsearch/cluster/metadata/WildcardExpressionResolverTests.java
> +    }
do you have indentation at 2 chars  only for this method? We use 4 chars in our codebase. I'd appreciate if you could change that.

2017-05-14 19:28 UTC, javanna commented on core/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java
> +      }
can you fix the indentation for this curly bracket?

2017-05-14 19:28 UTC, javanna commented on core/src/test/java/org/elasticsearch/cluster/metadata/WildcardExpressionResolverTests.java
> +    public void testForDeprecatedWildCard() {
it is not the wildcard that's deprecated, rather the '+' . Could you rename this method accordingly please?

2017-05-14 19:28 UTC, javanna commented on core/src/test/java/org/elasticsearch/cluster/metadata/WildcardExpressionResolverTests.java
> +      assertThat(newHashSet(resolver.resolve(context, Arrays.asList("+test*"))), equalTo(newHashSet("test", "test1")));
nit: can you also add here the same few tests that you had above, which combined the use of '+' with other names in the same expression

2017-05-14 19:28 UTC, javanna commented on core/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java
> +    public void testConcreteIndicesForDeprecatedPattern() {
could you slightly expand this test by adding the different combinations that we used to have above? This is just to make sure that everything still works properly.

2017-05-14 19:30 UTC, javanna commented
jenkins test this please

2017-05-15 06:58 UTC, kunal642 commented
@javanna Done. Please review

2017-05-15 09:25 UTC, javanna approved these changes
LGTM thanks @kunal642 I am going to merge this.

2017-05-15 09:26 UTC, merged

2017-05-15 09:27 UTC, kunal642 commented
@javanna Great, Thanks for your help

2017-05-15 09:31 UTC, javanna commented
@kunal642 do you want to send a new PR for removing this in master?

2017-05-15 09:36 UTC, kunal642 commented
@javanna removing the support for + in index names??

2017-05-15 09:37 UTC, javanna commented
@kunal642 yep.

2017-05-15 09:38 UTC, kunal642 commented
@javanna yeah sure
but why didn't we remove it all together in the master

2017-05-15 09:39 UTC, javanna commented
@kunal642 because we tend to deprecate things first and your PR was against master in the first place. I am currently backporting the change to 5.x branch/ We can now either leave it deprecated in master for a while and remove it later, or already remove it (in master only).

2017-05-15 09:40 UTC, kunal642 commented
@javanna okay
ill make another PR for removing this

2017-05-15 11:05 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-05-15 11:24 UTC, kunal642 commented
@javanna After removing support for +, the index names with +test should not return any index name
right??

2017-05-15 11:36 UTC, javanna commented
@kunal642 right, as index names cannot start with '+'. As part of index resolution, '+' prefixes should just stay untouched. Then depending on the indices option (whether ignore_unavailable is set to true or false), we throw exception or ignore the fact that such an index didn't exist.