Scripting: Remove file scripts
elastic/elasticsearch pull request #24627
Opened 2017-05-11 17:43 UTC by rjernst

This commit removes file scripts, which were deprecated in 5.5.

closes #21798

2017-05-11 18:43 UTC, jasontedor requested changes
I left some comments, nothing major.

2017-05-11 18:43 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/script/ScriptServiceTests.java
>              // only file scripts are accepted by default
This comment can go.

2017-05-11 18:43 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/script/ScriptServiceTests.java
>              //Otherwise they are always considered file ones as they can be found in the static cache.
These comments about file scripts can go.

2017-05-11 18:43 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/script/ScriptServiceTests.java
>                  Boolean scriptEnabled = engineSettings.get(dangerousScriptEngine.getType() + "." + scriptType + "." + scriptContext.getKey());
It won't let me review line 278 where there is still an assertion about file scripts.

2017-05-11 18:43 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/script/ScriptServiceTests.java
>      private static final Map<ScriptType, Boolean> DEFAULT_SCRIPT_ENABLED = new HashMap<>();
There's a field up there `scriptsFilePath` that I think can go?

2017-05-11 18:43 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/script/ScriptServiceTests.java
> -    private ResourceWatcherService resourceWatcherService;
There are imports up above that can be removed.

2017-05-11 18:43 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/script/ScriptServiceTests.java
>              deprecate = true;
I think this can go?

2017-05-11 19:14 UTC, jasontedor commented
Also, I *think* there are some packaging tests that set up a file script?

2017-05-11 20:37 UTC, rjernst commented
@elasticmachine retest this please

2017-05-16 08:07 UTC, rjernst commented
@jasontedor Packaging tests are updated.

2017-05-17 20:26 UTC, jasontedor approved these changes
LGTM.

2017-05-17 21:42 UTC, merged