SniffNodesSampler should close connection after handling responses
elastic/elasticsearch pull request #24632
Opened 2017-05-11 20:53 UTC by tlrx

With the current implementation, `SniffNodesSampler` might close the
current connection right after a request is sent but before the response
is correctly handled. This causes to timeouts in the transport client
when the sniffing is activated in all versions since #22828.

closes #24575
closes #24557

2017-05-11 20:56 UTC, tlrx commented
@bleskes @jasontedor the PR does not have tests, I created it to point it to you what _I think_ is the cause of #24575 (and also the deleted #24557). I'd be happy if you could confirm or invalidate that this is the cause of transport client exceptions.

2017-05-12 06:04 UTC, s1monw requested changes
the fix looks good to me, left some comments. good catch.

2017-05-12 06:04 UTC, s1monw commented on core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java
> -                            IOUtils.closeWhileHandlingException(connectionToClose);
we also need to close the connection in `public void onFailure(Exception e) {` since we might get rejected or something like this.

2017-05-12 06:04 UTC, s1monw commented on client/transport/src/main/resources/log4j2.properties
> +appender.console.type = Console
this is unrelated?

2017-05-12 06:04 UTC, s1monw commented on client/transport/src/main/java/TestClient.java
> +public class TestClient {
this is unrelated?

2017-05-12 06:04 UTC, s1monw commented on core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java
> +                                    }
testing will be tricky but doable. I have some ideas here similar to what I did on `RemoteClusterConnectionTests` where we basically mock the calls to clusterstate and return a pre-build state but we can also put some sleeps into it.

2017-05-12 06:10 UTC, s1monw commented
one thing that I am puzzled about is why this causes timeouts instead of triggering onException on the handler? I think the reason is that we don't notify the TransportService when a connection is closed but only if a node is disconnected that is a different bug here. Both are independent and should be handled independently. so I think your fix is sufficient for the issues referenced in the description.

2017-05-12 07:16 UTC, s1monw commented
I opened #24639 for the notification part

2017-05-12 07:28 UTC, s1monw commented
I also marked this as a blocker for 5.4.1

2017-05-12 09:44 UTC, bleskes approved these changes
Great catch. LGTM (although I left one suggestion).

2017-05-12 09:44 UTC, bleskes commented on core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java
> +                                        closeConnection();
maybe we should unify the `latch.countDown()` and `closeConnection()` into a single method called "onDone" on the AbstractRunnable that everyone calls? this it's less trappy and people wouldn't forget to do one but not the other.

2017-05-12 12:46 UTC, tlrx commented on core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java
> +                                    }
I wrote a test which would have failed before the fix. That would be great if you can have a look.

2017-05-12 12:46 UTC, tlrx commented on client/transport/src/main/java/TestClient.java
> +public class TestClient {
Yes, this should not have been commited, thanks.

2017-05-12 12:49 UTC, tlrx commented
> one thing that I am puzzled about is why this causes timeouts instead of triggering onException on the handler? I think the reason is that we don't notify the TransportService when a connection is closed but only if a node is disconnected that is a different bug here. Both are independent and should be handled independently. so I think your fix is sufficient for the issues referenced in the description.

I agree - I didn't spot this problem but my knowledge of the TransportService is limited, I'm glad you already proposed a fix.

I updated the PR according to your comments.

2017-05-12 12:57 UTC, s1monw approved these changes
LGTM 2 thx for the test

2017-05-12 14:27 UTC, s1monw commented on core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java
>                              IOUtils.closeWhileHandlingException(connectionToClose);
can we call the latch in a finally block just to be absolutely sure

2017-05-12 14:28 UTC, tlrx commented on core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java
>                              IOUtils.closeWhileHandlingException(connectionToClose);
Sure

2017-05-12 14:38 UTC, merged

2017-05-12 14:39 UTC, tlrx commented
Thanks @s1monw @bleskes

2017-06-07 02:39 UTC, konste commented
I'm getting exactly this error with the version 5.4.1 across the board. What's the quickest way for me to recover?

2017-06-07 07:00 UTC, tlrx commented
@konste I just ran another test this morning with a fresh 5.4.1 installation and a PreBuiltTransportClient with sniff option set to true and everything worked as expected (while the error was really obvious and appears at startup time).

Can you please provide the logs of both transport client and elasticsearch node please? As well as the transport client settings?

2017-06-07 14:52 UTC, konste commented
@tlrx Sorry I had to restore functionality ASAP and lost the repro.