Part 2 of reviewing all list constructors and adding a size where possible.
elastic/elasticsearch pull request #24656
Opened 2017-05-13 11:08 UTC by KoenDG

This very small PR is related to issue #24226 it is small exactly to keep it readable.

This is part 2, follow-up to part 1, which can be found here: #24439

I'd like to point out that `Iterable<T>` doesn't have a `size()` method.

And these are the remaining PRs I still have open: #24533 and #24340

===========

1. Contributor agreement: Has been signed

2. Contributor guidelines: I have read them.

3. Gradle check: build successful.

4. PR is against master

5. The PR is not OS specific.

6. I'm not part of a class.

2017-05-13 11:08 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-05-14 20:42 UTC, jasontedor requested changes
I left some changes.

2017-05-14 20:42 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/plugins/PluginsService.java
> +        List<PluginInfo> pluginsList = new ArrayList<>(classpathPlugins.size());
These aren't right, we load more than just classpath plugins, it's not worth jumping through hoops trying to size them correctly, this code is executed exactly once in the life of an Elasticsearch server or transport client instance. Let's revert this change.

2017-05-14 20:42 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/fielddata/plain/ParentChildIndexFieldData.java
> +            List<Releasable> closeables = new ArrayList<>(atomicFD.size());
This one is not right, it's flattening a bunch of collections, please revert.

2017-05-14 20:42 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/common/hppc/HppcMapsTests.java
> +import java.util.Collection;
This is not needed, please revert.

2017-05-14 20:42 UTC, jasontedor commented on test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java
> +        List<InternalAggregation> toReduce = new ArrayList<>(toReduceSize);
This one is not right, sometimes a random reduce is added, let's add one more here to `toReduceSize`.

2017-05-14 23:18 UTC, jasontedor commented on test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java
> +        List<InternalAggregation> toReduce = new ArrayList<>(toReduceSize);
And to be clear, I mean shifting the random decision up here and sizing based on the outcome.

2017-05-14 23:38 UTC, KoenDG commented
Changes implemented as requested.

2017-05-14 23:39 UTC, jasontedor commented on test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java
> +        List<InternalAggregation> toReduce = new ArrayList<>(toReduceSize);
Note the extra reduce is added only if we are doing an extra reduce, and toReduce is greater than one.

2017-05-15 08:44 UTC, KoenDG commented on test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java
> +        List<InternalAggregation> toReduce = new ArrayList<>(toReduceSize);
Right, my bad, added it in.

2017-08-15 20:09 UTC, dakrone commented
@koendg this needs to have master merged and the conflicts addressed and then ping Jason for another review

2017-08-15 20:11 UTC, jasontedor commented
We are not going to pull this one in.

2017-08-15 20:11 UTC, closed without merging