Allow removing multiple fields in ingest processor
elastic/elasticsearch pull request #24750
Opened 2017-05-17 18:38 UTC by glefloch

Remove processor is now able to handle an array. The parameter name is still `field`. Should we rename it to `fields` ? And deprecates the name `field` in `5.x` branch? 

Close #24622

2017-05-17 18:38 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-05-24 12:20 UTC, clintongormley commented
@glefloch we tend to use the singular even when the parameter accepts multiple values, eg `index` instead of `indices`

2017-06-05 20:30 UTC, talevy requested changes
thanks for the PR, overall looks like what we want!

left a few comments, let me know what you think!

2017-06-05 20:30 UTC, talevy commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/IngestCommonPlugin.java
> +        processors.put(RemoveProcessor.TYPE, new RemoveProcessor.Factory());
it would be best to leave templatable field values, since that was the previously supported behavior

2017-06-05 20:30 UTC, talevy commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/RemoveProcessor.java
> +            List<String> fields = ConfigurationUtils.readList(TYPE, processorTag, config, "field");
I think it would be nice to support both singular strings *and* lists. what do you think? Will also help with backwards compatibility

2017-06-06 07:08 UTC, glefloch commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/RemoveProcessor.java
> +            List<String> fields = ConfigurationUtils.readList(TYPE, processorTag, config, "field");
Yes, you right, this would be better.

2017-06-06 19:43 UTC, glefloch commented
@talevy, I pushed `6e4150d` to fix your comment. Could you review it?

2017-06-06 19:54 UTC, talevy reviewed
nice! overall looks good. just a few comments, let me know what you think

2017-06-06 19:54 UTC, talevy commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/RemoveProcessor.java
> +    public List<TemplateService.Template> getField() {
getFields*

2017-06-06 19:54 UTC, talevy commented on modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/RemoveProcessorFactoryTests.java
> +         RemoveProcessor.Factory factory = new RemoveProcessor.Factory(TestTemplateService.instance(true));
nitpick: why the extra space?

2017-06-06 19:55 UTC, talevy commented
jenkins, test this please

2017-06-06 20:08 UTC, glefloch commented
you are right, I fixed those issues ;)

2017-06-06 20:09 UTC, talevy commented
jenkins, test this please

2017-06-07 14:44 UTC, glefloch commented
@talevy, It seems that errors occured on `:qa:backwards-5.0:integTestRunner` but the reason why it went wrong is not clear to me. Could you have a look please?

2017-06-07 17:11 UTC, talevy commented
@glefloch, we just updated our versions across `master` and `5.x` for a release. could be the reason. I will kick it off again

2017-06-07 17:11 UTC, talevy commented
jenkins, test this please

2017-06-07 18:46 UTC, talevy commented
hmm. do you mind rebasing off latest `master`? not entirely sure why it is failing on the versioned tests

2017-06-08 18:41 UTC, glefloch commented
I merge master in my branch. Could you restart test? Thanks

2017-06-08 18:43 UTC, talevy commented
thanks!

jenkins, test this please

2017-06-08 20:15 UTC, talevy approved these changes

2017-06-08 20:17 UTC, talevy commented
@glefloch thank you for following up with this PR! looks good. I'll go ahead and merge this into `master`(6.0) and `5.x`(5.6)

2017-06-08 20:17 UTC, merged