Fix indentation for mem_limit
elastic/elasticsearch pull request #24765
Opened 2017-05-18 08:01 UTC by indigo423

When running the docker-compose example the following error is shown:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.elasticsearch1: 'mem_limit'.
```

The fix sets the `mem_limi` option below the `ulimits`.

2017-05-18 08:01 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-08-15 20:10 UTC, dakrone commented
@dliappis can you please review/merge this?

2017-08-17 15:20 UTC, dliappis requested changes
All the tests I did and documentation I can find about docker-compose v2 format support that the indentation is correct as it is. I left a comment with details.

2017-08-17 15:20 UTC, dliappis commented on docs/reference/setup/install/docker.asciidoc
> +      mem_limit: 1g
`mem_limit` is not a ulimit in the [docker-compose v2 format](https://docs.docker.com/compose/compose-file/compose-file-v2/#ulimits) so it shouldn't be a key inside the `ulimit:` hash.

Instead [it needs to be specified](https://docs.docker.com/compose/compose-file/compose-file-v2/#mem_limit) at the same indentation level as image, ulimit etc. as  it currently is.

I just freshly copied/pasted the [docker-compose.yml](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) from [the elastic.co website](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) and it worked fine with docker-compose 1.13.0.

Testing should be done by inspecting `/sys/fs/cgroup/memory/memory.limit_in_bytes`, e.g. I defined 3g in my `docker-compose.yml` and see:

```
$ docker exec -u root -ti elasticsearch1 bash -c 'cat /sys/fs/cgroup/memory/memory.limit_in_bytes'
3221225472
```

Moving the indentation to the right, as in your PR, causes `mem_limit` not be honored and the container receives the cgroup default (which is unlimited).

What is your `docker-compose` version?

2017-10-10 16:23 UTC, jasontedor commented
No further feedback, closing.

2017-10-10 16:23 UTC, closed without merging