GET _tasks/taskId:1 doesn't work to get task info
elastic/elasticsearch pull request #24801
Opened 2017-05-19 14:41 UTC by AshishAAB

The proposed API doesn't work.
Instead, the one suggested in the Tasks API page works.
Like GET _tasks/node_id:task_id works.
Similarly for cancelling and re-throttling

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2017-05-19 14:41 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-05-19 14:54 UTC, nik9000 requested changes
I don't think this is going to work properly with `gradle docs:check`. If you added `// TEST[s/:taskId/1/]` below each of them then `gradle docs:check` should work.

2017-05-23 11:34 UTC, AshishAAB reviewed
Added // TEST[s/:taskId/1/] in the required places as suggested

2017-05-23 16:32 UTC, nik9000 requested changes
This doesn't pass `gradle docs:check`. I think my regex replacement wasn't quite right. Sorry! Can you debug it?

2017-08-15 20:11 UTC, dakrone commented
@AshishAAB are you still interested in pursuing this PR? Can you make the corrections so that `gradle docs:check` passes?

2017-11-06 17:11 UTC, javanna commented
test this please

2018-03-20 12:24 UTC, bleskes commented
There hasn't been any activity here for a while. Closing this PR...

2018-03-20 12:24 UTC, closed without merging