Add typeless APIs to `Get` `Index` and `Bulk`
elastic/elasticsearch pull request #24843
Opened 2017-05-23 13:59 UTC by s1monw

This commit adds `GET|PUT /{index}/_doc/{id}` and relatives to
index, bulk and get. This is a step towards removing types from elasticsearch.
This change adds a default `doc` type as the type for requests against typeless
APIs. In the future we might improve this by dyncamically detecting the type
in the mapping if there is one already.
This chance also doesn't cut over existing rest tests to ensure tests work for
our BWC tests. Once this is backported to 5.5 we can cut over rest tests to use
the typeless API as well as adding deprecation headers to the typed APIs.

Relates to #24592
Relates to #15613

2017-05-23 14:07 UTC, clintongormley requested changes
looks good, but we're missing the rest handler and tests for the `_create`  endpoint I think?

2017-05-23 14:07 UTC, clintongormley commented on core/src/main/java/org/elasticsearch/rest/action/document/RestIndexAction.java
> +        controller.registerHandler(POST, "/{index}_doc", new DocTypeRestHandler(settings, this::prepareRequest)); // auto id creation
Missing `/` in `/{index}_doc`

2017-05-23 14:07 UTC, clintongormley commented on core/src/main/java/org/elasticsearch/rest/action/document/RestIndexAction.java
>      }
Aren't we missing `PUT|POST /{index}/_doc/{id}/_create`?

2017-05-23 14:08 UTC, s1monw commented on core/src/main/java/org/elasticsearch/rest/action/document/RestIndexAction.java
>      }
I missed to push a commit - this is incomplete

2017-05-23 14:08 UTC, s1monw commented
> looks good, but we're missing the rest handler and tests for the _create endpoint I think?

what is this create thing? can't folks use a opt_type?

2017-05-23 14:15 UTC, clintongormley commented
> what is this create thing? can't folks use a opt_type?

The `_create` end point has been there since 0.early.  using an `op_type` is an option, but requires custom handling in the clients, which is why we added the `create.json` rest spec:

https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/create.json

2017-05-23 14:16 UTC, s1monw commented
clients.... zzzz.... :)

2017-05-23 14:19 UTC, s1monw commented
@clintongormley I pushed a new commit

2017-05-23 14:25 UTC, clintongormley approved these changes
Thanks Simon.  LGTM

2017-05-23 19:48 UTC, jpountz approved these changes
LGTM!

2017-05-23 20:35 UTC, nik9000 approved these changes

2017-05-23 20:35 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java
> +    public static String DEFAULT_DOC_TYPE = "doc";
Probably worth javadoc.

2017-05-23 20:35 UTC, nik9000 commented on rest-api-spec/src/main/resources/rest-api-spec/test/bulk/60_without_type.yml
> +"Array of objects without type":
I think this is missing a `skip`.

2017-05-24 14:10 UTC, s1monw commented
closing unmerged see https://github.com/elastic/elasticsearch/issues/15613#issuecomment-303727982

2017-05-24 14:10 UTC, closed without merging