Prevent Index & Delete request primaryTerm getter/setter, setShardId setter
elastic/elasticsearch pull request #24908
Opened 2017-05-26 15:58 UTC by dakrone

2017-05-26 16:16 UTC, jasontedor requested changes
I left some comments. Also can you provide a PR description/commit message that motivates what is going on here.

2017-05-26 16:16 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/action/delete/DeleteRequest.java
> +    // *should* be set.
Please promote these to legitimate Javadocs on each method so they show up in IDEs, etc.

2017-05-26 16:16 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/action/delete/DeleteRequest.java
> +        throw new UnsupportedOperationException("primary should never be set on DeleteRequest");
Missing "term"?

2017-05-26 16:33 UTC, dakrone commented
@jasontedor sure, updated the PR with a description and a commit.

2017-05-26 17:08 UTC, jasontedor requested changes
You're missing "term".

2017-05-26 17:08 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/action/delete/DeleteRequest.java
> +        throw new UnsupportedOperationException("primary should never be set on DeleteRequest");
Sorry, I wasn't explicit, but you're missing "term" everywhere except for the ones that you just fixed.

2017-05-30 14:06 UTC, jasontedor approved these changes
LGTM.

2017-05-30 14:56 UTC, merged