24217 rollover max docs
elastic/elasticsearch pull request #24977
Opened 2017-05-31 06:41 UTC by fred84

max_doc condition for index rollover should use document count only from primary shards (#24217).

2017-05-31 06:41 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-05-31 06:45 UTC, karmi commented
Hi @fred84, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/24977.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

2017-05-31 06:54 UTC, bleskes requested changes
Thank you for the PR. The change looks good but I would love to move the test to be a unit test. I left a suggestion on how to do it.

2017-05-31 06:54 UTC, bleskes commented on rest-api-spec/src/main/resources/rest-api-spec/test/indices.rollover/20_max_doc_condition.yml
> +        wait_for_active_shards: all
I would much prefer it if you add a unit test in TransportRolloverActionTests instead. The REST yaml tests are there to make sure we pass requests and read responses correctly but it has a big overhead to test simple inner behavior with it. To do so you can add an overload of evaluateConditions that takes IndicesStatsResponse and translates it to a call to an evaluateConditions which gets the number of docs (it seems that's the only stats we use in [here](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java#L197)

2017-05-31 07:02 UTC, fred84 commented on rest-api-spec/src/main/resources/rest-api-spec/test/indices.rollover/20_max_doc_condition.yml
> +        wait_for_active_shards: all
Thanks for suggestion. I'll create unit test. Should I keep yaml test?

2017-05-31 07:10 UTC, fred84 commented
@karmi I have used incorrect email in commit. Should I create new PR?

2017-05-31 08:44 UTC, s1monw commented on rest-api-spec/src/main/resources/rest-api-spec/test/indices.rollover/20_max_doc_condition.yml
> +        wait_for_active_shards: all
yeah please keep it

2017-05-31 08:46 UTC, s1monw commented
> @karmi I have used incorrect email in commit. Should I create new PR?

@fred84 you can change you setting for git and then rebase the PR and force push to you branch that should fix it?

2017-06-01 13:16 UTC, fred84 commented on rest-api-spec/src/main/resources/rest-api-spec/test/indices.rollover/20_max_doc_condition.yml
> +        wait_for_active_shards: all
@bleskes I added 2 more tests to TransportRolloverActionTests

2017-06-06 10:04 UTC, bleskes requested changes
Thank you @fred84! I think we are moving in the right direction. I would like to suggest another simplifications. We already have a fairly extended test to test the condition logic (`testEvaluateConditions`). We don't really need to duplicate the testing logic in it. I think we need to test here is only the conversion between `IndicesStatsResponse` and the `DocStats` used for the conditions. We can do so, using the new method you added, by adding a single test call `testDocStatsSelection` (or something like) that has a single custom condition when asserts that the numbers you got are what you expect. You can then randomize the stats in a `IndicesStatsResponse` and use the custom condition to assert that the right ones (i.e., the primaries) have been passed into it.

2017-06-07 08:53 UTC, fred84 commented
Thanks for suggestions, @bleskes. I updated the PR. The only thing I disagree that we need randomize stats in test. "testDocStatsSelectionFromPrimariesOnly" tests only that right value passed from IndicesStatResponse to Condition. There is no manipulation with this value inside "evaluateConditions".

2017-06-07 09:09 UTC, s1monw commented
@elasticmachine ok to test

2017-06-07 10:38 UTC, karmi commented
@fred84, sorry, I've missed your notification, I can see the CLA check is green now, @s1monw's advice was spot on, thanks for updating the e-mail!

2017-06-07 12:03 UTC, s1monw commented
I see this in the build logs:

```
{p0=indices.rollover/20_max_doc_condition/Rollover conditions matched with replica node}]: after test
  1> [2017-06-07T03:35:53,692][INFO ][o.e.t.r.IntegTestZipClientYamlTestSuiteIT] Stash dump on failure [{
  1>   "stash" : {
  1>     "body" : null
  1>   }
  1> }]
ERROR   30.0s | IntegTestZipClientYamlTestSuiteIT.test {p0=indices.rollover/20_max_doc_condition/Rollover conditions matched with replica node} <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: Failure at [indices.rollover/20_max_doc_condition:4]: listener timeout after waiting for [30000] ms
   > 	at __randomizedtesting.SeedInfo.seed([856786C5C842552:800247B6F27848AA]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:346)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:328)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.io.IOException: listener timeout after waiting for [30000] ms
   > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:660)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:219)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:191)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestClient.callApi(ClientYamlTestClient.java:169)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApiInternal(ClientYamlTestExecutionContext.java:157)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApi(ClientYamlTestExecutionContext.java:89)
   > 	at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:221)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:344)
   > 	... 37 more```

@fred84 can you take a look at it?

2017-06-07 12:19 UTC, bleskes commented
The rest test are run (sometimes) against a 1 node cluster. This means that replicas won't always be assigned. This `wait_for_active_shards: all` condition in the rest test makes it fail. I suggest just removing it. We also probably don't need explicit setting replicas to 1. Better leave to the default imo.

2017-06-07 15:01 UTC, fred84 commented
@bleskes @s1monw This yml test make no sense when running without replica (and will fail anyway with different number of shards/replicas). Is it possible to run it on specific number of shards/replicas? Or better remove this test?

2017-06-08 08:24 UTC, s1monw commented
> @bleskes @s1monw This yml test make no sense when running without replica (and will fail anyway with different number of shards/replicas). Is it possible to run it on specific number of shards/replicas? Or better remove this test?

we run test with one node and with multiple nodes I think your test will be fine it should just use defaults and remove the `wait_for_active_shards: all` condition to make sure it also passes in a single node enviroment

2017-06-08 08:30 UTC, bleskes commented
> This yml test make no sense when running without replica

I agree it will be great if we can pin down the test to always fail without your fix. Sadly this is not possible today. Doing it like we suggested means it will fail *sometimes* (if the replicas were fast enough to allocate). That's better than nothing.

> (and will fail anyway with different number of shards/replicas)

I'm not sure I follow this one. can you clarify?

2017-06-08 16:28 UTC, fred84 commented
@bleskes 
>
> > (and will fail anyway with different number of shards/replicas)
>
> I'm not sure I follow this one. can you clarify?

Test had checks for docs count in both "total" and "primaries": 
```yml 
- match:    { _all.primaries.docs.count: 1 }
- match:    { _all.total.docs.count: 2 } 
```
It was done to explicitly demonstrate that condition will be applied only after primaries reach max_docs.

> The rest test are run (sometimes) against a 1 node cluster. This means that replicas won't always be assigned. This wait_for_active_shards: all condition in the rest test makes it fail. I suggest just removing it. We also probably don't need explicit setting replicas to 1. Better leave to the default imo.

> we run test with one node and with multiple nodes I think your test will be fine it should just use defaults and remove the wait_for_active_shards: all condition to make sure it also passes in a single node enviroment

@s1monw @bleskes Thanks for suggestions!

2017-06-09 06:36 UTC, fred84 commented
":distribution:integ-test-zip:integTest" now works fine, but ":qa:mixed-cluster:integTest" fails most of the times locally. I will try to figure it out.

2017-06-11 06:49 UTC, fred84 commented
@bleskes I currently added "skip before 5.6.1 version" in yml to pass mixed cluster test, but I'm not sure that it is proper version.

2017-06-13 12:25 UTC, bleskes approved these changes

2017-06-13 12:25 UTC, bleskes commented
@fred84 that makes sense for now, I'll fix it later based on how we decide to backport this. Thanks for all the itertations

2017-06-13 12:30 UTC, merged