Refactor TransportShardBulkAction.executeUpdateRequest and add tests
elastic/elasticsearch pull request #24973
Opened 2017-05-30 21:37 UTC by dakrone

This splits `executeUpdateRequest` into separate parts and adds some unit tests
for the behavior in it. The actual behavior has not been changed.

2017-06-05 03:08 UTC, gustavobustos commented on core/src/test/java/org/elasticsearch/action/bulk/TransportShardBulkActionTests.java
> +    public void testProcessUpdateResponse() throws Exception {
Add Javadocs to the test method

2017-06-05 03:08 UTC, gustavobustos commented on core/src/test/java/org/elasticsearch/action/bulk/TransportShardBulkActionTests.java
> +    public void testExecuteUpdateRequestOnceWithFailure() throws Exception {
Add javadocs

2017-06-05 09:06 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/action/bulk/TransportShardBulkActionTests.java
> +    public void testProcessUpdateResponse() throws Exception {
It's a test method which does not need Javadocs as it's not part of a public API. Sometimes we add explanatory comments to non-straightforward tests but this is not such a test.

2017-06-05 09:07 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/action/bulk/TransportShardBulkActionTests.java
> +    public void testExecuteUpdateRequestOnceWithFailure() throws Exception {
See previous comment.

2017-06-06 16:39 UTC, bleskes requested changes
I went through this and left some very minor comments. I think there is a lot we should do here (but not sure exactly what yet), but this is a step in the right direction. Thanks for doing this @dakrone

2017-06-06 16:39 UTC, bleskes commented on core/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java
> +        BulkItemRequest originalReplicaRequest = request.items()[requestIndex];
can we call this primaryItemRequest? It's the one that's sent to the primary. Also, if we pass it as a `BulkItemRequest` parameter, we can avoid sending `requestIndex` and `BulkShardRequest` (from which need the concreteIndex, which I think we can from the shard). Last can we assert that the `BulkItemRequest` has as a request object the `updateRequest` we got? this is all super trappy but we can take one step at a time :)

2017-06-06 16:39 UTC, bleskes commented on core/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java
> +            BulkItemRequest replicaRequest = new BulkItemRequest(bulkReqId, updateDeleteRequest);
I think we can share this line and the return new BulkItemRequest line? these two clauses will need to set a final `updateResponse` field.

2017-06-06 16:39 UTC, bleskes commented on core/src/test/java/org/elasticsearch/action/bulk/TransportShardBulkActionTests.java
> +        // Assert that the document actually made it there
comment needs fixing no?

2017-06-06 16:39 UTC, bleskes commented on core/src/test/java/org/elasticsearch/action/bulk/TransportShardBulkActionTests.java
> +    private static class FakeUpdateHelper extends UpdateHelper {
nit: call this mock?

2017-06-08 17:26 UTC, dakrone commented on core/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java
> +        for (int attemptCount = 1; attemptCount <= maxAttempts; attemptCount++) {
It was purely for `null` avoidance. I will change it to

```java
private static BulkItemResultHolder executeUpdateRequest(UpdateRequest updateRequest, IndexShard primary,
                                                         IndexMetaData metaData, BulkShardRequest request,
                                                         int requestIndex, UpdateHelper updateHelper,
                                                         LongSupplier nowInMillis,
                                                         final MappingUpdatePerformer mappingUpdater) throws Exception {
    BulkItemResultHolder holder = null;
    int maxAttempts = updateRequest.retryOnConflict();
    // There must be at least one attempt
    maxAttempts = maxAttempts <= 0 ? 1 : maxAttempts;
    for (int attemptCount = 0; attemptCount < maxAttempts; attemptCount++) {

        holder = executeUpdateRequestOnce(updateRequest, primary, metaData, request,
                requestIndex, updateHelper, nowInMillis, mappingUpdater);

        // It was either a successful request, or it was a non-conflict failure
        if (holder.isVersionConflict() == false) {
            return holder;
        }
    }
    // We ran out of tries and haven't returned a valid bulk item response, so return the last one generated
    return holder;
}
```

2017-06-08 20:12 UTC, dakrone commented
Thanks for taking a look @bleskes, I pushed commits addressing your feedback

2017-06-08 22:41 UTC, dakrone commented
retest this please

2017-06-14 12:40 UTC, bleskes approved these changes
LGTM. Thx @dakrone

2017-06-14 12:40 UTC, bleskes commented on core/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java
> +        maxAttempts = maxAttempts <= 0 ? 1 : maxAttempts;
Math.min(1, maxAttempts)?

2017-06-14 15:40 UTC, dakrone commented
Thanks for the review @bleskes!

2017-06-14 15:40 UTC, merged