Update tika version
elastic/elasticsearch pull request #25003
Opened 2017-06-01 14:06 UTC by glefloch

Close #24969

2017-06-01 14:07 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-06-01 14:18 UTC, jasontedor requested changes
I don't think this will pass `gradle precommit`, let alone `gradle check`.

2017-06-01 14:18 UTC, jasontedor commented on plugins/ingest-attachment/build.gradle
> +  'tika': '1.15',
There's more that will be needed than this, for example, updating the SHAs. Did you run `gradle check`?

2017-06-07 14:25 UTC, glefloch commented
You were right, I ran checks, everything looks good. 
In this updates, for the issue [2212](https://issues.apache.org/jira/browse/TIKA-2212) they removed the mediatype `x-tika-ooxml` in order to be more specific and add some new media type. I excluded media type in reference with visio in order to keeps things working as before ( #22077). But there still is new Mej uded into `x-tika-ooxml` before like:

 * model/vnd.dwfx+xps
 * application/vnd.ms-powerpoint.slide.macroenabled.12
 * application/vnd.ms-powerpoint.template.macroenabled.12
 * application/vnd.openxmlformats-officedocument.presentationml.slide

Should I exclude them as well?

2017-06-30 14:04 UTC, dadoonet approved these changes
The change looks OK. That said I know 1.15.1 will be released soonish as per https://twitter.com/_tallison/status/880140793553596418. Should we wait a bit? @jasontedor WDYT?

2017-07-01 01:20 UTC, jasontedor commented
@dadoonet I think if this build is green we should get this in as-is. I know how release processes go, we could be waiting some uncertain period. A bird in the hand is worth two in the bush.

2017-07-01 01:21 UTC, jasontedor commented
test this please

2017-07-01 03:28 UTC, jasontedor commented
retest this please

2017-07-01 12:25 UTC, glefloch commented
@jasontedor, would you like me to merge `master` in my branch to fix the build issue?

2017-07-01 12:29 UTC, jasontedor commented
Yes, please do.

2017-08-15 20:55 UTC, dakrone commented
@jasontedor I think since this has had master merged it's ready to be merged, is there any other review you want? (you're still marked as requesting changes which is why I pinged you)

2017-08-15 21:02 UTC, jasontedor commented
test this please

2017-08-16 12:51 UTC, jasontedor commented
retest this please

2017-08-16 15:19 UTC, dadoonet reviewed
I wonder if this is working when Tesseract is installed on the same platform. I read somewhere that Tika now runs OCR by default from 1.15 and I'm pretty sure we need to disable it.
I can't check now as I'm on holidays and AFK. :)

But I prefer saying now if anyone would like to check before I'm back.

2017-10-10 16:53 UTC, rjernst commented
@elasticmachine test this please

2017-11-03 10:43 UTC, dadoonet commented
I ran a manual test with Tesseract installed locally and the current patch passed the integration tests.

2017-11-03 10:50 UTC, dadoonet commented
@jasontedor WDYT? 

Should we merge it as is or update this branch to 1.16 first?

2017-11-09 04:25 UTC, jasontedor commented
We should merge this as-is (assuming CI is green)

2017-11-09 04:25 UTC, jasontedor commented
retest this please

2017-11-09 12:03 UTC, jasontedor commented
retest this please

2017-11-09 18:13 UTC, jasontedor approved these changes
LGTM.

2017-11-09 18:16 UTC, merged

2017-11-09 18:19 UTC, jasontedor commented
I have integrated this into 5.6, 6.x, and master. This still needs to be merged into 6.0 after GA.

2017-11-13 13:38 UTC, tlrx commented
@jasontedor I pushed https://github.com/elastic/elasticsearch/commit/91a23de55e0d85f131e0609a7ea075d77313a931 to fix a version number issue in the packaging tests. Please don't forget to backport this commit when backporting your change in 6.0.