Fix GeoDistance Ordinal for BWC
elastic/elasticsearch pull request #25033
Opened 2017-06-02 19:01 UTC by nknize

`GeoDistance` enum ordinals from 5.3.3+ are not backwards compatible with earlier client versions.. This PR adds backward compatibilty support in `GeoDistance` serialization.

closes #24816

2017-06-05 07:19 UTC, jpountz requested changes
The change looks good but I think we need to fix the write side too.

2017-06-05 07:19 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java
> +
Can you also fix the write side so that if the client is on 5.4 while the cluster is on 5.3 then things would still work?

2017-06-05 07:30 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java
> +        if (clientVersion.before(Version.V_5_3_3)) {
we should update version labels on #19846?

2017-06-06 18:27 UTC, nknize commented on core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java
> +
absolutely! Good catch @jpountz made the fix.

2017-06-07 07:40 UTC, jpountz approved these changes
Looks good, can you just add the comments and test I mentioned before merging?

2017-06-07 07:40 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java
> +                case 0:
can you add a comment saying it is the ordinal of `PLANE`

2017-06-07 07:40 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java
> +                    out.write(0);
same here

2017-06-07 07:40 UTC, jpountz commented on core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java
> +                    out.write(2);
can you comment those are the ordinals of `ARC` in both cases?

2017-06-07 07:40 UTC, jpountz commented on core/src/test/java/org/elasticsearch/common/geo/GeoDistanceTests.java
> +    }
quickly test writeTo too?

2017-06-09 20:26 UTC, merged