add refresh stats tracking for realtime get
elastic/elasticsearch pull request #25052
Opened 2017-06-05 09:23 UTC by PnPie

Is it a way to solve refresh stats tracking by passing `refreshMetric` into `get` function ? And it just keeps the refresh number count as before.

Related to #24806

2017-06-05 09:23 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-06-05 09:32 UTC, jasontedor requested changes
I don't think we should do it like this.

2017-06-05 09:32 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/engine/Engine.java
> +    public abstract GetResult get(Get get, Function<String, Searcher> searcherFactory, @Nullable MeanMetric refreshMetric) throws EngineException;
Sorry, I do not think this should be done by pushing the metric into the engine. Now there are two places the metric can be updated and it's mixing things up. This needs to stay at the index shard level and can be done via callbacks.

2017-06-05 12:24 UTC, PnPie commented
like this ?

2017-06-05 14:03 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/index/engine/Engine.java
> +import org.elasticsearch.common.util.Callback;
I had not idea we had this! I'd use `Runnable` instead.

2017-06-05 14:06 UTC, nik9000 reviewed
Or, not runnable, but maybe `LongConsumer`.

2017-06-05 14:06 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +                    if (onRefreshMetric == null)
I'd name it `onRefresh` because the engine doesn't want to know about metrics at all, even in names.

2017-06-05 14:07 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/index/engine/Engine.java
>      public final GetResult get(Get get) throws EngineException {
Honestly I'd nuke this rather than make the callback `@Nullable`.

2017-06-05 14:35 UTC, jasontedor requested changes
I left more comments.

2017-06-05 14:35 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +    public GetResult get(Get get, Function<String, Searcher> searcherFactory, @Nullable Callback<Long> onRefreshMetric) throws EngineException {
Let's use a LongConsumer here to avoid boxing.

2017-06-05 14:35 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +                    if (onRefreshMetric == null)
+1

2017-06-05 14:35 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/engine/Engine.java
>      public final GetResult get(Get get) throws EngineException {
+1

2017-06-05 16:41 UTC, PnPie commented on core/src/main/java/org/elasticsearch/index/engine/Engine.java
>      public final GetResult get(Get get) throws EngineException {
If we totally delete this, we also need to replace the call of this method in `InternalEngineTests` and `RefreshListenersTests` by:
`get(Get get, Function<String, Searcher> searcherFactory, LongConsumer onRefresh)`
ex.https://github.com/PnPie/elasticsearch/blob/test/core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java#L923 
For non-realtime get we can pass `null` for `onRefresh` consumer, for realtime get so we just pass sth. whatever like `(x) -> {}` ?

2017-06-05 17:06 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/index/engine/Engine.java
>      public final GetResult get(Get get) throws EngineException {
I'd pass `() -> fail("didn't expect a refresh")` when you don't expect a GET and do something a bit more elaborate when you expect a refresh:
```
AtomicBoolean refreshed = new AtomicBoolean(false);
engine.get(get, () -> refreshed.set(true));
assertTrue("expected a refresh", refreshed.get());
```

2017-06-06 09:41 UTC, bleskes commented
@nik9000 @jasontedor did you consider using lucene's `RefreshListener` to track all refreshes, wherever they come from?

2017-06-06 11:24 UTC, nik9000 commented
Hmm. We already use it for firing the wait for refresh call backs. I think
we probably could. It would be in the right spot, I think.

Off hand, I think that is a better choice.

On Tue, Jun 6, 2017, 5:41 AM Boaz Leskes <notifications@github.com> wrote:

> @nik9000 <https://github.com/nik9000> @jasontedor
> <https://github.com/jasontedor> did you consider using lucene's
> RefreshListener to track all refreshes, wherever they come from?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/elastic/elasticsearch/pull/25052#issuecomment-306435074>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AANLoluSCNULmKsd79C2oLViN_kgnRkMks5sBR7VgaJpZM4Nv0gz>
> .
>

2017-06-06 12:34 UTC, jasontedor commented
@bleskes Yes, but I think it gets tricky because then you need state between the before and after calls to be able to track the total time of a refresh. I would prefer that we fix the bug along the lines here and investigate an architecture change to the approach for tracking these stats separately.

2017-06-06 14:26 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/engine/Engine.java
> +import org.elasticsearch.common.util.Callback;
This import can be dropped now.

2017-06-06 14:27 UTC, jasontedor commented
@PnPie It's easier during reviews to *not* force push, instead just keep accumulating commits.

2017-06-06 14:28 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +                        throw new InvalidParameterException("Consumer onRefresh should not be null in case of realtime get.");
This is the wrong exception type (it's a security exception), and I'm not sure if we even need to throw here, just let it NPE?

2017-06-06 14:29 UTC, nik9000 commented
> I would prefer that we fix the bug along the lines here and investigate an architecture change to the approach for tracking these stats separately.

+1

I think we should go with the LongConsumer for now and open an issue to investigate moving to a RefreshListener. The trouble with RefreshListener is that we don't know all the implications so I'll open an issue to investigate this as a followup.

2017-06-06 14:30 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +                        throw new InvalidParameterException("Consumer onRefresh should not be null in case of realtime get.");
Yeah. NPE should be fine.

2017-06-06 14:31 UTC, nik9000 commented
Since we'd like to get this in pretty quick I'm going to see about pushing a small commit with the cleanups that we'd like and then merging it.

2017-06-06 14:57 UTC, nik9000 commented
@jasontedor and @PnPie, I pushed some small cleanups.

2017-06-06 15:17 UTC, PnPie commented
Thanks for all your comments @jasontedor @nik9000

2017-06-06 15:23 UTC, jasontedor approved these changes
LGTM.

2017-06-06 15:23 UTC, jasontedor commented
Thanks @PnPie for this PR.

2017-06-06 15:37 UTC, nik9000 commented
> Thanks @PnPie for this PR.

Yeah! Thanks!

I'm sorry to grab it like I did. We realized that we want it merged today in the past few hours....

2017-06-06 16:08 UTC, PnPie commented
@nik9000 There is no problem at all, it's just the modifications and improvements. it's pretty normal, isn't it ?! in addition I really didn't well clean and format the codes ...

2017-06-06 16:39 UTC, merged

2017-06-06 17:04 UTC, nik9000 commented
@PnPie It is normal for us to ask you to do them. That way it feels like the whole thing is yours and you learn all of our ways. Doing what I did is fairly rare, but I'm glad you are ok with it!

I'm backporting to 5.x right now, btw.

2017-06-12 11:05 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?