Issue #24543 Fix
elastic/elasticsearch pull request #25080
Opened 2017-06-06 18:49 UTC by jmorph99

The EC2 Test did not need to be modified like the other two.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2017-06-06 18:56 UTC, nik9000 commented
Can you explain what you did in the PR's title? It is super useful for those of us that use our email to decide which PRs to review.

2017-06-06 20:35 UTC, jmorph99 reviewed
I fixed the plugins
used DISCOVERY_HOSTS_PROVIDER_SETTING
instead of DISCOVERY_TYPE_SETTING

removed backward compatibility support for DISCOVERY_TYPE.
Updated unit tests as well to use the new method.

2017-06-06 21:11 UTC, jmorph99 commented
Ok, I think it is updated.

On Tue, Jun 6, 2017 at 2:57 PM, Nik Everett <notifications@github.com>
wrote:

> Can you explain what you did in the PR's title? It is super useful for
> those of us that use our email to decide which PRs to review.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elastic/elasticsearch/pull/25080#issuecomment-306583550>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJQUx9lYFUHoZVAaDH7ruKyErQ1IINl4ks5sBaEFgaJpZM4Nxwj1>
> .
>

2017-06-07 00:15 UTC, rjernst commented
@jmorph99 I think he means the issue title and the commit message. Right now it is "Issue #24543 Fix", which will be the first line of the commit message when this is merged. That title is not useful. Instead, I would expect something like "Remove discovery plugins legacy support for discovery.type".

2017-06-07 03:54 UTC, jmorph99 commented
Thanks.


I apologize if I am slow to adapt.



On Tue, Jun 6, 2017 at 8:16 PM, Ryan Ernst <notifications@github.com> wrote:

> @jmorph99 <https://github.com/jmorph99> I think he means the issue title
> and the commit message. Right now it is "Issue #24543
> <https://github.com/elastic/elasticsearch/issues/24543> Fix", which will
> be the first line of the commit message when this is merged. That title is
> not useful. Instead, I would expect something like "Remove discovery
> plugins legacy support for discovery.type".
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elastic/elasticsearch/pull/25080#issuecomment-306649784>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJQUx_nC8ifLu5OBFCmvTu5cJ9ss20B8ks5sBevFgaJpZM4Nxwj1>
> .
>

2017-06-08 07:37 UTC, bleskes requested changes
Thx @jmorph99 for all the iterations. The code looks good! My only ask is that you add a note to the migration guide, [here](https://github.com/elastic/elasticsearch/blob/master/docs/reference/migration/migrate_6_0/settings.asciidoc). I think something like adding a new section called GCE/Azure/EC2 discovery setting and note that `discovery.type: ec2/azure/gce` has been removed in favor of the discovery host provider variants.

2017-06-08 21:48 UTC, jmorph99 commented
Ok - I think I did it successfully.

2017-06-11 20:50 UTC, jmorph99 commented
Ever going to close this?

2017-06-13 06:58 UTC, bleskes commented
@jmorph99 I think you pushed your doc change to another branch of your repo and therefore they don't appear here.  I suggest we just pull this PR as is and I can work on docs on as a follow up. Is that OK with you? Thanks for all the hard work. Git can be difficult.

2017-06-13 17:14 UTC, jmorph99 commented
Sure - that will be fine.

On Tue, Jun 13, 2017 at 2:59 AM, Boaz Leskes <notifications@github.com>
wrote:

> @jmorph99 <https://github.com/jmorph99> I think you pushed your doc
> change to another branch of your repo and therefore they don't appear here.
> I suggest we just pull this PR as is and I can work on docs on as a follow
> up. Is that OK with you? Thanks for all the hard work. Git can be difficult.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elastic/elasticsearch/pull/25080#issuecomment-308025318>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJQUx4pxlve2DExw7HaRZ141ceSRgZYcks5sDjM1gaJpZM4Nxwj1>
> .
>

2017-06-14 11:52 UTC, bleskes approved these changes

2017-06-14 11:52 UTC, merged

2017-06-14 11:53 UTC, bleskes commented
Thx @jmorph99 !