Add remote cluster infrastructure to fetch discovery nodes.
elastic/elasticsearch pull request #25123
Opened 2017-06-08 06:52 UTC by s1monw

In order to add scroll support for cross cluster search we need
to resolve the nodes encoded in the scroll ID to send requests to the
corresponding nodes. This change adds the low level connection infrastructure
that also ensures that connections are re-established if the cluster is
disconnected due to a network failure or restarts.

Relates to #25094

2017-06-08 09:04 UTC, bleskes requested changes
I left one ask about testing. Looks good otherwise

2017-06-08 09:04 UTC, bleskes commented on core/src/main/java/org/elasticsearch/transport/RemoteClusterService.java
> +                    if (countDown.fastForward()) {
I think that this can never be false, should we assert?

2017-06-08 09:04 UTC, bleskes commented on core/src/test/java/org/elasticsearch/transport/RemoteClusterServiceTests.java
> +                    service.collectNodes(new HashSet<>(Arrays.asList("cluster_1", "cluster_2", "no such cluster")),
can we also test transport layer failures? It's a different failure path.

2017-06-08 09:11 UTC, s1monw commented on core/src/main/java/org/elasticsearch/transport/RemoteClusterService.java
> +                    if (countDown.fastForward()) {
if you have more than one failure it will be false

2017-06-08 11:56 UTC, s1monw commented
@bleskes I pushed a new commit

2017-06-08 12:08 UTC, bleskes approved these changes

2017-06-08 12:08 UTC, bleskes commented on core/src/main/java/org/elasticsearch/transport/RemoteClusterService.java
> +                    if (countDown.fastForward()) { // we need to check if it's true since we could have multiple failures
right. thanks :)

2017-06-13 09:46 UTC, javanna approved these changes
LGTM

2017-06-13 09:46 UTC, javanna commented on core/src/main/java/org/elasticsearch/transport/RemoteClusterConnection.java
> +            request.local(true); // run this on the node that get's the request it's as good as any other
that get**s**

2017-06-13 09:46 UTC, javanna commented on core/src/main/java/org/elasticsearch/transport/RemoteClusterConnection.java
> +            runnable.run();
Question: why using a runnable here? couldn't we do `transportService.sendRequest` straight-away?

2017-06-13 12:19 UTC, s1monw commented on core/src/main/java/org/elasticsearch/transport/RemoteClusterConnection.java
> +            runnable.run();
we could but that means that we duplicate the code, so in this case I have it all in one runnable and just pass it on.

2017-06-13 12:23 UTC, merged