Port more OldIndexBackwardsCompatibilityIT tests to full cluster restart qa tests
elastic/elasticsearch pull request #25173
Opened 2017-06-12 09:31 UTC by martijnvg

Relates to #24939

2017-06-13 17:32 UTC, nik9000 requested changes

2017-06-13 17:32 UTC, nik9000 commented on qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java
> +        assertTrue("totalHits < " + totalHits, totalHits >=  1);
I'd go with `assertThat(totalHits, greaterThanOrEqualTo(1))` because it is going to produce a nice error message.

2017-06-13 17:32 UTC, nik9000 commented on qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java
> +        Map<String, Object> bestHit = (Map<String, Object>)
`Map<?, ?> bestHit = (Map<?, ?>) ...` will probably work and won't require the SuppressWarnings.

2017-06-13 17:32 UTC, nik9000 commented on qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java
> +        Map<String, Object> bestHit = (Map<String, Object>)
Probably....

2017-06-13 17:32 UTC, nik9000 commented on qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java
> +    static String toStr(Response response) throws IOException {
I do this a bit in other places. Do you want to convert? I didn't feel the need to make this but it *is* shorter so I'm fine with it.

2017-06-13 17:32 UTC, nik9000 commented on qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java
> +        assertNewReplicasWork(index);
I feel like `assertNewReplicasWork` should be in its own test. It doesn't have much to do with searching, I don't think.

2017-06-13 17:32 UTC, nik9000 commented on qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java
> +        assertNewReplicasWork(index);
I just like the idea of keeping the complexity around searching in the search test. That way the test for new replicas doesn't need fancy documents. It doesn't *have* fancy documents so we can be sure fancy documents have nothing to do with the test.

2017-06-14 08:05 UTC, martijnvg commented on qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java
> +        assertTrue("totalHits < " + totalHits, totalHits >=  1);
sure, on the other hand I try to use junit's `Assert.*` methods where possible. I'm not a big fan of using both test libraries in the same test case. But in this case it does improve readability.

2017-06-14 08:43 UTC, martijnvg commented
@nik9000 Thanks! I've update the PR.

2017-06-14 14:04 UTC, nik9000 commented on qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java
> +        assertTrue("totalHits < " + totalHits, totalHits >=  1);
I go the other way: I use junit's assert when it produces goot error messages and hamcrest otherwise. Whatever works is cool.

2017-06-14 17:27 UTC, nik9000 approved these changes
LGTM. I did just merge https://github.com/elastic/elasticsearch/pull/25204 which causes some conflicts. Sorry!

2017-06-15 12:48 UTC, merged