make identificaiton of closed indices more clear
elastic/elasticsearch pull request #25253
Opened 2017-06-15 13:16 UTC by asd-and-Rizzo

2017-06-15 13:16 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-06-15 13:17 UTC, asd-and-Rizzo commented
https://elasticsearch.na1.echosign.com/public/viewAgreement?tsid=CBFCIBAA3AAABLblqZhAw9JIc_nx4zzBm6p5I0Eb3OvgGcMdYvUBhpd4WEZqdu06WW-a3-ZojdMqUmyKveZZprmKUtIftRIY6ZHbirm_a&

2017-06-16 15:19 UTC, javanna requested changes
hi @asd-and-Rizzo thanks for your PR I requested a change.

2017-06-16 15:19 UTC, javanna commented on docs/reference/indices/open-close.asciidoc
> +Closed index responses with `index_closed_exception` and `403` status on call to `_stats` API. Closed indices are not returned in cross index `_aliases` or `_stats` API responses.
there are many more APIs that return IndexClosedException and 403 status code when executed against closed indices. For instance _search. But through the `ignore_unavailable` parameter, you can decide whether to ignore those closed indices or get an exception back instead. I would rephrase your new paragraph without mentioning any specific APIs, rather say "most APIs don't support execution against closed indices, hence `ignore_unavailable allows to control whether closed indices are skipped or cause an IndexClosedException to be returned". What do you think?

2017-06-19 12:32 UTC, asd-and-Rizzo commented
I will check `ignore_unavailable` behavior and update as recommend within next 2 weeks.

2017-06-19 12:44 UTC, javanna commented
thanks @asd-and-Rizzo please ping me once you've done so

2017-07-03 11:57 UTC, asd-and-Rizzo commented
@javanna, Please check my comment in patch. I see your thinking of closed behavior could be different from what I see. What does ES version your knowledge steam from?

2017-07-12 14:56 UTC, javanna requested changes
hi @asd-and-Rizzo I left a couple more comments. My feedback doesn't stem from any specific Elasticsearch version, ignore_unavailable is supported for a very long time now. Let me know if you have any further questions.

2017-07-12 14:56 UTC, javanna commented on docs/reference/indices/open-close.asciidoc
> +Closed index responses with `index_closed_exception` and `403` for most APIs, including `_stats` and `_search`. `ignore_unavailable` allows to control whether closed index do not cause `index_closed_
I would slightly rephrase this sentence: "Most APIs, including `_stats` and `_search`, return `index_closed_exception` and `403` status code when accessing closed indices. The `ignore_unavailable querystring parameter allows to control whether closed indices cause an error to be returned or not.".

2017-07-12 14:56 UTC, javanna commented on docs/reference/indices/open-close.asciidoc
> +Closed indices are not returned in most wildcard index API calls, like `_aliases`, `_stats` or `_search`, nor throw any exceptions and behave like non-existent.
I am not sure about this sentence. You control through ignore_unavailable whether closed indices throw error or not. They are unavailable indices for most of the APIs, hence either they are ignored or they cause an error (e.g. it is not technically possible to search against a closed index, so the question is just what to do instead: error or skip them?)

2017-07-12 14:56 UTC, javanna commented on docs/reference/indices/open-close.asciidoc
> +Closed index responses with `index_closed_exception` and `403` for most APIs, including `_stats` and `_search`. `ignore_unavailable` allows to control whether closed index do not cause `index_closed_
What do you mean with "Index returns value on call to `_aliases`" ?

2017-07-22 20:02 UTC, asd-and-Rizzo commented
Here is case:
/my_index
/my_closed_index

1. Request:
/_aliases
Response:
/my_index

2. Request:
/my_closed_index/_aliases
Response:
/my_closed_index

2. Request:
/_search
Response:
Some values from my_index
No error from my_closed_index.

3. Request:
/my_closed_index/_search?ignore_unavailable
Response:
Zero hits.

4. Request:
/my_closed_index/_search
Response:
Error.


From these I conclude next:
1. I should keep external list of indices to be able to delete them later (e.g. because of my retention policy we do close and then delete) or access ES cluster directly, not via API, to find the list.
2. ignore_unavailable does not work on multi indeces requests. So it makes `ignore_unavailable` useless in some situations.

So the problem is what is correct and useful specification of closed indices calls and usage of ignore_unavailable?

I will rephrase the sentence, but current behavior of closed indexes does not fill consistent for me.

2017-07-24 09:39 UTC, javanna commented
hi @asd-and-Rizzo  we'd like users to ask questions in our [forums](https://discuss.elastic.co/), as we reserve github issues for verified bug reports and feature requests.

From your example I see that `ignore_unavailable` does work with e.g. the search API. But I am not clear on the following statement:

> ignore_unavailable does not work on multi indeces requests. So it makes ignore_unavailable useless in some situations.

Please do open another issue if you think that the above is a bug rather than commenting here.

This other issue may be interesting too: #9438

2017-08-07 10:42 UTC, asd-and-Rizzo commented
@javanna, thanks for reference to forum and other issues. My pull request was only about to add documentation about current behavior, no expectancy to change this behavior. Just helping our support team and hoping that current behavior inconsistencies(as I see these) will be visible to other people.

2017-08-24 17:37 UTC, javanna requested changes
sorry @asd-and-Rizzo it took me a while to have another look, I left some more comments. Could you address those so I can get your PR in?

2017-08-24 17:37 UTC, javanna commented on docs/reference/indices/open-close.asciidoc
> +Most APIs, including _stats and _search, return `index_closed_exception` and 403 status code when accessing closed index.  The `ignore_unavailable` querystring parameter allows to control whether clo
403 recently became 400 . Can you update that?

2017-08-24 17:37 UTC, javanna commented on docs/reference/indices/open-close.asciidoc
> +Most APIs, including _stats and _search, return `index_closed_exception` and 403 status code when accessing closed index.  The `ignore_unavailable` querystring parameter allows to control whether clo
when accessing closed ind**ices**

2017-08-24 17:37 UTC, javanna commented on docs/reference/indices/open-close.asciidoc
> +Most APIs, including _stats and _search, return `index_closed_exception` and 403 status code when accessing closed index.  The `ignore_unavailable` querystring parameter allows to control whether clo
whether closed ind**ices** cause an error to be returned or are skipped.

2017-08-24 17:37 UTC, javanna commented on docs/reference/indices/open-close.asciidoc
> +Most APIs, including _stats and _search, return `index_closed_exception` and 403 status code when accessing closed index.  The `ignore_unavailable` querystring parameter allows to control whether clo
I find this sentence confusing: "Call to index `_aliases` returns correct value without error. " I would remove it.

2017-08-24 17:37 UTC, javanna commented on docs/reference/indices/open-close.asciidoc
> +Closed indices are not returned in most wildcard API calls, like `_aliases`, `_stats` or `_search`, nor throw any exceptions. Closed indices behave like non-existent, closed indices will not be retur
expand_wildcards allows to control whether to expand wildcards against open, closed or both. can you update this sentence please?

2017-11-06 09:22 UTC, javanna commented
There has been no activity on this for two months, I am closing. Feel free to reopen once the comments are addressed.

2017-11-06 09:22 UTC, closed without merging