[WIP] update DateFormat to use same year heuristic as Logstash
elastic/elasticsearch pull request #25266
Opened 2017-06-15 21:37 UTC by talevy

This is intended to keep parity of behavior between Logstash and Elasticsearch

here was the original PR: https://github.com/logstash-plugins/logstash-filter-date/pull/4

2017-06-16 08:23 UTC, jpountz requested changes
I think we should restrict the cases in which we apply this heuristic. For instance by failing if there is more than one day between the parsed date and the current date. Otherwise it is not unlikely we are just assigning random years to parsed dates?

2017-06-16 08:23 UTC, jpountz commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java
> +            boolean containsTimeZone = format.contains("Z");
You need to check for `z` as well?

2017-07-06 20:50 UTC, talevy commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java
> +            boolean containsTimeZone = format.contains("Z");
indeed... ported from Logstash code... looks like it may be missing on that end

2017-07-06 20:57 UTC, talevy commented
thank you for the review, sorry for the delay.. not sure Logstash will have time to react on their side, and the goal of this is to keep parity. For now, how do we feel if we leave it be a month-long lenient period. Although, I completely agree

2017-07-06 22:08 UTC, talevy commented
NEVERMIND, might not belong here in the end. Closing for now

2017-07-06 22:08 UTC, closed without merging