Update synonym-tokenfilter.asciidoc
elastic/elasticsearch pull request #25280
Opened 2017-06-16 19:45 UTC by elasticsearcher

Explicitly specify a 'tokenizer' setting in the 'synonym_graph' filter configuration to make it clear that this setting is allowed, which is not obvious from the documentation.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2017-06-16 19:45 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-06-20 11:57 UTC, clintongormley commented
@johtani is this correct?

2017-06-20 13:06 UTC, johtani commented
@clintongormley correct. And we already mention it after example.
```
The tokenizer parameter controls the tokenizers that will be used to tokenize the synonym, and defaults to the whitespace tokenizer.
```
Is not it enough?

2017-06-20 13:22 UTC, elasticsearcher commented
@johtani It's confusing because the analyzer in the example itself takes a `tokenizer` config so it's not clear that the blurb afterwards refers to the token filter and not the analyzer.

2017-06-21 09:00 UTC, johtani commented
@elasticsearcher I understood. How about adding "in synonym filter" sentence in `tokenizer` configuration sentence? or additional example before `tokenizer` parameter explanation?

cc: @clintongormley

2017-06-29 17:29 UTC, clintongormley commented
It would be good to add a callout `<1>` to the example to explain that that tokenizer is for the synonyms themselves, not for the analyzer definition

2017-06-30 01:22 UTC, johtani requested changes
Hi @elasticsearcher , 
I left a comment.
And could I ask you to sign the [CLA](https://www.elastic.co/contributor-agreement) ?

2017-06-30 01:22 UTC, johtani commented on docs/reference/analysis/tokenfilters/synonym-tokenfilter.asciidoc
> +                        "tokenizer" : "whitespace"
Could you please add a callout <1> to the example that you added?
 
Example is https://raw.githubusercontent.com/elastic/elasticsearch/master/docs/reference/analysis/analyzers/configuring.asciidoc

2017-07-05 23:09 UTC, elasticsearcher commented
Hi @johtani, done, sorry for the delay. I've signed the CLA and got a confirmation by email, but the commit check still fails for some reason.

2017-07-05 23:57 UTC, johtani commented
Hi @elasticsearcher Thanks for the update. I will check CLA checker!

2017-07-06 02:40 UTC, johtani approved these changes

2017-07-07 11:17 UTC, clintongormley commented
Hi @elasticsearcher 

I can't find a record of a signed CLA.  You need to use the same email address as you have on your github account, and if the email address you used when committing is different, then that email should be added to your github account too.

2017-07-12 07:59 UTC, merged

2017-07-12 08:04 UTC, johtani commented
@elasticsearcher Thanks! I cherry-pick to 5.5 and 5.x.