Disable date field mapping changing
elastic/elasticsearch pull request #25285
Opened 2017-06-18 21:02 UTC by PnPie

Disable date field changing in mapping.

I also modified a little `DocumentMapperMergeTests` in format.

Closes #25271

2017-06-18 21:02 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-06-22 11:17 UTC, jpountz requested changes
Thanks for picking this one up! I left some minor comments.

2017-06-22 11:17 UTC, jpountz commented on core/src/test/java/org/elasticsearch/index/mapper/DocumentMapperMergeTests.java
> +    public void testMergeDate() throws IOException {
Can you move this test to `DateFieldMapperTests` instead and undo changes to this file?

2017-06-22 11:17 UTC, jpountz commented on core/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java
> +            throw new IllegalArgumentException("date field cannot be updated");
Could you only check the `format` property and make the error message more specific?

2017-06-22 11:17 UTC, jpountz commented on core/src/test/java/org/elasticsearch/index/mapper/DocumentMapperMergeTests.java
> +        Exception e = expectThrows(IllegalArgumentException.class, () -> initMapper.merge(updateFormatMapper.mapping(), false));
++, thanks for using `expectThrows`

2017-06-22 11:17 UTC, jpountz commented on core/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java
> +            throw new IllegalArgumentException("date field cannot be updated");
it is currently a bit confusing since eg. `ignore_malformed` can be updated

2017-06-22 12:28 UTC, PnPie commented on core/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java
> +            throw new IllegalArgumentException("date field cannot be updated");
Thx for your comments, I modified the error message and specified it's _date field's format_ which cannot be updated. And the `fieldType()`'s [`equals()`](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java#L193-L199) method has been re-implemented to just compare the format of a Date, isn't it ?

2017-06-22 13:47 UTC, jpountz commented
Sorry but I just realized there is a better way of doing that, which is by changing `DateFieldType.checkCompatibility` and moving the format check out of the `if (strict)` block (and changing the conflict message). This is how we generally ensure that some options cannot change. And compare to your way of doing things, it also does the right thing when multiple types have a field with the same name by requiring that they all have the same format. You'll probably need to modify `DateFieldTypeTests` to pass `false` to `strictOnly` instead of `true`. By the way, we should do the same for the `locale` parameter since it affects date parsing as well.

2017-06-22 13:48 UTC, jpountz commented on core/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java
> +            throw new IllegalArgumentException("date field cannot be updated");
it also checks for other properties through the super.equals call

2017-06-23 08:30 UTC, PnPie commented
Yes I noticed that we also did this in `ParentFieldMapper`, so I retrieved both `format` and `locale` check from `if (strict)` block and modified the error message like in super class.
For `ParentFieldMapper` I put the `checkCompatibility` before `super.doMerge` because the `super.doMerge` copies target `fieldType` to the current one so it should be done before I think ?

2017-07-04 08:46 UTC, jpountz commented
@PnPie Sorry for the late reply, I was absent lately. Your PR looks good but I think it is not necessary to call checkComtpatibility as part of `doMerge` as it is checked higher up in the stack by `MapperService`. If you remove this call, your tests should still pass.

2017-07-05 20:43 UTC, PnPie commented
I deleted the [`checkCompatibility`](https://github.com/PnPie/elasticsearch/blob/f9b5e886ec32622f598719cfabc0ae7fb2811373/core/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java#L492-L494) call in `DateFieldMapper` but the `testMergeDate` didn't pass it said no expected exception thrown.
And I've had a look and it seems that `checkCompatibility` hasn't been called in higher level ? And in `MapperService` I found `checkObjectsCompatibility` but it's for `ObjectMapper` and it just did a merge to see if there are exceptions.

2017-07-06 07:51 UTC, jpountz commented
I think you need to change the test to call `MapperService.merge` which performs this check:

```patch
diff --git a/core/src/test/java/org/elasticsearch/index/mapper/DateFieldMapperTests.java b/core/src/test/java/org/elasticsearch/index/mapper/DateFieldMapperTests.java
index 448538b..fac4e7c 100644
--- a/core/src/test/java/org/elasticsearch/index/mapper/DateFieldMapperTests.java
+++ b/core/src/test/java/org/elasticsearch/index/mapper/DateFieldMapperTests.java
@@ -25,6 +25,7 @@ import org.elasticsearch.common.compress.CompressedXContent;
 import org.elasticsearch.common.xcontent.XContentFactory;
 import org.elasticsearch.common.xcontent.XContentType;
 import org.elasticsearch.index.IndexService;
+import org.elasticsearch.index.mapper.MapperService.MergeReason;
 import org.elasticsearch.plugins.Plugin;
 import org.elasticsearch.test.ESSingleNodeTestCase;
 import org.elasticsearch.test.InternalSettingsPlugin;
@@ -352,7 +353,8 @@ public class DateFieldMapperTests extends ESSingleNodeTestCase {
             .startObject("properties")
             .startObject("release_date").field("type", "date").field("format", "yyyy/MM/dd").endObject()
             .endObject().endObject().endObject().string();
-        DocumentMapper initMapper = parser.parse("movie", new CompressedXContent(initMapping));
+        DocumentMapper initMapper = indexService.mapperService().merge("movie", new CompressedXContent(initMapping),
+                MergeReason.MAPPING_UPDATE, randomBoolean());
 
         assertThat(initMapper.mappers().getMapper("release_date"), notNullValue());
         assertFalse(initMapper.mappers().getMapper("release_date").fieldType().stored());
@@ -361,9 +363,11 @@ public class DateFieldMapperTests extends ESSingleNodeTestCase {
             .startObject("properties")
             .startObject("release_date").field("type", "date").field("format", "epoch_millis").endObject()
             .endObject().endObject().endObject().string();
-        DocumentMapper updateFormatMapper = parser.parse("movie", new CompressedXContent(updateFormatMapping));
 
-        Exception e = expectThrows(IllegalArgumentException.class, () -> initMapper.merge(updateFormatMapper.mapping(), false));
+
+        Exception e = expectThrows(IllegalArgumentException.class,
+                () -> indexService.mapperService().merge("movie", new CompressedXContent(updateFormatMapping),
+                        MergeReason.MAPPING_UPDATE, randomBoolean()));
         assertThat(e.getMessage(), containsString("Merge conflits: [mapper [release_date] has different [format] values]"));
     }
 }
```

2017-07-06 13:07 UTC, PnPie commented
@jpountz Sorry I saw that the `checkCompatibility` was called in `MapperService`'s `merge` method by calling `FieldTypeLookup`'s same method. I removed in `doMerge`.

2017-07-06 13:47 UTC, jpountz approved these changes
No need to be sorry! It looks good, I'll check that tests pass and merge. Thanks!

2017-07-06 13:47 UTC, jpountz commented
@elasticmachine please test it

2017-07-07 09:48 UTC, jpountz commented
The test failure looks unrelated so I'll merge. Thanks @PnPie!

2017-07-07 09:49 UTC, merged