Fix race condition in RemoteClusterConnection node supplier
elastic/elasticsearch pull request #25432
Opened 2017-06-27 16:37 UTC by jaymode

This commit fixes a race condition in the node supplier used by the RemoteClusterConnection. The
node supplier stores an iterator over a set backed by a ConcurrentHashMap, but the get operation
of the supplier uses multiple methods of the iterator and is suceptible to a race between the
calls to hasNext() and next(). The test in this commit fails under the old implementation with a
NoSuchElementException. This commit adds a wrapper object over a set and a list, with all methods
being synchronized to avoid races. Additionally, iterators are no longer used and replaced with a
counter and index based access of an array list to maintain the round robin aspect of the previous
node supplier implementation.

2017-06-27 16:38 UTC, jaymode commented
@pickypg observed the following errors that were caused by this race condition:

```
java.util.NoSuchElementException: null
        at java.util.concurrent.ConcurrentHashMap$KeyIterator.next(ConcurrentHashMap.java:3416) ~[?:1.8.0_111]
        at org.elasticsearch.transport.RemoteClusterConnection$1.get(RemoteClusterConnection.java:127) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.transport.RemoteClusterConnection$1.get(RemoteClusterConnection.java:117) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.transport.RemoteClusterConnection.fetchShardsInternal(RemoteClusterConnection.java:183) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.transport.RemoteClusterConnection.fetchSearchShards(RemoteClusterConnection.java:165) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.transport.RemoteClusterService.collectSearchShards(RemoteClusterService.java:225) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:190) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:66) ~[elasticsearch-5.5.0.jar:5.5.0]
```

2017-06-28 10:02 UTC, s1monw requested changes
left a comment, thanks for the fix @jaymode

2017-06-28 10:02 UTC, s1monw commented on core/src/main/java/org/elasticsearch/transport/RemoteClusterConnection.java
> +        private final AtomicInteger counter = new AtomicInteger(0);
this can be a simple integer now?

2017-06-28 10:02 UTC, s1monw commented on core/src/main/java/org/elasticsearch/transport/RemoteClusterConnection.java
> +        private final Set<DiscoveryNode> nodeSet = new HashSet<>();
I don't like to have 2 data structures that we have to keep in sync. if you really wanna optimize for removal / insertion we can just use an array or an array list and sort it? I doubt we should to be honest. Maybe we just go with a list and linear scan or we use a set only and the same iterator approach and with the synchronization in place we can just set the iterator to null if we changed the set? that might be the easiest

2017-06-28 21:23 UTC, s1monw approved these changes
LGTM

2017-06-28 21:50 UTC, merged