Track local checkpoint on primary immediately
elastic/elasticsearch pull request #25434
Opened 2017-06-27 18:31 UTC by jasontedor

Today after a primary shard is recovered or promoted from a replica, it will not be tracking its own local checkpoint until the first indexing operation on the shard. This leads to situations where a shard is relocated and the knowledge it sends in the primary context about its own local checkpoint violates the global checkpoint. This commit rectifies this situation by tracking the local checkpoint on such shards immediately on recovery/promotion/relocation.

Closes #25415, relates #10708, relates #25355

2017-06-27 18:31 UTC, jasontedor commented
@ywelsch I'm opening this for discussion.

2017-06-28 14:06 UTC, jasontedor commented
@ywelsch I think this is ready for you after integrating #25431.

2017-06-28 14:38 UTC, ywelsch requested changes
I've made a suggestion around the update condition and suggested to use unit tests instead.

2017-06-28 14:38 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +                .filter(e -> !e.key.equals(allocationId)) // during primary relocation a shard can already know its local checkpoint
I think we should not filter out the allocation id, but keep the method as before and instead assert in the `IndexShard.updateAllocationIdsFromPrimaryContext` method that the local checkpoint that is provided as part of the primary context is equal to the local checkpoint that exists locally.

2017-06-28 14:38 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/index/shard/IndexShard.java
> +                            recoveryState.getRecoverySource().getType().equals(RecoverySource.Type.PEER)) {
With the change I suggested above we can leave out the == PEER condition and instead add ` && currentRouting.isRelocationTarget == false` to `currentState == IndexShardState.POST_RECOVERY && state == IndexShardState.STARTED`

2017-06-28 14:38 UTC, ywelsch commented on core/src/test/java/org/elasticsearch/index/shard/LocalCheckpointIT.java
> +public class LocalCheckpointIT extends ESIntegTestCase {
I wonder if we need an integration test for this. A test under `IndexShardTests` would be able to check the same.

2017-06-28 14:40 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/index/shard/LocalCheckpointIT.java
> +public class LocalCheckpointIT extends ESIntegTestCase {
Yeah, now that we are not doing this via indices cluster state service, this is now possible. I will update.

2017-06-28 15:49 UTC, jasontedor commented
This will be superseded by a forthcoming PR.

2017-06-28 15:49 UTC, closed without merging