Introduce primary/replica mode for GlobalCheckPointTracker
elastic/elasticsearch pull request #25468
Opened 2017-06-29 10:10 UTC by ywelsch

This PR refactors the GlobalCheckPointTracker to make it more resilient. The main idea is to make it more explicit what state is actually captured and how that state is updated through replication / cluster state updates etc. It also fixes the issue where the local checkpoint information is not being updated when a shard becomes primary.

The PR still has two issues, which I will address soon. The main reason for opening it as is to get initial feedback.
Issue 1: Some GlobalCheckpointTrackerTests are still missing.
Issue 2: BWC with 5.x is broken (qa/mixed-cluster tests failing).

2017-07-06 09:02 UTC, bleskes requested changes
I left a bunch of nits around assertion messages. There is one important test coverage ask for `GlobalCheckpointTracker#initializeWithPrimaryContext`, which caused to mark it as request changes. All the rest LGTM. Thanks @ywelsch

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +        assert !handOffInProgress || pendingInSync.isEmpty();
can we add a message that says what the pending in sync aIds are?

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +        assert !primaryMode || globalCheckpoint == computeGlobalCheckPoint(pendingInSync, localCheckpoints.values(), globalCheckpoint);
can we add a message with the globalCheckpoint and the result of the computation?

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +            assert !pendingInSync.contains(entry.getKey()) || !entry.getValue().inSync;
can we add message that indicates which aID it is?

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +    public synchronized void initializeAsPrimary(final String allocationId, final long localCheckpoint) {
how would you feel about naming this method (and it's counterpart) `activatePrimaryMode` ? I was confused a couple of times as initialize and primary terms already used in the IndexShard context (a primary relocation target is a primary shard and is already initializing long before the method is called) .

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +        assert localCheckpoints.get(allocationId) != null && localCheckpoints.get(allocationId).inSync &&
can we add a message with localCheckpoints.get(allocationId) and allocationId ?

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +            assert !primaryMode || inSyncAllocationIds.stream().allMatch(
can we add a message that tells us which aid the master fabricated?

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +                        assert inSync == false;
add a message with aid?

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +            throw new IllegalStateException("no local checkpoint tracking information available");
can we add the aid to the message?

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +        assert pendingInSync.contains(allocationId) == false;
can we add aid to the message?

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +        assert !lcps.inSync || (lcps.localCheckPoint >= globalCheckpoint);
can we add a message with the local checkpoint, the aid and the global checkpoint?

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +    public synchronized void markAllocationIdAsInSync(final String allocationId, final long localCheckpoint) throws InterruptedException {
should we assert here that the localCheckpoint is NO_OPS_PERFORMED or higher?

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +        assert lcps.localCheckPoint != SequenceNumbersService.PRE_60_NODE_LOCAL_CHECKPOINT ||
can we add a message with the aid in question?

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointTracker.java
> +        assert pendingInSync.isEmpty();
can we add a message with the pending aid?

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/shard/IndexShard.java
> +            if (engine != null) {
I'm wondering - shall we do this only when shardRouting.primary() is true?

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/shard/IndexShard.java
> +                assert Thread.holdsLock(mutex);
this can go away, since you inlined the method

2017-07-06 09:02 UTC, bleskes commented on core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java
> +            cancellableThreads.execute(() -> runUnderOperationPermit(() -> shard.initiateTracking(request.targetAllocationId())));
question, why did you choose to do it after phase1 ?

2017-07-06 09:02 UTC, bleskes commented on core/src/test/java/org/elasticsearch/index/replication/IndexLevelReplicationTests.java
> +                    globalCheckpointMatcher = numDocs == 0 ? equalTo(SequenceNumbersService.NO_OPS_PERFORMED) : equalTo(numDocs - 1L);
++. It is a good that this is fixed and we start with no ops performed.

2017-07-06 09:02 UTC, bleskes commented on core/src/test/java/org/elasticsearch/index/seqno/GlobalCheckpointTrackerTests.java
> +        // TODO: fix this: newActiveAllocationIds.add(initializingIds.iterator().next());
what do you mean?

2017-07-06 09:02 UTC, bleskes commented on core/src/test/java/org/elasticsearch/index/seqno/GlobalCheckpointTrackerTests.java
> -    public void testPrimaryContextOlderThanAppliedClusterState() {
I think we need equivalent tests of `initializeWithPrimaryContext` and it's relation to `appliedClusterStateVersion` ?

2017-07-07 12:47 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java
> +            cancellableThreads.execute(() -> runUnderOperationPermit(() -> shard.initiateTracking(request.targetAllocationId())));
It only becomes relevant that we're properly tracking the target shard when starting the engine on the target shard. With this we ensure that we don't miss any local checkpoint updates from the target shard.

2017-07-07 12:49 UTC, ywelsch commented on core/src/test/java/org/elasticsearch/index/seqno/GlobalCheckpointTrackerTests.java
> +        // TODO: fix this: newActiveAllocationIds.add(initializingIds.iterator().next());
I've removed this line, as it was an illegal operation (adding a fresh in-sync allocation id while the tracker was in primary mode).

2017-07-07 12:50 UTC, ywelsch commented
@bleskes I've addressed all comments. Have another look.

2017-07-07 15:04 UTC, bleskes commented on core/src/test/java/org/elasticsearch/index/seqno/GlobalCheckpointTrackerTests.java
> +        // TODO: fix this: newActiveAllocationIds.add(initializingIds.iterator().next());
clear. thx.

2017-07-07 15:15 UTC, bleskes approved these changes
LGTM. Thanks for the thorough test.

2017-07-07 15:15 UTC, bleskes commented on core/src/test/java/org/elasticsearch/index/seqno/GlobalCheckpointTrackerTests.java
> +        for (int i = 0; i < randomInt(10); i++) {
nit: this samples the randomInt again and again.. much less likely to get to 10.

2017-07-07 18:01 UTC, jasontedor approved these changes
LGTM.

2017-07-07 18:04 UTC, merged