Remove deprecated created and found from index, delete and bulk
elastic/elasticsearch pull request #25516
Opened 2017-07-03 11:17 UTC by olcbean

The `created` and `found` fields in index and delete responses became obsolete after the introduction of the `result` field in index, update and delete responses (#19566).

After deprecating the `created` and `found` fields in 5.x (#19633), now they are removed.

Fixes #19630

2017-07-03 11:17 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-07-03 13:20 UTC, nik9000 requested changes
I left two minor things. Otherwise I think this looks good!

Thanks for working on it @olcbean!

2017-07-03 13:20 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/action/delete/DeleteResponse.java
> +            DeleteResponse deleteResponse = new DeleteResponse(shardId, type, id, seqNo, primaryTerm, version,
I think you should pass the Result here. Maybe also add an assertion in the ctor that the result is either `Result.DELETED` or `Result.NOT_FOUND`.

2017-07-03 13:20 UTC, nik9000 commented on core/src/main/java/org/elasticsearch/action/index/IndexResponse.java
> +                    result == Result.CREATED ? true : false);
Same deal here as on Delete. I think you should pass the `result` into the ctor and `assert` that it is sane.

2017-07-03 13:20 UTC, nik9000 commented on docs/reference/docs/bulk.asciidoc
> -            "created": true,
I'm so glad we assert that these are right now!

2017-07-03 13:20 UTC, nik9000 commented on docs/reference/docs/bulk.asciidoc
> -            "created": true,
This is exactly the kind of thing I'd miss when removing these without the assertions.

2017-07-03 13:21 UTC, nik9000 commented
Marked as `breaking` because it is but that is ok because it removes deprecated response parameters that have had an alternate way to read them for most of the 5.x series.

2017-07-05 12:12 UTC, olcbean commented
@nik9000 thanks for the feedback! Just pushed a new commit

2017-07-07 17:58 UTC, nik9000 commented
Ah! I see now. The way you had it first was better. I'll revert the second commit and merge.

2017-07-07 17:58 UTC, merged

2017-07-07 17:59 UTC, nik9000 commented
Thanks @olcbean! I've merged to master.

2017-07-08 10:54 UTC, olcbean commented
@nik9000 Excellent, this is what I was hoping the final change to look like. Sorry about the confusion with the belated push earlier :)