[Docs] Document Update API for Java High Level REST Client
elastic/elasticsearch pull request #25536
Opened 2017-07-04 14:35 UTC by tlrx

This PR adds documentation for Java High Level REST Client's Update API.

2017-07-04 16:23 UTC, javanna requested changes
left some comments, looks good though

2017-07-04 16:23 UTC, javanna commented on client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java
> +            BytesRef script = XContentBuilder.builder(xContentType.xContent())
would it be possible to do this without using BytesRef from lucene?

2017-07-04 16:23 UTC, javanna commented on client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java
> +            parameters.put("count", 4);
maybe use a `Collections.singletonMap("count", 4)` in this case?

2017-07-04 16:23 UTC, javanna commented on docs/java-rest/high-level/apis/update.asciidoc
> +<3> Sets the script in the update request
**to** the update request

2017-07-04 16:23 UTC, javanna commented on client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java
> +                Script stored = new Script(ScriptType.STORED, "painless", "increment-field", parameters);  // <1>
can you split this line in two? otherwise the <1> ends up in a new line in the rendered docs

2017-07-04 16:23 UTC, javanna commented on docs/java-rest/high-level/apis/update.asciidoc
> +When using updates with a partial document, the partial document will be merged into the
merged **with** ?

2017-07-04 16:23 UTC, javanna commented on docs/java-rest/high-level/apis/update.asciidoc
> +<1> Handle the case where the document was created for the first time
add (upsert) at the end just to make sure it's clear when it can happen ?

2017-07-04 16:23 UTC, javanna commented on docs/java-rest/high-level/apis/update.asciidoc
> +<1> The raised exception indicates that a version conflict error was returned.
can we add docs for `fetchSource` (you can borrow it from my get api PR), `retryOnConflict` and `waitForActiveShards` ?

2017-07-04 16:23 UTC, javanna commented on docs/java-rest/high-level/apis/update.asciidoc
> +<1> The raised exception indicates that a version conflict error was returned.
also `getGetResult` in the response (I think it has to do with `fetchSource`)

2017-07-05 07:35 UTC, tlrx commented on client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java
> +            BytesRef script = XContentBuilder.builder(xContentType.xContent())
Good catch, I changed that

2017-07-05 09:30 UTC, tlrx commented
@javanna Thanks! I rebased and updated the doc.

2017-07-05 09:54 UTC, javanna commented on docs/java-rest/high-level/apis/update.asciidoc
> +When the source retrieval is enabled in the `UpdateRequest` using the `fetchSource(true)`
it can be enabled also with source inclusion and exclusion right? Maybe we should rather say "through the fetchSource method"

2017-07-05 09:56 UTC, javanna commented on docs/java-rest/high-level/apis/update.asciidoc
> +been changed by another operation between the start and the end of the current
between the document retrieval and its reindex operation ?

2017-07-05 09:56 UTC, javanna approved these changes
left two nits, LGTM otherwise, thanks!!!

2017-07-05 10:05 UTC, tlrx commented on docs/java-rest/high-level/apis/update.asciidoc
> +When the source retrieval is enabled in the `UpdateRequest` using the `fetchSource(true)`
right

2017-07-05 10:07 UTC, tlrx commented on docs/java-rest/high-level/apis/update.asciidoc
> +been changed by another operation between the start and the end of the current
What about "between the get and indexing phases of the update operation"

2017-07-05 10:08 UTC, javanna commented on docs/java-rest/high-level/apis/update.asciidoc
> +been changed by another operation between the start and the end of the current
fine with me

2017-07-05 10:16 UTC, merged