Expand How to tune for disk usage
elastic/elasticsearch pull request #25562
Opened 2017-07-05 20:52 UTC by cwurm

Adding sections on:
- Shard size (20-30 GB)
- Disabling `_source` when possible
- Force Merge
- Shrink

More suggestions welcome.

2017-07-06 02:04 UTC, jasontedor requested changes
I left a comment.

2017-07-06 02:04 UTC, jasontedor commented on docs/reference/how-to/disk-usage.asciidoc
> +Larger shards are going to be more efficient at storing data. While it is not possible to give a precise recommendation for how large shards should be, and very large shards come with drawbacks (for
I don't think we should specify a size here as it depends on too many factors. With fast replica recovery coming that is another mitigating factor (#22484) to one of the drawbacks that you mention.

2017-07-06 17:33 UTC, cwurm commented on docs/reference/how-to/disk-usage.asciidoc
> +Larger shards are going to be more efficient at storing data. While it is not possible to give a precise recommendation for how large shards should be, and very large shards come with drawbacks (for
@jasontedor Makes sense. Do you think we should mention an upper range, e.g. 50 GB?

2017-07-06 19:07 UTC, jasontedor commented on docs/reference/how-to/disk-usage.asciidoc
> +Larger shards are going to be more efficient at storing data. While it is not possible to give a precise recommendation for how large shards should be, and very large shards come with drawbacks (for
It's a good question but I don't think so. We are still fighting the "30 GB" heap recommendation, too many people see that number and think it's the magical number where they should set their heap without enough consideration for all the factors involved. Instead, I think that the verbiage is good but we should avoid enshrining specific numbers.

2017-07-07 18:48 UTC, cwurm commented
@jasontedor I've updated the shard size recommendation.

2017-07-08 11:51 UTC, jasontedor reviewed
I left a few suggestions.

2017-07-08 11:51 UTC, jasontedor commented on docs/reference/how-to/disk-usage.asciidoc
> +Elasticsearch stores data in segments. Segments make up a Lucene index - a shard in Elasticsearch. The <<indices-forcemerge,`_forcemerge` API>> can be used to reduce the number of segments per shard.
Perhaps turn this around a bit: Elasticsearch stores data in shards. Shards are Lucene indices and are composed of segments. Segments are the actual files on disk, etc.

2017-07-08 11:51 UTC, jasontedor commented on docs/reference/how-to/disk-usage.asciidoc
> +Keep in mind that very large shard sizes come with drawbacks, such as longer recovery times.
I do wonder if a comment is in order here about how this applies to *full* recoveries.

2017-07-10 16:10 UTC, cwurm commented on docs/reference/how-to/disk-usage.asciidoc
> +Keep in mind that very large shard sizes come with drawbacks, such as longer recovery times.
Maybe, I'm not sure under which circumstances we'd do a full recovery. Can you suggest a wording?

2017-07-10 16:18 UTC, cwurm commented on docs/reference/how-to/disk-usage.asciidoc
> +Elasticsearch stores data in segments. Segments make up a Lucene index - a shard in Elasticsearch. The <<indices-forcemerge,`_forcemerge` API>> can be used to reduce the number of segments per shard.
Makes sense, how about: "Indices in Elasticsearch are stored in one or more shards. Each shard is a Lucene index and made up of one or more segments - the actual files on disk. Larger segments are more efficient for storing data. The <<indices-forcemerge,`_forcemerge` API>> can be [...]"

2017-07-24 04:34 UTC, cwurm commented on docs/reference/how-to/disk-usage.asciidoc
> +Keep in mind that very large shard sizes come with drawbacks, such as longer recovery times.
@jasontedor ping

2017-07-27 14:08 UTC, jasontedor commented on docs/reference/how-to/disk-usage.asciidoc
> +Keep in mind that very large shard sizes come with drawbacks, such as longer recovery times.
Sorry, I've been on vacation. I will resume reviewing when I'm fully back tomorrow.

2017-08-04 14:13 UTC, jasontedor commented on docs/reference/how-to/disk-usage.asciidoc
> +Keep in mind that very large shard sizes come with drawbacks, such as longer recovery times.
I don't think we need anything elaborate here, something like: "Keep in mind that large shard sizes come with drawbacks such as long full recovery times."

2017-08-04 14:14 UTC, jasontedor commented on docs/reference/how-to/disk-usage.asciidoc
> +Elasticsearch stores data in segments. Segments make up a Lucene index - a shard in Elasticsearch. The <<indices-forcemerge,`_forcemerge` API>> can be used to reduce the number of segments per shard.
That sounds good to me.

2017-08-07 20:12 UTC, cwurm commented
@jasontedor Incorporated your suggestions, thanks a lot. How does it look?

2017-08-19 06:21 UTC, jasontedor approved these changes
LGTM.

2017-08-21 19:07 UTC, merged