s3 encryption using AWS kms key
elastic/elasticsearch pull request #25620
Opened 2017-07-08 18:44 UTC by suman29

Close #18561

Currently elasticsearch provides server side encryption of s3 repository only using AES256 algorithm. 
This pull request in an enhancement on top of that. It provides a functionality to use aws:kms algorithm to encrypt s3 repositories if aws_kms_key is provided. 

If no aws_kms_key is provided, it would default to it's beahviour of encrypting s3 repository files using AES256.

A curl request to take snapshot would look like this:

curl -XPUT 'http://localhost:9200/_snapshot/s3_repository?verify=false&pretty' -d'
 {
   "type": "s3",
   "settings": {
     "bucket": "my-bucket",
     "base_path": "es/test-snapshot",
     "region": "us-east-1",
     "server_side_encryption": true,
     "aws_kms_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
   }
 }'

2017-07-08 18:44 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-07-11 06:05 UTC, sunkuet02 requested changes

2017-07-11 06:05 UTC, sunkuet02 commented on plugins/repository-s3/src/test/java/org/elasticsearch/repositories/s3/MockAmazonS3.java
> +
Isn't the blank line is unnecessary ?

2017-07-11 17:27 UTC, suman29 commented on plugins/repository-s3/src/test/java/org/elasticsearch/repositories/s3/MockAmazonS3.java
> +
Sure, I will remove it.

2017-07-23 03:25 UTC, yaauie reviewed
Hello.

First, I'm a community member and not part of Elastic; my opinions might not line up perfectly with Elastic's.

First, the PR contains a lot of unrelated changes, which add noise and make it hard to decipher which changes are intentional and which ones are side-effects of your editor's settings. By using `git add --patch` and selecting only the relevant hunks, and by previewing your diff before committing with `git diff --cached`,  you can reduce the noise and make it easier for your reviewers to have rational conversations about the effect of your changes.

Second, I think as it stands, this PR doesn't really have a case for any one object "owning" the encryption key; because the `S3BlobStore` is passed around to just about everything else that needs the key, it _may_ make sense to make it the owner, in which case a lot of the changes to constructors aren't needed since they already have a reference to the `S3BlobStore`. 

Third, only after careful review did it become clear that the "keys" that are being passed around are key-_id_s. Naming them in such a way that indicates that they are KMS key _id_s would be hugely helpful in understanding the risk involved with, say, having public accessors, logging them, etc.

2017-07-23 03:25 UTC, yaauie commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
> +import java.io.IOException;
again, picking around unrelated changes with `git add --patch` is hugely helpful in reducing noise.

2017-07-23 03:25 UTC, yaauie commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
> +     * The access key to authenticate with s3. This setting is insecure because cluster settings are stored in cluster state
don't include unrelated changes

2017-07-23 03:25 UTC, yaauie commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
> +     * The secret key to authenticate with s3. This setting is insecure because cluster settings are stored in cluster state
don't include unrelated changes

2017-07-23 03:25 UTC, yaauie commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
> +        new ByteSizeValue(5, ByteSizeUnit.MB), new ByteSizeValue(5, ByteSizeUnit.TB));
unrelated changes

2017-07-23 03:25 UTC, yaauie commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
> +        new ByteSizeValue(5, ByteSizeUnit.MB), new ByteSizeValue(5, ByteSizeUnit.TB));
unrelated changes

2017-07-23 03:25 UTC, yaauie commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
> -                        NamedXContentRegistry namedXContentRegistry, AwsS3Service s3Service) throws IOException {
unrelated changes

2017-07-23 03:25 UTC, yaauie commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
> +                "server_side_encryption_key [{}], buffer_size [{}], cannedACL [{}], storageClass [{}]",
even though this is just `debug`, logging an encryption key is worrisome

2017-07-23 03:25 UTC, yaauie commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
> +        if (serverSideEncryptionKey == null) {
if the key isn't set, why set it to an empty string?

2017-07-23 03:25 UTC, yaauie commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java
> -                                                   " creating an s3 snapshot repository backed by it.");
unrelated changes

2017-07-23 03:25 UTC, yaauie commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3OutputStream.java
> +        bufferSizeInBytes, boolean serverSideEncryption,  String serverSideEncryptionKey) {
unconventional newline between type and parameter name

2017-11-06 20:18 UTC, javanna commented
@tlrx could you have a look at this please?

2017-11-06 20:29 UTC, sunkuet02 approved these changes

2018-01-08 13:04 UTC, tlrx commented
@suman29 Sorry to come so late. Are you still interested to work on this?

If so, I think that @yaauie 's comments are worth to have a look. I also think that the aws_kms_key must be a secure settings like `access_key` and `secret_key` already are, ie a setting stored in the `elasticsearch-keystore` but read back using `SecureSetting.secureString()`.

2018-01-08 13:04 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-03-23 11:36 UTC, tlrx commented
Thanks @suman29 for this contribution, we greatly appreciated it and I strongly apologize for the time it took me to look at it. 

We are still interested in such a feature but we don't have immediate plan to work on it. Also, adding the feature might require more work as it should be integrated with the Elasticsearch keystore. Since this pull request is a bit stalled I'm going to close it (again, sorry!). If anyone is interested in revived it please feel free to comment or +1.

2018-03-23 11:36 UTC, closed without merging

2018-04-05 20:34 UTC, robsweet commented
I'll +1 this.  Also, as the key is really just the ARN for the KMS key, and not the key itself, it doesn't seem like it needs to be a secure setting.

2018-04-30 15:07 UTC, danlsgiga commented
I'm also +1 here. Agree with @robsweet, the key ARN is not a secret in any form, so having it out of the secure keystore is just fine.

2018-07-05 11:17 UTC, wknapik commented
+1

2019-06-04 16:22 UTC, SkySonR commented
Please, merge this

2019-06-04 16:32 UTC, wknapik commented
@SkySonR https://github.com/elastic/elasticsearch/pull/41738