explain mapping explosion
elastic/elasticsearch pull request #25654
Opened 2017-07-11 16:18 UTC by matarrese

Closes #23687

2017-07-11 16:18 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-07-12 14:02 UTC, javanna requested changes
hi @matarrese thanks a lot for your PR, I left a few minor comments on the new docs section, let me know what you think.

2017-07-12 14:02 UTC, javanna commented on docs/reference/mapping.asciidoc
> +Defining too many fields in an index or having too many nested documents or too many fields that contain nested
I think we should only mention too many fields in an index here. how do too many nested documents cause a mapping explosion?

2017-07-12 14:02 UTC, javanna commented on docs/reference/mapping.asciidoc
> +documents are conditions that can lead to a mapping explosion, a case that occur when a cluster run ot of memory
I would rather say: "conditions that can lead to a mapping explosion, which can cause out of memory errors and difficult situations to recover from.

2017-07-12 14:02 UTC, javanna commented on docs/reference/mapping.asciidoc
> +As an example, consider a situation in which every new document inserted introduced new fields.
introduce**s** ?

2017-07-12 14:02 UTC, javanna commented on docs/reference/mapping.asciidoc
> +This is entirely legit possibility considering that Elasticsearch has the ability to be schema-less, which means that
This is possible considering with dynamic mappings. Every time a document contains new fields, those will end up in the index's mappings.

2017-07-12 14:02 UTC, javanna commented on docs/reference/mapping.asciidoc
> +index's mappings. This isn't worrying for a small amount of data, but it can become an "exploding" situation as the
but it can become a problem as the mapping grows.

2017-07-12 14:22 UTC, matarrese commented on docs/reference/mapping.asciidoc
> +Defining too many fields in an index or having too many nested documents or too many fields that contain nested
you are right, jut to be 100% sure, if I nested document introduce new fields, this can be a similar case of Defining too many fields?

2017-07-12 14:25 UTC, javanna commented on docs/reference/mapping.asciidoc
> +Defining too many fields in an index or having too many nested documents or too many fields that contain nested
if you mean when using the nested type, nested documents are submitted together with their "parent" document. So, yes if they contain too many fields they lead to the same problem, but given that they are part of the main document their case is not different from "Defining too many fields in an index".

2017-07-12 16:10 UTC, javanna commented on docs/reference/mapping.asciidoc
> +introduces new fields. This is possible considering with dynamic mappings.
let's make it "This is quite common with dynamic mappings." ?

2017-07-12 16:11 UTC, javanna approved these changes
left a small last comment, LGTM otherwise. If you can make that change I will merge this. Thank you!

2017-07-13 14:02 UTC, javanna approved these changes
thanks @matarrese LGTM I will merge this.

2017-07-14 07:47 UTC, merged