Remove all_fields:true in favour of default_field:* in the query_string query
elastic/elasticsearch pull request #25726
Opened 2017-07-14 14:26 UTC by jimczi

This change deprecates the `all_fields` parameter in the query_string query in favour of setting
`default_field` to "*".
Setting "*" will cause the query_string to expand any query text without prefix field to be expanded to all fields queryable in the mapping.
This mode is also the default when `fields` and `default_field` are not set.
This change also build a match all query when "*" is requested and default_field is also set to "*".

The same should be done on simple_query_string to resolves https://github.com/elastic/elasticsearch/issues/25551 entirely.

Relates #25551

2017-07-14 15:43 UTC, dakrone requested changes
@jimczi I just started playing with this (hence the short review), but I found something that causes some dissonance. If someone configures `"default_field": "*"` in the index settings, it does *not* work the same way as configuring `"default_field": "*"` in the query does.

Here's something that demonstrates the problem:

```json
DELETE /test?pretty=false
{}

PUT /test?pretty=false
{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 0,
      "query": {
        "default_field": "*"
      }
    }
  },
  "mappings": {
    "doc": {
      "properties": {
        "f1": {"type": "text"},
        "f2": {"type": "text"}
      }
    }
  }
}

POST /test/doc/1?refresh=wait_for&filter_path=result&pretty=false
{"f1": "foo", "f2": "bar"}

POST /test/_search
{
  "query": {
    "query_string": {
      "query": "foo AND bar"
    }
  }
}

POST /test/_search
{
  "query": {
    "query_string": {
      "query": "foo AND bar",
      "default_field": "*"
    }
  }
}
```

And the output:

```json
{"acknowledged":true}
{"acknowledged":true,"shards_acknowledged":true,"index":"test"}
{"result":"created"}
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}

{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.5753642,
    "hits" : [
      {
        "_index" : "test",
        "_type" : "doc",
        "_id" : "1",
        "_score" : 0.5753642,
        "_source" : {
          "f1" : "foo",
          "f2" : "bar"
        }
      }
    ]
  }
}
```

2017-07-14 15:43 UTC, dakrone commented on core/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java
> +     * This setting is deprecated, set {@link #defaultField(String)} to "*" instead.
I think this comment is misleading since this is a getter

2017-07-14 19:19 UTC, jimczi commented
Thanks @dakrone , good catch.
I pushed some changes to fix the bug.

2017-07-17 20:57 UTC, jimczi commented
This PR has been updated to refactor the expansion of field names for the main es queries (the simple query string should be done in a follow up). The new description reflects the latest status of the PR (and explains the main changes). @dakrone I need to document the new behavior and work a bit on tests but the code is ready for a review I think ;).

2017-07-18 16:53 UTC, dakrone commented
> For partial field names (with * suffix), the expansion is done only on keyword, text, date and number field types. Other field types are simply ignored.

Does this include the `ip` field? (I can't remember if `ip` counts as a `number`)

2017-07-18 16:58 UTC, jimczi commented
> Does this include the ip field? (I can't remember if ip counts as a number)

It's a separate type but you are right this include the `ip` type as well. I've updated the description of the PR.

2017-07-18 17:24 UTC, dakrone approved these changes
LGTM, I left some comments about whether we want to capture exception messages, but it's up to you for addressing them.

Thanks for doing this!

2017-07-18 17:24 UTC, dakrone commented on core/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java
> +                Boolean useAllFields = defaultField == null ? null : "*".equals(defaultField);
I think `"*".equals(defaultField)` should use `Regex.isMatchAllPattern`

2017-07-18 17:24 UTC, dakrone commented on core/src/main/java/org/elasticsearch/index/search/MatchQuery.java
> +                    return new MatchNoDocsQuery("fuzzy query failed for " + fieldType.name() + ":" + term.text());
Can we include the exception message? It might be good to know that a lenient query failed due to something that is avoidable

2017-07-18 17:24 UTC, dakrone commented on core/src/main/java/org/elasticsearch/index/search/MultiMatchQuery.java
> +                                FieldAndFieldType... blendedFields) {
I think the indentation is off here still? :)

2017-07-18 17:24 UTC, dakrone commented on core/src/main/java/org/elasticsearch/index/search/QueryStringQueryParser.java
> +                return null;
should this return a `MatchNoDocsQuery` like the other ones where an exception is thrown?

2017-07-18 17:24 UTC, dakrone commented on core/src/main/java/org/elasticsearch/index/search/QueryStringQueryParser.java
> +                return new MatchNoDocsQuery("fuzzy query failed for " + currentFieldType.name() + ":" + termStr);
Should we include the message of the exception here?

2017-07-18 17:24 UTC, dakrone commented on docs/reference/query-dsl/query-string-query.asciidoc
> -|`all_fields` | Perform the query on all fields detected in the mapping that can
Should we leave this in here, but mark it as deprecated? It still technically exists and I'm not sure we want people that have `all_fields: true` set to not be able to look up what the option does (until it's removed)

2017-07-21 14:52 UTC, merged

2017-08-01 17:44 UTC, Bargs commented
Hey @jimczi, I'm seeing an odd difference between `default_field` and `fields`. `fields: ["*"]` sometimes throws an error when `default_field: "*"` does not. For example:

I'm using a weblogs data set with IP fields. If I send the following query, I get an error:

```
  {
    "query_string": {
      "query": "200",
      "analyze_wildcard": true,
      "fields": [
        "*"
      ]
    }
  }
```

```
{
      "error": {
        "root_cause": [
          {
            "type": "query_shard_exception",
            "reason": "failed to create query: {\n  \"bool\" : {\n    \"must\" : [\n      {\n        \"query_string\" : {\n          \"query\" : \"200\",\n          \"fields\" : [\n            \"*^1.0\"\n          ],\n          \"type\" : \"best_fields\",\n          \"default_operator\" : \"or\",\n          \"max_determinized_states\" : 10000,\n          \"enable_position_increments\" : true,\n          \"fuzziness\" : \"AUTO\",\n          \"fuzzy_prefix_length\" : 0,\n          \"fuzzy_max_expansions\" : 50,\n          \"phrase_slop\" : 0,\n          \"analyze_wildcard\" : true,\n          \"escape\" : false,\n          \"boost\" : 1.0\n        }\n      },\n      {\n        \"range\" : {\n          \"@timestamp\" : {\n            \"from\" : 1501607670716,\n            \"to\" : 1501608570716,\n            \"include_lower\" : true,\n            \"include_upper\" : true,\n            \"format\" : \"epoch_millis\",\n            \"boost\" : 1.0\n          }\n        }\n      }\n    ],\n    \"adjust_pure_negative\" : true,\n    \"boost\" : 1.0\n  }\n}",
            "index_uuid": "3FMTvZhWQyimxtxw3pJvvg",
            "index": "logstash-0"
          }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
          {
            "shard": 0,
            "index": "logstash-0",
            "node": "38QhIDc9TTGCRXYNWAmFJA",
            "reason": {
              "type": "query_shard_exception",
              "reason": "failed to create query: {\n  \"bool\" : {\n    \"must\" : [\n      {\n        \"query_string\" : {\n          \"query\" : \"200\",\n          \"fields\" : [\n            \"*^1.0\"\n          ],\n          \"type\" : \"best_fields\",\n          \"default_operator\" : \"or\",\n          \"max_determinized_states\" : 10000,\n          \"enable_position_increments\" : true,\n          \"fuzziness\" : \"AUTO\",\n          \"fuzzy_prefix_length\" : 0,\n          \"fuzzy_max_expansions\" : 50,\n          \"phrase_slop\" : 0,\n          \"analyze_wildcard\" : true,\n          \"escape\" : false,\n          \"boost\" : 1.0\n        }\n      },\n      {\n        \"range\" : {\n          \"@timestamp\" : {\n            \"from\" : 1501607670716,\n            \"to\" : 1501608570716,\n            \"include_lower\" : true,\n            \"include_upper\" : true,\n            \"format\" : \"epoch_millis\",\n            \"boost\" : 1.0\n          }\n        }\n      }\n    ],\n    \"adjust_pure_negative\" : true,\n    \"boost\" : 1.0\n  }\n}",
              "index_uuid": "3FMTvZhWQyimxtxw3pJvvg",
              "index": "logstash-0",
              "caused_by": {
                "type": "illegal_argument_exception",
                "reason": "'200' is not an IP string literal."
              }
            }
          }
        ]
      },
      "status": 400
    }
```

A multi_match with `fields: ["*"]` fails with the same error:

```
{
  "multi_match": {
    "query": 200,
    "fields": [
      "*"
    ],
    "type": "phrase"
  }
}
```

The following query_string query using default_field, however, works fine:

```
{
  "query_string": {
    "query": "200",
    "analyze_wildcard": true,
    "default_field": "*"
  }
}
```

For me, it would be ideal if `fields: ["*"]` worked like `default_field: "*"`. If `fields: ["*"]` throws errors depending on the query value, I can't really send user provided values and I'm back to abusing the query_string query in order to do searches across all fields.

2017-08-01 18:49 UTC, jimczi commented
This is just a leftover of the `all_fields` mode. By default the `query_string` and `multi_match` query are not lenient, they throw an error when an invalid content is used for a field type. When the `all_fields` was used (by default or when it was explicitly set) the leniency was forced to true. I kept this behavior for `query_string` query using `default_field:*` but it's just to make sure that the default (when default_field is not set) doesn't change. If you use `fields:*` or the `multi_match` query you'll have to set the leniency to true manually.

2017-08-01 22:10 UTC, Bargs commented
Ah, I had no idea that `lenient` parameter existed. Thanks @jimczi, that's exactly what I needed!