Move tribe to a module
elastic/elasticsearch pull request #25778
Opened 2017-07-18 16:27 UTC by ywelsch

This PR moves tribe to a module, stripping core from the tribe functionality. If desired, we could even make tribe a plugin instead of a module.

2017-07-25 08:23 UTC, s1monw commented
> If desired, we could even make tribe a plugin instead of a module. 

I think a module is fine here we should have done the move to a plugin earlier we are late in to the game here.

2017-07-25 08:40 UTC, s1monw requested changes
I left some suggestions and asks. I love this effort it makes core so much cleaner and settigns handling is so much improved.

2017-07-25 08:40 UTC, s1monw commented on core/src/main/java/org/elasticsearch/node/Node.java
> +    public static class NodeBuilder {
do we really need this additional class? it's seem like users can provide all the stuff at once to the newNode method?

2017-07-25 08:40 UTC, s1monw commented on modules/tribe/src/main/java/org/elasticsearch/tribe/TribeService.java
> +    @Inject
I strongly believe we should not add any new  `@Inject` anywhere in the codebase. we need to find a different way to do this

2017-07-25 08:40 UTC, s1monw commented on modules/tribe/src/main/java/org/elasticsearch/tribe/TribePlugin.java
> +        return Collections.singleton(TribeService.class);
why do we need to initialize it via guice, is there anything we can do about this? I think this is a blocker if we are adding inject annotations anywhere

2017-07-25 08:40 UTC, s1monw commented on core/src/main/java/org/elasticsearch/node/Node.java
> +        onStartedListeners.add(runnable);
our plugin API on the node level is pull based not push. Can we add a method to pull these from `ClusterPlugin.java` that way we are consistent and we fully control who calls this method.

2017-07-25 08:40 UTC, s1monw commented on core/src/main/java/org/elasticsearch/node/Node.java
> +    public static class NodeBuilder {
I don't think we need this entire construct we can just subclass Node.java in the plugin / module and create a node via this?

2017-07-25 15:58 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/node/Node.java
> +    public static class NodeBuilder {
To play nicely with the `MockNode` concept used by the tests, we cannot just create the Node instance ourselves. However, by removing Guice injection, I've just replaced this class by a `BiFunction<Settings, Path>`.

2017-07-25 15:58 UTC, ywelsch commented on modules/tribe/src/main/java/org/elasticsearch/tribe/TribeService.java
> +    @Inject
I tried to unguice it in 2025150

2017-07-25 19:38 UTC, s1monw requested changes
Left a comment LGTM otherwise

2017-07-25 19:38 UTC, s1monw commented on core/src/main/java/org/elasticsearch/plugins/Plugin.java
> +                                               BiFunction<Settings, Path, Node> clientNodeBuilder) {
I think we should not make this a first class citizen. Instead I suggest we remove the Node#newNode entirely and add a `MockTribePlugin` class that passes such a function that delegates to / creates a `MockNode`. Given that tribe goes away I think that is the right tradeoff. WDYT?

2017-07-28 08:09 UTC, s1monw approved these changes
LGTM thank you for all the extra iterations. good change!

2017-07-28 09:23 UTC, merged

2017-07-28 09:24 UTC, ywelsch commented
Thanks @s1monw