Support client-only mode for NioTransport
elastic/elasticsearch pull request #25839
Opened 2017-07-21 23:10 UTC by tbrooks8

Currently, NioTransport does start normal socket selectors and the
client when the network server setting is set to false. This commit
makes it so that the client will be started even when the network server
is not enabled.

Additionally, it randomly introduces the NioTransport as an option for
the MockTransportClient throughout tests.

2017-07-23 02:09 UTC, yaauie commented
> it randomly introduces the NioTransport as an option for
> the MockTransportClient throughout tests.
> -- [@tbrooks8](https://github.com/elastic/elasticsearch/pull/25839#issue-244803500)

Randomly selecting an alternate codepath in tests seems like a recipe for hard-to-reproduce bugs and builds that succeed only because they randomly failed to exercise code that created a bug; perhaps this option should be parameterised, and _all_ of the tests run through both?

2017-07-24 14:36 UTC, nik9000 commented
> Randomly selecting an alternate codepath in tests seems like a recipe for hard-to-reproduce bugs and builds that succeed only because they randomly failed to exercise code that created a bug; perhaps this option should be parameterised, and all of the tests run through both?

It *is* parameterize, just, randomly. Elasticsearch uses [this](https://github.com/randomizedtesting/randomizedtesting/wiki) randomized testing framework which allows us to reproduce random tests by starting with the same seed. That is why the seed is in every failure message.

We do have to be very careful though, routing all random decisions through carrotsearch's random source if we are running in test land, but we have the forbiddenapis static analysis to help make sure we do that right.

2017-07-25 08:55 UTC, s1monw requested changes
left some comments Looks Good in general

2017-07-25 08:55 UTC, s1monw commented on core/src/test/java/org/elasticsearch/client/transport/TransportClientHeadersTests.java
> +        String transport = randomBoolean() ? NioTransportPlugin.NIO_TRANSPORT_NAME : MockTcpTransportPlugin.MOCK_TCP_TRANSPORT_NAME;
should we push this into a util method in EsTestCase?

2017-07-25 08:55 UTC, s1monw commented on test/framework/src/main/java/org/elasticsearch/transport/MockTransportClient.java
> +        } else if (NioTransportPlugin.NIO_TRANSPORT_NAME.equals(transportType)) {
should this also check if the setting exists?

2017-07-25 08:55 UTC, s1monw commented on test/framework/src/main/java/org/elasticsearch/transport/nio/NioTransportPlugin.java
> +            settings1 = Settings.builder().put(settings).put(NioTransport.NIO_WORKER_COUNT.getKey(), 2).build();
++ what about 1? I mean that should still work no?

2017-07-25 14:46 UTC, tbrooks8 commented on test/framework/src/main/java/org/elasticsearch/transport/nio/NioTransportPlugin.java
> +            settings1 = Settings.builder().put(settings).put(NioTransport.NIO_WORKER_COUNT.getKey(), 2).build();
Yeah. I guess the reason I went with 2, is that we would generally expect the nio transport to be used with multiple selectors. And I thought maybe we would want the testing to always include some level of concurrency? But I can use 1 if you think that is better. Just let me know.

2017-07-25 14:47 UTC, tbrooks8 commented on test/framework/src/main/java/org/elasticsearch/transport/MockTransportClient.java
> +        } else if (NioTransportPlugin.NIO_TRANSPORT_NAME.equals(transportType)) {
I check in the `if` block. If is does not exist, we enter the `if` block and never go to the `else if` block.

2017-07-26 15:24 UTC, s1monw commented on test/framework/src/main/java/org/elasticsearch/transport/nio/NioTransportPlugin.java
> +            settings1 = Settings.builder().put(settings).put(NioTransport.NIO_WORKER_COUNT.getKey(), 2).build();
yeah lets stick with 2 we can still randomize it down the road

2017-07-26 15:25 UTC, s1monw approved these changes
LGTM

2017-07-26 15:25 UTC, s1monw commented on test/framework/src/main/java/org/elasticsearch/transport/MockTransportClient.java
> +        } else if (NioTransportPlugin.NIO_TRANSPORT_NAME.equals(transportType)) {
nevermind I was confused... all is good

2017-07-26 15:27 UTC, merged