fixed script syntax to access .keyword field, various cleanup
elastic/elasticsearch pull request #25915
Opened 2017-07-26 18:21 UTC by jpcarey

2017-07-26 22:16 UTC, nik9000 requested changes

2017-07-26 22:16 UTC, nik9000 commented on docs/reference/aggregations/metrics/scripted-metric-aggregation.asciidoc
> +// TEST[setup:transactions]
The name of the setup script is `ledger` so this change broke the build. If you'd like to rename it you can change it in `docs/build.gradle` so long as you change everything that uses it.

2017-08-20 20:46 UTC, jpcarey commented on docs/reference/aggregations/metrics/scripted-metric-aggregation.asciidoc
> +// TEST[setup:transactions]
reverted to the original `ledger` naming.

2017-08-21 13:42 UTC, nik9000 requested changes

2017-08-21 15:58 UTC, jpcarey commented on docs/reference/aggregations/metrics/scripted-metric-aggregation.asciidoc
> +        "map_script" : "params._agg.transactions.add(doc['type.keyword'].value == 'sale' ? doc.amount.value : -1 * doc.amount.value)", <1>
makes sense. I was adding the `.keyword` as the default behavior from elasticsearch when no explicit mappings were provided. This page didn't have mappings for the examples (but the test does), so I assumed this was a miss.

2017-09-12 18:59 UTC, cbuescher commented
@jpcarey are you still working on this? Going through some docs PRs to see if we can get some of these ready to get merged.

2017-10-27 14:07 UTC, cbuescher commented
ping @jpcarey, do you need any more help with this? Just glancing at the PR, but it looks close to completion?

2018-04-24 09:29 UTC, elasticmachine commented
Pinging @elastic/es-search-aggs

2018-10-24 10:49 UTC, colings86 commented
The documentation has changed quite a bit since this was opened and I'm not sure if this PR is still relevant. Since its not had any activity since the previous ping I'm going to close it but feel free to either re-open it with an up to date version or open a PR if there is still something you'd like to fix here

2018-10-24 10:49 UTC, closed without merging