exists template needs a template name
elastic/elasticsearch pull request #25988
Opened 2017-07-31 22:37 UTC by HonzaKral

running `curl -X HEAD localhost:9200/_template` results in `405 Method Not Allowed`

2017-08-01 00:17 UTC, jasontedor requested changes
The `flat_settings` parameter should remain, it is supported on `HEAD` template requests.

2017-08-01 00:17 UTC, jasontedor commented on rest-api-spec/src/main/resources/rest-api-spec/api/indices.exists_template.json
> -        "flat_settings": {
`flat_settings` is supported on `HEAD` requests; the behavior of `GET` and `HEAD` are aligned when both methods are supported.

2017-08-01 00:17 UTC, jasontedor commented on rest-api-spec/src/main/resources/rest-api-spec/api/indices.exists_template.json
> -          "required": false,
This change is correct.

2017-08-01 01:01 UTC, HonzaKral commented
Thanks for the review, updated the commit. Out of curiosity, what does `flat_settings` do for `HEAD` request?

2017-08-01 01:07 UTC, jasontedor commented
> Out of curiosity, what does `flat_settings` do for `HEAD` request?

Per the HTTP specification, when an endpoint supports both the `HEAD` and `GET` methods, the response to a `HEAD` request should be the same as a `GET` request to the same endpoint (including the same parameters) except that the body should be empty (to be explicit: this means that the `Content-Length` header should be the same as if a `HEAD` request had been sent). The way that we implement `HEAD` requests on endpoints that support them is to treat the request as if it was a `GET` request, and then before sending the request to the client, strip the body from the response. This means that a parameter like `flat_settings` on a `HEAD` request will change the content of the reply that would have come if the method was a `GET` method, thus changing the content length, thus changing the value of the `Content-Length` header that is included in the reply to the `HEAD` request.

2017-08-01 01:07 UTC, jasontedor approved these changes
LGTM.

2017-10-27 14:02 UTC, cbuescher commented
@HonzaKral just going through older open PRs, seems like this one is ready to merge. Do you want to go ahead or should we do it?

2017-10-27 14:05 UTC, HonzaKral commented
@cbuescher, please go ahead, I am not up-to-date with all the necessary backporting policies and other steps.

Thank you!

2017-10-27 14:14 UTC, merged

2017-10-27 14:38 UTC, cbuescher commented
@HonzaKral not entirely sure how rest-api-specs are used, but I suppose this change should be applied to all active branches down to 5.6?

2017-10-27 14:41 UTC, HonzaKral commented
I'd say yes, but not sure what is the current status of freezes/branch policies etc. That is why I try to stay away from merging patches to es myself since I am no longer familiar enough with the process...