Fixes Eclipse Oxygen type inference error
elastic/elasticsearch pull request #26001
Opened 2017-08-01 15:26 UTC by albertzaharovits

Need to be explicit on the generic type, Eclipse cannot infer the type from a function return type

2017-08-01 15:35 UTC, colings86 approved these changes
LGTM - tested in Eclipse Neon.3 Release (4.6.3) and does not cause any issues so I think as long as the build passes here we are good to merge this and then backport to 6.x, 6.0 (assuming its needed in those branches, can you see if this is also an issue in these branches?)

2017-08-01 21:54 UTC, jasontedor requested changes
I left a general comment.

2017-08-01 21:54 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/search/suggest/SuggestBuilderTests.java
> +            EqualsHashCodeTestUtils.<SuggestBuilder>checkEqualsAndHashCode(randomSuggestBuilder(), original -> {
When making these changes please add a comment that it is here to workaround compiler bugs, and link to an existing compiler bug or open a new one. Without a comment, someone else might see the generic parameter that is not needed per the specification and turn around and remove it and we are back to Eclipse being broken. Without an upstream issue to track and linked to from the comment we do not know when it's safe to remove.

2017-08-09 10:36 UTC, merged

2017-08-09 12:34 UTC, albertzaharovits commented
After a test, it looks like it is not a problem with the return type of the function, it is related to type inference for lambda function, see: https://bugs.eclipse.org/bugs/show_bug.cgi?id=481649
backported to 6.x & 6.0

2017-08-17 17:39 UTC, cbuescher commented
@albertzaharovits fyi I also just merged this to the 5.6 branch because it still is in active development