Update getting-started.asciidoc
elastic/elasticsearch pull request #26159
Opened 2017-08-11 07:50 UTC by rishabhbanga

Pasting this command in Kibana - curl -H "Content-Type: application/json" -XPOST 'localhost:9200/bank/account/_bulk?pretty&refresh' --data-binary "@accounts.json"
Gives - POST /json -binary @accounts.json and Error - {  "error": "Content-Type header [text/plain] is not supported",   "status": 406 }

Mainly because it is not mentioned explicitly, which directory is  "our current directory" referring to.

I may be wrong, since I've just started using this, but why not simply ask the reader to use - curl -XPUT "http://localhost:9200/bank/account/_bulk?pretty&refresh" -H 'Content-Type: application/json' and paste the content from Account.json?

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2017-08-11 07:50 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-08-11 10:54 UTC, cbuescher requested changes
I can understand why its not completely clear at this point that this command is meant to be used from the command line, not necessarily inside Kibana. Its a bit of a break here, so I can imagine a clarification of this in the previous paragraph would be better than changing the command here. Or, as an alternative, explain both approaches.

2017-08-11 11:33 UTC, rishabhbanga commented
Ideally,mentioning/explaining both alternatives would make sense, but since the context is with respect to the Kibana GUI, I suggested replacing the command itself.

2017-10-27 13:47 UTC, cbuescher commented
@rishabhbanga I'm closing this since there hasn't been much movement in favour of removing current state from other sides. If you still think the docs need improving here, please reopen with another suggestion on how to improve the wording in the introduction paragraph or any other ideas about improving this. Thanks for raising this though.

2017-10-27 13:47 UTC, closed without merging