Fix two unreleased percolator query analyze bugs
elastic/elasticsearch pull request #26176
Opened 2017-08-11 20:29 UTC by martijnvg

* If in a range query upper is smaller than lower then ignore the range query
* If two empty range extractions are compared don't fail with `NoSuchElementException`

2017-08-14 07:00 UTC, jpountz requested changes

2017-08-14 07:00 UTC, jpountz commented on modules/percolator/src/main/java/org/elasticsearch/percolator/QueryAnalyzer.java
> +        BytesRef min = UnicodeUtil.BIG_TERM;
It works for strings by using illegal characters. However here, ranges use a binary encoding and all values are allowed. So we should probably use `null` as a sentinel value.

2017-08-14 07:00 UTC, jpountz commented on modules/percolator/src/test/java/org/elasticsearch/percolator/QueryAnalyzerTests.java
> +        assertSame("In case ", queryTerms1, result);
does the string really help?

2017-08-30 15:02 UTC, martijnvg commented
@jpountz I updated the PR.

2017-09-05 14:35 UTC, jpountz approved these changes

2017-09-06 04:47 UTC, merged