DateProcessor Locale
elastic/elasticsearch pull request #26186
Opened 2017-08-14 02:48 UTC by sneivandt

Set the language on the Locale.Builder used to construct the DateProcessor. This change results in the locale that is generated being equal to one of standard locales such as Locale.SPANISH given the localeString "SPANISH".

2017-08-14 02:48 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-08-14 16:12 UTC, jpountz commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateProcessor.java
> -                    locale = (new Locale.Builder()).setLanguageTag(localeString).build();
would it work to use `LocalUtils.parse(localeString)` like we do for the date field?

2017-08-14 16:12 UTC, jpountz commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java
> +            return text -> parser.withDefaultYear((new DateTime(DateTimeZone.UTC)).getYear()).parseDateTime(text.toLowerCase());
this feels wrong to me, why did you do that change?

2017-08-15 01:06 UTC, sneivandt commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateProcessor.java
> -                    locale = (new Locale.Builder()).setLanguageTag(localeString).build();
This does not have the desired result. This snippet evaluates as false.

`LocaleUtils.parse("FRENCH").getLanguage().equals(Locale.FRENCH.getLanguage())`

The locale from LocaleUtils has the language "french" while Locale.FRENCH has the language "fr". This seems to be the key difference that results in the JodaTime parser not correctly looking for words in the correct language.

Perhaps it makes sense to move the logic that I have written here to convert from the display name for a language to the ISO code.

2017-08-15 01:55 UTC, sneivandt commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java
> +            return text -> parser.withDefaultYear((new DateTime(DateTimeZone.UTC)).getYear()).parseDateTime(text.toLowerCase());
This is an attempt to make the date parsing case insensitive. If you remove this change then you will be able to parse "mai 2017" but not "Mai 2017" for example.

2017-08-16 12:55 UTC, jpountz requested changes
I don't think we should try to understand the names of Java constants as locale names. However I realized that we parse locales differently in the date processor and in date fields, which I think we should fix.

2017-08-16 12:55 UTC, jpountz commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java
> +            return text -> parser.withDefaultYear((new DateTime(DateTimeZone.UTC)).getYear()).parseDateTime(text.toLowerCase());
It looks a bit wrong to me. If you would like to suggest this change, I'd like it to be a separate PR.

2017-08-16 12:55 UTC, jpountz commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateProcessor.java
> -                    locale = (new Locale.Builder()).setLanguageTag(localeString).build();
Why do you want `FRENCH` to work? The actual locale name is `fr`, not `FRENCH`?

2017-08-16 13:06 UTC, jpountz commented
I'm wondering whether a better fix would be to fail if the language code has less than 2 or more than 3 letters? This way it would be less trappy as `FRENCH` would fail immediately instead of being silently ignored?

2017-08-19 20:46 UTC, sneivandt commented
@jpountz I updated the change so that now it simply validates that the language tag matches an available locale. In this state it will not accept `FRENCH` as a valid locale but would accept values such as `fr` or `fr-CA`.

2017-08-21 08:39 UTC, jpountz commented
I have a limited knowledge of locales and language tags, but such a change makes me a bit worried that some valid tags may be rejected eg. because they are aliases and `Locale.getAvailableLocales()` will only give you the canonical ones.

2017-08-22 01:43 UTC, sneivandt commented
I agree with your concerns about filtering out potentially valid locales. I am not certain if there is a legitemate use case that would be impacted by validating against locales in `Locale.getAvailableLocales()`. I have updated this PR so that it just does does a simple check based on the languageString. This is a safer check and will prevent confusing errors as a result of using a value like `FRENCH`. You can of course still construct something with a value like `AA-AA` that the Locale.Builder will still accept when constructing the locale.

2017-08-22 07:47 UTC, jpountz requested changes

2017-08-22 07:47 UTC, jpountz commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateProcessor.java
> +                }
A single value should still work?

Maybe we could use the validation logic from https://stackoverflow.com/questions/3684747/how-to-validate-a-locale-in-java in order to make sure that the provided locale is recognized by the JVM?

2017-08-28 08:54 UTC, jpountz approved these changes

2017-08-28 08:59 UTC, merged

2017-08-28 08:59 UTC, jpountz commented
Thanks @sneivandt !