[DOCS] Adding settings reference. Closes #11504
elastic/elasticsearch pull request #26251
Opened 2017-08-17 03:53 UTC by debadair

This is a WIP. As step 1, I pulled the settings returned from include_defaults into an alphabetized list.  In addition to adding the allowed values and units for each setting, we should provide a brief description and say something about when you might want to use something other than the default. (And, possibly, when you really shouldn't)

2017-08-17 03:58 UTC, geekpete commented
Thanks, taking a look...

2017-09-06 06:26 UTC, geekpete commented
So as a start this LGTM. Would it be good to mention that this list is a WIP?

2017-09-08 22:20 UTC, jasontedor requested changes
I don't think we should do this.

2017-09-08 22:20 UTC, jasontedor commented on docs/reference/setup/settings-reference.asciidoc
> +allocation.max_retries::
I'm not sure what the key with defaults adds, and this looks like it will not be fun to maintain.

2017-09-08 22:24 UTC, jasontedor commented on docs/reference/setup/settings-reference.asciidoc
> +merge.policy.max_merge_at_once::
We intentionally undocumented these "expert" settings (#13199), let's not bring them back.

2017-09-08 22:26 UTC, jasontedor commented
> I don't think we should do this.

Elaborating on this, I question the value of documenting every setting versus other improvements that we can make to the settings documentation. There are expert settings that we do not want to document (cf. #13199). We should try to document the top `N` settings (I do not claim to know what `N` is, nor how to figure out what the `N` are). I don't think a raw list of settings with their defaults without any explanation of the settings helps users.

2017-09-10 22:08 UTC, geekpete commented
The point was to get to a list of all settings for the purposes of explaining those critical details such as defaults, measure of units, detailed description of the setting, if it's cluster/index/node level setting, etc that can sometimes be a bit mysterious. So perhaps we can still start this list but start with some sort of top N settings with all those minimum details, then expand with more settings as we can provide the details for them (also avoiding including the expert settings). This will almost always be incomplete though and probably need some indicator that lets the end reader know this like an alternative heading of "common settings reference" or some other indicator that ensures it's not meant to be definitive?

Or perhaps as you might have meant with your comment, we can just expand the details on existing settings that are scattered around the documentation with these extra details that would make them much more informative?

How do we plan to tackle entirely missing settings or settings that only have a passing mention? Expand as we go and file them into parts of the documentation relevant to the setting? This is what we do today?

2018-01-19 19:18 UTC, closed without merging