[Docs] Clarify behaviour of Pattern Capture Token Filter during search
elastic/elasticsearch pull request #26278
Opened 2017-08-18 10:23 UTC by cbuescher

There was some confusion about the fact that tokens emitted from a Pattern
Capture Token Filter are treated as synonyms when used to analyze a search
query. This commit adds an explanation to the note in the docs to emphasize this
behaviour.

Closes #25746

2017-08-18 10:24 UTC, cbuescher commented
@jimczi whould you mind taking a look if this small addition to the docs makes the sitation discussed in the referenced issue clear enough or do you have any suggestions for adding anything else?

2017-08-21 11:29 UTC, jimczi requested changes
Not sure that this makes the behavior more obvious. 
The previous sentence is good enough I think and could maybe be extended to explain search behavior (and not only highlighting):

````
 All tokens are emitted in the same position, and with the same character offsets...
````

Something like:
````
and a query for `john-smith_123@foo-bar.com` will return hits that contain any of the tokens even if AND is the default operator
````
?

2017-08-21 12:41 UTC, cbuescher commented
@jimczi thanks, good suggestion. I pushed a change according to your suggestions.

2017-08-21 12:48 UTC, jimczi approved these changes
LGTM, thanks !

2017-08-21 12:48 UTC, jimczi commented on docs/reference/analysis/tokenfilters/pattern-capture-tokenfilter.asciidoc
> +containing any of these tokens, even when using the `AND` operator.
I would use `and` lowercase since this is how we document it

2017-08-21 12:55 UTC, cbuescher commented
@jimczi thanks, will merge this soon

2017-08-21 12:56 UTC, merged