Add ThreadPool constructor that accepts name as a String
elastic/elasticsearch pull request #26283
Opened 2017-08-18 14:20 UTC by javanna

`BulkProcessor` needs a `ThreadPool` to be created, which needs settings that must contain a `node.name` setting. In a client, such setting makes little sense. This commit allows to create a `ThreadPool` by providing its name separately as a `String`, which will internally be added to the settings. `TestThreadPool` can be removed and replaced with the ordinary `ThreadPool`.

Closes #26028

2017-08-18 14:29 UTC, jasontedor requested changes
I left one comment.

2017-08-18 14:29 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java
> +        this(Settings.builder().put(settings).put(Node.NODE_NAME_SETTING.getKey(), name).build(), customBuilders);
I think we should fail if `settings` contains `node.name` setting already?

2017-08-18 14:41 UTC, nik9000 reviewed
I think it'd be cleaner to pass the name where it is needed rather than add it to the Settings object. I know that is a bigger change but stuffing it in a NODE_NAME_SETTING sees a bit hacky to me.

2017-08-21 07:43 UTC, tlrx reviewed
I tend to agree with Nik, I find it a bit hacky too.

2017-08-21 10:43 UTC, javanna commented
@nik9000 @tlrx the `node.name` was already part of the settings, I only added a new constructor that takes it as a separate argument to work around the check around it, as it makes little sense to require `node.name` setting on client code. Are you suggesting to remove it from there? I wouldn't want this change to affect that much the server code.

2017-08-21 12:50 UTC, tlrx commented
@javanna Looking at this again, I think that I'm ok with the additional ctor you added. What I'm not comfortable with is that the node name (or thread pool name) is extracted from the settings lower in the code path, making the node.name setting a mandatory setting but it's not exposed as such by the current ctor `ThreadPool(final Settings settings, final ExecutorBuilder<?>... customBuilders)`. I think we could change that in core but maybe in another pull request.

2017-08-22 12:26 UTC, javanna commented
I made the change that @jasontedor requested and added a test. Ready for another review round.

2017-08-23 12:27 UTC, jasontedor commented
I have an alternative proposal, and I'm sorry it's taken my time to write this down. My proposal is this: let's remove the thread pool as a need for bulk processor. We can do this in the following way:
 - the thread pool is needed for scheduling: for this we can either create a scheduling thread pool executor in the processor, and close on close or have the user pass one in (I favor the former, the latter is closer to today)
 - we use the thread pool to preserve the context for situations like reindex and it's friends; I think we can do this (thanks @nik9000 for helping with this one): allow a Function<Runnable, Runnable> to be passed in so then reindex and friends can pass a context preserving transformation and everyone else can us Function.identity

That would remove the need for this change.

2017-08-23 12:40 UTC, nik9000 commented
> we use the thread pool to preserve the context for situations like reindex and its friends; I think we can do this (thanks @nik9000 for helping with this one): allow a Function<Runnable, Runnable> to be passed in so then reindex and friends can pass a context preserving transformation and everyone else can us Function.identity

Now that you've written this I wonder if it'd be better instead to do
`Retry(BiFunction<Long, Runnable> delay)` and internally we delegate that appropriately to ThreadPool and others can delegate to their own delay implementation.

2017-08-25 14:38 UTC, javanna commented
Closing, I will revisit based on Jason's last comment.

2017-08-25 14:38 UTC, closed without merging