Migrates more ToXContentClasses
elastic/elasticsearch pull request #26321
Opened 2017-08-22 10:20 UTC by colings86

This includes removing `ToXContentToBytes`

2017-08-22 11:43 UTC, javanna requested changes
left a couple of comments, thanks for doing this!

2017-08-22 11:43 UTC, javanna commented on core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java
> +public final class InnerHitBuilder implements Writeable, ToXContentObject {
should we add toString impl to this class now that it doesn't inherit anymore from ToXContentToBytes?

2017-08-22 11:43 UTC, javanna commented on core/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java
> +    }
can we use some of the XContentHelper or Strings.toString here instead?

2017-08-22 11:43 UTC, javanna commented on core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java
> +public final class InnerHitBuilder implements Writeable, ToXContentObject {
this applies to all the classes that don't extend from ToXCOntentToBytes anymore and don't declare their own toString .

2017-08-22 12:55 UTC, colings86 commented
@javanna thanks for reviewing, I push two commits that address your comments, could you look again?

2017-08-22 13:03 UTC, javanna commented on core/src/main/java/org/elasticsearch/action/admin/indices/recovery/RecoveryResponse.java
> +            return XContentHelper.toXContent(this, XContentType.JSON, true).utf8ToString();
Strings.toString already catches IOException. there is a variant of it where you can pass in pretty and himanReadable flags.

2017-08-22 13:04 UTC, javanna approved these changes
LGTM besides the comment I left on using Strings.toString .

2017-08-23 07:17 UTC, merged

2017-08-23 08:16 UTC, colings86 commented
Note that this PR is only in merged to master and 6.x as the changes are not compatible with 6.0