Fork can match requests to the generic thread pool
elastic/elasticsearch pull request #26484
Opened 2017-09-03 20:18 UTC by jasontedor

If the query coordinating node is also a data node that holds all the shards for a search request, we can end up recursing through the can match phase (because we send a local request and on response in the listener move to the next shard and do this again, without ever having returned from previous shards). This recursion can lead to stack overflow for even a reasonable number of indices (daily indices over a sixty days with five shards per day is enough to trigger the stack overflow). Moreover, all this execution would be happening on a network thread (the thread that initially received the query). With this commit, we fork can match requests to the generic thread pool to prevent this.

Closes #26198

2017-09-03 20:41 UTC, jasontedor commented
This is fine in 5.6.0, the request are forked to the search thread pool there already.

2017-09-04 09:49 UTC, bleskes approved these changes
LGTM

2017-09-04 09:49 UTC, bleskes commented on core/src/test/java/org/elasticsearch/action/search/CanMatchIT.java
> +        final String node = internalCluster().startDataOnlyNode(Settings.builder().put("node.attr.color", "blue").build());
why do we need to start a node? can't we use an existing node and use it's _name for allocation filtering?

2017-09-04 09:49 UTC, bleskes commented on core/src/test/java/org/elasticsearch/action/search/CanMatchIT.java
> +    public void testAvoidStackOverflow() throws InterruptedException {
nit - this isn't really a can match test but more an "can we run with lot's of shards on nodes" tests. I think it's good to have but maybe we can fold it into one of the generic search IT suites? maybe `SimpleSearchIT` (although nothing is simple in life ;)

2017-09-04 09:54 UTC, bleskes commented on core/src/test/java/org/elasticsearch/action/search/CanMatchIT.java
> +        ensureGreen(TimeValue.timeValueSeconds(Long.MAX_VALUE));
this is worrisome...  how long does this test run normally? should we fallback to mocking?

2017-09-04 11:40 UTC, s1monw requested changes
I think we should fix this differently. This is only an issue since we are running into the `maxConcurrentShardRequests` which is unnecessary for this `can_match` action I wonder if we should rather opt out of it entirely otherwise we are subject to rejections which was partially the purpose of the `can_match` change.

2017-09-04 14:19 UTC, jasontedor commented
@s1monw For this reason when I initially submitted the pull request I forked this requests to the generic thread pool. After seeing that in the 5.6 branch these requests are forked to the search thread pool I followed your lead there. I'll look into opting out of max concurrent shard requests and I'll reach out later this week to discuss all of our options.

2017-09-05 07:49 UTC, s1monw commented
> @s1monw For this reason when I initially submitted the pull request I forked this requests to the generic thread pool. After seeing that in the 5.6 branch these requests are forked to the search thread pool I followed your lead there. 

lemme provide some history here since it's not obvious, in 5.6 do still fetch resouces in the rewrite phase for some queries. I fixed this in #25791 which allows to execute the rewrite phase on the network thread. The execution on the search threadpool will again cause potential rejections which we tried to prevent with moving to the network threadpool. 

> I'll look into opting out of max concurrent shard requests and I'll reach out later this week to discuss all of our options.

Looking forward to your suggestions

2017-09-13 02:30 UTC, jasontedor commented
@bleskes @s1monw I have updated this pull request, would you please take a look?

2017-09-13 02:30 UTC, jasontedor commented on core/src/test/java/org/elasticsearch/action/search/CanMatchIT.java
> +        ensureGreen(TimeValue.timeValueSeconds(Long.MAX_VALUE));
This test is removed, I am now using mocking.

2017-09-13 07:48 UTC, s1monw approved these changes
LGTM left 2 minors thanks for doing this

2017-09-13 07:48 UTC, s1monw commented on core/src/main/java/org/elasticsearch/action/search/InitialSearchPhase.java
> +    InitialSearchPhase(
can we maybe not warp on every parameter please?

2017-09-13 07:48 UTC, s1monw commented on core/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java
> +            shardsIts, timeProvider, clusterStateVersion, task, new BitSetSearchPhaseResults(shardsIts.size()), shardsIts.size());
can we leave a comment why we do this here?

2017-09-13 10:16 UTC, merged

2017-09-13 10:56 UTC, bleskes reviewed
Much cleaner. Thanks.