Better message text for ResponseException
elastic/elasticsearch pull request #26564
Opened 2017-09-09 20:35 UTC by synhershko

This avoids messages with malformed URLs, like `org.elasticsearch.client.ResponseException: PUT http://127.0.0.1:9502customer: HTTP/1.1 400 Bad Request`

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2017-09-09 20:35 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-09-09 20:39 UTC, jasontedor commented
Thanks for the PR. Would mind providing a reproduction that shows when this can happen?

2017-09-09 20:46 UTC, synhershko commented
I have it happening with the following code:

```
Response response = restClient.performRequest("PUT", "customer", newHashMap(), new NStringEntity("{\"invalid\":0}", ContentType.APPLICATION_JSON));
```

Because "customer" is without a leading `/`, and the hosts in RestClient I assume will never hold trailing `/`, a message like in the PR description happens.

If you want this within an actual test it might take me a few days to provide

2017-09-09 20:49 UTC, jasontedor commented
Thanks, no need for a test for a situation like this.

2017-09-09 20:57 UTC, jasontedor commented
So I don't think this is how we should fix this, I would prefer that we not "quietly" imply a "/" where none was given (in this case, neither the hostname nor the URI). Instead, I would suggest it be changed to something like:

```
method [PUT], host [http://127.0.0.1:9502], URI [customer], status [HTTP/1.1 400 Bad Request]
```

2017-09-09 22:07 UTC, synhershko commented
Makes sense, will do!

2017-09-13 09:43 UTC, synhershko commented
@javanna @jasontedor ready for review - also moved to using StringBuilder, which seems the common practice in the code base

2017-09-13 10:09 UTC, jasontedor requested changes
Thanks for the iteration @synhershko, I left another suggestion.

2017-09-13 10:09 UTC, jasontedor commented on client/rest/src/main/java/org/elasticsearch/client/ResponseException.java
> +        sb.append("], status line [").append(response.getStatusLine().toString()).append(']');
I appreciate the use of `StringBuilder`, but I think we can do something simpler and clearer here:

```java
String.format(
    Locale.ROOT,
    "method [%s], host [%s], URI [%s], status line [%s]\n%s",
    . 
    .
    .);
```

I find this so much easier to see what the end result is going to be.

2017-09-13 10:12 UTC, synhershko commented
Bah that's the first thing I did.. will update it back again now

2017-09-13 10:16 UTC, synhershko commented
done

2017-09-13 10:24 UTC, jasontedor commented
Looks good, I'll start a CI run. Thanks.

2017-09-13 10:24 UTC, jasontedor commented
test this please

2017-09-13 23:10 UTC, jasontedor commented
@synhershko It looks like there is already a test for this and it's failing with the change. Would you mind updating the test?

2017-09-14 08:56 UTC, synhershko commented
@jasontedor done

2017-09-14 09:19 UTC, jasontedor commented
test this please

2017-09-14 14:49 UTC, jasontedor commented
test this please

2017-09-15 01:09 UTC, jasontedor approved these changes
LGTM.

2017-09-15 01:10 UTC, merged

2017-09-15 01:11 UTC, jasontedor commented
Thanks @synhershko!

2017-09-15 13:04 UTC, synhershko commented
Awesome! @jasontedor any chance you can backport this to 6.x and 5.x, where I first encountered this issue?

2017-09-15 13:06 UTC, jasontedor commented
@synhershko I did backport this to 6.x and 6.0 already. I need to think about backporting to 5.6.

2017-10-05 19:31 UTC, jasontedor commented
I think this should remain as-is in 5.6.