Update removal_of_types.asciidoc
elastic/elasticsearch pull request #26614
Opened 2017-09-12 22:56 UTC by danochoa

Fix link to [parent-child relationship]

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2017-09-12 22:56 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-09-13 08:42 UTC, cbuescher requested changes

2017-09-13 08:42 UTC, cbuescher commented on docs/reference/mapping/removal_of_types.asciidoc
> +https://www.elastic.co/guide/en/elasticsearch/reference/5.4/mapping-parent-field.html[parent-child relationship]
I think it whould be better to use the asciidoc syntax for internal cross-references (<<url,link text>>) so we keep linking the current version etc... The page that the hard link refers to has the section title `mapping-parent-field`, so the link should be <<mapping-parent-field,parent-child relationship>>

2017-09-13 08:43 UTC, cbuescher commented
@danochoa thanks for opening this PR. I left a comment on how to improve the linking to other parts of the document. After you changed this, would you also sign the CLA so we can merge the PR?

2017-09-13 20:27 UTC, danochoa commented
@cbuescher thanks for the feedback, I made the change and signed the CLA

2017-09-14 08:09 UTC, cbuescher approved these changes
@danochoa thanks a lot, LGTM. I will merge this to the active branches where this is still a static link.

2017-09-14 08:10 UTC, merged