rename 'vm_map_max_count' into 'vm_max_map_count'
elastic/elasticsearch pull request #26798
Opened 2017-09-27 08:07 UTC by wlalele

2017-09-27 08:07 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-09-28 01:08 UTC, jasontedor commented
@wlalele Can you sign the CLA?

2017-09-29 07:49 UTC, wlalele commented
@jasontedor I signed it 3 times and it is still red, can you relaunch the test manually ?

2017-09-29 13:08 UTC, jasontedor commented
Thanks @wlalele. I ran the CLA checker manually and it's correct now.

2017-09-29 13:10 UTC, jasontedor requested changes
Thanks for the PR @wlalele. This is correct that the words are not in the correct order, but I think there's one more change to make while we are here.

2017-09-29 13:10 UTC, jasontedor commented on docs/reference/setup/install/docker.asciidoc
> +The `vm_max_map_count` setting should be set permanently in /etc/sysctl.conf:
I think this should be changed to `vm.max_map_count` as well. Can you push that change?

2017-09-29 19:37 UTC, wlalele commented
@jasontedor does it look like what you wanted ?

2017-09-29 19:53 UTC, jasontedor approved these changes
LGTM.

2017-09-29 19:55 UTC, merged

2017-09-29 19:56 UTC, jasontedor commented
Thanks @wlalele!