doc: deprecate _primary and _replica shard option
elastic/elasticsearch pull request #26792
Opened 2017-09-26 15:44 UTC by dnhatn

Tells v6 users that we are going to remove these options in v7.

Related #26335

2017-09-26 15:49 UTC, dakrone commented
@dnhatn we have special asciidoc syntax for deprecations, see: https://github.com/elastic/docs#additions-and-deprecations

2017-09-26 15:50 UTC, dnhatn commented
Thanks @dakrone. I will update it.

2017-10-04 11:23 UTC, jasontedor requested changes
I think that we should add deprecation logging for use of these preferences.

2017-10-04 16:42 UTC, dnhatn commented
retest this please

2017-10-04 19:44 UTC, dnhatn commented
Thanks @jasontedor  for the suggestion. I have added deprecation logging for these parameters. Could you please have another look?

2017-10-04 21:41 UTC, jasontedor reviewed
I left a few more, almost there.

2017-10-04 21:41 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/cluster/routing/OperationRouting.java
> +                    deprecationLogger.deprecated("[_primary] has been deprecated in 6.0+, and will be removed in 7.0; " +
The version here should be 6.1 (we are going to backport this to 6.x but not 6.0).

2017-10-04 21:41 UTC, jasontedor commented on docs/reference/search/request/preference.asciidoc
> +	shards. deprecated[6.0.0, will be removed in 7.0, use `_only_nodes` or `_prefer_nodes`]
This should be 6.1.0.

2017-10-04 21:41 UTC, jasontedor commented on rest-api-spec/src/main/resources/rest-api-spec/test/bulk/20_list_of_strings.yml
> +      version: " - 5.99.99"
Let's only skip to 6.0.99.

2017-10-04 23:14 UTC, jasontedor commented
@dnhatn Let's be careful when we merge this that the master branch does not break because of the BWC tests that use preferences. If you need help walking through how to test that locally, please let me know.

2017-10-04 23:15 UTC, jasontedor approved these changes
LGTM. This looks good, but please see my note about making sure that this doesn't break master because of the BWC tests there. So: a green CI PR build on this is not enough.

2017-10-09 00:21 UTC, merged

2017-10-09 00:23 UTC, dnhatn commented
@jasontedor The BWC tests are good for this branch. Thanks a lot for your guidance.