Update by Query is modified to accept short `script` parameter.
elastic/elasticsearch pull request #26841
Opened 2017-09-29 17:01 UTC by pozhidaevak

This change adding support of both long and short form of `script` parameter to `_update_by_query` request.
It should close the issue #24898 .

Changes in code:
static function `RestUpdateByQueryAction:parseScript()` is modified to accept `Object` parameter.
If `Object` is an instance of `Map` then it is a long form of `script` and old version of this function will be executed.
If `Object` is an instance of `String` then `Script` object will be created by using `Script(String)` constructor.

All tests are passed or ignored. However, `gradle check` is failed with the next message (I think it is not connected with my changes`
`* What went wrong:
Execution failed for task ':docs:integTestCluster#installAnalysisIcuPlugin'.
> A problem occurred starting process 'command '/Users/anton/Private/Coding/elasticsearch/docs/build/cluster/integTestCluster node0/elasticsearch-7.0.0-alpha1-SNAPSHOT/bin/elasticsearch-plugin''
`

2017-09-29 17:01 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-10-10 13:48 UTC, nik9000 requested changes
I left some minor requests for changes but it looks good to me! Thanks for doing this and I'm sorry for leading you astray with my mistaken comments earlier.

2017-10-10 13:48 UTC, nik9000 commented on modules/reindex/src/main/java/org/elasticsearch/index/reindex/RestUpdateByQueryAction.java
> +                return new Script((String) config);
Can you fix the indentation on this to line up?

2017-10-10 13:48 UTC, nik9000 commented on modules/reindex/src/main/java/org/elasticsearch/index/reindex/RestUpdateByQueryAction.java
> +        else {
We usually don't put a newline between `}` and `else`. Can you undo?

2017-10-10 13:48 UTC, nik9000 commented
@elasticmachine, test this please.

2017-10-10 13:51 UTC, nik9000 commented
Can you add a test for this? I'd add it to `qa/smoke-test-reindex-with-all-modules/src/test/resources/rest-api-spec/test/reindex/update_by_query/10_script.yml`.

2017-10-10 13:57 UTC, pozhidaevak commented
@nik9000, thanks for comments. 
I'll fix mistakes, add tests and commit it to this branch

2017-10-10 17:08 UTC, pozhidaevak commented
I created a test and tried to launch it, but I it's not executing. So, I've created [a topic on elastic forum](https://discuss.elastic.co/t/launching-tests-in-qa-smoke-test-reindex-with-all-modules/103410) with description of the error

2017-10-10 18:43 UTC, pozhidaevak commented
@nik9000, Thanks for help with testing. I pushed formatting changes and a new test

2017-10-11 21:57 UTC, nik9000 approved these changes

2017-10-11 21:57 UTC, merged

2017-10-11 22:05 UTC, nik9000 commented
Thanks @pozhidaevak! I've merged to master and will cherry-pick into 6.x and push that after the tests pass for me locally.

I didn't think to ask you before, but would you like to write the documentation update for this? [This](https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-update-by-query.html) page is generated by `docs/reference/doc/update-by-query.asciidoc`. The instructions for building the docs are [here](https://github.com/elastic/docs) or you can just make the change blind and I'll check it if you submit a PR. All the snippets in the docs are checked as part of the build. So if you add a snippet you can test that it works with `gradle docs:check`. That'll test all the snippets in the docs but that only takes a few minutes. If your snippet fails it'll print out reproduction steps you can use to rerun just that snippet.

2017-10-12 07:26 UTC, pozhidaevak commented
@nik9000, yah, I’ll add a documentation. Do I need to mention full version from which short form of script is accepted by API? If so, what is the version?

2017-10-12 14:06 UTC, nik9000 commented
@pozhidaevak you don't need to mention the version in the docs because I'll only backport your documentation change only to the branches that have the change. When the targeted version is released we'll flip "current" version of the docs to the version with your change. Folks that browse older versions of the docs won't get docs for your change.

The targeted version for this is 6.1/7.0. The master branch that you developed it against is 7.0 and the 6.x branch that I backported it to is planned to be 6.1.

2017-10-12 19:35 UTC, pozhidaevak commented
@nik9000, thanks for explaining.
I also think it will be useful to update `docs/reference/modules/scripting/using.asciidoc`.

I think I've found an inconsistency between code and documentation in the code we have `painless` as the default language. From `Script.java`:
```java
public static final String DEFAULT_SCRIPT_LANG = "painless";
//some code is omitted

// this constructor is used to create simple script
public Script(String idOrCode) {
        this(DEFAULT_SCRIPT_TYPE, DEFAULT_SCRIPT_LANG, idOrCode, Collections.emptyMap(), Collections.emptyMap());
    } 
```
But in the documentation it is stated (from using.asciidoc):

> The default language may be changed in the `elasticsearch.yml` config file by
> setting `script.default_lang` to the appropriate language.

However, it needs to be checked by running some tests...

2017-10-12 20:29 UTC, rjernst commented
`script.default_lang` was removed back in 5.0