Close #26771: beider_morse phonetic encoder failure when languageset unspecified
elastic/elasticsearch pull request #26848
Opened 2017-10-01 15:04 UTC by bkazez

This closes #26771. Based on jpountz's analysis: check languageset is neither null nor the empty array.

The previous behaviour was for an empty languageset array to cause the original tokens to be returned. Now, an empty languageset array will function the same as a non-existent languageset and trigger automatic language detection. This ensures that beider_morse phonetic encoder always returns a phonetic encoding of SOME sort, and that it matches the documented behavior.

2017-10-01 15:04 UTC, karmi commented
Hi @bkazez, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/26848.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

2017-10-01 15:04 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-10-01 15:08 UTC, bkazez commented
I added the other email address to my github profile. This should fix the CLA check failure.

2017-10-02 11:27 UTC, cbuescher requested changes
@bkazez thanks for opening this PR, the fix looks good at first looks, but can you also add a unit test that checks the expected behaviour? Some of the other TokenFilterFactoryTests in `org.lasticsearch.index.analysis` are probably a good start.

2017-10-02 11:29 UTC, cbuescher commented
@bkazez also regarding the failing CLA check, I was able to see your Github user and the associated email in our CLA database, but its not the email adress you used in the commit, so can you re-check that your Github profile contains the email adress you signed the CLA with or change the commit email adress accordingly?

2017-10-04 08:38 UTC, cbuescher reviewed
@bkazez the CLA check looks good now,  if you could add a unit test for this change we can merge it. If you have any questions please let me know.

2017-10-18 15:15 UTC, cbuescher commented
@bkazez are you still interested to work on this? I think adding a simple unit test is enought to get this in.

2017-10-21 12:15 UTC, bkazez commented
Sorry, I don't know the testing framework at all (or even Java/Eclipse
particularly well) and I don't think I will have time the next while to
learn it since I've just started a graduate program. It would be great if
someone else could write a quick test so we could get this in.

On Wed, Oct 18, 2017 at 4:16 PM, Christoph Büscher <notifications@github.com
> wrote:

> @bkazez <https://github.com/bkazez> are you still interested to work on
> this? I think adding a simple unit test is enought to get this in.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elastic/elasticsearch/pull/26848#issuecomment-337625788>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAD6Bbo0B1Tp1DtwgdT9ong9Bh5enUNHks5sthZmgaJpZM4Pp64d>
> .
>

2017-10-25 15:00 UTC, cbuescher commented
Hi @bkazez, thanks for letting us know. I hope you mind me closing this PR then and open a new PR. In case you have time to look at the tests that I added there, you could verify that it fixes your issue reported in #26771.

2017-10-25 15:00 UTC, closed without merging