Fix serialization errors when cross cluster search go to a single shard
elastic/elasticsearch pull request #26881
Opened 2017-10-04 14:08 UTC by javanna

The single shard optimization that we have in our search api changes the type of response returned by the query transport action name based on the shard search request. if the request goes to one shard, we will do query and fetch at the same time, hence the response will be different. The proxying layer used in cross cluster search was not aware of this distinction, which causes serialization issues every time a cross cluster search request goes to a single shard and goes through a gateway node which has to forward the shard request to a data node. The coordinating node would then expect a `QueryFetchSearchResult` while the gateway would return a `QuerySearchResult`.

Closes #26833

2017-10-04 14:30 UTC, s1monw requested changes
I left one comment, LGTM otherwise

2017-10-04 14:30 UTC, s1monw commented on core/src/main/java/org/elasticsearch/transport/TransportActionProxy.java
> +            service.sendRequest(targetNode, action, wrappedRequest, new ProxyResponseHandler<>(channel, wrappedRequest, responseFactory));
do we really need to hold on to the request or can we invoke the function here? I really think we shouldn't hold on to the request?!

2017-10-04 18:52 UTC, javanna commented
@s1monw my last commit should address your concerns ;) good points!

2017-10-04 19:07 UTC, s1monw approved these changes
LGTM

2017-10-04 20:39 UTC, merged

2017-10-13 04:03 UTC, hankduan commented
Does the tag mean this will be fixed in v5.6.3?

2017-10-13 05:06 UTC, tvernum commented
@hankduan You can read the release notes for 5.6.3 here: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/release-notes-5.6.3.html

This fix is the last item on that list.

2017-10-13 05:07 UTC, hankduan commented
Great, thank you!