Change default value to true for transpositions parameter of fuzzy query
elastic/elasticsearch pull request #26901
Opened 2017-10-05 19:08 UTC by alexshadow007

All other fuzzy queries (`match`, `multi_match`, `query_string` and `simple_query_string`) are using `true` as default value for `transpositions` parameter.

2017-10-05 19:08 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-10-06 09:05 UTC, jimczi requested changes
I left a comment to add a test.
Thanks @alexshadow007 !

2017-10-06 09:05 UTC, jimczi commented on core/src/main/java/org/elasticsearch/index/query/FuzzyQueryBuilder.java
Can you add a small test in `FuzzyQueryBuilderTests` that setting `transpositions` to true/false works ?
You can also remove the comment below:
````
//LUCENE 4 UPGRADE ...
````

2017-10-07 16:04 UTC, alexshadow007 commented
@jimczi Done

2017-10-11 11:16 UTC, jimczi approved these changes
Thanks @alexshadow007 !

2017-10-11 11:17 UTC, jimczi commented
@elasticmachine ok to test

2017-10-11 13:31 UTC, merged