Fix creating snapshot on missing index (#25359)
elastic/elasticsearch pull request #27056
Opened 2017-10-20 04:39 UTC by liketic

Closes #25359 

Actually I'm not sure if this is a bug. The root cause of the issue is the default `IndicesOptions` is `lenientExpandOpen` when parsing `IndicesOptions` from Map. However, as @PnPie mentioned in the issue, an integration test will not help to find this behaviour. I'm not clear why the logic between creating snapshot through `Client` and creating snapshot through REST API is different. So, please review this and leave your comments. 👍 

And, for `restore` API, I think same problem is exist. 

cc @jpcarey

2017-10-20 04:39 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-10-24 15:15 UTC, liketic commented
@abeyad Could you please review this? Thanks in advance.

2017-10-24 19:02 UTC, dnhatn commented
@elasticmachine please test this.

2017-10-25 05:01 UTC, liketic commented
@dnhatn I rebased and get test passed. Please test again.

2017-10-25 05:07 UTC, tvernum commented
@elasticmachine ok to test

2017-11-15 11:53 UTC, ywelsch requested changes
Indeed, the REST API is not aligned with the defaults of the transport client. I have made a suggestion that makes sure they're always aligned. Can you also fix RestoreSnapshotRequest?

2017-11-15 11:53 UTC, ywelsch commented on core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/CreateSnapshotRequest.java
> +        indicesOptions(IndicesOptions.fromMap(source, IndicesOptions.strictExpandOpen()));
I think this should be fixed by falling back to `indicesOptions` instead (which is equal to `IndicesOptions.strictExpandOpen()` by default)

2017-11-16 03:03 UTC, liketic commented
@ywelsch Thanks for reviewing this. I pushed 9c657d7fb08eddd8e58e8cf4239b99f2c7c1b4d0

2017-11-16 08:36 UTC, ywelsch commented
Thanks for the quick update. Can you also add a REST test in `rest-api-spec/test/snapshot.create/10_basic.yml` that checks that creating a snapshot with an unavailable index name fails? (i.e. that the defaults match what's in the documentation). Note that this will require adding a skip section (for tests in mixed clusters with older versions):

```
  - skip:
      version: " - 6.99.99"
```

For now, you can specify "-6.99.99", I will take care about changing it once we decide on backporting this PR.

Finally can you update the PR title and description? Thanks a lot!

2017-11-16 10:19 UTC, liketic commented
@ywelsch Thanks. I updated the REST test. Hope it makes sense.

2017-11-16 10:24 UTC, ywelsch commented
@elasticmachine retest this please

2017-11-16 13:51 UTC, ywelsch approved these changes
Thanks again @liketic. I took the liberty of editing the PR description and will merge this soon.

2017-11-16 15:03 UTC, merged