Fix a typo.
elastic/elasticsearch pull request #27066
Opened 2017-10-20 18:22 UTC by ismailarilik

'a index' should be 'an index'.

2017-10-20 18:22 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-10-25 11:02 UTC, cbuescher commented on docs/reference/docs/delete.asciidoc
> +to use the <<docs-delete-by-query,Delete By Query API>> to perform an
Looking at the context, I think it should rather be something like "to perform a delete for..."

2017-10-25 11:02 UTC, cbuescher requested changes
Hi @ismailarilik, thanks for opening this PR. I left a comment with some suggestions.

2017-10-26 05:49 UTC, ismailarilik commented
I have made the change you mentioned. But I also think this statement in the same sentence can be enhanced:

> which is in the format parent_type#parent_id

Users can write a query like that after this statement:

```
{
  parent_id: 'parent_type#parent_id'
}
```

Of course, this can be right. But I proofed this solution and I think it is much more elegant:

```
{
  parent_id: {
    type: parent_type,
    id: parent_id
  }
}
```

2017-10-26 09:04 UTC, cbuescher approved these changes
Thanks, I think the change is good as it is

2017-10-26 09:05 UTC, merged