#26990 prevent duplicate fields when mixing parent and root nested includes
elastic/elasticsearch pull request #27072
Opened 2017-10-21 16:43 UTC by original-brownbear

Fixes #26990 (I think :))

Fixed this by traversing the tree of `Nested` instances in the `Builder` for `RootObjectMapper` since it seemed to be the one place before instantiating the mappers where I can mutate builders and have the full tree of `Nested` available to me.
So my logic was:

* The duplicate fields arise from a child nested by more than one level, that is directly included in the root and also transitively included via a chain of parent(s).
 => Set all `include_in_root` to `false`, that are already covered by transitive chains of `include_in_parent == true`

2017-10-27 07:10 UTC, jpountz requested changes
I think you found the right place to fix the issue, however I spotted a bug (see comments).

2017-10-27 07:10 UTC, jpountz commented on core/src/main/java/org/elasticsearch/index/mapper/RootObjectMapper.java
> +                        included = nested.isNested() && nested.isIncludeInParent();
I don't think it is correct: `included` should also `true` if `nested.isIncludeInRoot` is true? Otherwise we might recurse on a wrong value.

2017-10-27 07:10 UTC, jpountz commented on core/src/main/java/org/elasticsearch/index/mapper/RootObjectMapper.java
> +                        if (included) {
However I agree that we should test for `if (nested.isNested() && nested.isIncludeInParent())` here.

2017-10-27 08:39 UTC, original-brownbear commented
@jpountz fixed + added a test that reproduced the bug you found. Also a little more readable now I think/hope, since now it's clearly visible that we're fixing only if included in parent and included in root are true simultaneously :)

2017-10-27 08:56 UTC, jpountz approved these changes
I just left a naming suggestion, but the change looks good to me!

2017-10-27 08:56 UTC, jpountz commented on core/src/main/java/org/elasticsearch/index/mapper/RootObjectMapper.java
> +                    boolean includedInParent = parentIncluded && isNested && nested.isIncludeInParent();
should we rename to something like `includeInRootViaParent` to make it clearer what this is about?

2017-10-27 09:00 UTC, original-brownbear commented
@jpountz I agree renamed variable :)

2017-10-27 10:04 UTC, original-brownbear commented
@jpountz build failure looks unrelated, should we retrigger Jenkins?

2017-10-27 10:21 UTC, jpountz commented
@elasticmachine please test it

2017-10-27 10:44 UTC, original-brownbear commented
@jpountz hmm no seems, there's an actual issue now. Failed the same way for me locally, sorry. Will fix shortly.

2017-10-27 11:07 UTC, original-brownbear commented
rebase against `master` fixed it locally, let's see what Jenkins says

2017-10-27 12:16 UTC, original-brownbear commented
I see the same error here for another PR and it seems to happen randomly locally https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/5141/console so not related it seems.

2017-10-27 12:16 UTC, original-brownbear commented
@elasticmachine please test it

2017-10-27 13:36 UTC, original-brownbear commented
@jpountz instability seems to be handled here https://github.com/elastic/elasticsearch/issues/27146 => good to squash + merge right? :)

2017-10-27 13:41 UTC, jpountz commented
Sure, I'll merge. Thanks @original-brownbear !

2017-10-27 13:48 UTC, original-brownbear commented
@jpountz np + thanks for the review :)

2017-10-30 15:20 UTC, original-brownbear commented
@jpountz ping :)

2017-10-31 09:01 UTC, merged

2017-10-31 09:01 UTC, jpountz commented
Thanks @original-brownbear !

2017-10-31 09:07 UTC, original-brownbear commented
np @jpountz  :)