lower fielddata circuit breaker's default limit
elastic/elasticsearch pull request #27162
Opened 2017-10-29 15:28 UTC by PnPie

As discussed in #27130, change fielddata circuit breaker default limit from 60% to 30%.

2017-10-29 15:28 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-10-29 19:25 UTC, dnhatn commented
@elasticmachine please test this.

2017-10-30 16:00 UTC, dakrone commented
In the #27130 we discussed going to 40% though, not 30%?

2017-10-30 19:11 UTC, PnPie commented
I changed it to 40%.

2018-12-04 07:37 UTC, danielmitterdorfer commented
@PnPie I had a quick look at your PR. Could you please:

1. Merge master and fix merge conflicts
2. Update the documentation in [circuit_breaker.asciidoc](https://github.com/elastic/elasticsearch/blob/master/docs/reference/modules/indices/circuit_breaker.asciidoc#field-data-circuit-breaker) so it reflects the new default.
3. Add a short note about this change to the [breaking changes docs for 7.0](https://github.com/elastic/elasticsearch/blob/master/docs/reference/migration/migrate_7_0/indices.asciidoc) next to "Parent circuit breaker changes"?

2018-12-08 13:02 UTC, PnPie commented
Hi @danielmitterdorfer I updated the PR with the changes you mentioned.

2018-12-10 09:20 UTC, danielmitterdorfer commented
@elasticmachine test this please.

2018-12-10 11:12 UTC, danielmitterdorfer commented
@elasticmachine test this please.

2018-12-10 13:03 UTC, danielmitterdorfer requested changes
@PnPie thanks for following up! Overall the change looks fine and also CI was green. I'd just ask you to change the wording in the migration docs (I've left a suggestion). Once this is in, I think we're good to merge. :)

2018-12-10 13:03 UTC, danielmitterdorfer commented on docs/reference/migration/migrate_7_0/indices.asciidoc
> +Lower the default field data circuit breaker limit from 60% to 40% as `doc_values` was introduced for
Can we please change the wording a little bit?

```suggestion
As doc values have been enabled by default in earlier versions of Elasticsearch,
there is less need for fielddata. Therefore, the default value of the setting
`indices.breaker.fielddata.limit` has been lowered from 60% to 40% of the JVM
heap size. 
```

2018-12-10 14:48 UTC, PnPie commented
Hi @danielmitterdorfer I changed the docs as you suggested.

2018-12-10 15:38 UTC, danielmitterdorfer commented
@elasticmachine test this please.

2018-12-10 15:39 UTC, danielmitterdorfer approved these changes
Looks good to me. Thank you for your pull request and thanks for iterating @PnPie. Once the CI build is green, I'll merge it.

2018-12-11 07:33 UTC, danielmitterdorfer commented
@elasticmachine test this please.

2018-12-11 10:30 UTC, merged

2018-12-11 10:31 UTC, danielmitterdorfer commented
This closes #27130