BUG: Fixed ByteBuf leaking in org.elasticsearch.http.netty4.Netty4Htt…
elastic/elasticsearch pull request #27222
Opened 2017-11-02 06:37 UTC by original-brownbear

I found a spot where we were leaking `ByteBuf` here:

You can reproduce the leak by sending a request with broken HTTP headers like e.g.

```sh
curl -XPOST -H "Content-Type: application/json" -H "Content-Type: application/json" -d '{"foo": "bar"}' http://127.0.0.1:9200/test/type
```
(note duplicate `Content-Type`)

This results in the following exception being thrown:

```sh
[2017-11-02T07:29:30,856][WARN ][o.e.h.n.Netty4HttpServerTransport] [node-0] caught exception while handling client http traffic, closing connection [id: 0x4c59c8e2, L:/127.0.0.1:9200 - R:/127.0.0.1:51618]
java.lang.IllegalArgumentException: only one Content-Type header should be provided
	at org.elasticsearch.rest.RestRequest.parseContentType(RestRequest.java:426) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.rest.RestRequest.<init>(RestRequest.java:84) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.http.netty4.Netty4HttpRequest.<init>(Netty4HttpRequest.java:49) ~[transport-netty4-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:67) ~[transport-netty4-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at org.elasticsearch.http.netty4.pipelining.HttpPipeliningHandler.channelRead(HttpPipeliningHandler.java:68) [transport-netty4-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.13.Final.jar:4.1.13.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

as well as this leak being logged:

```sh
[2017-11-02T07:29:30,941][ERROR][i.n.u.ResourceLeakDetector] LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 6
#6:
	io.netty.buffer.AdvancedLeakAwareByteBuf.slice(AdvancedLeakAwareByteBuf.java:72)
	io.netty.buffer.CompositeByteBuf.addComponent0(CompositeByteBuf.java:259)
	io.netty.buffer.CompositeByteBuf.addComponent(CompositeByteBuf.java:195)
	io.netty.buffer.WrappedCompositeByteBuf.addComponent(WrappedCompositeByteBuf.java:524)
	io.netty.buffer.AdvancedLeakAwareCompositeByteBuf.addComponent(AdvancedLeakAwar [...]

2017-11-02 12:59 UTC, jasontedor requested changes
I left a comment.

2017-11-02 12:59 UTC, jasontedor commented on modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequestHandler.java
> +            request.release();
I don't think this is right, I think this should only be released here if we added a retain which only happens if `msg` is an instance of `HttpPipelinedRequest`.

2017-11-02 13:19 UTC, original-brownbear commented
@jasontedor thanks, my mistake. Made it only fire the `release` for the pipelined request now :)

2017-11-02 13:36 UTC, jasontedor approved these changes
LGTM.

2017-11-02 13:36 UTC, jasontedor commented
Thanks @original-brownbear, this looks good to me now. I will pull this in after CI completes.

2017-11-02 14:28 UTC, original-brownbear commented
@jasontedor thanks for the review :) Failure looks unrelated?

```sh
14:23:17 Executing task ':checkout-6.x:core:compileJava' (up-to-date check took 0.485 secs) due to:
14:23:17   No history is available.
14:23:17 All input files are considered out-of-date for incremental task ':checkout-6.x:core:compileJava'.
14:23:17 :core:compileJava - is not incremental (e.g. outputs have changed, no previous execution, etc.).
14:23:17 Compiling with Java command line compiler '/usr/lib/jvm/java-8-openjdk-amd64/bin/javac'.
14:23:18 Starting process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/javac''. Working directory: /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request/distribution/bwc/build/bwc/checkout-6.x/core Command: /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -J-Xmx1g @/var/lib/jenkins/workspace/elastic+elasticsearch+pull-request/distribution/bwc/build/bwc/checkout-6.x/core/build/tmp/compileJava/java-compiler-args.txt
14:23:18 Successfully started process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/javac''
14:23:18 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
14:23:37 /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request/distribution/bwc/build/bwc/checkout-6.x/core/src/main/java/org/elasticsearch/search/SearchService.java:652: error: cannot find symbol
14:23:37             throw new QueryPhaseExecutionException(context,
14:23:37                       ^
14:23:37   symbol:   class QueryPhaseExecutionException
14:23:37   location: class SearchService
14:23:44 Note: Some input files use or override a deprecated API.
14:23:44 Note: Recompile with -Xlint:deprecation for details.
14:23:44 Note: Some input files use unchecked or unsafe operations.
14:23:44 Note: Recompile with -Xlint:unchecked for details.
14:23:44 1 error
14:23:44 :checkout-6.x:core:compileJava FAILED
```

2017-11-02 14:30 UTC, original-brownbear commented
I guess it was related to https://github.com/elastic/elasticsearch/commit/081e7e34db3c288b316cb64bf8757d53a00eac12

2017-11-03 00:22 UTC, merged

2017-11-03 00:23 UTC, jasontedor commented
Thanks again @original-brownbear\.