Fix cat API help with url parameters
elastic/elasticsearch pull request #27598
Opened 2017-11-29 21:17 UTC by olcbean

The `_cat` API was throwing IllegalArgumentException if url parameters were provided
```
# worked
GET _cat/shards?help
GET _cat/shards/test_index
# returned an exception
GET _cat/shards/test_index?help
```
Fixes #27424

2017-11-29 21:17 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-11-29 21:25 UTC, rjernst commented on core/src/main/java/org/elasticsearch/rest/action/cat/AbstractCatAction.java
> +            request.params().keySet().forEach(request::param);
Shouldn't this only be consuming the `help` key? Any random other params should still cause an error.

2017-11-30 02:24 UTC, jasontedor requested changes
Sorry, this change is broken. And I question if we should be making a change that introduces any confusion here whatsoever. If I ask Elasticsearch:

`GET /_cat/shards/garbage_index_that_does_not_exist?help`

What should the behavior be? Help? 404 index not found? Unrecognized parameter? No matter what it's confusing.

2017-11-30 02:24 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/rest/action/cat/AbstractCatAction.java
> +            request.params().keySet().forEach(request::param);
As @rjernst says, this incredibly broken behavior. It invalidates all the work we did to reject unrecognized URL parameters, now it accepts any parameters including garbage parameters.

2018-01-30 06:50 UTC, olcbean commented
Closing as there is no clear decision how to 'correctly' implement the support of `help` when there are other url params.

2018-01-30 06:50 UTC, closed without merging