Improve error msg when a field name contains only white spaces
elastic/elasticsearch pull request #27709
Opened 2017-12-07 20:18 UTC by olcbean

Till now if a field name is empty or contains only white spaces, the error msg is `object field starting or ending with a [.] makes object resolution ambiguous`.

This PR explicitly check if the field name contains only white spaces and result in the error `object field cannot contain only white spaces`.

Fixes #27701

CC @danielmitterdorfer @dakrone

2017-12-07 20:18 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2017-12-08 15:10 UTC, cbuescher commented
@elasticmachine test this please

2017-12-08 15:41 UTC, dakrone requested changes
I left two comments about the messages

2017-12-08 15:41 UTC, dakrone commented on core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java
> +                                "object field cannot contain only white spaces: ['" + fullFieldPath + "']");
this should be "white spaces" -> "whitespace"

2017-12-08 15:41 UTC, dakrone commented on core/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java
> +                "object field cannot contain only white spaces: ['top.aoeu. ']"));
"white spaces" -> "whitespace"

2017-12-08 18:30 UTC, olcbean commented
@dakrone thanks! I just modified the msg.

2017-12-08 20:46 UTC, merged

2017-12-08 20:47 UTC, dakrone commented
Merged, thanks @olcbean!