Use IndexWriter#flushNextBuffer to free memory
elastic/elasticsearch pull request #27753
Opened 2017-12-11 13:33 UTC by s1monw

Lucene now has the ability to move the biggest ram buffer to disk in a
controlled fashion. This wasn't possilbe before or only in a way that would tie
up indexing threads for flushes. With `flushNextBuffer` the `IndexWriter` uses
the caller thread to do all computations and disk IO instead of an indexing
thread which seperates the concerns for indexing and flushing to disk. This
means we also don't need to flush all buffers at the same time (as in a
refresh) but can only take the biggest one to disk to ensure we write the
larger segments and minimize merge costs and disk IO. This also prevents heavy
load on disks when multipl threads flush to disk on refresh every so often
which can maximize throughput.

2017-12-11 14:08 UTC, fonghuiyue commented
v7.0

2017-12-17 19:53 UTC, jpountz requested changes
Can we avoid creating classes in the oal.index package to have access to pkg-private methods?

2017-12-18 07:04 UTC, s1monw commented
> Can we avoid creating classes in the oal.index package to have access to pkg-private methods?

no we can't in this case... not sure how to effectively expose this otherwise

2017-12-18 10:32 UTC, bleskes requested changes
production code LGTM. I left an ask around testing

2017-12-18 10:32 UTC, bleskes commented on core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +    public long writeIndexingBuffer(boolean execute) throws EngineException {
this can be private.

2017-12-18 10:32 UTC, bleskes commented on core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
> +    public void testWriteIndexingBuffer() throws IOException {
can we add a version of this test that also looks at the live version size and falls into a full refresh?  I also don't see anywhere a test that shows that the live version map memory usage is reflected in the InternalEngine#getIndexBufferRAMBytesUsed method. Maybe I miss it though (as it is an existing problem).

2017-12-18 14:16 UTC, bleskes commented
@s1monw I think this can go into 6.2, no?

2017-12-19 18:20 UTC, jpountz reviewed
I'm wondering whether we should do something in case flushing one buffer from each shard doesn't free up enough memory? Should we for instance run the status checker again if we ended up consuming all entries from the queue, or poll from the queue directly from the refresh threadpool so that we can add entries back to the queue after having called `shard.writeIndexingBuffer()`?

2018-08-16 13:58 UTC, javanna commented
@s1monw should this be adapted and merged?

2018-08-20 07:11 UTC, s1monw commented
closing this in favor of https://github.com/elastic/elasticsearch/issues/29368

2018-08-20 07:11 UTC, closed without merging