Limit the analyzed text for highlighting
elastic/elasticsearch pull request #27934
Opened 2017-12-20 21:44 UTC by mayya-sharipova

- Introduce index level settings to control the max number of character
to be analyzed for highlighting
- Throw an error if analysis is required on a larger text

Closes #27517

2017-12-20 22:48 UTC, jimczi requested changes
The changes look good, I left some comment regarding naming.

2017-12-20 22:48 UTC, jimczi commented on core/src/main/java/org/elasticsearch/index/IndexSettings.java
> +        Setting.intSetting("index.analyze.max_analyzed_offset", 10000, 1, Property.Dynamic, Property.IndexScope);
Maybe `index.highlight.max_analyzed_offset` to indicate that it applies to highlighting only ?

2017-12-20 22:48 UTC, jimczi commented on core/src/main/java/org/elasticsearch/index/IndexSettings.java
> +    public int getMaxAnalyzedOffset() { return this.maxAnalyzedOffset; }
Same here, getHighlightMaxAnalyzedOffset ?

2017-12-21 07:59 UTC, jimczi approved these changes
LGTM

2017-12-21 15:19 UTC, merged

2017-12-21 15:20 UTC, mayya-sharipova commented
@jimczi thanks for the review, Jim

2018-01-09 15:24 UTC, Bargs commented
Hi @mayya-sharipova and @jimczi. I was just testing this change and it looks like it's going to break Kibana for users with large fields. It's quite common for users to have fields with >10000 characters so with this change in 6.2 Kibana's Discover (which uses highlighting) will start throwing errors. 

Is it necessary to throw an error? Without the error, users might see a change in highlighting on large fields but at least Kibana wouldn't stop working. The downside is that users may think highlighting is broken if they see matching text that is not highlighted. That might be an acceptable tradeoff and breaking change in a major release but I think either change might be surprising in a minor.

<img width="1440" alt="screen shot 2018-01-09 at 10 08 05 am" src="https://user-images.githubusercontent.com/6239176/34728205-414a9394-f527-11e7-832d-c05e6ef0e769.png">

2018-01-09 15:43 UTC, jimczi commented
> That might be an acceptable tradeoff and breaking change in a major release but I think either change might be surprising in a minor

The setting should be unlimited by default in 6.2. @mayya-sharipova can you change the value for that branch and maybe add a deprecation warning for texts bigger than the default limit in 7 ?

2018-01-09 18:59 UTC, mayya-sharipova commented
@Bargs thank you for reporting this. Have you tested this on 6.2 and experienced the error? 
Because for 6.2 we don't throw an error, we just issue a deprecation warning: 
https://github.com/elastic/elasticsearch/blob/6.x/core/src/main/java/org/apache/lucene/search/uhighlight/CustomUnifiedHighlighter.java#L133

2018-01-09 19:42 UTC, mayya-sharipova commented
@jimczi So,  for 6.2 do we want to do following:
if the settings != LIMIT_& and text exceeds the limit, we will issue an error
if the setting == LIMIT_7  and text exceeds the limit, we will issue a deprecation warning happening in the major version

Sorry, slack has connection problems for me, can't open it for 30 mins

2018-01-09 21:39 UTC, Bargs commented
Sorry, like a fool I only tested quickly in master. If 6.2 doesn't respond with an error, Kibana should still work fine. Though we might end up spamming their deprecation logs on every search request.

2018-01-10 11:37 UTC, jimczi commented
> So, for 6.2 do we want to do following:
if the settings != LIMIT_7 and text exceeds the limit, we will issue an error
if the setting == LIMIT_7 and text exceeds the limit, we will issue a deprecation warning happening in the major version

For 6.2 I would set the limit to -1 and allow updating this setting only if the value is > 0. This way if the value is -1 you know that the setting is not explicitly set. Then if the value is -1 you can issue a deprecation warning when the text exceeds the default value set in 7 (`10,000`) and if it's not -1 you can throw an error if the text exceeds the provided threshold.

2018-03-22 06:04 UTC, kiju98 commented
👍