Enable ASN support for Ingest GeoIP plugin.
elastic/elasticsearch pull request #27958
Opened 2017-12-22 06:54 UTC by kiawin

Closes #27849

2018-01-04 09:03 UTC, martijnvg commented
@elasticmachine please test this

2018-01-04 09:03 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-04 09:03 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-04 15:46 UTC, martijnvg requested changes
@kiawin I left some comments. Looks good in general.

2018-01-04 15:46 UTC, martijnvg commented on plugins/ingest-geoip/src/test/resources/rest-api-spec/test/ingest_geoip/20_geoip_processor.yml
> +  - match: { _source.geoip.asn: "5615" }
This should be `5615` instead of `"5615"`.

2018-01-04 15:46 UTC, martijnvg commented on plugins/ingest-geoip/src/test/resources/rest-api-spec/test/ingest_geoip/20_geoip_processor.yml
> +  - match: { _source.geoip.organization_name: "KPN B.V." }
a new line at the end of this file is required.

2018-01-04 15:46 UTC, martijnvg commented on buildSrc/version.properties
> +jackson           = 2.9.3
Unfortunately ES can't be upgraded to the latest Jackson 2.9.x release: https://github.com/elastic/elasticsearch/pull/27032#issuecomment-340783545

But I think ASN support will still work with Jackson 2.8.10, so lets undo the Jackson upgrade here.

2018-01-04 15:46 UTC, martijnvg commented on plugins/ingest-geoip/build.gradle
> +  compile ('com.maxmind.geoip2:geoip2:2.10.0')
This library upgrade then also needs to be revered.

2018-01-04 19:33 UTC, kiawin commented
@martijnvg done the changes. back to you :)

2018-01-05 10:05 UTC, martijnvg approved these changes
Thanks @kiawin! This PR looks good to me now.

2018-01-05 10:09 UTC, martijnvg commented
@elasticmachine please test this

2018-01-05 13:08 UTC, merged