[docs] Fix typoes in comment in source code
elastic/elasticsearch pull request #28098
Opened 2018-01-05 09:22 UTC by aeroastro

While reading some code, I have found out some typoes.

* Gramatical Typoes
* Comment on query_and_fetch, which has already been removed. (#22996)

2018-01-05 09:22 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-05 09:22 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-05 11:13 UTC, cbuescher requested changes
@aeroastro thanks for the changes, I agree with all of them but one where I left a comment. Can you update, then I will merge this.

2018-01-05 11:13 UTC, cbuescher commented on core/src/main/java/org/elasticsearch/search/SearchService.java
> +     * Returns true if the given search source builder can be early terminated by rewriting to a match none query. Or in other words
I think `iff` is intended here, meaning "if and only if" here (https://en.wikipedia.org/wiki/If_and_only_if), I'd leave this as is.

2018-01-07 04:19 UTC, aeroastro commented
Thank you for your review.
I have fixed the issue by leaving iff as is at 1cfcda4c2cb26a053f7a3bace0b04dff48795022

2018-01-08 09:38 UTC, cbuescher requested changes
@aeroastro thanks, looks like instead of changing back you changed another occurance of "if". Left a comment, can you correct this please?

2018-01-08 09:38 UTC, cbuescher commented on core/src/main/java/org/elasticsearch/search/SearchService.java
> -     * if the execution of a the search request can be early terminated without executing it. This is for instance not possible if
Looks like you just changed both the first occurance of "iff" and the later "if" to the other version. Could you just change them back?

2018-01-09 08:56 UTC, aeroastro commented
Sorry about that.
I have fixed the mistake at e4123c9

2018-01-09 08:58 UTC, cbuescher approved these changes
Thanks, LGTM. I will merge this soon.

2018-01-09 09:01 UTC, merged

2018-01-09 16:19 UTC, aeroastro commented
Thank you 🐱