parse long first
elastic/elasticsearch pull request #28118
Opened 2018-01-06 17:50 UTC by matarrese

Hi all,
if someone is already working on that please ignore my pull request otherwise let me know your thoughts about my solution!
Thanks,
Antonio
#28012

2018-01-06 17:50 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-06 17:50 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-06 18:00 UTC, jasontedor requested changes
I left a comment.

2018-01-06 18:00 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/StringTerms.java
> +            }
I think a comment why this is being swallowed is in order here.

2018-01-06 18:00 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/StringTerms.java
> +            } catch (NumberFormatException numberFormatException) {
I think it's best to name the exception as `ignored` here; it makes it clearer that the swallowing is intentional (and some IDEs complain about unused exceptions unless they are named `ignored`).

2018-01-06 18:02 UTC, jasontedor commented
@matarrese In general it is best to add more context to your commit messages. A good commit message has a brief one-line summary (usually less than fifty characters), and then a more verbose message explaining the reasoning behind the change (wrapped to 72-column width). A more thorough explanation of this is [here](https://chris.beams.io/posts/git-commit/).

2018-01-06 18:49 UTC, jasontedor requested changes
This comment is not sufficient.

2018-01-06 18:49 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/StringTerms.java
> +            //if it fails, it will be parsed as a Double
This comment is a translation of the code to English, information that can already be gleaned by reading the code. The comment I am looking for here is *why* the code is written the way that it is written. *Why* are we doing this, why is it okay to swallow an exception?

2018-01-07 15:34 UTC, matarrese commented
Hi @jasontedor thank you for all your comments. 
I was going to write some tests but I have just checked that this change (for both cases) is already well covered by the tests contained in these classes: `DoubleTermsIT.testScriptSingleValue` and `LongTermsIT.testScriptSingleValue`. 
Let me know what do you think about the update comment and the necessity to write some additional tests.

2018-01-07 15:43 UTC, jasontedor commented
@matarrese This functionality can not be covered by existing tests; there is new code with different behavior than the what happened previously being added here?

2018-01-07 22:13 UTC, matarrese commented
Please have a look at the newly added asserts

2018-01-08 12:09 UTC, jasontedor requested changes
I left another comment about the comment.

2018-01-08 12:09 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/StringTerms.java
> +                //failed to be parsed as a Long, it will be parsed as a Double
This comment is still not explaining why we are doing this. It's again an English translation of the code. May I suggest going back to the original issue and reading why we are making this change? That is what we want to say here, the why.

2018-01-10 11:09 UTC, jasontedor reviewed
I left another comment.

2018-01-10 11:09 UTC, jasontedor commented on core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/StringTerms.java
> +                //failed to detect an Integer
@matarrese This is still not what we would want in a comment here. We want to explain why we doing this. Please look at the original issue that provoked this change and leave a comment here that explains the why behind first parsing as a long, and then leniently parsing as a double.

2018-01-13 19:00 UTC, matarrese commented
@jasontedor please have a look at the new comment

2018-01-24 11:57 UTC, jasontedor commented
retest this please

2018-01-25 11:32 UTC, jasontedor commented
retest this please

2018-01-25 20:07 UTC, jasontedor commented
retest this please

2018-01-25 23:51 UTC, jasontedor commented
retest this please

2018-01-26 11:22 UTC, merged

2018-01-26 11:35 UTC, jasontedor commented
Thanks @matarrese.