Proposed changes to revise current/ingest.html . . .
elastic/elasticsearch pull request #28212
Opened 2018-01-14 03:04 UTC by fbsolo

Proposed changes for

https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html

to improve the text flow, style, and readability . . .

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2018-01-14 03:04 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-14 03:04 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-14 03:11 UTC, fbsolo commented
I did sign the CLA a few minutes ago, but I am not a member of Elasticsearch. LMK what further steps I should take.

Thank you!

- Frank Solomon
  fbsolo@gmail.com

2018-01-14 03:11 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-14 03:11 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-15 09:43 UTC, cbuescher requested changes
@fbsolo thanks a lot for your contribution, I think it really improves the current documentation. Your CLA signing looks good, however I left two small comments about things I'd like you to change, but once they are adressed I'm happy to merge it.

2018-01-15 09:43 UTC, cbuescher commented on docs/reference/ingest.asciidoc
> +To pre-process documents before indexing, define a pipeline that specifies a series of
Can you keep the links to the pipeline and ingest-processor documentation? I think they are useful.

2018-01-15 09:43 UTC, cbuescher commented on docs/reference/ingest.asciidoc
> +To use a pipeline, simply specify the pipeline parameter on an index or bulk request. This
The backtics around "pipeline" shouldn't be removed here, we use them to highlight json or url parameters (like in this case).

2018-01-15 20:12 UTC, fbsolo commented
Done:

[https://github.com/elastic/elasticsearch/pull/28212/commits/0e333a7da8c8dedb9e825f142637b1db60b124a3]

2018-01-15 20:14 UTC, fbsolo commented
[Done](https://github.com/elastic/elasticsearch/pull/28212/commits/0e333a7da8c8dedb9e825f142637b1db60b124a3).

2018-01-16 08:34 UTC, cbuescher approved these changes
@fbsolo thanks for the update, will merge this in.

2018-01-16 08:35 UTC, merged