Update getting-started.asciidoc
elastic/elasticsearch pull request #28249
Opened 2018-01-16 17:28 UTC by wr0ngc0degen

since it's a JSON-style query request body it should be a POST not GET request

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2018-01-16 17:28 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-16 17:28 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-17 09:55 UTC, DaveCTurner requested changes
The verb is correct, and we use `GET` throughout the rest of this section too (see e.g. https://www.elastic.co/guide/en/elasticsearch/reference/current/_executing_searches.html) so this should remain as it is.

However, the following line does say that we "POST" the query which isn't right. I don't think we need to mention the HTTP verb in that sentence, so that's the fix I'd prefer.

Additionally, this change is opened against `6.1` instead of `master` because it came through the doc editor. Please could you rebase it against `master` and update the target branch to match?

2018-02-05 13:34 UTC, cbuescher commented
@wr0ngc0degen any interest in changing this PR like @DaveCTurner suggested to get this in? Otherwise I think we should close this.

2018-03-26 13:28 UTC, cbuescher commented
Closing, @wr0ngc0degen if you would like to make the changes suggested here, please reopen as a PR against master.

2018-03-26 13:28 UTC, closed without merging