Discontinue archiving broken cluster settings
elastic/elasticsearch pull request #28253
Opened 2018-01-16 21:21 UTC by mayya-sharipova

Currently unknown or invalid cluster settings get archived.
If archived settings are still present in the cluster,
updating other cluster settings will become impossible,
as an error will be thrown about the archived settings
being invalid.

For a better user experience, we stop archving broken cluster settings.
Instead, we will fail to recover the cluster state.
The solution for users in an upgrade case would be to rollback
to the previous version, address the settings that would be unknown
or  invalid the next major version, and then proceed with the upgrade.

Closes #28026

2018-03-30 00:02 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-09-21 06:22 UTC, danielmitterdorfer requested changes
@mayya-sharipova I am sorry that reviewing this fell through the cracks. I did an initial review based on the current code. Glancing at the current labels I also wonder whether we should just keep this for 7.0.0 and not backport it given that this is a breaking change?

2018-10-17 15:01 UTC, mayya-sharipova commented
@danielmitterdorfer  Hi Daniel, thank so much for your feedback.  I wonder if this change is still relevant after @jasontedor's PR: https://github.com/elastic/elasticsearch/pull/28888

2018-11-09 07:52 UTC, danielmitterdorfer commented
@mayya-sharipova I agree that this PR seems obsolete with #28888 already being merged. As far as I understood the discussion in the related issue https://github.com/elastic/elasticsearch/issues/28026, and specifically https://github.com/elastic/elasticsearch/issues/28026#issuecomment-375965818, the PR #28888 should actually fix #28026? Can you please double-check with Jason and close this PR and update / close issue #28026 accordingly depending on the result of your discussion?

2018-12-07 12:00 UTC, mayya-sharipova commented
Closing this PR, as it looks like it is stalled. If the issue is still relevant, people are welcome to work on it.

2018-12-07 12:00 UTC, closed without merging