Improve error message when installing an offline plugin
elastic/elasticsearch pull request #28298
Opened 2018-01-18 15:00 UTC by mayya-sharipova

Provide more actionable error message when installing an offline plugin
in the plugins directory, and the `plugins` directory for the node
contains plugin distribution.

Closes #27401

2018-01-29 16:44 UTC, jasontedor requested changes
I think we can detect this situation sooner and much more clearly (e.g., in `install`). Would you take another approach?

2018-01-29 16:44 UTC, jasontedor commented on distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java
> +        } catch (IllegalStateException e) {
I do not think this is right, we could catch an IllegalStateException for JAR hell and really we are only trying to detect when the offline plugin is contained in the plugins folder.

2018-01-31 08:35 UTC, rjernst commented
I think `downloadZip` would be the best place to detect this. Once the URL is created, see if it is a file URL, and if it is, convert it to a local path, then see if the path is prefixed by the plugins dir?

2018-03-14 02:29 UTC, jasontedor commented
@mayya-sharipova Would you be able to incorporate the feedback here and iterate on this PR?

2018-03-14 02:36 UTC, mayya-sharipova commented
@jasontedor I have already incorporated it. I followed the last suggestion from Ryan.

2018-03-14 02:39 UTC, jasontedor commented
@mayya-sharipova I see, again we see the problem with force pushing to a pull request; I do not think anyone knew that new commits were pushed here. Please ping when you push commits. Also, would you resolve the existing merge conflicts?

2018-03-14 12:58 UTC, jasontedor approved these changes
Thank you @mayya-sharipova, the change looks good. I left one comment.

2018-03-14 12:58 UTC, jasontedor commented on distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java
> +                    "Make sure `plugins` directory doesn't contain the plugin distribution! " );
I think we can have a more actionable error message here like: `"the plugins directory [" + pluginsDir + "] can not contain the plugin distribution [" + pluginsFile + "]; move the distribution to an alternate location"`

2018-03-14 12:58 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-03-14 23:19 UTC, merged

2018-03-14 23:26 UTC, jasontedor commented
@mayya-sharipova I’m confused. I left a comment about the user-facing message but I do not see that incorporated here nor a response to that comment although this change has been merged?

2018-03-14 23:30 UTC, jasontedor commented
Oh I see that you force pushed! Please prefer to push additional commits instead of force pushing. There are generally very few situations in which we need to force push.