Read and write metrics represented in bytes and printed as byteSizeField
elastic/elasticsearch pull request #28367
Opened 2018-01-24 21:52 UTC by kujon

This is a proposed solution to https://github.com/elastic/elasticsearch/issues/27037

2018-01-24 21:52 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-24 21:52 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-25 03:44 UTC, jasontedor requested changes
Thanks for the PR yet I left thoughts on #27037.

2018-04-24 08:51 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-05-07 12:36 UTC, javanna commented
#27037 which originated this PR got closed as won't fix, from the discussion there we decided to keep things as they are. Closing.

2018-05-07 12:36 UTC, closed without merging