Add logging for index commit deletion policy
elastic/elasticsearch pull request #28448
Opened 2018-01-30 18:21 UTC by dnhatn

This would help us to figure out which index commit that an engine started with or used in peer-recovery.

Relates #28405

2018-01-30 19:31 UTC, bleskes requested changes
Looks great. I left some minor feedback. Let me know what you think.

2018-01-30 19:31 UTC, bleskes commented on server/src/main/java/org/apache/lucene/index/IndexCommits.java
> +    public static String commitDescription(IndexCommit commit) {
It will be great if we can move it somewhere rather than open a new class. Maybe move this to CombinedDeltionPolicy? (see my main comment)

2018-01-30 19:31 UTC, bleskes commented on server/src/main/java/org/apache/lucene/index/IndexCommits.java
> +        } catch (IOException e) {
I think all places that use this can throw an IOException no? can't we just let it bubble up?

2018-01-30 19:31 UTC, bleskes commented on server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +                if (logger.isDebugEnabled()) {
we will already log the safe commits and deletions in the onInit of the CombinedDeletionPolicy, maybe this is an overkill?

2018-01-30 19:31 UTC, bleskes commented on server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +                    logger.debug("Open engine with the safe commit [{}], global checkpoint [{}], existing commits [{}]",
we will already log the safe commits and deletions in the onInit of the CombinedDeletionPolicy, maybe this is an overkill?

2018-01-30 19:31 UTC, bleskes commented on server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java
> +                logger.debug("Start peer-recovery with safe commit [{}], global checkpoint [{}], existing commits [{}]",
Higher up at the caller we log in trace. If we want debug info then I think we should have a nice summary of the recovery starting info. I would recommend just making this trace for now. Also nit-  maybe say something like "calculated starting seq# based on..."

2018-01-31 01:18 UTC, dnhatn commented
@bleskes I've addressed your feedbacks. Please take another look. Thank you!

2018-01-31 15:30 UTC, bleskes approved these changes
LGTM. Thanks.

2018-01-31 16:08 UTC, dnhatn commented
Thanks @bleskes for reviewing.

2018-01-31 16:09 UTC, merged