Update 5.6 Breaking Changes doc
elastic/elasticsearch pull request #28470
Opened 2018-01-31 23:15 UTC by mstruve

Added a section about the breaking changes made to referencing parent docs in aggregations and scripts. This broke when my company upgraded to 5.6 and we were not expecting it since it was not listed here under breaking changes.

2018-01-31 23:15 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-01-31 23:15 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-02-01 01:57 UTC, jasontedor requested changes
I left a comment.

2018-02-01 01:57 UTC, jasontedor commented on docs/reference/migration/migrate_5_6.asciidoc
> +Previously in Elasticsearch parent documents could be aggregated on or referenced in a script using `_parent`. Now in order to reference a parent document in an aggregation or script you must do `_pa
Thanks for the PR. This should not be a hard link but rather a doc link to the `mapping-parent-field` section in the docs. Can you help with this @jimczi?

Also, would you please wrap the lines at 80-columns?

2018-02-01 02:17 UTC, jasontedor approved these changes
This looks good now! Can you double check and integrate @jimczi?

2018-02-01 08:00 UTC, jimczi reviewed
LGTM, thanks @mstruve and @jasontedor

2018-02-01 08:01 UTC, merged