Update s3 secure settings
elastic/elasticsearch pull request #28517
Opened 2018-02-05 09:29 UTC by albertzaharovits

Secure settings for the S3 repository plugin are update-able.
AWSS3 clients have to be requested from the `InternalAwsS3Service` service for each use. These client instances cannot be stored and used at a later time because they can change if their settings change. The client request and client update logic is protected by a read-write lock.

TODOs:
fix existing tests
add tests for reload
fail if removing settings in use by the repository ?
keep existing settings override from cluster settings ?

2018-02-13 10:11 UTC, s1monw requested changes
I like it. I left some comments

2018-02-13 10:11 UTC, s1monw commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/InternalAwsS3Service.java
> +    private final ConcurrentHashMap<String, AmazonS3> clientsCache;
lets make this an immutable map instead. That way we don't need a read-write lock and can just make the method that changes the reference synchronized. Also for the `AmazonS3Wrapper` we can just use a reference counter. We already have the infrastructure for it in `org.elasticsearch.common.util.concurrent.AbstractRefCounted` lemme know if you need help with this.

2018-02-13 10:11 UTC, s1monw commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/InternalAwsS3Service.java
> +            // clear previously cached clients
++ I like that we completely destroy it once we are refreshing the settings.

2018-02-13 10:11 UTC, s1monw commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobContainer.java
> -        return AccessController.doPrivileged((PrivilegedAction<Map<String, BlobMetaData>>) () -> {
can we please not change the way we use AccessController here. We can do this in a sep. change but this is a cause of trouble and hard to understand why it's needed if at all

2018-02-16 11:56 UTC, albertzaharovits commented
@s1monw I have addressed your feedback.
The client cache is a volatile reference to an immutable map.
Also, `AmazonS3Wrapper`interface extends `RefCounted` *and* `Releasable`. The implementation extends `AbstractRefCount`. The `Releasable#close` methods is a proxy for `RefCounted#decRef` so it's not really required ,but it's nice because it allows the usage inside try/with blocks.

2018-02-16 15:03 UTC, albertzaharovits commented
@s1monw this is ready for another review round. Can you please take a look?
If you agree if the approach I will update the tests as well.

2018-02-19 11:45 UTC, s1monw reviewed
left some comments. The approach is good IMO

2018-02-19 11:45 UTC, s1monw commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/InternalAwsS3Service.java
> +        for (final AmazonS3Wrapper clientWrapper : clientsCache.values()) {
can u use Releasables#close here instead of a loop.

2018-02-19 11:45 UTC, s1monw commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/InternalAwsS3Service.java
> +        clientsSettings = Collections.unmodifiableMap(S3ClientSettings.load(settings));
leave a comment here that we built the clients lazily

2018-02-19 11:45 UTC, s1monw commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/InternalAwsS3Service.java
> +        clientsCache = Collections.unmodifiableMap(emptyMap());
Collections.emptyMap() is already immutable

2018-02-19 11:45 UTC, s1monw commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/InternalAwsS3Service.java
> +    private static class InternalAmazonS3Wrapper extends AbstractRefCounted implements AmazonS3Wrapper {
I don't think we need the `AmazonS3Wrapper` interface just make this class public and name it `AmazonS3Wrapper`

2018-02-19 11:45 UTC, s1monw commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/InternalAwsS3Service.java
> +    private static class InternalAmazonS3Wrapper extends AbstractRefCounted implements AmazonS3Wrapper {
I'd call it `AmazonS3Reference`

2018-03-12 09:52 UTC, albertzaharovits commented
test this please

2018-03-12 15:13 UTC, s1monw approved these changes
LGTM

2018-03-13 16:59 UTC, merged