Correct the explanation of load time percentiles
elastic/elasticsearch pull request #28510
Opened 2018-02-04 15:56 UTC by iheggo

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2018-02-04 15:56 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-02-04 15:56 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-02-07 00:19 UTC, mayya-sharipova requested changes
Thank you for your contribution! 
You very well noticed `10-723ms` and `941-980ms` numbers.  
But I don't think this sentence is right: "with majority of a load time between 168ms to 723ms".  These numbers denote 25% and 75% percentiles, so only half of loads fall into this range.  I think your previous sentence `normally loads in 10-723ms` should be enough.

2018-02-07 11:55 UTC, iheggo commented
You are welcome!
Yes, you are right. Actually I meant to say an average or moderate rate.
However, I've considered your suggestion. I've removed this confusing sentence.

2018-02-07 16:29 UTC, mayya-sharipova approved these changes

2018-02-07 16:30 UTC, merged