Fix groovy `for in` syntax example.
elastic/elasticsearch pull request #28545
Opened 2018-02-07 10:47 UTC by theyoprst

2018-02-07 10:47 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-02-07 10:47 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-02-07 17:50 UTC, cbuescher requested changes
@theyoprst thanks for opening this issue. I might miss something but I think the syntax you suggest to change is not supported in painless. I didn't run this on 5.2 but in the 6 versions I get an error. Do you have a working example?`

2018-02-07 17:50 UTC, cbuescher commented on docs/reference/modules/scripting/painless-syntax.asciidoc
> +for (item in list) {
I don't think this works, I just tried in 6.2. Have you tested this syntax in 5.2 where you opened this issue? Can you post a working example if so?

2018-03-23 14:42 UTC, nik9000 commented
No response for a month, I think it is right to close this.

2018-03-23 14:42 UTC, closed without merging