[Tests] Skip some ingest-attachment tests on java 10
elastic/elasticsearch pull request #28570
Opened 2018-02-08 14:03 UTC by cbuescher

Some ingest-attachment tests that parse word documents using tika and 
fail because parsing doesn't seem to work for java 10 yet. This commit 
disables running those tests.

Relates to #28568

2018-02-08 14:26 UTC, martijnvg approved these changes
LGTM. We just need to not forget to enable these tests when we officially support java10.

2018-02-08 14:29 UTC, jasontedor requested changes
I think we should not do this. JDK 10 is entering the release candidate phase. I think we should try to figure out what is going on here instead of skipping these tests.

2018-02-08 14:41 UTC, cbuescher commented
@jasontedor The problem clearly comes from Tika, all the problematic documents seem to be word docs and the Tika AutoDetectParser returns nothing, but also doesn't throw an error. Since we are already using the latest Tika version I think opening an issue upstream and still disabeling the tests in the meantime is the best option. After all they fail consistently, those failures don't add much new information and might mask other more interesting failures.

2018-02-08 15:17 UTC, nik9000 commented
Do we have an upstream issue for this? I mean, it'd be nice to skip the tests so we can see what *else* is failing on Java 9 but I think we need to make sure the Tika folks are working on it.

2018-02-09 03:16 UTC, tvernum commented
This seems to be something on our side.
I created a standalone test project, copied our test files into it and ran this test (based on our TikaImpl), which passes.

Tika seems to work fine on Java 10, just not under our test setup.

```
public class TestParse {
    @Test
    public void testParseFiles() throws Exception {
        final Parser parsers[] = new Parser[]{
                // documents
                new org.apache.tika.parser.html.HtmlParser(),
                new org.apache.tika.parser.rtf.RTFParser(),
                new org.apache.tika.parser.pdf.PDFParser(),
                new org.apache.tika.parser.txt.TXTParser(),
                new org.apache.tika.parser.microsoft.OfficeParser(),
                new org.apache.tika.parser.microsoft.OldExcelParser(),
                new org.apache.tika.parser.odf.OpenDocumentParser(),
                new org.apache.tika.parser.iwork.IWorkPackageParser(),
                new org.apache.tika.parser.xml.DcXMLParser(),
                new org.apache.tika.parser.epub.EpubParser(),
                new org.apache.tika.parser.microsoft.ooxml.OOXMLParser()
        };
        final AutoDetectParser parser = new AutoDetectParser(parsers);
        final Tika tika = new Tika(parser.getDetector(), parser);

        Assert.assertEquals("10-ea", System.getProperty("java.version"));

        for (File file : new File("src/test/resources/tika-files").listFiles()) {
            testParse(tika, file);
        }
    }

    private void testParse(Tika tika, File file) throws IOException, TikaException {
        try (InputStream input = new FileInputStream(file)) {
            final String string = tika.parseToString(input, new Metadata(), -1);
            Assert.assertNotNull(file.getAbsolutePath(), string);
            Assert.assertFalse(file.getAbsolutePath(), string.isEmpty());
        }
    }
```

2018-02-09 04:17 UTC, tvernum commented
It's not a Tika issue.
ZipFile on Java 10 has decide that it needs `accessDeclaredMembers`
https://github.com/dmlloyd/openjdk/commit/0052c70c389aa5bed6e9b47e09ca887ac0ef4b2f#diff-704561497d8c3df4c77bc8f35b15ad73R825

And Tika is [swallowing the security exception](https://github.com/apache/tika/blob/1.17/tika-parsers/src/main/java/org/apache/tika/parser/pkg/ZipContainerDetector.java#L216-L217)
```
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:895)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:335)
	at java.base/java.lang.Class.checkMemberAccess(Class.java:2806)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2430)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:840)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:245)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:175)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:189)
	at org.apache.poi.openxml4j.util.ZipSecureFile.<init>(ZipSecureFile.java:142)
	at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipFile(ZipHelper.java:243)
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:134)
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:117)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:257)
	at org.apache.tika.parser.pkg.ZipContainerDetector.detectOPCBased(ZipContainerDetector.java:197)
	at org.apache.tika.parser.pkg.ZipContainerDetector.detectZipFormat(ZipContainerDetector.java:127)
	at org.apache.tika.parser.pkg.ZipContainerDetector.detect(ZipContainerDetector.java:88)
	at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:84)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:116)
	at org.apache.tika.Tika.parseToString(Tika.java:568)
	at org.elasticsearch.ingest.attachment.TikaImpl.lambda$parse$0(TikaImpl.java:108)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.ingest.attachment.TikaImpl.parse(TikaImpl.java:107)
	at org.elasticsearch.ingest.attachment.TikaDocTests.assertParseable(TikaDocTests.java:66)
	at org.elasticsearch.ingest.attachment.TikaDocTests.testFiles(TikaDocTests.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1713)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:943)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:957)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:916)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:802)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:852)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:863)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

2018-02-09 11:32 UTC, cbuescher commented
Closing in favour of #28602

2018-02-09 11:32 UTC, closed without merging

2018-02-09 13:32 UTC, nik9000 commented
> And Tika is swallowing the security exception

This is worth filing upstream I think.

2018-02-09 13:40 UTC, nik9000 commented
> This is worth filing upstream I think.

https://issues.apache.org/jira/browse/TIKA-2571

2018-02-09 13:41 UTC, nik9000 commented
> ZipFile on Java 10 has decided that it needs accessDeclaredMembers

Also this is super lame.

2018-02-09 13:51 UTC, jasontedor commented
>> ZipFile on Java 10 has decided that it needs accessDeclaredMembers

>Also this is super lame.

This is a temporary situation as finalizers are deprecated and the JDK maintainers are in the process of removing the use of finalizers from the JDK: https://bugs.openjdk.java.net/browse/JDK-8187485

When this process is complete, I think that the use of `getDeclaredMethod` will be removed and we can revoke this permission again. I will leave a comment on the PR #28602.