Validate translog before execute seq-based recovery
elastic/elasticsearch pull request #28587
Opened 2018-02-08 22:59 UTC by dnhatn

A recovering replica can be broken forever if its translog does not belong to its index. This can happen as follows.

1. A replica executes a file-based recovery
2. Index files are copied to replica but it crashed before finishing the recovery
3. Replica starts recovery again with a sequence-based recovery as the copied commit is safe
4. Replica fails to open engine because its translog and Lucene index are not matched
5. This replica won't be able to recover from primary

This commit makes sure the translog belong to the index commit before executing the sequence-based recovery, otherwise fallback to a file-based recovery.

Closes #28435

2018-02-09 10:37 UTC, bleskes commented
@dnhatn I was thinking to add a translog uuid parameter to org.elasticsearch.index.translog.Translog#readGlobalCheckpoint , so you always have to indicate which translog you expect when you just go and read the global checkpoint. It requires some juggling in IndexShard (where we read it before opening the engine) and I'm not sure how that will look. I wonder whether we should put our time in the store corruption marker reflecting a broken translog. Let's discuss.

2018-02-09 15:03 UTC, dnhatn commented
Closing this in favour of #28604

2018-02-09 17:13 UTC, dnhatn commented
@bleskes 
Yannick and I discussed this and agreed to fix the test by #28604. I will think more about the translog corruption issue.

2018-02-11 15:12 UTC, dnhatn commented
@bleskes I've added translogUUID requirement when reading the global checkpoint. Can you please have a look? Thank you!

2018-02-12 13:59 UTC, bleskes requested changes
I left a very minor comment.

2018-02-12 13:59 UTC, bleskes commented on server/src/main/java/org/elasticsearch/index/translog/Translog.java
> +        for (long i = checkpoint.generation - 1; i >= checkpoint.minTranslogGeneration; i--) {
I think we can just read the uuid of the generation associated with the checkpoint? I think this is overly fanatic, no? (I want to make a more complete validation at one place in a different PR - complete in the sense, check multiple lucene commits and multiple generations.

2018-02-12 14:34 UTC, bleskes commented on server/src/main/java/org/elasticsearch/index/translog/Translog.java
> +            Checkpoint.read(location.resolve(getCommitCheckpointFileName(checkpoint.generation))), expectedTranslogUUID)) {
why do we need to read the checkpoint again? I think we need to be consistent here - either with throw the underlying exception (and thus not protect about FileNotFoundException) or catch everything and rethrow a corruption exception. I tend toward the later..

2018-02-12 15:12 UTC, bleskes approved these changes

2018-02-12 15:12 UTC, bleskes commented on server/src/main/java/org/elasticsearch/index/translog/Translog.java
> +
add a comment about what we're doing here?

2018-02-12 18:23 UTC, merged

2018-02-12 18:33 UTC, dnhatn commented
Thanks @bleskes for your review.