OSGI support for elasticsearch-rest-client
elastic/elasticsearch pull request #28709
Opened 2018-02-17 00:02 UTC by markwoon

Adding OSGI support to elasticsearch-rest-client jar file (issue #28707).

It's using the defaults, which is fine.  Might want to consider modifying `Bundle-SymbolicName` in `MANIFEST.MF` to match whatever Java module name you end up using for this.

2018-02-17 00:03 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-02-17 00:03 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-02-17 01:00 UTC, jasontedor requested changes
I am sorry to say that this will not be enough. If we decide to support OSGi* we would need a test project that actually stands up a client application in an OSGi container and tests that the low-level REST client is well-behaved in that environment. We do not merely start supporting something and then cross our fingers that it works or that we never break it. I suggest that we first have a discussion about whether or not we want to support OSGi on #28707.

*: I will be upfront and say that I am not likely to support supporting OSGi at this time.

2018-03-23 16:37 UTC, nik9000 commented
I'm going to close this because it looks like we aren't going to finish it. @markwoon, if you like to work on adding a test project for this then please reopen this and let us know!

2018-03-23 16:37 UTC, closed without merging