typo
elastic/elasticsearch pull request #28717
Opened 2018-02-18 09:01 UTC by hatem20

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2018-02-18 09:01 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-02-18 09:01 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-02-19 09:29 UTC, cbuescher requested changes
Hi @hatem20, thanks for the PR. I'm not a native speaker but according to http://grammarist.com/usage/indexes-indices/ both "indexes" and "indices" are common plural forms of "index". I cannot find any evidence that the form you are using is correct though.

We seem to use both in our documentation, with an emphasis on "indices". If you would like to change your PR to that, I'd be okay merging it, but since we use both forms currently maybe we can also close this PR. Please push an update or close as you see fit.

2018-02-19 09:48 UTC, DaveCTurner requested changes
Both are fine as plurals of the noun "an index", and we do seem to prefer "indices" (e.g. the API includes `GET /cat/_indices`). "Indeces", despite seeming like a reasonable compromise, isn't ok.

However, as the third person singular of the verb "to index", only "indexes" is acceptable.

2018-02-19 09:48 UTC, DaveCTurner commented on docs/reference/getting-started.asciidoc
> +The above indeces a new document with an ID of 2.
This is a verb, so `indexes` is the only correct spelling.

2018-02-19 09:48 UTC, DaveCTurner commented on docs/reference/getting-started.asciidoc
> +As a quick example, the following call indeces two documents (ID 1 - John Doe and ID 2 - Jane Doe) in one bulk operation:
This is a verb, so `indexes` is the only correct spelling.

2018-02-19 09:48 UTC, DaveCTurner commented on docs/reference/getting-started.asciidoc
> +In addition to being able to index and replace documents, we can also update documents. Note though that Elasticsearch does not actually do in-place updates under the hood. Whenever we do an update,
This is a verb, so `indexes` is the only correct spelling.

2018-02-19 11:16 UTC, hatem20 commented
I was just talking about consistency, but you are right both words are valid.

2018-02-19 11:19 UTC, closed without merging