Deprecate setting index.optimize_auto_generated_id in 6.x (#27583)
elastic/elasticsearch pull request #28862
Opened 2018-03-01 09:59 UTC by liketic

Deprecate setting ```index.optimize_auto_generated_id``` in 6.x. 

Relates to #27600

2018-03-01 09:59 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-03-01 09:59 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-03-02 08:30 UTC, jasontedor commented
test this please

2018-05-07 12:34 UTC, javanna commented
@jasontedor the build succeeded when you ran it a (long) while ago, would you mind picking this one up?

2018-05-25 02:22 UTC, jasontedor requested changes

2018-05-26 03:44 UTC, liketic commented on server/src/main/java/org/elasticsearch/index/engine/EngineConfig.java
>          Property.IndexScope, Property.Dynamic);
Thanks @jasontedor , please review again.

2018-12-06 21:59 UTC, jasontedor commented
@liketic Would you update EngineConfigTests so that it compiles?

2018-12-09 14:01 UTC, jasontedor commented
@elasticmachine test this please

2018-12-09 19:58 UTC, jasontedor approved these changes

2018-12-09 20:01 UTC, jasontedor commented
@elasticmachine test this please

2018-12-11 14:43 UTC, merged

2018-12-14 17:32 UTC, jasontedor commented
I added [v6.6.0](https://github.com/elastic/elasticsearch/labels/v6.6.0).