[docs] add warning for read-write indices in force merge documentation
elastic/elasticsearch pull request #28869
Opened 2018-03-01 16:31 UTC by mueedc

This PR updates force merge documentation:

- Add warning message to specify force merge API calls should only be used against read-only indices

addresses #28843

2018-03-01 16:31 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-03-01 16:31 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-03-02 09:59 UTC, javanna commented
@ppf2 would you like to have a look at this?

2018-03-15 14:56 UTC, jpountz requested changes
Looks good to me overall, I left some minor comments.

2018-03-15 14:56 UTC, jpountz commented on docs/reference/indices/forcemerge.asciidoc
> +it has 75% of deleted docs. This can cause very large segments to remain in the shards.
I don't think this 75% is correct, it would be shard_size/5GB but I think it's fine to say "until it mostly consists of deleted docs".

2018-03-15 14:56 UTC, jpountz commented on docs/reference/indices/forcemerge.asciidoc
> +Force merge should only be called against *read-only indices*. Running
Just do `WARNING: Force merge...` and our documentation processor will make a nice warning block out of this paragraph.

2018-03-15 15:48 UTC, mueedc commented
@jpountz your requested changes have been added and the commit was rebased/squashed back into one

2018-03-15 18:40 UTC, ppf2 commented
lgtm thanks all!

2018-04-24 08:39 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-04-30 19:08 UTC, mueedc commented
@jpountz I can add a tip for re-running force merge after altering many documents as per @gondalez comment. let me know your thoughts

2018-05-07 12:32 UTC, javanna commented
@jpountz can you have another look please?

2018-05-09 16:50 UTC, jpountz commented
@gondalez I have seen too many issues when force-merge was run too often, and basically none when it wasn't run when it should so I'd rather keep the messaging clear for now and only say that force-merge should only run against read-only indices.

2018-05-09 16:50 UTC, jpountz approved these changes

2018-05-09 16:53 UTC, merged

2018-08-21 08:44 UTC, silashansen commented
I think some information on what to do if a force merge was already issued would be welcomed.

How do you get the index back to a state where the normal cleanup policies will apply?