fix query string syntax doc when OR operator is missed
elastic/elasticsearch pull request #28882
Opened 2018-03-02 10:05 UTC by fbaligand

@jimczi 
I complete here your PR #28798 to fix issue #28719

2018-03-02 10:05 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-03-02 10:05 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-03-04 21:37 UTC, jimczi requested changes
I left some comments, I think we should just remove the sentence that you changed.

2018-03-04 21:37 UTC, jimczi commented on docs/reference/query-dsl/query-string-syntax.asciidoc
> +  If you omit the OR operator, the default operator will be used (except if `title` field is typed `keyword`)
I think we should remove this sentence completely. We don't split on whitespace anymore so we shouldn't assume that `quick` and `brown` are going to be separated. It depends only on the tokenizer that is use for the field. We've added a warning section at the beginning of the docs regarding `keyword` field so I think it's enough.

2018-03-04 21:37 UTC, jimczi commented on docs/reference/query-dsl/query-string-syntax.asciidoc
> +    book.\*:(quick OR brown)
+1 to add an explicit `OR`

2018-03-04 22:57 UTC, fbaligand commented
@jimczi 
I agree with you.
So I removed the sentence, and the associated example `title:(quick brown)`

2018-03-18 17:44 UTC, fbaligand commented
@jimczi 
Could you review my last change and tell if it answers your requested changes ?

2018-03-30 14:19 UTC, fbaligand commented
Hi @jimczi
Could you review my last commit ?

2018-03-30 14:35 UTC, jimczi approved these changes
Thanks @fbaligand

2018-03-30 14:36 UTC, merged

2018-03-30 15:30 UTC, fbaligand commented
Thanks @jimczi for the merge !