Packaging: Unmark systemd service file as a config file
elastic/elasticsearch pull request #29004
Opened 2018-03-13 04:32 UTC by rjernst

Systemd overrides should happen through /etc/systemd/system, not
directly editing the service file. This commit removes marking the
service file as configuration for rpm and deb packages.

2018-03-13 04:32 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-03-13 04:33 UTC, rjernst commented
packaging tests are broken right now, so I will trigger the tests tomorrow once they are working again.

2018-03-13 19:43 UTC, rjernst commented
@elasticmachine run packaging tests

2018-03-13 19:53 UTC, nik9000 approved these changes
I agree.

2018-03-20 08:14 UTC, rjernst commented
@elasticmachine run packaging tests

2018-03-20 13:38 UTC, jasontedor requested changes
The packaging test failure here is related to your change. Previously, since it was marked as configuration, it would not be removed during a remove on Debian-based systems (only on a purge). Now, since it is not marked as a configuration file, it would always be removed. This will require a change to one of the assertions in the packaging tests on Debian-based systems.

I think that this change should go to 7.0.0 only, be marked as breaking, and added to the migration guide. For users that are mistakenly editing this file instead of using an override file, they will be in for a rude awakening in 6.3.0 if they upgrade and we overwrite their customized service file.

I do think that this is the right change though. We do document not to edit this file and use an override instead, but I would rather we be safe here regarding the consequences of this change.

2018-03-21 06:19 UTC, rjernst commented
@elasticmachine run packaging tests

2018-03-21 06:19 UTC, rjernst commented
@jasontedor I pushed a4dc719

2018-04-19 21:34 UTC, jasontedor reviewed
I left a minor comment.

2018-04-19 21:34 UTC, jasontedor commented on docs/reference/migration/migrate_7_0/packaging.asciidoc
> +==== systemd service file is no longer configuration
Would you add an entry to the changelog too?

2018-04-20 07:39 UTC, tlrx approved these changes
LGTM, CI still complains about packaging tests and exit code

2018-05-02 16:01 UTC, rjernst commented
@jasontedor This is passing packaging tests now. Do you have any more concerns?

2018-05-02 16:11 UTC, jasontedor approved these changes
LGTM.

2018-05-02 16:48 UTC, merged