I add Ansible playbook for Elasticsearch
elastic/elasticsearch pull request #29238
Opened 2018-03-25 14:17 UTC by refactormyself

I add Ansible playbook for Elasticsearch under Deployment - Supported by Elasticsearch

2018-03-25 14:17 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-03-25 14:17 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2018-03-25 14:20 UTC, refactormyself commented
This PR Closes Issue  #18636

2018-03-26 09:58 UTC, Crazybus requested changes

2018-03-26 09:58 UTC, Crazybus commented on docs/plugins/integrations.asciidoc
> +  It has been tested Ubuntu 14.04/16.04, Debian 8, Centos 7
Should be "it has been tested on". Maybe something like "Tested with the latest version of 5.x and 6.x on Ubuntu 14.04/16.04, Debian 8, Centos 7"

2018-03-26 10:00 UTC, Crazybus commented
@jasontedor Left a small comment about the wording. 

But can also confirm that this is accurate and elastic/ansible-elasticsearch is an officially supported ansible playbook for Elasticsearch.

2018-03-26 14:01 UTC, Crazybus approved these changes

2018-03-27 21:34 UTC, nik9000 commented
Hey, CLAbot, check this!

2018-03-28 02:54 UTC, jasontedor commented
@nik9000 Will you handle integrating this one?

2018-03-28 22:16 UTC, nik9000 commented
> @nik9000 Will you handle integrating this one?

On it!

2018-03-28 22:18 UTC, merged

2018-03-28 22:20 UTC, nik9000 commented
Merged to master and backported to 6.x and 6.2 branches. The docs changes should be live in about 30 minutes on all three branches.

2018-03-28 23:04 UTC, jasontedor commented
Thanks a lot @refactormyself for the contribution, @Crazybus for the review, and @nik9000 for integrating.