Use soft-update to maintain document history
elastic/elasticsearch pull request #29458
Opened 2018-04-10 20:17 UTC by dnhatn

Today we can the soft-update feature from Lucene to maintain a history
of document. This change simply replaces hard-update in the Engine by
soft-update methods. Stale operations, delete, and no-ops will be
handled in subsequent changes.

Note:
`indexWriter#updateDocValues` requires that the soft-delete field must be existed. I think we have to skip the intermediate step. I will work on another change to index a delete tombstone when deleting a document.

2018-04-10 20:17 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-04-10 22:00 UTC, dnhatn commented
test this please.

2018-04-11 03:08 UTC, dnhatn commented
please test this.

2018-04-11 12:16 UTC, s1monw commented
@elasticmachine test this please

2018-04-11 12:24 UTC, s1monw requested changes
looks great, I left some comments

2018-04-11 18:59 UTC, dnhatn commented on server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
> +                    public CacheHelper getCoreCacheHelper() {
I removed the test and this wrapper in the PR, and will add it to Lucene.java later. I prefer to keep this change as a cut-over.

2018-04-11 19:00 UTC, dnhatn commented
@s1monw I have addressed your comments. Can you please take a look? Thank you.

2018-04-12 11:52 UTC, s1monw approved these changes
LGTM

2018-04-12 11:52 UTC, s1monw commented on server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +                indexWriter.softUpdateDocuments(uid, docs, Lucene.newSoftDeleteField());
I think we can cache this in here in a constant so we don't need to re-create a new one every time.

2018-04-12 16:30 UTC, dnhatn commented
Thanks @s1monw for reviewing.

2018-04-12 16:30 UTC, merged