Index stale operations to Lucene to have complete history
elastic/elasticsearch pull request #29679
Opened 2018-04-24 18:33 UTC by dnhatn

Today, when processing out of order operations, we only add it into
translog but skip adding into Lucene. Translog, therefore, has a
complete history of sequence numbers while Lucene does not.

Since we would like to have a complete history in Lucene, this change
makes sure that stale operations will be added to Lucene as soft-deleted
documents if required.

2018-04-24 18:34 UTC, dnhatn commented
@s1monw and @bleskes Can you please have a look? I could not make review requests. Thank you!

2018-04-24 22:13 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-04-25 13:14 UTC, s1monw requested changes
I left some minor things. this looks pretty awesome! @bleskes please take a look at the engine parts.

2018-04-25 13:14 UTC, s1monw commented on server/src/main/java/org/elasticsearch/common/lucene/uid/VersionsAndSeqNoResolver.java
> +            final NumericDocValues seqNoDV = leaf.reader().getNumericDocValues(SeqNoFieldMapper.NAME);
I think we can assert that both seqNoDV and primaryTermDV are non null. They are required at least for this code to work.

2018-04-25 13:14 UTC, s1monw commented on server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +    private OpVsLuceneDocStatus compareToLuceneHistory(final Operation op, final Searcher searcher) throws IOException {
can we have a javadoc for this method?

2018-04-25 13:14 UTC, s1monw commented on server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> +        OP_STALE_HISTORY_EXISTED,
maybe `OP_STALE_HISTORY_EXISTS` ?

2018-04-25 13:14 UTC, s1monw commented on server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
> -                        status = OpVsLuceneDocStatus.OP_STALE_OR_EQUAL;
can you please add comments here in what cases we can get into these situations?

2018-04-25 20:27 UTC, bleskes commented
I talked to @dnhatn and I'm a bit uncomfortable with the PR changes to how we resolve stale operations in the engine. It seems that the main goal here was to try to avoid indexing duplicates of the same stale operation into Lucene. I'm not sure we need to do this. This is very rare. The alternative would be to accept duplicates under the condition that duplicate seq# also means the same doc version. A few things that are worth noting on top of it:
1) The Translog already has this property and may have duplicates.
2) To fully achieve these semantics we need to implement lucene roll backs.

If we accept the above, we can keep the current (simpler) way we resolve stale operations and follow the following:
1) If an incoming op with a seq# < local checkpoint, skip lucene and only store in the translog (as now)
2) If not, resolve the latest seq# for the doc id to decide if the op is stale (as today)
3) Stale ops with seq# > local checkpoint go into lucene with the soft delete flag "on".

2018-04-25 21:41 UTC, dnhatn commented
>  The alternative would be to accept duplicates under the condition that duplicate seq# also means the same doc version.

@bleskes I pushed https://github.com/elastic/elasticsearch/pull/29679/commits/70d5359b871ca7f37bff01e885de8d6f78fed98f to back out the dedup logic as we discussed. Can you please have another look? Thank you!

2018-04-27 11:18 UTC, s1monw approved these changes
left a tiny comment LGTM

2018-04-27 11:18 UTC, s1monw commented on server/src/main/java/org/elasticsearch/common/lucene/Lucene.java
> +     * The wrapped reader can be used to query documents which are soft-deleted.
just say `to query all documents`

2018-04-27 15:44 UTC, dnhatn commented
@elasticmachine test this please.

2018-04-27 22:13 UTC, dnhatn commented
run sample packaging tests

2018-04-27 23:38 UTC, dnhatn commented
Thanks @simonw and @bleskes for reviewing.

2018-04-27 23:39 UTC, merged