Rest tests against cloud
elastic/elasticsearch pull request #30119
Opened 2018-04-25 09:28 UTC by beiske

These are changes for running the rest tests against a cluster on Cloud.

* Ensure all paths have a leading `/` by setting path prefix
* Allow adding additional blacklisted tests for `CoreWithSecurityClientYamlTestSuiteIT`
* Allow specifying custom cluster credentials for `CoreWithSecurityClientYamlTestSuiteIT`

2018-04-25 09:34 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-04-25 11:59 UTC, javanna commented
As far as I can see this change makes it possible to configure '/' as a `pathPrefix` in the low-level REST client. I wonder if this is how we want to make this change. We never modified paths to start with '/' but Elasticsearch used to be lenient there and accept relative paths as they were absolute. Considering that Elasticsearch no longer makes relative paths work as if they were absolute, should we rather always add the '/' when missing on any path, rather than adding the ability to configure '/' as `pathPrefix`?

2018-04-25 12:36 UTC, beiske commented
>...should we rather always add the '/' when missing on any path, rather than adding the ability to configure '/' as pathPrefix?

Sounds good to me. That was one of my original proposals. Using the prefix path was done by proposal from @jasontedor. Maybe he was anticipating issues when backporting to 6.x or something else I don't remember?

2018-04-25 12:42 UTC, jasontedor commented
I really do not like manipulating user input. If the user says: send the request to a/b/c we should send the request to a/b/c.

2018-04-26 11:56 UTC, javanna commented
@jasontedor I agree on the sentiment. On my end, I would like to figure out what Elasticsearch accepts with the recent changes in master, what works and what doesn't, and make sure that we are heading in the right direction. I would find it a bit weird to allow users to provide relative paths if they don't work at all, so wondering if this is only a proxy problem or not. An alternative could be to consider to no longer accept relative paths in the client, assuming that recent changes in the Elasticsearch server code doesn't make them work well like it did before.

2018-05-07 18:39 UTC, javanna commented on client/rest/src/main/java/org/elasticsearch/client/RestClient.java
> +            logger.debug("Building URI with fullpath: ["+ fullPath+"] for path: ["+path+"]");
nit: I wonder if this new log line is necessary, given that it's called for every single request I'd try to do without it. If users want to log this though they can enable request tracing?

2018-05-07 18:40 UTC, javanna commented
I had another look and I am ok with this approach. I can't comment on the build changes though.

2018-05-22 13:00 UTC, beiske commented
Jenkins test this

2018-05-24 05:32 UTC, suyograo commented
> I can't comment on the build changes though.

@jasontedor could you please review or assign this to someone who can review the build changes bits?

2018-05-25 03:02 UTC, jasontedor commented
This will be looked at soon; we are bottlenecked right now.

2018-05-25 17:38 UTC, jasontedor commented
I want to break this PR into three separate PRs as there are multiple changes bundled here.

2018-05-25 17:41 UTC, jasontedor commented
The first PR is #30885.

2018-06-04 14:12 UTC, jasontedor commented
A second PR is #31074.

2018-06-10 13:31 UTC, jasontedor commented
A third PR is #31235.

2018-06-21 09:17 UTC, beiske commented
I have rebased this one after the merges of #30885, #31074 and #31235 so that it now only contains the path prefix changes.

2018-06-27 21:27 UTC, jasontedor requested changes
Looks good in general but I left some comments.

2018-06-28 08:23 UTC, beiske commented on client/rest/src/main/java/org/elasticsearch/client/RestClient.java
> +                fullPath = (pathPrefix + "/" + path).replaceAll("//+", "/");
A `pathPrefix` that is a single slash, would also be a `pathPrefix` that ends with a slash. So a naturalæ consequence of using the `pathPrefix` to ensure there always is a leading slash is allowing `pathPrefix` with a trailing slash. Of course one could make a special case for trailing slash when it is the entire prefix, but that seemed like very circumstantial logic to me.

2018-06-29 19:36 UTC, jasontedor requested changes
I left a comment.

2018-06-29 19:36 UTC, jasontedor commented on client/rest/src/main/java/org/elasticsearch/client/RestClient.java
> +                fullPath = (pathPrefix + "/" + path).replaceAll("//+", "/");
This value is immediately written over in any one of the following `if`, `else if`, or `else` blocks so this line does not do anything?

2018-06-29 19:39 UTC, jasontedor approved these changes

2018-07-01 17:42 UTC, merged

2018-07-05 08:43 UTC, beiske commented
@jasontedor Thank you!

2018-08-13 06:15 UTC, aug24 commented
I've done some more digging, and I would like to discuss this further if that's OK?  I believe the current position is inconsistent.

In RestClientBuilder.setPathPrefix, there is the following code:

        if (cleanPathPrefix.startsWith("/") == false) {
            cleanPathPrefix = "/" + cleanPathPrefix;
        }

ie paths are forced to have a leading slash.

There is also this:

        if (cleanPathPrefix.isEmpty() || "/".equals(cleanPathPrefix)) {
            throw new IllegalArgumentException("pathPrefix must not be empty or '/': [" + pathPrefix + "]");
        }

ie you cannot simply handle the trivial case of "always prepend a slash" because the code actually doesn't let you.

As far as I can tell, there is no correct use case for the user providing a relative path URI without a pathPrefix.  If we don't automatically fix this error (per the fix I suggested) then we should throw an exception with advice that either a pathPrefix or a leading slash is required.

2018-08-13 08:34 UTC, aug24 commented
Apologies: more context is at https://github.com/elastic/elasticsearch/pull/32714.  Perhaps this discussion should continue there.  I'll cross-post.

I clearly have a slightly old client as the second block, which was removed on July 1st, is present.  

In short: the rest client builder permits the user to build a request which is, as I understand it, invalid.  

I suggest adding a leading slash if one was not provided, or throwing an exception, as I think a request without a leading is slash is invalid (and so do AWS ELBs, which leads to a hard to debug error).

I notice that we do force a leading slash if a pathPrefix without one is given.  In fact the comment on this PR:

> Some proxies require all requests to have paths starting with / since
> there are no relative paths at the HTTP connection level. Elasticsearch
> assumes paths are absolute. 

is precisely the reason why I think the other PR should be accepted.