_cluster/state should always return cluster_uuid
elastic/elasticsearch pull request #30143
Opened 2018-04-25 17:09 UTC by pickypg

Currently, the only way to get the REST response for the `/_cluster/state`
call to return the `cluster_uuid` is to request the `metadata` metrics,
which is one of the most expensive response structures. However, external
monitoring agents will likely want the `cluster_uuid` to correlate the
response with other API responses whether or not they want cluster
metadata.

Relates to https://github.com/elastic/beats/pull/6807

2018-04-25 17:09 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-04-25 18:36 UTC, bleskes requested changes
LGTM, though I believe you need a skip clause in your yml tests to make sure it doesn't run against an old version that doesn't output the uuid.

2018-04-25 18:43 UTC, pickypg commented
@bleskes I wonder if I should just make a specific test for the cluster_uuid in that case, then skip only that one for older versions and avoid having none of these REST tests run on older versions?

2018-04-25 18:44 UTC, bleskes commented
@pickypg makes sense.

2018-04-25 21:03 UTC, pickypg commented on rest-api-spec/src/main/resources/rest-api-spec/test/cluster.state/10_basic.yml
> +      version:  " - 6.99.99"
There will be a follow-up PR to change this to `6.3.99` after this PR is merged / backported to 6.x (6.4).

2018-04-26 19:44 UTC, pickypg commented
jenkins test this

2018-04-27 00:03 UTC, pickypg commented
jenkins test this

2018-04-27 14:10 UTC, pickypg commented
@bleskes Updated with skip logic and CI has calmed down

2018-04-30 08:48 UTC, bleskes approved these changes

2018-04-30 14:16 UTC, merged

2018-04-30 14:32 UTC, pickypg commented on rest-api-spec/src/main/resources/rest-api-spec/test/cluster.state/10_basic.yml
> +      version:  " - 6.99.99"
https://github.com/elastic/elasticsearch/pull/30264 as promised