Adds single node allocation to shrink
elastic/elasticsearch pull request #30206
Opened 2018-04-27 14:17 UTC by colings86

This change adds two new steps as the first steps of the shrink action:

1. A `SetSingleNodeAllocateStep` which:
    1. Determines which of the active nodes match the existing index
allocation rules
    2. Randomly (using Randomness so its deterministic for testing)
picks one of the matching nodes
    3. Updates the index settings to add a require allocation rule for
the node that was picked (using the
`index.routing.allocation.require._name` setting)
2. An `AllocationRoutedStep` which ensures that at least one copy of
each shard is allocated according to the new allocation rules

Note that this change also modifies the `AllocationRoutedStep` to add a
boolean field which determines whether the allocation is complete when
at least one copy of each shard matches the allocation rulees or if it
needs to wait for all shard copies to be allocated according to the
rules.

Lastly, a `randomStepKey()` method is added to `AbstractStepTestCase`
for convenience.

2018-04-27 14:36 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-04-27 14:52 UTC, talevy commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/AsyncActionStep.java
> +    public abstract void performAction(IndexMetaData indexMetaData, ClusterState currentClusterState, Listener listener);
should we just have `Index` and `ClusterState` and fetch `indexMetaData` internally every time?

2018-04-27 21:12 UTC, talevy requested changes
should we add a test to IndexLifecycleRunnerTests with a real clusterState object, and verify that the indexMetaData that was passed in, is in fact, sameAs the one found inside the clusterState argument?

2018-04-27 21:12 UTC, talevy commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/SetSingleNodeAllocateStep.java
> +/*
watch license

2018-04-27 21:12 UTC, talevy commented on x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/indexlifecycle/SetSingleNodeAllocateStepTests.java
> +/*
watch license

2018-04-30 11:58 UTC, colings86 commented
@talevy I pushed a commit to address your comments. Regarding the test you suggested, I don't think IndexLifecycleRunnerTests would be the right place for that since the IndexMetadata is retrieved from the  ClusterState before that point (in IndexLifecycleService). I looked into adding it to IndexLifecycleServiceTests but I'm not sure that is the right place either.

2018-04-30 14:42 UTC, talevy approved these changes
LGTM.

Then that is OK, I thought there was a place for testing those parameters.

2018-05-01 09:27 UTC, merged