Exclude soft-deleted documents in commit stats
elastic/elasticsearch pull request #30228
Opened 2018-04-28 03:00 UTC by dnhatn

Since #29458, we use a searcher to calculate the number of documents for
a commit stats. Sadly, that approach is flawed. The searcher might no
longer point to the last commit if it's refreshed.

This commit uses `SoftDeletesDirectoryReaderWrapper` to exclude the
soft-deleted documents from numDocs in a SegmentInfos. I chose to modify 
method `Lucene#getNumDocs` so that we can read a store metadata snapshot
correctly without opening an engine.

Relates #29458

2018-04-28 03:00 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-04-29 15:14 UTC, dnhatn commented
@elasticmachine test this please

2018-04-30 08:09 UTC, bleskes commented
I wonder if we should do this. Classically number of docs was always total docs in the segments. I'm not saying this isn't debatable but I'm also not sure it merits the breakage price. Also we want this to go into 6.x. Instead of this, maybe we should another field to the stats to reflect soft deletes? then sycned flush is freed to do what it thinks is right and we have more information.

2018-04-30 08:23 UTC, s1monw requested changes
left one comment

2018-04-30 15:45 UTC, dnhatn commented
> I think we need a better utility method like Lucene. getNumDocs that takes soft deletes into account? 

@bleskes Yes, we should do it.

2018-05-01 02:26 UTC, dnhatn commented
@s1monw I take a different approach for this. Can you please have a look? Thank you.

2018-05-03 06:31 UTC, s1monw commented
I am ok with the changing the semantics here. I think we try to make something work that isn't necessarily giving us enough information. I think we should keep it the way it is and deprecate it in 6.x? I really wonder what the purpose of this stats is compared to other stats that have a live numDocs that is accurate?

2018-05-03 07:27 UTC, bleskes commented
@s1monw as said, I think you are a better judge here for what's handy. I'm not sure I fully follow what you suggest.

>  I think we should keep it the way it is and deprecate it in 6.x? 

Double checking - the way it is in master or in the PR? can you clarify?

> other stats that have a live numDocs that is accurate?

What other stats are you referring to?

2018-05-03 11:29 UTC, s1monw commented
> Double checking - the way it is in master or in the PR? can you clarify?

the way it is in master

> other stats that have a live numDocs that is accurate?

I mean for instance docStats here: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html

2018-05-10 02:02 UTC, dnhatn commented
@s1monw  and @bleskes,

I've updated the PR to restore the CommitStats and made synced-flush using an exact numDocs only when soft-deletes is enabled. There are still some issues that I am not sure.

1. With this change, only the synced-flush call uses an exact numDocs. Should we still need to cache this value in an engine?

2. In peer-recovery, a replica shard needs to send an exact numDocs to the primary shard if soft-deletes is enabled and an index was sealed. I see two possible approaches:

- Pass an extra parameter "requiredExactNumDocs" in `getStoreMetadataSnapshot`. Internally we always calculate an exact numDocs if this parameter is true. This does not optimize the case when the index was not sealed and may cause confusion for other StoreMetadataSnapshot's usages.

- Override the numDocs by an exact numDocs when the soft-deletes is true and an index was sealed. This is not nice but the change is minimal and does not affect StoreMetadataSnapshot's other usages.

Please have a look and let me know your thought. Thank you!

2018-05-10 09:27 UTC, bleskes commented on server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java
> +                final List<IndexCommit> commits = DirectoryReader.listCommits(recoveryTarget.store().directory());
This needs to use safe commit. This is the commit the engine will use (probably an existing bug) .

2018-05-10 09:30 UTC, bleskes commented
Thx @dnhatn . I like where this is going. IMO neither synced flush nor recover are frequent operations. We should just use exact numbers all the time and everywhere. keep it simple. if soft deletes are not enabled, it's the same as the "fast" numDocs (and we can assert for that).

2018-05-14 14:09 UTC, s1monw approved these changes
LGTM

2018-05-14 14:09 UTC, s1monw commented on server/src/main/java/org/elasticsearch/common/lucene/Lucene.java
> +    public static int getExactNumDocs(IndexCommit commit) throws IOException {
++

2018-05-14 14:09 UTC, s1monw commented on server/src/main/java/org/elasticsearch/indices/flush/SyncedFlushService.java
> +                numDocs = Lucene.getExactNumDocs(commitRef.getIndexCommit());
you can call the `getExactNumDocs` all the time. it has no overhead if soft_deletes are not there

2018-05-14 14:09 UTC, s1monw commented on server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java
> +                final long numDocsSource = softDeletesEnabled ? Lucene.getExactNumDocs(snapshot) : recoverySourceMetadata.getNumDocs();
same here just use `getExactNumDocs`

2018-05-14 20:53 UTC, dnhatn commented
@elasticmachine test this please

2018-05-15 20:19 UTC, bleskes approved these changes
LGTM. Thanks Nhat.

2018-05-15 21:40 UTC, dnhatn commented
Thanks @bleskes and @s1monw

2018-05-15 22:00 UTC, merged