Fix some small issues in the getting started docs
elastic/elasticsearch pull request #30346
Opened 2018-05-02 19:52 UTC by tryantwit

* Modified a reference to real time to match the previous line reference of realtime.
* Modified eg to e.g. as it's an abbreviation for the latin exempli gratia.
* Added missing pronoun to `_executing_filters` section to read better.

2018-05-03 06:51 UTC, DaveCTurner requested changes
Looks good, thanks @tryantwit. I asked for one minor change.

2018-05-03 06:51 UTC, DaveCTurner commented on docs/reference/getting-started.asciidoc
> +Elasticsearch is a near realtime search platform. What this means is there is a slight latency (normally one second) from the time you index a document until the time it becomes searchable.
I think I'd prefer `near-realtime`.

2018-05-03 06:52 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-05-03 12:41 UTC, karmi commented
Hi @tryantwit, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/30346.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

2018-05-03 12:54 UTC, tryantwit commented
Hey @karmi, sorry about that. Got the other email added to github.

@DaveCTurner pull request was updated with your requested change. Though after doing a quick search through the rest of Elasticsearches documentation it look like the docs are usage the phrase `near real-time`.

Those references can be found in `docs/reference/search/suggesters/completion-suggest.asciidoc` and `docs/reference/modules/indicies/request_cache.asciidoc`. It'd probably be best to keep it consistent throughout the docs so I can modify my reference or modify those as well. Just let me know what you think.

2018-05-08 06:46 UTC, DaveCTurner approved these changes
LGTM

2018-05-08 06:47 UTC, DaveCTurner commented
@elasticmachine test this please

2018-08-16 13:16 UTC, javanna commented
retest this please

2018-08-16 14:16 UTC, DaveCTurner commented
@elasticmachine test this please

2018-08-18 08:55 UTC, DaveCTurner commented
@elasticmachine test this please

2018-08-20 06:54 UTC, merged