Transport client: Don't validate node in handshake
elastic/elasticsearch pull request #30737
Opened 2018-05-18 20:30 UTC by tbrooks8

This is related to #30141. Right now in the transport client we open a
temporary node connection and take the node information. This node
information is used to open a permanent connection that is used for the
client. However, we continue to use the configured transport address.
If the configured transport address is a load balancer, you might
connect to a different node for the permanent connection. This causes
the handshake validation to fail. This commit removes the handshake
validation for the transport client.

2018-05-18 20:30 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-05-18 20:33 UTC, tbrooks8 commented
I want to point out that there is some tension with this functionality and how we publicize (and log) discovery node information. You might not actually be connected to the node that you think you are connected to (https://github.com/elastic/elasticsearch/issues/30141#issuecomment-388137656). 

It feels kind of weird to me that the transport client is based on "nodes" and not "connections". But that ship has sailed and is probably not too important to resolve for something that is deprecated. But I want to raise that point. Should I modify the PR to store the node that is eventually connected to in the "persistent, managed" connection?

2018-05-22 10:13 UTC, s1monw requested changes

2018-05-22 10:13 UTC, s1monw commented on server/src/main/java/org/elasticsearch/transport/TransportService.java
> +    public void connectToNode(final DiscoveryNode node, ConnectionProfile connectionProfile, boolean validateNodeConnection) {
can we please not add another API here but rather try to detect if we are a client or a node? I mean down the road we don't want to support this anymore so lets make sure we don't have special public APIs. I can imagine a boolean on the ctor or even check if ClusterService is != null (not that intuitive). You can just add an overloaded ctor instead.

2018-05-22 11:55 UTC, s1monw commented on server/src/main/java/org/elasticsearch/transport/TransportService.java
> +    public void connectToNode(final DiscoveryNode node, ConnectionProfile connectionProfile, boolean validateNodeConnection) {
we can also just look at the settings like this `TransportClient.CLIENT_TYPE.equals(settings.get(Client.CLIENT_TYPE_SETTING_S.getKey()));`

2018-05-31 07:25 UTC, s1monw approved these changes
LGTM

2018-05-31 15:42 UTC, bleskes approved these changes
LGTM. Thanks @tbrooks8

2018-05-31 15:42 UTC, bleskes commented on server/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java
> +        List<DiscoveryNode> establishNodeConnections(Set<DiscoveryNode> nodes, boolean validateInHandshake) {
`validateInHandshake` not used anymore?

2018-05-31 19:14 UTC, merged