WIP: Added grep support for cat APIs
elastic/elasticsearch pull request #31015
Opened 2018-05-31 22:38 UTC by sohaibiftikhar

Resolves #30245

2018-05-31 22:39 UTC, sohaibiftikhar commented
@nik9000 If you could take a cursory look when you have time and check if this is going in the right direction it would great. I can then add more tests and make the changes in the documentation.

2018-06-01 00:55 UTC, nik9000 requested changes
I think it'd be better to do the grepping in `RestTable#buildTextPlainResponse` because you only render the strings one time and you get to grep on the whole line rather than the values one by one.

2018-06-01 00:55 UTC, nik9000 commented on server/src/main/java/org/elasticsearch/rest/action/cat/AbstractCatAction.java
> +    private String grepFilter;
These are singletons so you'd have to put this somewhere else or parse after rendering. You can use `responseParams` so the request will run.

2018-06-01 00:55 UTC, nik9000 commented on server/src/main/java/org/elasticsearch/rest/action/cat/CatResponseTable.java
> +    private boolean isValidRow;
I'm fairly sure `Table` is only used for cat actions.

2018-06-01 02:16 UTC, jasontedor commented
I do not agree with this feature being added to the codebase. Every feature we add is one that we have to maintain and have to consider maybe breaking in the future. The cat APIs are meant for the command line where grep is readily available?

2018-06-01 02:19 UTC, jasontedor commented
Also this PR needs labels so that the appropriate area team is brought into the conversation.

2018-06-01 09:07 UTC, sohaibiftikhar commented
@nik9000 Thanks for the review. Since the feature itself seems to be in question I will wait until this is decided.

2018-06-01 13:26 UTC, jasontedor commented
Thanks for the PR @sohaibiftikhar yet we are not going to add this functionality to Elasticsearch.

2018-06-01 13:26 UTC, closed without merging