Compliant SAML Response destination check
elastic/elasticsearch pull request #31175
Opened 2018-06-07 14:44 UTC by jkakavas

Only validate the Destination element of an incoming SAML Response
if the SAML Response is signed.
The standard [1] - 3.5.5.2 and [2] - 3.2.2 does mention that the
Destination element is optional and should only be verified when
the SAML Response is signed. Some Identity Provider implementations
are known to not set a Destination XML Attribute in their SAML
responses when those are not signed, so this change also aims to
enhance interoperability.

[1] https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf
[2] https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf

2018-06-07 14:44 UTC, elasticmachine commented
Pinging @elastic/es-security

2018-06-07 17:37 UTC, jaymode approved these changes
LGTM. It would still be good for @tvernum to take a look

2018-06-08 02:38 UTC, tvernum requested changes

2018-06-08 02:38 UTC, tvernum commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/saml/SamlAuthenticator.java
> +        if (response.isSigned() && asc.equals(response.getDestination()) == false) {
I would prefer that we continue to reject _present-but-incorrect_ destinations even for unsigned messages.

So this should be more like
```
   if (asc.equals(response.getDestination()) == false) {
      if(response.isSigned() || Strings.hasText(response.getDestination()) {
         // ...
```

2018-06-08 07:22 UTC, tvernum approved these changes

2018-06-08 17:36 UTC, merged

2018-06-13 18:06 UTC, jpountz commented
@jkakavas This may be backported now.