Limit the number of concurrent requests per node
elastic/elasticsearch pull request #31206
Opened 2018-06-08 15:03 UTC by s1monw

With `max_concurrent_shard_requests` we used to throttle / limit
the number of concurrent shard requests a high level search request
can execute per node. This had several problems since it limited the
number on a global level based on the number of nodes. This change
now throttles the number of concurrent requests per node while still
allowing concurrency across multiple nodes.

Closes #31192

2018-06-08 15:03 UTC, elasticmachine commented
Pinging @elastic/es-search-aggs

2018-06-08 15:48 UTC, jpountz requested changes
It looks like you had a search/replace issue but I like it in general. Given that it is an expert option I don't think we need sophisticated backward compatibility, let's just add a note about it in the breaking changes for 7.0?

2018-06-08 15:48 UTC, jpountz commented on server/src/main/java/org/elasticsearch/action/search/InitialSearchPhase.java
> +                queue = new LinkedList<>();
not that it matters much but ArrayDeque should be better?

2018-06-08 15:48 UTC, jpountz commented on server/src/main/java/org/elasticsearch/action/search/InitialSearchPhase.java
> +            if (queue == null) { // create this lazily
why does it need to be lazy?

2018-06-08 15:48 UTC, jpountz commented on server/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java
> +                // here we have to pendingExecutionsPerNode the filters to the UUID since from now on we use the uuid for the lookup
search/replace issue?

2018-06-08 15:48 UTC, jpountz commented on server/src/main/java/org/elasticsearch/action/search/InitialSearchPhase.java
> +                        shardIt.shardId(), shardIt.getClusterAlias(), shardIt.getOriginalIndices()), shardIndex) {
indentation of the two above lines doesn't help readability

2018-06-08 15:48 UTC, jpountz commented on server/src/main/java/org/elasticsearch/action/search/SearchResponse.java
> +     * @return The profile results or an empty pendingExecutionsPerNode
search/replace issue?

2018-06-08 15:48 UTC, jpountz commented on server/src/main/java/org/elasticsearch/action/search/SearchResponseSections.java
> +     * An empty pendingExecutionsPerNode is returned if profiling was not enabled
search/replace issue?

2018-06-08 15:48 UTC, jpountz commented on server/src/main/java/org/elasticsearch/action/search/SearchTransportService.java
> +     * Return a pendingExecutionsPerNode of nodeId to pending number of search requests.
search/replace issue?

2018-06-08 15:48 UTC, jpountz commented on server/src/main/java/org/elasticsearch/action/search/InitialSearchPhase.java
> +            if (pendingExecutions == null || pendingExecutions.tryAcquire()) {
maybe remove this tryAcquire and go through the else block directly? I think it's simpler if the management of the semaphore permits are contained in PendingExecutions?

2018-06-08 16:37 UTC, s1monw commented
@jpountz I addressed your comments

2018-06-11 06:47 UTC, jpountz approved these changes
LGTM

2018-06-11 06:49 UTC, merged