Update getting-started.asciidoc
elastic/elasticsearch pull request #31295
Opened 2018-06-13 11:47 UTC by teshanya

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2018-06-13 14:04 UTC, elasticmachine commented
Pinging @elastic/es-docs

2018-06-14 19:35 UTC, debadair requested changes

2018-06-14 19:35 UTC, debadair commented on docs/reference/getting-started.asciidoc
This subtly changes the meaning--the intent was to describe a possible scenario. Instead, I would suggest splitting off the scenario into a separate sentence. 

By default, each index in Elasticsearch is allocated 5 primary shards and 1 replica. If you have two nodes in your cluster, your index will have a total of 10 shards: 5 primary shards on one node and 5 replica shards (1 complete replica) on the other.  Replicas are not stored on the same node as an index's primary shards.

2018-08-16 13:13 UTC, javanna commented
CLA not signed, also feedback not addressed. Closing.

2018-08-16 13:13 UTC, closed without merging