[DOCS] Added OSS repo info.
elastic/elasticsearch pull request #31342
Opened 2018-06-14 19:12 UTC by debadair

2018-06-14 19:12 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-06-14 19:19 UTC, jasontedor requested changes
I think we need a similar change on the Debian page?

2018-06-14 19:19 UTC, jasontedor commented on docs/reference/setup/install/rpm.asciidoc
> +The OSS only distribution is available from the
Nit: `OSS-only`?

2018-06-14 19:19 UTC, jasontedor commented on docs/reference/setup/install/rpm.asciidoc
> +The OSS only distribution is available at
Nit: `OSS-only`?

2019-01-11 14:14 UTC, colings86 commented
@debadair Could we add the information to the deb package instructions and get this merged?

2020-05-14 02:51 UTC, closed without merging