AsyncAfterWriteAction error handling improvement, part 1
elastic/elasticsearch pull request #31755
Opened 2018-07-03 08:39 UTC by vladimirdolzhenko

AsyncAfterWriteAction error handling improvement, part 1
Relates to #31716

- any exceptions in `indexShard.sync(location, syncListener)` could be swallowed - as it could be done asynchronously and synchronously - at the moment `listener` could not be registered. 
- closes engine on `ensureTranslogSynced` failure

2018-07-03 08:39 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-07-08 18:08 UTC, bleskes requested changes
Thx Vlad. I left some minor comments. Can you also change the PR title to better describe what the problem is? 

I'm a bit uncomfortable merging this before we have a complete solution to #31716 as it may erroneously fail indexing requests (it's likely that the async write actions finish before the replication operation is completed - which is a situation we were not reporting the error so far). It's good we're doing this in small steps, but how about merging this into a feature branch where we can iterate towards a complete solution? we can then merge it into master in one go and it will also be easier to back port (I think this can go into 6.x, if we do the right thing)

2018-07-09 08:22 UTC, vladimirdolzhenko commented on server/src/test/java/org/elasticsearch/action/support/replication/TransportWriteActionTests.java
> +        CapturingActionListener<TestResponse> listener = new CapturingActionListener<>();
agree

2018-07-09 08:22 UTC, vladimirdolzhenko commented on server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
> +    public void sync(Translog.Location location, Consumer<Exception> syncListener) {
yes, it's required for mocking

2018-07-09 08:29 UTC, vladimirdolzhenko commented on server/src/main/java/org/elasticsearch/action/support/replication/TransportWriteAction.java
> +        private volatile Exception failure;
there is `public final Exception finalFailure;` in `PrimaryResult` (the same in `ReplicaResult`) - shall we consider to merge them ? they do have slightly different (but close) semantic

2018-07-09 08:31 UTC, vladimirdolzhenko commented
thanks @bleskes for comments - I did required changes.

In fact https://github.com/elastic/elasticsearch/pull/31857 (as a complete solution for #31716) is based on this PR.

2018-07-11 13:10 UTC, bleskes approved these changes
I left some a minor comment on the test that isn't required for another review. Can you please merge this into a *feature* branch and proceed with prs to that?

2018-07-11 13:10 UTC, bleskes commented on server/src/test/java/org/elasticsearch/index/replication/AsyncAfterWriteActionTests.java
> +            if (randomBoolean()) {
this is not needed, right?

2018-07-12 10:35 UTC, vladimirdolzhenko commented
merged into [feature/31755](https://github.com/elastic/elasticsearch/tree/feature/31755)

2018-07-12 10:35 UTC, closed without merging