Remove reference to _all in Mapping
elastic/elasticsearch pull request #31781
Opened 2018-07-04 05:54 UTC by Sriegis

All field is removed, so no need to refer to it. It is confusing.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2018-07-04 06:56 UTC, dliappis commented
Hey @Sriegis ,

Thanks for the PR. Would you mind signing the [contributor licensing agreement](https://www.elastic.co/contributor-agreement) so that this can move forwards?

2018-07-05 03:36 UTC, Sriegis commented
Hi @dliappis,

I have already signed it.

Cheers!

2018-07-09 10:42 UTC, elasticmachine commented
Pinging @elastic/es-search-aggs

2018-07-10 17:52 UTC, cbuescher requested changes
@Sriegis thanks for opening this PR. I think mentioning the `_all` field should be removed in version 7.0, but this has already been done on the master branch of the documentation. I don't think we should to remove it in the 6.x versions yet. Although the `_all`field may no longer be enabled for indices created in 6.0+, it can still be present in indices created in 5 which should still work with it in 6.x. For that reason I hope you don't mind if I close this PR. Let me know if you differ.

2018-07-18 10:34 UTC, closed without merging