Ingest: Support integer and long hex values in convert
elastic/elasticsearch pull request #32213
Opened 2018-07-19 20:43 UTC by rjernst

This commit adds checks for hex formatted strings in the convert
processor, allowing strings like `0x1` to be parsed as integer `1`.

closes #32182

2018-07-19 20:43 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-07-19 20:48 UTC, talevy requested changes

2018-07-19 20:48 UTC, talevy commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ConvertProcessor.java
> +                        return Integer.decode(str);
should we add a test for when it is `Integer.decode` that throws the NumberFormatException?

same goes for `Long.decode`

2018-07-19 21:21 UTC, rjernst commented
@talevy I switched to always use `decode`, since that also handles decimal.

2018-07-19 21:26 UTC, jasontedor requested changes
I left a comment.

2018-07-20 00:25 UTC, jasontedor commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ConvertProcessor.java
> +                    return Integer.decode(value.toString());
Here is a test case that passes today and fails after this change:

```diff
diff --git a/modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/ConvertProcessorTests.java b/modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/ConvertProcessorTests.java
index 4a6ce21b2dc..2dece6d1b9a 100644
--- a/modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/ConvertProcessorTests.java
+++ b/modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/ConvertProcessorTests.java
@@ -59,6 +59,14 @@ public class ConvertProcessorTests extends ESTestCase {
         assertThat(ingestDocument.getFieldValue(fieldName, Integer.class), equalTo(randomInt));
     }
 
+    public void testConvertIntWithLeadingZero() throws Exception {
+        IngestDocument ingestDocument = RandomDocumentPicks.randomIngestDocument(random());
+        String fieldName = RandomDocumentPicks.addRandomField(random(), ingestDocument, "010");
+        Processor processor = new ConvertProcessor(randomAlphaOfLength(10), fieldName, fieldName, Type.INTEGER, false);
+        processor.execute(ingestDocument);
+        assertThat(ingestDocument.getFieldValue(fieldName, Integer.class), equalTo(10));
+    }
+
     public void testConvertIntList() throws Exception {
         IngestDocument ingestDocument = RandomDocumentPicks.randomIngestDocument(random());
         int numItems = randomIntBetween(1, 10);
```

Now this gives:

```
FAILURE 0.14s | ConvertProcessorTests.testConvertIntWithLeadingZero <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <10>
   >      but: was <8>
   >    at __randomizedtesting.SeedInfo.seed([535A28EEEA332364:F868934FEE583676]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.ingest.common.ConvertProcessorTests.testConvertIntWithLeadingZero(ConvertProcessorTests.java:67)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
  2> NOTE: leaving temporary files on disk at: /home/jason/src/elastic/elasticsearch/modules/ingest-common/build/testrun/test/J0/temp/org.elasticsearch.ingest.common.ConvertProcessorTests_535A28EEEA332364-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=616, maxMBSortInHeap=6.377649114725773, sim=RandomSimilarity(queryNorm=true): {}, locale=ckb-IQ, timezone=EST
  2> NOTE: Linux 4.17.5-200.fc28.x86_64 amd64/Oracle Corporation 10.0.1 (64-bit)/cpus=20,threads=1,free=492873192,total=536870912
  2> NOTE: All tests run in this JVM: [ConvertProcessorTests]
Completed [1/1] in 0.82s, 1 test, 1 failure <<< FAILURES!


> Task :modules:ingest-common:test FAILED
   [junit4] <JUnit4> says hello! Master seed: 535A28EEEA332364
==> Test Info: seed=535A28EEEA332364; jvm=1; suite=1
Tests with failures:
  - org.elasticsearch.ingest.common.ConvertProcessorTests.testConvertIntWithLeadingZero

   [junit4] JVM J0:     0.31 ..     1.71 =     1.39s
   [junit4] Execution time total: 1.72 sec.
   [junit4] Tests summary: 1 suite, 1 test, 1 failure
.
.
.
```

2018-07-20 00:47 UTC, rjernst commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ConvertProcessor.java
> +                    return Integer.decode(value.toString());
I see the concern. Would you be ok with having a sysprop that controls this in 6.x (defaulting to the old behavior), and logging a deprecation warning in 6.x for the old behavior? While I understand the concern, having numbers zero padded is very rare IMO, so the likelihood this affects that many users seems low.

Alternatively, I can switch back to the old behavior and test for "0x" first, only passing to decode with that prefix.

2018-07-20 01:25 UTC, jasontedor commented on modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ConvertProcessor.java
> +                    return Integer.decode(value.toString());
A system property, or alternatively a converter setting on the processor, is okay with me! The nice thing with the latter is we can introduce this with no behavior change today. I’m open to either approach so curious to hear your preference.

2018-07-23 21:31 UTC, rjernst commented
@talevy @jasontedor I switched back to explicitly checking for 0x.

2018-07-24 03:36 UTC, jasontedor approved these changes
Looks good. Yet, would you add a test in this PR for the case I mentioned (`010` -> `10`) so that we don't have to worry about someone refactoring this in the future and inadvertently making the same break that we avoided here?

2018-07-24 15:54 UTC, rjernst commented
@jasontedor I added a test in 54c30ca

2018-07-24 16:00 UTC, jasontedor approved these changes
LGTM.

2018-07-24 19:05 UTC, talevy approved these changes
LGTM

2018-07-24 19:05 UTC, merged