HLRC: Add delete watch action
elastic/elasticsearch pull request #32337
Opened 2018-07-24 16:50 UTC by ywelsch

Relates #29827

2018-07-24 16:50 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-07-25 08:57 UTC, ywelsch commented
@elasticmachine retest this please

2018-07-25 14:24 UTC, hub-cap requested changes
One Q, one doc failure. Other than that, looks fresh and clean. Great work.

2018-07-25 14:29 UTC, ywelsch commented on client/rest-high-level/src/main/java/org/elasticsearch/client/WatcherClient.java
> +            DeleteWatchResponse::fromXContent, singleton(404));
`RestDeleteWatchAction` returns a 404 with a body if the deleted object is not found. It's a bit unusual, but yeah, if I didn't add this here, the `RestHighLevelClient` class would puke all over itself.

2018-07-25 17:20 UTC, ywelsch commented on docs/java-rest/high-level/x-pack/watcher/delete-watch.asciidoc
> +[[java-rest-high-x-pack-watcher-delete-watch]]
thanks, I've pushed a8b0423 which fixes the copy-paste error (I've tested it also by running your command). I've also added the put-watch and delete-watch action to the actual page (and not only right-hand-side table of contents).

2018-07-25 17:21 UTC, ywelsch commented
Thanks for the quick review @hub-cap. I've addressed your question and the doc failure.

2018-07-25 20:53 UTC, ywelsch commented
@elasticmachine retest this please

2018-07-26 13:05 UTC, ywelsch commented
@elasticmachine retest this please.
@hub-cap CI fails for a million reasons, but none have to do with the PR here

2018-07-30 17:46 UTC, hub-cap commented on client/rest-high-level/src/main/java/org/elasticsearch/client/WatcherClient.java
> +            DeleteWatchResponse::fromXContent, singleton(404));
lol, ok. This is indeed fun.

2018-07-30 17:47 UTC, hub-cap commented on docs/java-rest/high-level/x-pack/watcher/delete-watch.asciidoc
> +[[java-rest-high-x-pack-watcher-delete-watch]]
excellent

2018-07-30 17:47 UTC, hub-cap approved these changes
CI got 99 problems, and a Delete Watch API aint one of em. :shipit:

2018-07-31 08:29 UTC, merged

2018-07-31 08:29 UTC, ywelsch commented
Thanks @hub-cap