[Kerberos] Add authorization realms support to Kerberos realm
elastic/elasticsearch pull request #32392
Opened 2018-07-26 09:27 UTC by bizybot

This commit allows Kerberos realm to delegate `User` resolution
to configured authorization realms. If Kerberos realm is not configured
with any authorization realms then it uses the native role mapper to
resolve User.

2018-07-30 00:42 UTC, tvernum requested changes
You don't seem to add the new setting in `KerberosRealmSettings`

2018-07-30 18:54 UTC, jaymode approved these changes
I left a couple of comments. Otherwise LGTM

2018-07-30 18:54 UTC, jaymode commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/kerberos/KerberosRealm.java
> +                    userPrincipalNameToUserCache.put(username, result.getUser());
I don't think we need to cache here. The delegated realm resolved the user and it should be caching it. The kerberos realm will never use the cache entry that we add

2018-07-30 18:54 UTC, jaymode commented on x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/kerberos/KerberosRealmTestCase.java
> +
nit: drop this extra line

2018-08-02 10:32 UTC, albertzaharovits approved these changes
LGTM too Yogesh!

2018-08-02 11:20 UTC, merged