move replicas action functionality into AllocateAction
elastic/elasticsearch pull request #32523
Opened 2018-07-31 23:13 UTC by talevy

WIP

2018-07-31 23:13 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-08-07 07:57 UTC, colings86 requested changes
I left a comment asking for an extra test but otherwise I think this is good

2018-08-07 07:57 UTC, colings86 commented on x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/indexlifecycle/TimeSeriesLifecycleActionsIT.java
> +    }
Could we also add a test that tests the bug I found (so where we change both replicas and allocate at the same times on a configuration where the resulting nodes would not be enough to allocate the original number of replicas)?

2018-08-07 21:17 UTC, talevy commented
@colings86 thanks for taking a look. I've added a unit test to check the allocation of an unallocated replica

2018-08-08 08:23 UTC, colings86 approved these changes
LGTM

2018-08-08 18:43 UTC, merged