Remove RolloverIndexTestHelper
elastic/elasticsearch pull request #32559
Opened 2018-08-01 18:37 UTC by dakrone

This removes the `RolloverIndexTestHelper` class in favor of making a couple of
getters publically accessible as well as custom building a response object using
JSON parsing.

Relates to #29823

2018-08-01 18:37 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-08-01 18:51 UTC, talevy approved these changes

2018-08-02 08:06 UTC, colings86 requested changes
As with the update settings PR I'm not sure about having the response parsed from a JSON string, it feels ugly to me and IMO more ugly than having the RollloverIndexTestHelper class. I'm wondering if we can't just make the Response constructor public?

Here this is especially ugly to me as the response is not trivial and could well change in the future. If it does, instead of immediately getting compile errors to add the new/remove the old information in the constructor call we would only find out about the change when running tests

2018-08-03 08:12 UTC, colings86 approved these changes
LGTM

2018-08-06 14:53 UTC, merged