Add link to es-kotlin-wrapper-client
elastic/elasticsearch pull request #32618
Opened 2018-08-03 15:50 UTC by jillesvangurp

I recently created this client and think it is of interest to other users. I intend to continue adding features to it in the next months.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
Yes, my details should be on file.
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
Yes
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2018-08-03 15:54 UTC, jillesvangurp commented
I signed the agreement a few years ago and again just now. How do I move this forward?

2018-08-03 16:02 UTC, jillesvangurp commented
ah now it went through. ignore my previous comment

2018-08-06 08:28 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-08-28 10:45 UTC, cbuescher requested changes
Hi @jillesvangurp, looks great. Thanks for the PR and sorry for the delay here. I left a super small nitpicking comment in terms of formatting, other than that I'm happy to merge as soon as you have updated this.

2018-08-28 10:45 UTC, cbuescher commented on docs/community-clients/index.asciidoc
> +* https://github.com/jillesvangurp/es-kotlin-wrapper-client[ES Kotlin Wrapper Client] Kotlin extension functions and abstractions for the {client}/java-api/current/index.html[official Elasticsearch H
super small nit: could you add a colon after the link and put the decription on the next line? This seems to be the formatting in most other places on this page and improves readability of the source file IMHO. Also line wrapping
at about  ~120 chars would be nice although it isn't strictly necessary.

2018-08-28 12:15 UTC, jillesvangurp commented
@cbuescher done!

2018-08-28 12:24 UTC, cbuescher approved these changes
Great thanks, will merge now.

2018-08-28 12:25 UTC, merged