Reduce connections used by MockNioTransport
elastic/elasticsearch pull request #32620
Opened 2018-08-03 17:41 UTC by tbrooks8

The MockNioTransport (similar to the MockTcpTransport) is used for integ
tests. The MockTcpTransport has always only opened a single for all of
its work. The MockNioTransport has awlays opened the default number of
connections (13). This means that every test where two transports
connect requires 26 connections. This is more than is necessary. This
commit modifies the MockNioTransport to only require 3 connections.

2018-08-03 17:41 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-08-06 21:34 UTC, jasontedor requested changes
I left a few comments.

2018-08-06 21:34 UTC, jasontedor commented on test/framework/src/main/java/org/elasticsearch/transport/nio/MockNioTransport.java
> +        ConnectionProfile connectionProfile1 = resolveConnectionProfile(connectionProfile, defaultConnectionProfile);
Can you give it a more meaningful name?

2018-08-06 21:34 UTC, jasontedor commented on test/framework/src/main/java/org/elasticsearch/transport/nio/MockNioTransport.java
> +        for (TransportRequestOptions.Type type :TransportRequestOptions.Type.values()) {
Nit: space after the `:`

2018-08-06 21:34 UTC, jasontedor commented on test/framework/src/test/java/org/elasticsearch/transport/nio/SimpleMockNioTransportTests.java
> +    protected int channelsPerNodeConnection() {
This appears unused?

2018-08-07 15:54 UTC, tbrooks8 commented
@jasontedor - I made changes based on your review. `channelsPerNodeConnection` is used. But I added the `@Override` to make that clear.

2018-08-07 15:59 UTC, jasontedor commented
> `channelsPerNodeConnection` is used. But I added the `@Override` to make that clear.

Great, thanks.

2018-08-07 15:59 UTC, jasontedor approved these changes
LGTM.

2018-08-07 18:52 UTC, merged