Expose whether or not the global checkpoint updated
elastic/elasticsearch pull request #32659
Opened 2018-08-06 22:02 UTC by jasontedor

It will be useful for future efforts to know if the global checkpoint was updated. To this end, we need to expose whether or not the global checkpoint was updated when the state of the replication tracker updates. For this, we add to the tracker a callback that is invoked whenever the global checkpoint is updated. For primaries this will be invoked when the computed global checkpoint is updated based on state changes to the tracker. For replicas this will be invoked when the local knowledge of the global checkpoint is advanced from the primary.

Relates #32651

2018-08-06 22:02 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-08-07 10:22 UTC, bleskes reviewed
I left some initial questions.

2018-08-07 10:43 UTC, jasontedor commented on server/src/main/java/org/elasticsearch/index/seqno/ReplicationTracker.java
> +            onGlobalCheckpointUpdated.accept(globalCheckpoint);
Good catch. That was not intended. I pushed a477ff4f27a91d1a7eec2c6840983ebd8a89e5dc.

2018-08-07 10:50 UTC, jasontedor commented on server/src/main/java/org/elasticsearch/index/seqno/ReplicationTracker.java
> +            onGlobalCheckpointUpdated.accept(globalCheckpoint);
Regarding not invoking the notification under lock, I was tending to avoid complicating these methods (I like that we have `synchronized` as a method modifier) and avoiding dealing with the fact that some of these updates can occur under nested invocations of `synchronized` methods. This would mean returning booleans and dropping the `synchronized` from the method modifiers. In the POC that I have, the callback is "cheap" because it forks invocation of the listeners to another thread (practically to the listener thread pool):

```java
    private void notifyListeners(final long globalCheckpoint, final IndexShardClosedException e) {
        assert (globalCheckpoint == UNASSIGNED_SEQ_NO && e != null) || (globalCheckpoint >= NO_OPS_PERFORMED && e == null);
        if (listeners != null) {
            final List<GlobalCheckpointListener> currentListeners;
            synchronized (this) {
                currentListeners = listeners;
                listeners = null;
            }
            if (currentListeners != null) {
                executor.execute(() -> {
                    for (final GlobalCheckpointListener listener : currentListeners) {
                        try {
                            listener.accept(globalCheckpoint, e);
                        } catch (final Exception caught) {
                            if (globalCheckpoint != UNASSIGNED_SEQ_NO) {
                                logger.warn(
                                        new ParameterizedMessage(
                                                "error notifying global checkpoint listener of updated global checkpoint [{}]",
                                                globalCheckpoint),
                                        caught);
                            } else {
                                logger.warn("error notifying global checkpoint listener of closed shard", caught);
                            }
                        }
                    }
                });
            }
        }
    }
```

I think this is okay?

2018-08-07 10:51 UTC, jasontedor commented
Thanks @bleskes, that was a good catch. I responded to your feedback.

2018-08-07 11:09 UTC, bleskes commented on server/src/main/java/org/elasticsearch/index/seqno/ReplicationTracker.java
> +            onGlobalCheckpointUpdated.accept(globalCheckpoint);
I'm fine if you intend to spawn off to other threads in the outer layers. Indeed the simplicity of the current solution is what was making me doubt towards having it as you did.

2018-08-07 11:19 UTC, bleskes requested changes
Production code LGTM. Left some nits on the testing.

2018-08-07 13:37 UTC, jasontedor commented on server/src/test/java/org/elasticsearch/index/seqno/ReplicationTrackerTests.java
> +        if (globalCheckpoint == tracker.getGlobalCheckpoint()) {
I pushed 614a350a5891a1d4bd5f4d7675c7827dbf0d3f05.

2018-08-07 13:38 UTC, jasontedor commented
@bleskes Will you take one last look?

2018-08-07 14:31 UTC, bleskes approved these changes
LGTM

2018-08-07 19:10 UTC, merged