Do NOT allow termvectors on nested fields
elastic/elasticsearch pull request #32728
Opened 2018-08-09 00:11 UTC by mayya-sharipova

Requesting _termvectors on a nested field or any sub-fields of a nested field
returns empty results.

Closes #21625, #32652

2018-08-09 07:46 UTC, jimczi requested changes
Thanks @mayya-sharipova , I left one comment

2018-08-09 07:46 UTC, jimczi commented on server/src/main/java/org/elasticsearch/index/termvectors/TermVectorsService.java
> +        // and must not be under nested field
We should check all levels in the path, for instance in `foo.bar.baz`, `foo` can be a simple object field and `foo.bar` a nested field.

2018-08-23 20:34 UTC, jimczi approved these changes
LGTM, thanks @mayya-sharipova

2018-08-23 20:46 UTC, merged

2020-12-16 17:44 UTC, BurntSushi commented
@mayya-sharipova Do you happen to know why this change was reverted? As far as I can tell, termvectors still doesn't work with nested documents.

2020-12-16 19:46 UTC, mayya-sharipova commented
@BurntSushi  We were a little hasty in disabling `_termvectors` request on nested docs, because this request works when term vectors are not explicitly stored, and disabling this request all together is a breaking change. That's why we had to revert the PR. 
You are right, the request `_termvectors` still doesn't work if term vectors were explicitly stored and pre-calculated during indexing.

2020-12-16 19:59 UTC, BurntSushi commented
@mayya-sharipova Great, thanks for the clarification!