INGEST: Create Index Before Pipeline Execute
elastic/elasticsearch pull request #32786
Opened 2018-08-10 15:45 UTC by original-brownbear

* Ensures that indices are created before the default pipeline setting is read to correcly handle the case of an index template containing a default pipeline (without the fix the first document does not get the pipeline applied as explained in #32758)
* closes #32758

2018-08-10 15:45 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-08-13 15:48 UTC, rjernst requested changes
A unit test is preferable, and can fit in TransportBulkActionTests? I don't think there should be an integration test, as the behavior is completely internal to TransportBulkAction.

2018-08-13 17:03 UTC, original-brownbear commented
@rjernst 

the problem with a UT (and as a result with leaving the IT out) is that we would basically want to test the the sequence of calling the transport client for setting up the new index, and then only loading the index+pipeline settings (and finally running the pipeline) once that index is up.

That's a lot of new test code that our current `org.elasticsearch.action.bulk.TransportBulkActionIngestTests` doesn't provide (it just hard uses a hard coded subclass of `TransportBulkAction` that has the auto create check overriden to false and uses `null` for the transport client).

... but I guess no time like the present to improve our test infra here :) On it.

2018-08-13 21:29 UTC, original-brownbear commented
@rjernst how about this replacement for the IT:

https://github.com/elastic/elasticsearch/pull/32786/commits/37d28ca0b25bbdeab653457b20fb7069804c7e00

Implemented the index creation check in the same style used by `org.elasticsearch.action.bulk.TransportBulkActionTests.TestTransportBulkAction#createIndex`. Def. a little dirty to override the class we test for testing, but how about it? :)

2018-08-13 22:15 UTC, rjernst approved these changes
Thanks @original-brownbear. This will work I think for now.

2018-08-13 22:15 UTC, rjernst commented on server/src/test/java/org/elasticsearch/action/bulk/TransportBulkActionIngestTests.java
> +        boolean needToCheck;
please add a comment that this makes the return of `needToCheck()` pluggable

2018-08-14 06:59 UTC, original-brownbear commented
@rjernst thanks, comment added, will merge once green :)

2018-08-14 09:27 UTC, merged