Reload Secure Settings REST specs & docs
elastic/elasticsearch pull request #32990
Opened 2018-08-20 15:43 UTC by albertzaharovits

This is a minimal REST API spec and docs for the REST handler for the `_nodes/reload_secure_settings` endpoint.

Relates https://github.com/elastic/elasticsearch/issues/29135

2018-08-20 15:43 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-08-20 16:07 UTC, jaymode requested changes
The password has been removed from this API so we need to fix those docs. I also added the 6.4.1 label to this since we need this on the 6.4 branch too

2018-08-21 12:17 UTC, albertzaharovits commented on docs/reference/cluster/nodes-reload-secure-settings.asciidoc
> +local node's encrypted keystore. Specifically, it broadcasts a password
Hah... I have checked the code of course, and I felt something was missing, I recalled adding the password in the request body, yet now it wasn't there, though I haven't investigated further. Thanks for the pointer Jay!

There is a note after this paragraph, disclaiming the password broadcast statement:
```
Note: At the moment, the password parameter is not supported. The empty password
is the only valid value. Consequently, the request body is empty.
```

I presume you have noticed it, but, in order to be consistent with the pointed change, you wish to banish the mention of 'password'.
I will make the changes.

2018-08-23 09:00 UTC, albertzaharovits commented
@jaymode is this satisfactory? or more thorough testing is required? I would say it's decent as it is.

2018-08-23 17:01 UTC, jaymode approved these changes
LGTM

2018-08-26 11:49 UTC, merged