Build: Create elasticsearch.is-ide plugin
elastic/elasticsearch pull request #33139
Opened 2018-08-24 20:19 UTC by nik9000

This moves the IDE detection code from `build.gradle` into a plugin that
you can get with `apply plugin: 'elasticsearch.is-ide'`. This is useful
because it allows us to move some of our IDE customization code from
`build.gradle` into `BuildPlugin` which should mean that external users
will get the shadow plugin configured correctly.

This does *not* move any more IDE customization into BuildPlugin because
it is a lot more opinionated.

2018-08-27 06:20 UTC, alpar-t requested changes
May be worth to add an integration test to make sure the plugin doesn't flag a regular build as ide ? These tests don't run in the IDE ( because Gradle needs to do some classpath setup to pass the plugin under test to testkit ) so we could run a build with a task that asserts false for the ide properties.

2018-08-27 18:28 UTC, rjernst commented
I think it would make sense to just add this inside BuildPlugin for now, and extract it to a separate plugin if/when that is done as @atorok suggests.

2018-08-27 19:10 UTC, nik9000 commented
We don't apply BuildPlugin to all projects so it'd be more complicated to move it there.

2018-08-27 21:18 UTC, rjernst commented
Which projects do we not apply it to that we need isIdea/isEclipse for?

2018-08-28 05:52 UTC, atorok commented
Anything that has `StandaloneRestTestPlugin` for sure, as they are mutually exclusive. 
It would make things simpler to have a non opinionated "base build plugin"  
( similar to how Gradle has  java-base and java ) that we would apply for all projects from the top of the root projects build script. @nik9000 I'm happy to help out with it if you want too.

2018-08-28 15:30 UTC, nik9000 commented
I don't believe that the distribution project use BuildPlugin either. A less opinionated base plugin would be  fine with me but I don't think I should work on it. If we want to fold this into that effort I can close it.

2018-08-29 12:17 UTC, atorok commented
@nik9000I don't think we need to close this, we could just rename it into something more generic and merge it like that, creating a home for all the other type for information we collect.

2018-12-03 20:30 UTC, nik9000 commented
I don't think this is as needed any more now that we're not using the shadow stuff as much.

2018-12-03 20:30 UTC, closed without merging