[DOCS] Clarifies examples in reindex and task APIs
elastic/elasticsearch pull request #33143
Opened 2018-08-25 00:02 UTC by lcawl

Fixes https://github.com/elastic/elasticsearch/issues/33071

2018-08-25 00:02 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-08-25 00:57 UTC, elasticdog commented
I was performing some upgrades on the elasticsearch-ci cluster, so I'm manually restarting your build.

Jenkins, test this please.

2018-09-12 16:50 UTC, nik9000 requested changes
Sorry I didn't see this 19 days ago!

I left a big thing about wording and a cleanup that'd be nice to do while you are here. And one more thing: I believe all of the docs for this in reindex are also in update-by-query and delete-by-query. Could you make the same changes there?

2018-09-12 21:05 UTC, lcawl commented
retest this please

2018-10-02 13:34 UTC, nik9000 approved these changes

2018-10-02 15:37 UTC, merged