Strengthen FilterRoutingTests
elastic/elasticsearch pull request #33149
Opened 2018-08-25 18:07 UTC by DaveCTurner

Today the FilterRoutingTests take the belt-and-braces approach of excluding
some node attribute values and including some others. This means that we don't
really test that both inclusion and exclusion work correctly: as long as one of
them works as expected then the test will pass. This change improves these
tests by only using one approach at once, demonstrating that both do indeed
work.

2018-08-25 18:07 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-08-25 18:36 UTC, jasontedor requested changes
I am in favor of the change, it's a good change. But I do have a difference in philosophy on using randomness for branch coverage. I would like to see the codebase move more and more away from this.

2018-08-25 18:36 UTC, jasontedor commented on server/src/test/java/org/elasticsearch/cluster/routing/allocation/FilterRoutingTests.java
> +        if (randomBoolean()) {
I like what you're doing here to improve these tests. However, I have been moving away from using randomness as a poor man's way to get branch coverage. I think that randomness is good for testing edge cases by randomly varying input data, but I don't like seeing it to half of the time cover one branch and half of the time cover another. I would prefer to see two tests here.

2018-08-26 12:55 UTC, DaveCTurner commented
Seems reasonable. This kinda snowballed as I dug into the implementation and realised there were quite a lot of things that aren't very well covered at the moment:

- filters on multiple attributes
- combinations of filters of different senses
- `require` filters
- wildcards

Some of these are somewhat covered at a lower level by `DiscoveryNodeFiltersTests`, but this doesn't properly verify the plumbing in `FilterAllocationDecider`, and I thought that it'd be good to add a few tests to show how this all fits together too.

2018-09-01 12:34 UTC, jasontedor approved these changes
LGTM.

2018-09-10 09:23 UTC, merged