[CCR] Introduce leader index name & last fetch time stats to stats api response
elastic/elasticsearch pull request #33155
Opened 2018-08-27 04:02 UTC by martijnvg

2018-08-27 04:02 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-08-27 10:51 UTC, jasontedor requested changes
I left a comment about using the relative time provider, so we would report how long it has been since the most recent fetch. In general, I think this changes like this would be better as two separate PRs, these are separate changes.

2018-08-27 10:51 UTC, jasontedor commented on x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java
> +                        LongSupplier currentTimeSupplier) {
I think we can use the `relativeTimeSupplier` and merely report the time (elapsed) since the last fetch.

2018-08-27 11:28 UTC, martijnvg commented on x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTaskStatusTests.java
> +        assertThat(newInstance.timeSinceLastFetch(), equalTo(expectedInstance.timeSinceLastFetch()));
🤦‍♂️

2018-08-27 11:30 UTC, martijnvg commented
@jasontedor I've updated the PR to use report time since last fetch instead of the timestamp the last fetch occurred. Next time I will split a change like this into 2 PRs.

2018-08-27 20:31 UTC, jasontedor reviewed
Overall looking good, I left a comment.

2018-08-27 20:31 UTC, jasontedor commented on x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java
> +            timeSinceLastFetchMillis = 0;
I don't think it should be 0, I think it should be -1 so that we can distinguish a fetch just happened less than 1ms ago from a fetch just happened.

2018-08-27 20:31 UTC, jasontedor commented on x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java
> +            timeSinceLastFetchMillis = 0;
This means a serialization change too, to support -1.

2018-08-28 01:59 UTC, martijnvg commented
@jasontedor I've addressed that comment.

2018-08-28 11:08 UTC, jasontedor requested changes
I left one important comment, the rest is cosmetic. We will get this in on the next iteration.

2018-08-28 11:08 UTC, jasontedor commented on x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java
> +            leaderIndex = params.getLeaderClusterAlias() + ":" + params.getLeaderShardId().getIndexName();
I think that we should avoid re-computing this value every time we get status (think of a monitoring system polling the stats every second). We are creating unnecessary garbage on every poll for every shard.

2018-08-28 11:08 UTC, jasontedor commented on x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java
> +            leaderIndex = params.getLeaderClusterAlias() + ":" + params.getLeaderShardId().getIndexName();
Additionally, that's a calculation done under a lock, a lock that synchronizes a lot of other methods in this class.

2018-08-28 11:08 UTC, jasontedor commented on x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java
> +        private final long timeSinceLastFetchMillis;
Thank you for keeping these in the same order as the constructor parameters, etc. 🙏

2018-08-28 11:08 UTC, jasontedor commented on x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java
> +                String leaderIndex,
This can be `final`.

2018-08-28 11:08 UTC, jasontedor commented on x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java
> +        public long timeSinceLastFetch() {
Add `Millis` to the name.

2018-08-28 11:56 UTC, martijnvg commented
Thanks @jasontedor. I've updated the PR.

2018-08-28 12:31 UTC, jasontedor approved these changes
LGTM.

2018-08-29 03:54 UTC, merged