[SECURITY] Set Auth-scheme preference
elastic/elasticsearch pull request #33156
Opened 2018-08-27 04:26 UTC by bizybot

Some browsers (eg. Firefox) behave differently when presented with
multiple auth schemes in 'WWW-Authenticate' header. The expected
behavior is that browser select the most secure auth-scheme before
trying others, but Firefox selects the first presented auth scheme and
tries the next ones sequentially. As the browser interpretation is
something that we do not control, we can at least present the auth
schemes in most to least secure order as the server's preference.

This commit modifies the code to collect and sort the auth schemes
presented by most to least secure. The priority of the auth schemes is
fixed, the lower number denoting more secure auth-scheme.
The current order of schemes based on the ES supported auth-scheme is
[`Negotiate`, `Bearer`,`Basic`] and when we add future support for
other schemes we will need to update the code. If need be we will make
this configuration customizable in future.

Unit test to verify the `WWW-Authenticate` header values are sorted by
server preference as more secure to least secure auth schemes.
Tested with Firefox, Chrome, Internet Explorer 11.

Closes#32699

2018-08-27 04:26 UTC, elasticmachine commented
Pinging @elastic/es-security

2018-08-28 19:00 UTC, jaymode requested changes

2018-08-29 16:38 UTC, jaymode requested changes

2018-08-29 16:38 UTC, jaymode commented on x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authc/DefaultAuthenticationFailureHandlerTests.java
> +        Arrays.sort(schemes, (o1, o2) -> authSchemePriority(o1).compareTo(authSchemePriority(o2)));
can you make this explicit? ie there could be a bug in `authSchemePriority` so we should validate Negotiate first, then bearer, then basic

2018-09-05 17:48 UTC, jaymode approved these changes
I left one minor comment, otherwise LGTM

2018-09-05 17:48 UTC, jaymode commented on x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authc/DefaultAuthenticationFailureHandlerTests.java
> +        failureResponeHeaders.put("WWW-Authenticate", Arrays.asList(basicAuthScheme, bearerAuthScheme, negotiateAuthScheme));
We should randomize the order of this list, ie `Collections.shuffle(list, random())`

2018-09-06 22:46 UTC, merged

2018-09-24 10:06 UTC, azasypkin commented
> Some browsers (eg. Firefox) behave differently when presented with
multiple auth schemes in 'WWW-Authenticate' header. The expected
behavior is that browser select the most secure auth-scheme before
trying others, but Firefox selects the first presented auth scheme and
tries the next ones sequentially. As the browser interpretation is
something that we do not control, we can at least present the auth
schemes in most to least secure order as the server's preference.

@bizybot, have we filed a bug against Firefox (assuming there was no existing one)? Can you please share a link? Thanks!

2018-09-24 10:43 UTC, tvernum commented
@azasypkin
See https://github.com/elastic/elasticsearch/issues/32699#issuecomment-412763576

2018-09-24 11:36 UTC, azasypkin commented
> See #32699 (comment)

Thanks! `Reported: 8 years ago` :disappointed:

2018-09-24 12:45 UTC, tvernum commented
Yeah, we decided it probably wasn't worth waiting on an upstream fix.