Core: Fix epoch millis java time formatter
elastic/elasticsearch pull request #33302
Opened 2018-08-31 11:15 UTC by spinscale

The existing implemention could not deal with negative numbers as well
as +- 999 milliseconds around the epoch.

This commit uses Instant.ofEpochMilli() and tries to parse the input to
a number instead of using a date formatter.

2018-08-31 11:15 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-08-31 14:21 UTC, cbuescher requested changes
@spinscale looks good, but I played around with the output of the formatter a bit for negative numbers and ran into some unexpected results. I left an example, maybe you can comment?

2018-08-31 14:50 UTC, spinscale commented on server/src/main/java/org/elasticsearch/common/time/DateFormatters.java
>          .appendValue(ChronoField.INSTANT_SECONDS, 1, 19, SignStyle.NEVER)
Good call. It seems that the date time formatter cannot deal with negative dates... overwriting the `format()` is something we can do in the custom implementation though.

2018-08-31 14:50 UTC, spinscale commented on server/src/main/java/org/elasticsearch/common/time/DateFormatters.java
> +     * or anything +- 999 milliseconds around the eopch
fixed

2018-08-31 14:51 UTC, spinscale commented on server/src/main/java/org/elasticsearch/common/time/DateFormatters.java
> +        EpochDateTimeFormatter() {
the class was already private... but fixed it for both ctors two as well

2018-09-03 09:25 UTC, cbuescher approved these changes
Thanks for the change and additional test. LGTM

2018-09-03 11:13 UTC, merged