Allow for pluggable search threadpool
elastic/elasticsearch pull request #33732
Opened 2018-09-15 07:36 UTC by s1monw

Today all searches happen on the search threadpool which is the correct
behavior in almost any case. Yet, there are exceptions where for instance
searches are required to succeed ie. in the case of a .security index.
These searches should not be rejected if a node is under load. There are other
more specialized usecases were searches should be passed through a single-thread
threadpool to reduce impact on a node.

Relates to #33205

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2018-09-15 07:36 UTC, elasticmachine commented
Pinging @elastic/es-search-aggs

2018-09-15 07:38 UTC, s1monw commented
the majority of the change is cutting SearchService over to async execution. The actual addition of the setting and such is really a smallish change.

2018-09-17 08:51 UTC, tlrx approved these changes
LGTM - I didn't expect this change to be so simple.

2018-09-17 08:51 UTC, tlrx commented on server/src/main/java/org/elasticsearch/search/SearchService.java
> +                                                     ActionListener<ScrollQuerySearchResult> listener) {
Nit: ident

2018-09-17 08:51 UTC, tlrx commented on server/src/main/java/org/elasticsearch/search/SearchService.java
> +
Nit: extra line

2018-09-17 15:08 UTC, jpountz commented
I'm curious why we now fork can_match tasks unless the default threadpool is used, what is the benefit compared to never forking?

2018-09-17 16:17 UTC, jasontedor commented on server/src/main/java/org/elasticsearch/index/IndexSettings.java
> +                throw new IllegalArgumentException("Invalid valid for [index.search.threadpool] - " + s + " is a reserved built-in " +
`valid` -> `value`

2018-09-17 16:24 UTC, jasontedor requested changes
I have some concerns.

2018-09-17 18:29 UTC, s1monw commented
@jasontedor here is my suggestion. 
 1. I will add a `search_single` threadpool with a single thread and a queue.
 2. users can either decide to go to `search_single` or `search`
 3. in a seperate PR I add an option on the SearchRequest that does a _force put_ on the queue that way we can fix #33205 by special casing where necessary and not globally on the index.

@jpountz with 2. I think your question is more clear as well. for the  `search_single` case we need to make sure nobody accesses more than one reader of an index that is marked as `search_single` at the same time. 

I guess that makes this change more contained and addresses all concerns.

2018-09-17 18:37 UTC, jasontedor commented
@s1monw The plan sounds good, I think that we are mostly on the same page. I do wonder if we need to allow users to use `search_single` AKA `frozen`, i think we can do it automatically for frozen indices and otherwise use `search`? Then this would not need to be user configurable at all?

2018-09-17 18:52 UTC, s1monw commented
> @s1monw The plan sounds good, I think that we are mostly on the same page. I do wonder if we need to allow users to use search_single AKA frozen, i think we can do it automatically for frozen indices and otherwise use search? Then this would not need to be user configurable at all?

I can do that. Private setting sounds good to me. then this PR will only add the setting and the reading. The test can add a plugin that allows changing it.

2018-09-17 18:53 UTC, jasontedor commented
Thanks @s1monw.

2018-09-17 19:01 UTC, jpountz commented
The plan sounds good to me too. Then maybe call the setting "frozen_search" rather than "search_single" since it would be dedicated to frozen indices?

2018-09-19 09:12 UTC, s1monw commented
@jasontedor @jpountz I pushed more changes

2018-09-19 10:22 UTC, jpountz approved these changes

2018-09-19 20:52 UTC, jasontedor approved these changes
Looks phenomenal @s1monw. Thank you for the extra iterations.

2018-09-20 11:43 UTC, merged