Ingest Attachement: Upgrade tika to v1.19
elastic/elasticsearch pull request #33896
Opened 2018-09-20 12:11 UTC by jkakavas

Upgrades Apache Tika to v1.19

Also upgrades transitive dependencies:

  pdfbox : 2.0.9 -> 2.0.11
  poi : 3.17 -> 4.0.0'
  commons-compress:1.16.1 -> 1.18

2018-09-20 12:11 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-09-22 12:42 UTC, jasontedor requested changes
I left one comment, capturing our discussion from another thread.

2018-09-22 12:42 UTC, jasontedor commented on plugins/ingest-attachment/src/main/plugin-metadata/plugin-security.policy
> +  // TODO: Remove once https://issues.apache.org/jira/browse/TIKA-2731 is resolved
As we discussed via another thread, let’s hold here until 1.19.1 is released so that we do not need to make this grant.

2018-09-28 14:45 UTC, jaymode commented
I'm not sure if you want to add un-muting tests that failed on JDK11 to this PR as they were waiting on this upgrade; if you do the issues are #31456 and #31305.

2018-10-01 17:01 UTC, jkakavas commented
Thanks for bringing this to my attention @jaymode . I will make sure the issues are resolved with 1.19.1 and unmute them in this PR as part of the upgrade

2018-10-10 13:11 UTC, jasontedor approved these changes

2018-10-11 14:44 UTC, jkakavas commented
The CI failure was a transient issue: 

```
 > Could not resolve org.hamcrest:hamcrest-core:1.3.
10:14:46   [bwc]       > Could not get resource 'https://jcenter.bintray.com/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom'.
10:14:46   [bwc]          > Could not HEAD 'https://jcenter.bintray.com/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom'. Received status code 502 from server: Bad Gateway
```

I unmuted previously failing tests from  #31456 and #31305 since we needed the extra CI run eitherway

2018-10-12 16:09 UTC, merged