Rename CCR APIs
elastic/elasticsearch pull request #34027
Opened 2018-09-25 05:57 UTC by martijnvg

Rename:
* POST `/{index}/_ccr/create_and_follow` to PUT `/{index}/_ccr/follow`
* `/{index}/_ccr/unfollow` to `/{index}/_ccr/pause_follow`
* `/{index}/_ccr/follow` to `/{index}/_ccr/resume_follow`

Relates to #33931

2018-09-25 05:57 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-09-25 13:22 UTC, jasontedor requested changes
I left one comment.

2018-09-25 13:35 UTC, martijnvg commented on x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/rest/RestFollowAction.java
> +public class RestFollowAction extends BaseRestHandler {
I did the rename here: 2f24ad8dcaac360416b77807cf38df808fbc581f

2018-09-27 18:20 UTC, jasontedor approved these changes
LGTM.

2018-09-28 06:02 UTC, merged