ES-32763 index.translog.sync_interval cannot be updated dynamically.
elastic/elasticsearch pull request #34104
Opened 2018-09-27 04:37 UTC by jubyvictor

…et dynamically

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2018-09-27 08:43 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-09-27 08:43 UTC, markharwood commented
Relates to https://github.com/elastic/elasticsearch/issues/32763

2018-09-27 16:35 UTC, ywelsch requested changes
While there's testing on the IndexSettings level, I don't think that the update logic actually takes effect on a live shard. The reason for this is that the fsyncTask (see IndexService) is currently only rescheduled when translog durability changes, not when the translog sync interval changes.

2018-10-02 00:15 UTC, jubyvictor commented on CONTRIBUTING.md
> +	See [cli example](CONTRIB_REBASE_EG.md)
I did check that the /_settings reflected the applied changes, but I'll double check. I'll submit the documentation changes as a separate PR.

2018-10-04 04:26 UTC, closed without merging