Allowing {index}/_xpack/rollup/data to accept comma delimited list
elastic/elasticsearch pull request #34115
Opened 2018-09-27 16:01 UTC by benwtrent

{index}/_xpack/rollup/data is supposed to be able to return given a comma delimited list of indices, there was a slight oversight on the REST facing side that caused index lookups to be the literal string and not an expanded list from the parameter. 

I apologize if the labels are not correct, this is my first bug PR referencing a released version.

2018-09-27 16:01 UTC, elasticmachine commented
Pinging @elastic/es-search-aggs

2018-09-27 16:38 UTC, benwtrent commented
Jenkins retest this please

2018-09-27 19:08 UTC, benwtrent commented
Jenkins, retest this please

2018-09-28 18:56 UTC, jimczi requested changes
Good catch @benwtrent ! I left some comments

2018-09-28 18:56 UTC, jimczi commented on x-pack/plugin/src/test/resources/rest-api-spec/test/rollup/get_rollup_index_caps.yml
> +- do:
You'll need to add a skip section to not run this test on version that don't have the fix:
````
  - skip:
      version: " - 6.99.99"
      reason: "comma delimited index support was fixed in 7.0"
````
After the backport to 6x we'll change the skip version to 6.4.99.

2018-09-28 18:56 UTC, jimczi commented on x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/rest/RestGetRollupIndexCapsAction.java
> +            new GetRollupIndexCapsAction.Request(Strings.commaDelimitedListToStringArray(index), options);
Can you use `Strings.splitStringByCommaToArray`, it should be equivalent but that's the function used by the other action when they parse the `index` param.

2018-10-02 12:10 UTC, jimczi approved these changes
LGTM, thanks @benwtrent

2018-10-02 13:21 UTC, merged