Create/Update role mapping API
elastic/elasticsearch pull request #34171
Opened 2018-10-01 07:00 UTC by bizybot

This change adds support for create/update role mapping API
to the high level rest client.

2018-10-01 07:00 UTC, elasticmachine commented
Pinging @elastic/es-security

2018-10-01 07:00 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-10-02 12:29 UTC, jkakavas commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/PutRoleMappingRequest.java
> +        super();
Is this needed?

2018-10-02 13:52 UTC, jkakavas reviewed
LGTM with some minor comments @bizybot

2018-10-02 13:52 UTC, jkakavas commented on client/rest-high-level/src/test/java/org/elasticsearch/client/security/PutRoleMappingRequestTests.java
> +        default:
Since this can never be anything else than `0,1,2`, maybe make the default case one of the permutations?

2018-10-02 16:45 UTC, jaymode requested changes

2018-10-02 16:45 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/PutRoleMappingResponse.java
> +    private boolean created;
make it final

2018-10-02 16:45 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/PutRoleMappingRequest.java
> +    private String name;
make all of the class member variables final

2018-10-02 16:45 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/PutRoleMappingRequest.java
> +    @Nullable private Map<String, Object> metadata;
metadata cannot be null based on the constructor

2018-10-02 16:45 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/PutRoleMappingRequest.java
> +    @Nullable private RefreshPolicy refreshPolicy;
refreshPolicy cannot be null based on the constructor

2018-10-02 16:45 UTC, jaymode commented on client/rest-high-level/src/test/java/org/elasticsearch/client/security/PutRoleMappingRequestTests.java
> +        if (Strings.hasText(name) == false) {
rather than use randomization for these branches can we just test the valid case and invalid cases?

2018-10-02 16:45 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/PutRoleMappingResponse.java
> +        PARSER.declareObject((a,b) -> {}, (parser, context) -> null, new ParseField("role_mapping")); // ignore the role_mapping field!
is there a change here that is missing to move created as a top level field in the PutRoleMappingResponse?

2018-10-02 16:46 UTC, jaymode commented
Also @bizybot can you please add more detail to the commit message. A specific item you could include would be how this builds on the work done to the expression dsl in #33745

2018-10-03 02:11 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/PutRoleMappingResponse.java
> +        PARSER.declareObject((a,b) -> {}, (parser, context) -> null, new ParseField("role_mapping")); // ignore the role_mapping field!
I am confused how this works when created is only within role mapping but we ignore role mapping

2018-10-03 18:29 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/PutRoleMappingResponse.java
> +        PARSER.declareObject((a,b) -> {}, (parser, context) -> null, new ParseField("role_mapping")); // ignore the role_mapping field!
I think I understand what is happening. The parser finds the role_mapping object, and calls our declared methods where we return null and do not actually consume content using the parser. The object parser then moves to the next item which is the created field, and parses it.

I personally do not like this behavior as it is very sneaky. @nik9000 I see your name on a lot of the lines of these classes, maybe you have some thoughts on this behavior?

>  saw we did similar in PutUserResponse

PutUserResponse did this as a BWC method. I added a top-level created field in 6.x so we could remove the nested field in master for 7.0, see https://github.com/elastic/elasticsearch/pull/33512

2018-10-05 15:14 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/PutRoleMappingResponse.java
> +        PARSER.declareObject((a,b) -> {}, (parser, context) -> null, new ParseField("role_mapping")); // ignore the role_mapping field!
@bizybot can you open up a issue that describes this behavior of the object parser and label it with discuss? Then we can move this PR forward.

2018-10-15 16:12 UTC, jaymode approved these changes
I left one comment. Otherwise LGTM

2018-10-15 16:12 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/PutRoleMappingResponse.java
> +        PARSER.declareObject((a,b) -> {}, (parser, context) -> null, new ParseField("role_mapping")); // ignore the role_mapping field!
can you please document how this code works and include a link to that issue in the comment. Its not straightforward and anything like this should be documented

2018-10-16 02:05 UTC, merged