Add Javadoc for X-Pack SecurityClient
elastic/elasticsearch pull request #34260
Opened 2018-10-03 09:48 UTC by hmcc

Connected to #30077.

I've added Javadoc for all the methods in X-Pack's `SecurityClient.java`.

When I was trying to find out more about how the methods were used, I realised that some of them *weren't* used. Rather than listing them out here, I'll add a second commit which removes them, which I'm very happy to revert.

2018-10-03 12:19 UTC, elasticmachine commented
Pinging @elastic/es-security

2018-10-05 15:41 UTC, jaymode commented
Hi @hmcc, thank you for your contribution. 

> When I was trying to find out more about how the methods were used, I realised that some of them weren't used.

Some of these methods are not used in our code base but are made available for our users. The SecurityClient can be used within custom java code so we provide methods for most APIs even if they are not used within our code base. If you do not mind reverting that commit, that would be great.

2018-10-07 19:16 UTC, hmcc commented
No problem, thanks for explaining!

2018-10-15 16:04 UTC, jaymode requested changes
I started looking at this and left a general comment that needs to be addressed regarding the `prepare*` javadocs

2018-10-15 16:04 UTC, jaymode commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/client/SecurityClient.java
> +     * Populates a {@link ClearRealmCacheRequest} to clear the realm caches.
I would say that this comment applies generally to all of the changes to `prepare*` methods

2018-10-16 06:53 UTC, hmcc commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/client/SecurityClient.java
> +     * Populates a {@link ClearRealmCacheRequest} to clear the realm caches.
Yes, agreed; that was only done for consistency with what was there before. I'll change the `prepare*` methods now.

2018-10-17 16:43 UTC, jaymode commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/client/SecurityClient.java
> +     * Populates a {@link ClearRealmCacheRequest} to clear the realm caches.
You're absolutely correct that some have a different behavior; the javadocs for the change password method would be fine saying something like "Populates a change password request to change the password of the provided user".

2018-10-19 12:34 UTC, hmcc commented
@jaymode, I've updated the `prepare*` Javadocs where nothing is populated. I've left things alone where most/all of the request is populated, and I've replaced "populates" with "initializes" if some fields are populated but not others.

Is that OK?

2018-11-09 16:31 UTC, closed without merging