HLRC XPack Protocol clean up: Licence, Misc
elastic/elasticsearch pull request #34469
Opened 2018-10-15 15:45 UTC by vladimirdolzhenko

Move parts related to XPack Licence and Misc from protocol to client

Relates #34451

2018-10-15 15:45 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-10-15 15:55 UTC, vladimirdolzhenko commented on client/rest-high-level/src/test/java/org/elasticsearch/client/LicensingIT.java
> +        // TODO
we need start trial ( https://github.com/elastic/elasticsearch/pull/33406 ) as a roll back here

2018-10-16 13:27 UTC, hub-cap requested changes
I think we can split this into 2 PRs, one for the refactor,  and one for the protocol-test stuff. I dont think they are related, either. <3 for the cleanup!!!

2018-10-16 13:27 UTC, hub-cap commented on client/rest-high-level/src/main/java/org/elasticsearch/client/license/GetLicenseRequest.java
> -public class XPackUsageRequest extends MasterNodeRequest<XPackUsageRequest> {
lolwut... thanks for nothing, git.

2018-10-16 13:27 UTC, hub-cap commented on client/rest-high-level/src/main/java/org/elasticsearch/client/license/PutLicenseResponse.java
> -        PARSER.declareBoolean(constructorArg(), new ParseField("acknowledged"));
i actually dont mind having these defined here if we dont use them anywhere else.

2018-10-16 19:07 UTC, vladimirdolzhenko commented
@elasticmachine test this please

2018-10-17 11:49 UTC, vladimirdolzhenko commented
@elasticmachine test this please

2018-10-17 13:57 UTC, vladimirdolzhenko commented
run gradle build tests please

2018-10-17 16:09 UTC, vladimirdolzhenko commented
run gradle build tests please

2018-10-18 14:08 UTC, vladimirdolzhenko commented
@hub-cap I've raised another PR for cross xpack-hlrc tests (actually it's PoC) #34547 . Could you pls have another look into this ?

2018-10-19 13:40 UTC, vladimirdolzhenko commented
run gradle build tests please

2018-10-19 14:52 UTC, hub-cap approved these changes
Looks good now, ty for splitting.

2018-10-19 17:05 UTC, merged

2018-10-19 17:06 UTC, vladimirdolzhenko commented
thanks @hub-cap for the review