Core: Parse floats in epoch millis parser
elastic/elasticsearch pull request #34504
Opened 2018-10-16 07:30 UTC by spinscale

In order to stay BWC compatible with joda time, the epoch millis date
formatter needs to properly parse dates with a dot like `123.45`. This
adds this functionality for the epoch millis parser in the same way as
for the epoch seconds parser.

2018-10-16 07:30 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-10-18 11:27 UTC, cbuescher requested changes
@spinscale I left a short question, otherwise I think this looks good.

2018-10-18 11:57 UTC, spinscale commented on server/src/main/java/org/elasticsearch/common/time/EpochMillisDateFormatter.java
> +                if (inputs[1].length() > 9) {
totally. fixed and tested...

I also fixed the negative handling of the epoch seconds parsing which was broken and added a test

2018-10-18 12:05 UTC, cbuescher approved these changes
@spinscale  Thanks, LGTM

2018-10-18 12:38 UTC, spinscale commented
@elasticmachine retest this please

2018-10-19 08:02 UTC, merged