Graph: Move qa into plugin
elastic/elasticsearch pull request #34517
Opened 2018-10-16 12:32 UTC by nik9000

Move `x-pack/qa/smoke-test-graph-with-security` to
`x-pack/plugin/graph/qa/security` which should make it easier to run all
of the tests with a single command. It also lines up the directories
more closely with newer projects like cross cluster replication.

2018-10-16 12:32 UTC, elasticmachine commented
Pinging @elastic/es-search-aggs

2018-10-16 12:45 UTC, nik9000 commented on x-pack/plugin/graph/qa/build.gradle
> +    // HACK: please fix this
I'm checking on whether we need this. SQL didn't.

2018-10-16 12:45 UTC, nik9000 commented on x-pack/plugin/graph/qa/build.gradle
> +    // HACK: please fix this
It wasn't required so I've removed it.

2018-10-16 20:41 UTC, nik9000 commented
@elasticmachine retest this please

2018-10-16 20:54 UTC, jasontedor requested changes
Thanks so much for picking this up @nik9000. I am so happy to see us making these changes, I think it is better productivity-wise and organizationally for individual developers on these sub-plugins.

I don't think this work is enough though. I think that you need to make a change like this to `graph/build.gradle`:

```
diff --git a/x-pack/plugin/graph/build.gradle b/x-pack/plugin/graph/build.gradle
index 069bfa5fbbe..f1bac2e54d4 100644
--- a/x-pack/plugin/graph/build.gradle
+++ b/x-pack/plugin/graph/build.gradle
@@ -15,6 +15,15 @@ dependencies {
     testCompile project(path: xpackModule('core'), configuration: 'testArtifacts')
 }
 
+// add all sub-projects of the qa sub-project
+gradle.projectsEvaluated {
+    project.subprojects
+            .find { it.path == project.path + ":qa" }
+            .subprojects
+            .findAll { it.path.startsWith(project.path + ":qa") }
+            .each { check.dependsOn it.check }
+}
+
 run {
     plugin xpackModule('core')
 }
```

Note that we have similar logic in the `ccr/build.gradle` file. You're welcome to add some logic higher up to add this automatically in a follow-up, but I am pretty sure that something like this is needed for this change.

The difference is that then `:x-pack:plugin:graph:check` will run these tests, whereas with the change you have proposed here it would only run under a full `check`.

Additionally, let us call this `with-security` instead of `security`. Then I think the intent of the tests is clearer.

2018-10-16 20:55 UTC, jasontedor commented
One additional point, I think it is good to notify the search team of this change with the `:Search/Graph` label yet I think of this as a `:Core/Build` change too.

2018-10-17 17:51 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-10-17 17:59 UTC, nik9000 commented
> The difference is that then `:x-pack:plugin:graph:check` will run these tests, whereas with the change you have proposed here it would only run under a full `check`.

I talked to @jasontedor about this. I always do things like `./gradlew -p x-pack/plugin/graph check` which works with the change as I proposed it. Apparently it is much more common for folks to do `./gradlew x-pack:plugin:graph:check` which requires the change that @jasontedor asked for. I'm making that change now. And the `security` -> `with-security` change.

2018-10-17 18:03 UTC, nik9000 reviewed
@jasontedor I've pushed an update with the changes that you asked for.

2018-10-17 18:03 UTC, nik9000 commented on x-pack/plugin/graph/qa/build.gradle
> +    // HACK: please fix this
I was running the tests wrong. It is required.

2018-10-17 18:12 UTC, jasontedor approved these changes
LGTM.

2018-10-18 06:59 UTC, atorok commented
See my comment on #34496 about the Gradle code to pull all the checks together.
+1 on having a central place to deal with this, having to cross reference comments on PRs is a good example of why it would be better not to duplicate small snippets like these throughout the build. Also helps allot with consistency.

2018-10-30 19:14 UTC, merged