ingest: documentation for the drop processor
elastic/elasticsearch pull request #34570
Opened 2018-10-17 19:49 UTC by jakelandis

part of #33188

------
<img width="765" alt="image" src="https://user-images.githubusercontent.com/976291/47112359-bce6ea80-d21b-11e8-9543-00abbe9544cd.png">

2018-10-17 19:49 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-10-18 05:29 UTC, original-brownbear commented on docs/reference/ingest/ingest-node.asciidoc
> +Drops the document without raising any an errors. This is useful to prevent the document from
Typo `s/an//`

2018-10-18 05:29 UTC, original-brownbear requested changes
One typo :)

2018-10-18 14:16 UTC, jakelandis commented on docs/reference/ingest/ingest-node.asciidoc
> +Drops the document without raising any an errors. This is useful to prevent the document from
@original-brownbear - thanks! fixed.

2018-10-18 14:20 UTC, original-brownbear approved these changes
@jakelandis thanks LGTM

2018-10-23 07:21 UTC, rjernst approved these changes
LGTM too, just one ask.

2018-10-23 17:30 UTC, merged

2018-10-24 18:06 UTC, jakelandis commented
6.5 backport: https://github.com/elastic/elasticsearch/commit/aed947f3f1edbae1021a503a12406fa4127febf6