[ILM] Add null check to CopyExecutionStateStep
elastic/elasticsearch pull request #34619
Opened 2018-10-18 20:54 UTC by gwbrown

Adds a null check for IndexMetaData similar to those in #33455.

2018-10-18 20:54 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-10-18 21:17 UTC, talevy requested changes
just left a small nit

2018-10-18 21:17 UTC, talevy commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/CopyExecutionStateStep.java
> +    private static final Logger logger = LogManager.getLogger(CopyExecutionStateStep.class);
nit, can we push private statics to right after public statics?

2018-10-22 15:59 UTC, dakrone approved these changes

2018-10-22 16:15 UTC, gwbrown commented
@elasticmachine test this please

2018-10-23 14:46 UTC, merged