Add start rollup job support to HL REST Client
elastic/elasticsearch pull request #34623
Opened 2018-10-18 22:32 UTC by cbuescher

This change adds support for starting a rollup job to High Level REST Client.

Relates to #29827

2018-10-18 22:32 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-10-18 22:32 UTC, elasticmachine commented
Pinging @elastic/es-search-aggs

2018-10-22 18:39 UTC, cbuescher commented
@elasticmachine test this please

2018-10-22 20:28 UTC, cbuescher commented
@elasticmachine test this please

2018-10-24 16:44 UTC, hub-cap requested changes
One nit and one larger comment that I think is worth discussing.

2018-10-25 10:13 UTC, cbuescher commented on client/rest-high-level/src/main/java/org/elasticsearch/client/rollup/AcknowledgedResponse.java
> +            builder.field(field, isAcknowledged());
np, will update

2018-10-25 10:14 UTC, cbuescher commented
@hub-cap thanks for the review, I updated the PR. Can you take a second look?

2018-10-25 21:33 UTC, hub-cap requested changes
Hey, awesome work. The only thing change is to remove the abstract from `getFieldName`, and just have the default AcknowledgeResponse impl of this method be "acknowledged", since thats the generic case that other APIs can and will use as well. 

I think it might be worth also moving the parser in. You can feel free to shoot this down, but i basically did the following to a sample response i had sitting in my current branch. Mind you, the tests started failing cuz i changed the parse field name, just to make sure it was working :)

```
public class DeleteRollupJobResponse extends AcknowledgedResponse {
    private static final String PARSE_FIELD_NAME = "some_other_ack";

    private static final ConstructingObjectParser<DeleteRollupJobResponse, Void> PARSER =
        AcknowledgedResponse.generateParser("delete_rollup_job_response", DeleteRollupJobResponse::new, PARSE_FIELD_NAME);

    public DeleteRollupJobResponse(boolean acknowledged) {
        super(acknowledged);
    }

    public static DeleteRollupJobResponse fromXContent(final XContentParser parser) throws IOException {
        return PARSER.parse(parser, null);
    }

    @Override
    String getFieldName() {
        return PARSE_FIELD_NAME;
    }
}
```

and added the following to AcknowledgedResponse
```
public static <T> ConstructingObjectParser generateParser(String name, Function<Boolean, T> ctor, String parseField) {
        ConstructingObjectParser p = new ConstructingObjectParser<>(name, true, args -> ctor.apply((boolean) args[0]));
        p.declareBoolean(constructorArg(), new ParseField(parseField));
        return p;
    }
```

2018-10-26 09:51 UTC, cbuescher commented
@hub-cap I think I got what you mean. Please take a look at the last commit if thats the change you intended.

2018-10-26 19:00 UTC, hub-cap approved these changes
yea this is real nice now.

2018-10-29 08:28 UTC, merged