NETWORKING: Add SSL Handler before other Handlers
elastic/elasticsearch pull request #34636
Opened 2018-10-19 13:02 UTC by original-brownbear

* The only way to run into the issue in #33998 is for `Netty4MessageChannelHandler`
to be in the pipeline while the SslHandler is not. Adding the SslHandler before any
other handlers should ensure correct ordering here even when we handle upstream events
in our own thread pool
* Relates #33998

2018-10-19 13:02 UTC, elasticmachine commented
Pinging @elastic/es-security

2018-10-19 13:02 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-10-23 00:00 UTC, Tim-Brooks requested changes
Thanks for picking this up. I missed the original issue.

I'm suspicious that this does not solve the issue. `initChannel` should not be called concurrently with the channel being read from. Additionally, `SslHandler` is necessary to have received a message from a channel. We need to handshake + decode in order to successfully get to the `TcpTransport`.

I suspect the actual issue is that the channel is being closed concurrently with a request being handled. When a channel is closed, netty removes the handlers. 

`DefaultChannelPipeline`

```
    private void destroyUp(AbstractChannelHandlerContext ctx, boolean inEventLoop) {
        final Thread currentThread = Thread.currentThread();
        final AbstractChannelHandlerContext tail = this.tail;
        for (;;) {
            if (ctx == tail) {
                destroyDown(currentThread, tail.prev, inEventLoop);
                break;
            }

            final EventExecutor executor = ctx.executor();
            if (!inEventLoop && !executor.inEventLoop(currentThread)) {
                final AbstractChannelHandlerContext finalCtx = ctx;
                executor.execute(new Runnable() {
                    @Override
                    public void run() {
                        destroyUp(finalCtx, true);
                    }
                });
                break;
            }

            ctx = ctx.next;
            inEventLoop = false;
        }
    }
```

I think what we need to do is check whether the channel is closed when the `SslHandler` is null. If the channel is open, then throw the assertion error. That is not excepted. Otherwise maybe throw some type of normal exception to indicate that the request cannot be processed? I'll ping the @elastic/es-security team here to see what they think. What should we do if we cannot access the SSLEngine as the channel if closed already?

2018-10-23 03:49 UTC, original-brownbear commented
> `initChannel` should not be called concurrently with the channel being read from. Additionally, SslHandler is necessary to have received a message from a channel. We need to handshake + decode in order to successfully get to the TcpTransport.

I think the issue isn't that the handler isn't there but rather that there may be a concurrency issue in the lookup of the handler (the thread failing the assertion in the report is not a Netty eventloop thread, see the thread model wiki page I linked where a race condition in this code is mentioned).

> I think what we need to do is check whether the channel is closed when the SslHandler is null. If the channel is open, then throw the assertion error. That is not excepted. Otherwise maybe throw some type of normal exception to indicate that the request cannot be processed?

Yea, this seems like a good idea! We are currently just checking if the channel is open before the we go into the method failing the assertion but since we're not in a Netty thread here we probably have the same concurrency issue here as well. I'd just throw an `io.netty.channel.ChannelException` in this case.
That said, when debugging this I actually tried if I could reproduce this by closing the channel concurrently (tried from within the Eventloop as well as from just our threadpool ... the `SslHandler` could still be looked up after a few seconds but maybe if the connection is closed from a broken pipe concurrently it's deregistered immediately?).
Either way, can't hurt to rule this out as well so I added https://github.com/elastic/elasticsearch/pull/34636/commits/b92fe67d88812a63b8dab639143c6863af16dbc1 :)

2018-10-23 15:41 UTC, jaymode commented
> Otherwise maybe throw some type of normal exception to indicate that the request cannot be processed?

+1

> see the thread model wiki page I linked where a race condition in this code is mentioned

I've looked at this before and I've always thought this described the Netty 3.x thread model and its issues that they wanted to fix in 4.0. The history of that page shows most of it was written 5 years ago and recent changes are very minor wording fixes, https://github.com/netty/netty/wiki/Thread-model/_history. I'm not sure we should base things off of this unless we can confirm that these issues still apply.

2018-10-23 16:03 UTC, tbrooks8 commented
> I've looked at this before and I've always thought this described the Netty 3.x thread model and its issues that they wanted to fix in 4.0. 

This is referencing 3.x. All inbound and outbound events happen on the same thread now. 

> I think the issue isn't that the handler isn't there but rather that there may be a concurrency issue in the lookup of the handler

I'm open to some complicated concurrency issue. But looking up a handler only touches `final` or `volatile` fields. If we agree that the handler is there (in order to have completed a handshake), we should be able to access it.

Anyway, I'm good with both changes to be safe. If Jay is okay with the `ChannelException` as the notification mechanism. And one comment that I just added.

2018-10-23 16:04 UTC, tbrooks8 commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/transport/netty4/SecurityNetty4Transport.java
> +            super.initChannel(ch);
Can you add an assertion post `super` call that the ssl handler is still first? That way a future change does not accidentally mess up necessary ordering on handlers.

2018-10-23 16:16 UTC, jaymode commented
> If Jay is okay with the ChannelException as the notification mechanism.

I am good with it

2018-10-25 02:56 UTC, Tim-Brooks approved these changes
LGTM

2018-10-25 05:50 UTC, original-brownbear commented
@tbrooks8 thanks!

2018-10-25 05:51 UTC, merged