Supplementary explanation for code snippets line width
elastic/elasticsearch pull request #34796
Opened 2018-10-24 08:42 UTC by wangzhenhui1992

Add "Line width for code snippets is 76 characters" to  Java Language Formatting Guidelines

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

For issue #34795

2018-10-24 10:44 UTC, cbuescher requested changes
Hi @wangzhenhui1992,

thanks for opening the issue and this PR. I agree it would be helpful to document the line length restrictions for code snippets somewhere. I think doing this here in CONTRIBUTING.md is a good start, but I want to suggest adding a little bit of context since the 76 character limit is only necessary for code snippets that are included in the documentation (the ones surrounded by `// tag` and `// end` comments). While this might be clear to somebody who has already written these code snippets, it might be confusing to people just working in the regular code base. I would suggest adding a short additional sentence for clarification, without going to much into detail.

2018-10-24 11:00 UTC, wangzhenhui1992 commented
@cbuescher 
Thank you for your advice and of course it is better.

2018-10-25 00:33 UTC, wangzhenhui1992 commented
@cbuescher I have added the additional sentence and review please.

2018-10-25 08:53 UTC, cbuescher approved these changes
Thanks @wangzhenhui1992, this looks good to me now. I will merge to master and the latest release branch.

2018-10-25 08:55 UTC, merged