[Docs] Add nmigration note about expanded fields limit
elastic/elasticsearch pull request #34920
Opened 2018-10-26 16:33 UTC by cbuescher

Adds a note to warn users about the limit introduced in #26541.

2018-10-26 16:33 UTC, elasticmachine commented
Pinging @elastic/es-search-aggs

2018-10-26 16:38 UTC, jimczi requested changes
Thanks @cbuescher . I left some comments

2018-10-26 16:38 UTC, jimczi commented on docs/reference/migration/migrate_7_0/search.asciidoc
> +for queries using the "all fields" mode ("default_field": "*").
It is applied to any expansion so not only `*` but also `a*` or `a,b,c,d*`

2018-10-26 16:38 UTC, jimczi commented on docs/reference/migration/migrate_7_0/search.asciidoc
> +To safeguard against this, a fixed limit of a maximum of 1024 fields has been introduced
`an hard limit of 1024 fields` ?

2018-10-29 08:37 UTC, cbuescher commented
@jimczi I updated the text according to your comments. Would you be able to take another look?

2018-10-29 08:48 UTC, jimczi approved these changes
Thanks for updating @cbuescher !

2018-10-29 09:23 UTC, merged