Add a prebuilt ICU Analyzer
elastic/elasticsearch pull request #34958
Opened 2018-10-29 10:55 UTC by romseygeek

The ICU plugin provides the building blocks of an analysis chain, but doesn't actually have a prebuilt analyzer.  It would be a better for users if there was a simple analyzer that they could use out of the box, and also something we can point to from the CJK Analyzer docs as a superior alternative.

Relates to #34285

2018-10-29 10:55 UTC, elasticmachine commented
Pinging @elastic/es-search-aggs

2018-10-30 16:13 UTC, nik9000 requested changes
I left a small thing about the default, otherwise I like the idea a lot!

2018-10-30 16:13 UTC, nik9000 commented on docs/reference/analysis/analyzers/lang-analyzer.asciidoc
> +for CJK text than the `cjk` analyzer.
Maybe add something like "experiment with your text and queries" or something like that.

2018-10-30 16:13 UTC, nik9000 commented on plugins/analysis-icu/src/main/java/org/elasticsearch/index/analysis/IcuAnalyzerProvider.java
> +            mode = "compose";
I'd prefer to throw an exception if they pass a string that isn't one of the options.

2018-10-30 16:13 UTC, nik9000 commented on plugins/analysis-icu/src/main/java/org/elasticsearch/index/analysis/IcuAnalyzerProvider.java
> +            mode = "compose";
And just default to `compose` if they don't pass anything.

2018-11-02 15:30 UTC, nik9000 approved these changes
LGTM

2018-11-14 10:02 UTC, romseygeek commented
@elasticmachine run docs test please

2018-11-19 09:08 UTC, romseygeek commented
@elasticmachine test this please

2018-11-21 09:00 UTC, merged