backport 936faba6c43 to 6.x
elastic/elasticsearch pull request #35045
Opened 2018-10-29 15:41 UTC by pcsanwald

This PR backports delete job from `master` to `6.x` branch.

2018-10-29 15:41 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-10-29 22:09 UTC, cbuescher requested changes
I left a few minor comments, looks good otherwise.

2018-10-29 22:09 UTC, cbuescher commented on docs/java-rest/high-level/supported-apis.asciidoc
> +:doc-tests-file: {doc-tests}/RollupDocumentationIT.java
duplication from line 299/300

2018-10-30 18:39 UTC, pcsanwald commented
@cbuescher no rush, but I believe I have addressed your comments and this is ready for re-review. thank you!

2018-10-30 21:29 UTC, cbuescher approved these changes
Many thanks, LGTM.

2018-10-31 12:00 UTC, merged