Move to Error step if ClusterState* steps throw
elastic/elasticsearch pull request #35069
Opened 2018-10-29 23:32 UTC by gwbrown

Previously, if ClusterStateActionSteps or ClusterStateWaitSteps threw an
exception executing, the exception would only be caught and logged by
the generic ClusterStateUpdateTask machinery and the index would become
stuck on that step.

Now, exceptions thrown in these steps will be caught and the index will
be moved to the Error step.

Credit to @talevy for the test cases, turns out we both worked on this separately and he got to them first.

2018-10-29 23:32 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-10-29 23:48 UTC, talevy approved these changes
left some comments I think should be addressed

2018-10-29 23:48 UTC, talevy commented on x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java
> +    private ClusterState moveToErrorStep(final ClusterState state, Step.StepKey currentStepKey, Exception cause) throws IOException {
this should probably be RuntimeException here?

2018-10-29 23:48 UTC, talevy commented on x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTaskTests.java
> +    }
nit: newline

2018-10-30 02:27 UTC, dakrone requested changes
I left a question

2018-10-30 15:51 UTC, gwbrown commented on x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java
> +                    } catch (RuntimeException exception) {
This was left over from an earlier draft of this that had more in the `try` block, and I wasn't sure if we wanted to include `IOException` in this catch. I've changed it.

2018-10-30 16:36 UTC, dakrone approved these changes

2018-10-30 19:33 UTC, merged