Make XContentBuilder in AliasActions build `is_write_index` field
elastic/elasticsearch pull request #35071
Opened 2018-10-30 05:35 UTC by upgle

Alias 'is_write_index' feature was introduced in 6.4 version. but, toXContent method of AliasActions does not build for `is_write_index` field.

so `is_write_index` can not be set with RestHighLevelClient

You can see it in the code below.

https://github.com/elastic/elasticsearch/blob/237650e9c054149fd08213b38a81a3666c1868e5/server/src/main/java/org/elasticsearch/action/admin/indices/alias/IndicesAliasesRequest.java#L448

## Sample of RestHighLevelClient

It does not set `is_write_index` despite specifying options with `writeIndex` chaining method.

```java
IndicesAliasesRequest request = new IndicesAliasesRequest();
IndicesAliasesRequest.AliasActions aliasAction =
        new IndicesAliasesRequest.AliasActions(IndicesAliasesRequest.AliasActions.Type.ADD)
                .index(index)
                .alias(alias)
                .filter(filter)
                .writeIndex(isWriteIndex); // this chaining method does not working.

request.addAliasAction(aliasAction);
return client.indices().updateAliases(request, RequestOptions.DEFAULT);
```

2018-10-30 09:55 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-10-30 16:56 UTC, talevy requested changes
thank you @upgle for contributing this fix and bringing it to our attention!

Rest High Level Client was missed here.

Your changes look good, but I think they are missing three things

- the IndicesClientIT changes would benefit from randomization
- The IndicesAliasesRequest's hashCode/toString/equals are also missing writeIndex
- Add test on the server-side for IndicesAliasesRequestTests, where toXContent is tested. This means updating RandomAliasActionsGenerator.java to randomly include writeIndex.

I've addressed these concerns in a commit to make it clearer: https://github.com/talevy/elasticsearch/commit/b72608d8ca24836dbcbbe6f1dcd2e0c5f86dbce8

thanks!

2018-10-30 17:39 UTC, upgle commented
Hi  @talevy, Thank you for your kind comments.
I've modified this PR with reference to the code you shared. Can I get a review again, please?

2018-10-30 17:55 UTC, talevy commented
thank you for for the update, I will run our continuous integration test suite against this to double check we didn't miss anything

test this please

2018-10-30 17:56 UTC, talevy commented
@elasticmachine, test this please

2018-10-31 01:46 UTC, upgle commented
@talevy 
Build is failed here https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/1418/
I found version confilict engine exceptoin.. so I rebased it on top of master.

> [2018-10-30T19:30:22,495][DEBUG][o.e.a.g.TransportGetAction] [node-3] null: failed to execute [get [test_1][test][1]: routing [null]]
org.elasticsearch.transport.RemoteTransportException: [node-1][127.0.0.1:40018][indices:data/read/get[s]]
Caused by: org.elasticsearch.index.engine.VersionConflictEngineException: [test][1]: version conflict, current version [2] is different than the one provided [1]
	at org.elasticsearch.index.engine.Engine.getFromSearcher(Engine.java:618) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.engine.InternalEngine.get(InternalEngine.java:659) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]

2018-10-31 01:47 UTC, upgle commented
@elasticmachine, test this please

2018-10-31 02:15 UTC, upgle commented
@talevy 
**P.S.**
And also found.. MixedClusterClientYamlTestSuiteIT.test failures

```
Tests with failures:
  - org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/10_source_filtering/_source_include}
  - org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/10_source_filtering/_source include and _source in body}
  - org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=get_source/70_source_filtering/Source filtering}
  - org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=get/71_source_filtering_with_types/Source filtering}
  - org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=explain/20_source_filtering/Source filtering}
```

I think we need to try integration test again. This seems to be caused by this issue. https://github.com/elastic/elasticsearch/commit/6256c330c0d4c5610ab8a41d7fceea8fec003dfe

2018-10-31 03:49 UTC, talevy commented
thanks for applying the rebase. I will rerun the tests

2018-10-31 03:49 UTC, talevy commented
@elasticmachine, test this please

2018-10-31 07:36 UTC, upgle commented
Hi @talevy, test is just passed 🎉

2018-10-31 21:12 UTC, talevy approved these changes
thank you @upgle! I'll go ahead and merge this into the appropriate branches

2018-10-31 21:15 UTC, merged