[HLRC] Add GetRollupIndexCaps API
elastic/elasticsearch pull request #35102
Opened 2018-10-30 17:45 UTC by polyfractal

Nearly identical to the GetRollupCaps API since the response is basically the same format, just different content.  The request object is slightly different too since it accepts a list of indices/index patterns and IndicesOptions

Also refactors the caps response tests a bit to share the same abstract class to reduce duplication of test code

Related to https://github.com/elastic/elasticsearch/issues/29827

2018-11-02 18:11 UTC, hub-cap requested changes
Looks good generally. Ill inspect it a bit more once youve modified the tests so they use the `org.elasticsearch.test.AbstractXContentTestCase.xContentTester`

2018-11-02 18:11 UTC, hub-cap commented on client/rest-high-level/src/main/java/org/elasticsearch/client/rollup/GetRollupIndexCapsResponse.java
> +public class GetRollupIndexCapsResponse implements ToXContentObject {
Generally speaking these responses shouldnt be `ToXContent` classes. I assume this is for a test case below. We have some newer HLRC's that have a diff test, see TermVectorsResponseTests. It looks like you picked the short straw that came after we modified the tests, sorry :)

2018-11-12 17:50 UTC, hub-cap commented on client/rest-high-level/src/main/java/org/elasticsearch/client/rollup/GetRollupIndexCapsResponse.java
> +public class GetRollupIndexCapsResponse implements ToXContentObject {
no, we are just changing things quickly on the client :)

2018-11-12 18:14 UTC, hub-cap approved these changes
great work updating the test. sorry it took a while to update.

2018-11-12 20:04 UTC, polyfractal commented
Thanks @hub-cap! <3

2018-11-12 20:05 UTC, merged