[Docs] Add painless context details for bucket_script
elastic/elasticsearch pull request #35142
Opened 2018-10-31 18:12 UTC by polyfractal

Fleshes out the details of the `bucket_script` context, adds an example and corresponding doc test.  I decided not to add a test to `ContextExampleTests` because the script is trivial, and we can test it through the usual doc testing mechanism.

Related to #34829

2018-10-31 18:12 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-11-01 15:29 UTC, jdconrad reviewed
@polyfractal Thank you for this! This looks good from the side to me.  I would like @debadair or another writer to take a look for the docs side.

2018-11-01 23:46 UTC, debadair requested changes
Suggested some minor edits.

2018-11-01 23:46 UTC, debadair commented on docs/painless/painless-contexts.asciidoc
>                                      | {ref}/search-aggregations-pipeline-bucket-script-aggregation.html[Elasticsearch Documentation]
I would lowercase script. In general, we don't use init caps in names of things

2018-11-01 23:46 UTC, debadair commented on docs/painless/painless-contexts/painless-bucket-script-agg-context.asciidoc
> +
In general, I recommend avoiding the use of "we" or "our". In this case, I'd just say:

This example takes the values from a `min` and `max` aggregation, calculates the difference, and adds the user-specified `base_cost` to the result.

2018-11-01 23:46 UTC, debadair commented on docs/painless/painless-contexts/painless-bucket-script-agg-context.asciidoc
> +
I'd pare this first sentence down to: 

Note that the values are extracted from the `params` map.

2018-11-01 23:46 UTC, debadair commented on docs/painless/painless-contexts/painless-bucket-script-agg-context.asciidoc
> +`params` variable for use in the script.
I think we generally (but likely not consistently) init-cap callouts whether or not they are complete sentences.

In <2>, I'd refer to it as the `params` map for consistency. I think I'd also drop "for use in the script".

2018-11-02 15:43 UTC, polyfractal commented
Thanks @debadair.  Pushed some tweaks per your suggestions :)

2018-11-02 22:45 UTC, debadair approved these changes

2018-11-06 17:18 UTC, merged