Run code snippets in ReindexDocumentationIT
elastic/elasticsearch pull request #35165
Opened 2018-11-01 15:47 UTC by vladimirdolzhenko

Actually `ReindexDocumentationIT` has documentation code snippets but it does not run as no `test*`-methods there.

This PR enforces to run ReindexDocumentationIT code examples.

Closes #32093

2018-11-01 15:47 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-11-02 01:16 UTC, cbuescher approved these changes
Thanks for picking up that issue, I left a small comment but rest LGTM.

2018-11-02 01:25 UTC, cbuescher requested changes
Hm, the current CI failure seems to indicate that there might be problems with the testTask indexing. I didn't run into those when running the test locally with several repetitions though, can you check whats going on there?

2018-11-02 07:36 UTC, vladimirdolzhenko commented on modules/reindex/src/test/java/org/elasticsearch/client/documentation/ReindexDocumentationIT.java
> +        client.admin().indices().preparePutMapping(INDEX_NAME).setType("type").setSource("cat", "type=keyword").get();
thanks for pointing to this 👍

2018-11-02 10:03 UTC, vladimirdolzhenko commented
@cbismuth I guess you try to run it locally from IDE while it is quite reproducible locally with gradle.

TIL: if you want to use custom node plugins in integration test (I had to use to interfere into task execution process) you have to ignore to be run on external cluster (gradle does by default)
```
@Override
protected boolean ignoreExternalCluster() {
    return true;
}
```

otherwise `nodePlugins()` are completely ignored

2018-11-02 12:44 UTC, cbuescher approved these changes
Thanks for the explanation about the earlier CI problem. LGTM.

2018-11-02 12:52 UTC, merged