[Docs] Add painless context details for bucket_selector
elastic/elasticsearch pull request #35162
Opened 2018-11-01 15:02 UTC by polyfractal

Adds docs for `bucket_selector` context, including example and corresponding doc test

Similar to the `bucket_script` PR, I opted to only test this through the doc testing mechanism since the script itself is trivial.

Related to #34829

2018-11-01 15:02 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-11-01 15:29 UTC, jdconrad reviewed
@polyfractal Same as the bucket_script. Firstly, thank you! This looks good from the side to me.  I would like @debadair or another writer to take a look for the docs side.

2018-11-01 23:54 UTC, debadair requested changes
Suggested some minor edits.

2018-11-01 23:54 UTC, debadair commented on docs/painless/painless-contexts.asciidoc
> +                                    | {ref}/search-aggregations-pipeline-bucket-selector-aggregation.html[Elasticsearch Documentation]
Again, I'd lowercase "selector"

2018-11-01 23:54 UTC, debadair commented on docs/painless/painless-contexts/painless-bucket-selector-agg-context.asciidoc
> +
Same as for bucket script:

This example finds the `max` of each bucket, adds a user-specified base_cost, and retains all of the buckets that are greater than `10`.

2018-11-01 23:54 UTC, debadair commented on docs/painless/painless-contexts/painless-bucket-selector-agg-context.asciidoc
> +
I'm not a fan of using slashes to show options, I'd probably just use or,  `true` or `false`.

2018-11-01 23:54 UTC, debadair commented on docs/painless/painless-contexts/painless-bucket-selector-agg-context.asciidoc
> +
Same as for bucket script:

Note that the values are extracted from the params map. The script is in the form of an expression that returns `true` or `false`.

2018-11-01 23:54 UTC, debadair commented on docs/painless/painless-contexts/painless-bucket-selector-agg-context.asciidoc
> +`params` variable for use in the script.
Same as for buckets script--I'd init cap, consistently use `params` map, and drop "for use in the script".

2018-11-02 15:48 UTC, polyfractal commented
Tidied up, and also re-arranged sentence order in one place.  :)

2018-11-02 22:46 UTC, debadair approved these changes

2018-11-07 20:02 UTC, polyfractal commented
Jenkins, test this please.

2018-11-08 16:02 UTC, merged