Remove build qualifier from server's Version
elastic/elasticsearch pull request #35172
Opened 2018-11-01 17:10 UTC by atorok

Build on #35155 ( and contains commits from )

- Rename the constant with an automated IDE refactoring - this generates a high number of changes and changed files. 
- Pass only the numeric part of the version in places like plugin properties so the server doesn't have to deal with qualifier and snapshot. 
- adds a new substitution to doc tests as the docs now need to know about both.

2018-11-01 17:10 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-11-05 20:27 UTC, nik9000 requested changes
OK! I left a few small things. I like `Build.getVersion()` - though maybe not the name? Maybe `Build.getQualifiedVersion` or something. And it should have javadoc. Because we already have `Version` and it isn't the same thing.

2018-11-06 10:35 UTC, atorok commented
Thanks for your review @nik9000 . I made changes as suggested.

2018-11-06 15:32 UTC, nik9000 approved these changes
I left a few super minor things but this LGTM. Good luck on the backport!

2018-11-06 15:32 UTC, nik9000 commented on qa/wildfly/src/test/java/org/elasticsearch/wildfly/WildflyIT.java
> +                System.getProperty("tests.jboss.home")
I think "home" means something else in this context. Maybe `test.wildfly.root`?

2018-11-06 15:32 UTC, nik9000 commented on server/src/main/java/org/elasticsearch/Build.java
> +    public String getQualifiedVersion() {
Could you add javadoc to this?

2018-11-06 15:32 UTC, nik9000 commented on server/src/main/java/org/elasticsearch/Build.java
> +    public boolean isProductionRelease() {
This too?

2018-11-06 15:32 UTC, nik9000 commented on server/src/main/java/org/elasticsearch/bootstrap/Elasticsearch.java
> +                Build.CURRENT.getQualifiedVersion(),
I think the indentation on this one is off.

2018-11-06 15:32 UTC, nik9000 commented on server/src/main/java/org/elasticsearch/node/Node.java
> +        if (build.isProductionRelease() == false) {
I think maybe this isn't worth being its own method any more. Now that we're testing `isProductionRelease` instead.

2018-11-07 05:36 UTC, atorok commented
@nik9000 this is not planned to be back-ported. I have done so with the work leading up here, but don't plan to do it with this one. Do you think we should ?

2018-11-07 12:01 UTC, merged

2018-11-07 12:32 UTC, atorok commented
After looking more into it, it seems that it was a deliberate decision not to have `-SNAPSHOT` in `version.number` so we'll probably want to stick to that.

2018-11-23 14:58 UTC, atorok commented
@javanna that was done on purpose. Qualified builds will be tagged as such as needed.