Add doc section about range query for range type
elastic/elasticsearch pull request #35222
Opened 2018-11-02 21:02 UTC by gskema

I didn't know about this mapping type until I saw it in an ES presentation. It's only described in the Mapping section. It should also be referenced in the Range Query documentation.

2018-11-05 12:28 UTC, elasticmachine commented
Pinging @elastic/es-search-aggs

2018-11-05 21:27 UTC, nik9000 requested changes
I think this is a great addition! I left some wording suggestions because when I didn't understand at first. I'm not 100% convinced they are better. What do you think?

2018-11-05 22:13 UTC, gskema commented
Hi @nik9000, I included your proposed changes. I also changed "This is the default value **when querying range fields**." for clarification.

2018-11-05 22:21 UTC, nik9000 approved these changes
I like it!

2018-11-05 22:32 UTC, gskema commented
@nik9000 np! This is a doc fix so there's no hurry. I just hope it's ok that this PR is not against master?

2018-11-05 23:50 UTC, nik9000 commented
Our policy is to develop against master but docs fixes end up coming from
other branches because folks clikc the edit button. I'm quite happy to
merge it and drag it forward so long as it targets a modern branch. I
suspect others are more strict.

On Mon, Nov 5, 2018, 17:32 Gytis Šk. <notifications@github.com wrote:

> @nik9000 <https://github.com/nik9000> np! This is a doc fix so there's no
> hurry. I just hope it's ok that this PR is not against master?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elastic/elasticsearch/pull/35222#issuecomment-436060545>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AANLok_vSW-5xtbcewh7w1YKBF20Jy9xks5usLyAgaJpZM4YMXlx>
> .
>

2018-11-06 15:45 UTC, merged

2018-11-06 15:49 UTC, nik9000 commented
I've merged and forward ported. Thanks @gskema!