[ILM] fix retry so it picks up latest policy and executes async action
elastic/elasticsearch pull request #35406
Opened 2018-11-09 06:51 UTC by talevy

Before, moving to a failed step would only change the step info
to be that of the failed step. This means two things.

1. Async Steps would never be triggered to execute
2. If there are inherent problems with the action definition that can
be fixed with a policy update, these changes were not being reflected
by the new execution info.

Changes now

1. Async steps are executed after the move to the failed step in cluster state
2. the lifecycle execution info's phase definition is updated from the current
latest policy definition, even though the index isn't moving to a new phase.

Closes #35397.

2018-11-09 06:51 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-11-09 06:54 UTC, talevy commented
I attempted to solve #35397 with minimal changes, but I'm not too happy about leaking ErrorStep specific things within the policyDefinition update code. I'd like to think about this a little bit more.

thought it would be good to put this up here sooner to see what others think

2018-11-09 09:29 UTC, colings86 requested changes

2018-11-09 09:29 UTC, colings86 commented on x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java
> +        if (currentStep.getPhase().equals(nextStep.getPhase()) == false || ErrorStep.NAME.equals(currentStep.getName())) {
I'm not sure this is the right pace to do this. We only want this functionality to occur in the retry API so I think it should only be that code path that gets this phase definition refresh. Maybe we can have a `boolean forcePhaseDefinitionRefresh` parameter and use that to override the behaviour for the retry method. I can also see a case in the future where we might want to have an option on the moveToStep API to force the phase definition to be updated too.

2018-11-09 22:56 UTC, gwbrown commented on x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/action/TransportRetryAction.java
> +                        logger.error("TRYING TRYING");
I think this log statement got left in accidentally.

2018-11-09 23:48 UTC, talevy commented
refreshed to leverage the flag since we concluded this was a reasonable approach.

2018-11-12 11:01 UTC, colings86 approved these changes
LGTM once the build passes

2018-11-12 19:33 UTC, merged