Avoid misplacing positions in unique filter
elastic/elasticsearch pull request #35420
Opened 2018-11-09 18:06 UTC by shuaibiyy

Fixes elasticsearch/elastic#35411

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2018-11-09 20:06 UTC, elasticmachine commented
Pinging @elastic/es-search-aggs

2018-11-09 20:10 UTC, romseygeek requested changes
Hi @shuaibiyy, thank you very much for the PR!  There's already a base class in lucene called `FilteringTokenStream` that will handle most of the logic here, so I think a better solution would be to make UniqueTokenStream extend FilteringTokenStream and move the checking logic into its `accept()` method.  Would you be able to try that?

2018-11-09 20:10 UTC, romseygeek commented on modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/UniqueTokenFilter.java
> +            skippedIncrement = posIncrement;
This isn't quite right, because we need to take into account multiple skipped tokens.

2018-11-09 20:10 UTC, romseygeek commented on modules/analysis-common/src/test/java/org/elasticsearch/analysis/common/UniqueTokenFilterTests.java
> +                new String[]{"f", "fo", "b", "ba", "br"},
Could we also include multiple skipped tokens in here?  e.g. test for "foo bar bro bar bro baz"

2018-11-09 21:15 UTC, shuaibiyy commented
Thanks for the review @romseygeek I'll work on the requested changes.

2018-11-12 12:17 UTC, shuaibiyy commented
Hi @romseygeek I've made the changes.

2018-11-13 09:18 UTC, romseygeek requested changes
Looks good, I just have two minor changes to request.

2018-11-13 09:18 UTC, romseygeek commented on modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/UniqueTokenFilter.java
> +        return !duplicate;
Can you write this as `duplicate == false`?  We prefer this style as it's easy to miss prefixed `!` characters.

2018-11-13 09:18 UTC, romseygeek commented on modules/analysis-common/src/test/java/org/elasticsearch/analysis/common/UniqueTokenFilterTests.java
> +import org.apache.lucene.analysis.*;
We prefer not to use `*` imports

2018-11-13 09:31 UTC, shuaibiyy commented
@romseygeek Updated :)

2018-11-13 09:41 UTC, romseygeek commented
@elasticmachine test this please

2018-11-13 20:37 UTC, romseygeek approved these changes

2018-11-14 10:22 UTC, romseygeek commented
Hi @shuaibiyy, I've realised that we're going to need to take into account backwards compatibility here so that already existing indexes don't suddenly start returning different results.  I think what we need to do is to keep the work you've done here, but add back in a class that retains the old behaviour.  Then in `UniqueTokenFilterFactory`, we check the settings to find when the index was created; if it's a pre-6.6 index, then return the old class, if it's 6.6 or later then return the new one.

2018-11-14 10:23 UTC, romseygeek requested changes
Holding off for backwards compatibility changes

2018-11-14 22:07 UTC, shuaibiyy commented
Hi @romseygeek May I take a shot at it? If yes, can you recall some other filter or something that has this sort of behavior off the top of your head?

2018-11-16 11:41 UTC, romseygeek commented
Hi @shuaibiyy , please do!  I'm doing similar sort of things (changing the behaviour of a TokenFilterFactory based on the index creation version) in #34331, which should give you some hints.

2018-12-03 08:43 UTC, romseygeek commented
Hi @shuaibiyy are you still interested in working on this one?

2018-12-03 20:57 UTC, shuaibiyy commented
Hi @romseygeek Yes I am. However, I've been on vacation and will resume next week. If there's a need to move it along faster, please feel free to do so :)

2018-12-31 22:37 UTC, shuaibiyy commented
Hi @romseygeek is there a way to run version 6.x from source?

2019-01-02 09:48 UTC, romseygeek commented
> is there a way to run version 6.x from source?

You can run `./gradlew run` from the root of the source tree

2019-01-15 17:33 UTC, shuaibiyy commented
Hi @romseygeek , I've updated the PR.

2019-01-15 18:06 UTC, romseygeek commented
@elasticmachine ok to test

2019-01-15 18:10 UTC, romseygeek commented on modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/UniqueTokenFilterFactory.java
> +        if (indexSettings.getIndexVersionCreated().onOrAfter(Version.V_6_6_0) == false) {
Can you make this 7.0.0?

2019-01-15 18:18 UTC, romseygeek commented
Hi @shuaibiyy , could you merge in the latest version of master and then push again?

2019-01-16 11:12 UTC, shuaibiyy commented on modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/UniqueTokenFilterFactory.java
> +        if (indexSettings.getIndexVersionCreated().onOrAfter(Version.V_6_6_0) == false) {
Done

2019-01-16 11:14 UTC, shuaibiyy commented
@romseygeek updated

2019-03-04 11:09 UTC, romseygeek commented
Hi @shuaibiyy, sorry for the radio silence.  This all looks great, can I ask that you add one more test to check that different index creation versions do indeed result in the different filters being used?  `SynonymsAnalysisTests#testDisallowedTokenFilters` has some examples of testing things using different versions.

2019-04-03 08:32 UTC, romseygeek commented
Hi @shuaibiyy do you still have time to work on this?  If not I can take it over and finish.

2019-04-03 18:59 UTC, shuaibiyy commented
Hi @romseygeek , I hadn't noticed your earlier message. Please feel to take over and finish. Thank you very much!

2020-02-07 10:30 UTC, cbuescher commented
@romseygeek just discovered this, I can update and add the missing tests to this PR...

2020-02-07 15:05 UTC, cbuescher commented
@elasticmachine run elasticsearch-ci/1

2020-02-07 15:05 UTC, cbuescher commented
@elasticmachine run elasticsearch-ci/bwc

2020-02-07 16:37 UTC, cbuescher commented
@elasticmachine update branch

2024-06-05 14:50 UTC, elasticsearchmachine commented
Pinging @elastic/es-search (Team:Search)

2024-06-05 16:57 UTC, closed without merging

2024-06-05 16:57 UTC, benwtrent commented
closing in deference to: https://github.com/elastic/elasticsearch/pull/109395

Commit history remains.