Improve documentation for --pass param to certutil
elastic/elasticsearch pull request #35432
Opened 2018-11-10 16:24 UTC by vikene

Better explaination for --pass parameter in documentation for elasticsearch-certutil.
Resolves: #35285

2018-11-11 23:13 UTC, elasticmachine commented
Pinging @elastic/es-security

2018-11-11 23:14 UTC, tvernum commented
@elasticmachine test this please

2018-11-26 06:56 UTC, tvernum requested changes
Hi @vikene, sorry it took so long to review this.

I think the way you've structured the information makes a lot of sense, but I've left some suggestions about the exact phrasing.

2018-11-26 06:56 UTC, tvernum commented on docs/reference/commands/certutil.asciidoc
> +prompt, use '--pass ""' (with no '=').
I like the way this has been structured, but I think we can tighten up the wording a bit.
What do you think of:
```
Keys stored in PKCS#12 format are always password protected, however,
this password may be _blank_. If you want to specify a blank password
without a prompt, pass `--pass ""` (with no `=`) on the command line.
```

2018-11-26 06:56 UTC, tvernum commented on docs/reference/commands/certutil.asciidoc
> +_blank_ as password.
_Suggestion_
```
`--pass` parameter, you are prompted for a password.
Encrypted PEM files do not support blank passwords (if you do not
wish to password-protected your PEM keys, then do not specify
`--pass`). 
```

2018-11-26 06:56 UTC, tvernum commented on docs/reference/commands/certutil.asciidoc
> +parameter.
I think this advice can be incorporated into the paragraph above it.

2018-12-17 02:49 UTC, tvernum commented
@vikene Do you think you'll have a chance to look at this again, or would prefer that we pick it up internally?

2018-12-19 06:06 UTC, vikene commented
@tvernum I am sorry missed those notification, sure. I will do those changes asap.

2019-03-27 03:15 UTC, tvernum commented
Closing in favour of #40137

2019-03-27 03:15 UTC, closed without merging