Prevent non-data nodes to start with dangling indices
elastic/elasticsearch pull request #35447
Opened 2018-11-12 12:04 UTC by vladimirdolzhenko

Non data node (like pure master or pure coordinator node) could behaves like a data node in terms of picking up dangling indices for other data nodes will automatically import them. 

This PR forbids non data nodes to start if any data shard folders in data path are found (`_state` metadata folder is not a case)

Closes #27073

2018-11-12 12:04 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-11-12 14:15 UTC, vladimirdolzhenko commented
@elasticmachine run gradle build tests

2018-11-13 08:21 UTC, ywelsch requested changes
I've left a few comments. Note that your check is never called on coordinating-only nodes.

2018-11-13 09:16 UTC, vladimirdolzhenko commented on server/src/main/java/org/elasticsearch/env/NodeEnvironment.java
> +                throw new IllegalStateException("Non data node cannot have dangling indices,"
addressed in 1478209

2018-11-13 09:17 UTC, vladimirdolzhenko commented on server/src/main/java/org/elasticsearch/env/NodeEnvironment.java
> +            checkDanglingIndices(settings);
addressed in 1478209

2018-11-13 09:17 UTC, vladimirdolzhenko commented on server/src/main/java/org/elasticsearch/env/NodeEnvironment.java
> +                                    if (MetaDataStateFormat.STATE_DIR_NAME.equals(path.getFileName().toString()) == false) {
addressed in 1478209

2018-11-13 09:17 UTC, vladimirdolzhenko commented on server/src/main/java/org/elasticsearch/env/NodeEnvironment.java
> +    private void checkDanglingIndices(Settings settings) throws IOException {
addressed in 1478209

2018-11-13 10:07 UTC, vladimirdolzhenko commented on server/src/test/java/org/elasticsearch/gateway/DanglingIndicesIT.java
> +        // replicating the case described in https://github.com/elastic/elasticsearch/issues/27073
I've extended at 47d1382 this test to make a clean up of unexpected directories (picking those up from error message) and start node again.

2018-11-13 13:30 UTC, vladimirdolzhenko commented
@elasticmachine run gradle build tests

2018-11-13 13:50 UTC, vladimirdolzhenko commented
@ywelsch I addressed your comments, could you pls have another look?

2018-11-13 20:01 UTC, vladimirdolzhenko commented
@elasticmachine run gradle build tests

2019-01-25 16:58 UTC, ywelsch commented
superseded by #37347 and #37748

2019-01-25 16:58 UTC, closed without merging