Geo: better handling of malformed geo_points
elastic/elasticsearch pull request #35554
Opened 2018-11-14 17:06 UTC by imotov

Improves handling of malformed geo_points when `ignore_malformed` is
set to true

Closes #35419

2018-11-14 17:06 UTC, elasticmachine commented
Pinging @elastic/es-search-aggs

2018-11-20 09:58 UTC, cbuescher requested changes
@imotov looks good to me except for a small issue I left a comment on.

2018-11-20 09:58 UTC, cbuescher commented on server/src/main/java/org/elasticsearch/index/mapper/GeoPointFieldMapper.java
> +            if (isNormalizable(point.lat()) && isNormalizable(point.lat())) {
should one of these be point.lon()?

2018-11-20 09:58 UTC, cbuescher commented on server/src/main/java/org/elasticsearch/index/mapper/GeoPointFieldMapper.java
> +            if (isNormalizable(point.lat()) && isNormalizable(point.lat())) {
If so, there should probably also be a test added that would have caught this.

2018-11-26 14:20 UTC, imotov commented
@cbuescher I pushed the changes that you have requested. Could you take another look?

2018-11-26 14:47 UTC, cbuescher approved these changes
Thanks for the change @imotov, LGTM

2018-11-26 19:44 UTC, merged