[Zen2] Fix test failures in diff-based publishing
elastic/elasticsearch pull request #35684
Opened 2018-11-19 06:34 UTC by DaveCTurner

`testIncompatibleDiffResendsFullState` sometimes makes a 2-node cluster and
then partitions one of the nodes from the leader, which makes the leader stand
down.  Then when the partition is removed the cluster re-forms but does so by
sending full cluster states, not diffs, causing the test to fail.

Additionally `testDiffBasedPublishing` sometimes fails if a publication is
delivered out-of-order, wiping out a fresher last-received cluster state with a
less-fresh one.  This change adds a freshness check to avoid this.

2018-11-19 06:34 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-11-19 11:33 UTC, ywelsch requested changes
I would like to avoid throwing a CoordinationStateRejectedException in PublicationTransportHandler. The validation logic should be left to CoordinationState. We can and should improve the logic on when to cache the incoming cluster state though, to avoid old cluster states from poisoning the cache. I wonder if the simplest way to do this would be to only store the new state in `lastSeenClusterState` after it passes the call to `handlePublishRequest.apply`. WDYT?

2018-11-21 16:06 UTC, DaveCTurner commented
> I wonder if the simplest way to do this would be to only store the new state in lastSeenClusterState after it passes the call to handlePublishRequest.apply. WDYT?

D'oh of course that makes much more sense. Somehow I missed that we were passing it to the coordinator here. I've done that instead.

2018-11-21 17:44 UTC, ywelsch approved these changes
LGTM

2018-11-22 09:08 UTC, merged