Fix "size" field in the body of AbstractBulkByScrollRequest
elastic/elasticsearch pull request #35742
Opened 2018-11-20 15:28 UTC by PnPie

The "size" field in the body of `AbstractBulkByScrollRequest(DeleteByQuery/UpdateByQuery)` is not taken into consideration anymore during some previous changes, and currently only passing "size" as parameter works for `DeleteByQuery` or `UpdateByQuery`. This is to fix it and make it worked again.

Close #35636

2018-11-20 17:19 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-11-27 17:30 UTC, nik9000 requested changes
I think this is *almost* right, but it has an issue for transport client users. I think. The trouble is that we didn't have any real testing of the default transport client behavior. But I'm fairly sure we should keep that default size setting. And that means changing Abstract rest controlled slightly. But I think this is on the right track!

2018-11-27 17:30 UTC, nik9000 commented on server/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByScrollRequest.java
> -            searchRequest.source().size(DEFAULT_SCROLL_SIZE);
I *think* this should stay as it was or else transport client users will start to get a default scroll size of `10` again which won't perform well..

2018-12-08 08:38 UTC, PnPie commented
Hi @nik9000 I changed [search XContent body parsing](https://github.com/elastic/elasticsearch/pull/35742/files#diff-373ad6c00a31d289415cc037657acb7bR1006) part and passed a setSize consumer inside to be able to "consume" `size` field in search request's body.
Otherwise it seems a little bit tricky on Abstract rest level to idenfity whether the `size` field has been set or not ([like this](https://github.com/elastic/elasticsearch/pull/35742/files#diff-de8f3e7c34ac2d22b99602b4b6cefd10R58)), as by default it's 1000.
What do you think of this ?

2019-07-03 16:21 UTC, henningandersen commented
@PnPie thanks for your efforts on providing this solution. Unfortunately, we have since implemented a different solution in #41894 where we renamed size to max_docs, fixing confusion on the different size parameters in place. I will therefore close this PR.

2019-07-03 16:21 UTC, closed without merging