[HLRC] Add support for get roles API
elastic/elasticsearch pull request #35787
Opened 2018-11-21 14:09 UTC by jkakavas

This commits adds support for the Get Roles API to the HLRC

Relates: #29827

2018-11-21 14:09 UTC, elasticmachine commented
Pinging @elastic/es-security

2018-11-22 06:02 UTC, jkakavas commented
Thanks for the feedback @bizybot

2018-11-23 00:08 UTC, albertzaharovits commented on client/rest-high-level/src/main/java/org/elasticsearch/client/SecurityClient.java
> +     * Retrieves roles in the native realm.
IMO s/native realm/native roles store/
(I know this comment uses the lingo from the docs)

2018-11-23 00:09 UTC, albertzaharovits commented on client/rest-high-level/src/main/java/org/elasticsearch/client/SecurityRequestConverters.java
> +
nit: extra line

2018-11-23 00:09 UTC, albertzaharovits commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/GetRolesRequest.java
> + * Request object to retrieve roles from the security index
IMO s/security index/native roles store

2018-11-23 00:34 UTC, albertzaharovits commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/GetRolesResponse.java
> +            roles.add(Role.PARSER.parse(parser, null));
I think we lose the role name here. The `Role` _should_ have a name.
For this, the `Role#fromXContent` could have a name parameter and be called here ; and not implement `ToXContentObject` (`PutRole` would build the XContent).

2018-11-23 00:41 UTC, albertzaharovits commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/user/privileges/Role.java
> +        PARSER.declareObject(optionalConstructorArg(), (parser, c) -> parser.map(), TRANSIENT_METADATA);
Is there a difference between `metadata` and `transient_metadata` ? If not I would make them both either `optionalConstructorArg` (cautious) or `constructorArg` (confident) :)

2018-11-23 00:52 UTC, albertzaharovits requested changes
I have recommended that the `Role` have a name despite the idiosyncratic Response making it hard.
From the client perspective, it's cumbersome to manipulate a list of roles, from the response, in the order of the role names that have been requested. I would argue that returning a `Collection` with `Role`s having a `name` as attribute follows closer the encapsulation precept.

2018-11-23 14:48 UTC, albertzaharovits approved these changes
LGTM
Only fished the nits of the nits. These are totally optional.

Thanks for tackling this before put role! 🎩

2018-11-23 14:48 UTC, albertzaharovits commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/user/privileges/Role.java
> +    private Role(@Nullable String name, @Nullable Collection<String> clusterPrivileges,
name is not `@Nullable`

2018-11-23 14:48 UTC, albertzaharovits commented on client/rest-high-level/src/main/java/org/elasticsearch/client/SecurityClient.java
> +     * Retrieves roles in the native realm.
Retrieves roles from the native roles store.

2018-11-23 14:48 UTC, albertzaharovits commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/user/privileges/Role.java
`"manage_token"` as well

2018-11-25 12:20 UTC, jkakavas commented
@elasticmachine run the gradle build tests 1

2018-11-26 07:32 UTC, jkakavas commented
```
23:41:29   1> [0030-11-25T14:41:24,539][ERROR][o.e.d.z.ZenDiscovery     ] [node_t0] unexpected exception while failing [master {node_t1}{BEVzq4gKQS64P6VHKriI8w}{zNOAkJu0SVKiSbw9ZL1Vfg}{127.0.0.1}{127.0.0.1:39245} committed version [3]]
23:41:29   1> java.lang.IllegalArgumentException: can't resolve failed cluster state with uuid [pUMf5_JaTfWkxYQpiownGw], version [3]
23:41:29   1> 	at org.elasticsearch.discovery.zen.PendingClusterStatesQueue.markAsFailed(PendingClusterStatesQueue.java:110) ~[main/:?]
23:41:29   1> 	at org.elasticsearch.discovery.zen.ZenDiscovery$3.onFailure(ZenDiscovery.java:817) [main/:?]
23:41:29   1> 	at org.elasticsearch.discovery.zen.ZenDiscovery$3.onSuccess(ZenDiscovery.java:807) [main/:?]
23:41:29   1> 	at org.elasticsearch.cluster.service.ClusterApplierService$SafeClusterApplyListener.onSuccess(ClusterApplierService.java:524) [main/:?]
23:41:29   1> 	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:476) [main/:?]
23:41:29   1> 	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:418) [main/:?]
23:41:29   1> 	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:162) [main/:?]
23:41:29   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:627) [main/:?]
23:41:29   1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [main/:?]
23:41:29   1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [main/:?]
23:41:29   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
23:41:29   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
23:41:29   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
23:41:29   1> 	Suppressed: java.lang.IllegalStateException: can't resolve processed cluster state with uuid [pUMf5_JaTfWkxYQpiownGw], version [3]
23:41:29   1> 		at org.elasticsearch.discovery.zen.PendingClusterStatesQueue.markAsProcessed(PendingClusterStatesQueue.java:147) ~[main/:?]
23:41:29   1> 		at org.elasticsearch.discovery.zen.ZenDiscovery$3.onSuccess(ZenDiscovery.java:805) [main/:?]
23:41:29   1> 		at org.elasticsearch.cluster.service.ClusterApplierService$SafeClusterApplyListener.onSuccess(ClusterApplierService.java:524) [main/:?]
23:41:29   1> 		at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:476) [main/:?]
23:41:29   1> 		at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:418) [main/:?]
23:41:29   1> 		at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:162) [main/:?]
23:41:29   1> 		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:627) [main/:?]
23:41:29   1> 		at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [main/:?]
23:41:29   1> 		at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [main/:?]
23:41:29   1> 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
23:41:29   1> 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
23:41:29   1> 		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
```

@elasticmachine run the gradle build tests 1

2018-11-26 09:25 UTC, merged