Work In Progress: Core: Migrating from joda to java.time. Watcher plugin
elastic/elasticsearch pull request #35809
Opened 2018-11-22 07:20 UTC by pgomulka

part of the migrating joda time work. The goal is to find usages of joda
time and refactor to use java.time.

No need for review yet.

refers #27330

2018-11-22 07:20 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2019-01-28 14:34 UTC, pgomulka commented on client/rest-high-level/src/main/java/org/elasticsearch/client/watcher/WatchStatusDateParser.java
> +    private static final DateFormatter FORMATTER = DateFormatter.forPattern("strict_date_optional_time||epoch_millis");
I can see the same one used in DateFieldMapper - should we create a "default_date_time_formatter" in `DateFormatters` ?

2019-01-28 14:40 UTC, pgomulka commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/support/WatcherDateTimeUtils.java
> -    public static final DateFormatter dateTimeFormatter = DateFieldMapper.DEFAULT_DATE_TIME_FORMATTER;
can see the same one used in DateFieldMapper - should we create a "default_date_time_formatter" in DateFormatters ?

2019-01-28 14:47 UTC, pgomulka commented on x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/watch/clock/ClockTests.java
> +    public void testNowUTC() {//TODO what is that test supposed to prove?
this test is kind of odd - testing the API?

2019-01-29 09:27 UTC, spinscale requested changes
left a few comments, mainly cosmetic ones, think we are almost there

2019-01-29 10:37 UTC, pgomulka commented on client/rest-high-level/src/main/java/org/elasticsearch/client/watcher/ActionStatus.java
> +            this.timestamp = timestamp.withZoneSameInstant(ZoneOffset.UTC);
toDateTime will return a new instance. Still unlikely that there is any comparison of references..
When I worked on this I wasn't aware that we have all DateTImes at UTC. 
You recon just assigning the parameter ?

2019-01-29 13:00 UTC, pgomulka commented on client/rest-high-level/src/main/java/org/elasticsearch/client/watcher/WatchStatusDateParser.java
> +    public static ZonedDateTime parseDate(String text) {
indeed in can now be replaced. good spot

2019-01-29 14:03 UTC, pgomulka commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/support/WatcherDateTimeUtils.java
> +            return ((JodaCompatibleZonedDateTime) value).toInstant().atZone(ZoneOffset.UTC);
so UTC time is here (or everywhere) safe to assume?

2019-01-29 14:27 UTC, pgomulka commented on x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java
> +                logger.debug("triggered job [{}] at [{}] (scheduled time was [{}])", schedule.name,
will create variables as previously

2019-01-29 16:06 UTC, pgomulka commented on x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalToolTests.java
> +        if (ZoneId.systemDefault().equals(ZoneOffset.UTC)) {//TODO that is probablyl broken!!
it did not fail for me, but I couldn't reproduce on master either

2019-01-29 17:38 UTC, jakelandis commented on client/rest-high-level/src/main/java/org/elasticsearch/client/watcher/ActionStatus.java
> +            this.timestamp = timestamp.withZoneSameInstant(ZoneOffset.UTC);
+1 to just assign the parameter. We should avoid the appearance of conversions where there are none, or should not be any.  

Perhaps a `assert timestamp.getOffset() == ZoneOffset.UTC`

2019-01-29 19:15 UTC, jakelandis commented on x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/watch/WatchStatusTests.java
> +        ActionStatus actionStatus = new ActionStatus(ZonedDateTime.now());
I know these are only tests, but we can we avoid using the default TZ ? For anyone that looks at the unit tests for examples, this can lead to bugs.

2019-01-29 19:20 UTC, jakelandis commented
Overall this change looks good a couple small comments. 

However a broader question, (not suggesting that we do this now), why do we pass a ZonedDateTime around everywhere if we only care about UTC timezone ?  I would think that passing around LocaleDateTime and only add the UTC timezone information when/where needed (like for serialization) would be more accurate and less prone to bugs.

2019-01-30 06:54 UTC, pgomulka commented on server/src/test/java/org/elasticsearch/search/aggregations/pipeline/DateDerivativeIT.java
> +    // rangefield method?
should not be here (old comment, not in master). will remove

2019-01-31 08:04 UTC, pgomulka commented on client/rest-high-level/src/main/java/org/elasticsearch/client/watcher/ActionStatus.java
> +            this.timestamp = timestamp.withZoneSameInstant(ZoneOffset.UTC);
will just assign. I like the idea of assert here. Since we have HLRC well covered in tests, this should help spotting if the timezone is badly set

2019-02-01 16:48 UTC, jakelandis approved these changes
LGTM

thanks for the updates and tackling this large chunk of code.

2019-02-04 10:20 UTC, spinscale commented on x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/notification/email/Email.java
> +                    email.sentDate(ZonedDateTime.parse(parser.text())
I'd go with a `strict_date_time` formatter for clarity here

2019-02-04 10:28 UTC, spinscale approved these changes

2019-02-04 14:08 UTC, merged