Introducing testing conventions task
elastic/elasticsearch pull request #35861
Opened 2018-11-23 15:13 UTC by atorok

This is in the context of #33524 and #34820 and an annoyance I had with running these checks as a separate process. 

This PR introduces a new task meant to replace  `NamingConventionsCheck` and `NamingConventionsTask`. 
In the interest of keeping the PR small it does not do so yet, but the goal is to have all the checks implemented here. 
These checks will be added as follow ups and we will eventually replace the old tasks with the new porting the existing tests to the new task.

There are small changes in the way the checks are done, like looking for method naming connections and methods annotated with `@Test`.  

The advantage of doing this in Gradle is speed and the ability to gather insights. 
This will allow us to do things like  auto disable testing tasks if all tests are muted. 

We call the same reflection methods multiple times, like getting the methods of a class multiple times to keep what's being checked for more readable.

2018-11-23 15:13 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-11-26 06:36 UTC, atorok commented
@elasticmachine run gradle tests 1

2018-11-26 06:39 UTC, atorok commented
@elasticmachine run gradle build tests 1

2018-11-26 08:29 UTC, atorok commented
@elasticmachine run gradle build tests 1

2018-11-27 17:06 UTC, nik9000 requested changes
I like it! I left a minor thing. We can build on this and remove the other checks that we have as we go! wonderful.

2018-11-27 17:06 UTC, nik9000 commented on buildSrc/src/main/java/org/elasticsearch/gradle/precommit/TestingConventionsTasks.java
> +    private final List<String> problems;
It feels like this should be a method variable in the `test()` method.

2018-11-28 00:29 UTC, rjernst reviewed
One question. I'm also curious how long this takes vs the previous task testing conventions implementation?

2018-11-29 07:06 UTC, atorok commented
@rjernst  `namingConventions` runs in `1m 5s` for me `testingConventions` completes in `55s` ( both are following a clean )

2018-11-29 14:48 UTC, atorok commented
@elasticmachine run gradle build tests 1

2018-11-29 14:51 UTC, nik9000 commented
> @rjernst `namingConventions` runs in `1m 5s` for me `testingConventions` completes in `55s` ( both are following a clean )

Is that including compile or just the running the task? Does it include gradle's startup time? Or is it the runtime of running that task for all subprojects?

2018-11-29 14:53 UTC, nik9000 reviewed
I'm happy with it modulo the timing discussion.

2018-11-29 14:53 UTC, nik9000 approved these changes

2018-11-29 19:32 UTC, rjernst approved these changes
LGTM. I also think after we convert the existing namingConventions uses, we should change this task name back to `namingConventions`

2018-11-30 05:52 UTC, atorok commented
The times are what Gradle reports after running each task after a clean has previously been ran, using the daemon and parallel. So it does include compile times as well.

2018-11-30 07:34 UTC, merged