SQL: Implement GREATEST and LEAST functions
elastic/elasticsearch pull request #35879
Opened 2018-11-25 01:10 UTC by matriv

Add GREATEST(expr1, expr2, ... exprN) and LEAST(expr1, expr2, exprN)
functions which are in the family of CONDITIONAL functions.

Implementation follows PostgreSQL behaviour, so the functions return
`NULL` when all of their arguments evaluate to `NULL`.

Renamed `CoalescePipe` and `CoalesceProcessor` to `ConditionalPipe` and
`ConditionalProcessor` respectively, to be able to reuse them for
`Greatest` and `Least` evaluations. To achieve that `ConditionalOperation`
has been added to differentiate between the functionalities at execution
time.

Closes: #35878

2018-11-25 01:10 UTC, elasticmachine commented
Pinging @elastic/es-search

2018-11-25 01:11 UTC, matriv commented on x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java
> -                        } else if (pj instanceof In) {
Leftover: `In` is already extending `ScalarFunction`.

2018-11-25 19:29 UTC, costin requested changes
Looks good however the optimizer rule could be improved as well as the class hierarchy.

2018-11-26 11:37 UTC, matriv commented on x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/Conditionals.java
> +    private static Object getMinOrMax(Collection<Object> values, BiFunction<Object, Object, Boolean> comparison) {
But the arguments can also be Strings.

2018-11-26 14:42 UTC, matriv commented
@costin Thanks for the review. Pushed commits to address comments.

2018-11-26 14:56 UTC, costin approved these changes
Left some minor polishing comments.
LGTM!

2018-11-26 14:56 UTC, costin commented on x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Foldables.java
> +    private static <T, C extends Collection<T>> C foldAndAdd(Collection<Expression> expressions, DataType to, C values) {
Please rename it to `foldTo` - I was thinking the values are folded and added together based on the current name.

2018-11-26 14:56 UTC, costin commented on x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/ArbitraryConditionalFunction.java
> +    private ConditionalOperation operation;
`final`

2018-11-26 14:56 UTC, costin commented on x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/Conditionals.java
> +    static Object coalesceOnInput(List<Processor> processors, Object input) {
The `On` is superfluous. - `coalesceInput`, `greatestInput`, etc...

2018-11-26 15:32 UTC, astefan approved these changes
LGTM. Left one question only.

2018-11-26 15:32 UTC, astefan commented on x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/Conditionals.java
> +            i++;
I think here the `i` logic can be replaced by a `boolean`? Seems to be a `true/false` scenario.

2018-11-26 17:21 UTC, merged

2018-11-26 17:37 UTC, matriv commented
Backported to `6.x` with 44d6c74214ab784ad324e7b5ecbb56d18940be8c