[APIKey] Add rest action for create API Key
elastic/elasticsearch pull request #36029
Opened 2018-11-29 05:51 UTC by bizybot

This commit adds rest action for creating API keys.

We use `java.time.Instant` to represent expiration for the API key.
But when we serialize the response object to JSON the nanosecond
precision is lost causing equality check failure after deserialization,
to avoid this we are removing the nanosecond precision while creating
the response object.

Note: HLRC changes will be done in next PR.

2018-11-29 05:51 UTC, elasticmachine commented
Pinging @elastic/es-security

2018-12-04 19:45 UTC, jaymode requested changes
Left a comment and we also need to add the rest spec json document in x-pack/plugin/src/test/resources/rest-api-spec/api. It would also be good to add a basic test in x-pack/plugin/src/test/resources/rest-api-spec/test

2018-12-04 19:45 UTC, jaymode commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/CreateApiKeyResponse.java
> +        this.expiration = (expiration != null) ? Instant.ofEpochMilli(expiration.toEpochMilli()): null;
can you add a comment about why you transform the instant here

2018-12-17 18:42 UTC, jaymode requested changes

2018-12-17 18:42 UTC, jaymode commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/CreateApiKeyRequest.java
> -        this.refreshPolicy = Objects.requireNonNull(refreshPolicy, "refresh policy may not be null");
Why would we allow a null refresh policy?

2018-12-17 18:42 UTC, jaymode commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/action/RestCreateApiKeyAction.java
> +}
nit: end file with a empty line

2018-12-17 18:42 UTC, jaymode commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/action/RestCreateApiKeyAction.java
> +                    .setRefreshPolicy((refresh != null) ? WriteRequest.RefreshPolicy.parse(request.param("refresh")) : null);
I think it is wrong to change the behavior to accept null just for this

2018-12-17 18:42 UTC, jaymode commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/TokenSSLBootstrapCheck.java
> +            } else if (apiKeyServiceEnabled) {
let's split this out into its own check

2018-12-17 18:42 UTC, jaymode commented on x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/rest/action/RestCreateApiKeyActionTests.java
> +        try {
use try-with-resources

2018-12-20 22:00 UTC, jaymode approved these changes
The last change that we need is to remove `_xpack` from the url and change `security` to `_security` everywhere in this PR. Otherwise LGTM

2018-12-24 03:07 UTC, merged