[Zen2] Storage layer WriteStateException propagation
elastic/elasticsearch pull request #36052
Opened 2018-11-29 13:24 UTC by andrershov

Currently, we only log that `WriteStateException` has occurred, in
`GatewayMetaState`. 

This PR goal is to re-throw `WriteStateException` to upper layers.
If `dirty` flag is set to false, we wrap `WriteStateException` in
`UncheckedIOException`, we prefer unchecked exception not to add
explicit `throws` in the multitude of layers.
If `dirty` flag is set to true - the world is broken. And we need to
halt the JVM. Instead of explicit halting in `GatewayMetaState`, we
prefer to throw `IOError`, which will be subsequently handled by
`ElasticsearchUncaughtExceptionHandler` and JVM will be halted. Sadly,
IOError accepts no message argument, that's why we first wrap
`WriteStateException` with `IOException` and then with `IOError`.

This PR also adds tests for `WriteStateException`.

2018-11-29 15:11 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-11-30 13:37 UTC, andrershov commented
run gradle build tests

2018-11-30 13:38 UTC, andrershov commented
run gradle build tests 1

2018-12-05 15:36 UTC, DaveCTurner commented
We discussed this issue as a team today and concluded that we are ok with the node shutting down with an exception in these situations.

2018-12-05 15:42 UTC, DaveCTurner requested changes
Asked for a couple of simplifications.

2018-12-05 15:42 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/gateway/WriteStateException.java
> +            throw new IOError(new IOException(msg + ", storage is dirty", this));
I think we do not need the message here: the message indicates the calling method but this is also in the stack trace (and the previous log line) and we would know that the storage was dirty if we have an `IOError` caused by a `WriteStateException`.

2018-12-05 15:42 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/gateway/WriteStateException.java
> +            throw new UncheckedIOException(msg, this);
Similarly I think we don't need to add this message.

2018-12-05 15:42 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/gateway/GatewayMetaState.java
> +            logger.error("Failed to set current term to {}", currentTerm);
Could we log the exception and stack trace too? `logger.error(new ParameterizedMessage("Failed to set current term to {}", currentTerm), e);`

2018-12-05 15:42 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/gateway/GatewayMetaState.java
> +            logger.error("Failed to set last accepted state with version {}", clusterState.version());
Could we log the exception and stack trace too?

2018-12-06 10:44 UTC, andrershov commented
@DaveCTurner I've finished with the changes, could you please take a look?

2018-12-06 15:09 UTC, DaveCTurner approved these changes
LGTM, thanks @andrershov

2018-12-06 16:02 UTC, merged

2018-12-06 16:03 UTC, andrershov commented
@DaveCTurner thanks for your reviewing efforts and bringing it up on the team meeting!