Deprecation check for File Discovery plugin
elastic/elasticsearch pull request #36190
Opened 2018-12-04 00:06 UTC by gwbrown

Adds a deprecation warning that the file discovery plugin is no longer
needed and that the path it uses has changed.

Relates to https://github.com/elastic/elasticsearch/issues/36024 and https://github.com/elastic/elasticsearch/pull/33257

2018-12-04 00:06 UTC, elasticmachine commented
Pinging @elastic/es-core-features

2018-12-04 07:53 UTC, DaveCTurner requested changes
I think this needs to be two independent checks:

1. the `discovery-file` plugin is not in use, and
1. the path to the unicast hosts file is correct

This is because in versions ≥ 6.5.0 you can be using the old path without using the plugin, and in that situation AIUI this warning won't fire.

2018-12-04 22:24 UTC, gwbrown commented
@DaveCTurner I agree that would be better, however it looks like a fair bit of plumbing work to get that information through the NodeInfo API (or modify the deprecation check framework to support getting information another way).  Am I wrong there?

This is an interesting one, as there doesn't look like a clean way to expose this easily.

2018-12-05 10:40 UTC, DaveCTurner commented
I see. Yes, you're right, apart from logging a deprecation warning we don't record that the discovery file isn't in the new place.

I think if the file is not in the right place on 7.0+ nodes during an upgrade then the upgraded nodes will struggle to join the cluster, which seems ok. It depends a bit on whether they're using file-based discovery exclusively or some combination of other discovery mechanisms too, but if it's exclusively file-based discovery then no file means no discovery. Am I right that the migration assistant is intended to be a best-effort thing? If so then this is going to be ok.

2018-12-06 23:43 UTC, gwbrown commented
@DaveCTurner I believe that yes, the migration assistant/deprecation info API is intended to be best-effort.  Users will still need to check the deprecation logs for any request/response format changes they'll need to make anyway.

I've opened https://github.com/elastic/elasticsearch/issues/36343 to track the larger issue, but it's unlikely to be addressed before the release of 7.0, so I think it might be best to move forward with this as-is.

2018-12-07 06:19 UTC, DaveCTurner approved these changes
Ok, this LGTM then, thanks for the explanations @gwbrown.

2018-12-07 16:06 UTC, merged