[Zen2] Hide not recovered state
elastic/elasticsearch pull request #36224
Opened 2018-12-04 17:15 UTC by andrershov

This PR hides `ClusterState`, that has `STATE_NOT_RECOVERED_BLOCK`,
from `ClusterStateAppliers`.
This is needed, because some appliers, such as `IngestService`, rely on
the fact, that cluster state with `STATE_NOT_RECOVERED_BLOCK` won't
contain anything useful.
Once the state is recovered it's fully available for the appliers.

Also, this PR switches most of the tests that require persistence/state
recovery from Zen1 to Zen2.
There are still the following tests, that were assumed to work after
persistence/recovery is implemented by do not, namely:
1. PrimaryAllocationIT
2. GatewayIndexIT.testDanglingIndices and
testIndexDeletionWhenNodeRejoins
3. RemoveCorruptedShardCommandIT

2018-12-04 17:15 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-12-05 12:27 UTC, ywelsch requested changes
I've request one small change to the hiding logic, o.w. looking good.

2018-12-05 14:13 UTC, andrershov commented on modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/IngestRestartIT.java
> -            .put(TestZenDiscovery.USE_ZEN2.getKey(), false) // no state persistence yet
https://github.com/elastic/elasticsearch/pull/36224/commits/0591d54cd60de120fff11a3ef3f69947b17ff6f2

2018-12-05 14:13 UTC, andrershov commented on x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/integration/MlDistributedFailureIT.java
> -            .put(TestZenDiscovery.USE_ZEN2.getKey(), false) // no state persistence yet
https://github.com/elastic/elasticsearch/pull/36224/commits/0591d54cd60de120fff11a3ef3f69947b17ff6f2

2018-12-05 14:13 UTC, andrershov commented on server/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java
> +        internalCluster().stopRandomNode(InternalTestCluster.nameFilter(nodes.get(1)));
https://github.com/elastic/elasticsearch/pull/36224/commits/254aa2fba23aa23140d54f79908dd848627e834c

2018-12-05 14:15 UTC, andrershov commented
@ywelsch I've fixed nits, for some reason I don't see your comments regarding changing hiding logic, can you please comment again?

2018-12-05 15:01 UTC, ywelsch commented
weird, my comment has disappeared. I had asked for the hiding logic to keep the coordinationmetadata and the cluster uuid in the empty metadata, as these are particularly useful at this stage where the state might not be recovered yet, but the cluster state is already accessible through the cluster state API.

2018-12-05 15:24 UTC, andrershov commented
@ywelsch I've improved hiding logic in https://github.com/elastic/elasticsearch/pull/36224/commits/9c2bfed2d81490dbb2ef09cab3e374dd137bf948, can you please take a look?

2018-12-05 15:41 UTC, ywelsch approved these changes
LGTM

2018-12-05 22:11 UTC, merged