add missing error type mapping for apm-server monitoring
elastic/elasticsearch pull request #36273
Opened 2018-12-05 16:25 UTC by graphaelli

backports #36178 to 6.5

depends on #36266

2018-12-05 16:56 UTC, graphaelli commented
run gradle build tests 1

2018-12-05 18:47 UTC, elasticmachine commented
Pinging @elastic/es-core-features

2018-12-05 19:29 UTC, pickypg requested changes
This also needs to update

https://github.com/elastic/elasticsearch/blob/9c761a810bf39d3269051d1c06d415c673094f6f/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/monitoring/exporter/MonitoringTemplateUtils.java#L31

For both 6.x/6.5 branches to `6.5.3`.

2018-12-05 19:31 UTC, graphaelli commented on buildSrc/version.properties
> +elasticsearch     = 6.5.3
those changes were already merged into 6.5 but after I created this.  Trying to avoid the wait for that to be merged + the test time following it.

2018-12-05 19:44 UTC, pickypg approved these changes
LGTM. This needs to be ported to 6.x as well.

2018-12-05 20:25 UTC, graphaelli commented
jenkins, retest this please

2018-12-05 22:14 UTC, graphaelli commented
jenkins, retest this please

no idea what is wrong here

2018-12-06 01:50 UTC, graphaelli commented
It was an issue with the bwc artifacts.

jenkins, retest this please

2018-12-06 02:38 UTC, graphaelli commented
run gradle build tests 2

2018-12-06 13:58 UTC, merged