Register CcrRepository based on settings update (#36086)
elastic/elasticsearch pull request #36277
Opened 2018-12-05 17:35 UTC by tbrooks8

This commit adds an empty CcrRepository snapshot/restore repository.
When a new cluster is registered in the remote cluster settings, a new
CcrRepository is registered for that cluster.

This is implemented using a new concept of "internal repositories".
RepositoryPlugin now allows implementations to return factories for
"internal repositories". The "internal repositories" are different from
normal repositories in that they cannot be registered through the
external repository api. Additionally, "internal repositories" are local
to a node and are not stored in the cluster state.

The repository will be unregistered if the remote cluster is removed.

2018-12-05 17:35 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-12-05 18:32 UTC, tbrooks8 commented
@ywelsch - This back port required some substantive changes due to modifications needed for the actions. Can you give it a review?

2018-12-06 08:04 UTC, ywelsch requested changes
If you subclass GenericAction instead, I think you can avoid the whole RequestBuilder stuff and the code will look pretty much like on master (and fields still final)

2018-12-06 21:55 UTC, ywelsch approved these changes
LGTM. Thanks!

2018-12-07 16:10 UTC, merged