Keys are compared in BucketSortPipelineAggregation so making key type…
elastic/elasticsearch pull request #36407
Opened 2018-12-09 14:56 UTC by ItamarBenjamin

… (ArrayMap) implement Comparable. Maps are compared using the entry set's iterator so ordered maps order is maintain. For each entry first comparing key then value. Assuming all keys are strings. When comparing entries' values if type is not identical and\or type not implementing Comparable, throwing exception. Not implementing equals() and hashCode() functions as parent's ones are sufficient. Tests included.

2018-12-09 14:56 UTC, elasticcla commented
Hi @ItamarBenjamin, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/36407.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

2018-12-10 07:40 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo

2018-12-10 08:15 UTC, jimczi requested changes
Thanks @ItamarBenjamin , the change looks good. I left some comments regarding the type of values that you need to compare.

2018-12-10 08:15 UTC, jimczi commented on server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/InternalComposite.java
>          final Object[] values;
The `values` are already comparable so you could change the type to `Comparable<?>` here and then use `values[i].compareTo` ?

2018-12-10 08:15 UTC, jimczi commented on server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/InternalComposite.java
> +                this.values[i] = formatObject(values[i], formats.get(i));
If you want a comparaison of the raw key you cannot perform the formatting in the ctr. Depending on the requested format the value can be formatted to a string which will not preserve the initial order (dates for instance).

2018-12-10 08:15 UTC, jimczi commented on server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/InternalComposite.java
> +                int compare = compareInternal(thisNext.getKey(),thatNext.getKey(),String::compareTo);
`Objects.compare` ?

2018-12-10 08:15 UTC, jimczi commented on server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/InternalComposite.java
>          ArrayMap(List<String> keys, List<DocValueFormat> formats, Object[] values) {
`ArrayMap(List<String> keys, List<DocValueFormat> formats, Comparable<?>[] values) {`

2018-12-10 08:15 UTC, jimczi commented on server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/InternalComposite.java
> +            Iterator<Entry<String, Object>> thisIterator = this.entrySet().iterator();
The iterator returns the formatted values so you should simply iterate directly on the `values` array ?

2018-12-12 10:10 UTC, ItamarBenjamin commented
Hi @jimczi, Thanks for your comments. please review the new commit.

2018-12-26 07:30 UTC, jimczi commented
@elasticmachine test this please

2018-12-26 07:54 UTC, jimczi commented
@elasticmachine test this please

2018-12-26 08:30 UTC, jimczi commented
@elasticmachine test this please

2018-12-26 08:55 UTC, jimczi commented
@elasticmachine test this please

2018-12-26 14:48 UTC, jimczi commented
run gradle build tests 2

2018-12-27 07:49 UTC, jimczi approved these changes
Sorry for the delay @ItamarBenjamin , the change looks good and tests pass so I'll merge

2018-12-27 07:51 UTC, merged