_msearch subrequests parsing #4227
elastic/elasticsearch pull request #36411
Opened 2018-12-09 22:35 UTC by vieirajlt

`MultiSearchRequest.add()` relies on `RestSearchAction.parseSearchRequest()` to parse the subrequests by making parsed vars on each subrequest part of `RestRequest.params` .

2018-12-10 07:39 UTC, elasticmachine commented
Pinging @elastic/es-search

2018-12-19 15:07 UTC, mayya-sharipova commented
@elasticmachine test this please

2019-02-25 14:12 UTC, javanna requested changes
hi @vieirajlt thanks for your PR, I left a couple of comments. Did you have a chance to check which parameters are missing in msearch that search supports, just to see what we are adding support for with your change ?

2019-02-25 14:12 UTC, javanna commented on server/src/main/java/org/elasticsearch/action/search/MultiSearchRequest.java
> +        RestSearchAction.parseSearchRequest(searchRequest, request, parser, setSize, false);
Ideally we would not reference any Rest action from a request

2019-02-25 14:12 UTC, javanna commented on server/src/main/java/org/elasticsearch/rest/RestRequest.java
> +    }
I was hoping that we could have shared code between search and msearch to keep the supported params in sync, without having to change RestRequest. Do you think that is possible?

2019-02-25 14:12 UTC, javanna commented on server/src/test/java/org/elasticsearch/action/search/MultiSearchRequestTests.java
> +    }*/
should the commented out tests be moved somewhere else?

2019-04-04 08:54 UTC, jimczi commented
@vieirajlt sorry for the late reply, are you still interested in getting this PR in? It has merge conflicts that need to be addressed and @javanna left some comments regarding the implementation.

2024-07-17 19:36 UTC, javanna commented
Closing for lack of feedback.

2024-07-17 19:36 UTC, closed without merging