CCR: mention how to enable soft deletes in error message when non enabled
elastic/elasticsearch pull request #36476
Opened 2018-12-11 12:03 UTC by bleskes

2018-12-11 12:03 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2018-12-11 12:10 UTC, martijnvg approved these changes
LGTM - Do think tests need to be adjusted because of this change. (`LocalFollowIndexIT#testDoNotCreateFollowerIfLeaderDoesNotHaveSoftDeletes(...)` and `TransportResumeFollowActionTests#testValidation(...)`)

2018-12-11 12:12 UTC, bleskes commented
Thanks @martijnvg, I was optimistically relying on CI to be bubble up tests that rely on this string (if at all). Thanks for the heads up.

2018-12-11 12:20 UTC, jasontedor requested changes
🙏

2018-12-11 12:20 UTC, jasontedor commented on x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportPutFollowAction.java
> +                    "soft deletes must be enabled when the index is created by setting index.soft_deletes.enabled to true"));
Please use `IndexSettings.INDEX_SOFT_DELETES_SETTING.getKey()` so we have fewer places we have to search the code base for the hard string for, if ever we need to.

2018-12-11 15:47 UTC, jasontedor approved these changes

2018-12-12 09:57 UTC, bleskes commented
check this please

2018-12-12 09:58 UTC, bleskes commented
@martijnvg @jasontedor FYI - I rebased this against 6.x . With the merge of #36141 which enables soft deletes as a default, I don't think this makes sense for master aymore.

2018-12-12 13:45 UTC, merged