restrict node start-up when cluster name in data path
elastic/elasticsearch pull request #36519
Opened 2018-12-12 00:06 UTC by talevy

When a 2.x cluster is created, the structure of `path.data` has all contents for a node inside a directory named after the cluster name. This was changed in 5.x (https://github.com/elastic/elasticsearch/pull/18554) to remove the directory with the cluster name and move its contents up a level. A 5.x cluster will still read the 2.x structure correctly. In 6.x this backwards compatible behavior is removed (https://github.com/elastic/elasticsearch/pull/20433), and if a 6.x node is started with a data directory using the old 2.x structure, it will see it as if it was empty and ignore the existing data.

This PR makes it so that a 6.x node refuses to start when there exists a data path 
with the cluster name in it.

relates: https://github.com/elastic/elasticsearch/issues/32661#issuecomment-432306352

2018-12-12 00:06 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2018-12-12 05:48 UTC, talevy commented
cc/ @bleskes took me a bit of time to get to this only to realize what the tests show, we don't necessarily have permissions to check whether there is a cluster-name in the data path.

2018-12-12 08:58 UTC, bleskes commented
Thx @talevy . I'm inclined to implement this as a `BootstrapCheck` that's always enforced. That said, those are run after the security manager is installed as well. @danielmitterdorfer can you please advise?

2018-12-12 13:15 UTC, danielmitterdorfer commented
A boostrap check makes sense to me (although they will only issue a warning when bound to loopback but I think it is ok?). I also think that we are safe with a bootstrap check because we setup the necessary permissions to access the data paths in `Security.configure`and then invoke the bootstrap checks. As the path in question is in a subdirectory of the data path (to which we have full access) I think we should be fine w.r.t. to access checks?

2018-12-12 15:49 UTC, talevy commented
thanks @danielmitterdorfer @bleskes, I will see how to make this a BootstrapCheck

2018-12-12 22:47 UTC, talevy commented
Update: I've learned more about BootstrapChecks and realized there are a few nice refactors to do that will make writing the `ClusterNameInDataPathCheck` a lot cleaner. Long story short: This check needs access to the node's Environment to work right.

PR that needs to be merged before continuing: https://github.com/elastic/elasticsearch/pull/36573
related PR that would be a nice to have: https://github.com/elastic/elasticsearch/pull/36574

2018-12-13 06:10 UTC, talevy commented
Update: refactors to give access to Environment#pathFiles have made it in, so now this is ready!

2018-12-13 08:54 UTC, danielmitterdorfer commented on server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java
> +    static class ClusterNameInDataPathCheck implements BootstrapCheck {
Should this overrride `alwaysEnforce()` and return `true`?

2018-12-14 08:21 UTC, danielmitterdorfer reviewed
Looks fine overall. I left a couple of suggestions / questions about the error message.

2018-12-15 00:07 UTC, talevy commented on server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java
> +                    "node cannot have cluster names as subdirectories in data paths [" + paths + "]");
thanks for the suggestion. more detail is probably best. updated

2018-12-17 18:02 UTC, talevy commented
example run from a test cluster named `elasticsearch`

```
[2018-12-17T10:00:23,572][INFO ][o.e.n.Node               ] [1Xo7d5f] initialized
[2018-12-17T10:00:23,573][INFO ][o.e.n.Node               ] [1Xo7d5f] starting ...
[2018-12-17T10:00:23,796][INFO ][o.e.t.TransportService   ] [1Xo7d5f] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}

ERROR: [1] bootstrap checks failed

[1]: Cluster name [elasticsearch] subdirectory exists in data paths [/distribution/archives/tar/build/distributions/elasticsearch-6.6.0-SNAPSHOT/data/elasticsearch]. All data under these paths must be moved up one directory to paths [/distribution/archives/tar/build/distributions/elasticsearch-6.6.0-SNAPSHOT/data]

[2018-12-17T10:00:23,850][INFO ][o.e.n.Node               ] [1Xo7d5f] stopping ...
[2018-12-17T10:00:23,865][INFO ][o.e.n.Node               ] [1Xo7d5f] stopped
[2018-12-17T10:00:23,866][INFO ][o.e.n.Node               ] [1Xo7d5f] closing ...
[2018-12-17T10:00:23,924][INFO ][o.e.n.Node               ] [1Xo7d5f] closed
[2018-12-17T10:00:23,928][INFO ][o.e.x.m.p.NativeController] [1Xo7d5f] Native controller process has stopped - no new native processes can be started
```

2018-12-17 21:36 UTC, talevy commented
run the default distro tests

2018-12-20 17:03 UTC, jasontedor requested changes
The production code looks good, yet I would structure it a little differently?

2018-12-20 17:10 UTC, talevy commented on server/src/main/java/org/elasticsearch/node/Node.java
> +        final List<Path> existingPathsWithClusterName = Arrays.stream(environment.dataFiles())
for sure, I was 50/50 on doing this, but decided against it due to fear of adding too much overhead. makes sense though, that method is large enough. I'll update

2018-12-23 01:45 UTC, jasontedor approved these changes
LGTM.

2019-01-02 18:02 UTC, talevy commented
thanks Jason!

2019-01-02 18:02 UTC, merged

2019-01-02 18:03 UTC, talevy commented
and thanks @danielmitterdorfer for initial review and suggestions!

2019-01-04 14:00 UTC, ywelsch commented
This PR was missing version and type labels. I've added them based on the commit that was merged. Please adapt if necessary.