Document dynamic email settings in Watcher
elastic/elasticsearch pull request #36543
Opened 2018-12-12 13:40 UTC by danielmitterdorfer

With this commit we document which of the email notification settings in
Watcher can be set dynamically via the cluster settings API.

2018-12-12 13:40 UTC, elasticmachine commented
Pinging @elastic/es-core-features

2018-12-13 01:11 UTC, jakelandis commented on docs/reference/settings/notification-settings.asciidoc
>    for the emails sent from the account. See {xpack-ref}/actions-email.html#email-action-attributes[
`email_defaults` are also dynamic.

2018-12-13 01:13 UTC, jakelandis requested changes
thanks @danielmitterdorfer ! this looks good.  just missing `email_defaults`

2018-12-13 05:35 UTC, danielmitterdorfer commented
@jakelandis thanks for the review. I've added a note to `email_defaults` as well now.

2018-12-13 12:58 UTC, jakelandis approved these changes

2018-12-13 12:58 UTC, jakelandis commented
LGTM thanks!

2018-12-13 13:09 UTC, merged

2018-12-13 13:10 UTC, danielmitterdorfer commented
Thanks for the review!

2018-12-13 13:14 UTC, danielmitterdorfer commented
Backported to 6.x in https://github.com/elastic/elasticsearch/commit/0e6afcb79968e4953140a81d02fe271655c08bee.