Refactored FIPS Checks into a Single Class (For Issue #34772)
elastic/elasticsearch pull request #36677
Opened 2018-12-15 20:15 UTC by LuisAlvelaMendes

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2018-12-17 02:52 UTC, elasticmachine commented
Pinging @elastic/es-security

2018-12-17 11:11 UTC, jkakavas requested changes
Hi @LuisAlvelaMendes !

Thanks once again for taking this up :) I did a first pass of your PR and I've left several comments and suggestions about how I think this could be further refactored. Let me know what you think. 

Please also make sure that you have configured your git installation correctly to set your name in the commits ( https://help.github.com/articles/setting-your-username-in-git/ )

Finally also make sure that you read through or [contribution guide](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) and follow all the steps mentioned there. At the absolute minimum, ensure that [precommit check](https://github.com/elastic/elasticsearch/blob/master/TESTING.asciidoc#running-verification-tasks) is passing. 

Let me know if you have any questions

2018-12-17 14:35 UTC, LuisAlvelaMendes commented on .gitignore
> +/bin/
This is my mistake, sorry for including certain files that weren't relevant

2018-12-17 14:37 UTC, LuisAlvelaMendes commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/FIPSInterface.java
> +public interface FIPSInterface {
The purpose would be to return an adequate FIPSCheckResult while also maintaining some consistency with how bootstrap checks were written .. I'm not quite sure what you mean b having the checks themselves implement it.

2018-12-17 14:40 UTC, LuisAlvelaMendes commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/FIPSChecks.java
> +        if (XPackSettings.FIPS_MODE_ENABLED.get(context.settings)) {
Do you mean add an if clause like `if (XPackSettings.FIPS_MODE_ENABLED.get(context.settings)) {}` surrounding it? I'm not sure what impact that would have

2018-12-17 14:43 UTC, LuisAlvelaMendes commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/FIPSChecks.java
> +		else {
How do you suggest we do it then?

2018-12-17 14:51 UTC, LuisAlvelaMendes commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java
> +                License.OperationMode licenseOperationMode = FIPSChecksInstance.get().getLicenseOperationMode();
How, exactly? I thought we had established the license operations should be independant from any metadata.

2018-12-17 14:52 UTC, LuisAlvelaMendes commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java
> +                License.OperationMode licenseOperationMode = FIPSChecksInstance.get().getLicenseOperationMode();
How, exactly? I thought we had established the license operations should be independant from any metadata.

2018-12-17 14:53 UTC, LuisAlvelaMendes commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java
> +        FIPSChecksInstance.set(new FIPSChecks(getLicenseState().getOperationMode()));
So we can get that instance with those values from the instruction `FIPSChecksInstance.get().check(context, env);` and call the checks

2018-12-17 21:10 UTC, jkakavas commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/FIPSChecks.java
> +        if (XPackSettings.FIPS_MODE_ENABLED.get(context.settings)) {
I meant that we can have the if clause once in `Security.java` and call `check()` on all the checks (or the one `check()` if we decide to implement `FipsChecks` in a simpler manner ) IF `fips_mode` is set

2018-12-17 21:11 UTC, jkakavas commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/FIPSInterface.java
> +public interface FIPSInterface {
I was thinking of an interface named `FIPSCheck` that then the checks like `FipsLicencingCheck` or `FipsPasswordHashingAlgoCheck` would implement. But I do think we don't necessarily need this either, there is no mandate to simulate bootstrap checks implementation. Same with `FIPSCheckResult`, it feels like an unnecessary abstraction. WDYT ?

2018-12-17 21:18 UTC, jkakavas commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/FIPSChecks.java
> +		else {
I was thinking something similar to how we use [addValidationError](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/ValidationException.java)

2018-12-20 17:59 UTC, jkakavas commented
@LuisAlvelaMendes Thanks for the updates and apologies, I just noticed the new commits. I will take another look tomorrow, please feel free to ping me directly here every time there is a pending action on my side as otherwise your updates might get lost in the sea of Github notifications :)

2018-12-21 09:01 UTC, jkakavas commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java
> +        FIPSChecksInstance.set(new FIPSChecks(getLicenseState().getOperationMode()));
The question was about why is it necessary to wrap the `FIPSChecks` in a `SetOnce` and not do 
```java
FIPSContext context = new FIPSContext(settings);
FIPSChecks checks = new FIPSChecks(getLicenseState().getOperationMode())
checks.check(context, env);
```

2019-01-08 11:47 UTC, jkakavas commented
Hi @LuisAlvelaMendes 

I thought I'd ping you and see how this is going and if you're still interested in seeing this PR through. If there's anything you'd want to discuss, feel free to add a comment here. 

https://github.com/elastic/elasticsearch/pull/36677/commits/e124f8a012165e2e60e217fd22f475e3c9b4d576 made me think that you had addressed some of the points we discussed above, hence my comment in https://github.com/elastic/elasticsearch/pull/36677#issuecomment-449084241,  but I then saw that this is the same as https://github.com/elastic/elasticsearch/pull/36677/commits/7a4e6ff574396a47b9c7d1d8a9870d6029fdd8f7 that you had committed earlier.

2019-01-10 19:37 UTC, LuisAlvelaMendes commented
@jkakavas Sorry but due to some personal things I will not be able conclude this pull request.

2019-10-03 11:02 UTC, jkakavas commented
Closing this in favor of #47499

2019-10-03 11:02 UTC, closed without merging