Added RLike tests
elastic/elasticsearch pull request #36688
Opened 2018-12-16 22:53 UTC by TomasNovo

Added some tests about RLike class to solve the issue #34609 .
The implemented tests focus not only on null arguments and null children but also with a normal constructor and with normal children, using a random integer to check the tests. The "to string" function was also tested

Closes https://github.com/elastic/elasticsearch/issues/34609 .

2018-12-17 09:52 UTC, elasticmachine commented
Pinging @elastic/es-search

2018-12-19 15:03 UTC, mayya-sharipova commented
@elasticmachine test this please

2018-12-19 15:32 UTC, astefan requested changes
@TomasNovo thank you for your interest and contribution. Unfortunately, the approach is not quite the one we were expecting. Please, have a look at other processors tests (for example, [BinaryComparisonProcessorTests](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/expression/predicate/operator/comparison/BinaryComparisonProcessorTests.java) or [SubstringProcessorTests](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/expression/function/scalar/string/SubstringProcessorTests.java)) to see how the unit testing for the RegexProcessor should look like.
Also, you need to add integration testing, as well. This would be in the form of queries in `*.csv-spec` files. See an example [here](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/sql/qa/src/main/resources/select.csv-spec).

2019-02-28 21:34 UTC, michaelbaamonde commented
@TomasNovo Are you still interested in moving this PR forward? Thanks!

2019-03-23 05:21 UTC, astefan commented
Closing this PR since the corresponding issue has been fixed and another PR pushed.

2019-03-23 05:21 UTC, closed without merging