Implement Atomic Blob Writes for HDFS Repository
elastic/elasticsearch pull request #37066
Opened 2019-01-02 09:20 UTC by original-brownbear

* Implement atomic writes the same way we do for the `FsBlobContainer` via rename which is atomic
* Relates #37011

2019-01-02 09:20 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-01-02 10:49 UTC, original-brownbear commented on plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsBlobContainer.java
> +                stream.hsync();
Created https://github.com/elastic/elasticsearch/pull/37069 to speed up writes using the same strategy for non-atomic writes.

2019-01-02 13:00 UTC, original-brownbear commented
Fails tests for some reason, looking into it

2019-01-03 11:05 UTC, ywelsch requested changes

2019-01-03 11:39 UTC, original-brownbear commented on plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsBlobContainer.java
> +                stream.hsync();
Urgh, you're right ... should've read the second paragraph in the docs of that method :)
Your solution is better will adjust.

2019-01-03 11:40 UTC, original-brownbear commented on plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsBlobContainer.java
> +        final String tempBlob = FsBlobContainer.tempBlobName(blobName);
I'd rather not I think. This method is kinda specific to the two file-system based implementations. Not sure it makes sense blowing up the interface for that?

2019-01-03 11:47 UTC, original-brownbear commented
@ywelsch fixed the sync method :)

2019-01-03 12:19 UTC, ywelsch approved these changes
LGTM

2019-01-03 13:12 UTC, original-brownbear commented
Jenkins runs gradle build tests 1 please

2019-01-03 13:12 UTC, original-brownbear commented
Jenkins run gradle build tests 1

2019-01-03 14:51 UTC, merged