MAPPING: Improve Precision for scaled_float
elastic/elasticsearch pull request #37169
Opened 2019-01-06 19:46 UTC by original-brownbear

* Use `toString` and `Bigdecimal` parsing to get intuitive behaviour for `scaled_float` as discussed in #32570
* Closes #32570

2019-01-06 19:46 UTC, elasticmachine commented
Pinging @elastic/es-search

2019-01-06 20:51 UTC, original-brownbear commented
Jenkins run gradle build tests 2

2019-01-07 07:33 UTC, original-brownbear commented
Jenkins run gradle build tests 2

2019-01-10 02:04 UTC, jpountz requested changes
I left a comment, thanks for tackling this issue!

2019-01-10 07:49 UTC, original-brownbear commented
@jpountz thanks for taking a look :) => all fixed in https://github.com/elastic/elasticsearch/pull/37169/commits/cad4fb1987a3bf5c1acc584c5265fbf0f79ece41 :)

2019-01-10 08:41 UTC, original-brownbear commented
Jenkins test this please

2019-01-10 08:57 UTC, original-brownbear commented
Jenkins run Gradle build test 1

2019-01-10 08:57 UTC, original-brownbear commented
Jenkins run gradle build tests 2

2019-01-10 08:58 UTC, original-brownbear commented
Jenkins run gradle build tests 1

2019-01-10 09:15 UTC, original-brownbear commented
Jenkins run Gradle build tests 1

2019-01-11 02:26 UTC, jpountz approved these changes

2019-01-11 07:07 UTC, original-brownbear commented
@jpountz thanks!

2019-01-11 07:07 UTC, merged