Missing parameter add
elastic/elasticsearch pull request #37294
Opened 2019-01-10 10:58 UTC by jm4ever

bin/elasticsearch-keystore add xpack.notification.email.account.gmail_account.smtp.secure_password
bin/elasticsearch-keystore add xpack.notification.email.account.outlook_account.smtp.secure_password
bin/elasticsearch-keystore add xpack.notification.email.account.ses_account.smtp.secure_password
bin/elasticsearch-keystore add xpack.notification.email.account.exchange_account.smtp.secure_password

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2019-01-10 11:01 UTC, elasticmachine commented
Pinging @elastic/es-security

2019-01-10 11:01 UTC, elasticmachine commented
Pinging @elastic/es-core-features

2019-01-14 17:06 UTC, jakelandis requested changes
@jm4ever - thanks for the contribution. Can you please sign the [CLA](http://www.elasticsearch.org/contributor-agreement/) and re-target your PR to master ? (I will back port to released versions)

2019-10-18 14:43 UTC, jrodewig commented
CLA not signed. #40444 corrected these bugs in later branches.

2019-10-18 14:43 UTC, closed without merging