HLRC - Add support for create API key
elastic/elasticsearch pull request #37389
Opened 2019-01-12 23:36 UTC by bizybot

This commit adds support for API to create an API key
in high-level rest client.

2019-01-12 23:36 UTC, elasticmachine commented
Pinging @elastic/es-security

2019-01-14 19:16 UTC, jaymode requested changes
I left one comment that needs to be addressed

2019-01-14 19:16 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/CreateApiKeyRequest.java
> +            @Nullable final RefreshPolicy refreshPolicy) {
I think our normal indentation aligns this with the `S` in String

2019-01-14 19:16 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/CreateApiKeyRequest.java
> +    public void setName(String name) {
why do we need setters? I'd prefer if we make all of the fields final and require them to be set in the constructor. Then we only have accessors

2019-01-15 14:51 UTC, jaymode approved these changes
I left a few minor comments to be addressed. Otherwise it LGTM and we do not need another review round

2019-01-15 14:51 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/CreateApiKeyResponse.java
> +        result = prime * result + Objects.hash(id, name, key);
just use `return Objects.hash`?

2019-01-15 14:51 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/CreateApiKeyResponse.java
> +        if (expiration == null) {
is this handwritten or auto generated? `Objects.equals` supports null values so why not just use that? Also, the lack of brackets on the if else bothers me

2019-01-15 14:51 UTC, jaymode commented on client/rest-high-level/src/main/java/org/elasticsearch/client/security/CreateApiKeyRequest.java
> +        int result = Objects.hash(name, refreshPolicy, roles);
just use Objects.hash?

2019-01-18 00:55 UTC, merged