Fix erroneous docstrings for abstract bulk by scroll request
elastic/elasticsearch pull request #37517
Opened 2019-01-16 08:59 UTC by torgeir

Fix erroneous docstrings indicating that `AbstractBulkByScrollRequest::abortOnVersionConflict` defaults to `false`, when it indeed actually [defaults to `true`](https://github.com/elastic/elasticsearch/blob/c1fe4b7d07794869ea7ac0036714552dcc15b47c/server/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByScrollRequest.java#L68),

2019-01-16 09:42 UTC, cbuescher requested changes
Hi @torgeir, thanks for suggesting the fix to the javadocs. The change looks good to me, but would you go a step further and change the docs to a sentence rather than a question? Something like "Returns "true" of version conflicts cause aborts. This is the default." and something similar (without the "returns) for the two setters?) That would be awesome. 
If you don't find the time for an update I can also merge this as-is.

2019-01-16 09:42 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-01-16 12:49 UTC, torgeir commented
Sure, I'll reformulate them to sentences without question marks!

If you really like to include information about the defaults I'd be happy to do so, but personally I belive (like the need for this PR shows) that this is a recipe for out of date docs 😊

2019-01-16 13:02 UTC, torgeir commented
@cbuescher Had another go, let me know what you think!

2019-01-17 09:21 UTC, cbuescher commented
> If you really like to include information about the defaults I'd be happy to do so, but personally I belive, that this is a recipe for out of date docs

Fair point. Thanks for the change, looks good to me. I will merge this to the other branches that are currently actively developed.

2019-01-17 09:21 UTC, cbuescher approved these changes

2019-01-17 09:22 UTC, merged