Document discovery.zen.commit_timeout treats negative values like 0. Issue #36632
elastic/elasticsearch pull request #37570
Opened 2019-01-17 13:45 UTC by camilin87

The scope of this PR is document the `discovery.zen.commit_timeout` treats negative values as 0.

A different PR will be required to update the Docs.

## Supporting Research

This test proves the setting can be negative

```java
public void testReadsNegativeCommitTimeout() {
    Settings settings = Settings.builder()
        .put(DiscoverySettings.COMMIT_TIMEOUT_SETTING.getKey(), "-10s")
        .build();

    TimeValue timeoutValue = DiscoverySettings.COMMIT_TIMEOUT_SETTING.get(settings);

    assertEquals(timeoutValue, new TimeValue(-10, TimeUnit.SECONDS));
}
```

However, the usage of `DiscoverySettings.getCommitTimeout()` leads down to this

```java
private boolean doAcquireSharedNanos(int arg, long nanosTimeout) throws InterruptedException {
        if (nanosTimeout <= 0L)
            return false;
        ...
}
```

2019-01-18 09:37 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-01-22 16:04 UTC, DaveCTurner requested changes
Since this setting is user-facing, I think the important documentation is the user-facing reference manual, i.e. `docs/reference/modules/discovery/zen.asciidoc`. Note that this file does not exist any more in `master`, reflecting that this setting will not be relevant in versions ≥7.0. You should make a PR against the `6.x` branch.

2019-02-25 14:58 UTC, javanna commented
hi @camilin87 would you mind opening a new PR against the 6.7 branch please? Like @DaveCTurner said above, this setting is not relevant anymore in master. Thanks!

2019-02-25 14:58 UTC, closed without merging

2019-02-25 15:06 UTC, camilin87 commented
No problem. I've been pretty busy for the last weeks. And I don't foresee that changing. I'll do it as soon as possible.

2019-02-25 15:08 UTC, javanna commented
sounds good thanks @camilin87 !