remove GeoHashGridAggregator.OrdinalBucket
elastic/elasticsearch pull request #37732
Opened 2019-01-22 23:35 UTC by talevy

This commit removes the OrdinalBucket class
from GeoHashGridAggregator and pulls the `bucketOrd`
field up to the GeoGridBucket. `bucketOrd` is
only used internally and is not used in serialization
and equivalence testing

2019-01-23 01:31 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo

2019-01-23 17:27 UTC, nyurik approved these changes
LGTM!

2019-01-23 17:35 UTC, talevy commented
this PR needs further discussion. These changes may have unintended consequences due to OrdinalBucket access from existing clients

2019-01-23 19:46 UTC, talevy commented
@colings86 do you think this change can present problems to users? I was thinking these changes would only go into 7.0

2019-01-24 08:49 UTC, colings86 requested changes
I'm not sure this is the right change to make because this change leaks information that is only relevant to the `buildAggregation` method of this class into an object that is shared across many classes.

If the intention here is to make it easier to allow different implementations of GeoGridBucket then why not change `OrdinalBucket` to be an object that instead of extending `GeoGridBucket` stores a GeoGridBucket and the bucket ordinal so the `bucketOrd` is not leaked outside of this method?

If the intention is just to get rid of a class then I don't think its worth doing and making the GeoGridBucket leak the information since the BucketOrdinal class is private and extremely lightweight

/cc @polyfractal @jpountz

2019-01-24 16:36 UTC, polyfractal commented
I might be wrong (@talevy correct me if I am), but I believe the intention was to just remove the class and simplify a bit.  

FWIW, this is [how terms buckets are done too](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/InternalTerms.java#L60) (non-serialized bucket ord tracked on the bucket itself).  Not to say it's better, just a datapoint :)

Perhaps we could refactor to not store ordinals on the buckets at all, and instead maintain a temporary map that links buckets to ords during `buildAggregation()`?  Since the least competitive bucket is always popped off we should know which ones need to be removed from a map.  But, I haven't really looked closely at how `buildAggregation()` works here (or in terms for that matter) so I may be missing something.  It's admittedly a little messier, but has less state floating around.

Re: bwc, is the issue that users may be typing directly on the `OrdinalBucket` class instead of the `GeoGridBucket` parent class?  It's package-private, so this shouldn't be an issue?

2019-01-24 16:47 UTC, talevy commented
> Re: bwc, is the issue that users may be typing directly on the OrdinalBucket class instead of the GeoGridBucket parent class? It's package-private, so this shouldn't be an issue?

that was the concern, but you're right. it shouldn't be a problem for clients. 

> If the intention here is to make it easier to allow different implementations of GeoGridBucket then why not change OrdinalBucket to be an object that instead of extending GeoGridBucket stores a GeoGridBucket and the bucket ordinal so the bucketOrd is not leaked outside of this method?

that is what I ended up doing in the refactor. For this reason, I will simply close this and take note of it for future aggregation refactoring that is to be planned.

2019-01-24 16:47 UTC, closed without merging