Step down as master when configured out of voting configuration
elastic/elasticsearch pull request #37802
Opened 2019-01-24 08:23 UTC by ywelsch

Abdicates to another master-eligible node once the active master is reconfigured out of the voting configuration, for example through the use of voting configuration exclusions.

Follow-up to #37712

2019-01-24 08:39 UTC, DaveCTurner approved these changes
LGTM

2019-01-24 08:39 UTC, DaveCTurner commented on server/src/test/java/org/elasticsearch/cluster/coordination/PublicationTests.java
> +        assertThat(publication.completedNodes().size(), equalTo(0));
I prefer using the `empty()` matcher so if it's not empty we get to see what was in it.

2019-01-24 08:42 UTC, DaveCTurner requested changes
Actually, I changed my mind, I think this behaviour should be noted in the docs for the voting config exclusions API.

2019-01-24 11:47 UTC, DaveCTurner approved these changes
LGTM

2019-01-24 16:34 UTC, ywelsch commented
This required more changes, I'll need another review.

2019-01-28 09:27 UTC, DaveCTurner requested changes
I asked for more harmony in how we prioritise nodes.

2019-01-28 11:48 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/cluster/coordination/Reconfigurator.java
> +    private TreeSet<String> masterFirstTreeSet(Collection<? extends String> items, DiscoveryNode masterNode) {
I've pushed 4e5886c4f9f

2019-01-28 18:13 UTC, ywelsch commented
@elasticmachine retest this please

2019-01-29 09:06 UTC, DaveCTurner approved these changes
LGTM

2019-01-29 09:18 UTC, ywelsch commented
@elasticmachine run elasticsearch-ci/default-distro

2019-01-29 11:43 UTC, merged