Move update and delete by query to use seq# for optimistic concurrency control
elastic/elasticsearch pull request #37857
Opened 2019-01-25 09:22 UTC by bleskes

The delete and update by query APIs both offer protection against overriding concurrent user changes to the documents they touch. They currently are using internal versioning. This PR changes that to rely on sequences numbers and primary terms.

Relates #37639 
Relates #36148 
Relates #10708

2019-01-25 09:22 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-01-28 19:29 UTC, ywelsch requested changes
One nit and possibly one important comment

2019-01-28 20:57 UTC, bleskes commented on modules/reindex/src/main/java/org/elasticsearch/index/reindex/AsyncDeleteByQueryAction.java
> +    private final boolean useSeqNoForOCC;
sure :)

2019-01-28 21:05 UTC, bleskes commented on server/src/main/java/org/elasticsearch/index/reindex/ScrollableHitSource.java
> +        public void setSeqNo(long seqNo) {
That's a good one. It's actually not relevant when indexing from remote (seqnos are only for when update the same index). This class is called "BasicHit" with a java doc of "An implementation of {@linkplain Hit} that uses getters and setters.", so I felt I had to add this, although it's not used. 

Your point actually made me realize I added partial parsing support which wasn't wired and isn't needed. I removed it.

2019-01-29 10:49 UTC, ywelsch approved these changes

2019-01-29 10:49 UTC, ywelsch commented on modules/reindex/src/main/java/org/elasticsearch/index/reindex/AsyncDeleteByQueryAction.java
> +    private final boolean useSeqNoForOCC;
You've changed it in the other class, but not here? 😢

2019-01-29 11:33 UTC, bleskes commented on modules/reindex/src/main/java/org/elasticsearch/index/reindex/AsyncDeleteByQueryAction.java
> +    private final boolean useSeqNoForOCC;
😢 indeed. fixing.

2019-01-29 15:23 UTC, merged

2019-01-29 15:23 UTC, bleskes commented
Thanks @ywelsch !