Handle total hits equal to track_total_hits
elastic/elasticsearch pull request #37907
Opened 2019-01-28 08:58 UTC by jimczi

This change ensures that a total hits equal to the value set for
track_total_hits is not considered as a lower bound.

Closes #37897

2019-01-28 08:58 UTC, elasticmachine commented
Pinging @elastic/es-search

2019-01-28 09:16 UTC, jpountz requested changes
We might still return `gte` in case of exact match if there is a single shard that has matches since Lucene sets the relation as `gte` as soon as the number of matches is greater than or equal to the threshold: https://github.com/apache/lucene-solr/blob/947f82679afa6d984c246b686d0133085982c376/lucene/core/src/java/org/apache/lucene/search/TopScoreDocCollector.java#L75

So I think we either need to change the behavior in Lucene as well or change expectations on our side?

2019-01-28 10:14 UTC, jimczi commented
We discussed with @jpountz offline and agreed that the behavior is Lucene is not intuitive (return a lower bound when the doc count is equal to the threshold). I opened https://issues.apache.org/jira/browse/LUCENE-8660 to change the heuristic to count accurately up to the threshold instead of threshold-1.

2019-02-15 15:43 UTC, jpountz approved these changes
LGTM

2019-03-05 11:03 UTC, merged