Add elasticsearch-node detach-cluster tool
elastic/elasticsearch pull request #37979
Opened 2019-01-29 15:31 UTC by andrershov

This commit adds the second part of `elasticsearch-node` tool - `detach-cluster` command in addition to `unsafe-bootstrap` command.
Also, this commit changes the semantics of `unsafe-bootstrap`, now `unsafe-bootstrap`` changes clusterUUID.
So the algorithm of running `elasticsearch-node` tool is the following:
1) Stop all nodes in the cluster.
2) Pick master-eligible node with the highest (term, version) pair and run the `unsafe-bootstrap` command on it. If there are no survived master-eligible nodes - skip this step.
3) Run `detach-cluster` command on the remaining survived nodes.

Detach cluster makes the following changes to the node metadata:
1) Resets clusterUUID to _na_ and sets clusterUUID commited to false.
2) Sets currentTerm, clusterVersion, term and version to 0 - not sure about it.
3) Removes voting tombstones and sets voting configurations to special constant MUST_JOIN_ELECTED_MASTER, that prevents initial cluster bootstrap.

`ElasticsearchNodeCommand` base abstract class is introduced, because `UnsafeBootstrapMasterCommand` and `DetachClusterCommand` have a lot in common.
Tests for both commands reside in `ElasticsearchNodeCommandIT` (renamed from `UnsafeBootstrapMasterIT`).

2019-01-29 15:31 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-01-30 10:10 UTC, ywelsch requested changes
Thanks for the PR @andrershov. I've left some initial comments. Can we also have a test where we have a data node rejoin a freshly bootstrapped cluster (i.e. when all master-eligible nodes were lost).
Also, can you adapt the existing tests (testDanglingIndices + ???) to show that this allows us to port them to Zen2?

2019-01-30 10:54 UTC, andrershov commented on server/src/main/java/org/elasticsearch/cluster/coordination/DetachClusterCommand.java
> +                    "your master-eligible nodes, and you cannot restore the cluster\n" +
See below "or you have already run `elasticsearch-node unsafe-bootstrap` ...". Probably @DaveCTurner will have to come up with better wording.

2019-01-30 10:54 UTC, andrershov commented on server/src/main/java/org/elasticsearch/cluster/coordination/DetachClusterCommand.java
> +                    "This tool can result in arbitrary data loss and should be\n" +
This sentence is just copied from unsafe-bootstrap command

2019-01-30 11:07 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/cluster/coordination/DetachClusterCommand.java
> +                    "This tool can result in arbitrary data loss and should be\n" +
sure, that still doesn't make it great :)

2019-01-30 12:45 UTC, andrershov commented
@ywelsch Thank you for the review!
I've addressed your comments, except wording.
Regarding tests, the two tests that you meant are `testDanglingIndices` and `testIndexImportedFromDataOnlyNodesIfMasterLostDataFolder` in my opinion they are the same and one of them should be removed.
Taking this into account, I've implemented `ElasticsearchNodeCommandIT.testAllMasterEligibleNodesFailedDanglingIndexImport` which replaces both  `testDanglingIndices` and `testIndexImportedFromDataOnlyNodesIfMasterLostDataFolder`.
I think, `ElasticsearchNodeCommandIT` is a better place for this test because it requires `detachCluster` invocation and `ElasticsearchNodeCommandIT` is specifically designed for this case and makes `detachCluster` command execution one-liner. 
Please let me know what do you think.

2019-01-30 16:04 UTC, DaveCTurner reviewed
I suggested some small changes to wording

2019-01-30 17:15 UTC, andrershov commented
@DaveCTurner thanks for your review! I've addressed `ClusterFormationFailureHelper` message in https://github.com/elastic/elasticsearch/pull/37979/commits/a122221a0986982a692c0eb2dc673d93cc001365 and all wording in https://github.com/elastic/elasticsearch/pull/37979/commits/80ad2248d1469b1ae602e891e91f63c594076734.
@DaveCTurner and @ywelsch it's ready for the next pass.

2019-01-31 14:06 UTC, ywelsch approved these changes
LGTM. Can you also address the TODO in `testCannotJoinClusterWithDifferentUUID` with this?

2019-01-31 15:20 UTC, DaveCTurner approved these changes
LGTM2

2019-01-31 20:30 UTC, andrershov commented
run elasticsearch-ci/2

2019-02-01 07:05 UTC, andrershov commented
run elasticsearch-ci/2

2019-02-01 09:40 UTC, andrershov commented
run elasticsearch-ci/2

2019-02-01 13:53 UTC, merged

2019-02-07 11:36 UTC, colings86 commented
Please remember to add all relevant labels (area label, version label(s) and change type label) on all PRs and please look for this as part of reviews. The release note generation process is made much harder when PRs are not labelled correctly.