Relax assertion in testRetentionLeasesSyncOnExpiration
elastic/elasticsearch pull request #38070
Opened 2019-01-31 06:12 UTC by dnhatn

The returned retention leases are collected from a HashMap which the
insert-order is not reserved; thus we should relax the order of leases.

Closes #37963

2019-01-31 06:12 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-02-04 22:36 UTC, jasontedor requested changes
I am confused by this change. Starting with [line 146](https://github.com/elastic/elasticsearch/pull/38070/files#diff-3fa4e051d3f4f29524dbaa47310ee845R144
), we assert that on the primary, the leases are either empty, or contain a single non-expired retention lease. For the assertion being changed here to be failing, that means that `currentRetentionLeases` is not empty. By the assertion on line 146, that means that `currentRetentionLeases` contains a single retention lease, the one non-expired retention lease. Therefore I do not see how changing from `contains` to `containsInAnyOrder` helps with that problem. Rather, I think that something else is going on although it is still not clear to me what. Note how the assert busy shows there was *another* retention lease on the replica, and then eventually none.

2019-02-04 23:05 UTC, jasontedor commented
@dnhatn I think that I have a better version of this test in a PR that I am working on.

2019-02-04 23:06 UTC, dnhatn commented
@jasontedor yeah, can I close this one?

2019-02-04 23:18 UTC, jasontedor commented
@dnhatn I opened #38380.

2019-02-05 03:50 UTC, dnhatn commented
Closes in favor of #38380.

2019-02-05 03:50 UTC, closed without merging