Limit token expiry to 1 hour and add API key documentation
elastic/elasticsearch pull request #38164
Opened 2019-02-01 09:18 UTC by bizybot

We have documented in our get token API that the configured
maximum value for token expiry is 1 hour but that was not
enforced. This commit fixes the setting and adds some missing
API key service settings documentation.

2019-02-01 09:18 UTC, elasticmachine commented
Pinging @elastic/es-security

2019-02-01 19:51 UTC, jaymode requested changes
We need to separate the token expiry change since it should probably be backported and is unrelated to API keys

2019-02-01 19:51 UTC, jaymode commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/TokenService.java
> +            TimeValue.timeValueMinutes(20L), TimeValue.timeValueSeconds(1L), TimeValue.timeValueHours(1L), Property.NodeScope);
this token expiry should be a separate change since it is unrelated to the API keys work

2019-02-04 17:16 UTC, jkakavas approved these changes
LGTM Yogesh

2019-02-06 06:33 UTC, closed without merging