Unmute, fix, refactor and zen2ify NetworkDisruptionIT
elastic/elasticsearch pull request #38351
Opened 2019-02-04 17:50 UTC by andrershov

This PR unmutes `NetworkDisruptionIT` on master.

It makes changes necessary for Zen2 - avoids usage of autoMinMasterNodes and selects cluster size, such that there is no need to call `AddVotingExclusion`.
This test also introduces refactors a single method `prepareDistruptedCluster` to be used by both test methods.
Unfortunately, `NetworkDisruption` is broken and the testNetworkPartitionRemovalRestoresConnections "is fixed" by introducing `assertBusy` -  https://github.com/elastic/elasticsearch/issues/38348.
I want to avoid backporting this PR to 6.x branch because there are might be Zen1 specific issues with the tests as well.

Relates https://github.com/elastic/elasticsearch/issues/36205
Relates https://github.com/elastic/elasticsearch/issues/38348

2019-02-04 17:50 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2019-02-04 17:50 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-02-08 12:45 UTC, ywelsch requested changes
Is the assertBusy and lowering `NodeConnectionsService.CLUSTER_NODE_RECONNECT_INTERVAL_SETTING` not sufficient here?
Note that these settings from AbstractDisruptionTestCase have their own problems, as they won't allow the cluster to be stable on a slow CI worker.

2019-02-08 12:45 UTC, ywelsch commented on test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java
> +                new NetworkDisruption.NetworkUnresponsive());
why change this to unresponsive?

2019-03-06 11:11 UTC, andrershov commented
@ywelsch thank you for your review, I've made necessary changes. Can you please make the second pass?

2019-03-15 15:46 UTC, ywelsch approved these changes
LGTM

2019-03-18 15:37 UTC, merged