Un-mute and fix BuildExamplePluginsIT
elastic/elasticsearch pull request #38899
Opened 2019-02-14 13:30 UTC by atorok

There doesn't seem to be anything wrong with the test iteself.
I think the failure were CI performance related, but while it was muted,
some failures managed to sneak in.

@jaymode , @tvernum note that this does fix the test, but users will still not be able to run it unless we publish the specific jars to maven central. This is done by the release manager. 
The `apply plugin: "nebula.maven-scm"` causes the POMs to be generated so RM can publish them, but the RM config still needs to be updated. 
This is necessary to make it possible for users to get to all the dependencies of the example plugin, including transitive dependencies. 
The reason this works in the regular build is that all the dependencies are taken from the current build, but the example plugins are also meant to be built outside the build. 

Closes #38784

2019-02-14 13:30 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2019-02-14 15:29 UTC, atorok commented
@elasticmachine run elasticsearch-ci/oss-distro-docs

2019-02-14 15:35 UTC, jaymode approved these changes

2019-02-27 17:45 UTC, mark-vieira requested changes

2019-02-27 17:45 UTC, mark-vieira commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy
> +import org.gradle.internal.os.OperatingSystem
Looks like this import is unused.

2019-02-27 17:45 UTC, mark-vieira commented on libs/ssl-config/build.gradle
> +apply plugin: "nebula.maven-scm"
Applying this plugin twice now.

2019-02-28 07:30 UTC, mark-vieira approved these changes

2019-03-04 06:37 UTC, merged