Edits to text in API Conventions docs
elastic/elasticsearch pull request #39001
Opened 2019-02-16 17:39 UTC by dmeiss

Minor edits to phrasing, punctuation, capitalization, and formatting.

2019-02-18 06:51 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2019-02-18 06:51 UTC, danielmitterdorfer commented
@elasticmachine test this please

2019-02-18 08:51 UTC, danielmitterdorfer requested changes
Thanks for these fixes @dmeiss. The changes look mostly fine to me but I left one remark about an incorrect multiplier. Can you please remove the "s" multiplier?

2019-02-18 08:51 UTC, danielmitterdorfer commented on docs/reference/api-conventions.asciidoc
> +`s`::  Single
The `s` suffix is not recognized by Elasticsearch (see also https://github.com/elastic/elasticsearch/blob/869de3f160a727fedf2eb8dc41713e9dce24ba5f/server/src/main/java/org/elasticsearch/common/unit/SizeValue.java#L170-L197) so this needs to be an empty string.

2019-02-18 13:45 UTC, dmeiss commented
Made requested changes. Have a question though about how that empty string should be represented. It’s currently `` but I’m wondering if it should be “” instead.

2019-02-18 16:53 UTC, danielmitterdorfer commented
> Have a question though about how that empty string should be represented. It’s currently `` but I’m wondering if it should be “” instead.

On second thought we should just remove the entire line. I doubt that it helps anybody if we document that if no multiplier is specified, we treat the value as is. I think this is expected behavior anyway.

2019-02-18 17:16 UTC, dmeiss commented
I agree. Would you like me to go ahead & remove it?

2019-02-18 18:36 UTC, dmeiss commented
Went ahead & removed the "single" line

2019-02-19 07:01 UTC, danielmitterdorfer approved these changes
Thanks! Looks good to me.

2019-02-19 07:01 UTC, danielmitterdorfer commented
@elasticmachine test this please

2019-02-20 09:37 UTC, merged