Move some token filter migration notes
elastic/elasticsearch pull request #39072
Opened 2019-02-18 19:54 UTC by cbuescher

The removal of the "nGram" and "edgeNGram" token filter was filed in a new
migrate_8_0/mappings.asciidoc document but it should better be in an
analysis.asciidoc section and file.

2019-02-18 19:54 UTC, elasticmachine commented
Pinging @elastic/es-search

2019-02-18 19:59 UTC, cbuescher commented
Just a small correction to #38911.

2019-02-19 10:10 UTC, jimczi requested changes

2019-02-19 10:10 UTC, jimczi commented on docs/reference/migration/migrate_8_0.asciidoc
> -* <<breaking_80_mappings_changes>>
We have entries in this file now so it should be preserved.

2019-02-19 10:10 UTC, jimczi commented on docs/reference/migration/migrate_8_0.asciidoc
> -include::migrate_8_0/mappings.asciidoc[]
Same here

2019-02-20 21:31 UTC, cbuescher commented
@jimczi I added the changes you asked for

2019-02-26 13:37 UTC, javanna approved these changes

2019-02-26 14:02 UTC, merged