Remove Unused Parameter from Buffer Slice Method
elastic/elasticsearch pull request #39106
Opened 2019-02-19 10:57 UTC by original-brownbear

* We're always slicing from the current index in all callers of this method (the tests that pass `0` have index `0` set as well) => removed the parameter to make the logic a little easier to follow

2019-02-19 10:57 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-02-19 17:13 UTC, Tim-Brooks requested changes
I am opposed to renaming the `sliceBuffersFrom` method to `slice`. I think that is not descriptive of what the method does. And is generally very different than how we use `BytesReference#slice(from, length)`.

As to the fact that `sliceBuffersFrom` and `sliceBuffersTo` always using the index. This approach came from @s1monw initial feedback when this was introduced. https://github.com/elastic/elasticsearch/pull/27551#discussion_r154876718 I do not know if his opinion has changed since then. But he should probably comment here.

We can still look at introducing a `slice(from, length)` method. I just did not do that at the time because, as you are noticing, our access patterns are very basic and if we had that method we would always use it as:

`buffer.slice(0, buffer.getIndex())` and `buffer.slice(buffer.getIndex(), buffer.length() - buffer.getIndex())`

2019-04-03 14:03 UTC, tbrooks8 commented
Anymore thoughts here? As I mentioned, I am fine with the removal of the index parameter as long as we retain descriptive names. @s1monw - I think the question about where we move forward with the removal of the index parameter depends on your thoughts as you (I think) wanted the parameter when we first introduced it?

I also am fine with moving to a method to like: `slice(offset, length)`. The biggest issue with that is if we are slicing with an offset > 0 we cannot random access to the correct page as we are using an `ArrayDeque`. That is why we using a descending iterator in the `sliceBuffersFrom` method.

2019-04-03 16:45 UTC, original-brownbear commented
I think my thoughts are still:

1. I kind of like the naming. We are doing something analogous to `java.nio.ByteBuffer#slice()` (which gives you current position to limit) aren't we? => At least to me it felt natural naming wise.
2. We probably shouldn't have more degrees of freedom on this kind of method than we're actually using. If we aren't ever using anything but the current position as the bound here, why hide possible future optimizations by allowing to pass anything else?

2020-05-27 12:11 UTC, ywelsch commented
@original-brownbear do you still want to get this one in? Should we mark it team-discuss in case there are disagreements on how to proceed?

2020-05-27 12:16 UTC, original-brownbear commented
Thanks for pinging Yannick. I'll close here for now, this one is ancient and really minor. Not worth the noise right now and I'm not sure it still applies even.

2020-05-27 12:16 UTC, closed without merging