Remove MovingAverage pipeline aggregation
elastic/elasticsearch pull request #39328
Opened 2019-02-22 20:28 UTC by polyfractal

This was deprecated in 6.4.0 and for the entirety of 7.0.  Removed in 8.0 :)

2019-02-22 20:28 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo

2019-03-19 10:16 UTC, iverase requested changes
LGTM

2019-03-19 10:17 UTC, iverase approved these changes

2019-03-19 15:35 UTC, polyfractal commented
Thanks @iverase! :heart: 

Merging master just to make sure nothing has changed since this went up.

2019-03-19 17:35 UTC, polyfractal commented
@elasticmachine run elasticsearch-ci/1

2019-03-19 19:31 UTC, merged