Use default discovery implementation for single-node discovery
elastic/elasticsearch pull request #40036
Opened 2019-03-14 08:54 UTC by ywelsch

Switches "discovery.type: single-node" from using a separate implementation for single-node discovery to using the existing standard discovery implementation, with two small adaptions:
- auto-bootstrapping, but requiring `initial_master_nodes` not to be set.
- not actively pinging other nodes using the Peerfinder
- not allowing other nodes to join its single-node cluster (if they have e.g. been set up using regular discovery and connect to the single-disco node).

2019-03-14 08:54 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-03-20 08:14 UTC, DaveCTurner requested changes
I think we can improve our handling of the case where this node used to be part of a larger cluster and has since been restarted in `single-node` mode, in which it will no longer be able to form a cluster. For instance, the `Coordinator` could check this in `doStart()` and throw an exception if it'll never obtain a quorum.

I think we should also refuse to start if `node.master: false`.

I think both of the above need a mention in the breaking changes docs.

~I would also like to reject `PeersRequest`s from other nodes; today we respond normally and this means that other nodes' `ClusterFormationFailureHelper`s will report that they have "discovered" this node (in amongst all the exceptions about being unable to join it).~ (edit - see [below](https://github.com/elastic/elasticsearch/pull/40036#issuecomment-474737169))

2019-03-20 08:14 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/coordination/Coordinator.java
> +            joinCallback.onFailure(new IllegalStateException("cannot join node with single-node discovery"));
Suggest `cannot join node with [discovery.type] set to [single-node]` so that it's clearer what setting to look for.

2019-03-20 08:41 UTC, DaveCTurner commented
> I would also like to reject PeersRequests from other nodes; today we respond normally and this means that other nodes' ClusterFormationFailureHelpers will report that they have "discovered" this node (in amongst all the exceptions about being unable to join it).

Rejecting `PeersRequest`s isn't sufficient for this: if another node has our transport address then it'll connect to us, handshake, and add us to its known peers list without any further checks. I think we'd need to do something like only exposing known peers once they've responded to a `PeersRequest`.

2019-03-20 09:19 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/cluster/coordination/ClusterBootstrapService.java
> +                throw new IllegalArgumentException("setting [" + INITIAL_MASTER_NODES_SETTING.getKey() +
I did not want to break existing behavior in this PR, hence only adding validation for a newly introduced setting.

2019-03-20 09:35 UTC, ywelsch commented
> I think we can improve our handling of the case where this node used to be part of a larger cluster and has since been restarted in single-node mode, in which it will no longer be able to form a cluster. For instance, the Coordinator could check this in doStart() and throw an exception if it'll never obtain a quorum.

It's an extra check in Coordinator for a super-edge case. I'm not sure how much that buys us (additional code to maintain vs slightly better error reporting), so just want to ask again if you think this is really worth pursuing.

> I think we should also refuse to start if node.master: false.

Again, extra check for an edge case, and covered by `ClusterFormationFailureHelper`.

> I think both of the above need a mention in the breaking changes docs.

I disagree and think this should be treated as a bug fix.

2019-03-20 10:04 UTC, DaveCTurner commented
> It's an extra check in Coordinator for a super-edge case. I'm not sure how much that buys us (additional code to maintain vs slightly better error reporting), so just want to ask again if you think this is really worth pursuing

Yes, I think the improvement in the error reporting is worth it. Bootstrap checks continue to cause confusion, and if someone tries to disable the bootstrap checks by moving to single-node discovery after the cluster has formed then I think that keeping the node running despite a hopeless situation is going to add to the confusion.

> Again, extra check for an edge case, and covered by `ClusterFormationFailureHelper`.

Similarly, keeping the node running in a hopeless situation is confusing. The log message would say `master not discovered yet: discovery will continue using [...] from hosts providers...` which is not true.

2019-03-27 13:32 UTC, DaveCTurner approved these changes
LGTM

2019-03-27 17:48 UTC, merged