Add SORTED_NUMERIC type for NumberFieldType
elastic/elasticsearch pull request #40187
Opened 2019-03-19 02:58 UTC by wuyunfeng

Since `MappedFieldType` comment remove this `docvalues` flag and use `docValuesType`,  we should use `docValuesType()` to decide which this Field has docvalue. But when encounter the number field, obtain the `MappedFieldType` and use `docValuesType` method return `DocValuesType.NONE`, I think this is so mistake.  I find all number field in Elasticsearch use `SORTED_NUMERIC` type, so adding it to the final class `NumberFieldType`, does it OK?  When added this, our plugin works well.

2019-03-19 04:33 UTC, elasticmachine commented
Pinging @elastic/es-search

2019-03-19 12:06 UTC, mayya-sharipova commented
@wuyunfeng  Thank you for your PR.  We indeed need to change for a check to `docValuesType` instead of `hasDocValues`? Would you have time and be interested to do more refactoring along this lines?  For example, to modify `MapperFieldType::hasDocValues()` to return if docValuesType == DocValuesType.NONE?

2019-03-19 13:51 UTC, wuyunfeng commented
@mayya-sharipova Thanks for your reply. I would like to try it. But then，maybe some modifications involving lot of refactor?

2019-03-20 21:12 UTC, mayya-sharipova commented
@wuyunfeng Right, it may, but from what I can judge it may touch a lot of files, but modifications in each of the file will be small.  We can also break the change into several PRs.

2019-03-21 11:08 UTC, wuyunfeng commented
@mayya-sharipova  maybe should have a schedule... ^o^, divided into serveral PRs is a good idea

2019-03-25 08:59 UTC, wuyunfeng commented
@mayya-sharipova  I modify some core MapperFieldType first,  can you give your review message?  Adopt your advice  divide into serveral PRs

2019-03-26 01:01 UTC, wuyunfeng commented
ping @mayya-sharipova

2019-03-26 18:03 UTC, mayya-sharipova requested changes
@wuyunfeng  Thank you for continuing your work on this PR.  Good changes.  
The main comment is that  I think we don't need `doSetDocValueType` in any of the files.

2019-03-27 02:16 UTC, wuyunfeng commented on server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java
> +            doSetDocValueType(docValues);
Good idea, I will put this line into  MapperFieldType setHasDocValues(). BTW,  delete `docValues` flag  is OK

2019-03-27 05:27 UTC, wuyunfeng commented
@mayya-sharipova  some XXXAggregatorTests may use the XXXFieldType() constructor directly, and the setDocValue(true),  What should we change for this scenario?

2019-03-27 22:22 UTC, mayya-sharipova commented
@wuyunfeng Thanks a lot, this is a good change. And modifying tests is great. I have started the tests to see that we have not broken anything.

2019-03-27 22:22 UTC, mayya-sharipova commented
@elasticmachine  test this please

2019-03-28 04:37 UTC, wuyunfeng commented
@mayya-sharipova  Thanks for your comment. I only modify a fraction of XXXTest file but not all, I find lots of test files use the XXXFieldType constructor directly then invoke the setHasDocValues(true), in this way not set the docValueType.  Maybe need to modify the XXXAggregatorTest and some other files
BTW,  I want to remove the `docValues` flag from the `MappedFieldType`, what do you think?

2019-03-28 17:55 UTC, mayya-sharipova commented
@wuyunfeng  I would suggest let's keep the changes for this PR as minimal as possible. 
For this PR we can only keep changes for:
-  all *FieldMapper.java files
- MappedFieldType.java
- and only *Tests.java files that break (for example keep the changes to `KeywordFieldMapperTests.java`, but don't change `*AggregatorTests.java` files if they don't break.  All  tests `*AggregatorTests.java` should pass, so let's not modify them in this PR).

In the subsequent PR, we can remove `docValues` field from `MappedFieldType`

2019-03-29 00:06 UTC, wuyunfeng commented
@mayya-sharipova OK, I will restore *AggregatorTests.java later

2019-03-30 13:33 UTC, wuyunfeng commented
@mayya-sharipova  I have rollbacked xxxAggregatorTests, I think KeywordFieldMapperTests should fail without changing

2019-03-31 12:02 UTC, mayya-sharipova commented
@elasticmachine test this please

2019-03-31 14:49 UTC, wuyunfeng commented
@mayya-sharipova  some UT fails seems not to related with this PR, and somewhere needed to be changed?

2019-04-01 15:22 UTC, wuyunfeng commented
@elasticmachine test this

2019-04-01 20:47 UTC, mayya-sharipova commented
@elasticmachine test this please

2019-04-02 07:50 UTC, wuyunfeng commented
@mayya-sharipova  
1. Some FieldMapper  ` fields.add(new Field(fieldType().name(), value, fieldType()) ` resulting in NullPointerException when index doc,  `noDocValueFieldType()` getting rid of the defalut docValue enable.
2.  Some UnitTest using clone method generate FieldType,  `this.docValues = ref.hasDocValues();` resulting `docValues` inconsistency

2019-04-03 14:13 UTC, wuyunfeng commented
@mayya-sharipova

2019-04-04 11:01 UTC, mayya-sharipova commented
@wuyunfeng  Sorry for a delay. This turned out to be more complicated than I thought. 
 I will need to discuss this change with my team. I will get back to you next wee

2019-04-05 03:08 UTC, wuyunfeng commented
@mayya-sharipova 
 

> Can you please also explain why do you need docValuesType for your plugin?
    
   Our plugin `Doris On Elasticsearch` would prefer retrieve value from  `docvalue` , you can see this issue for Doris（incubator-doris）: [Doris On Elasticsearch](incubator-doris) , Just like elasticsearch-hadoop for spark analysis. In Our first version we write native Luece Query for `query phase`, and use the origin `Fetch Phase`,  `Doris On Elasticsearch` needs to know wheather fields has `docvalue`, if has we would retrieve the value from the `docvalue` through add this field to  `docvalue_fields: [ fieldA, fieldB]` context.  
     Just as you see, when i use `MappedFieldType:docValues` , `Remove this TODO item` caught my attention. If  using this `docValues`, I worried Elasticseach Team will remove this value in future release version. I decided to use `docValuesType` instead of `docValues`, until `docValuesType` always return `DocValuesType.NONE`.

> The problem is that one Elasticsearch MappedFieldType usually corresponds to two Lucene's FieldType - as we create 2 fields: 1 must be with some DocValues and another must be with DocValuesType.NONE.

   Yeah,  use different format value for `index field`, `store field` and `doc_value field`  from same `Field` is a great idea, so I add `noDocValueFieldType ()` method to strip the `docValueType` for normal field.

> We have two potential resolutions: 1. Remove this TODO item, keep the code and MappedFieldType:docValues as is  2. Something suggested in this PR, set in all *FieldMapper in Defaults the corresponding docValuesType FIELD_TYPE.setDocValuesType, but when creating a usual field (not DocValuesField) make sure that it is created with a fieldType where DocValuesType.NONE

   1.  `docValuesType` would still return` DocValuesType.NONE`, maybe mistaking another guys in the future. In this way, we should add note comment for `docValuesType`  when `Remove this TODO item`
  2.  maybe `noDocValueFieldType ` is not a good resolution but can make sure ` DocValuesType.NONE` assign  normal field, maybe the function name need to be changed or the location need to change.

2019-04-08 06:37 UTC, wuyunfeng commented
@mayya-sharipova another alternative way, can set the DocValueType when add DocValueField for this field

2019-04-08 15:41 UTC, wuyunfeng commented
@mayya-sharipova

2019-04-09 09:42 UTC, jpountz commented
The TODO about using docValueType rather than the `docValues` flag made sense at that time when things were simpler than now. However I think a better option now would be to decouple MappedFieldType from Lucene's FieldType. It is a bit of a hack today, but this is almost what we started doing for numeric fields by using `indexOptions` to figure out whether a field is indexed even though numeric fields are no longer using the inverted index, they are using points.

2019-04-09 16:31 UTC, closed without merging

2019-04-09 16:41 UTC, wuyunfeng commented
@mayya-sharipova it does not matter. enjoy to discuss with you ^o^