[DOCS] Clarify Recovery Settings for Shard Relocation
elastic/elasticsearch pull request #40329
Opened 2019-03-21 19:42 UTC by jrodewig

- Adds a sentence clarifying that recovery settings also apply to shard relocation
- Rewrites introduction to highlight when peer recovery occurs
- Rewrites and reformats setting descriptions for scannability and clarity

Resolves #14539 🤞

2019-03-21 19:42 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-03-21 20:34 UTC, jrodewig commented
please retest this

2019-03-21 20:36 UTC, jrodewig commented
retest this please

2019-03-21 21:05 UTC, jrodewig commented
retest this please

2019-03-22 00:49 UTC, jrodewig commented
retest this please

2019-03-22 00:58 UTC, jrodewig commented
retest this please

2019-03-27 13:40 UTC, jrodewig commented
Hi @ppf2

Let me know if this addresses your concerns from #14539.

I also included some other rewrites for clarity, but I can break those out into another PR if wanted. Thanks!

2019-04-04 17:34 UTC, ywelsch requested changes
While we're already touching these docs here, maybe cross-link to `[[cat-recovery]]` which provides progress information about recoveries.

2019-04-04 17:34 UTC, ywelsch commented on docs/reference/modules/indices/recovery.asciidoc
> +* Restores a <<modules-snapshots, snapshot>>
recovery from snapshot is different to peer recovery and has different settings

2019-04-04 17:34 UTC, ywelsch commented on docs/reference/modules/indices/recovery.asciidoc
> +You can use the following _expert_ settings to manage resources for peer
The first setting (`indices.recovery.max_bytes_per_sec`) is not an expert-level setting and is quite often adjusted. Let's separate it from the second one which should be attributed as expert-level and will very rarely need adjustment.

2019-04-04 19:43 UTC, jrodewig commented
Thanks for the review @ywelsch! I addressed your feedback in commit d09877e.

Let me know if you have any other concerns.

2019-04-04 19:47 UTC, jrodewig commented
retest this please

2019-04-24 16:26 UTC, jrodewig commented
@ywelsch Let me know if these changes look okay to you.

Happy to close or rewrite if needed.

2019-04-26 14:00 UTC, ywelsch approved these changes
Great, thank you! Sorry for the late reply here, I was on vacation.

2019-04-26 14:23 UTC, jrodewig commented
No worries! Thank you!

2019-04-26 14:23 UTC, merged