Supporting automatic release of index blocks. Closes #39334
elastic/elasticsearch pull request #40338
Opened 2019-03-22 05:30 UTC by alex101101

Automatically remove INDEX_READ_ONLY_ALLOW_DELETE_BLOCK block on index once node(s) disk usage at least 5% below the flood_stage watermark and below the high watermark. Feature disabled by default.

2019-03-22 07:54 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-04-27 06:09 UTC, DaveCTurner requested changes
Thanks @alex101101. My main concern with this implementation is that it might release the block if a node that's above the flood stage threshold failed to respond to the stats request sent by the `InternalClusterInfoService`, because then it wouldn't be included in the disk usage statistics. I think it'd be better to only release this block if we are _certain_ that every assigned shard is definitely on a node below the threshold.

I left a few more comments on the implementation, but I haven't been through the tests in detail yet.

2019-04-27 06:09 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdSettings.java
> +        return (this.freeBytesThresholdHigh != null && this.freeBytesThresholdFloodStage != null);
Is this needed? I can't see that `this.freeBytesThresholdHigh` is ever null, and `this.freeBytesThresholdFloodStage` should only be null during initialisation, which I think I'd prefer to fix by setting it to `new ByteSizeValue(0, ByteSizeUnit.BYTES)` first.

2019-04-27 06:09 UTC, DaveCTurner commented
Also please don't force-push to PRs, it makes it much harder to keep track things.

2019-04-30 13:59 UTC, DaveCTurner commented on docs/reference/modules/cluster/disk_allocator.asciidoc
> +`cluster.routing.allocation.disk.auto_release_index_enabled`::
> I'm going to check this with the team to be certain that there are no objections.

We discussed this today and agreed to make this the only behaviour in future: this should be the only option in 8.0 and should be the usual behaviour in 7.x, although we would support disabling it with a system property, `es.auto_release_flood_stage_block` in 7.x.

2019-05-18 14:49 UTC, Bukhtawar commented
>My main concern with this implementation is that it might release the block if a node that's above the flood stage threshold failed to respond to the stats request sent by the InternalClusterInfoService, because then it wouldn't be included in the disk usage statistics. I think it'd be better to only release this block if we are certain that every assigned shard is definitely on a node below the threshold.

@DaveCTurner
There are a couple of thing that I can think of
1. Have `DiskUsage` maintain the last update time and we allow release up to a minutes' staleness since even today there can be a GC pause between node stats response and the `DiskThresholdMonitor` setting/unsetting the block

2. Have `ClusterInfo` maintain a flag indicating if all the nodes responded. This could be used for releasing the block

2019-05-28 11:34 UTC, DaveCTurner commented
Superseded by #42559.

2019-05-28 11:34 UTC, closed without merging