Remove Gradle deprecation warnings
elastic/elasticsearch pull request #40449
Opened 2019-03-26 11:49 UTC by atorok

Turns out that without the explicit project, some how the deprecated
properties were being red.
With this change we have no Gradle deprecation warnings.

2019-03-26 11:49 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2019-03-26 17:20 UTC, mark-vieira requested changes

2019-03-26 17:20 UTC, mark-vieira commented on build.gradle
> +if (project.properties.get("org.elasticsearch.acceptScanTOS", "false") == "true") {
We should never be directly accessing `properties` in any case. This is not a Gradle API, it's a general Groovy mechanism. It just happens to work with Gradle properties via `propertyMissing()`.

Instead we should use the available Gradle APIs here. I'd change this to something like this:
```
if (Boolean.valueOf(project.findProperty('org.elasticsearch.acceptScanTOS') ?: "false"))
```

2019-03-28 17:01 UTC, rjernst approved these changes
The change to getting the property seems fine, but I've seen a lot of these conversions to Boolean parsing recently. This method is lenient, allowing anything to represent false. We should add our own static helper method like we have in ES (orthogonal to this change).

2019-03-28 20:56 UTC, mark-vieira approved these changes
👍

2019-03-29 06:10 UTC, merged