Mark notable breaking changes for 7.0
elastic/elasticsearch pull request #40478
Opened 2019-03-26 16:33 UTC by jasontedor

This commit adds a tag for each breaking change that could be considered notable.

2019-03-26 16:34 UTC, jasontedor commented
@eskibars @jpountz This is my take on what is considered notable breaking changes. I am happy to hear your thoughts as well. I did try to keep this list not long so if we do want to add more to it, I think we should also consider taking away some of the items that I have already marked as notable, otherwise it will be laundry list.

2019-03-26 17:07 UTC, jpountz reviewed
I left comments around whether some breaking changes are actually notable but in general this looks good to me. I reviewed the list of breaking changes that we document and didn't find one that I would put on the list that you didn't.

2019-03-26 17:07 UTC, jpountz commented on docs/reference/migration/migrate_7_0/settings.asciidoc
> +//tag::notable-breaking-changes[]
I'm wondering how many users are disabling HTTP, should we keep it a non-notable breaking change?

2019-03-26 17:07 UTC, jpountz commented on docs/reference/migration/migrate_7_0/settings.asciidoc
> +//tag::notable-breaking-changes[]
This one won't fail any upgrade if my understanding is correct, so I'd be leaning towards removing it.

2019-03-26 17:07 UTC, jpountz commented on docs/reference/migration/migrate_7_0/logging.asciidoc
> +//tag::notable-breaking-changes[]
I'd maybe put these changes around JSON log files in the notable highlights but not in the notable breaking changes?

2019-03-27 00:17 UTC, eskibars requested changes
I left a few comments.  It looks like there is one close-tag without an open.  There are 2 others that I would consider adding:
1) search.max_buckets: Based on the number of conversations I've had with users that haven't configured this and had bad things happen, I suspect we'll want to make this prominent.
2) The security realm type prefix requirements.  We've got the non-prefixed format in a lot of docs/blogs/examples, even recent ones (e.g. https://www.elastic.co/guide/en/elasticsearch/reference/6.7/security-settings.html#realm-settings) and this could be very surprising and frustrating if users aren't aware of it.

2019-03-27 11:18 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-03-27 15:08 UTC, lcawl commented
You can preview this content in the Installation and Upgrade Guide here: 
https://doc-review-63bf6.firebaseapp.com/x4/elastic-stack-breaking-changes.html#elasticsearch-breaking-changes

2019-03-27 15:13 UTC, lcawl commented on docs/reference/migration/migrate_7_0/search.asciidoc
> +//tag::notable-breaking-changes[]
There's a <1> in the example in this section that isn't explained.

2019-03-27 15:21 UTC, jasontedor commented
@eskibars I've responded to your feedback. I added the two that you suggested, and removed the documentation distribution change.

2019-03-27 20:25 UTC, eskibars approved these changes
Thanks @jasontedor .  This LGTM

2019-03-27 20:39 UTC, merged