Update eager-global-ordinals.asciidoc
elastic/elasticsearch pull request #40620
Opened 2019-03-28 22:05 UTC by Leaf-Lin

Adding clarification on global ordinals.
Global ordinals are loaded as-needed by default as opposed to up-front. setting `eager_global_ordinals: true` will load them up-front and keep them up-to-date, as opposed to lazy loading when needed.
eager_global_ordinals is false by default, just trying to clarify that bit.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2019-03-28 22:17 UTC, Leaf-Lin commented
I think the doc can be further improved, but I'm not sure how. Here's some external [blogs](https://alexmarquardt.com/how-to-tune-elasticsearch-for-aggregation-performance/) gave a good explanation:

Enable eager global ordinals to improve the performance of high-cardinality terms aggregations
The performance of terms aggregations on high-cardinality fields (fields with thousands or millions of possible unique values) may become slow and unpredictable in-part because by default global ordinals are lazily built on the first aggregation that occurs since the previous refresh as described [here](https://github.com/elastic/elasticsearch/issues/19780).

Building global ordinals eagerly should improve such aggregations and make response times more consistent, as the related data structure will be created when segments are refreshed, as opposed to the first query after each refresh.

Note that if global ordinals are eagerly built, this will impact write performance because new global ordinals will be created on every refresh. To minimize the additional workload caused by frequently building global ordinals due to frequent refreshes, increase the refresh interval.

2019-03-29 09:22 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo

2019-03-29 09:23 UTC, elasticmachine commented
Pinging @elastic/es-search

2019-03-30 14:52 UTC, mayya-sharipova commented
@Leaf-Lin Thanks for your contributions.

I actually think that the original wording that we had in the documentation is more clear and specific than the one you suggested.  You suggested as "as-needed" but it is not clear when they are needed.  If you want, we can incorporate both your suggestions and our original statement to something like this:

"global ordinals are loaded as needed for a search or aggregation request..."

Also, we can just copy text from external blogs.  If you have some original content to enhance documentation, please go ahead. You contribution is very much welcome.

2019-03-30 14:55 UTC, mayya-sharipova requested changes
@Leaf-Lin Thanks for your contributions.

I actually think that the original wording that we had in the documentation is more clear and specific than the one you suggested. You suggested as "as-needed" but it is not clear when they are needed. If you want, we can incorporate both your suggestions and our original statement to something like this:

"global ordinals are loaded as needed for a search or aggregation request..."

Another note - please keep the text wrapped around 80 columns.

Also, we can NOT just copy text from external blogs. If you have some original content to enhance documentation, please go ahead. You contribution is very much welcome.

2019-04-01 04:13 UTC, Leaf-Lin commented
Hi,

I'm not suggesting to copy/paste content from other blogs, but I found the other blog seems to explain more clearly about what the setting is about.
Also, here's another comment from our internal team:
https://discuss.elastic.co/t/global-ordinals-performance-and-size-on-heap/158320/2
```
The doc is maybe a bit optimistic and could mention workarounds if loading is slow or if the searcher is refreshed often (each refresh of the main searcher invalidates the loaded global ordinals).
```

I think the doc can be improved to incorporate more clarity, but I'm not in the position to do so.

2019-04-01 10:21 UTC, mayya-sharipova commented
@Leaf-Lin  You are right, the doc can be improved. And  we have an [issue](https://github.com/elastic/elasticsearch/issues/37092) for it.
Would like to continue to work on this small PR and address the requested changes?

2019-04-03 23:11 UTC, Leaf-Lin commented
Ah, I didn't realised this has been raised. Maybe we can close this one, let's just focus on that [issue](https://github.com/elastic/elasticsearch/issues/37092). 
Some of the info posted here might be useful though.

2019-04-03 23:11 UTC, closed without merging