Validate snapshot lifecycle policies
elastic/elasticsearch pull request #40654
Opened 2019-03-29 20:32 UTC by dakrone

(This is a PR against the `snapshot-lifecycle-management` branch)

With the commit, we now validate the content of snapshot lifecycle policies when
the policy is being created or updated. This checks for the validity of the id,
name, schedule, and repository. Additionally, cluster state is checked to ensure
that the repository exists prior to the lifecycle being added to the cluster
state.

Part of #38461

2019-03-29 20:32 UTC, elasticmachine commented
Pinging @elastic/es-core-features

2019-04-01 23:00 UTC, AthenaEryma requested changes
Left some minor comments, otherwise looks good.

2019-04-01 23:02 UTC, dakrone commented on x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/snapshotlifecycle/SnapshotLifecycleService.java
> +    public static void validateRepositoryExists(final String repository, final ClusterState state) {
I was thinking about that, I should be able to change it to a valid repo, but list `"indices": ["foo"], "ignore_unavailable": false` and then it should fail if the "foo" index is not available.

2019-04-01 23:04 UTC, gwbrown commented on x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/snapshotlifecycle/SnapshotLifecycleService.java
> +    public static void validateRepositoryExists(final String repository, final ClusterState state) {
Oh, cool. I'll make that change in my PR before it gets merged.

2019-04-02 19:15 UTC, dakrone commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/snapshotlifecycle/SnapshotLifecyclePolicy.java
> +        // ID validation
Yeah not a bad idea, I copied this from ILM's validation for now.

2019-04-02 19:35 UTC, dakrone commented
Thanks for taking a look Gordon, I pushed commits addressing your comments

2019-04-02 19:40 UTC, AthenaEryma approved these changes
LGTM!

2019-04-03 13:19 UTC, merged