Add a configuration property to ban ClusterFormationTasks
elastic/elasticsearch pull request #40700
Opened 2019-04-01 18:23 UTC by atorok

The intent is tofold:

- first, make sure what we think is converted actually is
- second, lather on, make sure that some checks in CI don't these tasks,
  so that once everything is converted we can be sure no new tests are
  added that follow the old ways

2019-04-01 18:23 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2019-04-02 01:19 UTC, mark-vieira commented
This seems a bit unnecessary to be honest. We'll also need to go and toggle this on all the respective CI builds for which the legacy method is "banned" until everything is fully migrated. I don't think we risk new usages of this leaking into the codebase given one of us reviews all build changes.

2019-04-02 01:22 UTC, mark-vieira requested changes
To be honest, this seems a bit unnecessary. I don't think we risk much new usages of this leaking into the build given we review all build changes. All the needed configuration on the Jenkins side is just another thing that we'll need to go back and remove once all this is fully migrated and removed entirely.

2019-04-02 01:22 UTC, mark-vieira commented on buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy
> +            throw new IllegalStateException("Using cluster formation tasks but these are not allowed in this build");
If we do this, we should give folks better instruction. Even so far as to say "Ping Alpar on Slack for more info" :wink:

At the very least we should point folks towards `TestClusters`.

2019-04-02 07:50 UTC, rjernst commented
I agree with @mark-vieira, this looks like overkill.

2019-04-02 11:19 UTC, closed without merging