Use alias name from rollover request to query indices stats
elastic/elasticsearch pull request #40774
Opened 2019-04-03 10:18 UTC by bizybot

In `TransportRolloverAction` before doing rollover we resolve
source index name (write index) from the alias in the rollover request.
Before evaluating the conditions and executing rollover action, we
retrieve stats, but to do so we used the source index name
resolved from the alias instead of what is in the request.
This fails when the user is assigned a role with index privilege on the
alias instead of the concrete index. This commit fixes this by using
the alias from the request.

Closes #40771

2019-04-03 10:18 UTC, elasticmachine commented
Pinging @elastic/es-security

2019-04-03 11:21 UTC, elasticmachine commented
Pinging @elastic/es-core-features

2019-04-04 06:34 UTC, albertzaharovits approved these changes
I am game with the main code change.
I would love if you'd add an `IntegTest` so that we don't catch authorization errors in Rest tests...

However, I think we should make the Rollover action use the client for index and alias creation. WDYT?

2019-04-04 11:02 UTC, albertzaharovits commented
Ah, I'm sorry, I mean `createIndexService.createIndex` to be replaced with `client.indices().create()` . I think the user of the rollup action should necessitate the create index privilege, at least this is my perception of the authorization with "action granularity".
This is a discussion suggestion for an issue as a follow-up, not to be addressed here.

2019-04-05 02:16 UTC, tvernum commented
@talevy Are you able to review the (1 line) change to the transport action? It looks like you were the last person to make actual functional changes to that action, and I'd appreciate a review from someone who knows that code better than we do.

2019-04-05 15:54 UTC, talevy reviewed
I still need to test my comments, but I figure sending this out earlier is better. let me know if 
what I said makes sense!

2019-04-05 15:54 UTC, talevy commented on server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java
> +        client.admin().indices().prepareStats(rolloverRequest.getAlias()).clear().setDocs(true).execute(
I will have to check, but I'm not sure this is the same thing.

will stats for shards of all the matched read-aliases be returned in this case? For example,
If the alias points to multiple indices, then we may be checking stats of indices that are of no 
concern to us.

2019-04-05 15:54 UTC, talevy commented on x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/31_rollover_using_alias.yml
> +"Test rollover, index via write alias of index":
can we add a test that has an alias that references multiple indices, where one of them is the write index.

2019-04-05 16:34 UTC, talevy requested changes
I just ran this check to assert my theory:

```
PUT alpha
{
  "aliases": {
    "my_alias": {
      "is_write_index": true
    }
  }
}

PUT beta
{
  "aliases": {
    "my_alias": {
      "is_write_index": false
    }
  }
}

PUT alpha/_doc/1?refresh
{
  "foo": "bar"
}

PUT beta/_doc/1?refresh
{
  "foo": "bar"
}

POST /my_alias/_rollover/new_index?dry_run
{
  "conditions": {
    "max_docs":  2
  }
}
```

this returns an incorrect rollover evaluation (the write index "alpha" only has one document):

```
{
  "acknowledged" : false,
  "shards_acknowledged" : false,
  "old_index" : "alpha",
  "new_index" : "new_index",
  "rolled_over" : false,
  "dry_run" : true,
  "conditions" : {
    "[max_docs: 2]" : true
  }
}
```

I think the additional change that would make this work would be this:

```diff
@@ -249,7 +249,7 @@ public class TransportRolloverAction extends TransportMasterNodeAction<RolloverR
 
     static Map<String, Boolean> evaluateConditions(final Collection<Condition<?>> conditions, final IndexMetaData metaData,
                                                     final IndicesStatsResponse statsResponse) {
-        return evaluateConditions(conditions, statsResponse.getPrimaries().getDocs(), metaData);
+        return evaluateConditions(conditions, statsResponse.getIndex(metaData.getIndex().getName()).getPrimaries().getDocs(), metaData);
     }
```

The issue is that the code was looking at the total DocStats of all the indices returned in the stats-response. This change should make it so that we are looking at the sourceIndex only. The non-docstats condition (index age) is done on the correct IndexMetaData of the sourceIndex, so this should not be a problem.

2019-04-05 16:42 UTC, talevy commented on x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/31_rollover_using_alias.yml
> +"Test rollover, index via write alias of index":
I take back this recommendation. This check should be done in the original rollover tests. security is unrelated

2019-04-05 16:45 UTC, talevy commented on server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java
> +        client.admin().indices().prepareStats(rolloverRequest.getAlias()).clear().setDocs(true).execute(
update: this does have semantic differences given how the stats response is interpreted. Looks like a solution to correct this exists (in separate review comment)

2019-04-08 01:44 UTC, talevy commented on server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java
> +        client.admin().indices().prepareStats(rolloverRequest.getAlias()).clear().setDocs(true).execute(
That is a good question. Although it is unfortunate that we are collecting stats on potentially a lot of indices/shards, I am not sure performance is of the upmost importance for this API. This API is a management api that already takes a while due to allocation lag, etc. 

It is good to note that this stats call would potentially hit hundreds of indices, assuming a user has daily rollover indices with ILM, but the API is designed to handle this in general, so it feels safe to do this internally here.

2019-04-08 01:55 UTC, talevy reviewed
Changes to Rollover look good to me. I'm not against 
getting another opinion regarding my comments around 
performance concerns.

Due to the difficulty of controlling time for the additional test in RolloverIT, 
what do you think of moving these additional tests as unit tests 
in `TransportRolloverActionTests`. That way we can control the 
state of the indices such that only the write-index meets the 
relevant criteria (max_age, max_docs, max_size).

2019-04-08 18:25 UTC, talevy approved these changes
LGTM

2019-04-15 07:26 UTC, tvernum approved these changes
LGTM

2019-04-16 08:29 UTC, merged