Remove string usages of old transport settings
elastic/elasticsearch pull request #40818
Opened 2019-04-03 21:56 UTC by tbrooks8

This is related to #36652. We intend to deprecate a number of transport
settings in 7.x and remove them in 8.0. This commit removes the string
usages of these settings.

2019-04-03 21:56 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-04-03 21:57 UTC, tbrooks8 commented
This commit will go to 7.1 and 8.0. There should not be any backwards compatibility issues because the new settings are on 6.7.

2019-04-04 12:39 UTC, ywelsch requested changes
Thanks for the clean-up. I've left 2 comments.

2019-04-04 12:39 UTC, ywelsch commented on buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
> +        defaultConfig.put("transport.port", "0");
do we need to conditionally set this based on version as well?

2019-04-04 12:39 UTC, ywelsch commented on client/sniffer/src/test/resources/create_test_nodes_info.bash
> +transport.port: ${transport_port}
this  script runs old versions of elasticsearch (2.0.0, 5.0.0, 6.0.0) so should not be updated

2019-04-04 15:47 UTC, ywelsch approved these changes
LGTM

2019-04-04 22:51 UTC, merged