Fixed synchronizing inflight breaker with internal variable
elastic/elasticsearch pull request #40878
Opened 2019-04-04 23:52 UTC by 111andre111

Tested http://localhost:9200/_nodes/stats/breaker
and found out that the in flight requests are divided with underscores.
This is wrong some versions already.
This is a replacement of pull request https://github.com/elastic/elasticsearch/pull/40755 and corrects the printed value in elasticsearch.

2019-04-05 08:26 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2019-04-05 08:51 UTC, danielmitterdorfer requested changes
@111andre111 thanks for the PR. Some tests are failing as a result of your change. Can you please have a look (see status checks of this PR)? Also, as I've mentioned before this is a breaking change and as such we need to include a note in the breaking changes docs. Here you can see an example how we did it for 7.0: https://github.com/elastic/elasticsearch/tree/7.0/docs/reference/migration - there is one file `migrate_7_0.asciidoc` which references the individual breaking changes. You can then create a new file for the circuit breaker changes in a subdirectory similarly to https://github.com/elastic/elasticsearch/tree/7.0/docs/reference/migration/migrate_7_0 and reference it from the main file.

2019-04-05 14:51 UTC, 111andre111 commented
Ok, got, I will try to apply these changes. Thank you for helping me out for that.

2019-07-19 21:52 UTC, 111andre111 commented
@danielmitterdorfer Would you mind to review this pull request again?
Thank you in advance.

2019-07-22 07:37 UTC, danielmitterdorfer requested changes
Thanks for iterating. I left a couple of comments.

2019-07-22 07:37 UTC, danielmitterdorfer commented on docs/reference/migration/migrate_8_0.asciidoc
> +* <<breaking_80_breaker_changes>>
There was a test failure on the [docs build](https://elasticsearch-ci.elastic.co/job/elastic+docs+elasticsearch+pull-request/152/console):

```
19:31:27 INFO:build_docs:/tmp/docsbuild/target_repo/html/en/elasticsearch/reference/master/index.x.xml:65535: element xref: validity error : IDREF attribute linkend references an unknown ID "breaking_80_breaker_changes"
```
I think this is caused by a missing include of the `breaker.asciidoc` file towards the end of this file.

Can you please double-check that all CI checks are green when you resubmit?

2019-07-22 07:37 UTC, danielmitterdorfer commented on docs/reference/migration/migrate_8_0/breaker.asciidoc
> +==== Request Circuit Breaker
This should say `In flight requests circuit breaker`. We have a *different* circuit breaker that is called "Request circuit breaker" so this is misleading.

2019-07-22 07:37 UTC, danielmitterdorfer commented on docs/reference/migration/migrate_8_0/breaker.asciidoc
> +In API documented request breaker there was change from in_flight_requests to inflight_requests, to be in line with the configuration values
How about this?

> The name of the in flight requests circuit breaker in log output and diagnostic APIs (such as the node stats API) changes from `in_flight_requests` to `inflight_requests` to align it with the name of the corresponding settings.

2019-07-29 15:25 UTC, 111andre111 reviewed
Thank Daniel,

I changed and reviewed your comments. Thank you for them, so could you please recheck again?

2019-07-30 06:48 UTC, danielmitterdorfer commented
@elasticmachine run elasticsearch-ci/2

2019-07-30 06:49 UTC, danielmitterdorfer commented
The previous test failure for `elasticsearch-ci/2` looked unrelated to me so I've retriggered a build.

2019-07-30 06:52 UTC, danielmitterdorfer approved these changes
Thanks for iterating. LGTM! 

Just a note for future PRs: It's best *not* to force-push because that preserves context and makes it clear what you've changed (thus simpler for me as a reviewer). When merging the PR you can then use [squash and merge](https://help.github.com/en/articles/about-pull-request-merges#squash-and-merge-your-pull-request-commits) so the PR's history is gone after merging and will only show up as a single commit.

2019-07-31 14:57 UTC, kwilczynski commented
Hello @danielmitterdorfer, thank you so much for your help here! Much appreciate.

@111andre111, I believe you are good to go! Great work here!

2019-08-14 19:36 UTC, kwilczynski commented
Hello @111andre111, please resolve conflicts and then merge this pull request.

Thank you!

2019-09-03 12:56 UTC, merged