Query parameter string s
elastic/elasticsearch pull request #40926
Opened 2019-04-07 02:09 UTC by hackaholic

Query parameter string s can be used for shorting on a specific column in elasticsearch, why to pipe to linux short

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2019-04-08 08:57 UTC, javanna commented
hello @hackaholic could you please sign our CLA so we can get your change in ?

2019-04-08 08:57 UTC, elasticmachine commented
Pinging @elastic/es-core-features

2019-07-04 02:57 UTC, hackaholic commented
Hi Luca,

I am not aware of CLA, can you guide me how to sign CLA?

Regards

On Mon, 8 Apr 2019 at 14:30, Elastic Machine <notifications@github.com>
wrote:

> Pinging @elastic/es-core-features
> <https://github.com/orgs/elastic/teams/es-core-features>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elastic/elasticsearch/pull/40926#issuecomment-480745574>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADjI3tbRTwXN9GsYSbIAkEZ-H9KpaHwmks5vewURgaJpZM4cghBY>
> .
>

2019-07-04 04:31 UTC, dadoonet commented
@hackaholic https://www.elastic.co//contributor-agreement

2019-07-15 09:25 UTC, javanna commented
ping @hackaholic we would like to incorporate your change but you need to sign the CLA, otherwise we can't go ahead. Thanks!

2019-07-16 11:05 UTC, hackaholic commented
Hi,
I have done the CLA. please look at the attachment.

Regards,
Kumar

On Mon, 15 Jul 2019 at 14:57, Luca Cavanna <notifications@github.com> wrote:

> ping @hackaholic <https://github.com/hackaholic> we would like to
> incorporate your change but you need to sign the CLA, otherwise we can't go
> ahead. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elastic/elasticsearch/pull/40926?email_source=notifications&email_token=AA4MRXWRVV236L2J4C7PLITP7Q7I5A5CNFSM4HECCBMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ5E4WQ#issuecomment-511331930>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA4MRXWDMAMWAIULE4LR6QDP7Q7I5ANCNFSM4HECCBMA>
> .
>

2019-07-16 11:48 UTC, javanna commented
test this please

2019-07-16 12:13 UTC, javanna commented
@elasticmachine update-branch

2019-07-16 12:15 UTC, javanna commented
@elasticmachine update branch

2019-07-16 12:15 UTC, javanna commented
test this please

2019-07-16 12:51 UTC, javanna commented on docs/reference/cat.asciidoc
> +% curl '192.168.56.10:9200/_cat/indices?v&bytes=b&s=store.size:desc'
Small comment: I think you either remove the v argument or you also need to update the following output as it does not contain the verbose output. Makes sense?

2019-08-06 10:57 UTC, javanna commented
heya @hackaholic this PR is really close to being merged. I left a small comment as part of my final review, if you could kindly address that I can then go and merge it in. Thanks!

2019-09-05 14:24 UTC, jakelandis commented
@hackaholic could you please take a look at the latest review comment ?

Also, have you signed the [CLA](https://www.elastic.co/contributor-agreement) ?

2019-10-11 12:49 UTC, martijnvg commented
Hey @hackaholic can you address Luca's comment and sign the CLA? It is important to use the same email address in CLA as in github / git commit.
This PR has been open for a while now and if there is no more activity then we have to close this PR.

2019-10-11 20:16 UTC, hackaholic commented
Hi Elastic/Elasticsearch,

Please find the attached signed CLA

Regards Kumar

On Fri, 11 Oct 2019 at 18:23, Martijn van Groningen <
notifications@github.com> wrote:

> Hey @hackaholic <https://github.com/hackaholic> can you address Luca's
> comment and sign the CLA? It is important to use the same email address in
> CLA as in github / git commit.
> This PR has been open for a while now and if there is no more activity
> then we have to close this PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elastic/elasticsearch/pull/40926?email_source=notifications&email_token=AA4MRXXWASP46XLOR5P2ZU3QOBZMBA5CNFSM4HECCBMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEA74PQI#issuecomment-541050817>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA4MRXXUEYHWUG55B3XSKPLQOBZMBANCNFSM4HECCBMA>
> .
>

2019-10-17 20:48 UTC, jrodewig commented on docs/reference/cat.asciidoc
> +% curl '192.168.56.10:9200/_cat/indices?v&bytes=b&s=store.size:desc'
Can you also update this sentence in the preceding paragraph?

> Then we'll pipe our output into `sort` using the appropriate column, which in this case is the eighth one.

Here's my recommendation, but please feel free to use your own:

> Then we'll sort our output by the `store.size` column, in descending order.

2019-10-17 20:51 UTC, jrodewig commented
Hi @hackaholic 

Thanks for signing the CLA. Do you mind addressing the following comments:

- https://github.com/elastic/elasticsearch/pull/40926/files#r303889185

- https://github.com/elastic/elasticsearch/pull/40926/files#r336219633

After those are addressed, we can merge your changes in.

2019-10-17 20:51 UTC, jrodewig requested changes
Hi @hackaholic 

Thanks for signing the CLA. Do you mind addressing the following comments:

- https://github.com/elastic/elasticsearch/pull/40926/files#r303889185

- https://github.com/elastic/elasticsearch/pull/40926/files#r336219633

After those are addressed, we can merge your changes in.

2020-01-02 20:08 UTC, jrodewig commented
Closing due to lack of response. Treating as a bug report.

2020-01-02 20:08 UTC, closed without merging