Restricts naming for repositories
elastic/elasticsearch pull request #41008
Opened 2019-04-09 12:11 UTC by danhermann

Limits repository names to alphanumeric characters, underscores, and dashes.

Fixes #40817.

2019-04-09 12:28 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-04-12 13:18 UTC, danhermann commented
Jenkins, test this please

2019-04-12 13:34 UTC, danhermann commented
Jenkins, test this please

2019-04-12 22:19 UTC, danhermann commented
Jenkins, test this please

2019-04-24 08:32 UTC, original-brownbear requested changes
@danhermann thanks! I think this is fine, can you add a quick test that checks these conditions as well please?

2019-04-24 08:33 UTC, original-brownbear commented
@ywelsch maybe you can take a quick look too, to confirm that it's fine to restrict naming like this (looks like the same conditions as for snapshot naming are in here as well which makes perfect sense to me)?

2019-04-24 10:08 UTC, ywelsch requested changes
I've left some comments. Thank you for contributing this PR.

2019-04-24 10:08 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java
> +        if (repositoryName.contains(" ")) {
this is already covered by filename check

2019-04-24 10:08 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java
> +        if (repositoryName.contains(",")) {
this is already covered by filename check

2019-04-24 10:08 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java
> +        validate(repositoryMetaData.name());
this is a method that is internally called both on repository creation, but also after a restart when a node rejoins a cluster with an existing repository. I think we should do the validation only for new repository creation requests, and not retroactively apply to old repositories (which will break them). This means that the validation should be done in `registerRepository`, not `createRepository`.

2019-04-25 12:17 UTC, danhermann commented
Jenkins, test this please

2019-04-26 13:38 UTC, ywelsch approved these changes
LGTM

2019-04-26 13:50 UTC, original-brownbear approved these changes
LGTM2

2019-04-26 13:54 UTC, merged