Improve accuracy for Geo Centroid Aggregation
elastic/elasticsearch pull request #41033
Opened 2019-04-09 20:51 UTC by iverase

Stores the partial results for the moving aggregate as doubles instead of encoding them as integer.

closes #41032

2019-04-09 20:51 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo

2019-04-10 08:01 UTC, jpountz requested changes
The serialization logic needs to be backward compatible. Otherwise it looks good.

2019-04-10 08:01 UTC, jpountz commented on server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroid.java
> +            out.writeDouble(centroid.lon());
and there

2019-04-10 08:01 UTC, jpountz commented on server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroid.java
> +            centroid = new GeoPoint(in.readDouble(), in.readDouble());
we need to handle backward compatibility here

2019-04-10 08:03 UTC, iverase commented
Thanks @jpountz. Of course you might be talking to nodes with different versions. I wonder if it is then worthy to change that logic.

2019-04-11 09:53 UTC, jpountz commented
@iverase Actually I was suggesting that we change the serialization format based on the Stream(In|Out)put#getVersion(). If the version is gte 7.1 then we would serialize pairs of doubles and otherwise we would keep the old that folds both lat and lon into a long.

2019-04-11 14:37 UTC, iverase commented
@elasticmachine run elasticsearch-ci/packaging-sample

2019-04-11 14:55 UTC, iverase commented
@elasticmachine run elasticsearch-ci/packaging-sample please

2019-04-11 16:21 UTC, polyfractal commented
There aren't any yaml tests for geo centroid, right?  Just double checking since those can run in mixed-cluster BWC tests and might fail before the backport is complete.  I skimmed quickly and didn't see any but wanted to double check :)

2019-04-11 16:23 UTC, polyfractal approved these changes
LGTM!

2019-04-25 06:06 UTC, merged