Update create_index.asciidoc
elastic/elasticsearch pull request #41487
Opened 2019-04-24 13:18 UTC by remotegun

Elasticsearch 7.0 Create index was used for EL 6.7.1 which is not working properly.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2019-04-24 15:02 UTC, elasticmachine commented
Pinging @elastic/es-core-features

2019-06-03 14:48 UTC, dakrone requested changes
Thanks for the PR @remotegun, but it appears that one of the source callouts you included doesn't exist in `IndiciesClientDocumentationIT`, can you either add the java code or remove the source callout?

2019-06-03 14:48 UTC, dakrone commented on docs/java-rest/high-level/indices/create_index.asciidoc
> +include-tagged::{doc-tests-file}[{api}-mappings-shortcut]
I looked through the integration tests, however, there is no `// tag::create-index-request-mappings-shortcut` tag in the file, so this source include would not work.

2019-06-03 14:48 UTC, dakrone commented on docs/java-rest/high-level/indices/create_index.asciidoc
> +<2> Timeout to wait for the all the nodes to acknowledge the index creation as a `String`
Thanks for catching these :+1:

2019-07-15 09:14 UTC, javanna commented
Closing for lack of feedback, feel free to reopen whenever you are ready to work on this again.

2019-07-15 09:14 UTC, closed without merging