Add initial documentation for SLM
elastic/elasticsearch pull request #41510
Opened 2019-04-24 21:47 UTC by dakrone

This adds the initial documentation for snapshot lifecycle management.

It also includes the REST spec API json files since they're sort of
documentation.

Relates to #38461

2019-04-24 21:47 UTC, elasticmachine commented
Pinging @elastic/es-core-features

2019-04-25 16:53 UTC, dakrone commented
@elasticmachine run elasticsearch-ci/1

2019-04-29 17:12 UTC, AthenaEryma requested changes
Great start, just left a few comments about awkward phrasing, etc.

2019-04-29 17:12 UTC, gwbrown commented on docs/reference/ilm/apis/slm-api.asciidoc
> +any currently ongoing snapshots.
Or delete any snapshots previously taken by the policy. Might seem obvious, but probably best to be as clear as possible.

2019-04-29 17:12 UTC, gwbrown commented on docs/reference/ilm/index.asciidoc
> +index-level policy is managing snapshots for a set of indices. Since snapshots
This is a little awkward, I recommend rearranging this just a bit:
```
ILM itself does allow managing indices, however, managing snapshots for a set of indices is
outside of the scope of an index-level policy.
```

2019-04-29 17:38 UTC, dakrone commented
Thanks @gwbrown, I think I addressed all of your comments, thanks for taking a look.

2019-04-29 17:47 UTC, AthenaEryma approved these changes
LGTM, thank you!

2019-04-29 19:57 UTC, merged