Allow unknown task time in QueueResizingEsTPE
elastic/elasticsearch pull request #41810
Opened 2019-05-03 20:13 UTC by williamrandolph

The afterExecute method previously asserted that a TimedRunnable task
must have a positive execution time. However, the code in TimedRunnable
returns a value of -1 when a task time is unknown. Here, we expand the
logic in the assertion to allow for that possibility, and we don't
update our task time average if the value is negative.

Fixes #41448

2019-05-03 20:13 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2019-05-06 14:12 UTC, williamrandolph commented
@elasticmachine run elasticsearch-ci/1

2019-05-06 14:44 UTC, jaymode requested changes
This looks pretty good. I think we can make a change to be more explicit though.

2019-05-06 14:44 UTC, jaymode commented on server/src/main/java/org/elasticsearch/common/util/concurrent/QueueResizingEsThreadPoolExecutor.java
> +        assert taskExecutionNanos >= 0 || taskExecutionNanos == -1 :
I am a bit paranoid about things. I'd prefer if we also tracked if an exception occurred with a boolean that gets updated in the `onRejection` and `onFailure` methods. Then we can say for certain that a taskExecutionNanos of -1 was really due to an exception.

2019-05-07 20:17 UTC, jaymode approved these changes
LGTM

2019-05-07 21:04 UTC, merged