Fix allocation commands to use routing nodes to fetch shards
elastic/elasticsearch pull request #42066
Opened 2019-05-10 09:32 UTC by vigyasharma

When multiple commands are called in sequence, fetch shards
from mutable, up to date routing nodes to ensure each command's
changes are visible to subsequent commands.

This addresses [this bug](https://github.com/elastic/elasticsearch/pull/41050#issuecomment-486603482), uncovered as part of a different [pull request](https://github.com/elastic/elasticsearch/pull/41050).

2019-05-10 12:34 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-05-10 12:39 UTC, DaveCTurner submitted a review, later dismissed
Thanks @vigyasharma. This needs tests to support the change too: you need to construct some sequences of commands that fail because each command is ignoring the effects of the previous ones.

2019-05-10 12:39 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateEmptyPrimaryAllocationCommand.java
> +        // Validate input shard and index values
I think the behaviour of this block of code is clear without a comment.

2019-05-10 12:39 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateReplicaAllocationCommand.java
> +        // Validate input shard and index values
I think the behaviour of this block of code is clear without a comment.

2019-05-10 12:39 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateStalePrimaryAllocationCommand.java
> +        // Validate input shard and index values
I think the behaviour of this block of code is clear without a comment.

2019-05-10 12:39 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateEmptyPrimaryAllocationCommand.java
> +        for (ShardRouting shard: unassigned) {
Nit: needs a space before the colon.

2019-05-10 12:39 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateReplicaAllocationCommand.java
> +        for (RoutingNode node: allocation.routingNodes()) {
Nit: space before colon

2019-05-10 12:39 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateReplicaAllocationCommand.java
> +            for (ShardRouting shard: node) {
Nit: space before colon

2019-05-10 12:39 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateReplicaAllocationCommand.java
> +        for (ShardRouting shard: unassigned) {
Nit: space before colon

2019-05-10 12:39 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateStalePrimaryAllocationCommand.java
> +        for (ShardRouting shard: unassigned) {
Nit: space before colon

2019-05-10 12:39 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateReplicaAllocationCommand.java
> +            if (shard.getIndexName().equals(index) && shard.getId() == shardId && !shard.primary()) {
The house style is to use `== false` instead of `!`.

2019-05-10 15:58 UTC, vigyasharma commented
Thanks for the review. Made styling changes, will add test as well

2019-05-10 19:07 UTC, vigyasharma commented
@DaveCTurner Added test for multiple commands in single request. Please review when you get some time. Thanks!

2019-05-10 19:51 UTC, DaveCTurner commented
Thanks @vigyasharma. It's likely I won't be available to look at this in detail next week, but it's on my list for after that.

@elasticmachine ok to test

2019-05-23 08:23 UTC, vigyasharma commented
@DaveCTurner Did you get a chance to review this?

2019-05-24 10:46 UTC, DaveCTurner requested changes
Thanks @vigyasharma this looks close. I requested a few tiny changes.

2019-05-24 10:46 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateEmptyPrimaryAllocationCommand.java
> +        RoutingNodes.UnassignedShards unassigned = allocation.routingNodes().unassigned();
Nit: you can inline `unassigned`, it's only used in the following line.

2019-05-24 10:46 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateReplicaAllocationCommand.java
> +        for (ShardRouting shard : unassigned) {
Nit: you can inline `unassigned`, it's only used in the following line.

2019-05-24 10:46 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateStalePrimaryAllocationCommand.java
> +        RoutingNodes.UnassignedShards unassigned = allocation.routingNodes().unassigned();
Nit: you can inline `unassigned`, it's only used in the following line.

2019-05-24 10:46 UTC, DaveCTurner commented on server/src/test/java/org/elasticsearch/cluster/routing/allocation/AllocationCommandsTests.java
> +            assertThat(e.getMessage(), containsString("primary [" + index1 + "][0] is already assigned"));
This doesn't assert that the exception is actually thrown: the test still passes if the reroute succeeds. Suggest using `expectThrows()` like this:

```
        {
            final ClusterState finalClusterState = clusterState;
            assertThat(expectThrows(IllegalArgumentException.class, () -> {
                allocation.reroute(finalClusterState,
                    new AllocationCommands(
                        new AllocateStalePrimaryAllocationCommand(index1, 0, node1, true),
                        new AllocateStalePrimaryAllocationCommand(index1, 0, node2, true)
                    ), false, false);
            }).getMessage(), containsString("primary [" + index1 + "][0] is already assigned"));
        }
```

2019-05-24 10:46 UTC, DaveCTurner commented on server/src/test/java/org/elasticsearch/cluster/routing/allocation/AllocationCommandsTests.java
> +                ), false, false).getClusterState();
I think there's no need to call `getClusterState()` here.

2019-05-24 10:46 UTC, DaveCTurner commented on server/src/test/java/org/elasticsearch/cluster/routing/allocation/AllocationCommandsTests.java
> +                ), false, false).getClusterState();
As above, no need for `.getClusterState()`.

2019-05-24 10:46 UTC, DaveCTurner commented on server/src/test/java/org/elasticsearch/cluster/routing/allocation/AllocationCommandsTests.java
> +                false, false).getClusterState();
As above, no need for `.getClusterState()`.

2019-05-24 10:46 UTC, DaveCTurner commented on server/src/test/java/org/elasticsearch/cluster/routing/allocation/AllocationCommandsTests.java
> +            assertThat(e.getMessage(), containsString("primary [" + index2 + "][0] is already assigned"));
This should also use `expectThrows()`.

2019-05-24 10:46 UTC, DaveCTurner commented on server/src/test/java/org/elasticsearch/cluster/routing/allocation/AllocationCommandsTests.java
> +            assertThat(e.getMessage(),
This should also use `expectThrows()`.

2019-05-24 13:26 UTC, vigyasharma commented
Thanks @DaveCTurner. Made suggested changes.

2019-05-24 13:35 UTC, DaveCTurner approved these changes
LGTM thanks @vigyasharma. I expect to merge this after the weekend now.

2019-05-28 14:42 UTC, merged