NullPointerException when creating a watch with Jira action (#41922)
elastic/elasticsearch pull request #42081
Opened 2019-05-10 14:48 UTC by ojasgulati

NullPointerException when secured_url does not use proper scheme in jira action. This commit will handle Expection and display proper message.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2019-05-11 08:07 UTC, ojasgulati commented
@ielatif i made the changes please have a look.

2019-05-12 23:33 UTC, ielatif commented
Relates to #41922

2019-05-13 07:32 UTC, elasticmachine commented
Pinging @elastic/es-core-features

2019-05-13 09:56 UTC, ielatif requested changes

2019-05-13 10:17 UTC, ojasgulati commented on x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/http/Scheme.java
> +        Objects.requireNonNull(value, "Schema should not be Null");
Made correction. please have a look 😃

2019-05-13 10:28 UTC, ielatif approved these changes

2019-05-24 17:52 UTC, jbaiera commented
Thanks for opening this PR @ojasgulati. 

@elasticmachine Test this please

2019-05-28 19:13 UTC, jbaiera commented
@ojasgulati CI is failing on what looks like some unrelated issues. Could you merge upstream master into your branch just to make sure CI is all green before merging? Alternatively, I can do the merge and CI dance if you [enable maintainer contributions](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on this PR

2019-05-28 22:49 UTC, ojasgulati commented
@jbaiera I am unable to merge. Newbie to git 😅. It would be very helpful if you merge the upstream master. I have already enabled edits from maintainers. Also if possible, could you please share a link to a good tutorial on how to merge upstream so I can deal with this problem in future. 
Thanks

2019-06-01 09:25 UTC, ojasgulati commented
@jbaiera I have merged the upstream master please have a look.

2019-06-03 18:52 UTC, jbaiera commented
Thanks @ojasgulati, appreciate it!

@elasticmachine Test this please

2019-06-04 15:28 UTC, jbaiera approved these changes
LGTM

2019-06-04 17:49 UTC, merged