Removes types from SearchRequest and QueryShardContext
elastic/elasticsearch pull request #42112
Opened 2019-05-13 14:02 UTC by colings86

This change will remove the notion of types completely from the Search API internals.

For classes that are serialised (such as `SearchRequest`, `IdsQuery`, `ShardLocalSearchRequest`) we need to check for the wire version and deal with the types serialisation if the other node is `<8.0.0`

2019-05-13 14:02 UTC, elasticmachine commented
Pinging @elastic/es-search

2019-05-13 14:06 UTC, colings86 commented
@jpountz I was hoping this would be easier to split into incremental changes. All I managed to do was split the changes from removing types from `SearchRequest` into a separate commit to the ones removing types from `QueryShardContext`. I can split the commits into 2 separate PRs if you prefer? Also open to thoughts on better ways to split this if think it needs to be made smaller?

2019-05-15 17:56 UTC, jpountz requested changes
It looks good overall. I think we should fail deserialization of request builders when the set of types is not empty? My worry is that we might hide bugs otherwise, eg. if a user is querying a different type than the type of the index: if we ignore types, the query might match some documents while it shouldn't?

2019-05-15 17:56 UTC, jpountz commented on server/src/main/java/org/elasticsearch/action/search/SearchRequest.java
> +            in.readStringArray();
should we fail if the array is not empty?

2019-05-15 17:56 UTC, jpountz commented on server/src/test/java/org/elasticsearch/search/aggregations/pipeline/SerialDiffIT.java
> +                    .prepareSearch("idx")
it should be indented on the same level as `.addAggregation`?

2019-05-16 12:26 UTC, colings86 commented
@jpountz thanks for the review, I pushed a commit to address your comments

2019-05-16 14:55 UTC, colings86 commented
@elasticmachine run elasticsearch-ci/1

2019-05-28 16:36 UTC, jpountz approved these changes

2019-05-29 07:50 UTC, merged