Added a new use case for transport.port
elastic/elasticsearch pull request #42126
Opened 2019-05-13 21:10 UTC by caminsha

I've had the problem that I was allowing only the http.port setting and I couldn't get a connection..

After I tried using the transport port I had a successful connection and the sync work perfectly. 

On Wednesday I can show the issue that I tried it on the other port..

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2019-05-15 00:56 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-06-06 08:21 UTC, ywelsch requested changes
Thank you for your contribution. I think it makes sense to name our Java transport client explicitly here. @jrodewig can you make a suggestion?

We can't account for other clients that wrap our Java transport client though, so I think it might be more appropriate if the docs of those clients (e.g. Cloudian Sync for Object Storage Integration) would contain that info.

Finally, as the transport client is going away in 8.0, this PR should be opened against the 7.x branch.

2019-06-06 12:26 UTC, jrodewig commented on docs/reference/modules/transport.asciidoc
> +the data). The transport module is also used for other Java Clients. (i.e.
```suggestion
the data). The transport module is also used for the `TransportClient` in the
{es} Java API.
```

2019-06-06 12:27 UTC, jrodewig requested changes
Thank you for your contribution @caminsha. 

I made some suggestions in line with @ywelsch's review.

Please note that you'll need to sign the Elastic CLA before we can merge this change.

Please let me know if you have any questions or concerns.

2019-06-16 20:55 UTC, caminsha commented
@jrodewig @ywelsch  Thanks for your tips!

I've signed the CLA. I hope it is okay with the CLA otherwise contact me, thanks!

2019-06-18 13:24 UTC, jrodewig commented on docs/reference/modules/transport.asciidoc
>  the Cloudian Sync for Object Storage Integration into Elasticsearch)
```suggestion

```

2019-06-18 13:25 UTC, jrodewig commented on docs/reference/modules/transport.asciidoc
>  the Cloudian Sync for Object Storage Integration into Elasticsearch)
Sorry. We'll need to remove this as well.

Otherwise, this looks good to me.

2019-06-18 13:32 UTC, ywelsch approved these changes
LGTM. The transport client is gone in 8.0, so this just needs to be merged in to 7.x and below. @jrodewig can you do this? Thank you

2019-06-18 13:33 UTC, ywelsch commented
@elasticmachine test this please

2019-06-18 13:34 UTC, jrodewig approved these changes

2019-06-18 13:35 UTC, jrodewig commented
@ywelsch  Will do.

Thanks again for your contribution @caminsha. I'll merge this after the CI tests pass.

2019-06-18 13:51 UTC, merged