Example of how to set slow logs dynamically per-index
elastic/elasticsearch pull request #42384
Opened 2019-05-22 17:58 UTC by luizgpsantos

2019-05-22 19:45 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2019-06-21 00:00 UTC, rjernst commented
@jrodewig Can you review this please?

2019-06-21 12:47 UTC, jrodewig requested changes
Thanks for the contribution @luizgpsantos!

I made a few suggestions that should get this to pass the CI. As soon as those are fixed, I can help merge and backport.

2019-06-21 12:47 UTC, jrodewig commented on docs/reference/index-modules/slowlog.asciidoc
> +All of the above settings are _dynamic_ and are set per-index. For example:
Minor edit to make the `_settings` API example more explicit.
```suggestion
All of the above settings are _dynamic_ and can be set for each index using the
<<indices-update-settings, update indices settings>> API. For example: 
```

2019-06-21 12:47 UTC, jrodewig commented on docs/reference/index-modules/slowlog.asciidoc
> +All of the above settings are _dynamic_ and are set per-index. For example:
```suggestion
All of the above settings are _dynamic_ and can be set for each index using the
<<indices-update-settings, update indices settings>> API. For example: 
```

2019-06-21 12:47 UTC, jrodewig commented on docs/reference/index-modules/slowlog.asciidoc
> +// CONSOLE
This should fix the CI errors.
```suggestion
// CONSOLE
// TEST[setup:twitter]
```

2019-06-21 12:47 UTC, jrodewig commented on docs/reference/index-modules/slowlog.asciidoc
> +// CONSOLE
```suggestion
// CONSOLE
// TEST[setup:twitter]
```

2019-06-21 13:14 UTC, jrodewig approved these changes
LGTM. I'll merge this and backport as needed once CI passes. Thanks again @luizgpsantos!

2019-06-21 13:24 UTC, merged

2019-06-21 13:49 UTC, luizgpsantos commented
Thanks @jrodewig!