Avoid throwing NPE when no master found
elastic/elasticsearch pull request #42419
Opened 2019-05-23 07:01 UTC by DaveCTurner

Today in `SpecificMasterNodesIT` we assert the name of the master and throw a
NPE if there is no master. This doesn't work within an `assertBusy()` because
the NPE triggers an immediate failure rather than the desired retry. This
commit addresses this by first asserting that the master is non-null.

Fixes #38331
Relates #38432, #37802

2019-05-23 07:01 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-05-23 08:08 UTC, ywelsch requested changes
I think it's trappy that a cluster state with no master is returned and would like to see that fixed in TransportClusterStateAction.
We use a TransportMasterNodeAction to make this request end up on the master, and do all kind of checks to make sure this node is still master, for it to fail  in the final stage due to a race between master service and cluster (applier) service.
In TransportClusterStateAction.masterOperation we should use the cluster state that is passed to masterOperation as the cluster state to return.

In case where we wait for metadataversion, we should also make sure we don't lose the master (otherwise throw NotMasterException which will bubble it back to TransportMasterNodeAction and its retries facilities)...

2019-05-23 16:55 UTC, DaveCTurner commented
Ok, closing in favour of #42454.

2019-05-23 16:55 UTC, closed without merging

2019-05-24 07:02 UTC, jpountz commented
@DaveCTurner Please remember to remove labels when closing unmerged PRs.