[DOCS] Set explicit anchor for "SysV `init` vs `systemd`" section
elastic/elasticsearch pull request #42525
Opened 2019-05-24 14:18 UTC by jrodewig

This PR attempts to fix the following autogenerated anchors so they render consistently in AsciiDoc and Asciidoctor:
* (5.0 - 6.2) _sysv_literal_init_literal_vs_literal_systemd_literal_2 -> _sysv_init_vs_systemd_2
* (5.0 - 6.2) _sysv_literal_init_literal_vs_literal_systemd_literal -> _sysv_init_vs_systemd

However, the `init-systemd.asciidoc` file containing the anchor is included in two other files:
- deb.asciidoc
- rpm.asciidoc

This means the explicit anchors is reused. Reusing the anchor results in the following errors:
```
INFO:build_docs:asciidoctor: WARNING: setup/install/init-systemd.asciidoc: line 2: id assigned to section already in use: _sysv_literal_init_literal_vs_literal_systemd_literal
```

### Next steps
@nik9000
Let me know if you have any suggestions. We might be better off just accepting the anchor change.

2019-05-24 14:18 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-05-24 20:24 UTC, nik9000 commented
I think the anchor change is better than duplicating the anchor.

2019-05-28 15:22 UTC, jrodewig commented
Thanks for your help @nik9000. This is now ready for your review.

2019-05-28 17:49 UTC, nik9000 requested changes

2019-05-28 17:49 UTC, nik9000 commented on docs/reference/setup/install/deb.asciidoc
> +:int-context: deb
Could you do `:init-context:` instead?

2019-05-28 18:37 UTC, jrodewig commented on docs/reference/setup/install/deb.asciidoc
> +:int-context: deb
Added with c161040. Thanks!

2019-05-28 19:05 UTC, nik9000 approved these changes
LGTM. Thanks!

2019-05-28 19:15 UTC, merged