Control Cluster Shards Balancing
elastic/elasticsearch pull request #42739
Opened 2019-05-31 04:18 UTC by hanbj

Previous implementations were well thought out, but an index balance would cause all indexes to balance together.

2019-05-31 11:20 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-06-05 14:49 UTC, ywelsch reviewed
Thank you for your interest in contributing to ES. I don't understand what this change is trying to achieve, unfortunately. Can you provide some more explanations? In particular, why is it removing the code that allows index-level settings from overriding the cluster-level ones?

2019-06-06 15:52 UTC, hanbj commented
If an index is allowed to be rebalance, then this line of code "if (allocation. deciders (). canRebalance (allocation). type ()!= Type. YES)" returns false, and the code continues to execute downward. In the balanceByWeights () method, all indexes are traversed according to the weight rebalance, so I set cluster. routing. rebalance. enable: "none" is invalid.

2019-07-01 11:14 UTC, ywelsch requested changes
I'm not sure I understand what the purpose of this PR is, especially as it's disabling existing ES functionality. Is it to address a scaling issue? You mention a cluster with 300,000 shards on another PR, so I assume this is related. Why is this cluster making use of index-level rebalancing (i.e. the `index.routing.rebalance.enable` setting) if that is turning out to be a scaling bottleneck?

2019-07-01 11:14 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/EnableAllocationDecider.java
> +                    return allocation.decision(Decision.NO, NAME,
why does this globally disable rebalancing when there are some inactive primaries of an unrelated index?

2019-07-01 11:14 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/EnableAllocationDecider.java
> +                    return allocation.decision(Decision.NO, NAME,
why does this globally disable rebalancing when there are inactive shards of some unrelated index?

2019-07-01 11:14 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/EnableAllocationDecider.java
> +                return allocation.decision(Decision.NO, NAME, "none rebalance are not allowed");
As said earlier, this changes the behavior of ES not to take the index-level property into account anymore when the cluster-level property is set.

2019-07-01 11:16 UTC, ywelsch commented
I don't see a way to take this PR forward (as it is breaking existing functionality), which is why I'm closing this. @hanbj do let me know about the problem this is trying to address and in particular whether it is something that would be covered by other work (e.g. https://github.com/elastic/elasticsearch/pull/42738)

2019-07-01 11:16 UTC, closed without merging

2020-05-29 07:00 UTC, hanbj commented
@ywelsch Thank you, there is indeed a problem at the moment, we are planning to implement it from another namespace way, ES cluster can be infinitely expanded, so this is the reason why I have not updated this pr for so long, sorry