Correct "term_vector" option with documented one
elastic/elasticsearch pull request #42828
Opened 2019-06-04 02:39 UTC by insukcho

In [term_vector reference doc](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/term-vector.html#term-vector), `with_positions_offsets_payloads` is not existed and `payloads` seems useless. 
Let's change it to `with_positions_offsets` as it was mentioned in the reference doc to avoid confusion. `with_positions_offsets_payloads` is not searchable in 7.1 doc.

2019-06-04 02:59 UTC, insukcho commented
It seems some test cases are checking the sample source code. It is my first time to see this for doc enhancements PR. Where should I change if I want to pass these test cases?

2019-06-06 07:36 UTC, elasticmachine commented
Pinging @elastic/es-search

2019-06-06 10:17 UTC, mayya-sharipova requested changes
@insukcho Thanks for your PR.  To pass the test, you should also correct the  provided response - remove payloads in the response body

2019-06-15 06:10 UTC, insukcho commented
@mayya-sharipova Thanks for the reply. Where can I find the response body? Could you please elaborate more about it? It will help me to do it right away next time ;)

2019-06-17 20:55 UTC, mayya-sharipova commented
@insukcho Response is presented on the lines: 207-263, this is where we need to remove payloads since you disabled payloads.  We are testing the response on the line 266, and the response provided in the file is different from the one ES returns, hence the test error occurs.

2019-07-15 09:09 UTC, javanna commented
I had a look at this and noticed that we support more options than the ones specified in our docs, see https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/mapper/TypeParsers.java#L324 . I wonder if we should update the docs to include all the supported options. What do you think @mayya-sharipova ?

2019-07-15 19:51 UTC, mayya-sharipova commented
@javanna Thanks Luca! I have created a [PR](https://github.com/elastic/elasticsearch/pull/44379) to add this option. Would mind reviewing it?

2019-07-16 11:47 UTC, javanna commented
Closing in favour of #44379 .

2019-07-16 11:47 UTC, closed without merging

2019-10-17 02:22 UTC, insukcho commented
Ohh, so the issue was the lack of documentation of supported options!!
Next time, I will try to find and read `the source code` first and discuss it in a more efficient way.

Thank you for your help @mayya-sharipova @javanna