Fix incorrect node name in docs
elastic/elasticsearch pull request #43062
Opened 2019-06-10 18:15 UTC by lag13

After starting up elasticsearch the documentation said that their node
name was "6-bjhwl" but in the documentation's output I did not see that
node name. Instead I saw the node name as `localhost.localdomain`

2019-06-11 06:12 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-07-15 08:58 UTC, javanna requested changes
thanks for fixing this @lag13, I left a small comment, looks good to me otherwise.

2019-07-15 08:58 UTC, javanna commented on docs/reference/getting-started.asciidoc
> +Without going too much into detail, we can see that our node named "localhost.localdomain" (which will be a different set of characters in your case) has started and elected itself as a master in a s
could you also remove the "(which will be a different set of characters in your case)" which is no longer true, please?

2019-07-15 19:11 UTC, lag13 commented
Thanks for catching that @javanna ! Fixed.

2019-07-16 11:40 UTC, javanna commented
test this please

2019-07-16 12:09 UTC, javanna approved these changes

2019-07-16 12:10 UTC, merged

2019-07-16 12:10 UTC, javanna commented
thanks a lot @lag13 !

2019-07-16 17:18 UTC, lag13 commented
thanks for your help getting this tiny change merged!

2019-07-26 15:44 UTC, elasticmachine commented
Pinging @elastic/es-core-infra