Fix for ApiKeyIntegTests related to Expired API keys remover
elastic/elasticsearch pull request #43477
Opened 2019-06-21 10:07 UTC by bizybot

When API key is invalidated we do two things first it tries to trigger `ExpiredApiKeysRemover` task
and second, we do index the invalidation for the API key. The index invalidation may happen
before the `ExpiredApiKeysRemover` task is run and in that case, the API key
invalidated will also get deleted. If the `ExpiredApiKeysRemover` runs before the
API key invalidation is indexed then the API key is not deleted and will be
deleted in the future run.
This behavior was not captured in the tests related to `ExpiredApiKeysRemover`
causing intermittent failures.
This commit fixes those tests by checking if the API key invalidated is reported
back when we get API keys after invalidation and perform the checks based on that.

Closes #41747

2019-06-21 10:07 UTC, elasticmachine commented
Pinging @elastic/es-security

2019-06-24 19:01 UTC, albertzaharovits requested changes
> The index invalidation may happen
before the ExpiredApiKeysRemover task is run and in that case, the API key
invalidated will also get deleted.

I believe this is not true. And I see the changes in the tests reflect this thinking.

In `ExpiredApiKeysRemover` there is this condition
`.should(QueryBuilders.rangeQuery("expiration_time").lte(now.minus(EXPIRED_API_KEYS_RETENTION_PERIOD).toEpochMilli()))`
such that expired API keys will not immediately be removed.
And I believe the tests don't change this?

2019-06-27 11:52 UTC, albertzaharovits commented
> The expiration_time can be null (for API keys with no expiration) and the minimumShouldMatch
means at least one out of the 2 should clause must match.

Ooops! You're right! I completely misunderstood the condition there. Good catch in the tests!

So, invalidated keys are removed as soon as possible but expired ones have a 7 days (configurable) grace period before they are deleted. I believe the reason for the grace period is for audit & diagnostic purposes (a service stops working some day, with its API key non-existent; did the API key existed and  and was deleted automatically, or it never existed and the client must have messed up its credentials).

Should invalidated API keys also have the same grace period? I believe this might have been discussed before? Invalidation is an explicit action that we audit so this is a strong reason no to; but we don't audit or otherwise trace specifically which API key got invalidated.

Alternatively, instead of marking them as invalidated and then having a periodic job do the removal, could we just remove them?

I am proposing this only because the changes required in tests look unnecessary complicated (but correct).

2019-09-26 13:13 UTC, jkakavas commented
@bizybot I think we're good to merge this and you can open the follow up issue to discuss the invalidation grace period ?

2019-10-01 08:14 UTC, albertzaharovits approved these changes
LGTM

2019-10-02 06:55 UTC, merged