Add snippet for the search_type query parameter
elastic/elasticsearch pull request #43540
Opened 2019-06-24 14:33 UTC by EmmanuelDemey

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2019-06-24 16:08 UTC, elasticmachine commented
Pinging @elastic/es-search

2019-06-24 16:08 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-07-11 13:24 UTC, mayya-sharipova requested changes
@EmmanuelDemey Thanks for you contribution! Indeed having examples here would be very helpful. Can you please address comments to ensure the snippets are testable.

2019-07-11 13:24 UTC, mayya-sharipova commented on docs/reference/search/request/search-type.asciidoc
> +
Let's make this example executable/testable by adding `CONSOLE`. This ensures that the snippet will be executed/tested. We will also need to setup the index with data for the test and for this we can use `TEST[setup:twitter]`.

So, the overall snippet can look like this:
```
[source,js]
--------------------------------------------------
GET twitter/_search?search_type=query_then_fetch
--------------------------------------------------
// CONSOLE
// TEST[setup:twitter]
```

2019-07-11 13:24 UTC, mayya-sharipova commented on docs/reference/search/request/search-type.asciidoc
> +--------------------------------------------------
similar comment here

2019-08-06 11:00 UTC, javanna commented
hi @EmmanuelDemey would you have time to address the comments you got above? Thanks!

2019-08-11 18:13 UTC, EmmanuelDemey commented
@javanna sorry for the delay. I have just pushed the change.

2019-08-11 22:05 UTC, mayya-sharipova commented
@elasticmachine test this please

2019-08-11 22:07 UTC, mayya-sharipova approved these changes
@EmmanuelDemey Thanks for your PR

2019-08-11 22:10 UTC, mayya-sharipova commented
@elasticmachine update branch

2019-08-11 22:11 UTC, mayya-sharipova commented
@elasticmachine test this please

2019-08-11 22:33 UTC, merged