Update docs to refer to 6.8 instead of 6.7
elastic/elasticsearch pull request #43685
Opened 2019-06-27 09:46 UTC by spinscale

A few places in the documentation had mentioned 6.7 as the version to
upgrade from, when doing an upgrade to 7.0. While this is technically
possible, this commit will replace all those mentions to 6.8, as this is
the latest version with the latest bugfixes, deprecation checks and
ugprade assistant features - which should be the one used for upgrades.

To any reviewers: I intend to backport this down to 7.0 - please veto as part of the review, if you disagree.

2019-06-27 09:46 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-06-27 12:37 UTC, jrodewig commented on docs/reference/upgrade/rolling_upgrade.asciidoc
> +* {stack-ref-67}/upgrading-elastic-stack.html[From 5.6 to 6.8]
`{stack-ref-67}` points to the 6.7 branch of the [Elastic Stack Installation and Upgrade Guide](https://www.elastic.co/guide/en/elastic-stack/6.7/index.html).

I opened elastic/docs#956 to add a `{stack-ref-68} attribute. However, if you don't want to wait or have the dependency, you can just the `https://www.elastic.co/guide/en/elastic-stack/6.8/upgrading-elastic-stack.html` link.

2019-06-27 12:38 UTC, jrodewig commented on docs/reference/upgrade/cluster_restart.asciidoc
> +https://www.elastic.co/guide/en/elastic-stack/6.8/upgrading-elastic-stack.html[upgrade to 6.8]
This should probably use the `{stack-ref-68}` attribute for consistency.

2019-06-27 12:39 UTC, jrodewig requested changes
LGTM aside from the needed link change.

2019-07-01 07:57 UTC, spinscale commented
thx for the pointers to the link changes, done!

2019-07-01 12:18 UTC, jrodewig approved these changes
LGTM. Thanks!

2019-07-02 07:06 UTC, merged

2019-09-13 19:16 UTC, jaymode commented
I opened #46720 to revert this from the 7.0 branch. 6.8 cannot perform a rolling upgrade to 7.0; instead 6.7 can perform a rolling upgrade to 7.0 and 6.8 can perform a rolling upgrade to 7.1.