Remove support for old translog checkpoint formats
elastic/elasticsearch pull request #44272
Opened 2019-07-12 10:58 UTC by Hohol

Closes https://github.com/elastic/elasticsearch/issues/44210

2019-07-12 10:59 UTC, Hohol commented
@DaveCTurner, am I on the right track? Is there anything else to be done in master (besides tests)?

2019-07-12 11:08 UTC, DaveCTurner commented
Yes that's about all that's needed for the production code in `master`, except that a few of the comments still mention version numbers or otherwise refer back to older versions. It's all about the tests :)

2019-07-12 11:08 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-07-12 11:10 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/index/translog/Checkpoint.java
> +                return Checkpoint.readCheckpointV6_4_0(indexInput);
Suggest removing the mention of a specific (ancient) version here too:

```suggestion
                return Checkpoint.readCheckpointV3(indexInput);
```

2019-07-15 17:09 UTC, DaveCTurner requested changes
Thanks @Hohol looks good, but needs merging with latest master.

2019-07-15 17:09 UTC, DaveCTurner commented on server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
> +            () -> Checkpoint.read(getDataPath("/org/elasticsearch/index/checkpoint/v2.cpk"))
:+1: although #44217 means this now throws a different exception.

2019-07-19 08:51 UTC, DaveCTurner commented
@elasticmachine test this please

2019-07-19 08:54 UTC, DaveCTurner commented on server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
> +            () -> Checkpoint.read(getDataPath("/org/elasticsearch/index/checkpoint/v2.cpk"))
Filename typo:

```suggestion
            () -> Checkpoint.read(getDataPath("/org/elasticsearch/index/checkpoint/v2.ckp"))
```

2019-07-19 09:18 UTC, Hohol commented
Forgot to actually change the file name...

2019-07-19 09:24 UTC, DaveCTurner commented
Oh hang on the build will still fail after renaming that file - try the `:server:forbiddenpatterns` task. Stand by I will work out what pattern would be acceptable.

2019-07-19 09:27 UTC, DaveCTurner commented
Please call it `v2.ckp.binary`.

2019-07-19 12:39 UTC, DaveCTurner commented
@elasticmachine please test this

2019-07-19 12:40 UTC, DaveCTurner commented
@elasticmachine test this please

2019-07-19 13:26 UTC, DaveCTurner commented
@elasticmachine please run elasticsearch-ci/2

2019-07-19 14:57 UTC, DaveCTurner approved these changes
LGTM

2019-07-19 15:00 UTC, merged