Fix Incorrect Uncompressed Error Handling in InboundMessage
elastic/elasticsearch pull request #44317
Opened 2019-07-14 18:25 UTC by original-brownbear

* CompressorFactory.compressor does not throw uncompressed exception on uncompressed bytes, it merely returns `null` in this case if the bytes are at least XContent so the current catch and re-throw logic is dead code
* Made it work again by throwing on a `null` return so we get a real error message instead of an NPE

2019-07-14 18:25 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-07-15 06:52 UTC, ywelsch requested changes
This needs tests

2019-07-15 08:29 UTC, original-brownbear commented
@ywelsch good call, sorry about that. Adding tests showed this was still misbehaving because the uncompressed bytes wouldn't necessarily be xcontent (who knows what they would be I guess) ... I adjusted the logic a little more to not run into the safety checks for xcontent in `CompressorFactory` now and added a test.

2019-07-15 17:17 UTC, Tim-Brooks approved these changes
LGTM

2019-07-17 07:49 UTC, ywelsch approved these changes
LGTM

2019-07-17 07:49 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/transport/InboundMessage.java
> +    static Compressor getCompressor(BytesReference message) {
Can you add `@Nullable` for the result here?

2019-07-17 09:55 UTC, original-brownbear commented
Thanks @ywelsch + @tbrooks8 !

2019-07-17 09:55 UTC, merged