[DOCS] Add explanation of relocating shard state.
elastic/elasticsearch pull request #44846
Opened 2019-07-25 08:54 UTC by JaredTan95

Related to: https://github.com/elastic/elasticsearch/issues/43244

2019-07-25 10:14 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-07-25 10:14 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-07-25 10:19 UTC, DaveCTurner requested changes
Thanks for opening this @JaredTan95. I don't fully understand the change you're proposing, although I do agree that these docs are a bit sparse. Can you explain in a bit more detail what you're hoping to clarify with this change?

2019-07-25 10:19 UTC, DaveCTurner commented on docs/reference/cat/shards.asciidoc
> +Before a shard can be used, it goes through an `INITIALIZING` or `Relocating` state.
I don't quite understand this change, and think the original docs are more correct than the statement written here. All shards go through an `INITIALIZING` state before they can be used, and moreover a shard that is in the `RELOCATING` state is completely usable - `RELOCATING` is much more like `STARTED` than `INITIALIZING`.

2019-07-26 09:29 UTC, JaredTan95 commented
Maybe there is something I miss, temporarily closed.

2019-07-26 09:29 UTC, closed without merging