Support fixture in repository-gcs:thirdPartyTest and fix GCS fixture
elastic/elasticsearch pull request #44885
Opened 2019-07-25 21:15 UTC by andrershov

It turns out that today `:plugins:repository-gcs:thirdPartyTest` can only run against real GCS.
Moreover, thirdPartyTest is not a part of check, so these tests are not running on intake build.
This commit addresses the issue and makes repository-gcs:thirdPartyTest work with both fixture and real GCS.
To do that, except adjusting build and test itself, I had to make changes to the fixture, because previously it was ignoring `BlobListOption.currentDirectory()` in the list call.
This is a ground needed to add GCS fixture based testing to the snapshot-tool.

2019-07-25 21:15 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-07-26 06:34 UTC, original-brownbear commented
@andrershov FYI, builds failing here.

2019-07-26 10:01 UTC, andrershov commented
@original-brownbear test failure should be fixed now

2019-07-26 10:45 UTC, original-brownbear commented
Jenkins run elasticsearch-ci/2 (watcher)

2019-07-26 11:07 UTC, original-brownbear requested changes
Looks ok in general, a few smaller comments.

Did you test this against real GCS to make sure it still works?

2019-07-26 11:31 UTC, andrershov commented on plugins/repository-gcs/build.gradle
> +task thirdPartyTest(type: Test) {
Sure, https://github.com/elastic/elasticsearch/pull/44885/commits/39fdfb324f32b9502e9d54d83cf24e86d0ce3df1

2019-07-26 11:31 UTC, andrershov commented on plugins/repository-gcs/build.gradle
> +    systemProperty 'tests.security.manager', 'false'
Agreed, it works fine with security manager enabled https://github.com/elastic/elasticsearch/pull/44885/commits/39433d8ede3ba4da879cb255fc6ba640a6be4140

2019-07-26 11:31 UTC, andrershov commented on plugins/repository-gcs/src/test/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageThirdPartyTests.java
> +        Settings.Builder builder = Settings.builder();
https://github.com/elastic/elasticsearch/pull/44885/commits/417a2f690e37881e380a717a693dd1f5c6e3bf85

2019-07-26 11:32 UTC, andrershov commented
@original-brownbear thanks for your review! I've made the necessary changes. Of course, I've made sure that it works for both real GCS and fixture. Ready for the next pass.

2019-07-26 12:01 UTC, original-brownbear approved these changes
thanks @andrershov LGTM if we get CI to be happy :)

2019-07-26 12:01 UTC, original-brownbear commented
Jenkins run elasticsearch-ci/2

2019-07-29 12:12 UTC, merged