REST API changes for manage-own-api-key privilege
elastic/elasticsearch pull request #44936
Opened 2019-07-29 05:28 UTC by bizybot

This commit adds a flag that can be set to `true` if the
API key request (Get or Invalidate) is for the API keys owned
by the currently authenticated user only.
These only interface changes and once the actual cluster privilege 
`manage_own_api_key` is done, we will have another PR to make the
interface work.

The Get API behavior would be:
- when `my_api_keys_only` is set to `true`
  `GET /_security/api_key?id=abcd&my_api_keys_only=true`
        the Rest controller will take care of setting `realm_name` and `username` to the
        values for the authenticated user and only return results if it finds one owned by
        the currently authenticated user.

- when `my_api_keys_only` is set to `false` (default)
  `GET /_security/api_key?id=abcd`
        the Rest controller will assume `realm_name` and `username` to be unspecified
        meaning it will try to search for the API key across users and realms.
        This will fail if the user has only `manage_own_api_key` privilege.

Similarly, for Delete API key behavior:
- when `my_api_keys_only` is set to `true`
   `DELETE /_security/api_key`
   ```
   {
     "id" : "VuaCfGcBCdbkQm-e5aOx",
     "my_api_keys_only": "true"
   }
   ```

   the Rest controller will take care of setting `realm_name` and `username` to the values
   for the authenticated user and only invalidate key if it finds one owned by
   the currently authenticated user.

- when `my_api_keys_only` is set to `false` (default)
   `DELETE /_security/api_key`
   ```
   {
     "id" : "VuaCfGcBCdbkQm-e5aOx",
     "my_api_keys_only": "false"
   }
   ```

    the Rest controller will assume `realm_name` and `username` to be unspecified meaning it will 
    try to search for the API key across users and realms. This will fail if the user has only
    `manage_own_api_key` privilege.

TODO:
- HLRC changes - these will be done in a separate PR
- Actual enforcement of `my_api_keys_only` in a separate PR

Relates #40031

2019-07-29 05:28 UTC, elasticmachine commented
Pinging @elastic/es-security

2019-07-29 20:20 UTC, albertzaharovits approved these changes
LGTM save for the lack of version guards.

2019-07-29 20:20 UTC, albertzaharovits commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/GetApiKeyRequest.java
> +        myApiKeysOnly = in.readOptionalBoolean();
This needs to be version guarded. Similarly for the write.

2019-07-29 20:20 UTC, albertzaharovits commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/InvalidateApiKeyRequest.java
> +        myApiKeysOnly = in.readOptionalBoolean();
The same version guard.

2019-08-01 06:03 UTC, tvernum commented
Did you consider alternatives for the parameter name? I don't love it (it's a bit verbose), but I don't want to go back over old ground if you've worked through a bunch of options already.

I would think that `owned=true` would be fine.

2019-08-01 07:33 UTC, tvernum commented
I'm personally not that worried about whether the meaning of the parameter is 100% obvious from its name - we have docs.
I'm OK with `owned_by_me` but we could do `own=true` or `owner=true` if they seemed clear enough to you.

2019-08-01 13:44 UTC, tvernum reviewed
I didn't get to finish my review, but I left some comments...

2019-08-01 13:44 UTC, tvernum commented on x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/action/GetApiKeyRequestTests.java
> +            inputStreamStreamInput.setVersion(randomFrom(Version.V_7_4_0, Version.CURRENT));
```suggestion
            inputStreamStreamInput.setVersion(VersionUtils.randomVersionBetween(random(), Version.V_7_4_0,  null));
```

2019-08-01 13:44 UTC, tvernum commented on x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/action/GetApiKeyRequestTests.java
> +        return randomFrom(new String[]{"", null});
It's personal preference, but ...
```suggestion
        return randomBoolean() ? "" : null;
```

2019-08-06 08:01 UTC, tvernum requested changes

2019-08-06 08:01 UTC, tvernum commented on x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/rest/action/apikey/RestGetApiKeyActionTests.java
> +        final boolean owner = randomBoolean();
Per my other comment, this variable seems to be named incorrectly.

2019-08-06 08:01 UTC, tvernum commented on x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/rest/action/apikey/RestGetApiKeyActionTests.java
> +        }
Per my other comment, it seems weird to set `param` and then set it again.

2019-08-07 06:37 UTC, tvernum approved these changes

2019-08-07 06:52 UTC, merged

2019-10-25 01:09 UTC, codebrain commented
@bizybot - PR looks good, we had to patch the REST API specification to add the "owner" flag. I will open an issue for this.

2019-10-25 01:12 UTC, codebrain commented
https://github.com/elastic/elasticsearch/issues/48499