keystore-format: change format
elastic/elasticsearch pull request #45222
Opened 2019-08-06 03:03 UTC by FreshOrangeXC

Closes #43835

2019-08-06 17:13 UTC, elasticmachine commented
Pinging @elastic/es-security

2019-08-07 06:25 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2019-08-07 06:33 UTC, tvernum commented
The lowercase requirement was intentionally added in https://github.com/elastic/elasticsearch/pull/27626, but at the time the keystore was implemented using a PKCS#12 keystore, which is no longer the case. 

There's the potential to relax that requirement now that the keystore uses a custom storage format with UTF strings.
@rjernst thoughts?

2019-08-07 18:17 UTC, rjernst commented
@tvernum You are correct this was a limitation from the time when we used PKCS#12.

@FreshOrangeXC Could you please update the test for this limitation in `KeyStoreWrapperTests.testIllegalSettingName()`? We can just change it to use a special character instead of upper case.

Also note this is not actually a format change, just a relaxing of restrictions on the tool itself.

2019-08-08 01:36 UTC, FreshOrangeXC commented
@rjernst Ok, I will do it.

2019-08-08 07:48 UTC, rjernst requested changes

2019-08-08 07:48 UTC, rjernst commented on distribution/tools/keystore-cli/src/test/java/org/elasticsearch/common/settings/AddStringKeyStoreCommandTests.java
> -    public void testUpperCaseInName() throws Exception {
We shoudl keep this test, but rename it and use a special character instead of uppercase.

2019-08-08 11:53 UTC, FreshOrangeXC reviewed
How to use the RandomizedTest class create a random special character? Or I just use a specific special character "@" like this commit?

2019-08-09 07:07 UTC, rjernst commented
@elasticmachine ok to test

2019-08-09 08:20 UTC, FreshOrangeXC commented
Oh, It seems test failed but I don't know why.

2019-08-09 14:14 UTC, rjernst commented
I think the branch needs to be synced with master.

@elasticmachine update branch

2019-08-09 22:33 UTC, rjernst commented
@elasticmachine update branch

2019-08-11 03:23 UTC, FreshOrangeXC commented
@elasticmachine update branch

2019-08-11 19:18 UTC, rjernst commented
There are a few build failures that need to be addressed. Another test has illegal setting name checking: `org.elasticsearch.common.settings.SettingsTests.testSecureSettingIllegalName`. Also, there are some checkstyle failures (line lengths and unused imports). Running `./gradlew :server:precommit :server:test` should allow you to reproduce the failures locally.

2019-08-12 04:42 UTC, FreshOrangeXC commented
I got it. I will solve it.

2019-08-13 06:01 UTC, FreshOrangeXC commented
@elasticmachine update branch

2019-08-13 06:01 UTC, elasticmachine commented
merge conflict between base and head

2019-08-13 09:33 UTC, FreshOrangeXC commented
@elasticmachine update branch

2019-08-14 03:13 UTC, FreshOrangeXC commented
@elasticmachine updata branch

2019-08-14 03:14 UTC, FreshOrangeXC commented
@elasticmachine update branch

2019-08-15 22:46 UTC, FreshOrangeXC commented
@rjernst Test passed.

2019-08-16 18:54 UTC, rjernst commented
@elasticmachine update branch

2019-08-17 00:48 UTC, merged

2019-08-17 00:49 UTC, rjernst commented
Thanks for the contribution @FreshOrangeXC!

2019-08-17 00:54 UTC, FreshOrangeXC commented
It is my pleasure to contribute to the open source.