Remove deprecated es.http.cname_in_publish_address setting
elastic/elasticsearch pull request #45616
Opened 2019-08-15 15:38 UTC by andrershov

Follow up on https://github.com/elastic/elasticsearch/pull/32806.

The system property `es.http.cname_in_publish_address` could be removed in master and I propose to backport this change to 7.x as well.
This property was added for BwC reasons and never was assumed to be set to false.

2019-08-15 15:40 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-08-15 15:55 UTC, original-brownbear requested changes
@andrershov Thanks for finding this!

I think we can't just remove this in the first PR? See the plan in https://github.com/elastic/elasticsearch/pull/32806#pullrequestreview-150949186 we need to first adjust the deprecation logging to say that this property does not have an effect anymore (and actually make it so like you did here). Then in another PR to `master` only we can remove that deprecation logging as well.

-> just keep the deprecation logger + adjust the message + then do a follow up ?

2019-08-16 14:38 UTC, andrershov commented
@original-brownbear correct, we need to log deprecation warning if the property is specified in 7.x.
I've updated the code and PR description and it's ready for the review.

2019-08-16 15:57 UTC, andrershov commented
run elasticsearch-ci/1

2019-08-21 16:40 UTC, original-brownbear approved these changes
LGMT after fixing the formatting change.

2019-08-21 16:40 UTC, original-brownbear commented on server/src/test/java/org/elasticsearch/http/HttpInfoTests.java
> +                new HttpInfo(
Revert noisy formatting change

2019-08-22 10:05 UTC, merged