[DOCS] Reformat get field mapping API docs
elastic/elasticsearch pull request #45700
Opened 2019-08-19 14:30 UTC by jrodewig

This PR updates the get field mapping API to align with the new [API reference template](https://github.com/elastic/docs/blob/master/shared/api-ref-ex.asciidoc).

Relates to elastic/docs#937 and #43765

Dependent on #45699.

2019-08-19 14:30 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-08-19 14:30 UTC, elasticmachine commented
Pinging @elastic/es-search

2019-08-19 14:30 UTC, elasticmachine commented
Pinging @elastic/es-core-features

2019-08-19 15:18 UTC, jrodewig commented
CI failures are expected until #45699 is merged.

2019-08-21 14:02 UTC, jrodewig commented
@elasticmachine update branch

2019-08-21 14:02 UTC, jrodewig commented
@elasticmachine update branch

2019-08-26 08:25 UTC, szabosteve requested changes
I think there might be some `{var}` in the piece that should be changed to `<var>`.

2019-08-26 08:25 UTC, szabosteve commented on docs/reference/indices/get-field-mapping.asciidoc
> +following syntax: `host:port/{index}/_mapping/field/{field}` where
Maybe we could change "{var}" to "< var >" in line 210-212, too.

2019-08-26 08:25 UTC, szabosteve commented on docs/reference/indices/get-field-mapping.asciidoc
> +following syntax: `host:port/{index}/_mapping/field/{field}` where
```suggestion
following syntax: `host:port/<index>/_mapping/field/<field>` where
```

2019-08-26 08:25 UTC, szabosteve commented on docs/reference/indices/get-field-mapping.asciidoc
> +`{index}` and `{field}` can stand for comma-separated list of names or wild cards. To
```suggestion
`<index>` and `<field>` can stand for comma-separated list of names or wild cards. To
```

2019-08-26 08:25 UTC, szabosteve commented on docs/reference/indices/get-field-mapping.asciidoc
> +get mappings for all indices you can use `_all` for `{index}`. The
```suggestion
get mappings for all indices you can use `_all` for `<index>`. The
```

2019-08-26 13:12 UTC, jrodewig commented
Good catches, @szabosteve!

2019-08-26 13:16 UTC, szabosteve approved these changes
Thanks!

LGTM!

2019-08-26 14:30 UTC, merged