[DOCS] Reformats search API
elastic/elasticsearch pull request #45786
Opened 2019-08-21 12:58 UTC by szabosteve

Relates to elastic/docs#937 and https://github.com/elastic/elasticsearch/issues/45621.

This PR updates the search API to align with the new [API reference template](https://github.com/elastic/docs/blob/master/shared/api-ref-ex.asciidoc).

Resources:
* [Search API spec](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/search.json)
* [Search API doc](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/search-search.html)

2019-08-21 12:59 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-08-21 13:37 UTC, jrodewig commented on docs/reference/search/search.asciidoc
> +`description`::
This isn't explicitly included in the JSON spec, but it's valid.
```suggestion
`query`::
```

2019-08-21 13:38 UTC, jrodewig commented on docs/reference/search/search.asciidoc
> +  (Optional, string) Defines the search definition using the Query DSL.
```suggestion
  (Optional, <<query-dsl,query object>>) Defines the search definition using the <<query-dsl,Query DSL>>.
```

2019-08-21 13:42 UTC, jrodewig commented on docs/reference/search/search.asciidoc
> +`allow_no_indices`::
You can replace this def with `include::{docdir}/rest-api/common-parms.asciidoc[tag=allow-no-indices]`

Added with #45699

2019-08-21 13:42 UTC, jrodewig commented on docs/reference/search/search.asciidoc
> +`expand_wildcards`::
You can replace this def with the following:

```
include::{docdir}/rest-api/common-parms.asciidoc[tag=expand-wildcards]
+
Defaults to `open`.
```

Will be added with #45699

2019-08-21 13:43 UTC, jrodewig commented on docs/reference/search/search.asciidoc
> +`ignore_unavailable`::
Replace with `include::{docdir}/rest-api/common-parms.asciidoc[tag=index-ignore-unavailable]`

2019-08-21 13:43 UTC, jrodewig requested changes
Couple of changes. Thanks again @szabosteve.

2019-08-22 08:44 UTC, szabosteve commented
Thanks for the review, @jrodewig. c7adf6c contains the changes you requested.

2019-08-22 12:38 UTC, jrodewig approved these changes
Thanks!

2019-08-22 13:04 UTC, merged

2019-08-22 13:10 UTC, szabosteve commented
Backported to 7.x and 7.3.