[DOCS] Reformats URI search request
elastic/elasticsearch pull request #45844
Opened 2019-08-22 14:03 UTC by szabosteve

Relates to elastic/docs#937 and https://github.com/elastic/elasticsearch/issues/45621.

This PR updates the URI search request API to align with the new [API reference template](https://github.com/elastic/docs/blob/master/shared/api-ref-ex.asciidoc).

Resources:
* [Search URI request API doc](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/search-uri-request.html)

2019-08-22 14:04 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-08-23 12:29 UTC, jrodewig commented on docs/reference/search/uri-request.asciidoc
> +`GET {index}/_search?q={parameter}`
In the Docs huddle, we agree to use the `<var>` convention going forward.

```suggestion
`GET /<index>/_search?q=<parameter>`
```

2019-08-23 12:30 UTC, jrodewig commented on docs/reference/search/uri-request.asciidoc
> +
Looks like we're missing the section for path parameters.

2019-08-23 12:30 UTC, jrodewig commented on docs/reference/search/uri-request.asciidoc
> +  Set to `false` to return an overall failure if the request would produce
```suggestion
(Optional, boolean)  Set to `false` to return an overall failure if the request would produce 
```

2019-08-23 12:31 UTC, jrodewig commented on docs/reference/search/uri-request.asciidoc
> +  Should wildcard and prefix queries be analyzed or not. Defaults to `false`.
```suggestion
(Optional, boolean)  Should wildcard and prefix queries be analyzed or not. Defaults to `false`.
```

2019-08-23 12:31 UTC, jrodewig commented on docs/reference/search/uri-request.asciidoc
> +  The analyzer name to be used when analyzing the query string.
```suggestion
(Optional, string) The analyzer name to be used when analyzing the query string.
```

2019-08-23 12:31 UTC, jrodewig commented on docs/reference/search/uri-request.asciidoc
> +  The number of shard results that should be reduced at once on the coordinating
```suggestion
  (Optional, integer) The number of shard results that should be reduced at once on the coordinating 
```

2019-08-23 12:31 UTC, jrodewig commented on docs/reference/search/uri-request.asciidoc
> +  The default operator to be used, can be `AND` or `OR`. Defaults to `OR`.
```suggestion
  (Optional, string) The default operator to be used, can be `AND` or `OR`. Defaults to `OR`.
```

2019-08-23 12:32 UTC, jrodewig commented on docs/reference/search/uri-request.asciidoc
> +  The default field to use when no field prefix is defined within the query.
```suggestion
  (Optional, string) The default field to use when no field prefix is defined within the query.
```

2019-08-23 12:34 UTC, jrodewig commented on docs/reference/search/uri-request.asciidoc
> +  For each hit, contain an explanation of how scoring of the hits was computed.
We'll need the `(Optional/Required, datatype)` for all the following parameters.

2019-08-23 12:37 UTC, jrodewig requested changes
I actually think this is the same API endpoint as https://www.elastic.co/guide/en/elasticsearch/reference/master/search-search.html.

We may just need to add any missing parameters and include an example in that documentation.

2019-08-27 12:56 UTC, szabosteve commented
@jrodewig Yes, it is the same endpoint. Furthermore, [request body search](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/search-request-body.html) also uses the same endpoint. I thought about documenting them together, but it would end in an extremely long reference page. Should I still merge these three pages together and delete the standalone versions of this API?

2019-08-27 23:40 UTC, debadair reviewed
Left some editorial comments because I was checking out the query parameters. Do we want to add the search related ones to common parameters?

2019-08-28 07:19 UTC, szabosteve commented on docs/reference/search/uri-request.asciidoc
> +
@debadair @jrodewig I think it's worth to add the search-related query parameters to the common parameters. I'll do it in a separate PR and add both of you as reviewers.

2019-08-28 08:19 UTC, szabosteve commented
Because of 7ae5fc8, this PR depends on #46057.

2019-08-28 16:15 UTC, jrodewig approved these changes
LGTM. Thanks for putting this together @szabosteve=.

2019-08-29 07:42 UTC, szabosteve commented
@elasticmachine test this please

2019-08-29 08:04 UTC, merged

2019-08-29 08:08 UTC, szabosteve commented
Backported to 7.x and 7.3.

2019-08-30 11:47 UTC, szabosteve commented
Backported to 7.x and 7.3.