Fix wrong URL encoding in watcher HTTP client
elastic/elasticsearch pull request #45894
Opened 2019-08-23 08:35 UTC by spinscale

The test assumption was calling the wrong method resulting in a URL
encoding before returning the data.

Closes #44970 (for real this time)

Reviewers note: This needs to be pushed to master, 7.x and 7.3

2019-08-28 16:14 UTC, jakelandis requested changes

2019-08-29 11:38 UTC, spinscale commented on x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/http/HttpClient.java
> +                            unescapedPathParts.add("");
yes. added a comment to clear things up

2019-08-29 18:16 UTC, jakelandis approved these changes
LGTM

2019-08-30 07:38 UTC, spinscale commented
@elasticmachine update branch

2019-08-30 10:02 UTC, spinscale commented
@elasticmachine run tests elasticsearch-ci/2

2019-08-30 10:12 UTC, spinscale commented
@elasticmachine run elasticsearch-ci/2

2019-08-30 12:02 UTC, merged