Improve documentation for X-Opaque-ID
elastic/elasticsearch pull request #46167
Opened 2019-08-30 10:10 UTC by pgomulka

this field can be present in search slow logs and deprecation logs. The
docs describes how to enable this functionality and what expect in logs.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2019-08-30 10:10 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2019-08-30 10:10 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-08-30 12:36 UTC, pgomulka commented
ok to test

2019-09-02 09:41 UTC, pgomulka commented
@jrodewig would you be able to have a look? I am having problems to passing a CI for this. Is there an issue with docs build atm?

2019-09-03 13:32 UTC, jrodewig commented on docs/reference/index-modules/slowlog.asciidoc
> +```
I'd rewrite this to use the Asciidoc source code blocks.

For example:
```
[source,txt]
----
[2019-08-30T11:59:37,786][WARN ][i.s.s.query              ] [node-0] [index6][0] took[78.4micros], took_millis[0], total_hits[0 hits], stats[], search_type[QUERY_THEN_FETCH], total_shards[1], source[{"query":{"match_all":{"boost":1.0}}}], id[MY_USER_ID],
----
```

Also consider replacing `[2019-08-30T11:59:37,786]` with a more future-proof timestamp like `[2030-08-30T11:59:37,786]`

2019-09-03 13:34 UTC, jrodewig commented on docs/reference/index-modules/slowlog.asciidoc
> +```
Also replace with a code block.
```
[source,js]
----
{
  "type": "index_search_slowlog",
  "timestamp": "2019-08-30T11:59:37,786+02:00",
  "level": "WARN",
  "component": "i.s.s.query",
  "cluster.name": "distribution_run",
  "node.name": "node-0",
  "message": "[index6][0]",
  "took": "78.4micros",
  "took_millis": "0",
  "total_hits": "0 hits",
  "stats": "[]",
  "search_type": "QUERY_THEN_FETCH",
  "total_shards": "1",
  "source": "{\"query\":{\"match_all\":{\"boost\":1.0}}}",
  "id": "MY_USER_ID",
  "cluster.uuid": "Aq-c-PAeQiK3tfBYtig9Bw",
  "node.id": "D7fUYfnfTLa2D7y-xw6tZg"
}
----
// NOTCONSOLE
```

2019-09-03 13:35 UTC, jrodewig commented on docs/reference/setup/logging-config.asciidoc
> +```
Replace with a code block

```
[source,js]
----
{
  "type": "deprecation",
  "timestamp": "2030-08-30T12:07:07,126+02:00",
  "level": "WARN",
  "component": "o.e.d.r.a.a.i.RestCreateIndexAction",
  "cluster.name": "distribution_run",
  "node.name": "node-0",
  "message": "[types removal] Using include_type_name in create index requests is deprecated. The parameter will be removed in the next major version.",
  "x-opaque-id": "MY_USER_ID",
  "cluster.uuid": "Aq-c-PAeQiK3tfBYtig9Bw",
  "node.id": "D7fUYfnfTLa2D7y-xw6tZg"
}
----
````

2019-09-03 13:36 UTC, jrodewig commented on docs/reference/index-modules/slowlog.asciidoc
> +will be present in Search Slow logs as an additional **id** field (scroll to the right).
```suggestion
is included in Search Slow logs as an additional **id** field (scroll to the right).
```

2019-09-03 13:37 UTC, jrodewig commented on docs/reference/index-modules/slowlog.asciidoc
> +It is often useful to identify what triggered a slow running query. If a call was initiated with an `X-Opaque-ID` header, then this value
```suggestion
It is often useful to identify what triggered a slow running query. If a call was initiated with an `X-Opaque-ID` header, then the user ID
```

2019-09-03 13:39 UTC, jrodewig commented on docs/reference/index-modules/slowlog.asciidoc
> +the same applies to JSON logs
```suggestion
The user ID is also included in JSON logs.
```

2019-09-03 13:39 UTC, jrodewig commented on docs/reference/setup/logging-config.asciidoc
> +You can identify who is triggering deprecated functionality if `X-Opaque-Id` was used as an HTTP header.
```suggestion
You can identify what is triggering deprecated functionality if `X-Opaque-Id` was used as an HTTP header.
```

2019-09-03 13:39 UTC, jrodewig commented on docs/reference/setup/logging-config.asciidoc
> +This field will be then present as `X-Opaque-ID` field in deprecation JSON logs.
```suggestion
The user ID is included in the `X-Opaque-ID` field in deprecation JSON logs.
```

2019-09-03 13:48 UTC, jrodewig commented
@elaticmachine run elasticsearch-ci/docs

2019-09-03 13:54 UTC, jrodewig commented
@elasticmachine update branch

2019-09-03 13:56 UTC, jrodewig requested changes
Left a few suggestions about changing the snippets to Asciidoc code blocks.

Also left some less important editorial changes. Please feel free to take/discard those as you see fit. 

Thanks!

2019-09-03 14:47 UTC, jrodewig commented on docs/reference/index-modules/slowlog.asciidoc
> +==== Identifying search slow log origin
```suggestion
[float]
==== Identifying search slow log origin
```

2019-09-04 12:48 UTC, jrodewig approved these changes
LGTM. Thanks @pgomulka!

2019-09-04 13:48 UTC, merged

2019-09-09 03:21 UTC, luyuncheng commented
LGTM