Document removing data nodes
elastic/elasticsearch pull request #46355
Opened 2019-09-04 22:23 UTC by rwaight

Document guidance on the removal / decommissioning of data nodes in `adding-removing-nodes.asciidoc`

Closes https://github.com/elastic/elasticsearch/issues/46338

2019-09-04 22:23 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-09-04 22:23 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-09-05 00:08 UTC, lcawl commented
You can preview the changes here:
http://elasticsearch_46355.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/7.3/modules-discovery-adding-removing-nodes.html

As a drive-by comment, I wonder if this information shouldn't be migrated here:
https://www.elastic.co/guide/en/elasticsearch/reference/master/add-elasticsearch-nodes.html

2019-09-17 16:57 UTC, debadair requested changes
Left some suggestions. I'd go ahead and add this information here for now, but avoid using the modules prefix in the anchor.

2019-09-17 16:57 UTC, debadair commented on docs/reference/modules/discovery/adding-removing-nodes.asciidoc
> +1. Validate node settings, including allocation <<allocation-awareness>> configurations
It isn't clear here just what you need to "validate". I'd provide a bit more detail--something like, "If you use custom node attributes to control where Elasticsearch allocates shards, make sure that those awareness attributes are configured on other nodes in the cluster."

.

2019-09-17 16:57 UTC, debadair commented on docs/reference/modules/discovery/adding-removing-nodes.asciidoc
> +# supported attributes:  `_name`, `_ip`, and `_host`
In general, we avoid including comments in the example snippets in favor of incorporating the content into the intro or using callouts. It's not necessary to repeat what can easily be gleaned by reading the example itself.

2019-09-17 16:57 UTC, debadair commented on docs/reference/modules/discovery/adding-removing-nodes.asciidoc
> +  }
Update the node name to match the lead-in:

`    "cluster.routing.allocation.exclude._name" : "prod-data-2"`

2019-09-17 16:57 UTC, debadair commented on docs/reference/modules/discovery/adding-removing-nodes.asciidoc
> +4. Monitor the cluster to ensure all primary shards have been allocated onto other nodes
The past-tense doesn't quite fit here. I'd say, "Monitor the cluster to ensure all primary shards are successfully migrated to other nodes."

2019-09-17 16:57 UTC, debadair commented on docs/reference/modules/discovery/adding-removing-nodes.asciidoc
> +5. Once the cluster is healthy and all shards have been reallocated to other nodes, turn off the elasticsearch service of the node being removed, then the node can be shut down/decommissioned
It's not necessary to reiterate the previous step. I'd just say, "Once the migration is complete and the cluster state is green, you can safely shut down the node."

2019-09-17 16:57 UTC, debadair commented on docs/reference/modules/discovery/adding-removing-nodes.asciidoc
> ++
I'd probably say something like, "Update the cluster's shard allocation settings to exclude the node you want to remove. This instructs Elasticsearch to migrate shards off of the node. You can specify the node by name, IP address, or host. For example, the following request excludes `prod-data-2`:

2020-05-20 07:27 UTC, colings86 commented
@rwaight  are you still wanting to progress this PR or should it be closed?

2020-08-12 09:00 UTC, colings86 commented
I'm going to close this PR since there has been no activity in 11 months.

2020-08-12 09:00 UTC, closed without merging