[DOCS] Reformats count API
elastic/elasticsearch pull request #46377
Opened 2019-09-05 12:57 UTC by szabosteve

Relates to elastic/docs#937 and https://github.com/elastic/elasticsearch/issues/45621.

This PR updates the count API to align with the new [API reference template](https://github.com/elastic/docs/blob/master/shared/api-ref-ex.asciidoc).

Resources:
* [Count API spec](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/count.json)
* [Count API doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html)

2019-09-05 12:57 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-09-09 15:36 UTC, jrodewig commented on docs/reference/search/count.asciidoc
> +[source,js]
```suggestion
[source,console]
```

This recently changed with #46189.

2019-09-09 15:36 UTC, jrodewig commented on docs/reference/search/count.asciidoc
> +//CONSOLE
```suggestion
// TEST[setup:twitter]
```

This is likely causing the CI to fail.

`//CONSOLE`  is no longer needed with `[source,console].

2019-09-09 15:36 UTC, jrodewig commented on docs/reference/search/count.asciidoc
> +`ignore_throttled`::
Can we move this to `common-parms.asciidoc`?

Looks like this parameter is also used here:

- https://www.elastic.co/guide/en/elasticsearch/reference/master/search-template.html#search-template-api-query-params
- https://www.elastic.co/guide/en/elasticsearch/reference/master/search-search.html#search-search-api-query-params

2019-09-09 15:36 UTC, jrodewig commented on docs/reference/search/count.asciidoc
> +  Sets the minimum `_score` value that documents must have to be included in the
```suggestion
(Optional, float)
  Sets the minimum `_score` value that documents must have to be included in the 
```

2019-09-09 15:36 UTC, jrodewig commented on docs/reference/search/count.asciidoc
>  [source,js]
```suggestion
[source,console]
```

This is actually required as the `//CONSOLE` comment was deleted below this.

2019-09-09 15:37 UTC, jrodewig commented on docs/reference/search/count.asciidoc
>  [source,js]
```suggestion
[source,console-result]
```

You can also remove the `// TESTRESPONSE` comment below this.

2019-09-09 15:37 UTC, jrodewig requested changes
Left a few comments that should help fix the CI.

2019-09-16 18:16 UTC, jrodewig commented on docs/reference/search/count.asciidoc
> +include::{docdir}/rest-api/common-parms.asciidoc[tag=expand-wildcards]
```suggestion
include::{docdir}/rest-api/common-parms.asciidoc[tag=expand-wildcards]
+
Defaults to `open`.
```

2019-09-16 18:17 UTC, jrodewig approved these changes
Left a few minor comments but generally LGTM.

2019-09-17 07:53 UTC, merged

2019-09-17 07:58 UTC, szabosteve commented
Backported to 7.x, 7.4, and 7.3.