[DOCS] add missing mention of current version to snapshot docs
elastic/elasticsearch pull request #46516
Opened 2019-09-09 22:58 UTC by geekpete

It's come up a couple of times that the current docs for snapshot compatibility
don't mention the current versions.
There's likely a reworking of this page to come but just plugging this gap
to reduce any confusion or doubt around version compatibility in the meantime.
Requires backport to all 7.x branches.

2019-09-09 22:58 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-09-11 13:24 UTC, jrodewig commented on docs/reference/modules/snapshots.asciidoc
>  or 6.x, and snapshots of indices created in 2.x **cannot** be restored to 6.x.
```suggestion
or 6.x, snapshots of indices created in 2.x **cannot** be restored to 6.x
```

2019-09-11 13:31 UTC, jrodewig requested changes
Left some needed grammatical corrections.

I also think this convention is getting a little unwieldy, but that's a separate problem from including the latest info. Created #46596 to address the information design issue.

Thanks @geekpete!

2019-09-12 12:22 UTC, jrodewig approved these changes
LGTM. Thanks.

I'll merge and backport this.

2019-09-12 12:30 UTC, merged

2019-09-17 07:51 UTC, colings86 commented
It looks like the backporting is complete here so I have removed the backport pending label while generating 7.4.0 release notes. Please let me know if this is wrong