Implement rounding optimization for fixed offset timezones
elastic/elasticsearch pull request #46670
Opened 2019-09-12 13:55 UTC by csoulios

Fixes #45702 with date_histogram aggregation when using `fixed_interval`. 

Implement code change discussed at:
https://github.com/elastic/elasticsearch/issues/45702#issuecomment-530775309

Optimization has been implemented for both fixed and calendar intervals

2019-09-12 14:05 UTC, spinscale requested changes
As I am unsure about the performance implications, maybe resurrecting the `RoundingBenchmark` for testing from the 7.x branch makes sense here (or just test on the 7.x branch then port)

2019-09-12 16:06 UTC, jimczi requested changes
Thanks @csoulios , the changes look good, I left some comments

2019-09-13 11:37 UTC, csoulios commented on server/src/main/java/org/elasticsearch/common/Rounding.java
> +            if (timeZone.getRules().isFixedOffset() == true) {
Moved this to constructor as discussed. Benchmark results improved by ~12%.

See results below (right column is the newer revision):

```|                                       50th percentile latency | query-agg-date_histogram |     2892.92 |     2539.31 | -353.609 |     ms |
|                                       90th percentile latency | query-agg-date_histogram |     3086.98 |     2762.28 | -324.694 |     ms |
|                                      100th percentile latency | query-agg-date_histogram |     3182.51 |     2865.38 | -317.137 |     ms |
|                                  50th percentile service time | query-agg-date_histogram |     2885.19 |     2532.11 | -353.078 |     ms |
|                                  90th percentile service time | query-agg-date_histogram |     3078.69 |     2755.39 | -323.297 |     ms |
|                                 100th percentile service time | query-agg-date_histogram |     3174.46 |     2857.74 | -316.713 |     ms |```

2019-09-13 12:53 UTC, csoulios commented
I ran ES Rally benchmark (https://github.com/csoulios/date_histogram-benchmark) for the following scenarios (on my laptop): 
* ES 6..8.0, UTC tz
* ES 8.x (with fix), UTC tz
* ES 8.x (with fix), -01:00 tz
* ES 8.x (with fix), Europe/Berlin tz

All produced similar results:
```
|-------------------------------+--------------------------+-------------+-----------+--------------+---------------------|
| Metric                        | Task                     | 6.8.0 (UTC) | 8.x (UTC) | 8.x (-01:00) | 8.x (Europe/Berlin) |
|-------------------------------+--------------------------+-------------+-----------+--------------+---------------------|
|      50th percentile latency | query-agg-date_histogram |      2570.75 |   2539.31 |      2687.07 |             2583.18 |  
|      90th percentile latency | query-agg-date_histogram |      2666.16 |   2762.28 |      2764.50 |             2674.80 |
|     100th percentile latency | query-agg-date_histogram |      2780.84 |   2865.38 |      2786.68 |             2898.41 | 
|-------------------------------+--------------------------+-------------+-----------+--------------+---------------------|
```

2019-09-13 14:33 UTC, jimczi approved these changes
LGTM, thanks @csoulios

2019-09-16 07:04 UTC, spinscale approved these changes
left a few minor nits, feel free to ignore them

LGTM otherwise, thanks for fixing!

2019-09-16 07:04 UTC, spinscale commented on server/src/main/java/org/elasticsearch/common/Rounding.java
> +        private final long fixedOffset;
ignoreable nit: maybe name this fixedOffsetMs or something to indicate its contents

2019-09-16 07:04 UTC, spinscale commented on server/src/main/java/org/elasticsearch/common/Rounding.java
> +        static final long TZ_OFFSET_NON_FIXED = -1;
comment nit: maybe include a small comment what `-1` indicates, and why this can never be -1 in a regular offset

2019-09-16 07:04 UTC, spinscale commented on server/src/main/java/org/elasticsearch/common/Rounding.java
> +        static final long TZ_OFFSET_NON_FIXED = -1;
minor nit: would one instance of this be enough?

2019-09-16 07:04 UTC, spinscale commented on server/src/main/java/org/elasticsearch/common/Rounding.java
> +        static final long TZ_OFFSET_NON_FIXED = -1;
minor nit: can be private?

2019-09-16 16:20 UTC, matriv commented
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

2019-09-16 20:16 UTC, merged