max_children exist only in top level nested sort
elastic/elasticsearch pull request #46731
Opened 2019-09-15 16:17 UTC by erayarslan

**FIX**
related with (https://github.com/elastic/elasticsearch/pull/33587#discussion_r222654589)

If we have query like that;
```javascript
GET /products/_search
{
  "sort": [
    {
      "variants.listings.price": {
        "order": "desc",
        "nested": {
          "path": "variants",
          "nested": {
            "max_children": 1,
            "path": "variants.listings"
          }
        }
      }
    }
  ]
}
``` 

Elastic going to ignore max_children=1, cause we passed top level nested sort object in here (example flow);
https://github.com/elastic/elasticsearch/blob/3f18cf74ac3e86907a0c73e53374dafa233d6268/server/src/main/java/org/elasticsearch/search/sort/FieldSortBuilder.java#L334-L340

https://github.com/elastic/elasticsearch/blob/3f18cf74ac3e86907a0c73e53374dafa233d6268/server/src/main/java/org/elasticsearch/search/sort/SortBuilder.java#L173-L186

https://github.com/elastic/elasticsearch/blob/3f18cf74ac3e86907a0c73e53374dafa233d6268/server/src/main/java/org/elasticsearch/index/fielddata/fieldcomparator/FloatValuesComparatorSource.java#L69-L74

So i think we must use max_children on top level nested sort or we need to pass last level nested sort.

In this PR, I allow to max_children on top level nested sort.

2019-09-18 06:51 UTC, elasticmachine commented
Pinging @elastic/es-search

2019-09-18 07:19 UTC, jimczi requested changes
Good catch @erayarslan , I left a minor comment but the change looks good.

2019-09-18 07:19 UTC, jimczi commented on server/src/test/java/org/elasticsearch/search/sort/FieldSortIT.java
> +        try {
Can you use `LuceneTestCase#expectThrows` for the check below in order to ensure that an exception is thrown ?

2019-09-18 10:33 UTC, erayarslan commented
Thanks @jimczi , I updated integration test.

Can you please take a look?

2019-09-20 06:45 UTC, jimczi commented
@elasticmachine test this please

2019-09-20 07:18 UTC, erayarslan commented
CI failed. I think my branch outdated. Now, its okay.
Can you trigger CI again? @jimczi

2019-09-20 07:26 UTC, jimczi commented
@elasticmachine test this please

2019-09-23 16:45 UTC, jimczi approved these changes
LGTM, thanks @erayarslan

2019-09-23 16:46 UTC, merged

2019-09-23 17:57 UTC, erayarslan commented
thank you for your time @jimczi