Extract proxy connection logic to specialized class
elastic/elasticsearch pull request #46898
Opened 2019-09-20 03:58 UTC by tbrooks8

Currently the logic to check if a connection to a remote discovery node
exists and otherwise create a proxy connection is mixed with the
collect nodes, cluster connection lifecycle, and other
RemoteClusterConnection logic. This commit introduces a specialized
RemoteConnectionManager class which handles the open connections.
Additionally, it reworks the "round-robin" proxy logic to create the list
of potential connections at connection open/close time, opposed to each
time a connection is requested.

2019-09-20 03:59 UTC, elasticmachine commented
Pinging @elastic/es-distributed

2019-09-20 12:27 UTC, ywelsch requested changes
I've left some comments around the caching of connections.

2019-09-20 12:27 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/transport/RemoteConnectionManager.java
> +                    addConnection(newConnection);
If possible, I think we should purely rely on the TransportConnectionListener events to add and remove nodes, and not manually recreate that logic. In particular, the logic as it stands here has a problem (see comment below in `removeConnection`). If need be, we can add for example extend the `TransportConnectionListener.onNodeConnected` method to also contain the `Connection` object as parameter.

Note that this also means that we need strong guarantees from the TransportConnectionListener, the order in which its methods are called (I don't think we have that today) and should also have additional tests on that.

2019-09-20 12:27 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/transport/RemoteConnectionManager.java
> +                              ActionListener<Void> listener) throws ConnectTransportException {
the listener here is never called on success?

2019-09-20 12:27 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/transport/RemoteConnectionManager.java
> +        assert newConnections.size() == newSize : "Expected connection count: " + newSize + ", Found: " + newConnections.size();
We can sometimes get two close events if we have two concurrent calls to `connectToNode` for the same node which give us the same connection object. Only one of these close calls removes the connections, the other becomes a NOOP and trips this assertion.

2019-09-25 08:45 UTC, ywelsch commented
There are merge conflicts here (after merging your other PR). Can you bring the PR up-to-date? I will have another look then.

2019-09-25 13:47 UTC, tbrooks8 commented
> There are merge conflicts here (after merging your other PR). Can you bring the PR up-to-date? I will have another look then.

I merged.

2019-09-25 16:41 UTC, ywelsch approved these changes
LGTM

2019-09-25 16:50 UTC, merged