shard allocation filtering add more support attributes
elastic/elasticsearch pull request #46992
Opened 2019-09-24 03:37 UTC by weizijun

Both Index-level and Cluster-level share the same filtering attributes.

 add `_id` attributes description in [Index-level shard allocation filtering](https://www.elastic.co/guide/en/elasticsearch/reference/master/shard-allocation-filtering.html)  and full attributes description in [Cluster-level shard allocation filtering](https://www.elastic.co/guide/en/elasticsearch/reference/master/allocation-filtering.html)

2019-09-24 07:37 UTC, elasticmachine commented
Pinging @elastic/es-docs

2019-09-24 07:38 UTC, atorok commented
@elasticmachine test this please

2019-10-01 04:04 UTC, weizijun commented
@atorok hi, can you reivew this doc?

2019-10-01 06:55 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2019-11-05 08:42 UTC, weizijun commented
@jasontedor can you help review  this doc?

2019-11-16 01:28 UTC, jasontedor requested changes
Thanks for picking this up. I left some minor feedback.

2019-11-16 01:28 UTC, jasontedor commented on docs/reference/index-modules/allocation/filtering.asciidoc
> +`_name`::       Match nodes by node names
I think that this should remain `name`.

2019-11-16 01:28 UTC, jasontedor commented on docs/reference/index-modules/allocation/filtering.asciidoc
> +`_id`::         Match nodes by node ids
`ids` -> `id`

2019-11-16 01:28 UTC, jasontedor commented on docs/reference/modules/cluster/allocation_filtering.asciidoc
> +`_host`::       Match nodes by hostnames
`hostnames` -> `hostname`

2019-11-16 01:28 UTC, jasontedor commented on docs/reference/modules/cluster/allocation_filtering.asciidoc
> +`_id`::         Match nodes by node ids
`ids` -> `id`

2019-11-16 01:28 UTC, jasontedor commented on docs/reference/modules/cluster/allocation_filtering.asciidoc
> +`_ip`::         Match nodes by IP addresses (the IP address associated with the hostname)
`Match nodes by IP addresses (the IP address associated with the hostname)` -> `Match either `_host_ip` or `_publish_ip`

2019-11-16 01:28 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/Allocation)

2019-11-20 07:30 UTC, weizijun commented
@jasontedor thank you for review.  _id can pass some ids, like "_id" : "id1,id2,id3", so I used ids. Can I needed to change to name\id?

2019-11-20 23:42 UTC, jasontedor commented
A node only has one name, ID, etc. We are matching nodes by their name, not by their node names.

2019-11-21 02:40 UTC, weizijun commented
> A node only has one name, ID, etc. We are matching nodes by their name, not by their node names.

thank you, I got it. I will change my commit.

2019-11-21 13:27 UTC, jasontedor approved these changes
LGTM. Thank you!

2019-11-21 13:29 UTC, merged