Cache between cluster state changes, allow checking of specific settings
elastic/elasticsearch pull request #47244
Opened 2019-09-27 18:28 UTC by danhermann

These two changes allow the `ConsistentSettingsService` to be used with the new hash processor:

1. The hash processor must ensure that its hash key is consistent on every execution, so caching the consistency of settings between cluster state changes means that the hash processor can call `areAllConsistent` frequently.
1. The hash processor should fail only if its own hash key is inconsistent, not if other unrelated settings are inconsistent. The overloaded `areAllConsistent(Collection<Setting<?>>)` method allows the hash processor to query the consistency of only the settings that are relevant to it.

2019-09-30 15:59 UTC, elasticmachine commented
Pinging @elastic/es-core-infra

2019-09-30 16:01 UTC, danhermann commented
@elastic/es-core-infra, I'd appreciate any input on this approach to adapting `ConsistentSettingsService` for use with the hash processor. If this approach is acceptable, I can fix the one remaining IT that is failing.

2019-10-04 16:12 UTC, jakelandis requested changes
A couple comments .. the larger question is do we need the cache and cluster state listener ?

2019-10-04 16:12 UTC, jakelandis commented on server/src/main/java/org/elasticsearch/common/settings/ConsistentSettingsService.java
> +    private volatile Map<String, Boolean> consistencyCache;
Do we need this cache, and do we need to populate it on cluster state change ?  I see it the cluster state work is protected by a change in master node ids, but it seems that a simpler solution is check the consistency every time with every call to `areAllConsistent`

2020-03-03 16:14 UTC, danhermann commented
Closing as these changes will not be necessary for the hash processor.

2020-03-03 16:14 UTC, closed without merging