Introduce simple remote conneciton strategy
elastic/elasticsearch pull request #47480
Opened 2019-10-02 23:45 UTC by tbrooks8

This commit introduces a simple remote connection strategy which will
open remote connections to a configurable list of user supplied
addresses. These addresses can be remote Elasticsearch nodes or
intermediate proxies. We will perform normal clustername and version
validation, but otherwise rely on the remote cluster to route requests
to the appropriate remote node.

2019-10-02 23:45 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/Network)

2019-10-07 07:09 UTC, ywelsch requested changes
Thanks for the PR. I've left some suggestions for code simplification

2019-10-07 07:09 UTC, ywelsch commented on server/src/test/java/org/elasticsearch/transport/SimpleConnectionStrategyTests.java
> +                    assertFalse(connectionManager.getAllConnectedNodes().stream().anyMatch(n -> n.getAddress().equals(address2)));
Can we check how many connections have been established?

2019-10-07 07:09 UTC, ywelsch commented on server/src/test/java/org/elasticsearch/transport/SimpleConnectionStrategyTests.java
> +            return Arrays.stream(addresses)
why not always return this? Doesn't this work for the `length = 0` and `length = 1` cases?

2019-10-07 07:09 UTC, ywelsch commented on server/src/test/java/org/elasticsearch/transport/SimpleConnectionStrategyTests.java
> +                    assertFalse(connectionManager.getAllConnectedNodes().stream().anyMatch(n -> n.getAddress().equals(address2)));
Can we check the number of connection attempts?

2019-10-08 02:53 UTC, tbrooks8 commented
@ywelsch i updated this PR for your comments.

2019-10-08 11:52 UTC, ywelsch approved these changes
I've left some nits, otherwise looking good.

2019-10-08 11:52 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/transport/RemoteConnectionStrategy.java
> +    static Predicate<ClusterName> getRemoteClusterNamePredicate(ClusterName remoteClusterName) {
this is only used by SniffConnectionStrategy now. Move it back down?

2019-10-08 11:52 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/transport/SimpleConnectionStrategy.java
> +
extra newline

2019-10-08 11:52 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/transport/SimpleConnectionStrategy.java
> +                finished.onFailure(new IllegalStateException("Unable to open any simple connections to remote cluster"));
mention remote cluster name here?

2019-10-08 11:52 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/transport/SimpleConnectionStrategy.java
> +                logger.trace("unable to open maximum number of connections [opened: {}, maximum: {}]", openConnections,
mention remote cluster name here, and log at debug level?

trace is for expected things, debug for more unusual stuff

2019-10-08 11:52 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/transport/SimpleConnectionStrategy.java
> +                        logger.debug(() -> new ParameterizedMessage("failed to open remote connection to address {}", address), e);
mention cluster name here

2019-10-08 11:52 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/transport/SimpleConnectionStrategy.java
> +    private ConnectionManager.ConnectionValidator clusterNameValidator(DiscoveryNode node) {
let's remove the `node` parameter here and have a single instance of the `ConnectionValidator` initialized in the constructor. The node here is not that useful, and you can get it from the connection (`newConnection.getNode()`).

2019-10-08 18:28 UTC, merged

2019-12-06 17:39 UTC, fpytloun commented
This is great feature, thank you.
Can you please post example configuration to switch existing setup to using simple strategy?

2019-12-06 22:10 UTC, tbrooks8 commented
@fpytloun The meta issue is here #49067. As you can see, the work is scoped for 7.6 although things can always change.

Currently the "simple" work is currently available on either 7.6 or 8.0 snapshot builds.

It can be configured:

```
// If you do not configure a mode, it will default to the existing sniff implementation
cluster.remote.test_remote_cluster.mode: "simple"
cluster.remote.test_remote_cluster.simple.addresses: ["address:port"]
```

Please note that it is still in active development. For example, we are still debating whether we want to name it "simple" or "proxy" (the primary advantage of this mode over sniff is for routing through a proxy to unaddressable nodes).

You can follow any updates on the meta issue and the documentation will be updated before any release where this feature is GA.