Add aws KMS encryption in the elastic search repository-s3 plugin
elastic/elasticsearch pull request #47486
Opened 2019-10-03 05:59 UTC by Prasannasaraf

2019-10-03 06:41 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/Snapshot/Restore)

2019-10-03 09:37 UTC, satishdash requested changes

2019-10-03 09:37 UTC, satishdash commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java
> +            return true;
Can be simplified into:
```
return sseAwsKeyId == null || sseAwsKeyId.trim().isEmpty()
```

2019-10-03 10:13 UTC, satishdash approved these changes

2019-10-03 12:01 UTC, original-brownbear requested changes
Thanks for this PR @Prasannasaraf !

I left a few comments/questions on the exact mechanics of how the new setting should work.

Also, we definitely have to add a 3rd party test for this that runs if the appropriate environment variable is set. Something along the lines of what we did for Azure SAS tokens is probably what we want here (see https://github.com/elastic/elasticsearch/pull/42982/files#diff-972bd167c62a9bf3a9bf9a80d6ea2298R79).

I also wonder if we sohuld make setting an `endpoint` on a repo or client mutually exclusive with using KMS on the settings layer already since this won't work with non-AWS S3 endpoints anyway?

2019-10-04 13:04 UTC, tlrx commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
> +    static final Setting<String> AWS_KMS_KEY = Setting.simpleString("aws_kms_key");
If we want to add support for KMS then I think we need smarter settings that allow to distinguish between server side encryption using AES256, SSE with KMS and default key and SSE with KMS and specific key id.

> I'd also like a second opinion here (@ywelsch, @tlrx maybe?) on whether or not this should be a secure setting.

I tend to think that it should be a secured setting. I also think that it should be correctly documented as we don't want users to remove or update keys and not being able to decrypt data afterwards? Also, @albertzaharovits might have an opinion on this.

2019-10-09 06:04 UTC, Prasannasaraf commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobContainer.java
>          if (blobStore.serverSideEncryption()) {
Should we put a warning if sse is disabled but KMS key is set and continue?

2019-10-09 12:11 UTC, albertzaharovits commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
> +    static final Setting<String> AWS_KMS_KEY = Setting.simpleString("aws_kms_key");
I don't think the key identifier should be a secure setting. It's just an identifier, and I think that putting it in the keystore creates unnecessary complications for the user.

2019-10-09 12:20 UTC, albertzaharovits commented on plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
> +    static final Setting<String> AWS_KMS_KEY = Setting.simpleString("aws_kms_key");
Also, from https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html I see that the API has complexish rules:
```
x-amz-server-side​-encryption
x-amz-server-side-encryption-aws-kms-key-id
x-amz-server-side-encryption-context

Note:
If you specify x-amz-server-side-encryption:aws:kms, but don't provide x-amz-server-side- encryption-aws-kms-key-id, Amazon S3 uses the default AWS KMS key to protect the data.
```

that don't really make much sense to me.

I would think to whitelist these request headers, together with `x-amz-server-side​-encryption​-customer-algorithm`, `x-amz-server-side​-encryption​-customer-key`, `x-amz-server-side​-encryption​-customer-key-MD5` from below, and delegate the responsibility to the user to validate them. What do you think?

2019-11-25 08:53 UTC, original-brownbear commented
Hi @Prasannasaraf,

sorry for the delay here. As I said in my last comment, this will require adding some actual third party tests against real AWS S3 to validate that it works. Are you interested in working on those and continuing here? (I realize that this is a non-trivial amount of effort on top of the actual change so no worries if not.)

2019-12-02 14:36 UTC, Prasannasaraf commented
Hi @original-brownbear 

I can work on adding third-party tests along with the changes suggested by @albertzaharovits. Do let me know the amount of work involved here.

2020-11-20 20:20 UTC, jstolle commented
Is there an ETA on the completion of this merge?

2024-05-30 10:35 UTC, wywywywy commented
Is this ever going to get merged?

2024-05-30 10:48 UTC, closed without merging