Update logging-config.asciidoc make it possible to directly remove deprecations logs without further googling.
elastic/elasticsearch pull request #47508
Opened 2019-10-03 13:33 UTC by nicholasklem

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2019-10-03 14:39 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (:Core/Infra/Logging)

2019-10-03 14:39 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2019-10-04 04:22 UTC, rjernst commented
@pgomulka Can you please review this?

2019-10-04 07:08 UTC, pgomulka commented
@elasticmachine ok to test

2019-10-04 09:11 UTC, pgomulka requested changes
it looks good! thank you for improving. I left few comments

2019-10-04 09:11 UTC, pgomulka commented on docs/reference/setup/logging-config.asciidoc
> +```
```suggestion
[source,properties]
--------------------------------------------------
```

2019-10-04 09:11 UTC, pgomulka commented on docs/reference/setup/logging-config.asciidoc
> +```
```suggestion
--------------------------------------------------
```

2019-10-04 09:11 UTC, pgomulka commented on docs/reference/setup/logging-config.asciidoc
> +...
I guess the context is clear that this is part of a bigger config. How about we remove the ... ?

2019-10-07 08:25 UTC, pgomulka commented
ok to test

2019-10-07 08:49 UTC, pgomulka commented
ok to test

2019-10-07 08:50 UTC, pgomulka commented
ok to test

2019-10-07 08:51 UTC, pgomulka commented
@elasticmachine run elasticsearch-ci/1

2019-10-07 09:42 UTC, pgomulka commented
@elasticmachine run elasticsearch-ci/1

2019-10-07 10:13 UTC, merged

2019-10-07 13:28 UTC, pgomulka commented
@nicholasklem once again - thank you for updating this. I have merged your change and will update the corresponding branches in older versions