[Docs] Fix typos and minor grammar mistakes
elastic/elasticsearch pull request #47512
Opened 2019-10-03 15:45 UTC by glenacota

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? ✅ 
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)? ✅

2019-10-15 19:23 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2019-10-15 20:24 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (:Core/Infra/Scripting)

2019-10-17 21:06 UTC, jrodewig commented on docs/painless/painless-guide/painless-datetime.asciidoc
> +call on a field within the `doc` input to ensure that a field has at least one
I believe the previous change was a bit more clear.

`that field` refers to the field on which the `size` method was called. Here's my recommendation:

> call on a field within the `doc` input to ensure the field has at least one

2019-10-17 21:08 UTC, jrodewig requested changes
Looks good overall. I left a comment for one of the suggested changes.

After that is addressed, I can merge this and port to other branches. Thank you @glenacota.

2019-10-17 21:08 UTC, jrodewig commented
@elasticmachine test this please

2019-12-10 17:25 UTC, jrodewig commented
Hi @glenacota. Do you plan to address the feedback listed here?

If not, I'll close this PR and treat it as a bug report.

Thanks again for your contribution.

2020-01-02 16:55 UTC, jrodewig commented
Closing due to lack of response. Treating as a bug report.

2020-01-02 16:55 UTC, closed without merging

2020-02-29 10:39 UTC, glenacota commented
Apologies for disappearing, and thanks for having taken care of it.