Remove option to enable direct buffer pooling
elastic/elasticsearch pull request #47956
Opened 2019-10-11 22:06 UTC by tbrooks8

This commit removes the option to change the netty system properties to
reenable the direct buffer pooling. It also removes the need for us to
disable the buffer pooling in the system properties file. Instead, we
programmatically craete an allocator that is used by our networking
layer.

This commit does introduce an Elasticsearch property which allows the
user to fallback on the netty default allocator. If they choose this
option, they can configure the default allocator how they wish using the
standard netty properties.

2019-10-11 22:06 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/Network)

2019-10-11 22:10 UTC, tbrooks8 commented
When we disable direct buffer pooling in 7.4, we agreed that once it was determined to be stable we could remove the fallback mode. This commit moves to a world where we programmatically assign the buffer allocator and do not use the default netty one. 

This commit does add a system property to allow expert users to fallback on the netty allocator (and therefore configure it how they like).

We still need to discuss this. The name of the system property is tentative. And this has some friction with the "unpooled" system property which we currently apply. We should perhaps move to a world where JvmErgonomics just tells us if we should use the unpooled allocator. However, then this has some tension with testing (we could add an Elasticsearch system property for the unpooled allocator the tests apply `es.allocator.unpooled` or something).

2019-10-14 16:58 UTC, original-brownbear commented
> allows the user to fallback on the netty default allocator.

I wonder if we should even allow this? I'm having a hard time seeing any situation where this would be helpful. On the other hand, if we keep this option around we have to continue to support/test it.
I think I'd rather just stick with `CopyBytesSocketChannel` since that seems to work in a safe and stable way now and keep it simple unless there's a good example for a situation where manually overriding the details of the allocator would be helpful?

2019-10-18 16:04 UTC, ywelsch requested changes
I've left some minor comments, o.w. looking good

2019-10-18 16:04 UTC, ywelsch commented on modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
> +        serverBootstrap.channel(CopyBytesServerSocketChannel.class);
Why can we unconditionally set this now? Shouldn't we check with the `NettyAllocator.ALLOCATOR`?

2019-10-18 16:04 UTC, ywelsch commented on distribution/tools/launchers/src/main/java/org/elasticsearch/tools/launchers/JvmErgonomics.java
> +        if (systemProperties.containsKey("es.unsafe.use_unpooled_allocator") == false) {
this setting does not need the unsafe prefix, that's only relevant for `es.unsafe.use_netty_default_allocator`

2019-10-20 08:11 UTC, original-brownbear reviewed
Just one comment on the test http client change, otherwise looks good :)

2019-10-20 08:11 UTC, original-brownbear commented on modules/transport-netty4/src/main/java/org/elasticsearch/transport/NettyAllocator.java
> +            // TODO: Currently the Netty SslHandler requests direct ByteBufs even when interacting with the
NIT: Maybe link the relevant Netty issue in the TODO?

2019-10-20 08:11 UTC, original-brownbear commented on modules/transport-netty4/src/main/java/org/elasticsearch/transport/NettyAllocator.java
> +            return delegate.isDirectBufferPooled();
`return false;` ?

2019-10-20 08:11 UTC, original-brownbear commented on modules/transport-netty4/src/test/java/org/elasticsearch/http/netty4/Netty4HttpClient.java
> +        clientBootstrap = new Bootstrap()
Could we maybe not change this or make it use a single threaded `NioEventLoopGroup` until we've successfully dealt with https://github.com/elastic/elasticsearch/issues/46803 (just reopened, the fact that every thread we touch is using 1MB of direct memory, weakly-referenced as a `ThreadLocal` with the copy bytes channel is causing trouble in CI in some tests and this seems like a spot where we'd add more trouble potentially) in full?

2019-10-21 08:09 UTC, ywelsch requested changes

2019-10-21 15:43 UTC, ywelsch approved these changes
LGTM

2019-10-21 15:43 UTC, ywelsch commented on modules/transport-netty4/src/main/java/org/elasticsearch/transport/NettyAllocator.java
> +            return false;
perhaps `assert delegate.isDirectBufferPooled() == false`?

2019-10-21 16:37 UTC, merged