[DOCS] Add more examples to Painless statements
elastic/elasticsearch pull request #48397
Opened 2019-10-23 13:42 UTC by renshuki

Add more examples to the Painless statements documentation (including `while` and `do...while`) as requested in https://github.com/elastic/elasticsearch/pull/47485#pullrequestreview-296850463

https://www.elastic.co/guide/en/elasticsearch/painless/current/painless-statements.html

2019-10-23 13:42 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2019-12-02 15:30 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (:Core/Infra/Scripting)

2019-12-04 23:30 UTC, jdconrad requested changes
@renshuki Apologies for the very delayed review. I have requested a few changes if you're still interested in working on this.

2019-12-11 17:14 UTC, jrodewig commented
Hi @renshuki. Do you still plan to address feedback for this PR?

If not, I'll close it. Either way, thanks for your contribution.

2019-12-12 01:41 UTC, renshuki commented on docs/painless/painless-lang-spec/painless-statements.asciidoc
> +===== If / Else if / Else
you just want me to remove "Else if" from the title to avoid confusion right?

2019-12-12 01:42 UTC, renshuki commented on docs/painless/painless-lang-spec/painless-statements.asciidoc
> +===== Do...While
ok, I'll make the change.

2019-12-12 01:43 UTC, renshuki commented
@jrodewig @jdconrad Yes I wish continue to work on this PR, I'll push the changes requested by @jdconrad today.

2019-12-12 10:35 UTC, renshuki commented
@jdconrad Could you please double check the latest changes? Thanks.

2020-05-11 14:55 UTC, jdconrad approved these changes
LGTM. Apologies for the serious delay.

2020-05-11 14:56 UTC, jdconrad commented
@elasticmachine test this please

2020-05-11 15:17 UTC, merged

2020-05-12 01:47 UTC, renshuki commented
Thanks for the merge @jdconrad ! 👍