[DOCS] Jailbreak Snapshot and Restore API documentation to REST API section
elastic/elasticsearch pull request #48419
Opened 2019-10-23 17:18 UTC by wchrisdean

2019-10-23 17:18 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/Snapshot/Restore)

2019-10-23 17:18 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2019-10-23 18:34 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +=== Snapshot Restore API
Titles and headings should be sentence case.
```suggestion
=== Snapshot restore API
```

2019-10-23 18:34 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +<titleabbrev>Snapshot Restore API</titleabbrev>
```suggestion
<titleabbrev>Snapshot restore</titleabbrev>
```

2019-10-23 18:34 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +////
These comments seem redundant. I'd remove them.

2019-10-23 18:39 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +////
Remove

2019-10-23 18:40 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +[[sample-api-request]]
This looks like the placeholder ID from the template. This needs to be unique to the API. Here's a suggestion:

```suggestion
[[snapshot-restore-api-request]]
```

2019-10-23 18:41 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +////
Remove

2019-10-23 18:42 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +////
You can omit this section is it's unneeded.

2019-10-23 18:45 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +[[sample-api-prereqs]]
```suggestion
[[snapshot-restore-api-prereqs]]
```

2019-10-23 18:45 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +[[sample-api-desc]]
```suggestion
[[snapshot-restore-api-desc]]
```

2019-10-23 18:45 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +////
Omit the comments and replace with a longer form description of the API and it's intended usage.

2019-10-23 18:46 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +[[sample-api-path-params]]
```suggestion
[[snapshot-restore-api-path-params]]
```

2019-10-23 18:46 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +////
Remove these comments. This is where you define the variable parameters you set up in the request section.

2019-10-23 18:47 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +[[sample-api-query-params]]
```suggestion
[[snapshot-restore-api-query-params]]
```

2019-10-23 18:47 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +////
Remove

2019-10-23 18:47 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +[[sample-api-request-body]]
```suggestion
[[snapshot-restore-api-request-body]]
```

2019-10-23 18:47 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +////
Remove

2019-10-23 18:47 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +[[sample-api-response-body]]
```suggestion
[[snapshot-restore-api-response-body]]
```

2019-10-23 18:48 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +////
Remove.

2019-10-23 18:48 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +[[sample-api-response-codes]]
```suggestion
[[snapshot-restore-api-response-codes]]
```

2019-10-23 18:48 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +////
Remove

2019-10-23 18:48 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +[[sample-api-example]]
```suggestion
[[snapshot-restore-api-example]]
```

2019-10-23 18:49 UTC, jrodewig commented on docs/reference/snapshot-api.asciidoc
> +////
Remove.

2019-10-25 18:25 UTC, debadair requested changes
Agree with @jrodewig's comments. In general, I think we should be consistent and name the source files the same as the anchors that are used as the generated HTML file names. It's easier all the way around if there's a 1:1 mapping between source files and the generated HTML files. 

I'd actually consider splitting Snapshot and Restore into two separate reference pages. While there's a strong argument for keeping them together from the API view, from the user perspective they are two separate actions and having them separate would be better from a discoverability standpoint. If I didn't already know, I might see "Snapshot restore" as the API to restore a snapshot and wonder where "Snapshot create" was.

2019-11-07 18:31 UTC, closed without merging