http://elastic.co -> https
elastic/elasticsearch pull request #48479
Opened 2019-10-24 15:57 UTC by jbudz

Quick find and replace from `http` to https` for references to elastic.co. Mostly localized to the rest spec.

2019-10-24 16:18 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2019-10-24 16:18 UTC, dnhatn commented
@jbudz Thanks for picking this up. There is a test failure that relates to your changes. Can you please fix it?

2019-12-02 15:29 UTC, ywelsch commented
@elastic/docs can someone from your team take a look here?

2019-12-02 15:36 UTC, jrodewig commented
@ywelsch  I can review this. Thanks!

2019-12-02 15:44 UTC, jrodewig commented on docs/plugins/discovery-ec2.asciidoc
> +https://www.elastic.co/cloud.*
It looks like we enforce a trailing slash here.
```suggestion
https://www.elastic.co/cloud/.*
```

2019-12-02 15:45 UTC, jrodewig commented on docs/plugins/redirects.asciidoc
> +Looking for a hosted solution for Elasticsearch on AWS? Check out https://www.elastic.co/cloud.
```suggestion
Looking for a hosted solution for Elasticsearch on AWS? Check out https://www.elastic.co/cloud/.
```/\

2019-12-02 15:45 UTC, jrodewig commented on docs/plugins/repository-s3.asciidoc
> +https://www.elastic.co/cloud.*
```suggestion
https://www.elastic.co/cloud/.*
```

2019-12-02 15:49 UTC, jrodewig commented on x-pack/plugin/src/test/resources/rest-api-spec/api/ccr.forget_follower.json
> +      "url":"https://www.elastic.co/guide/en/elasticsearch/reference/current"
Not related to your changes, but this link is wrong.
```suggestion
      "url":"https://www.elastic.co/guide/en/elasticsearch/reference/current/ccr-post-forget-follower.html"
```

2019-12-02 15:50 UTC, jrodewig commented on x-pack/plugin/src/test/resources/rest-api-spec/api/ccr.unfollow.json
> +      "url":"https://www.elastic.co/guide/en/elasticsearch/reference/current"
Link is wrong.
```suggestion
      "url":"https://www.elastic.co/guide/en/elasticsearch/reference/current/ccr-post-unfollow.html"
```

2019-12-02 16:14 UTC, jrodewig commented
@jbudz  Thanks for this PR. I added a few suggestions, most of which weren't directly related to your changes.

It looks like you also have some merge conflicts on this PR.

Once those two issues are addressed, I can help merge and backport these changes. Let me if you need any help implementing the feedback.

2019-12-02 16:54 UTC, jrodewig requested changes
@jbudz Thanks for this PR. I added a few suggestions, most of which weren't directly related to your changes.

It looks like you also have some merge conflicts on this PR.

Once those two items are addressed, I can help merge and backport these changes. Let me if you need any help implementing the feedback.

2020-02-03 13:51 UTC, jrodewig approved these changes
Thanks @jbudz

2020-02-03 13:52 UTC, merged

2020-02-03 14:50 UTC, jrodewig commented
### Backport commits
master 23b31d6
7.x 4ea7297