Closes #48469 - Refactor and DRY up Kahan Sum algorithm
elastic/elasticsearch pull request #48558
Opened 2019-10-27 21:53 UTC by JosemyDuarte

I have created `CompensatedSum` to centralize the logic of Kahan Sum and replace it in all the classes mentioned by #48469. 

I haven't put the looping logic inside the class since there are places where we do other stuff besides the sum in the loop, like in `StatsAggregator` where besides calculating the sum we also get the max and min value.

2019-10-28 01:58 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo (:Analytics/Aggregations)

2019-10-28 18:57 UTC, not-napoleon commented
@elasticmachine test this please

2019-10-28 19:45 UTC, JosemyDuarte commented
Hi @not-napoleon! I just saw the build log that seems to be failing and I am not sure if I understand how my change could have caused that. If this is my fault I'm willing to solve it, but I would appreciate it if you can point me in the right direction.

Thanks!

2019-10-28 20:05 UTC, not-napoleon requested changes
I like the solution overall.  Left a couple of clean up comments that need to be fixed before we can merge it.

I appreciate you doing this work.  In the future though, please check if someone else has already asked to work on an issue before you start on it.

2019-10-28 20:05 UTC, not-napoleon commented on server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalWeightedAvg.java
> -            // Inf/NaN.  This keeps the behavior bwc from before kahan summing
I think this inline comment is worth preserving; Let's just copy it to the same clause in the new class.

2019-10-28 20:07 UTC, not-napoleon commented
I agree, the BWC failure looks unrelated.  I'll run it again after the requested changes land, and if it's green then we should be okay.

2019-10-29 21:11 UTC, JosemyDuarte commented
Cool! Thanks for your feedback. I have a busy week, but I'll work on this before finishing the week.

2019-11-01 09:41 UTC, csoulios commented
Just a quick note that Kahan summation is also used in #47468 for the `string_stats` aggregation

2019-11-01 11:08 UTC, JosemyDuarte commented on server/src/main/java/org/elasticsearch/search/aggregations/metrics/CompensatedSum.java
> +    public CompensatedSum add(double value, double delta) {
Taking into consideration that we don't pass any delta different than 0, do you think it is better this one or the one which only takes `value` as a parameter (assuming delta as 0 always)?

2019-11-03 17:09 UTC, JosemyDuarte commented on server/src/main/java/org/elasticsearch/search/aggregations/metrics/CompensatedSum.java
> +    public CompensatedSum add(double value, double delta) {
I kept both versions.

2019-11-04 19:42 UTC, not-napoleon commented
@elasticmachine update branch

2019-11-04 19:42 UTC, not-napoleon commented
@elasticmachine test this please

2019-11-04 19:49 UTC, not-napoleon approved these changes

2019-11-04 19:57 UTC, not-napoleon commented
Hi @JosemyDuarte 

This looks good, thanks for making those changes.  I'm at a conference this week, so may be slow in checking in, but I'll keep an eye on the tests.  I'll let you know if there are failures I need you to look into.  Not sure I'll have time to merge it this week, but if I don't, I definitely will next week.

Thanks again for the contribution!

2019-11-04 20:04 UTC, JosemyDuarte commented
Great! Thank you for your feedback. I'll keep an eye on simple issues to keep contributing. Enjoy your conference 👍

2019-11-07 16:48 UTC, not-napoleon commented
@elasticmachine run elasticsearch-ci/packaging-sample-matrix

2019-11-11 18:29 UTC, merged