Improve jdk download retries
elastic/elasticsearch pull request #48560
Opened 2019-10-28 03:47 UTC by atorok

Look like the `--retry` argument is not always effective.

Closes #40531

2019-10-28 03:47 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (:Core/Infra/Build)

2019-10-29 09:10 UTC, dliappis requested changes
Thanks! I left a few comments, mainly highlighting the need to emit the error at the end.

2019-10-29 09:10 UTC, dliappis commented on distribution/docker/src/docker/Dockerfile
> +RUN for iter in {1..10}; do curl -L -s -S ${jdkUrl} | tar -C /opt -zx &&\
nit: let's have a space between `&&` and `\` for consistency i.e. `&& \`

2019-10-29 09:10 UTC, dliappis commented on distribution/docker/src/docker/Dockerfile
> +
One new line is enough, I think we can remove this.

2019-10-29 16:23 UTC, mark-vieira approved these changes
LGTM I suppose. Pretty annoying that `--retry` doesn't do what we want. Did we discover what kind of errors we are encountering that aren't caught by `--retry`?

2019-10-30 07:38 UTC, dliappis commented
> Did we discover what kind of errors we are encountering that aren't caught by `--retry`?

Connection resets -- which is something that occasionally happens from the GitHub URL we are relying -- aren't being retried (others reporting the same [here](https://superuser.com/questions/1083589/curl-56-recv-failure-connection-reset-by-peer)).

For the record `curl` already covers connection refused (via https://github.com/curl/curl/issues/1036) and will also retry connection timeouts (if [--connect-timeout](https://github.com/curl/curl/issues/4461) has been set).

2019-10-30 07:55 UTC, atorok commented
but `--connection-timeout`is not available in the curl version we use here.

2019-10-30 14:54 UTC, dliappis approved these changes
LGTM. I left a minor comment, there's no need for another review cycle.

2019-10-30 14:54 UTC, dliappis commented on distribution/docker/src/docker/Dockerfile
> +
(super) nit: we could remove the 4 space characters in line 22 (so that there's just a newline).

2019-11-03 02:59 UTC, merged