Update aggregations.asciidoc
elastic/elasticsearch pull request #48984
Opened 2019-11-12 12:47 UTC by farhan711

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2019-11-12 13:25 UTC, cbuescher requested changes
I don't see why adding a comma here would help. Would you explain your intentions, otherwise we'll close this

2019-11-12 13:25 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2019-11-12 13:25 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo (:Analytics/Aggregations)

2019-11-13 05:10 UTC, farhan711 commented
> I don't see why adding a comma here would help. Would you explain your intentions, otherwise we'll close this

Its for more clarity to the document, currently it look bit unstructured and incomplete. (it got confused me)

2019-12-10 20:24 UTC, jrodewig commented
Hi @farhan711 

Thanks for your interest in Elasticsearch.

While they can be read as-is, this Asciidoc file is used as a source to generate this HTML page:
https://www.elastic.co/guide/en/elasticsearch/reference/7.4/search-aggregations.html

Here's a screenshot of how this current content displays there:
<img width="746" alt="Screen Shot 2019-12-10 at 3 20 58 PM" src="https://user-images.githubusercontent.com/40268737/70565821-e3bf5900-1b60-11ea-83e0-9061bc089afb.png">

I agree with @cbuescher that adding a comma here isn't necessary and would be grammatically incorrect. I'm going to close this PR.

2019-12-10 20:24 UTC, closed without merging