Update doc_values doc
elastic/elasticsearch pull request #49041
Opened 2019-11-13 14:04 UTC by TonioGarcia07

According to https://kb.objectrocket.com/elasticsearch/when-to-use-the-keyword-type-vs-text-datatype-in-elasticsearch, the `string` type (with option `analyzed`) has been replaced by `text` after `6.0` (This version is 7.4)

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2019-11-13 14:05 UTC, elasticcla commented
Hi @TonioGarcia07, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/elasticsearch/pull/49041.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

2019-11-13 14:19 UTC, elasticmachine commented
Pinging @elastic/es-search (:Search/Mapping)

2019-11-13 14:19 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2019-11-18 10:08 UTC, cbuescher requested changes
Hi @TonioGarcia07, generally looks good to me, can you also add the recently introduced `annotated_text` field to the list which, looking at the code, also doesn't support doc_values?

2019-11-18 14:16 UTC, cbuescher approved these changes
@TonioGarcia07 thanks for the update, will run our docs CI tests before merging.

2019-11-18 14:16 UTC, cbuescher commented
@elasticmachine test this please

2019-11-18 15:37 UTC, merged