Update CONTRIBUTING.md
elastic/elasticsearch pull request #49221
Opened 2019-11-17 20:38 UTC by ejmiers

./gradlew run will fail with error: "a problem occurred running Docker from [/usr/bin/docker] yet it is required to run the following tasks" if docker is not installed. Updated the contributing guide to reflect that docker is a necessary dependency. Change is made under "Contributing to the Elasticsearch codebase" section.

2019-11-18 09:40 UTC, pgomulka commented
@ejmiers this is unusual, can you provide the full command, logs with relevant stactrace and confirm the branch you are working on?

2019-11-18 09:40 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (:Core/Infra/Build)

2019-11-18 17:13 UTC, nik9000 commented
I saw some PRs fly by about not enabling docker tests if docker wasn't available. I wonder if those are related?

2019-11-18 19:31 UTC, ejmiers commented
I uninstalled docker from my machine and reran the gradle build from within eclipse. This is the output I get:

<pre>Working Directory: /home/ejmie518/git/elasticsearch
Gradle user home: /home/ejmie518/.gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 5.6.2
Java Home: /usr/lib/jvm/jdk-12.0.2
JVM Arguments: -ea
Program Arguments: --stacktrace
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: build

> Task :buildSrc:compileMinimumRuntimeJava UP-TO-DATE
> Task :buildSrc:compileMinimumRuntimeGroovy NO-SOURCE
> Task :buildSrc:processMinimumRuntimeResources NO-SOURCE
> Task :buildSrc:minimumRuntimeClasses UP-TO-DATE
> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:generateVersionProperties UP-TO-DATE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:reaper:compileJava UP-TO-DATE
> Task :buildSrc:reaper:processResources NO-SOURCE
> Task :buildSrc:reaper:classes UP-TO-DATE
> Task :buildSrc:reaper:jar UP-TO-DATE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava UP-TO-DATE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources UP-TO-DATE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test SKIPPED
> Task :buildSrc:validateTaskProperties UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
> Task :buildSrc:reaper:assemble UP-TO-DATE
> Task :buildSrc:reaper:compileTestJava NO-SOURCE
> Task :buildSrc:reaper:processTestResources NO-SOURCE
> Task :buildSrc:reaper:testClasses UP-TO-DATE
> Task :buildSrc:reaper:test NO-SOURCE
> Task :buildSrc:reaper:check UP-TO-DATE
> Task :buildSrc:reaper:build UP-TO-DATE

> Configure project :distribution:docker
Tests for :distribution:docker require docker-compose at /usr/local/bin/docker-compose or /usr/bin/docker-compose but none could be found so these will be skipped

> Configure project :test:fixtures:krb5kdc-fixture
Tests for :test:fixtures:krb5kdc-fixture require docker-compose at /usr/local/bin/docker-compose or /usr/bin/docker-compose but none could be found so these will be skipped

> Configure project :plugins:repository-hdfs
Tests for :plugins:repository-hdfs require docker-compose at /usr/local/bin/docker-compose or /usr/bin/docker-compose but none could be found so these will be skipped

> Configure project :plugins:repository-s3
Tests for :plugins:repository-s3 require docker-compose at /usr/local/bin/docker-compose or /usr/bin/docker-compose but none could be found so these will be skipped

> Configure project :x-pack:qa:kerberos-tests
Tests for :x-pack:qa:kerberos-tests require docker-compose at /usr/local/bin/docker-compose or /usr/bin/docker-compose but none could be found so these will be skipped

> Configure project :x-pack:test:idp-fixture
Tests for :x-pack:test:idp-fixture require docker-compose at /usr/local/bin/docker-compose or /usr/bin/docker-compose but none could be found so these will be skipped

> Configure project :x-pack:qa:oidc-op-tests
Tests for :x-pack:qa:oidc-op-tests require docker-compose at /usr/local/bin/docker-compose or /usr/bin/docker-compose but none could be found so these will be skipped

> Configure project :x-pack:qa:openldap-tests
Tests for :x-pack:qa:openldap-tests require docker-compose at /usr/local/bin/docker-compose or /usr/bin/docker-compose but none could be found so these will be skipped

> Configure project :x-pack:qa:saml-idp-tests
Tests for :x-pack:qa:saml-idp-tests require docker-compose at /usr/local/bin/docker-compose or /usr/bin/docker-compose but none could be found so these will be skipped

> Configure project :x-pack:test:smb-fixture
Tests for :x-pack:test:smb-fixture require docker-compose at /usr/local/bin/docker-compose or /usr/bin/docker-compose but none could be found so these will be skipped

> Configure project :x-pack:qa:third-party:active-directory
Tests for :x-pack:qa:third-party:active-directory require docker-compose at /usr/local/bin/docker-compose or /usr/bin/docker-compose but none could be found so these will be skipped

FAILURE: Build failed with an exception.

* What went wrong:
Docker (checked [/usr/bin/docker,/usr/local/bin/docker]) is required to run the following tasks: 
  :distribution:docker:buildDockerImage
  :distribution:docker:buildOssDockerImage
you can address this by attending to the reported issue, removing the offending tasks from being executed, or by passing -Dbuild.docker=false

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleException: Docker (checked [/usr/bin/docker,/usr/local/bin/docker]) is required to run the following tasks: 
  :distribution:docker:buildDockerImage
  :distribution:docker:buildOssDockerImage
you can address this by attending to the reported issue, removing the offending tasks from being executed, or by passing -Dbuild.docker=false
	at org.elasticsearch.gradle.BuildPlugin.throwDockerRequiredException(BuildPlugin.groovy:284)
	at org.elasticsearch.gradle.BuildPlugin.access$2(BuildPlugin.groovy)
	at org.elasticsearch.gradle.BuildPlugin$_requireDocker_closure3.doCall(BuildPlugin.groovy:223)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1$1.run(DefaultListenerBuildOperationDecorator.java:185)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1.run(DefaultListenerBuildOperationDecorator.java:180)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure.doCall(DefaultListenerBuildOperationDecorator.java:177)
	at jdk.internal.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:41)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:231)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:150)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:325)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDisp [...]

2019-11-18 19:46 UTC, nik9000 commented
@mark-vieira this seems like a bug to me. Do you think so?

2019-11-18 20:57 UTC, mark-vieira commented
That build execution is running `./gradlew build` which is going to try and assemble all artifacts, including our Docker images.

@pugnascotia what's the expected behavior here? It doesn't' like like `-Dbuild.docker=false` actually does anything anymore.

2019-11-19 08:24 UTC, pugnascotia commented
> what's the expected behavior here?

Well, I don't remember explicitly changing anything to do with `-Dbuild.docker`, but the Docker packing test work might have inadvertently made it impossible to run the build without Docker. A full build should definitely build and test the Docker image, but if we need to able to bypass that then I can certainly add / fix / reinstate that.

2019-11-19 16:43 UTC, mark-vieira commented
@ejmiers can you confirm this? Running `build` as mentioned above _does_ require docker, as it builds the images. You should be able to run `./gradlew :run` without docker though as that just uses the regular archive distribution for whatever platform you're on. Do you mind confirming this?

2019-11-25 23:35 UTC, ejmiers commented
Sorry for the delay, life got real busy last week. I uninstalled docker and ran <pre>./gradlew :run</pre>. This appears to work fine, I am able to run an instance of elasticsearch without any "docker not found" errors.

2019-11-26 13:05 UTC, pugnascotia commented on CONTRIBUTING.md
> +[Docker](https://docs.docker.com/install/) is a necessary dependency for building elasticsearch. Make sure docker is installed prior to running an instance of elasticsearch from source code.
@ejmiers thanks for confirming!

Regarding the change, how about the following?

```suggestion
[Docker](https://docs.docker.com/install/) is a necessary dependency for building Elasticsearch. You can run Elasticsearch without building all the artifacts with:

    ./gradlew :run
```

2019-11-26 16:23 UTC, ejmiers commented
Change committed.

2019-11-26 21:00 UTC, pugnascotia approved these changes
LGTM. @mark-vieira what do you think?

2019-12-02 23:11 UTC, mark-vieira requested changes

2019-12-02 23:11 UTC, mark-vieira commented on CONTRIBUTING.md
> +[Docker](https://docs.docker.com/install/) is a necessary dependency for building Elasticsearch. You can run Elasticsearch without building all the artifacts with:
Sorry if I'm overly pedantic about this but can we be a bit more accurate and say docker "is required for building _some_ Elasticsearch artifacts and executing certain test suites."

2019-12-02 23:20 UTC, ejmiers commented
No problem, just made the change.

2019-12-02 23:54 UTC, mark-vieira approved these changes
LGTM 👍

2019-12-03 09:31 UTC, merged