SQL: Fix issue with folding of CASE/IIF
elastic/elasticsearch pull request #49449
Opened 2019-11-21 16:05 UTC by matriv

Add extra checks to prevent ConstantFolding rule to try to fold
the CASE/IIF functions early before the SimplifyCase rule gets applied.

Fixes: #49387

2019-11-21 16:05 UTC, elasticmachine commented
Pinging @elastic/es-search (:Search/SQL)

2019-11-21 16:11 UTC, astefan approved these changes
LGTM

2019-11-21 16:50 UTC, costin requested changes
I consider it a semantic leak when expression classes become aware of runtime rules.
It indicates that either the expression tries to do too much (in this case folding) or that the relationship between the rules is not correct (either the rules need to be simplified or the order between them changed).

The comment refers to a rule but it seems to me that the folding is eager?
Or maybe `SimplifyCase` be moved before `ConstantFolding` - I couldn't tell from the test case what is the current issue...

2019-11-21 17:52 UTC, matriv commented
@costin The issue was that the Case was answering `foldable() -> true` even if the result of the condition (folded to true) was un-foldable. The tests test that the case is not foldable before the SimplifyCase rule takes place.

I thought of changing the order but I thought personally that can become easier a future confusion than my current solution. The current code just tests that the result or elseResult (depending on the TRUE/FALSE of the condition) is also foldable and (at least in my mind) doesn't appear that connected to the rules and their order. On the contrary the previous state seems to depend more on the ordering of the rules in the Optimizer, and the comment on the method (comes from a previous suggestion of yours) clearly states that it's based on the fact that the SimplifyCase rule has been applied.

If you think changing the orders of the rules in the Optimizer seems a better approach, I'm happy to proceed with that.

2019-11-21 17:57 UTC, matriv commented
@costin 
To give an example for supporting the current solution:
```
public void testSimplifyIif_ConditionFalse_NonFoldableResult() {
        SimplifyCase rule = new SimplifyCase();
        Iif iif = new Iif(EMPTY, new Equals(EMPTY, ONE, TWO), Literal.of(EMPTY, "foo"), getFieldAttribute("myField"));
        assertFalse(iif.foldable()); --> previously here it was TRUE which logically is wrong.

        Expression e = rule.rule(iif);
        assertEquals(Iif.class, e.getClass());
        iif = (Iif) e;
        assertEquals(0, iif.conditions().size());
        assertFalse(iif.foldable());
        assertEquals("myField", Expressions.name(iif.elseResult()));
    }
```

2019-11-22 11:34 UTC, costin approved these changes
LGTM - the comment about the rules threw me off hence why it should be removed.

2019-11-22 11:34 UTC, costin commented on x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/Case.java
> +            // Need to prevent ConstantFolding rule to get applied before SimplifyCase rule
I find the comment misleading as it implies the rules order is incorrect - called in a different order the rules might affect `fold` but the matter is, `foldable` is incorrect (which leads to the exception).

2019-11-22 12:52 UTC, matriv commented
@elasticmachine run elasticsearch-ci/default-distro
@elasticmachine run elasticsearch-ci/bwc

2019-11-22 13:49 UTC, matriv commented
@elasticmachine run elasticsearch-ci/packaging-sample-matrix

2019-11-22 14:28 UTC, merged