Run build-tools test with compiler jdk
elastic/elasticsearch pull request #49459
Opened 2019-11-21 18:59 UTC by jaymode

The test task is configured to use the runtime java version, but there
are issues with the version of groovy used by gradle pre 6.0. In order
to workaround this, we use the compiler java to execute the build-tools
tests.

Closes #49404

2019-11-21 18:59 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (:Core/Infra/Build)

2019-11-21 19:10 UTC, mark-vieira requested changes
This brings up a good question, which is that we don't well define what versions of Java our build runtime is compatible with. This is mostly `minimumCompilerVersion` but there are exceptions here. Essentially, because we are still on Gradle 5.x, you cannot run the build with Java 13, thus it makes no sense to test `build-tools` against that version.

With that in mind, I think the better thing to do is simply to disable our build-tools tests entirely on those Java versions. Essentially, those matrix jobs are not applicable to `build-tools`, so there's no point in reconfiguring the build to test with another java version that already overlaps with another matrix build.

Let's do something like this:
```
tasks.withType(Test) {
  onlyIf {
    org.elasticsearch.gradle.info.BuildParams.runtimeJavaVersion <= JavaVersion.VERSION_12
  }
}
```

2019-11-21 20:05 UTC, jaymode commented
I made the proposed change but I have a concern. In the default developer setup, tests will not be run for build-tools at all. Unless a runtime java home is specified, we default to using JDK 13 as the runtime java home (the provisioned jdk) so these tests will only run in matrix jobs if I understand correctly.

2019-11-21 21:03 UTC, mark-vieira commented
> I made the proposed change but I have a concern. In the default developer setup, tests will not be run for build-tools at all. Unless a runtime java home is specified, we default to using JDK 13 as the runtime java home (the provisioned jdk) so these tests will only run in matrix jobs if I understand correctly.

Good point. So I'd do two things:
1. Omit the `build-tools` project in the `runtime-jdk-provision.gradle` script altogether, as those defaults aren't applicable here.
2. Hard code the test executable in `buildSrc/build.gradle` to `Jvm.current().getJavaHome()` so that we are always testing with the _build_ java home, since that's what we care about.

2019-11-22 15:23 UTC, mark-vieira approved these changes
LGTM 👍

2019-11-22 15:24 UTC, mark-vieira commented on buildSrc/build.gradle
> +    it.executable = Jvm.current().getJavaHome().toPath().resolve("bin").resolve("java").toAbsolutePath()
This can be simplified to `Jvm.current().getJavaExecutable()`

2019-11-22 17:13 UTC, merged