Disable DiagnosticTrustManager in FIPS 140
elastic/elasticsearch pull request #49888
Opened 2019-12-05 21:04 UTC by jkakavas

This commit changes the default behavior for 
`xpack.security.ssl.diagnose.trust` when running in a FIPS 140 JVM.

More specifically, when `xpack.security.fips_mode.enabled` is true:
- If `xpack.security.ssl.diagnose.trust` is not explicitly set, the 
default value of it becomes `false` and a log message is printed
on info level, notifying of the fact that the TLS/SSL diagnostic 
messages are not enabled when in a FIPS 140 JVM. 
- If `xpack.security.ssl.diagnose.trust` is explicitly set to true, we fail
to start the node and give a descriptive error message
- If `xpack.security.ssl.diagnose.trust` is explicitly set to false, the
behavior is the same as before. 

This is relevant only for 7.x where we support Java 8 in which 
SunJSSE can still be used as a FIPS 140 provider for TLS. SunJSSE
in FIPS mode, disallows the use of other TrustManager implementations
than the one shipped with SunJSSE.

2019-12-05 21:04 UTC, elasticmachine commented
Pinging @elastic/es-security (:Security/Network)

2019-12-09 07:45 UTC, tvernum commented
> If xpack.security.ssl.diagnose.trust is explicitly set to true, we fail

Is that what we want? Do we support using BC-FIPS-JSSE on 7.x? (I think we do/will) 
If so, isn't it OK for users to opt-in to diagnostic trust if their JSSE provider supports it?

2019-12-10 15:00 UTC, jkakavas commented
> Is that what we want? Do we support using BC-FIPS-JSSE on 7.x? (I think we do/will)
If so, isn't it OK for users to opt-in to diagnostic trust if their JSSE provider supports it?

You're right, I was probably too aggressively defensive here. We do plan to start testing with BCJSSE in  FIPS mode and there is no reason to not support this.

2019-12-16 04:19 UTC, tvernum requested changes
I've marked this as "request changes" so it drops from my queue (based on agreement above)

2019-12-16 04:19 UTC, tvernum commented on docs/reference/settings/security-settings.asciidoc
> +`xpack.security.fips_mode.enabled` is `true`.
Based on agreement to allow FIPS users to opt-in, let's remove the 2nd part of this note.

2019-12-16 04:19 UTC, tvernum commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ssl/SSLService.java
> +        }
```
       if (XPackSettings.FIPS_MODE_ENABLED.get(settings) && DIAGNOSE_TRUST_EXCEPTIONS_SETTING.exists(settings) == false ) {
            logger.info("diagnostic messages for SSL/TLS trust failures are not enabled in FIPS 140 mode.");
            return false;
        } else {
            return DIAGNOSE_TRUST_EXCEPTIONS_SETTING.get(settings);
        }
```

2019-12-16 04:19 UTC, tvernum commented on x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java
> +        }
I think we can just drop this.

2020-01-13 13:20 UTC, tvernum approved these changes

2020-01-13 13:20 UTC, tvernum commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ssl/SSLService.java
> +            logger.info("diagnostic messages for SSL/TLS trust failures are not enabled in FIPS 140 mode be default.");
```suggestion
            logger.info("diagnostic messages for SSL/TLS trust failures are not enabled in FIPS 140 mode by default.");
```

2020-01-13 15:04 UTC, merged