Add command-line tool support for Lucene-based metadata storage
elastic/elasticsearch pull request #50179
Opened 2019-12-13 13:51 UTC by ywelsch

Adds command-line tool support (unsafe-bootstrap, detach-cluster, repurpose, & shard commands) for the Lucene-based metadata storage.

Relates #48701

2019-12-13 13:51 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/Cluster Coordination)

2019-12-16 16:45 UTC, ywelsch commented
@elasticmachine run elasticsearch-ci/2

2019-12-17 11:06 UTC, henningandersen approved these changes
LGTM.

I left a few minor comments to consider. I assume the two important TODOs (setLastAcceptedTerm and dangling indices) will be tackled in follow-ups.

2019-12-17 11:42 UTC, DaveCTurner requested changes
I do not think we should expose the internals of `LucenePersistedStateFactory` as much as we are proposing here. The internal details and the state-loading logic are once again spilling into `GatewayMetaState` and elsewhere. I would prefer to keep things more isolated and add public methods to `LucenePersistedStateFactory` as needed to support the non-standard ways that the node tool accesses the on-disk state.

2019-12-17 11:42 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/gateway/GatewayMetaState.java
> +                    assert Version.CURRENT.major <= Version.V_7_0_0.major + 1 :
We also return `LucenePersistedStateFactory.NO_ON_DISK_STATE` if starting up a brand-new node?

(I know this is merely moving code from an earlier PR, I missed this last time)

2019-12-17 11:52 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/gateway/GatewayMetaState.java
> +                    assert Version.CURRENT.major <= Version.V_7_0_0.major + 1 :
Sorry, ignore this comment, there's not really an obvious better way to assert this.

2019-12-17 14:34 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/env/NodeRepurposeCommand.java
> +        final Set<String> indexUUIDs = Sets.union(indexUUIDsFor(indexPaths),
fixed in fd3dd91

2019-12-17 14:36 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/gateway/LucenePersistedStateFactory.java
> +    public LucenePersistedStateFactory(Path[] dataPaths, String nodeId, boolean preserveUnknownCustoms,
adapted in cffdd8a.
The way I had it, the parameter list had the same suffix. Now it does not have same prefix nor suffix...

2019-12-17 14:36 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/cluster/coordination/ElasticsearchNodeCommand.java
> +    protected static final Logger logger = LogManager.getLogger(ElasticsearchNodeCommand.class);
adapted in 0c8bb67

2019-12-17 14:36 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/gateway/GatewayMetaState.java
> +                            null, legacyState.v1().getCurrentTerm(),
adapted in 0c8bb67

2019-12-17 14:36 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/gateway/LucenePersistedStateFactory.java
> +        public final Path dataPath;
adapted in 0c8bb67

2019-12-17 14:43 UTC, ywelsch reviewed
> I do not think we should expose the internals of LucenePersistedStateFactory as much as we are proposing here.

I've hidden more things away in 0c8bb67. I don't want to go back to `LegacyLoader` and introducing more callbacks to `LucenePersistedStateFactory` (e.g. to adapt cluster state). I think that as it stands this class has a minimal interface, and does not need to concern itself with legacy stuff.

> I would prefer to keep things more isolated and add public methods to LucenePersistedStateFactory as needed to support the non-standard ways that the node tool accesses the on-disk state.

That was my starting point, but after adding more bells and whistles to `LucenePersistedStateFactory` that were essentially irrelevant for what this class was trying to achieve, I didn't like it and got to the current solution.

I find the current minimal Writer/OnDiskState interfaces a good compromise between having a closed interface and unnecessary parameterization of the class.

2019-12-19 09:41 UTC, DaveCTurner approved these changes
LGTM thanks for the re-organisation.

2019-12-19 10:02 UTC, merged