[Draft] Add tests for IntervalsSourceProvider implementations
elastic/elasticsearch pull request #50271
Opened 2019-12-17 11:57 UTC by Hohol

This PR adds unit tests for wire and xContent serialization of IntervalsSourceProvider implementations.

Closes https://github.com/elastic/elasticsearch/issues/50150

2019-12-17 11:59 UTC, Hohol commented
@cbuescher, I've added the test for `Prefix` provider only for now. Should I proceed with the other providers in the similar manner?

2019-12-17 12:06 UTC, cbuescher commented
> Should I proceed with the other providers in the similar manner

Thanks a lot for opening this, let me take a closer looks at this one first. I opening smaller PRs one after the other will be easier. I'll try to take a closer look soon.

2019-12-17 12:09 UTC, Hohol commented
Some questions and notes.
1. In [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-intervals-query.html#intervals-top-level-params) `filter` rule is listed as one of possible top-level rules. Although as you can see from the code, it's actually not:
https://github.com/elastic/elasticsearch/blob/4f8d29edfaa1913ab9179b0ef7aabb0fc9093c29/server/src/main/java/org/elasticsearch/index/query/IntervalsSourceProvider.java#L77-L88
Is it normal?
2. In `AbstractSerializingTestCase.doParseInstance`, why `parser` always starts pointing at `null`? At first, I thought it was a bug with my test, but I checked a few other tests, and it's always the same. Strange.

2019-12-17 17:40 UTC, cbuescher requested changes
Great test, I left two minor comments but otherwise this looks great.
With regards to your questions:

> why parser always starts pointing at null

I think the parser is created somewhere in the base tests `testFromXContent`, actually I think a factory method is passed into the `XContentTester` helper. I cannot really say why the setup doesn't initialize the token pointer, so we need to advance the token pointer manually.

> In the documentation filter rule is listed as one of possible top-level rules

You are most likely right, when I look at the parsing in IntervalQueryBuilder#fromXContent, it looks like "filter" cannot be top level, but it can be nested. I'll try to verify that.

2019-12-17 17:40 UTC, cbuescher commented on server/src/main/java/org/elasticsearch/index/query/IntervalsSourceProvider.java
> +        public String getPrefix() {
nit: maybe we can keep this method and the other two getters package private for now, since its only used in the test.

2019-12-17 17:40 UTC, cbuescher commented on server/src/main/java/org/elasticsearch/index/query/IntervalsSourceProvider.java
> +            Wildcard wildcard = (Wildcard) o;
great catch, makes sense but maybe include this in a follow up PR adding the wildcard tests so we have code change coming with test.

2019-12-18 13:01 UTC, cbuescher commented
@Hohol all of this seems to be included in #50306 now, lets close this then okay?

2019-12-18 13:03 UTC, closed without merging