Fix typos
elastic/elasticsearch pull request #50365
Opened 2019-12-19 12:08 UTC by daixiang0

Signed-off-by: Xiang Dai <764524258@qq.com>

2019-12-19 14:29 UTC, elasticmachine commented
Pinging @elastic/es-docs (:Docs)

2019-12-19 14:30 UTC, nik9000 requested changes
This is quite long to review. I think it'd be nice if you could break it up a bit. Maybe also break out the removal of trailing spaces as well.

2019-12-20 01:44 UTC, daixiang0 commented
@nik9000 I want to split them then maybe too many pr, so i put them together.
I have a tool to clean up white up safely, i would revert this commit first.

2019-12-20 15:01 UTC, nik9000 commented on docs/plugins/mapper-annotated-text.asciidoc
> +  "my_field": "[Jeff Beck](Jeff+Beck&Guitarist) plays a start"<2>
This one refers to [fender stratocaster](https://en.wikipedia.org/wiki/Fender_Stratocaster).

2019-12-20 15:04 UTC, nik9000 requested changes
I left two comments about corrections that you made that I think weren't needed. Otherwise this looks good. Could you revert those two change?

2019-12-20 15:04 UTC, nik9000 commented on docs/reference/mapping/types/percolator.asciidoc
> +        "body" : "Bicycles are missing"
I think this one might be intentional

2019-12-20 15:05 UTC, nik9000 commented
@elasticmachine, ok to test

2019-12-23 15:29 UTC, nik9000 approved these changes
Seems right to me. Let's see what CI thinks:

@elasticmachine, ok to test.

2019-12-23 15:35 UTC, merged

2019-12-23 15:36 UTC, nik9000 commented
CI seemed to like it. I've merged it. It should show up on the site in about an hour for the master branch. I'll open PRs to backport it to 7.x and 7.5 so it shows up there too.