[docs] indent
elastic/elasticsearch pull request #50855
Opened 2020-01-10 14:13 UTC by missinglink

minor minor indentation issue

2020-01-15 09:59 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2020-01-15 16:22 UTC, jrodewig commented on docs/reference/index-modules/similarity.asciidoc
> +           }
Github won't allow me to comment on the line, but do you mind fixing the indentation on line 27 (` "similarity"`) as well?

It looks like it uses tab/5 spaces.

2020-01-15 16:22 UTC, jrodewig requested changes
Left a request to fix one other indentation issue. After that's addressed, I can merge and backport.

2020-01-15 16:23 UTC, elasticmachine commented
Pinging @elastic/es-search (:Search/Ranking)

2020-01-16 09:30 UTC, missinglink commented
@jrodewig this is not a new code submission and I don't work for elastic.
I'm happy to continue catching and fixing docs issues for you but I'm not working for you for free.

If you see another issue in the same document you can open a PR yourself to fix it rather than expecting me to do it for you.
If you need help using the `cherry-pick` command I am happy to oblige.

2020-01-16 13:34 UTC, jrodewig commented
Hi @missinglink.

Sorry for any confusion. The change I requested is indeed related to this one.

Line 27 contains the opening bracket (`{`) for the change you submitted. Unfortunately, I cannot accept your changes without also fixing the indentation for that line.

I'm going to close this PR and treat this as a bug report. Please feel free to re-open this PR if you'd like to address.

Thanks for raising this issue.

2020-01-16 13:35 UTC, closed without merging