Respect alternate keystore locations
elastic/elasticsearch pull request #50865
Opened 2020-01-10 17:37 UTC by bdentino

If an operator has ELASTIC_PASSWORD set and is using a non-default path.conf location via ES_PATH_CONF, the application will hang pre-startup when the keystore already exists. I believe this is because the keystore tool uses ES_PATH_CONF (does it?), so it detects the existing keystore file in the alternate directory and requires an interactive confirmation to ignore or overwrite, which causes the entrypoint script to hang.

2020-01-15 10:00 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (:Core/Infra/Packaging)

2020-01-24 22:58 UTC, williamrandolph commented
@bdentino I'm sorry that it's taken me so long to review this contribution. I'm working on replicating the problem locally so I can test your code fix. Can you describe the use case in a little more detail or provide some steps to replicate?

2020-02-25 19:34 UTC, williamrandolph requested changes
@bdentino I've looped back around on this, stepping through the commands this time instead of trying to configure the docker image to replicate this problem, and I see exactly what you're talking about. I failed to correctly set `ELASTIC_PASSWORD` the first time I tried to reproduce this, even though that was the first thing you mentioned.

Are you able to bring this branch up to date with master?

2020-02-25 19:35 UTC, williamrandolph requested changes

2020-02-25 19:35 UTC, williamrandolph commented on distribution/docker/src/docker/bin/docker-entrypoint.sh
> +    [[ -f $ES_PATH_CONF/elasticsearch.keystore ]] || (run_as_other_user_if_needed elasticsearch-keystore create)
I believe that all you need to do to fix the merge conflict is remove `run_as_other_user_if_needed `.

2020-02-25 21:12 UTC, williamrandolph commented
For future reference, my steps to reproduce are as follows:

1. Build docker image locally: `./gradlew distribution:docker:assemble`
2. Copy over the temporary directory of an archive installation with the normal Elasticsearch configuration files:
```
➜  ls dockertmp
elasticsearch.yml log4j2.properties roles.yml         users
jvm.options       role_mapping.yml  tini.sha512       users_roles
```
3. Put something like this in docker-compose.yml:

```
version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.0.0-SNAPSHOT
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_PATH_CONF=/usr/tmp/dockertmp
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=mypass
    volumes:
      - "./dockertmp:/usr/tmp/dockertmp"
```
4. Run `docker-compose up`. The first time, there will be a message about creating a keystore. The second time (and every time after that), the image doesn't hang for me, but I do get the following error:

```
➜  50865 docker-compose up
Starting 50865_elasticsearch_1 ... done
Attaching to 50865_elasticsearch_1
elasticsearch_1  | Exception in thread "main" java.lang.IllegalStateException: unable to read from standard input; is standard input open and a tty attached?
elasticsearch_1  |      at org.elasticsearch.cli.Terminal$SystemTerminal.readText(Terminal.java:273)
elasticsearch_1  |      at org.elasticsearch.cli.Terminal.promptYesNo(Terminal.java:152)
elasticsearch_1  |      at org.elasticsearch.common.settings.CreateKeyStoreCommand.execute(CreateKeyStoreCommand.java:51)
elasticsearch_1  |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
elasticsearch_1  |      at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:90)
elasticsearch_1  |      at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:43)
50865_elasticsearch_1 exited with code 1
```

Rebuilding and running with the proposed changes fixes the problem for me.

2022-07-18 14:52 UTC, pugnascotia commented
This PR has had no updated for over a year, so I hope you don't mind if I close it.

2022-07-18 14:52 UTC, closed without merging