Update httpcore to 4.4.13
elastic/elasticsearch pull request #51786
Opened 2020-02-01 14:35 UTC by racevedoo

Just keeping up to date

2020-02-03 08:30 UTC, elasticmachine commented
Pinging @elastic/es-core-features (:Core/Features/Java Low Level REST Client)

2020-02-03 08:34 UTC, dliappis commented
Last time this was upgraded was in #45808 due to the https://issues.apache.org/jira/browse/HTTPASYNC-152.

Normally upgrading just to keep up to date wouldn't be a sufficient reason, as there may be unknown issues introduced with the new version.

The changelog for the .13 patch release brought in this PR can be seen here: https://www.apache.org/dist/httpcomponents/httpcore/RELEASE_NOTES-4.4.x.txt

2020-02-06 15:27 UTC, danhermann commented
@elasticmachine ok to test

2020-02-18 17:00 UTC, danhermann requested changes
@racevedoo, the hashes for the updated httpcore jar files need to be updated for the dependency tests in our build to succeed. If helpful, there's an example of how that works in this PR: https://github.com/elastic/elasticsearch/pull/46549

2021-03-18 07:59 UTC, closed without merging