Forbid equality checks against 'true'
elastic/elasticsearch pull request #51805
Opened 2020-02-03 11:24 UTC by pugnascotia

Add a Checkstyle rule to forbid equality checks against a literal 'true' value, since this is redundant. Follow up to #51723.

I also built a rule to prohibit logical negations i.e. `!`, but there are thousands of violations, so I left it in place for interest but commented it out. Maybe at some point we'll feel that we want it. It's probably an expensive rule.

2020-02-03 11:24 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (:Core/Infra/Core)

2020-02-04 14:59 UTC, jasontedor requested changes
LGTM.

2020-02-04 14:59 UTC, jasontedor approved these changes
LGTM.

2020-02-04 15:36 UTC, merged

2020-02-04 16:40 UTC, mark-vieira commented on buildSrc/src/main/resources/checkstyle.xml
> +    <module name="DescendantToken">
Why is this commented out?