EQL: Add ? param support
elastic/elasticsearch pull request #52301
Opened 2020-02-13 00:46 UTC by rw-access

Relates to #51756 (closed with API support)

Add support for `?` params to EQL. This hasn't been integrated/tested with for the API, but that can be added here easily if this is the right PR for that.

2020-02-13 00:46 UTC, elasticmachine commented
Pinging @elastic/es-search (:Search/EQL)

2020-02-13 09:59 UTC, astefan reviewed
I've left few comments.

Also, since `?` has other meaning in the grammar, as well, I would like to see a test that contains both uses of `?`. For example:

```
assertEquals(expr("a == ?\"String with literal 'slash' \\ characters included\" and b == ? or c == ?", Arrays.asList("test", false)),
                expr("a == ?\"String with literal 'slash' \\ characters included\" and b == 'test' or c == false"));
```

2020-02-13 09:59 UTC, astefan commented on x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/parser/ParameterTests.java
> +    }
Newline here, please.

2020-02-13 09:59 UTC, astefan commented on x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/parser/ParameterTests.java
> +    }
Newline

2020-02-13 09:59 UTC, astefan commented on x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/parser/ParameterTests.java
> +    public Expression expr(String source) {
Is this method used somewhere else? If not, maybe make it `private`?

2020-02-13 09:59 UTC, astefan commented on x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/parser/ParameterTests.java
> +import org.elasticsearch.xpack.sql.proto.SqlTypedParamValue;
Lots of unused imports.

2020-02-13 09:59 UTC, astefan commented on x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/parser/ParameterTests.java
> +            () -> new EqlParser().createExpression("(? + ? * ?) - ?", Arrays.asList(1, 2, 3)));
Why creating a new EqlParser if there is already one at class level?

2020-02-13 09:59 UTC, astefan commented on x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/parser/ParameterTests.java
> +            () -> new EqlParser().createExpression("a + ?", Collections.singletonList(new Object())));
Why creating a new EqlParser if there is one at class level?

2020-02-13 12:12 UTC, costin requested changes
Left some comments - more tests are needed to check that not only the param get replaced but also that tricky strings are properly added in the query.

2020-02-13 12:12 UTC, costin commented on x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/ExpressionBuilder.java
> +    protected final ParserParams params;
Why protected and not private?

2020-02-13 12:12 UTC, costin commented on x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/ExpressionBuilder.java
> +        } catch (QlIllegalArgumentException ignored) {};
The try/catch is not needed.
And we never catch exceptions and ignore them.

2020-03-30 15:28 UTC, matriv commented
@elastic/es-ql

2020-09-15 13:52 UTC, matriv commented
After searching around regarding query params in SQL DBs, I saw that `?` is the one used for prepared statements, and then each DB uses different syntax for its procedural language (defining custom functions/stored procedures, etc) like: `@param`, `$param` or `:param`. In my opinion I would say let's proceed with the basic usage of `?` as a place holder and a list (array) of value replacements that correspond to those params.

2021-03-06 14:13 UTC, closed without merging