Add documentation for remote cluster proxy mode
elastic/elasticsearch pull request #52779
Opened 2020-02-25 16:48 UTC by tbrooks8

This is related to #49067.

2020-02-25 16:50 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2020-02-25 16:51 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/Network)

2020-02-25 22:39 UTC, tbrooks8 commented
Depends on #52796

2020-02-27 07:20 UTC, ywelsch reviewed
@jrodewig can you have a look too?

2020-02-27 07:20 UTC, ywelsch commented on docs/reference/modules/remote-clusters.asciidoc
> +potential modes for remote cluster connections: sniff mode and proxy mode.
I would remove the word "potential" here.

2020-02-27 07:20 UTC, ywelsch commented on docs/reference/modules/remote-clusters.asciidoc
> +potential modes for remote cluster connections: sniff mode and proxy mode.
also, perhaps link sniff and proxy to the corresponding sections below?

2020-02-27 07:20 UTC, ywelsch commented on docs/reference/modules/remote-clusters.asciidoc
> +`cluster.remote.${cluster_alias}.mode`::
Perhaps add a sentence above the first setting stating that this section is covering settings that apply to both sniff and proxy mode, and that mode-specific settings are coming later.

2020-02-27 07:20 UTC, ywelsch commented on docs/reference/modules/remote-clusters.asciidoc
>  === Remote cluster settings
Remote cluster settings for all modes?

2020-02-27 07:20 UTC, ywelsch commented on docs/reference/modules/remote-clusters.asciidoc
> +=== Remote cluster sniff mode settings
Remote cluster settings for sniff mode?

2020-02-27 10:23 UTC, jrodewig commented on docs/reference/cluster/remote-info.asciidoc
> +    The configured connection mode for the remote cluster. Will be `sniff` or
```suggestion
    Configured connection mode for the remote cluster. Returned values are `sniff` or
```

2020-02-27 10:27 UTC, jrodewig commented on docs/reference/cluster/remote-info.asciidoc
> +	sniff mode is configured.
This looks like it was double indented.

```suggestion
`seeds`::
    Initial seed transport addresses of the remote cluster when
    `sniff` mode is configured.
```

2020-02-27 10:27 UTC, jrodewig commented on docs/reference/cluster/remote-info.asciidoc
> +    configured.
```suggestion
    Number of connected nodes in the remote cluster when `sniff` mode is
    configured.
```

2020-02-27 10:28 UTC, jrodewig commented on docs/reference/cluster/remote-info.asciidoc
> +	sniff mode is configured.
Double indented.
```suggestion
`max_connections_per_cluster`::
      Maximum number of connections maintained for the remote cluster when
      `sniff` mode is configured.
```

2020-02-27 10:29 UTC, jrodewig commented on docs/reference/cluster/remote-info.asciidoc
> +    The configured address for remote connections when proxy mode is configured.
```suggestion
    Address for remote connections when `proxy` mode is configured.
```

2020-02-27 10:29 UTC, jrodewig commented on docs/reference/cluster/remote-info.asciidoc
> +    is configured.
```suggestion
    Number of open socket connections to the remote cluster when `proxy` mode
    is configured.
```

2020-02-27 10:30 UTC, jrodewig commented on docs/reference/cluster/remote-info.asciidoc
> +	mode is configured.
```suggestion
`max_socket_connections`::
    Maximum number of socket connections to the remote cluster when `proxy`
    mode is configured.
```

2020-02-27 10:32 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +only to a limited number of nodes in that remote cluster. There are two
```suggestion
to a limited number of nodes in that remote cluster. There are two
```

2020-02-27 10:33 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +// tag::how-sniff-mode-works[]
It doesn't look like this section is reused anywhere. I would remove the tags until the content is actually reused.
```suggestion
```

2020-02-27 10:33 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +// end::how-sniff-mode-works[]
```suggestion
```

2020-02-27 10:34 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +A cluster in sniff mode is created by a name and a list of seed nodes. When a
```suggestion
A cluster in sniff mode is created using a name and a list of seed nodes. When a
```

2020-02-27 10:38 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +part of remote cluster requests. This mode requires that the _gateway node_
```suggestion
seed nodes and up to three _gateway nodes_ are selected as
part of remote cluster requests. This mode requires that the gateway node's
```

2020-02-27 10:40 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +A cluster in proxy mode is created by a name and a single proxy address. When
```suggestion
In proxy mode, a cluster is created using a name and a single proxy address. When
```

2020-02-27 10:41 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +publish addresses are accessible.
```suggestion
the remote cluster. Proxy mode does not require remote cluster nodes
to have accessible publish addresses.
```

2020-02-27 10:44 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +// tag::how-proxy-mode-works[]
I'd remove this unneeded tag.
```suggestion
```

2020-02-27 10:44 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +// end::how-proxy-mode-works[]
```suggestion
```

2020-02-27 10:48 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
>  // tag::how-remote-clusters-work[]
The content is this tagged region gets re-used here:
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-works

Originally, that was intended to explain the concept of gateway nodes _before_ the recommendations outlined here:
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-gateway-seed-nodes

With this changes, I don't think this re-use makes sense anymore. I'm also not sure if those recommendations would work with proxy mode.

Could you advise on how these changes would impact those CCS recommendations? After that, you can either update those docs as a part of this PR or I can update them as part of a separate PR. Thanks!

2020-02-27 10:50 UTC, jrodewig requested changes
I commented on several, non-blocking nits, but I do have a bigger concern with how this will impact the CCS docs here:

https://github.com/elastic/elasticsearch/pull/52779/files#r385049630

I think we should plan to address that either as part of this PR or a separate one I handle. Either way, it's not clear to me how this would impact CCS recommendations.

Thanks!

2020-02-28 20:02 UTC, jrodewig commented
I took a stab at updating the CSS docs for remote cluster connection modes with e97d0216ce7062aedced50f47a1a7ae3929baece, which I pushed to this PR. This commits also removes some of the unneeded tags from the remote clusters docs.

That commit doesn't include some of the optional editorial suggestions I made. Feel free to take or leave those as you see fit. Also please feel free to change the CSS docs if needed.

2020-02-28 20:03 UTC, jrodewig reviewed
I took a stab at updating the CSS docs for remote cluster connection modes with e97d0216ce7062aedced50f47a1a7ae3929baece, which I pushed to this PR. This commit also removes some of the unneeded tags from the remote clusters docs.

That commit doesn't include some of the optional editorial suggestions I made. Feel free to take or leave those as you see fit. Also please feel free to change the CSS docs if needed.

2020-03-03 20:34 UTC, tbrooks8 commented
I updated this and added a section on proxy mode in the CCS docs.

2020-03-04 09:26 UTC, jrodewig commented on docs/reference/modules/cross-cluster-search.asciidoc
> +For remote clusters using the <<sniff-mode,sniff connection> mode, gateway and
This is required for the link to render properly.
```suggestion
For remote clusters using the <<sniff-mode,sniff connection>> mode, gateway and
```

2020-03-04 09:27 UTC, jrodewig commented on docs/reference/modules/cross-cluster-search.asciidoc
> +connections will connect to the configured `proxy_address`. Any desired
```suggestion
connections connect to the configured `proxy_address`. Any desired
```

2020-03-04 09:30 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +are exposed to the local cluster.
"accessible" is more consistent with what's stated in "proxy" mode and has less of a negative connotation.
```suggestion
cluster requests. This mode requires that the gateway node's publish addresses
are accessible by the local cluster.
```

2020-03-04 09:31 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +<4> The configured connection mode. By default it is <<sniff-mode,sniff>>, so
```suggestion
<4> The configured connection mode. By default, this is <<sniff-mode,`sniff`>>, so
```

2020-03-04 09:33 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +`cluster.remote.${cluster_alias}.seeds`::
Our docs typically use the `<variable>` convention.
```suggestion
`cluster.remote.<cluster_alias>.seeds`::
```

2020-03-04 09:34 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +`cluster.remote.${cluster_alias}.node_connections`::
```suggestion
`cluster.remote.<cluster_alias>.node_connections`::
```

2020-03-04 09:34 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +`cluster.remote.${cluster_alias}.proxy_address`::
```suggestion
`cluster.remote.<cluster_alias>.proxy_address`::
```

2020-03-04 09:34 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +`cluster.remote.${cluster_alias}.proxy_socket_connections`::
```suggestion
`cluster.remote.<cluster_alias>.proxy_socket_connections`::
```

2020-03-04 09:35 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +`cluster.remote.${cluster_alias}.server_name`::
```suggestion
`cluster.remote.<cluster_alias>.server_name`::
```

2020-03-04 09:43 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +`cluster.remote.${cluster_alias}.server_name`::
I think this should be `ifdef`, not `ifndef`.

I'm also not sure if it's necessary to do `ifdef::include-xpack[]`. Adding `[role="xpack"]` before the setting def should suffice.

```suggestion

[role="xpack"]
`cluster.remote.${cluster_alias}.server_name`::
```

2020-03-04 09:43 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +endif::[]
```suggestion

```

2020-03-04 09:43 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +  An optional hostname string which will be sent in the server_name field of
```suggestion
  An optional hostname string which is sent in the server_name field of
```

2020-03-04 09:44 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +  <<configuring-tls,{TLS is enabled}>>. The TLS transport will fail to open
```suggestion
  <<configuring-tls,TLS is enabled>>. The TLS transport will fail to open
```

2020-03-04 09:45 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +you must re-include seeds or proxy_address in the settings update request.
```suggestion
you must re-include seeds or a `proxy_address` in the settings update request.
```

2020-03-04 09:47 UTC, jrodewig commented on docs/reference/modules/remote-clusters.asciidoc
> +The sniff mode is the default connection mode.
```suggestion
Sniff mode is the default connection mode.
```

2020-03-04 09:51 UTC, jrodewig approved these changes
Look good overall. I did suggest a few needed changes:

- Fix a broken internal link
- Remove or update the new `ifndef` directive in the remote cluster settings section
- Use the standard `<variable>` convention in the remote cluster settings section

My other feedback is non-blocking. Feel free to use or ignore those items as you see fit.

Thanks for writing up the proxy mode CCS section!

2020-03-09 16:19 UTC, tbrooks8 commented
I made @jrodewig changes. @ywelsch are you good with this?

2020-03-09 16:22 UTC, ywelsch approved these changes
LGTM

2020-03-09 16:49 UTC, merged