Fix ingest pipeline _simulate api with empty docs never returns a res…
elastic/elasticsearch pull request #52937
Opened 2020-02-28 07:08 UTC by gaobinlong

This PR relates to #52833.

The main changes are:

1. Return 400 status code with error message if the docs array is empty.
2. Return 400 status code with error message if the element in docs array is not a map.
3. Check whether the docs array is empty again when executing the pipeline simulate, avoiding no response.
4. Add some test code for the changes.

2020-02-28 11:51 UTC, elasticmachine commented
Pinging @elastic/es-core-features (:Core/Features/Ingest)

2020-03-02 14:01 UTC, danhermann commented
@elasticmachine update branch

2020-03-02 14:22 UTC, danhermann requested changes
@gaobinlong, thank you for fixing this bug. I made a couple minor suggestions for the error messages. Otherwise, this looks great and I'll get it merged in.

2020-03-02 14:22 UTC, danhermann commented on server/src/main/java/org/elasticsearch/action/ingest/SimulatePipelineRequest.java
> +                throw new IllegalArgumentException("expected map in docs but found not");
```suggestion
                throw new IllegalArgumentException("malformed [docs] section, should include an inner object");
```

2020-03-02 14:22 UTC, danhermann commented on server/src/test/java/org/elasticsearch/action/ingest/SimulatePipelineRequestParsingTests.java
> +        assertThat(e2.getMessage(), equalTo("expected map in docs but found not"));
```suggestion
        assertThat(e2.getMessage(), equalTo("malformed [docs] section, should include an inner object"));
```

2020-03-02 14:22 UTC, danhermann commented on server/src/main/java/org/elasticsearch/action/ingest/SimulatePipelineRequest.java
> +            throw new IllegalArgumentException("must specify at least one doc");
```suggestion
            throw new IllegalArgumentException("must specify at least one document in [docs]");
```

2020-03-02 14:22 UTC, danhermann commented on server/src/test/java/org/elasticsearch/action/ingest/SimulatePipelineRequestParsingTests.java
> +        assertThat(e1.getMessage(), equalTo("must specify at least one doc"));
```suggestion
        assertThat(e1.getMessage(), equalTo("must specify at least one document in [docs]"));
```

2020-03-02 15:57 UTC, martijnvg commented on server/src/main/java/org/elasticsearch/action/ingest/SimulateExecutionService.java
> +                l.onResponse(new SimulatePipelineResponse(request.getPipeline().getId(),
Also maybe add a return statement here? Technically it is not needed because the for loop is skipped, but I find it easier to read.

2020-03-05 10:25 UTC, gaobinlong commented
Thanks @danhermann and @martijnvg,  I have made a new commit which contains some changes following your  comment. Can you have a look on that?

2020-03-11 14:03 UTC, danhermann commented
@elasticmachine update branch

2020-03-11 14:04 UTC, danhermann commented
@elasticmachine ok to test

2020-03-11 15:03 UTC, danhermann commented
Thanks for the fix, @gaobinlong! I'll get this merged now.

2020-03-11 15:05 UTC, merged