Add BlobStoreRepository#writeSnapshotIndexLatestBlob method
elastic/elasticsearch pull request #53189
Opened 2020-03-05 20:38 UTC by albertzaharovits

This commit creates a new protected method to access (write) the `index.latest` blob; there exists already to opposite method to read the said blob. This change permits `BlobStoreRepository` implementations to have a different access behavior, compared to the other blobs, for the special `index.latest` blob.

_NB: This change might not be REQUIRED for the encrypted repository, given the latest developments https://github.com/elastic/elasticsearch/pull/50846#issuecomment-594063727 , but it seems to me like a good-to-have option._

2020-03-05 20:38 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/Snapshot/Restore)

2020-03-06 07:21 UTC, original-brownbear commented
@albertzaharovits I think we don't need to make this change in a separate PR do we? (maybe I'm missing the reason for locking this in now?)
Can't we just make it as part of the encrypted repo PR when and if we need it?

2020-03-06 07:21 UTC, original-brownbear requested changes
See my comment, I don't see why we need this yet?

2020-03-06 08:04 UTC, albertzaharovits commented
Okay @original-brownbear , thanks for taking a look!
We don't need it indeed, but it looked like a useful change, closing.

2020-03-06 08:04 UTC, closed without merging