[DOCS]Add a lower-casing eamil address example to Keyword Tokenizer
elastic/elasticsearch pull request #53257
Opened 2020-03-07 11:34 UTC by jureaky

While reading a document for `Keyword Tokenizer`, I felt a bit confused why `Keyword Tokenizer` is needed.

`Keyword Tokenizer` is too simple to explain, which makes an example also simple.
However, as the document stated the other use-case(lower-casing email address) for users
to better understand the necessity of `Keyword Tokenizer`, I added the corresponding example.

### This is AS-IS:
![kwt-as-is](https://user-images.githubusercontent.com/24863651/76142634-e0c9fb00-60b2-11ea-928c-b801431636c6.PNG)

### This is Added Example:
![kwt-added-example](https://user-images.githubusercontent.com/24863651/76142641-f3443480-60b2-11ea-9833-e7d2864a25e9.PNG)

2020-03-09 09:45 UTC, elasticmachine commented
Pinging @elastic/es-search (:Search/Analysis)

2020-03-09 09:45 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2020-03-24 18:17 UTC, jrodewig commented on docs/reference/analysis/tokenizers/keyword-tokenizer.asciidoc
> +  "text": "john.SMITH@global-international.COM"
Changing the spacing to be more consistent with our other examples.

Let's also use `example.com` as the placeholder domain.
```suggestion
  "filter": [ "lowercase" ],
  "text": "john.SMITH@example.COM"
```

2020-03-24 18:17 UTC, jrodewig commented on docs/reference/analysis/tokenizers/keyword-tokenizer.asciidoc
> +      "end_offset": 35,
```suggestion
      "token": "john.smith@example.com",
      "start_offset": 0,
      "end_offset": 22,
```

2020-03-24 18:18 UTC, jrodewig commented on docs/reference/analysis/tokenizers/keyword-tokenizer.asciidoc
> +[ john.smith@global-inetrnational.com ]
```suggestion
[ john.smith@example.com ]
```

2020-03-24 18:18 UTC, jrodewig commented on docs/reference/analysis/tokenizers/keyword-tokenizer.asciidoc
> +The above sentence would produce the following term:
```suggestion
The request produces the following token:
```

2020-03-24 18:22 UTC, jrodewig requested changes
Thanks for the PR @jureaky.

The snippet looks good. I left some suggestions to fix typos and add some text to provide context.

I'd like to take another look after you've had a chance to go through those.

2020-03-24 18:22 UTC, jrodewig commented
@elasticmachine test this please

2020-03-24 18:42 UTC, jrodewig commented on docs/reference/analysis/tokenizers/keyword-tokenizer.asciidoc
> +=== Exmaple output(Lower-casing email address)
```suggestion
[discrete]
=== Combine with token filters
You can combine the `keyword` tokenizer with token filters to normalise
structured data, such as product IDs or email addresses.

For example, the following <<indices-analyze,analyze API>> request uses
`keyword` tokenizer and <<analysis-lowercase-tokenfilter,`lowercase`>> filter to
convert an email address to lowercase.
```

2020-03-28 06:33 UTC, jureaky commented
@jrodewig I changed all you suggested and force-pushed after rebase... PTAL !

2020-03-30 12:17 UTC, jrodewig approved these changes
LGTM. Thanks @jureaky. I'll get this merged and backported.

2020-03-30 12:17 UTC, jrodewig commented
@elasticmachine test this please

2020-03-30 12:35 UTC, merged

2020-03-30 13:12 UTC, jrodewig commented
### Backport commits
master 4fe8ad3
7.x  21f362a 
7.7 0813ec4 
7.6 8983bc3