_cat/shards support path stats
elastic/elasticsearch pull request #53461
Opened 2020-03-12 09:29 UTC by weizijun

_cat/shards cant support path stats. so where path.data uses multiple paths,  _cat/shards can be used to view the path of each shard

2020-03-12 09:44 UTC, elasticmachine commented
Pinging @elastic/es-core-features (:Core/Features/CAT APIs)

2020-03-13 22:28 UTC, probakowski requested changes
Thanks for working on this @weizijun! I've left couple of style suggestions, other than that it's good to go, I'll run tests and merge it as soon as you can update them

2020-03-13 22:28 UTC, probakowski commented on server/src/test/java/org/elasticsearch/rest/action/cat/RestShardsActionTests.java
> +            ShardRouting shardRouting = TestShardRouting.newShardRouting(
Please move arguments to single line (you can extract `ShardRoutingState` to variable to make it more readable)

2020-03-13 22:28 UTC, probakowski commented on server/src/test/java/org/elasticsearch/rest/action/cat/RestShardsActionTests.java
> +            ShardStats shardStats = new ShardStats(
Same as above

2020-03-13 22:28 UTC, probakowski commented on server/src/test/java/org/elasticsearch/rest/action/cat/RestShardsActionTests.java
> +        final RestController restController = new RestController(
`restController` is not really used here, it can be removed

2020-03-13 22:28 UTC, probakowski commented on server/src/test/java/org/elasticsearch/rest/action/cat/RestShardsActionTests.java
> +            ShardRouting shardRouting = shardRoutings.get(i);
Consider using iterator here, you don't have to increment counter by yourself
```java
Iterator<ShardRouting> shardRoutingsIt = shardRoutings.iterator();
for (final List<Table.Cell> row : rows) {
    ShardRouting shardRouting = shardRoutingsIt.next();
```

2020-03-14 13:30 UTC, weizijun commented
> Thanks for working on this @weizijun! I've left couple of style suggestions, other than that it's good to go, I'll run tests and merge it as soon as you can update them

@probakowski  Thank you very much for review, I have fixed these problem.

2020-03-14 15:47 UTC, probakowski approved these changes
LGTM :+1:

2020-03-14 15:49 UTC, probakowski commented
@elasticmachine ok to test

2020-03-15 04:27 UTC, weizijun commented
hi, @probakowski , I fix the rest-api-spec cat.shards error.

2020-03-15 21:01 UTC, probakowski commented
@elasticmachine update branch

2020-03-16 13:51 UTC, probakowski commented
@weizijun there are still tests failing and it seems strongly connected (`MixedClusterClientYamlTestSuiteIT.test {p0=cat.shards/10_basic/Help}`), can you please fix it?

2020-03-16 16:15 UTC, weizijun commented
> @weizijun there are still tests failing and it seems strongly connected (`MixedClusterClientYamlTestSuiteIT.test {p0=cat.shards/10_basic/Help}`), can you please fix it?

ok, I'am trying to fix the mixedClusterTest.

2020-03-17 10:07 UTC, weizijun commented
HI, @probakowski !, I fixed the bwc error. But some other case run error. Can you help to update branch again! Thank you very much!

2020-03-19 01:53 UTC, weizijun commented
@elasticmachine update branch

2020-03-19 16:18 UTC, weizijun commented
@elasticmachine update branch

2020-03-21 02:13 UTC, weizijun commented
@elasticmachine update branch

2020-03-23 02:04 UTC, weizijun commented
hi, @probakowski  @jakelandis , can you help to merge this pr? thanks!

2020-03-23 13:27 UTC, merged

2020-03-23 13:28 UTC, probakowski commented
Thanks @weizijun for working on this and fixing all issues, I've merged PR to master and will backport it soon to `7.x`

2020-03-24 03:18 UTC, weizijun commented
> Thanks @weizijun for working on this and fixing all issues, I've merged PR to master and will backport it soon to `7.x`

Thank you @probakowski ！