Deprecated support for delaying state recovery pending master nodes
elastic/elasticsearch pull request #53646
Opened 2020-03-17 03:55 UTC by ShawnLi1014

As mentioned in issue [#51806](https://github.com/elastic/elasticsearch/issues/51806), we now have the option to delay state recovery until a certain number of master-eligible nodes have joined, but this seems unnecessary: we require a majority of master-eligible nodes for state recovery, but there is no advantage in waiting for more.
This pull request deprecated the following settings in `GatewayService.java`
* `gateway.expected_nodes`
* `gateway.expected_master_nodes`
* `gateway.recover_after_nodes`
*  `gateway.recover_after_master_nodes`

2020-03-17 10:33 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/Allocation)

2020-03-17 10:40 UTC, DaveCTurner requested changes
I suggested an alternative way to note that these are deprecated in the docs, but the code changes look good.

2020-03-17 10:40 UTC, DaveCTurner commented on docs/reference/modules/gateway.asciidoc
>      The number of (data or master) nodes that are expected to be in the cluster.
```suggestion
    deprecated[7.7,This setting will be removed in 8.0. You should use `gateway.expected_data_nodes` instead.]
    The number of (data or master) nodes that are expected to be in the cluster.
```

2020-03-17 10:40 UTC, DaveCTurner commented on docs/reference/modules/gateway.asciidoc
>      The number of master nodes that are expected to be in the cluster.
```suggestion
    deprecated[7.7,This setting will be removed in 8.0. You should use `gateway.expected_data_nodes` instead.]
    The number of master nodes that are expected to be in the cluster.
```

2020-03-17 10:40 UTC, DaveCTurner commented on docs/reference/modules/gateway.asciidoc
>      Recover as long as this many data or master nodes have joined the cluster.
```suggestion
    deprecated[7.7,This setting will be removed in 8.0. You should use `gateway.recover_after_data_nodes` instead.]
    Recover as long as this many data or master nodes have joined the cluster.
```

2020-03-17 10:40 UTC, DaveCTurner commented on docs/reference/modules/gateway.asciidoc
>      Recover as long as this many master nodes have joined the cluster.
```suggestion
    deprecated[7.7,This setting will be removed in 8.0. You should use `gateway.recover_after_data_nodes` instead.]
    Recover as long as this many master nodes have joined the cluster.
```

2020-03-17 10:40 UTC, DaveCTurner commented on docs/reference/modules/gateway.asciidoc
> +    Deprecated and will be removed in 8.0
```suggestion
```

2020-03-17 10:40 UTC, DaveCTurner commented on docs/reference/modules/gateway.asciidoc
> +    Deprecated and will be removed in 8.0
```suggestion
```

2020-03-17 10:40 UTC, DaveCTurner commented on docs/reference/modules/gateway.asciidoc
> +    Deprecated and will be removed in 8.0
```suggestion
```

2020-03-17 10:40 UTC, DaveCTurner commented on docs/reference/modules/gateway.asciidoc
> +    Deprecated and will be removed in 8.0
```suggestion
```

2020-03-17 10:41 UTC, DaveCTurner commented
@elasticmachine test this please

2020-03-17 11:16 UTC, DaveCTurner commented
@elasticmachine update branch

2020-03-17 11:19 UTC, DaveCTurner commented
@elasticmachine test this please

2020-03-18 08:18 UTC, DaveCTurner commented
@elasticmachine test this please

2020-03-18 10:00 UTC, DaveCTurner approved these changes
LGTM thanks @ShawnLi1014. Do you plan to open a follow-up to remove these settings?

2020-03-18 10:03 UTC, merged

2020-03-18 10:12 UTC, ShawnLi1014 commented
> LGTM thanks @ShawnLi1014. Do you plan to open a follow-up to remove these settings?

Thank you, and yes I am working on it