ODBC: Document the new VarcharLimit and EarlyExecution params
elastic/elasticsearch pull request #54632
Opened 2020-04-02 10:42 UTC by bpintea

Add the documentation for the newly added [VarcharLimit](https://github.com/elastic/elasticsearch-sql-odbc/pull/229) and
[EarlyExecution](https://github.com/elastic/elasticsearch-sql-odbc/pull/227) DSN attributes.

2020-04-02 10:42 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2020-04-02 10:42 UTC, elasticmachine commented
Pinging @elastic/es-ql (:Query Languages/SQL)

2020-04-02 13:34 UTC, matriv approved these changes

2020-04-03 02:33 UTC, codebrain requested changes
LGTM, couple of typos

2020-04-03 02:33 UTC, codebrain commented on docs/reference/sql/endpoints/odbc/configuration.asciidoc
> +The maximum caracter length of the string type columns.
```suggestion
The maximum character length of the string type columns.
```

2020-04-03 02:33 UTC, codebrain commented on docs/reference/sql/endpoints/odbc/configuration.asciidoc
> +This is required for those applications that do not support column lenghts as
```suggestion
This is required for those applications that do not support column lengths as
```

2020-04-03 12:43 UTC, bpintea commented
Thanks, @codebrain , @matriv .

2020-04-03 12:44 UTC, merged