ILM stop step execution if writeIndex is false
elastic/elasticsearch pull request #54805
Opened 2020-04-06 13:05 UTC by andreidan

2020-04-06 13:05 UTC, elasticmachine commented
Pinging @elastic/es-core-features (:Core/Features/ILM+SLM)

2020-04-06 19:01 UTC, AthenaEryma requested changes
Nice catch, thanks for fixing. That said, I have a few issues with the tests.

2020-04-19 14:36 UTC, andreidan commented
@elasticmachine update branch

2020-04-24 13:23 UTC, andreidan commented
@elasticmachine update branch

2020-04-24 15:02 UTC, andreidan commented on x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/WaitForRolloverReadyStepTests.java
> +    public void testPerformActionWriteIndexIsFalse() {
thanks for the suggestion, adding a verify on the client mock

2020-04-24 15:05 UTC, andreidan commented on x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/WaitForRolloverReadyStepTests.java
> +    public void testPerformActionWriteIndexIsNullOrTrue() {
good shout! (I like to see unit tests as specification, collapse them and just by reading the test names understand what the invariants are, but in this case I think it makes sense to drop the extra test) Thanks for the suggestion

2020-04-24 16:25 UTC, andreidan commented
@elasticmachine run elasticsearch-ci/2

2020-04-28 17:10 UTC, dakrone approved these changes
LGTM

2020-04-29 11:06 UTC, merged