Minimise object allocation in MappingMetadata parsing
elastic/elasticsearch pull request #54880
Opened 2020-04-07 12:24 UTC by romseygeek

Currently, when building a `MappingMetadata` object from x-content, we build
a realised `Map<String, Object>` by calling `parser.map()` and then re-serialize
this in the `MappingMetadata` constructor.  This can create a lot of small objects
that are immediately thrown away, particularly for large mappings, which seems
wasteful.

This commit changes `IndexMetadata` x-content parsing code to instead pass
the mappings map directly as a `BytesReference`.  We still need to do some 
parsing but we avoid much of the object allocation.  It also tightens up the contract
for what `MappingMetadata` will accept as its source, which must always be in
json format and have a containing type field.

2020-04-07 12:24 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/CRUD)

2020-04-07 12:24 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (:Core/Infra/Core)

2020-04-07 14:45 UTC, romseygeek commented
@elasticmachine update branch

2020-04-07 16:01 UTC, romseygeek commented
@elasticmachine run elasticsearch-ci/2

2020-04-08 12:49 UTC, ywelsch requested changes

2020-04-08 12:49 UTC, ywelsch commented on server/src/main/java/org/elasticsearch/cluster/metadata/MappingMetadata.java
> +    public MappingMetadata(BytesReference mapping) {
What if were to keep the `CompressedXContent` constructor instead here? I would feel more comfortable about that, as we currently implicitly assume that the bytes passed here are always decompressed?

Note that we are anyway decompressing the array again in the `new CompressedXContent()` call in line 83 as `CompressedXContent` is computing the `crc32`.

2020-07-23 08:09 UTC, ywelsch commented
@romseygeek are you still interested in pursuing this PR?

2020-07-23 08:11 UTC, romseygeek commented
@ywelsch I am, but I don't think I'm going to have time to look at it properly any time soon

2020-07-23 08:15 UTC, ywelsch commented
ok, let's close the PR for the time being then.

2020-07-23 08:15 UTC, closed without merging