Add documentation about path prefix
elastic/elasticsearch pull request #55057
Opened 2020-04-10 13:26 UTC by dadoonet

When using a reverse proxy, developers might need to define a path prefix.
This appears to be not documented.

See related discussions:

* https://discuss.elastic.co/t/resthighlevelclient-accessing-an-elastic-http-endpoint-behind-reverse-proxy/117306
* https://discuss.elastic.co/t/elesticsearch-rest-http-request-through-redirected-url/227478
* https://discuss.elastic.co/t/java-high-level-rest-client-including-a-basepath-to-request-urls/217533

2020-04-10 13:26 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2020-04-10 16:25 UTC, elasticmachine commented
Pinging @elastic/es-core-features (:Core/Features/Java Low Level REST Client)

2020-05-15 17:27 UTC, andreidan requested changes
Thanks for working on this @dadoonet 

Left a minor suggestion about reorganising the structure

2020-05-15 17:27 UTC, andreidan commented on docs/java-rest/low-level/usage.asciidoc
> +
Shall we move this below the example that shows the encrypted communication configuration? (below line 222)

I think the encrypted communication example still stands as an example on its own and we can showcase the proxy path configuration a standalone paragraph and code snippet

2022-07-27 15:00 UTC, elasticsearchmachine commented
Pinging @elastic/es-docs (Team:Docs)

2022-07-27 15:00 UTC, elasticsearchmachine commented
Pinging @elastic/clients-team (Team:Clients)

2024-03-05 13:30 UTC, dadoonet commented
@swallez I'm wondering if we should close this PR. It has been there since 2020 ;)
It was just about documenting path prefix...

2025-01-29 18:00 UTC, leemthompo commented
> [!IMPORTANT]  
> Elastic documentation is migrating to Markdown for version 9.0+. See the [migration guide](https://elastic.github.io/docs-builder/migration/freeze/index.html) for details.


## ℹ️ **What's happening?**
- Starting January 29, we will start closing all unmerged documentation PRs targeting main/master
- We're migrating from AsciiDoc to Markdown for 9.0+
- 9.0 docs will be frozen from January 29 until February 20 2024
- **NOTE**: PRs that include both code and documentation changes will remain open

### **What do I need to do?**

#### For **<=8.x docs**:
 1. Rebase your PR to target the relevant 8.x branch instead
 2. The content can remain in AsciiDoc format

#### For **9.0+ docs**:

_Option 1_:
 - Draft docs in Markdown
 - Once migration freeze ends, find the relevant page in the new docs system and use the edit options to submit your changes


_Option 2_:
- Open an issue in [elastic/docs-content](https://github.com/elastic/docs-content)

### 💡 **Need help?**
1. For Elasticians: Ask in **#docs** Slack channel
2. For external contributors: Open an issue in [elastic/docs-content](https://github.com/elastic/docs-content)

2025-10-02 07:19 UTC, elasticsearchmachine commented
Pinging @elastic/core-docs (Team:Docs)

2026-07-08 00:39 UTC, elasticsearchmachine commented
Pinging @elastic/devtools-team (Team:Clients)

2026-07-08 08:47 UTC, swallez commented
The Java client docs have moved to https://github.com/elastic/elasticsearch-java/tree/main/docs/reference/transport/rest-client

@l-trotta can you check if the additional information from this PR exists in the current docs?

2026-07-08 08:47 UTC, closed without merging