Save memory in on aggs in async search
elastic/elasticsearch pull request #55083
Opened 2020-04-10 18:13 UTC by nik9000

This replaces a reference to the result of partially reducing
aggregations that async search keeps with a reference to the serialized
form of the result of the partial reduction which we need to keep
anyway.

2020-04-10 18:13 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo (:Analytics/Aggregations)

2020-04-10 18:14 UTC, nik9000 commented
I've marked this a blocker for 7.8.0 because we'd really like to avoid releasing with the aggs referenced twice in async search. We have plenty of time to get it or something like it merged.

2020-04-10 18:15 UTC, nik9000 commented
Follow up to https://github.com/elastic/elasticsearch/pull/54758#pullrequestreview-390018326

2020-04-10 19:40 UTC, nik9000 commented
Test failures are real. Looks like I should have run more of the tests before opening!

2020-04-14 18:48 UTC, nik9000 commented
I could have made aggs from remote clusters delayed but that'd have effected the transport client and, maybe, other things. I'll investigate it, but I don't want to "sneak" that in.

2020-04-15 19:52 UTC, jimczi requested changes
The change makes sense to me. I left one comment regarding the usage of `InternalSearchResponse#aggregations` that should be addressed.

2020-04-15 19:52 UTC, jimczi commented on server/src/main/java/org/elasticsearch/search/internal/InternalSearchResponse.java
> +            return aggregations.get();
I am worried about the hidden cost of calling this on `serialized` aggs. Can we at least ensure that we don't get aggregations twice like [here](https://github.com/Kobar-Demo/Elasticsearch_Clone/blob/master/x-pack/plugin/async-search/src/main/java/org/elasticsearch/xpack/search/MutableSearchResponse.java#L132) ?

2020-04-28 14:08 UTC, nik9000 commented
Replaced by #55683.

2020-04-28 14:08 UTC, closed without merging