[DOCS] Combine search API and URI search API reference docs
elastic/elasticsearch pull request #55884
Opened 2020-04-28 19:17 UTC by jrodewig

The search API and URI search pages document the same `_search` API.
This combines the documentation from each page under the search API
docs.

Changes:

* Adds an abbreviated title for the search API page.
* Removes the following invalid query parameters:
  * `analyzer`
  * `analyze_wildcard`
  * `default_operator`
  * `df`
  * `lenient`
  * `suggest_mode`
  * `suggest_size`
* Removes the URI search docs page and adds a related redirect.
* Updates the headings of several examples

As this change contains a redirect, I'll treat it as a breaking change and only apply to the `master` branch. I'll open up separate PRs to remove the invalid query parms after merge.

Relates to #48194

2020-05-04 18:34 UTC, debadair requested changes
Left a couple suggested edits--the one sentence definitely needs tweaked one way or another. :-)

2020-05-04 18:34 UTC, debadair commented on docs/reference/search/search.asciidoc
> +no partial results. Defaults to `true`.
```suggestion
If `true`, returns partial results if there are request timeouts or
<<shard-failures,shard failures>>. If `false`, returns an error with
no partial results. Defaults to `true`.
```

2020-05-04 18:34 UTC, debadair commented on docs/reference/search/search.asciidoc
> +`search.default_allow_partial_results` to `false` in your cluster settings.
```suggestion
To override the default for this field, set the 
`search.default_allow_partial_results` cluster setting to `false`.
```

2020-05-04 18:36 UTC, jrodewig commented on docs/reference/search/search.asciidoc
> +no partial results. Defaults to `true`.
Thanks for catching this one.

2020-05-04 18:37 UTC, jrodewig commented
Thanks for catching those @debadair. I've committed your suggestions.

2020-05-04 18:55 UTC, debadair approved these changes
LGTM

2020-05-05 14:28 UTC, merged

2020-05-05 15:24 UTC, jrodewig commented
### Backport commits
master e6542c0
7.x a528319 
7.7 804c38f 
7.6  ac36232