Remove codec from ilm action forcemerge
elastic/elasticsearch pull request #55978
Opened 2020-04-29 20:48 UTC by freakingid

`codec` was removed at some point in the past, yet the documentation still lists it.

The issue: https://github.com/elastic/elasticsearch/issues/41274
and its associated PR: https://github.com/elastic/elasticsearch/pull/49974
... seem to be adding "codec" to ILM action forcemerge in version 7.7. However, older docs need corrected.

2020-04-30 13:24 UTC, elasticmachine commented
Pinging @elastic/es-core-features (:Core/Features/ILM+SLM)

2020-05-04 18:22 UTC, debadair approved these changes
LGTM

2020-05-21 11:58 UTC, DaveCTurner requested changes
Hang on, we do support setting the `codec`, but it's called `index_codec` for reasons I do not currently understand. I'm raising this with the team.

2020-10-14 16:25 UTC, jrodewig commented
With #62243, `index_codec` is now documented: https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-forcemerge.html

I'm going to close this issue. Please feel free to re-open if I missed something. Thanks!

2020-10-14 16:25 UTC, closed without merging