Throw a RepositoryConflictException when trying to put or delete a repository in used
elastic/elasticsearch pull request #56070
Opened 2020-05-01 09:09 UTC by gaobinlong

Relates to #54637.

The main changes are:
1. Add a `RepositoryConflictException` with 409 status code.
2. Throw a `RepositoryConflictException` when trying to put or delete a repository in used.
3. Add unit test for the change.

2020-05-01 11:50 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/Snapshot/Restore)

2020-05-01 12:04 UTC, original-brownbear requested changes
Thanks @gaobinlong I'm on board with this change in general. I left a few smaller points on the code.

2020-05-01 12:04 UTC, original-brownbear commented on server/src/test/java/org/elasticsearch/snapshots/RepositoriesIT.java
> +        try {
We actually have a neat short-cut for testing this kind of spot with the `expectThrows` method that keeps this much shorter. See https://github.com/elastic/elasticsearch/blob/master/server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java#L2169 for an example.

2020-05-01 12:04 UTC, original-brownbear commented on server/src/test/java/org/elasticsearch/snapshots/RepositoriesIT.java
> +        try {
Same here, `expectThrows` is nicer I think :)

2020-05-02 15:11 UTC, original-brownbear commented
Jenkins test this

2020-05-02 19:03 UTC, original-brownbear commented
@gaobinlong thanks for the changes, looking good. There's a related test failure here though, could you take a look please? (ideally make sure at least `./gradlew :server:check` passes locally) Thanks!

2020-05-06 06:16 UTC, gaobinlong commented
@original-brownbear, I have pushed a new commit to fix the test failure  and  `./gradlew :server:check` executed successfully in my local environment.

2020-05-06 06:56 UTC, original-brownbear commented
Jenkins test this

2020-06-03 05:10 UTC, gaobinlong commented
@original-brownbear , all checks have passed, can this PR be approved?

2020-06-03 07:11 UTC, fcofdez commented
I can see that there are some merge conflicts and checks failing, could you please merge the latest master branch @gaobinlong? thanks!

2020-06-03 09:09 UTC, gaobinlong commented
@fcofdez , I have merged the master branch yet.

2020-06-03 09:19 UTC, fcofdez commented
Jenkins test this please

2020-06-10 03:27 UTC, gaobinlong commented
@fcofdez, there is a new conflict, I have resolved it and pushed a new commit, can you help to take a look at that?

2020-12-23 02:22 UTC, gaobinlong commented
Can we take one step further here?

2021-09-14 07:10 UTC, DaveCTurner commented
I think this is a sensible change to make. I resolved the merge conflicts that have accumulated since it was opened and will ping @fcofdez for another review.

2021-09-14 13:13 UTC, fcofdez commented
@elasticmachine run tests

2021-09-14 13:21 UTC, fcofdez commented
@elasticmachine test this please

2021-09-14 16:06 UTC, fcofdez requested changes
Sorry for the delay on this @gaobinlong, the changes look good to me but the test failures seems to be related to the change. We should fix those before merging this patch.

2021-09-16 03:17 UTC, gaobinlong commented
@fcofdez I can't see the details of the test failures, because the url shows a 404 error: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+part-2/5040/ . Can you help to take a look?

2021-09-16 09:29 UTC, fcofdez commented
@elasticmachine test this please

2021-09-16 09:30 UTC, fcofdez commented
That's strange, I couldn't see the failures either. I've triggered a new CI round to regenerate the results. Sorry about that.

2021-09-16 12:44 UTC, fcofdez commented
@gaobinlong this are the failing tests, I think those expect the previous `IllegalArgumentException` or the previous status code.
```
BlobStoreDynamicSettingsIT » testUpdateRateLimitsDynamically FAILED 
SharedClusterSnapshotRestoreIT » testDeleteRepositoryWhileSnapshotting FAILED 
SharedClusterSnapshotRestoreIT » testSnapshotSucceedsAfterSnapshotFailure FAILED
SearchableSnapshotsRepositoryIntegTests » testRepositoryUsedBySearchableSnapshotCanBeUpdatedButNotUnregistered
SearchableSnapshotsClientYamlTestSuiteIT » test {p0=/repository/Delete repository when a snapshot is mounted as an index}
```

2021-09-27 13:28 UTC, gaobinlong commented
@fcofdez ,I've fixed the test failures, please help to trigger a new CI, thanks!

2021-09-27 13:38 UTC, fcofdez commented
@elasticmachine test this please

2021-09-28 03:22 UTC, gaobinlong commented
@fcofdez,  the CI task `:x-pack:plugin:searchable-snapshots:qa:rest:yamlRestTestV7CompatTest` executed failed, we may need backport the change to the 7.x branch, can you help to take a look how to do this?  We should change the `request` to `conflict` here: 
https://github.com/elastic/elasticsearch/blob/a5db81b34c36059b2c1d6d94d434667636f9b0c0/x-pack/plugin/searchable-snapshots/qa/rest/src/yamlRestTest/resources/rest-api-spec/test/repository.yml#L75

2021-09-29 12:08 UTC, fcofdez commented
```
diff --git a/server/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestDeleteRepositoryAction.java b/server/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestDeleteRepositoryAction.java
index 1198f58b1c0..9506474583a 100644
--- a/server/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestDeleteRepositoryAction.java
+++ b/server/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestDeleteRepositoryAction.java
@@ -8,8 +8,12 @@

 package org.elasticsearch.rest.action.admin.cluster;

+import org.elasticsearch.action.ActionListener;
 import org.elasticsearch.action.admin.cluster.repositories.delete.DeleteRepositoryRequest;
+import org.elasticsearch.action.support.master.AcknowledgedResponse;
 import org.elasticsearch.client.node.NodeClient;
+import org.elasticsearch.common.xcontent.ToXContentObject;
+import org.elasticsearch.core.RestApiVersion;
 import org.elasticsearch.rest.BaseRestHandler;
 import org.elasticsearch.rest.RestRequest;
 import org.elasticsearch.rest.action.RestToXContentListener;
@@ -40,6 +44,23 @@ public class RestDeleteRepositoryAction extends BaseRestHandler {
         DeleteRepositoryRequest deleteRepositoryRequest = deleteRepositoryRequest(request.param("repository"));
         deleteRepositoryRequest.timeout(request.paramAsTime("timeout", deleteRepositoryRequest.timeout()));
         deleteRepositoryRequest.masterNodeTimeout(request.paramAsTime("master_timeout", deleteRepositoryRequest.masterNodeTimeout()));
-        return channel -> client.admin().cluster().deleteRepository(deleteRepositoryRequest, new RestToXContentListener<>(channel));
+        return channel -> {
+            final RestToXContentListener<ToXContentObject> restListener = new RestToXContentListener<>(channel);
+            client.admin().cluster().deleteRepository(deleteRepositoryRequest, new ActionListener<>() {
+                @Override
+                public void onResponse(AcknowledgedResponse acknowledgedResponse) {
+                    restListener.onResponse(acknowledgedResponse);
+                }
+
+                @Override
+                public void onFailure(Exception e) {
+                    if (request.getRestApiVersion().equals(RestApiVersion.V_7)) {
+                        restListener.onFailure(new IllegalStateException(e.getMessage()));
+                    } else {
+                        restListener.onFailure(e);
+                    }
+                }
+            });
+        };
     }
 }
```

@gaobinlong we need to add a little compatibility layer for the `7.x` REST API as we won't backport this change. I'll take care of adding a deprecation notice in `7.x` regarding this change.

2021-10-19 03:04 UTC, gaobinlong commented
@fcofdez, all checks have passed yet, can this PR be merged now?

2021-10-20 10:24 UTC, fcofdez commented
@gaobinlong sorry for the delay on this. I've pushed a commit handling the BWC dance and docs. Once the CI runs and I check that the docs are fine I'll merge this. Again, sorry for the delay.

2021-10-21 10:58 UTC, fcofdez approved these changes
LGTM

2021-10-21 11:16 UTC, merged

2021-10-21 11:17 UTC, fcofdez commented
Thanks for your contribution @gaobinlong !