ITV2: disallow duplicate dynamic templates
elastic/elasticsearch pull request #56291
Opened 2020-05-06 16:10 UTC by andreidan

Dynamic templates can contain multiple templates with the same name. This
commit changes the way V2 index templates mappings are resolved to add
deduplication of dynamic templates when resolving the mappings, by having
the last dynamic templates override the ones defined with the same name
earlier in the `dynamic_templates` array.

Relates to #53101
Relates to #53326
Relates to #28988

2020-05-06 16:10 UTC, elasticmachine commented
Pinging @elastic/es-core-features (:Core/Features/Indices APIs)

2020-05-06 16:35 UTC, dakrone commented
@andreidan can you add a test that component templates merge their dynamic templates correctly? I think because we merge the XContent maps prior to the dedupe it is possible to end up with an invalid dynamic template if you have two component templates that each define a dynamic template with the same name but different configurations that, when merged, make the template invalid.

2020-05-07 10:47 UTC, andreidan commented
@dakrone thanks for the suggestion on the component templates merging. Great shout on testing that as you were right and we are merging the Maps so, even though we dedup the key names (ie. there will only be one `dynamic_template` with a particular name) the bodies are merged.

2020-05-07 13:12 UTC, andreidan commented
@elasticmachine update branch

2020-05-07 15:32 UTC, dakrone requested changes
I left a couple of comments similar to what we talked about regarding naming, thanks for doing this Andrei!

2020-05-07 15:32 UTC, dakrone commented on server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
> +                }
I think we can encapsulate this logic into a method to make it a bit clearer what's going on, perhaps something like:

```
nonProperties = removeDuplicatedDynamicTemplates(nonProperties, innerTemplateNonProperties);
```

Then the same method can be used below (where these lines are almost identical except for the maps passed in).

2020-05-07 15:32 UTC, dakrone commented on server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
> +    private static List<Map<String, Object>> removeAll(List<Map<String, Object>> first, List<Map<String, Object>> second) {
Maybe call this `removeOverlapping` to make it a bit clearer what it's doing?

2020-05-07 15:55 UTC, dakrone approved these changes
LGTM, thanks for working on this Andrei!

2020-05-12 13:24 UTC, merged