[DOCS] Add search pagination docs
elastic/elasticsearch pull request #56785
Opened 2020-05-14 17:43 UTC by jrodewig

Reworks the `from / size` content to `Paginate search results`.

Moves those docs from the `Request body search` API docs page
(slated for deletion) to the `Run a search` tutorial docs.

Also adds some notes to the `from` and `size` param docs.

Because this involves redirects, I only plan to merge into `master`.

Relates to #48194

2020-05-14 17:43 UTC, elasticmachine commented
Pinging @elastic/es-search (:Search/Search)

2020-05-14 17:43 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2020-05-14 22:45 UTC, debadair requested changes
Left some comments--the wording of the offset piece, in particular, definitely needs to be changed.

2020-05-14 22:45 UTC, debadair commented on docs/reference/search/request/from-size.asciidoc
> +number of results to return.
"Offset from the first result you want to fetch" doesn't make sense. It's an offset from the beginning of the result set. [The Definitive Guide ](https://www.elastic.co/guide/en/elasticsearch/guide/2.x/pagination.html) called it "the number of initial results you want to skip". That seems a little convoluted--it's really just the document you want to start with.

```suggestion
To paginate through a larger set of results, you can use the search API's `size`
and `from` parameters. The `size` parameter is the number of matching documents to return. The `from` parameter is a zero-indexed offset from the beginning of the complete result set that indicates the document you want to start with. 
```

2020-05-14 22:45 UTC, debadair commented on docs/reference/search/request/from-size.asciidoc
> +====
I think the point here is that by default, you can page through a maximum of 10,000 documents. I'd say that, and then xref the settings, but probably not as a note. Instead,
I'd pull some of the cautionary info about deep paging into an important note from the definitive guide.

2020-05-14 22:45 UTC, debadair commented on docs/reference/search/search.asciidoc
> +[IMPORTANT]
Some combo of only being able to page through 10k docs by default and the warning about deep paging would need to go replace these admonitions, as well.

2020-05-15 12:27 UTC, jrodewig commented
Thanks for your review @debadair, particularly your help with the `from` sentence.

I've made some other adjustments based on your feedback with a1d3c9f3feea679293b2c62158e597b0bbc6426c.

I think this is ready for another review at your convenience.

2020-05-15 12:46 UTC, jrodewig commented on docs/reference/search/request/from-size.asciidoc
> +results, starting with the first, most relevant document.
I meant to comment on this!

I think "search result" tends to be a more intuitive term than "hit" -- but I don't see us getting rid of either in the near term. It's sort of a similar synonym situation with "token" and "term."

However, I also know that "search results" can be a more loaded term while "hit" can be more narrowly defined.

That said, I don't have a strong preference. If you lean toward one or the other, please let me know. There could be other impacts I haven't considered. I can update the changes here to use "hit/hits" if wanted.

2020-05-15 21:17 UTC, debadair approved these changes
Looks good!

2020-05-15 21:19 UTC, jrodewig commented
Thanks!

2020-05-15 21:22 UTC, merged

2020-06-01 20:44 UTC, jrodewig commented
### Backport commits
master 56d7af0
7.x 994781ff36160b0467aaf092c463fbed7d1da50d 
7.8 e7516fc7d65b2c3bc8abdd251b271e71a4e3bd74
7.7  f31e172