Add Restore UUID Index Setting
elastic/elasticsearch pull request #56930
Opened 2020-05-19 08:06 UTC by original-brownbear

Pre-requesite for #50278 to be able to uniquely identify index metadata by
its version fields and UUIDs when restoring into closed indices.

See related discussion here: https://github.com/elastic/elasticsearch/pull/50278#discussion_r382498267

2020-05-19 08:06 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/Distributed)

2020-05-19 16:00 UTC, ywelsch requested changes
I wonder if we should generalize this to an `index.history.uuid` (which is also updated on dangling indices import, as well as whenever we run the unsafe bootstrap command). This makes this also more generally useful to characterize the identity of the index metadata.

2020-05-20 16:22 UTC, original-brownbear commented
Jenkins run elasticsearch-ci/2 (random known aggs failure)

2020-05-20 16:44 UTC, original-brownbear commented
Jenkins run elasticsearch-ci/bwc

2020-05-20 19:29 UTC, original-brownbear commented on x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportResumeFollowAction.java
> +        settings.remove(IndexMetadata.SETTING_RESTORE_UUID);
Jup makes sense to me => done.

2020-05-20 19:30 UTC, original-brownbear commented
Thanks @ywelsch, I renamed the setting as suggested and added the functionality to dangling index import and unsafe bootstraps now.

2020-05-25 08:32 UTC, ywelsch approved these changes
LGTM

2020-05-25 08:33 UTC, original-brownbear commented
Thanks Yannick!

2020-05-25 08:34 UTC, merged