Add http proxy support for OIDC realm
elastic/elasticsearch pull request #57039
Opened 2020-05-21 13:24 UTC by jkakavas

This change introduces support for using an http proxy for egress
communication of the OpenID Connect realm.

resolves: https://github.com/elastic/elasticsearch/issues/53379

2020-05-21 13:24 UTC, elasticmachine commented
Pinging @elastic/es-security (:Security/Authentication)

2020-05-24 14:26 UTC, albertzaharovits requested changes
I think we should do a better job validating the values and expressing the dependency between the new proxy settings.
I have left suggestions with my preferred approach, but feel free to elaborate freely over them.
In addition we should add tests in `OpenIdConnectRealmSettingsTests` and also maybe update the docs to reflect the valid values (eg http/https for scheme).

I also _think_ we should support configuring ssl context parameters (eg, a different truststore, like at `HttpExporter#configureSslStrategy`), as I doubt the internal proxies to the OP have public certs.
I'm not sure though, maybe in a docker world and given that we package the runtime, it's actually decent to recommend appending the JVM trustore; but I doubt it. Nevertheless, we can tackle this in a follow-up (raising an issue for this is enough for the moment IMO).

2020-05-24 15:10 UTC, jkakavas commented
> I also think we should support configuring ssl context parameters (eg, a different truststore, like at HttpExporter#configureSslStrategy), as I doubt the internal proxies to the OP have public certs.
I'm not sure though, maybe in a docker world and given that we package the runtime, it's actually decent to recommend appending the JVM trustore; but I doubt it. Nevertheless, we can tackle this in a follow-up (raising an issue for this is enough for the moment IMO).

We _do_ already expose TLS settings specific to the outgoing connections relevant to the OIDC realm : https://github.com/elastic/elasticsearch/blob/bbaa1f5fd5dabe7d9e2781f0eade947cbb1223fb/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java#L568

2020-05-24 15:11 UTC, jkakavas commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authc/oidc/OpenIdConnectRealmSettings.java
> +        key -> Setting.simpleString(key, Setting.Property.NodeScope));
> The value validation for hostname is probably overkill in this form

Nah, I like delegating the validation to the class that would actually do it in runtime too, +1

2020-05-24 15:12 UTC, jkakavas commented
> I think we should do a better job validating the values and expressing the dependency between the new proxy settings.

True , true, that was sloppy - will ammend

2020-05-24 15:34 UTC, albertzaharovits commented
> We do already expose TLS settings specific to the outgoing connections relevant to the OIDC realm

Gotcha, you're right, I got confused thinking that we need a ssl context for the `.proxy*` namespace.

2020-06-01 21:40 UTC, jkakavas commented
Ping @albertzaharovits this is ready for another round

2020-06-02 08:19 UTC, jkakavas commented
@elasticmachine update branch

2020-06-02 16:23 UTC, albertzaharovits approved these changes
LGTM 

Thank you for the patience, Ioannis! I should've prioritized this review more, apologies!

2020-06-02 16:23 UTC, albertzaharovits commented on docs/reference/settings/security-settings.asciidoc
> +http client for all back-channel communication to the OpenID Connect Provider
nit "backchannel" is a valid english word.

2020-06-02 16:23 UTC, albertzaharovits commented on x-pack/qa/oidc-op-tests/build.gradle
> +String ephmeralOpPort
this nit is still standing

2020-06-03 05:52 UTC, jkakavas commented on x-pack/qa/oidc-op-tests/build.gradle
> +String ephmeralOpPort
:facepalm:

2020-06-03 06:36 UTC, merged