Release HTTP Request Body Earlier
elastic/elasticsearch pull request #57094
Opened 2020-05-24 20:03 UTC by original-brownbear

We don't need to hold on to the request body past the beginning of sending
the response. There is no need to keep a reference to it until after the response
has been sent fully and we can eagerly release it here.
Note, this can be optimized further to release the contents even earlier but for now
this is an easy increment to saving some memory on the IO pool.

2020-05-24 20:04 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/Network)

2020-05-24 22:14 UTC, keypointt commented on modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpResponse.java
>      }
sorry maybe a naive comment, is it better to name public api `getRequestHeaders` ?

2020-05-24 22:17 UTC, keypointt reviewed
minor non-blocking

2020-05-25 07:04 UTC, original-brownbear commented on modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpResponse.java
> +    Netty4HttpResponse(HttpHeaders requestHeaders, HttpVersion version, RestStatus status, BytesReference content) {
I figured if we release the request before using these parts (version and headers) it's a little nicer not to pass the full request around. Also, for non-pooled allocation (this includes all requests that aren't search or bulk) this makes the GC's life a little easier)

2020-05-25 09:03 UTC, ywelsch requested changes
Let's align NIO in this PR as well (same transformation)

2020-05-25 09:03 UTC, ywelsch commented on modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/cors/Netty4CorsHandler.java
> +    public static void setCorsResponseHeaders(HttpHeaders headers, HttpResponse resp, CorsHandler.Config config) {
Do the same for NioCorsHandler here?

2020-05-25 09:18 UTC, original-brownbear commented
Thanks Yannick, aligned the NIO implementation in 3b7ebcf

2020-05-25 09:21 UTC, ywelsch approved these changes
LGTM

2020-05-25 10:02 UTC, original-brownbear commented
Thanks Yannick!

2020-05-25 10:02 UTC, merged