Handle Class.getProtectionDomain() returning null
elastic/elasticsearch pull request #58166
Opened 2020-06-16 12:22 UTC by pugnascotia

Closes #58075. This method isn't implemented on the Android JVM, and
always returns null.

2020-06-16 12:22 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (:Core/Infra/Core)

2020-06-16 15:15 UTC, rjernst approved these changes
LGTM. One ask.

2020-06-16 15:15 UTC, rjernst commented on server/src/main/java/org/elasticsearch/Build.java
> +        final CodeSource codeSource = protectionDomain == null ? null : protectionDomain.getCodeSource();
Can you please add a comment explaining when this can potentially be null?

2020-06-16 16:12 UTC, jasontedor requested changes
I'm doubting that we should do this. There's the question of whether or not we support the Android JVM (we don't), and we have a policy on the team that we don't make changes for platforms that we don't support, because then there's a level of implicit support that we can't maintain. We don't have tests for this, that run on the Android JVM, so what do we when further issues arise, or how do we avoid breaking this in the future? For the server codebase, which the clients depend on right now, we're not going to invest any effort in getting it supported on the Android JVM, which is what would be needed to offer that level of support for the clients. We can revisit whether or not the clients support the Android JVM when they are separate from the codebase, but that's in the future. Lastly, I'm fairly certain on the JDKs that we do not support, this can never be null, so this really is making a change for a JVM that we don't support, and I don't think we should do that.

2020-06-24 08:52 UTC, pugnascotia commented
Closing this PR given the issue around JVM support.

2020-06-24 08:52 UTC, closed without merging