Migrate plugin packaging tests to java
elastic/elasticsearch pull request #58518
Opened 2020-06-24 21:28 UTC by rjernst

This commit converts the bats tests for the plugin cli into the java
packaging test framework. The new tests only use the example plugin to
test the plugin cli. The tests for each individual plugin's contents
after being installed are handled by a new unit test for the plugin
installer added in #58287.

2020-06-24 21:28 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (:Core/Infra/Packaging)

2020-06-24 22:57 UTC, mark-vieira approved these changes
The build bits all seem sound to me but someone more familiar might want to take a pass at the actual test coverage.

2020-06-25 16:15 UTC, nik9000 requested changes
LGTM except I think you commented out some code you meant to keep.

2020-06-25 16:15 UTC, nik9000 commented on qa/os/src/test/java/org/elasticsearch/packaging/util/Shell.java
> +            /*if (size > 100 * 1024) {
Leftover?

2020-06-25 16:15 UTC, nik9000 commented on qa/os/src/test/java/org/elasticsearch/packaging/test/PluginCliTests.java
> +        withCustomConfig(confPath -> assertWithExamplePlugin(installResult -> {}));
I don't remember why some of them booted ES and asserted that the example plugin looks good and some didn't. I think what you have here is fine though, just asserting that the installer didn't blow up is probably good enough in these cases so long as we have a single test that asserts that it did indeed install the plugin in all the way. And you have that above.

:+1:

2020-06-25 16:50 UTC, rjernst commented on qa/os/src/test/java/org/elasticsearch/packaging/util/Shell.java
> +            /*if (size > 100 * 1024) {
Oops yes, will uncomment.

2020-06-25 16:51 UTC, rjernst commented on qa/os/src/test/java/org/elasticsearch/packaging/util/Shell.java
> +            /*if (size > 100 * 1024) {
I pushed d6b6627

2020-06-25 18:49 UTC, nik9000 approved these changes
LGTM

2020-06-25 20:38 UTC, merged