Increase default write queue size
elastic/elasticsearch pull request #59464
Opened 2020-07-13 20:32 UTC by tbrooks8

This commit increases the default write queue size to 4000. This is to
allow a greater number of pending indexing requests. This work is safe
as we have added additional memory limits.

2020-07-13 20:32 UTC, elasticmachine commented
Pinging @elastic/es-distributed (:Distributed/CRUD)

2020-07-13 20:33 UTC, tbrooks8 commented
After this is merged, it needs to be forward ported to 8.0 without the release notes. I have added a meta issue for that.

2020-07-14 09:57 UTC, ywelsch requested changes
This is missing the actual change to the setting.

2020-07-14 09:57 UTC, ywelsch commented on docs/reference/release-notes/7.9.asciidoc
> +  introduced with the `indexing_limits.memory.limit` setting. This setting
you mean `indexing_pressure.memory.limit` here?

2020-07-14 15:40 UTC, ywelsch commented on docs/reference/release-notes/7.9.asciidoc
> +  increased from 200 to 10000. Additional memory-oriented back pressure has been
Should we mention here that this new model now better supports indexing loads that consist of a few large bulks as well as many small bulks (from a larger number of clients).

2020-07-14 15:46 UTC, ywelsch approved these changes
LGTM

2020-07-14 16:35 UTC, merged

2020-07-21 22:58 UTC, tbrooks8 commented
This is currently labelled breaking as it changes a major default setting - the `WRITE` queue size from 200->10,000.