Use weekyear for WEEK_YEAR format name
elastic/elasticsearch pull request #60855
Opened 2020-08-07 00:54 UTC by russcam

Relates: #60707

With the deprecation of camel case names in #59555,
the format "weekyear" was deprecated in favour of
"week_year". This is inconsistent with other weekyear
formats however, that use "weekyear", for example

```java
WEEKYEAR_WEEK("weekyear_week"),
WEEKYEAR_WEEK_DAY("weekyear_week_day"),
```

This commit keeps "weekyear" as the snake case name
for the enum constant `FormatNames.WEEK_YEAR`. In addition,
the format for `DateFormatter WEEK_YEAR` is changed to
"weekyear".

If agreed, this PR would need to be backported to 7.9 because #59555 has been merged to 7.9.

2020-08-13 02:07 UTC, rjernst commented
I think it is already too late to make 7.9, and this change looks like it would be breaking? We need to properly deprecate usages of the snake_case version.

2020-08-17 07:36 UTC, pgomulka requested changes
maybe we could deprecate in 7.x and also add a new WEEKYEAR("weekyear") value?

2020-08-19 06:56 UTC, pgomulka commented
btw I also plan to review and remove some of these formats. I only briefly mentioned this here https://github.com/elastic/elasticsearch/issues/58719
`WEEKYEAR` is one of them to be removed in my book. I don't find it to be massively useful as it is easier to just use a 'YYYY' :)

2020-10-07 08:48 UTC, pgomulka commented
closing in favour of https://github.com/elastic/elasticsearch/pull/63384

2020-10-07 08:48 UTC, closed without merging