[7.9][DOCS] Replaces ml.node with node.roles:ml in ML settings.
elastic/elasticsearch pull request #61018
Opened 2020-08-12 10:35 UTC by szabosteve

## Overview

This PR applies the changes of the following PR to the 7.9 branch: [DOCS] Replaces ml.node with node.roles: [ ml ] in ML settings #61017 and adds a deprecation note to the text.

### Preview:

[Machine learning settings in Elasticsearch]()

2020-08-12 10:45 UTC, sophiec20 commented
While this file is being edited, please remove the tip `Dynamic settings take precedence over settings in the elasticsearch.yml file.` and incorporate it in the prior paragraph. The tip clashes with the important notice.

2020-08-12 10:54 UTC, sophiec20 requested changes

2020-08-12 10:54 UTC, sophiec20 commented on docs/reference/settings/ml-settings.asciidoc
> +Set `node.roles` to contain `ml` to identify the node as a _{ml} node_. +
suggest append ... `to identify the node as an ML node that is capable of running jobs.`

Also, can we explain..
If using the setting `node.roles` then all required roles must be explicitly set.
The absence of `node.roles` will have ml enabled by default. However setting `node.roles:[]` will configure a dedicated coordinating node.

2020-08-12 10:54 UTC, sophiec20 commented on docs/reference/settings/ml-settings.asciidoc
> +to run jobs, there must be at least one {ml} node in your cluster. +
Now explained in prev para. Suggest leaving as 

`If you want to run jobs, there must be at least one {ml} node in your cluster.`

2020-08-12 10:54 UTC, sophiec20 commented on docs/reference/settings/ml-settings.asciidoc
>  Set to `true` (default) to enable {ml} on the node.
Suggest append ... `to enable ML APIs on the node.`

2020-08-12 12:07 UTC, lcawl commented
I worry that this type of info is also in https://www.elastic.co/guide/en/machine-learning/master/setup.html#ml-nodes and https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-node.html.  Can we reduce the redundancy by putting all the info on one of those pages and linking to it from the others?

2020-08-12 12:31 UTC, szabosteve commented
++ reducing redundancy.
`node.roles: [ ml ]` still needs to be presented on this page though as it is a general ML setting. I added a link that points to the node documentation page for more info. I'll also review the Setup ML page.

2020-08-12 12:38 UTC, sophiec20 commented
++ reducing redundancy, however https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-node.html needs some serious clean up now the legacy settings can be removed.

2020-08-18 09:19 UTC, elasticmachine commented
Pinging @elastic/ml-core (:ml)

2020-08-18 09:19 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2020-08-18 13:26 UTC, merged