Fix condition in ILM step that cannot be met
elastic/elasticsearch pull request #62377
Opened 2020-09-15 12:22 UTC by cbuescher

ReplaceDataStreamBackingIndexStep#performAction seems to perform an equality
check on an original Index and the write indexes names, but because this
compares an Index instance to a String, the condition can never be met.
I added a test that triggers this code path but am not sure if this scenario can
really happen in practice or if the test is too constructed. Happy to change,
just wanted to raise this since I happend to run across the warning in the code.

2020-09-15 12:22 UTC, elasticmachine commented
Pinging @elastic/es-core-features (:Core/Features/ILM+SLM)

2020-09-15 19:38 UTC, dakrone approved these changes
LGTM, thanks for finding this, I think the test looks reasonable to me

2020-09-15 19:38 UTC, dakrone approved these changes
LGTM, thanks for finding this, I think the test looks reasonable to me

2020-09-15 19:39 UTC, dakrone commented
Huh I don't know why my review was left twice, but at least it worked?

2020-09-16 07:47 UTC, cbuescher commented
Thanks for the review @dakrone, do you think this should also go to 7.10?

2020-09-16 08:17 UTC, andreidan approved these changes
LGTM, thanks for fixing this Christoph.

Yes, this should go into 7.10 too

2020-09-16 11:17 UTC, andreidan requested changes
Just a small change request Christoph, thank you

2020-09-16 11:17 UTC, andreidan commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/ReplaceDataStreamBackingIndexStep.java
> +        if (dataStream.getWriteIndex().getIndex().getName().equals(originalIndex)) {
on second thought, to be consistent, I believe we should check indices equality (not just the name)
```suggestion
        if (dataStream.getWriteIndex().getIndex().equals(index)) {
```
We already do this in [another step](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CheckNotDataStreamWriteIndexStep.java#L64)

2020-09-16 14:56 UTC, cbuescher commented
@andreidan thanks, I pushed the change you suggested

2020-09-16 15:04 UTC, andreidan approved these changes
LGTM, thanks for fixing

2020-09-17 09:22 UTC, merged