Add index.routing.allocation.prefer._tier setting
elastic/elasticsearch pull request #62589
Opened 2020-09-17 22:43 UTC by dakrone

This commit adds the `index.routing.allocation.prefer._tier` setting to the
`DataTierAllocationDecider`. This special-purpose allocation setting lets a user specify a
preference-based list of tiers for an index to be assigned to. For example, if the setting were set
to:

```
"index.routing.allocation.prefer._tier": "data_hot,data_warm,data_content"
```

If the cluster contains any nodes with the `data_hot` role, the decider will only allow them to be
allocated on the `data_hot` node(s). If there are no `data_hot` nodes, but there are `data_warm` and
`data_content` nodes, then the index will be allowed to be allocated on `data_warm` nodes.

This allows us to specify an index's preference for tier(s) without causing the index to be
unassigned if no nodes of a preferred tier are available.

Subsequent work will change the ILM migration to make additional use of this setting.

Relates to #60848

2020-09-17 22:43 UTC, elasticmachine commented
Pinging @elastic/es-core-features (:Core/Features/Features)

2020-09-17 23:16 UTC, dakrone commented
Since this setting is not part of the existing preference group, we need to handle backwards compatibility. I think we have a couple of options here:

- Find a way to determine the node versions when the index is created, ignoring the setting for versions that don't support it.
- Collapsed the setting into one of the existing groups, so something like: `index.routing.allocation.include._tier_preference` or `index.routing.allocation.include_prefer_tier`

2020-09-18 13:44 UTC, andreidan requested changes
Thanks for working on this Lee. 

I've left a couple of rather minor suggestions. 

Can you please add some tests to show illustrate the include/exclude/require precedence over `preferred`?

2020-09-18 13:44 UTC, andreidan commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/cluster/routing/allocation/DataTierAllocationDecider.java
> +    private static Optional<String> preferredTier(String prioritizedTiers, RoutingAllocation allocation) {
would this be better named as `preferedAvailableTier` or `preferedPresentTier`?

2020-09-18 13:44 UTC, andreidan commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/cluster/routing/allocation/DataTierAllocationDecider.java
> +    private static boolean tierNodesPresent(String singleTier, RoutingAllocation allocation) {
should we make both these methods as default visible and add unit tests?

2020-09-18 16:39 UTC, dakrone commented
Thanks Andrei, I made the changes you suggested

2020-09-18 16:41 UTC, dakrone commented
@elasticmachine run elasticsearch-ci/packaging-sample-windows

2020-09-18 17:01 UTC, dakrone commented
@elasticmachine update branch

2020-09-18 18:27 UTC, dakrone commented
@elasticmachine test this please

2020-09-18 19:15 UTC, dakrone commented
@elasticmachine run elasticsearch-ci/2

2020-09-18 20:13 UTC, andreidan approved these changes
LGTM, thanks Lee

2020-09-18 20:49 UTC, merged