EQL: Replace [`] with ['] for identifiers
elastic/elasticsearch pull request #62638
Opened 2020-09-18 14:33 UTC by matriv

Since `'` is no longer supported for defining string literals,
we replace the backquote [`] with single quote ['] for the definition of
identifiers. The backquote is not a commonly used symbol in languages
and many times, especially with some fonts, can easily be mistaken and
cause confusion.

Closes: #62539

2020-09-18 14:38 UTC, rw-access commented on x-pack/plugin/eql/src/main/antlr/EqlBase.g4
> +    : '\'' (~'`')* '\''
We haven't agreed on this.

https://github.com/elastic/elasticsearch/pull/62539#pullrequestreview-491521943

2020-09-18 14:38 UTC, rw-access requested changes
Please don't merge until we reach an agreement.

2020-09-18 15:03 UTC, matriv commented
@rw-access I agree with you, since there is no way (grammar-wise) to keep both the error message for the single quotes around strings and their new usage around identifiers. Personally, I'd keep the next release with the prohibition of single quotes and introduce the new usage in the release after that.

2020-09-18 19:58 UTC, matriv commented
Let me add some more thoughts.

- The single quote `'` is currently used rarely to identify strings
- If a user issues a query with `'` around a string literal, e.g.: `process where a = 'foo'` then the foo will be parsed as a identifier and:
  - if `foo` is a valid identifier, an exception will be thrown since we cannot have comparisons with identifiers both to the left and to the right.
  - if `foo` is an invalid identifier, an exception will be thrown stating this.

This doesn't seem as a dangerous behaviour since it doesn't lead to a correct query with wrong behaviour.

On the other hand, for me it seems quite inconvenient for the user to receive a message mentioning a wrong identifier for something that until now it was considered a string literal.

To conclude, if we think that the percentage of users/queries affected is rather low, and since ES-EQL is experimental, doesn't seem so impactful. Imho though, I have a preference over the more clear 2 step approach (1. error message for single quotes around string, 2. replacement of backquotes with single quote for identifiers).

2020-09-21 10:35 UTC, matriv commented
Based on @astefan 's comment here: https://github.com/elastic/elasticsearch/issues/62650#issuecomment-695995357
I'd like to conclude that if we lock ourselves in the situation that we have to wait replacing the backquote with the single quote for identifiers until next major release, I'd rather proceed with this breaking change now, since it's safe enough (no wrong results for deprecated syntax).

2020-09-28 08:39 UTC, costin commented
This PR can be closed without merging (see https://github.com/elastic/elasticsearch/issues/62663#issuecomment-699866306).
The issue of quoting an identifier containing the quoting character needs to be verified and addressed.

2020-09-28 08:55 UTC, matriv commented
Closing this, see comments above and on the relevant issue: #62539

2020-09-28 08:55 UTC, closed without merging