add country_name to the default properties of geoip ingest processor
elastic/elasticsearch pull request #62915
Opened 2020-09-26 04:24 UTC by gaobinlong

Closes #61523.

The main changes are:
1. Add `coutry_name` to the default properties of geoip processor.
2. Add a yaml test for the code change.
3. Update the geoip processor doc.

2020-09-29 11:50 UTC, danhermann commented
@elasticmachine ok to test

2020-09-29 13:15 UTC, elasticmachine commented
Pinging @elastic/es-core-features (:Core/Features/Ingest)

2020-09-29 15:18 UTC, danhermann requested changes
@gaobinlong, thanks for adding this. I think the source of the current test failures is that `country_name` needs to be added to the results of the query in the `geoip.asciidoc` file around line 280. If you can add that, I think we can get this merged.

2020-09-30 09:14 UTC, gaobinlong commented
@danhermann, thanks for your review, I have done that and all checks have paased yet.

2020-09-30 19:06 UTC, merged