SQL: Allow skip of bwc tests on `check` task
elastic/elasticsearch pull request #62936
Opened 2020-09-28 09:10 UTC by matriv

Bwc tests can consume much time to build and to run so it's nice to be
able to skip them when running the `check` task on the SQL module.

Introduce a project property `skipBwc` so one can use:
```
./gradlew -p x-pack/plugin/sql check -PskipBwc
```
to skip them.

2020-09-28 09:10 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (:Core/Infra/Build)

2020-09-28 09:10 UTC, elasticmachine commented
Pinging @elastic/es-ql (:Query Languages/SQL)

2020-09-28 11:02 UTC, costin approved these changes
LGTM

2020-09-28 12:12 UTC, astefan approved these changes
LGTM

2020-09-28 21:19 UTC, rjernst commented
I don't think we should be added such properties. Bwc tests on check are already limited to snapshot versions, so from master, this is only 7.x that is tested against. If you want to run a specific test of tests, for example unit tests or rest tests, then use the appropriate tasks directly. Skipping creation of tasks is not what we want. /cc @mark-vieira

2020-09-28 21:46 UTC, mark-vieira commented
I agree with Ryan. These magic flags are not very discoverable. I'd prefer if you want some kind of "shortcut" for the sql project you should add a specific task for this that depends on all tests except for the BWC ones.

2020-09-30 15:18 UTC, mark-vieira requested changes

2020-09-30 15:18 UTC, mark-vieira commented on x-pack/plugin/sql/build.gradle
> +  dependsOn 'check'
This wasn't exactly what I was thinking. What I was saying is that `checkNoBwc` should depend on `test`, `integTest`, `yamlRestTest`, etc. That way it runs those w/o running all the BWC stuff.

2020-09-30 17:07 UTC, mark-vieira approved these changes
LGTM

2020-09-30 17:11 UTC, merged