Adding script support for version parts
elastic/elasticsearch pull request #62953
Opened 2020-09-28 12:46 UTC by cbuescher

Spin off of https://github.com/elastic/elasticsearch/pull/59773 that factors out adding support to access special information about a version field value via scripts. 
This is only one potential solution, so mainly opening this for discussion.

2020-09-30 10:47 UTC, mayya-sharipova commented
Thanks @cbuescher.  This change LGTM! 
I guess the main question if @jimczi is ok with it.

2020-09-30 14:26 UTC, cbuescher commented
> Also you mentioned that it is one potential solution. What's another? Is it indexing these fields explicitly?

That would be one other option, also using runtime fields for this comes into mind, which would potentially be slower but would allow the same kind of operations for versions currently stored in ' keyword' fields I think. I think this can be discussed in #62952 before proceeding but thanks for the review.

2020-10-01 07:14 UTC, jimczi requested changes
I left one comment regarding where and how we could apply these functions.

2020-10-01 07:14 UTC, jimczi commented on x-pack/plugin/mapper-version/src/main/java/org/elasticsearch/xpack/versionfield/VersionScriptDocValues.java
> +    public boolean isValid() {
`VersionScriptDocValues` is a list so I don't think this is the right level to apply the functions. We accept multiple values so there should be a way to apply these functions to the first, second or last entry in the list too ?
These functions could also be applied to any string (keyword family) field ? A static function like`semverIsRelease(String)` that would work on the decoded version could also be helpful imo, we don't need to put these functions under the new script values.

2024-05-07 08:49 UTC, cbuescher commented
This PR is hopelessly outdated, so closing it.

2024-05-07 08:49 UTC, closed without merging