Rework parent-join to not require access to DocumentMapper
elastic/elasticsearch pull request #63738
Opened 2020-10-15 12:49 UTC by romseygeek

Parent joins work using a cluster of field mappers: the join field itself;
a set of subfields that allow multiple relationships between parents and
children to be defined; and a metadata field that acts to only allow a 
single join field per index to be defined.  The various queries and
aggregations that use this infrastructure retrieve the join field mapper
via a static method and then build themselves by pulling individual
relationship mappers from this main mapper.

Using mappers rather than MappedFieldTypes means that we need to
expose DocumentMapper at search time, which is something we are
trying to avoid.  This commit refactors things so that the join relations
are encapsulated in a Joiner object, which lives instead on the 
MappedFieldType associated with the metadata join field.  Rather than
using the ParentJoinFieldMapper and connected ParentIdFieldMappers,
we can now build queries and aggregations using this Joiner object,
retrieved via the QueryShardContext or AggregationContext using
a static helper method on Joiner itself.  In addition, the mappers are
refactored to parametrized form, and the Builders for the metadata and
relation mappers are removed as they are always constructed directly
by the join field mapper, and never via parsable user input.

2020-10-15 12:50 UTC, elasticmachine commented
Pinging @elastic/es-search (:Search/Mapping)

2020-10-15 13:15 UTC, nik9000 commented
> Rework parent-join to not require access to DocumentMapper

hell yeah!

2020-10-15 13:23 UTC, javanna reviewed
This is a great change! Would it be possible to split it into smaller PRs? For instance one could be to move the mappers to parametrized field mapper, another one to replace the lookup mechanism so that looking up mappers is no longer required. Or are these two tied to each other?

2020-10-15 14:00 UTC, romseygeek commented
I can probably split the parametrization out into a separate PR, although encapsulating the connection logic into the Relations class is a major part of it - I'll give it a go.

2020-10-16 08:37 UTC, javanna requested changes
I left some minor comments, looks great though, thanks for untangling this, I would not have known where to start ;)

2020-10-16 08:37 UTC, javanna commented on modules/parent-join/src/main/java/org/elasticsearch/join/mapper/Joiner.java
> +    public Query getChildrenFilter(String parentType) {
nit: is there a reason why this method starts with get while the two above don't?

2020-10-16 08:37 UTC, javanna commented on modules/parent-join/src/main/java/org/elasticsearch/join/mapper/Joiner.java
> +    public static Joiner getJoiner(Predicate<String> isMapped, Function<String, MappedFieldType> getFieldType) {
shall we make this package private?

2020-10-16 08:37 UTC, javanna commented on modules/parent-join/src/main/java/org/elasticsearch/join/mapper/Joiner.java
> +    public Joiner(String joinField, List<Relations> relations) {
could this be package private?

2020-10-16 08:37 UTC, javanna commented on modules/parent-join/src/main/java/org/elasticsearch/join/mapper/Joiner.java
> +public class Joiner {
make this final?

2020-10-16 08:37 UTC, javanna commented on modules/parent-join/src/main/java/org/elasticsearch/join/mapper/Relations.java
> +    static List<Relations> parse(Object node) {
parse looks unused?

2020-10-16 08:37 UTC, javanna commented on server/src/main/java/org/elasticsearch/search/aggregations/support/AggregationContext.java
> +        public boolean isFieldMapped(String field) {
you may also remove getMapper from this class , one less usage of getMapperService ;)

2020-10-19 09:51 UTC, javanna approved these changes
LGTM

2020-10-19 10:28 UTC, romseygeek commented
@elasticmachine update branch

2020-10-19 11:17 UTC, merged