Optimize cluster block clear logic.
elastic/elasticsearch pull request #64113
Opened 2020-10-25 14:33 UTC by howardhuanghua

Currently if we have follow cluster settings(we have set both persistent and transient before):
```
GET_cluster/settings?pretty
{
  "persistent" : {
    "cluster" : {
      "blocks" : {
        "read_only_allow_delete" : "true"
      }
    }
  },
  "transient" : {
    "cluster" : {
      "blocks" : {
        "read_only_allow_delete" : "true"
      }
    }
  }
}
``` 

Then we cannot remove them together:
```
PUT _cluster/settings?pretty
{
  "persistent" : {
    "cluster.blocks.read_only_allow_delete": null
  },
  "transient" : {
    "cluster.blocks.read_only_allow_delete": null
  }
}'

Response:
{
  "error" : {
    "root_cause" : [
      {
        "type" : "cluster_block_exception",
        "reason" : "blocked by: [FORBIDDEN/13/cluster read-only / allow delete (api)];"
      }
    ],
    "type" : "cluster_block_exception",
    "reason" : "blocked by: [FORBIDDEN/13/cluster read-only / allow delete (api)];"
  },
  "status" : 403
}

```

Even we can remove them one by one, but I think it's reasonable to allow user to remove them together. This PR supports to remove them one by one or together.

2020-10-29 08:37 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (:Core/Infra/Settings)

2020-10-31 18:30 UTC, rjernst commented
@DaveCTurner Can you review please?

2020-11-02 08:55 UTC, DaveCTurner commented
Does this address https://github.com/elastic/elasticsearch/issues/62920 @howardhuanghua? It's the right area of code to do so. If it does, could you add a test for that issue too? If it doesn't, would you do so?

2020-11-02 09:02 UTC, howardhuanghua commented
Hi @DaveCTurner, this is another seperated issue, it cannot fix https://github.com/elastic/elasticsearch/issues/62920 driectly.
Before fixing https://github.com/elastic/elasticsearch/issues/62920, I would like to fix this individual issue first.
I have also adjusted test case `testClusterUpdateSettingsWithBlocks` L323 in ClusterSettingsIT.java to support **removing persistent and transient cluster block settings together**. Without this fix, we could not set them together.

2020-11-02 09:39 UTC, DaveCTurner commented
I would rather you addressed #62920 as well here. There is little value in us reviewing a PR which addresses a very minor issue and will be superseded straight away by a fix to a much more serious bug.

2020-11-02 10:05 UTC, howardhuanghua commented
OK, I will update the PR to fix them together.

2020-11-08 08:05 UTC, howardhuanghua commented
Hi @DaveCTurner , I have updated the PR. Here are the related logics:

If cluster has read only blocks and archived settings:
1. Cannot remove read only blocks due to archived settings.
2. Cannot update any cluster settings due to read only blocks.
3. Can only remove archived settings.

That means we cannot do any changes before removing archived settings. And if cluster is read only, except removing archived settings, we could do nothing include removing read only blocks.

Now we also support removing transient and persistent cluster blocks together.

2020-11-17 06:10 UTC, howardhuanghua commented
Hi @DaveCTurner would you please help to check the updated logic again? Thanks.

2020-12-12 13:32 UTC, howardhuanghua commented
Merged master.

2020-12-15 10:17 UTC, DaveCTurner commented
@elasticmachine ok to test

2020-12-15 10:38 UTC, DaveCTurner reviewed
Permitting multiple settings in updates does open up quite a lot of complexity. For instance, with the suggested implementation here I think we would permit removing archived settings without removing the metadata block. You could even be adding a metadata block at the same time as removing those settings.

However, I don't think it's worth resolving the provided settings updates against the current cluster state here just for validation. Let's skip calling `globalBlockedException` only if all of the following are true:

- at least one of `cluster.blocks.read_only` or `cluster.blocks.read_only_allow_delete` is being cleared (set to `null` or `false`)
- neither `cluster.blocks.read_only` nor `cluster.blocks.read_only_allow_delete` is being set to `true`
- the only other settings in this update are archived ones being set to `null`.

I see that it's a bit of a pain to do this for both the transient and persistent settings at the same time, but could you find a way to do these checks without duplicating the entire loop and all its logic? Extract a method or two perhaps.

2020-12-15 10:39 UTC, DaveCTurner commented
@elasticmachine update branch

2020-12-15 10:39 UTC, elasticmachine commented
user doesn't have permission to update head repository

2020-12-15 10:40 UTC, DaveCTurner commented
@howardhuanghua you'll need to tick the box to let maintainers push code to your branch, or else look after merging latest `master` yourself. I've enabled CI on this branch anyway so it'll run the full test suite each time you push changes.

2020-12-15 16:41 UTC, howardhuanghua commented
Hi @DaveCTurner I have updated the latest master. And I will check your suggestions and remove duplicated loop. Thanks.

2020-12-27 15:25 UTC, howardhuanghua commented
Hi @DaveCTurner , I have updated the skip calling `globalBlockedException` logic based on your suggestion. I used a map to group by `transent` and `persistent` clear block and archived settings. One condition different is that we need to allow user to remove cluster blocks if cluster doesn't have archived settings.

2021-01-04 10:01 UTC, DaveCTurner requested changes
Thanks @howardhuanghua, this looks closer. I left some more comments.

2021-01-05 03:57 UTC, howardhuanghua commented
Hi @DaveCTurner , I have updated the change based on your suggestions. Thank you.

2021-01-20 12:31 UTC, howardhuanghua commented
Hi @DaveCTurner , would you please help to review the changes again? Thanks a lot.

2021-01-26 16:21 UTC, DaveCTurner requested changes
I left a few nits but this is looking good. I also pushed a branch with my suggested changes: https://github.com/TencentCloudES/elasticsearch/compare/remove_block...DaveCTurner:2021-01-26-remove_block-reviews

2021-01-26 16:21 UTC, DaveCTurner commented on server/src/internalClusterTest/java/org/elasticsearch/cluster/settings/ClusterSettingsIT.java
> +                    if (readOnly) {
I think here we should set these settings randomly, not just setting the one we care about to `true`.

2021-01-26 16:21 UTC, DaveCTurner commented on server/src/internalClusterTest/java/org/elasticsearch/cluster/settings/ClusterSettingsIT.java
> +            assertTrue(Metadata.SETTING_READ_ONLY_SETTING.get(state.getMetadata().transientSettings()));
We can assert the persistent settings here too?

2021-01-26 16:21 UTC, DaveCTurner commented on server/src/internalClusterTest/java/org/elasticsearch/cluster/settings/ClusterSettingsIT.java
> +            assertTrue(Metadata.SETTING_READ_ONLY_ALLOW_DELETE_SETTING.get(state.getMetadata().transientSettings()));
We can assert the persistent settings here too?

2021-01-26 16:21 UTC, DaveCTurner commented on server/src/internalClusterTest/java/org/elasticsearch/cluster/settings/ClusterSettingsIT.java
> +                        builder.put(Metadata.SETTING_READ_ONLY_SETTING.getKey(), "false");
We could also set this to `null`.

2021-01-26 16:21 UTC, DaveCTurner commented on server/src/internalClusterTest/java/org/elasticsearch/cluster/settings/ClusterSettingsIT.java
> +                        builder.put(Metadata.SETTING_READ_ONLY_ALLOW_DELETE_SETTING.getKey(), "false");
We could also set this to `null`.

2021-01-26 16:21 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/action/admin/cluster/settings/TransportClusterUpdateSettingsAction.java
> +                                                         final Map<String, String> clearedBlockAndArchivedSettings) {
This could just be a `Set<String>`, we don't care about the values.

2021-01-26 16:21 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/action/admin/cluster/settings/TransportClusterUpdateSettingsAction.java
> +                if ("true".equals(value)) {
I don't think we should duplicate the parsing of boolean settings here. Suggest using `Metadata.SETTING_READ_ONLY_ALLOW_DELETE_SETTING.get(settings)` etc.

2021-01-26 17:17 UTC, howardhuanghua commented
Hi @DaveCTurner , thanks for your patient help. I have reviewed and merged your suggested changes. Also successfuly run several times of `testRemoveArchiveSettingsWithBlocks` test case in my local env.

2021-01-26 17:21 UTC, DaveCTurner approved these changes
LGTM

2021-01-26 17:21 UTC, DaveCTurner commented
Thanks @howardhuanghua, I'll get this merged shortly although probably not today.

2021-01-27 07:11 UTC, merged