Enable geo_distance and geo_bounding_box queries on geo_shape field type
elastic/elasticsearch pull request #64224
Opened 2020-10-27 14:06 UTC by iverase

This commit enables geo_distance and geo_bounding_box queries on geo_shape field type. In addition it enables those queries over geo_point runtime fields as well.

closes #54628

2020-10-27 14:06 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo (:Analytics/Geo)

2020-10-27 20:47 UTC, talevy approved these changes
Overall looks great! I read the docs, the content looks good. There are some English things that @jrodewig could comment on maybe?

2020-10-27 20:47 UTC, talevy commented on docs/reference/query-dsl/geo-bounding-box-query.asciidoc
> +//./gradlew ':docs:integTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/query-dsl/geo-bounding-box-query/*}"
whoa, I didn't know this is possible

2020-10-28 14:17 UTC, jrodewig requested changes
This looks good overall. However, there are some grammar issues that need to be fixed before a merge. It also looks like a few of the example snippets target the wrong indices.

2020-10-28 14:17 UTC, jrodewig commented on docs/reference/query-dsl/geo-distance-query.asciidoc
> +Or it can be executed in both indexes at the same time:
Current text is fine. Feel free to ignore if wanted.
```suggestion
To match both `geo_point` and `geo_shape` values, search both indices:
```

2020-10-28 15:38 UTC, iverase commented
Thanks you @jrodewig, I added your suggestions!

2020-10-28 15:59 UTC, jrodewig approved these changes
LGTM. Thanks @iverase!

2020-10-29 06:30 UTC, merged