Add info on how to disable cleaner service
elastic/elasticsearch pull request #64655
Opened 2020-11-05 14:51 UTC by jguay

Add information on how to disable cleaner service when using dedicated monitoring cluster

2020-11-05 14:52 UTC, elasticmachine commented
Pinging @elastic/es-docs (>docs)

2020-11-18 13:43 UTC, elasticmachine commented
Pinging @elastic/es-core-features (Team:Core/Features)

2020-12-07 23:23 UTC, jakelandis requested changes, later dismissed
change looks good (sans one line). thanks for documenting this!

2020-12-07 23:23 UTC, jakelandis commented on docs/reference/monitoring/local-export.asciidoc
> +xpack.monitoring.collection.enabled: false
The following is necessary to disable the cleaner: (setting this to false would also disable all monitoring data collection)
```
xpack.monitoring.collection.enabled: false
```

2020-12-21 17:47 UTC, jrodewig approved these changes
LGTM. I made the changes @jakelandis requested and made some minor wording changes. Thanks @jguay!

2020-12-21 17:52 UTC, merged