[7.x] Implement aggregations on aggregate metric fields
elastic/elasticsearch pull request #64939
Opened 2020-11-11 15:31 UTC by csoulios

Backports 7.x to #56745

>In the process of developing a new implementation for the Elasticsearch Rollups functionality we came up with the concept of the aggregate metric field type.
> 
>The aggregate_metric_double field type can store the results of aggregations (currently min, max, sum, value_count and avg are supported - more to come).
> 
>This field allows us to run (min, max, sum, value_count, avg) aggregations on the container field and the field will return the correct metric depending on the aggregation that is computed.

2020-11-11 15:34 UTC, csoulios commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/aggregatemetric/AggregateMetricFeatureSetUsage.java
> +        return Version.V_7_11_0;
@polyfractal I guess after this PR is merged, we should change the minimal supported version in master branch from `V_8_0_0` to `V_7_11_0`. Right?

2020-11-11 18:57 UTC, csoulios commented
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

2020-11-11 22:06 UTC, polyfractal requested changes
Mainly looked at the FeatureSet/Usage stuff, left a comment about transport client mode stuff but otherwise looks good to me.

Only other major thing I think are version skips in the YAML tests... I think we need to pull those down to 7.11 right?

2020-11-12 10:13 UTC, csoulios commented on x-pack/plugin/src/test/resources/rest-api-spec/test/aggregate-metrics/10_basic.yml
> +      version: " - 7.99.99"
Good catch. I totally missed that. Thanks!

2020-11-12 14:29 UTC, polyfractal commented on x-pack/plugin/src/test/resources/rest-api-spec/test/aggregate-metrics/10_basic.yml
> +      version: " - 7.99.99"
I only remember to check because I've forgotten do this many times :)

2020-11-12 14:30 UTC, polyfractal approved these changes
Backport LGTM!

2020-11-12 14:32 UTC, merged