Doc DLS FLS do apply when queries refer foreign indices
elastic/elasticsearch pull request #65793
Opened 2020-12-02 23:27 UTC by albertzaharovits

The statement that DLS/FLS does not work/apply when using queries that refer to remote indices (terms lookup, geo shape and percolate) does not apply anymore.

2020-12-02 23:27 UTC, elasticmachine commented
Pinging @elastic/es-security (Team:Security)

2020-12-02 23:27 UTC, elasticmachine commented
Pinging @elastic/es-docs (Team:Docs)

2020-12-02 23:47 UTC, tvernum commented
That comment in the docs is attempting to say something different.
It means that you can't have a role query that does a terms lookup, which is still true.

2020-12-03 00:13 UTC, ywangd requested changes
@tvernum is right. These limitations still [apply](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/support/DLSRoleQueryValidator.java#L143-L159). IIUC, one main technical reason for these limitations is caching as it is difficult to invalidate the DLS cache when stats on another index changes.

2020-12-03 00:15 UTC, tvernum commented
Actually the main technical reason is recursion. If a DLS query performs an external lookup on an index that has DLS applied then you can end up in an infinitely recursive application of the DLS query.

2020-12-03 08:03 UTC, albertzaharovits commented
You're right. Funny how I was biased reading that while working on something related https://github.com/elastic/elasticsearch/pull/65801 .

2020-12-03 08:03 UTC, closed without merging