[ILM] check if delete phase has actions (#65847)
elastic/elasticsearch pull request #66664
Opened 2020-12-19 17:33 UTC by dlbas

Fixes #65847

Added validation for the Delete phase with empty actions.

2020-12-21 10:54 UTC, astefan commented
@dlbas thank you for your contribution, but it seem you didn't sign the contributor agreement.

2020-12-21 10:55 UTC, elasticmachine commented
Pinging @elastic/es-core-features (Team:Core/Features)

2020-12-21 11:12 UTC, dlbas commented
@astefan sorry, I believe I did. Is there a way to recheck my CLA signature?

2020-12-21 11:13 UTC, dlbas commented
seems like ok now :)

2021-01-04 12:23 UTC, andreidan commented
@elasticmachine ok to test

2021-01-05 10:42 UTC, andreidan requested changes
Thanks for fixing this issue @dlbas 

This looks great, I've left a super minor suggestion related to the error message.

2021-01-05 10:42 UTC, andreidan commented on client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/LifecyclePolicy.java
> +               throw new IllegalArgumentException("phase [" + phase.getName() + "] must contain actions");
In order to keep the messaging around phase and actions consistent with the below validation, can you please change the message to "must define actions"?

 ```suggestion
               throw new IllegalArgumentException("phase [" + phase.getName() + "] must define actions");
```

2021-01-05 10:42 UTC, andreidan commented on client/rest-high-level/src/test/java/org/elasticsearch/client/ilm/LifecyclePolicyTests.java
> +        assertThat(e.getMessage(), equalTo("phase [" + delete.getName() + "] must contain actions"));
```suggestion
        assertThat(e.getMessage(), equalTo("phase [" + delete.getName() + "] must define actions"));
```

2021-01-06 10:18 UTC, andreidan approved these changes
LGTM, thanks for fixing this @dlbas

2021-01-06 10:19 UTC, merged