Retry point in time on other copy when possible
elastic/elasticsearch pull request #66713
Opened 2020-12-21 19:08 UTC by dnhatn

2021-01-06 17:46 UTC, elasticmachine commented
Pinging @elastic/es-search (Team:Search)

2021-01-06 17:47 UTC, dnhatn commented on server/src/main/java/org/elasticsearch/search/internal/ShardSearchContextId.java
>      public ShardSearchContextId(String sessionId, long id) {
I will remove this constructor in a follow-up.

2021-01-07 14:00 UTC, jimczi requested changes
I like the approach.
I left one comment regarding the deletion of the PIT.
We should lookup all active replicas when removing the contexts.
I am also concerned by the fact that we always keep the latest failure for each shard. 
Now that we add replicas in the context, we should ensure that we keep the original exception when we retry on a replica. Otherwise any exception could be hidden by the search context missing exception that the other replicas would send. Does that makes sense ?

2021-01-07 15:38 UTC, dnhatn commented
@jimczi Thanks for reviewing.

> We should lookup all active replicas when removing the contexts.

I think we handle this in https://github.com/elastic/elasticsearch/pull/66713/files#diff-5198131d51dc75f4b8b82d7cc9a3960b0955bbd50c7b6573bdc5a227f02d12cfR213 and https://github.com/elastic/elasticsearch/pull/66713/files#diff-c547f7891956be1109085c486b76f18044af4b96551b46ed3aba5cf82c044158R103

> I am also concerned by the fact that we always keep the latest failure for each shard.
Now that we add replicas in the context, we should ensure that we keep the original exception when we retry on a replica. Otherwise any exception could be hidden by the search context missing exception that the other replicas would send.

I think it's implemented here:
https://github.com/elastic/elasticsearch/pull/66713/files#diff-96633e6da7d4c7696cf8d66d892f86fab7e407f42b45bb9d1df9b6b92b1270d5R484

2021-01-07 15:53 UTC, jimczi commented
> I think we handle this in https://github.com/elastic/elasticsearch/pull/66713/files#diff-5198131d51dc75f4b8b82d7cc9a3960b0955bbd50c7b6573bdc5a227f02d12cfR213 and https://github.com/elastic/elasticsearch/pull/66713/files#diff-c547f7891956be1109085c486b76f18044af4b96551b46ed3aba5cf82c044158R103

Yep sorry I should have been more precise. If we delete the extra context after each search, we loose the protection that we set when the context is opened on the shard. Maybe that's not important for searchable snapshots so the workaround that you implemented is ok but I am not sure :(.

> I think it's implemented here:
https://github.com/elastic/elasticsearch/pull/66713/files#diff-96633e6da7d4c7696cf8d66d892f86fab7e407f42b45bb9d1df9b6b92b1270d5R484

Nice, sorry I missed it.

2021-01-07 18:52 UTC, jimczi approved these changes
I've been thinking more about the options we have to take replicas into account and I think your solution is simpler and less intrusive.  We can revisit in the future but that sounds enough for now especially knowing that it's a solution for frozen indices and searchable snapshots only. So +1 to merge this solution, sorry for the back and forth.

2021-01-07 22:18 UTC, dnhatn commented
I indeed explored two options before choosing the current approach. I found the other option more compelling than the current one as it truly replaces unavailable contexts with the new ones. However, it's not easy to clean up those new contexts properly. I will merge this PR as is, and we can revisit this as you said. Thank you for the feedback.

2021-01-07 22:18 UTC, dnhatn commented
@elasticmachine update branch

2021-01-07 23:23 UTC, dnhatn commented
@elasticmachine update branch

2021-01-08 02:24 UTC, dnhatn commented
run elasticsearch-ci/2

2021-01-09 14:43 UTC, merged