fix   issue-#53129
elastic/elasticsearch pull request #67209
Opened 2021-01-08 11:11 UTC by shay123g

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2021-01-26 18:51 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (Team:Core/Infra)

2021-01-26 18:52 UTC, jtibshirani commented
@shay123g sorry for the slow response, this PR slipped through the cracks. I've now alerted the relevant team.

2021-01-26 19:34 UTC, jdconrad requested changes
@shay123g Apologies for missing this. It looks like you haven't signed the CLA from my end. I won't be able to merge anything until that is done.

As far as the change goes, this doesn't cover the actual issue. The issue is that callArgs[0] is null because an attempt to access a `def` type variable that is null is made at runtime. It would be great if we could give additional information about this instead of just an NPE in a cryptic stack trace. Ideally, the error would describe the situation as an attempt to access a `def` type variable that is null.

Please let me know if you still have interest in fixing this.  Thank you!

2021-02-03 00:16 UTC, mark-vieira commented
@elasticmachine update branch

2021-02-08 12:13 UTC, closed without merging