SQL: Improve test robustness against timezone offset changes
elastic/elasticsearch pull request #68064
Opened 2021-01-27 15:23 UTC by palesz

The offset of a timezone is not fixed, can change over time. Countries
can decide to move between offsets/timezones over time. Different
JDK versions have different versions of the timezone -> offset
mapping leading to same instant represented differently in outputs
and errors messages.

This commit improves the error message validation in
the `JdbcResultSetIT` testcases by not asserting the string
representation of the dates in the error message, rather asserting if
they represent the expected instant (epochMillis).

Fixes #68018

2021-01-27 15:23 UTC, elasticmachine commented
Pinging @elastic/es-ql (Team:QL)

2021-01-27 16:04 UTC, matriv approved these changes
LGTM. Cool approach!

Maybe you could extract the pattern compilation to a method where you pass the target data type needed for the message.

2021-01-27 16:04 UTC, matriv commented on x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/ResultSetTestCase.java
> +    private void assertMessageWithInstant(String actualMessage, Pattern expectedPattern, long epochMillis) {
maybe `assertErrorMessageForDateTimeValues` ?

2021-01-27 16:04 UTC, matriv commented on x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/ResultSetTestCase.java
> +
minor: revert whitespaces

2021-01-27 18:34 UTC, astefan approved these changes
LGTM
Personal opinion: I think it's too much to use a regular expression matcher to basically check equality of two parts of the same string and to extract whatever sits between them. But it gets the job done.

2021-01-27 20:15 UTC, bpintea approved these changes
LGTM

2021-01-28 13:13 UTC, costin requested changes
Nice. I would move though the message creation inside the assertion method and clean it up a bit:
```
assertExceptionForInstant(Exception ex, long epoch, Class<?> expectedType)
```

2021-01-28 19:48 UTC, matriv approved these changes
LGTM! thx!

2021-01-28 20:54 UTC, costin approved these changes
LGTM

2021-01-28 23:16 UTC, merged