Add forum URL and update first steps using ES and Gradle
elastic/elasticsearch pull request #68261
Opened 2021-01-31 23:59 UTC by ayusopatricia

Add forum URL so new contributors can refer to it, and update first steps using ES and Gradle in CONTRIBUTING documentation.

2021-02-01 10:34 UTC, henningandersen requested changes
@ayusopatricia thanks for improving this. I added a few comments, in particular we like to keep this file to 80 characters line width and at least additions should adhere to that.

2021-02-01 10:34 UTC, henningandersen commented on CONTRIBUTING.md
> +writing its log above Gradle's status message. We log a lot of stuff on startup, when you see some lines like these ones (when the console stops scrolling):
Can we limit this to 80 characters line width?

2021-02-01 10:34 UTC, henningandersen commented on CONTRIBUTING.md
> -    [2020-05-29T14:50:35,169][INFO ][o.e.n.Node               ] [runTask-0] started
I see that we end with the security line now. It is a bit arbitrary and somewhat likely to change. Therefore I would like to also keep this line. I propose to keep both lines, with `...` between them to signal that other stuff goes in between.

2021-02-01 10:34 UTC, henningandersen commented on CONTRIBUTING.md
> +Open another terminal window to check if ES is ready to receive requests by running this `curl` command in :
Also limit this to 80 characters.

2021-02-01 10:34 UTC, henningandersen commented on CONTRIBUTING.md
> +> Note: If you need assistance or question, go to our [discussion forum](https://discuss.elastic.co/).
```suggestion
> Note: If you need assistance or have questions, visit our
[discussion forum](https://discuss.elastic.co/).
```

2021-02-03 00:15 UTC, mark-vieira commented
@elasticmachine update branch

2021-04-29 13:01 UTC, elasticmachine commented
Pinging @elastic/es-delivery (Team:Delivery)

2021-04-29 13:02 UTC, elasticsearchmachine commented
<!-- Automatically generated by [elasticsearchmachine], action: [checking labels] -->
<!-- This comment will be automatically removed when the labelling issues are resolved -->
Hello @ayusopatricia, there are labelling issues with this PR that need to be fixed:

 * At least one version label is required
 * At least one change type label (starting with '>') is required

2022-07-18 14:57 UTC, pugnascotia commented
This PR has had no updates for over a year, so I hope you don't mind if I close it.

2022-07-18 14:57 UTC, closed without merging