Separate task output directories for YAML REST testing
elastic/elasticsearch pull request #68943
Opened 2021-02-11 23:00 UTC by mark-vieira

The existing implementation for YAML REST testing aggregates specification files and test files from several locations and copies them to the target test source set resources output directory to be available on the test runtime classpath. This means we have multiple tasks all copying files to the same output destination which causes some issues:

1. Gradle really doesn't like this as it makes it really difficult to track task input/outputs properly. In fact it's likely in future version this will be outright prohibited and cause build failures.
2. It becomes impossible to clean stale outputs as we cannot rely on simply deleting the target output directory before copying as there might be content there from other tasks.
3. As a consequence of (2) you can see strange behavior when doing things like branch switching as tests from the previous branch will be orphaned and fail.

This PR refactors the rest resources and yaml testing plugins to use individual output directories for all tasks. Now specs and tests defined in the project itself and those copied from elsewhere not live in separate output directories under the `build/` directory. This new behavior also required some changes to our YAML testing framework to support locating specs and tests from multiple directories on the classpath.

2021-02-11 23:00 UTC, elasticmachine commented
Pinging @elastic/es-delivery (Team:Delivery)

2021-02-16 17:01 UTC, mark-vieira commented
@elasticmachine update branch

2021-02-16 17:43 UTC, jakelandis requested changes
Hmm.. I looked at the recent [test failure](https://gradle-enterprise.elastic.co/s/4mvfu5vb34q6k) on this PR and think we need to change x-pack/plugin/build.gradle to no longer copy itself...it now ends up with 2 sets of specs and it (correctly) complains about that [1]:

from
```
restResources {
  restApi {
    includeCore '*'
    includeXpack '*'
  }
}
```
to:
```
restResources {
  restApi {
    includeCore '*'
  }
}
```

[1]
```
org.elasticsearch.xpack.test.rest.XPackRestIT > test {p0=runtime_fields/90_loops/loose loop - aggs} FAILED
    java.lang.IllegalArgumentException: cannot register api [ml.get_data_frame_analytics] found in [/dev/shm/elastic+elasticsearch+pull-request-2/x-pack/plugin/build/resources/test/rest-api-spec/api/ml.get_data_frame_analytics.json]. api with same name was already found in [/dev/shm/elastic+elasticsearch+pull-request-2/x-pack/plugin/build/restResources/yamlSpecs/rest-api-spec/api/ml.get_data_frame_analytics.json]
```

before this change, i think it was just doing an extra copy and overwriting itself...However, testing locally, that change does not seem to completly fix the issue and there are still a few rouge x-pack specs in under restResources/yamlSpecs dir.

2021-02-16 17:59 UTC, jakelandis commented
Weird ... so if comment out `includeXpack 'eql', 'indices'` in  x-pack/plugin/eql/qa/correctness/build.gradle (along with the above change to not double copy) `:x-pack:plugin:yamlRestTest` works fine. For some reason that config is influencing the copy spec behavior for `:x-pack:plugin` I suspect it has something to do with the odd configuration of using the restResources config without a yaml test source set ? (this is about the time I would ping you to ask what is going on !?)

2021-02-16 18:08 UTC, mark-vieira commented on buildSrc/src/integTest/groovy/org/elasticsearch/gradle/YamlRestTestPluginFuncTest.groovy
> +                   println sourceSets.yamlRestTest.runtimeClasspath.asPath
This is just a test so we aren't concerned about concise build output. Writing to the console make it a lot easier to debug test failures as with files we need to go digging into temp directories to find them.

2021-02-16 18:10 UTC, mark-vieira commented on buildSrc/src/main/java/org/elasticsearch/gradle/internal/rest/compat/YamlRestCompatTestPlugin.java
> +        yamlCompatTestSourceSet.getOutput().dir(transformCompatTestTask.map(RestCompatTestTransformTask::getOutputDirectory));
That is correct, this creates an implicit dependency here. That is, when we say "yaml compat souce set output includes the output of (a) and (b), anything that depends on that source set output (like the test task itself) implitly depends on (a) and (b)".

2021-02-16 18:11 UTC, mark-vieira commented
Yeah, I still need to track down the root cause of the duplicates and figure out the best solution there. It may very well been that config is redundant and we were copying stuff twice even before, but since we were copying stuff into the same destination, we were just overriding the same files.

2021-02-16 18:34 UTC, jakelandis commented
OK ... I think I figured out why that eql config is bleeding over to x-pack plugin. The RestResource object appears to live beyond the single project execution, normally each project gets a new instance since the project will define a plugin that applies the RestResourcesPlugin which creates a new RestResourcesExtension. In this case the eql project (`x-pack/plugin/eql/qa/correctness/build.gradle`) does not define any plugin that creates the the extension, so it is modifying the prior one defined, in this case the `:x-pack:plugin`. I think this is latent issue and only exposed here...and you can "fix" it by explicity applying `apply plugin: 'elasticsearch.rest-resources'` to the eql project (or just remove the config outright since it is not used).

So the two latent issues are 1) accidental copy of rest resources in :xpack-plugin (fix - remove the config that says to copy) 2) bleeding over of the RestResourcesExtension between projects (fix - remove unnecessary config or explicitly apply the plugin) and log an issue to prevent bleeding over ? (or is that just how gradle works?)

2021-02-16 23:29 UTC, mark-vieira commented
One confusing thing is that `:x-pack:plugin` is both a) the parent project of all other plugin projects and b) a java project in its own right in that it declares tests. We should probably move most of what exists there into a `rest-api-spec` project under `:x-pack` to make it explicit that's what it is.

As to the "leaking" config, yes that is "how gradle works". Specifically that's how dynamic dispatch is implement to search upwards in the project structure for any missing references. I was mostly under the impression that this was limited to things like project and extra properties but apparently this extends to extensions as well, which is unfortunate :facepalm:

2021-02-17 10:30 UTC, breskeby requested changes
Few change requests to avoid getProject() where possible

2021-02-17 10:30 UTC, breskeby commented on buildSrc/src/main/java/org/elasticsearch/gradle/internal/rest/compat/RestCompatTestTransformTask.java
> +    private final DirectoryProperty sourceDirectory = getProject().getObjects().directoryProperty();
Instead of relying on getProject(), we should inject ObjectFactory via constructor and do this assignment in the constructor.

2021-02-17 10:30 UTC, breskeby commented on buildSrc/src/main/java/org/elasticsearch/gradle/test/rest/CopyRestApiTask.java
> +    private final DirectoryProperty outputResourceDir = getProject().getObjects().directoryProperty();
Again we should assign this from an injected ObjectFactory in the constructor. Lets clean up the other usages of getProject() here too

2021-02-17 10:30 UTC, breskeby commented on buildSrc/src/main/java/org/elasticsearch/gradle/test/rest/CopyRestTestsTask.java
> +    private final DirectoryProperty outputResourceDir = getProject().getObjects().directoryProperty();
As above get rid of getProjects()

2021-02-17 16:08 UTC, mark-vieira commented
@elasticmachine update branch

2021-02-17 17:03 UTC, jakelandis commented
> We should probably move most of what exists there into a rest-api-spec project under :x-pack to make it explicit that's what it is.

Actually, I think we can move 90% to the respective x-pack plugins once we provide the clients team a zip of the tests and specs (breaking up that giant test suite). Also, once we have that zip we can move the specs to the single bucket in rest-api-spec.

2021-02-17 17:04 UTC, jakelandis approved these changes
LGTM, thanks for fixing this !

2021-02-17 21:17 UTC, breskeby approved these changes
👍

2021-02-17 23:16 UTC, merged