Search - make wildcard field use constant scoring queries for wildcard queries
elastic/elasticsearch pull request #70452
Opened 2021-03-16 12:12 UTC by markharwood

Wrap the wildcard queries produced by the wildcard field as a constant scoring query because there is no sensible index to use for scoring terms with their frequencies.
Added a note about ignoring rewrite parameters on wildcard queries.

Note this change revealed [an issue](https://github.com/elastic/elasticsearch/issues/69604#issuecomment-800192441) in test which I'm not sure if it is a new general bug which requires attention (@jpountz ?)

Closes #69604

2021-03-16 12:12 UTC, elasticmachine commented
Pinging @elastic/es-search (Team:Search)

2021-03-17 12:13 UTC, markharwood commented
Thanks to @jimczi for discovering the issue revealed as part of adding ConstantScoreQuery - there was a caching issue with AutomatonQueryOnBinaryDV objects due to not implementing hashcode/equals correctly for case sensitivity options. This PR also now includes a fix for that and related test addition.

2021-03-17 12:22 UTC, jimczi requested changes
I left some comments.

2021-03-17 12:22 UTC, jimczi commented on x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/AutomatonQueryOnBinaryDv.java
> +            && Objects.equals(automaton, other.automaton);
`Automaton` does not implement equals/hashCode. The `ByteRunAutomaton` should be used instead.

2021-03-17 12:22 UTC, jimczi commented on x-pack/plugin/wildcard/src/test/java/org/elasticsearch/xpack/wildcard/mapper/WildcardFieldMapperTests.java
> +        assertNotEquals(csQ.hashCode(), csQ2.hashCode());
Can you also test equality. There's a bug currently but this test doesn't catch it (automaton doesn't implement equals/hashCode).

2021-03-17 12:22 UTC, jimczi commented on x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/WildcardFieldMapper.java
> +            return new ConstantScoreQuery(verifyingQuery);
The `AutomatonQueryOnBinaryDv` is already a constant score query so I don't think this is needed.

2021-03-18 16:05 UTC, markharwood commented
One thing I wasn't sure on was when the AutomatonQueryOnBinaryDV should convert the Automaton to a ByteRunAutomaton.
In the constructor or with every call to hashcode/equals/createWeight?

A ByteRunAutomaton looks to use a lot more memory than the source Automaton so might be expensive memory-wise to hold as a field. The alternative of converting Automaton to ByteRunAutomaton every time we want to use it might slow down comparisons in hash look-ups. I've gone with the latter but not sure if that's the better trade-off.

2021-03-24 18:05 UTC, jimczi approved these changes
I left one comment regarding the building of the BytesRunAutomaton. LGTM otherwise.

2021-03-24 18:05 UTC, jimczi commented on x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/AutomatonQueryOnBinaryDv.java
> +            && Objects.equals(new ByteRunAutomaton(automaton), new ByteRunAutomaton(other.automaton));
Rebuilding the `ByteRunAutomaton` on equals and hashCode seems overkill. Let's build it once in the ctr, the AutomatonQuery does the same so no reason to differ.

2021-03-30 09:37 UTC, merged