CORE: Validate list values for settings
elastic/elasticsearch pull request #71276
Opened 2021-04-04 14:11 UTC by amitds1997

Settings value could be a list. This should only
happen if the underlying setting type is a list setting type.

* Validation has been added that
	* when we get a setting value which is list, setting
is also a list setting
	* when we get a value for a list setting, underlying
 value is also a list
* Closes #33135

- If submitting code, have you built your formula locally prior to submission with `gradle check`?

2021-04-22 16:41 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (Team:Core/Infra)

2021-05-11 07:07 UTC, pgomulka commented
ok to test

2021-05-11 07:19 UTC, pgomulka commented
ok to test

2021-05-12 10:33 UTC, pgomulka commented
@amitds1997 this looks good, but can you fix the test? 
You might need to change the message and get rid of the check in Environment 
```
 String rawDataPath = PATH_DATA_SETTING.get(settings);
            if (rawDataPath.startsWith("[")) {
```

can you also add a testcase for SettingsTests with a happy path where a `Setting.listSetting` successfully parses ?

2021-05-12 10:35 UTC, pgomulka requested changes
looks good, thanks!
can you add the testcase for happy path and fix the failing test?
You might need to change the exception message and remove the if condition that throws Environment
```
 String rawDataPath = PATH_DATA_SETTING.get(settings);
            if (rawDataPath.startsWith("[")) {
```

2021-05-12 10:35 UTC, pgomulka commented on server/src/test/java/org/elasticsearch/common/settings/SettingsTests.java
>      public void testGetAsArrayFailsOnDuplicates() {
can we also have a happy path testcase where `Setting.listSetting` parses successfully ?

2021-08-12 16:45 UTC, rjernst commented
@amitds1997 Are you still interested in getting this PR in? If so can you please address the comments Przemek made above?

2021-08-21 08:38 UTC, amitds1997 commented
Sorry, I won't be able to get this through. Anyone else can take this up. Thanks!

2021-08-21 08:38 UTC, closed without merging