Transform docker log4j properties at build time
elastic/elasticsearch pull request #71346
Opened 2021-04-06 14:13 UTC by pugnascotia

For the Docker distribution, we transform the archive distribution's
log4j2 config so that all messages are logged to the console by default.
However this transformation step happens when the Docker image is built,
which means that the source for the transformation must be included in
the Docker context.

Improve this by transforming the config when the Docker context is
built. The downside is that build context task now has dependencies.

Also tweak the Checkstyle config to stop complaining about missing docs
on the `main` method.

2021-04-06 14:13 UTC, elasticmachine commented
Pinging @elastic/es-delivery (Team:Delivery)

2021-04-06 19:02 UTC, mark-vieira requested changes

2021-04-06 19:02 UTC, mark-vieira commented on distribution/docker/transform-log4j-config/build.gradle
> +String transformSource = "${project.projectDir}/src/main/java/org/elasticsearch/transform/log4j/TransformLog4jConfig.java"
We should just convert `TransformLog4jConfig` into a proper Gradle task in `buildSrc` rather then rely on `LoggedExec` here. We don't use that anywhere else and it avoids forking another JVM just to execute that logic.

2021-04-06 19:02 UTC, mark-vieira commented on distribution/docker/transform-log4j-config/build.gradle
> +String transformSource = "${project.projectDir}/src/main/java/org/elasticsearch/transform/log4j/TransformLog4jConfig.java"
In fact, if we do that we can ditch this project entirely and just register the transform task directly in the docker distribution project and get rid of this intermediary project altogether.

2021-04-07 14:14 UTC, pugnascotia commented
@mark-vieira I've made the `log4j2.properties` file an artifact as you suggested, but instead of defining a task, I implemented the transformation as a filter instead. See what you think.

2021-04-07 16:31 UTC, mark-vieira approved these changes
Brilliant. That works just as well :+1:

2021-04-08 08:53 UTC, merged