In expand phase, call onPhaseFailure when multi-search fails.
elastic/elasticsearch pull request #72500
Opened 2021-04-29 18:41 UTC by jtibshirani

Before we called SearchPhaseContext#onFailure, which doesn't release contexts.
This also lets us remove the onFailure method, since there are no other callers.

2021-04-29 20:47 UTC, elasticmachine commented
Pinging @elastic/es-search (Team:Search)

2021-04-29 20:51 UTC, jtibshirani commented
This is just a small clean-up, I didn't see evidence that this actually caused problems with unreleased contexts.

2021-04-30 06:32 UTC, jtibshirani commented
Marked as a draft as I need to look more closely -- I just saw that `onFailure` was intentionally kept in #43269.

2021-04-30 17:07 UTC, jtibshirani commented
@javanna after opening this, I noticed we purposefully kept this `onFailure` call in #43269. Is there a problem with removing it? (I'm new to this part of the code and am working to improve my understanding.)

2021-05-03 07:41 UTC, javanna commented
@jtibshirani I wish I had used either the typical `iter` commit message or add some explanation around why I was reverting part of the initial changes in the linked PR. I have absolutely no memory about this, do you @jimczi ?

2021-05-03 09:58 UTC, jimczi requested changes
`onPhaseFailure` is called to release the search contexts that are held between the query and the fetch phase. The expand phase doesn't use these contexts, they are released at the end of the fetch phase. So calling `onPhaseFailure` at this stage would try to remove outdated contexts. 
So if we want to have a consistent way to fail an entire phase, we should take into account phases that happen after the release of the context. It could be a boolean that we had to the public function or the `results` array could be cleared when the fetch phase has completed ?

2021-05-03 23:16 UTC, jtibshirani commented
Thanks @jimczi, then my description doesn't make sense! I hadn't seen that contexts were released early.

Looking at the code, we already call `onPhaseFailure` in the expand phase if an individual multi-search fails: https://github.com/elastic/elasticsearch/blob/95f3bee07ef172495e9e97ec955573eaf21b2367/server/src/main/java/org/elasticsearch/action/search/ExpandSearchPhase.java#L95

If I'm understanding correctly, we can also try to rerelease a context in the fetch phase: https://github.com/elastic/elasticsearch/blob/c1c5e67f373331290fd46e8ee6e0b71c759df922/server/src/main/java/org/elasticsearch/action/search/FetchSearchPhase.java#L184-L189

Do you think it's worth distinguishing between the cases with a boolean flag, or is it simpler to just rerelease sometimes in these rare error cases?

2021-05-12 02:55 UTC, dnhatn commented
I think line 95 in ExpandSearchPhase that you quoted would cause the same issue (i.e., try to release some search contexts twice). We should fix it. I am in favor of removing `SearchPhaseContext#onFailure`, but I don't have a better suggestion than what Jim said. Also, `releasables` of AbstractSearchAsyncAction are currently released twice.

2021-05-14 01:53 UTC, jtibshirani commented
Thanks @dnhatn for looking. I plan to close this and open a separate PR focused on not releasing contexts twice. For my knowledge, is the only problem that it's a bit wasteful? From my research it looks like it couldn't actually cause bugs?

> Also, releasables of AbstractSearchAsyncAction are currently released twice.

We already fixed this in a separate PR.

2021-05-14 04:57 UTC, dnhatn commented
>  For my knowledge, is the only problem that it's a bit wasteful? From my research it looks like it couldn't actually cause bugs?

That's correct but we would send release context requests twice in this case.

2021-05-14 06:45 UTC, closed without merging