Remove multiple paths from ShardPath
elastic/elasticsearch pull request #72713
Opened 2021-05-04 17:51 UTC by rjernst

relates #71205

2021-05-04 17:51 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (Team:Core/Infra)

2021-05-05 17:11 UTC, jasontedor requested changes
I left a few comments.

2021-05-05 17:11 UTC, jasontedor commented on server/src/main/java/org/elasticsearch/index/shard/ShardPath.java
>       */
This comment looks out of date now.

2021-05-05 17:11 UTC, jasontedor commented on server/src/main/java/org/elasticsearch/index/shard/ShardPath.java
> +    public static ShardPath loadShardPath(Logger logger, ShardId shardId, String customDataPath, Path availableShardPath,
Isn't this just `shardPath` now?

2021-05-05 18:46 UTC, rjernst commented on server/src/main/java/org/elasticsearch/index/shard/ShardPath.java
>       */
Good catch. I tweaked these in 16975ec

2021-05-05 18:46 UTC, rjernst commented on server/src/main/java/org/elasticsearch/index/shard/ShardPath.java
> +    public static ShardPath loadShardPath(Logger logger, ShardId shardId, String customDataPath, Path availableShardPath,
Yes. Renamed in 16975ec

2021-05-05 18:49 UTC, jasontedor approved these changes
LGTM.

2021-05-05 19:47 UTC, merged