Add _meta field to ilm policy
elastic/elasticsearch pull request #73515
Opened 2021-05-28 08:51 UTC by gaobinlong

Relates to #70755.

The main changes of this PR are:
1. Add an optional `_meta` field to ILM policy.
2. Add some test code about the change.
3. Update the doc of `Create or update lifecycle policy API`.

2021-05-28 08:52 UTC, gaobinlong commented
@dakrone, can you help to take a look at this PR?

2021-05-28 14:38 UTC, elasticmachine commented
Pinging @elastic/es-core-features (Team:Core/Features)

2021-05-28 21:57 UTC, dakrone requested changes
Thanks for working on this @gaobinlong! I left a couple of comments, we need to add BWC version checks for the serialization

2021-05-28 21:57 UTC, dakrone commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/LifecyclePolicy.java
> +        }
This needs some version control logic, something like:

```java
if (in.getVersion().onOrAfter(Version.V8_0_0)) {
    this.metadata = in.readMap();
} else {
    this.metadata = null;
}
```

(`readMap()` and `writeMap(...)` can return null and handle null values)

2021-05-28 21:57 UTC, dakrone commented on x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/LifecyclePolicy.java
> +        }
Same here about version control, something like:

```java
if (out.getVersion().onOrAfter(Version.V8_0_0)) {
    out.writeMap(this.metadata);
}
```

2021-05-28 21:58 UTC, dakrone commented
@elasticmachine ok to test

2021-05-31 07:25 UTC, gaobinlong commented
@dakrone, thanks for your review, I have added some BWC code and all checks have passed yet.

2021-06-01 14:14 UTC, dakrone commented
@elasticmachine test this please

2021-06-01 17:17 UTC, dakrone approved these changes
LGTM, thanks for adding this @gaobinlong! I'll merge this and work on backporting it.

2021-06-01 17:17 UTC, merged