Remove deprecated string concat painless
elastic/elasticsearch pull request #74214
Opened 2021-06-16 20:51 UTC by danielcr10

Removing the deprecated string builder and adding the new implementation adopted by Java 9.
And remove the conditionals that identify Java 8 and using string concatenation with +.

Closes #52601

2021-06-25 03:59 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (Team:Core/Infra)

2021-07-06 14:53 UTC, stu-elastic requested changes
Hi @danielcr10 it's a bit premature to remove this as we are still supporting [Java 8](https://www.elastic.co/support/matrix#matrix_jvm) and so we would not be able to backport it.

2021-12-01 14:15 UTC, pugnascotia commented
@stu-elastic since v8.0 will be Java 17, are still we interested in including this change?

2021-12-01 16:33 UTC, jdconrad commented
This is a change we would still like and can be applied for 8.1+. @danielcr10 are you still interested in working on this?

2022-07-24 18:28 UTC, closed without merging