Deprecate frozen indices endpoint in REST API specification
elastic/elasticsearch pull request #74983
Opened 2021-07-06 14:39 UTC by stevejgordon

Relates to #72618 which added deprecation warnings for this endpoint. This PR adds the deprecation to the REST API spec so that clients can generate the appropriate code comments.

@danhermann perhaps you can ensure this is as you'd expect based on your previous PR?

I believe this should be merged into 7.x and 7.14 branches. I've targeted 7.x as the base for the PR and added the `v7.14.0` label + `auto-backport`. I may need some help confirming that this is the correct labelling before this gets merged.

2021-07-06 14:39 UTC, elasticmachine commented
Pinging @elastic/es-core-features (Team:Core/Features)

2021-07-06 15:02 UTC, elasticmachine commented
Pinging @elastic/clients-team (Team:Clients)

2021-07-06 15:13 UTC, danhermann requested changes
We do want to keep the original verbiage on the warning (Frozen indices are deprecated because they provide no benefit given improvements in heap memory utilization. They will be removed in a future release.) because we are not committing to removing them in the 8.0 release.

2021-07-06 15:17 UTC, stevejgordon commented
> We do want to keep the original verbiage on the warning (Frozen indices are deprecated because they provide no benefit given improvements in heap memory utilization. They will be removed in a future release.) because we are not committing to removing them in the 8.0 release.

I can adjust that for sure.

2021-07-07 13:10 UTC, closed without merging

2021-07-07 13:10 UTC, stevejgordon commented
Closing and will resubmit based on master.