Refactor SimpleFeatureFactory so it has no external dependencies
elastic/elasticsearch pull request #75232
Opened 2021-07-12 12:58 UTC by iverase

SimpleFeatureFactory can generate vector tile features of simple geometries like points and rectangles. This PR refactor that class so it does not have external dependencies, e.g it contains the methods to serialise the feature into a byte array. This makes possible to maybe move this class to server.

This PR adds more test to the feature factory implementation,

2021-07-12 12:58 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo (Team:Analytics)

2021-07-12 22:31 UTC, imotov requested changes
I would be more comfortable if it didn't copy code (even if it is one function) without attribution.

2021-07-13 06:40 UTC, iverase commented
Right, I think it was. a mistake to copy those methods as we just need to write integers using vints. I modified the code so we are suing a `BytesStreamOutput` to write the features.

2021-07-13 15:56 UTC, imotov approved these changes
LGTM, thanks!

2021-07-14 05:47 UTC, merged