Add `replace` shutdown type
elastic/elasticsearch pull request #75908
Opened 2021-07-30 22:19 UTC by gwbrown

This PR adds the `REPLACE` shutdown type. More description to come.

---

Draft because: No tests yet.

2021-08-20 23:43 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (Team:Core/Infra)

2021-08-23 21:51 UTC, dakrone requested changes
I left a comment, I think we need to treat REPLACE similar to REMOVE in the ILM status check

2021-08-23 21:51 UTC, dakrone commented on x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleService.java
> +        // GWB-> Handle REPLACE here
I think this branch still needs to be handled since we would exit early on accident without handling it

2021-08-25 23:04 UTC, dakrone approved these changes

2021-08-30 14:37 UTC, gwbrown commented
Changes look good to me, gonna merge master and let CI pass one more time since it's been a few days since the last merge.

@elasticmachine update branch

2021-08-30 16:13 UTC, gwbrown commented
@elasticmachine update branch

2021-08-30 17:34 UTC, merged

2021-08-30 17:35 UTC, elasticsearchmachine commented
## 💚 Backport successful
| Status | Branch | Result |
|:------:|:------:|:------:|
| ✅ |  [7.x](https://github.com/elastic/elasticsearch/pull/77035)  | [<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/77035">](https://github.com/elastic/elasticsearch/pull/77035) |