Fix memory/breaker leaks for outbound responses
elastic/elasticsearch pull request #76474
Opened 2021-08-12 21:36 UTC by henningandersen

Outbound responses would not get the expected `decRef`, resulting in
memory and/or circuit breaker leaks. In particular, the
`GetCcrRestoreFileChunkResponse` expects this, causing a leak when
a follower bootstraps.

Relates #65921

2021-08-12 21:36 UTC, elasticmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2021-08-13 04:41 UTC, original-brownbear requested changes
Thanks for spotting this Henning!

unfortunately, the tests are failing now. There must be more to this than just a failure in the general case as this would definitely fail existing tests if it would leak all the time.
We must fail to invoke a listener/decrement in some exceptional case as now we're failing tests with:

```
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=50, name=elasticsearch[leader1][transport_worker][T#2], state=RUNNABLE, group=TGRP-RestartIndexFollowingIT]

        Caused by:
        java.lang.AssertionError
            at __randomizedtesting.SeedInfo.seed([3BDF36A18D3FAC5D]:0)
            at org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:52)
            at org.elasticsearch.common.bytes.ReleasableBytesReference.close(ReleasableBytesReference.java:90)
            at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:314)
            at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:217)
            at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:29)
            at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
            at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:140)
            at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:409)
            at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:235)
            at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163)
            at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120)
            at java.base/java.lang.Thread.run(Thread.java:834)
```

2021-08-13 08:47 UTC, original-brownbear approved these changes
LGTM after discussing on another channel this looks just fine :)

2021-08-13 08:57 UTC, henningandersen commented
Let us do one more round of randomized test:
@elasticmachine run tests

2021-08-13 08:59 UTC, henningandersen commented
@elasticmachine test this please

2021-08-14 16:41 UTC, merged