Adding deprecation checks for geo_shape parameters
elastic/elasticsearch pull request #76627
Opened 2021-08-17 22:07 UTC by masseyke

The following properties have been removed from the geo_shape data type in 8.0: "strategy", "tree", "tree_levels", "precision", "distance_error_pct", "points_only". This PR adds a deprecation info API check for indexes and templates that have any of these properties in their mappings. Relates to #42404 and #70850.

2021-08-26 21:19 UTC, jbaiera requested changes
A few questions, but things look good

2021-08-30 13:54 UTC, masseyke commented on x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/ClusterDeprecationChecks.java
> +            StreamSupport.stream(clusterState.getMetadata().getTemplates().spliterator(), false).map((templateCursor) -> {
Are those not returned by clusterState.getMetadata().getTemplates()? How do I get access to component templates?

2021-08-30 14:42 UTC, masseyke commented on x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/ClusterDeprecationChecks.java
> +            StreamSupport.stream(clusterState.getMetadata().getTemplates().spliterator(), false).map((templateCursor) -> {
Oh I see now that there's a separate clusterState.getMetadata().componentTemplates() method. I'll add that here.

2021-08-30 16:53 UTC, masseyke commented on x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/IndexDeprecationChecks.java
> +                "a future version", type, deprecatedParameter, fieldName))
Done.

2021-08-30 16:53 UTC, masseyke commented on x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/IndexDeprecationChecks.java
> +            .collect(Collectors.joining("; "));
Done.

2021-08-30 16:54 UTC, masseyke commented on x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/ClusterDeprecationChecks.java
> +            StreamSupport.stream(clusterState.getMetadata().getTemplates().spliterator(), false).map((templateCursor) -> {
Done.

2021-09-01 19:45 UTC, jbaiera approved these changes
LGTM! Thanks for making those changes

2021-09-01 21:00 UTC, merged

2021-12-03 18:09 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo (Team:Analytics)