Type Migration: introducing primitive functional interfaces
elastic/elasticsearch pull request #76808
Opened 2021-08-23 09:15 UTC by SmirnovOleg

Hey!

We are a collaborative group of researchers from JetBrains Research and Oregon State University, and we are testing our data-driven [plugin](https://github.com/JetBrains-Research/data-driven-type-migration), which is based on the IntelliJ's [Type Migration](https://www.jetbrains.com/help/idea/type-migration.html) framework and adjusts it using custom structural-replace templates that express the adaptations required to perform the type changes.

I want to apply several type changes using it and open the PR, thus introducing primitive functional interfaces in order to prevent unnecessary boxing (like BooleanSupplier instead of Supplier<Boolean>, OptionalInt instead of Optional<Integer>, Predicate<T> instead of Function<T, Boolean>, etc.), since it can affect the performance of the code (Effective Java, Items 44, 61). 

This patch is made automatically by the plugin, so it would help us a lot to evaluate the usefulness of our approach!

Thank you in advance!

2021-08-30 11:59 UTC, henningandersen commented
@elasticmachine test this please

2021-09-01 10:16 UTC, henningandersen requested changes
This looks mostly good, but would like to see one comment addressed before merging.

2021-09-02 07:36 UTC, SmirnovOleg commented on server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodes.java
> +                            final Predicate<String> mutation;
Fixed

2021-09-02 07:37 UTC, SmirnovOleg commented
@henningandersen @ChrisHegarty Thank you for such quick feedback!
Hope that I've fixed all the comments in the last commits!

2021-09-02 11:08 UTC, henningandersen requested changes
Thanks for addressing the initial feedback. I missed a few whitespace-nits initially, hope you do not mind resolving those too.

2021-09-02 11:08 UTC, henningandersen commented on x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/action/TransportDeleteExpiredDataActionTests.java
> +                BooleanSupplier isTimedOutSupplier
I think this indentation change does not match our conventions, can you remove the extra indentation?

2021-09-02 11:08 UTC, henningandersen commented on x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/retention/ExpiredForecastsRemover.java
> +            BooleanSupplier isTimedOutSupplier
I think this indentation change does not match our conventions, can you remove the extra indentation?

2021-09-02 17:52 UTC, SmirnovOleg commented
@henningandersen  
Done!

2021-09-03 09:33 UTC, henningandersen commented
@elasticmachine test this please

2021-09-03 10:16 UTC, henningandersen commented
@elasticmachine update branch

2021-09-03 10:21 UTC, henningandersen commented
@elasticmachine test this please

2021-09-03 11:42 UTC, henningandersen approved these changes
LGTM, thanks for your contribution.

2021-09-03 11:45 UTC, merged