Deprecate lenient parsing of bulk actions
elastic/elasticsearch pull request #78876
Opened 2021-10-08 14:41 UTC by arteam

Make sure there are no arbitrary fields after an action declaration and that it gets properly closed by a curly bracket.

Resolves #43774

2021-10-26 12:01 UTC, DaveCTurner requested changes
I suggested some other ways that we accept invalid input. Could you add tests that assert that the new warnings are emitted too please?

2021-11-01 17:47 UTC, DaveCTurner reviewed
Looks great, I left only minor comments/questions.

2021-11-01 17:47 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/action/bulk/BulkRequestParser.java
> +                "A bulk action contains trailing junk after the closing brace. It is currently ignored but will be rejected in a "
Rewording suggestion:

```suggestion
                "A bulk action contained trailing data after the closing brace. This is currently ignored but will be rejected in a "
```

2021-11-01 17:47 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/action/bulk/BulkRequestParser.java
> +                    );
`DeprecationLogger#compatibleCritical` looks to accept a format string and args already, do we need to use `String.format` here or could we just do this?

```suggestion
                    deprecationLogger.compatibleCritical(
                        STRICT_ACTION_PARSING_WARNING_KEY,
                            "Unsupported action: [{}]. Supported values are [create], [delete], [index], and [update]. "
                                + "Unsupported actions are currently accepted but will be rejected in a future version.",
                            action
                    );
```

Also I'd prefer `[brackets]` over backticks in these messages.

2021-11-02 14:18 UTC, arteam commented
@elasticmachine update branch

2021-11-05 17:01 UTC, DaveCTurner reviewed
Code changes all LGTM, but since this adds deprecations I think we need to add docs about the change too. https://github.com/elastic/elasticsearch/pull/80410 adds the deprecation docs files for 8.1.0 so you can either wait for that to be merged or else duplicate those files here (and I'll sort out any merge conflicts on my PR later).

2021-11-09 09:32 UTC, arteam commented
@elasticmachine update branch

2021-11-09 12:09 UTC, merged

2021-11-09 12:09 UTC, arteam commented
Thanks David!

2021-11-10 09:08 UTC, DaveCTurner commented
I would have preferred not to have merged this until the docs changes were reviewed and approved - it's hard to keep track of outstanding things to review otherwise. I opened https://github.com/elastic/elasticsearch/pull/80580 to suggest alternative wording and revert the unnecessary docs formatting changes that this PR introduces.