Update question: index recovery
elastic/elasticsearch pull request #78881
Opened 2021-10-09 02:54 UTC by stefnestor

Hello, team! I'm trying to understand possible recovery stages for myself per [this doc > `STAGE`](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-recovery.html#index-recovery-api-response-body) as compared to [this code](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/indices/recovery/RecoveryState.java#L41-L91) ([part2](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/indices/recovery/RecoveryState.java#L187-L223)). However, I'm not finding the expected reference to `STAGE:start` & instead am finding reference to `STAGE:verify_index`. I may be missing a code-to-human translation somewhere. Will you double check for me? 🙏🏼

2021-10-09 02:54 UTC, elasticmachine commented
Pinging @elastic/es-docs (Team:Docs)

2021-10-09 13:39 UTC, elasticmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2021-10-14 06:57 UTC, DaveCTurner requested changes
`VERIFY_INDEX` is a possible state, although usually it instantaneously moves to `TRANSLOG`. The description is wrong tho, it should say something like

> Verifying the integrity of the index.

Also the order is now inconsistent - it looks like they were in alphabetical order so `VERIFY_INDEX` should be at the end. Alternatively they could be in temporal order:

1. `INIT`
2. `INDEX`
3. `VERIFY_INDEX`
4. `TRANSLOG`
5. `FINALIZE`
6. `DONE`

2021-10-14 15:03 UTC, lockewritesdocs approved these changes
LGTM 👍 Thanks to @DaveCTurner for input!

2021-10-14 15:03 UTC, merged

2021-10-14 15:05 UTC, elasticsearchmachine commented
## 💚 Backport successful
| Status | Branch | Result |
|:------:|:------:|:------:|
| ✅ |  [7.x](https://github.com/elastic/elasticsearch/pull/79160)  | [<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/79160">](https://github.com/elastic/elasticsearch/pull/79160) |
| ✅ |  [7.15](https://github.com/elastic/elasticsearch/pull/79161)  | [<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/79161">](https://github.com/elastic/elasticsearch/pull/79161) |