Rework docs for the `size` of `terms` agg
elastic/elasticsearch pull request #79205
Opened 2021-10-14 22:57 UTC by nik9000

The `terms` agg picks the top `size` terms in a single scatter/gather
pass across all the shards. For the default `order` and if you `order`
by `_key` this works quite well. Some errors creep in, but it's fairly
easy to point to them and understand them. But ordering by doc count
ascending is like inviting the error vampire into your agg. It's super
easy to get inaccurate results. This updates the docs to be more stark
about it.

Closes #72684

2021-10-14 22:57 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo (Team:Analytics)

2021-10-15 20:21 UTC, jrodewig requested changes
Thanks for putting this together, @nik9000.

For this first pass, I focused mostly on the `order` warnings. However, I also left some feedback on the other sections. Don't feel obligated to take all the suggestions.

I'd like to take another look once you feel this is ready for it.

2021-10-28 14:00 UTC, jrodewig approved these changes
Thanks for iterating on this @nik9000. Overall, this LGTM.

I mostly left minor style nits that you can disregard if wanted. The only bigger piece of feedback is in the `size` section. We may want to provide clearer guidance on:

- How many terms are "too many" when choosing between the terms agg and the composite agg.
- What happens if you try using a huge `size` on a high-cardinality field.

2021-11-01 20:07 UTC, nik9000 commented
run elasticsearch-ci/part-2

2021-11-01 21:07 UTC, merged

2021-11-01 21:08 UTC, elasticsearchmachine commented
## 💔 Backport failed
| Status | Branch | Result |
|:------:|:------:|:------:|
| ❌ |  7.15  | Commit could not be cherrypicked due to conflicts |
| ✅ |  [8.0](https://github.com/elastic/elasticsearch/pull/80162)  | [<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/80162">](https://github.com/elastic/elasticsearch/pull/80162) |

You can use [sqren/backport](https://github.com/sqren/backport) to manually backport by running `backport --upstream elastic/elasticsearch --pr 79205`

2021-11-01 21:21 UTC, nik9000 commented
OK! I'll backport it myself.

2021-11-02 20:23 UTC, nik9000 commented on server/src/main/java/org/elasticsearch/index/query/CoordinatorRewriteContextProvider.java
> +import org.elasticsearch.xcontent.XContentParserConfiguration;
Oh yikes this snuck in here! That was not my intent....

2021-11-02 20:25 UTC, nik9000 commented on server/src/main/java/org/elasticsearch/index/query/CoordinatorRewriteContextProvider.java
> +import org.elasticsearch.xcontent.XContentParserConfiguration;
It's supposed to be in https://github.com/elastic/elasticsearch/pull/80161 - which was approved. So I'm not going to revert.

2021-11-02 20:26 UTC, nik9000 commented on server/src/main/java/org/elasticsearch/index/query/CoordinatorRewriteContextProvider.java
> +import org.elasticsearch.xcontent.XContentParserConfiguration;
But I won't backport it.

2021-11-02 20:50 UTC, nik9000 commented
Backported in #80223, #80226, and #80227.