Adjust snapshot index resolution behavior to be more intuitive
elastic/elasticsearch pull request #79670
Opened 2021-10-22 00:18 UTC by gwbrown

This PR removes the logic used to ensure backwards-compatible behavior
in the Snapshot and Restore APIs and updates the tests to check the new
logic. This is technically a breaking change, but significantly improves
the usability of snapshots in the presence of system indices.

The new behavior is as follows:
- When creating a snapshot, system indices are not resolved based on the
`indices` field in the request. System indices are included or excluded
using the `include_global_state` or `feature_states` fields, defaulting
to snapshotting all system indices.
- When restoring a snapshot, system indices cannot be requested using
the `indices` field in the request. System indices are included or
excluded using the `include_global_state` or `feature_states` fields,
defaulting to restoring no system indices.

Fixes https://github.com/elastic/elasticsearch/issues/78320

---

It's worth noting that this is a breaking change, but we deprecated the behavior that won't work anymore a while ago, and I don't think anyone likes the current behavior - it's a mess because of shenanigans we had to pull to maintain BWC.

2021-11-01 19:13 UTC, williamrandolph requested changes
Production code changes look straightforward. I only have a couple of cleanup nitpicks and suggestions, and it looks like there might be a nontrivial test failure to fix.

2021-11-09 01:24 UTC, gwbrown commented on server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemIndicesSnapshotIT.java
> +        // GWB> What do we check here?
This test case was now a duplicate of another! So I deleted it.

2021-11-17 21:00 UTC, williamrandolph approved these changes
LGTM!

2021-11-29 23:01 UTC, gwbrown commented
@elasticmachine update branch

2021-11-30 19:00 UTC, original-brownbear approved these changes
LGTM from my end :) Sorry for the delay here!

2021-11-30 21:41 UTC, merged

2021-11-30 21:42 UTC, elasticsearchmachine commented
## 💚 Backport successful
| Status | Branch | Result |
|:------:|:------:|:------:|
| ✅ |  [8.0](https://github.com/elastic/elasticsearch/pull/81180)  | [<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/81180">](https://github.com/elastic/elasticsearch/pull/81180) |