[DOCS] Add deprecation notice for system indices
elastic/elasticsearch pull request #80028
Opened 2021-10-28 16:18 UTC by lockewritesdocs

In 7.16, directly accessing system indices is deprecated. If an application or API directly accesses system indices, we generate warnings in the deprecation log as indicated in #79633. PR #80095 will add a deprecation message for 7.16.

In 8.0, users _must_ add the `allow_restricted_indices` permission set to `true` on a user role to access
system indices. This PR adds a deprecation notice to the 8.0 migration docs so that we can inform users of this change and link to documentation for guidance.

**We should wait until #79679 is merged so that we can link directly to that documentation for more details.**

Preview link: https://elasticsearch_80028.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/migrating-8.0.html#breaking_80_indices_changes

Relates to #79679

2021-11-02 17:08 UTC, williamrandolph approved these changes
From the dev's perspective, I think this is all accurate, and will be complete once we can link to something that explains what system indices are. I can't speak to the product manager perspective.

2021-11-02 23:31 UTC, bytebilly requested changes
I left a suggestion, LGTM otherwise

2021-11-02 23:31 UTC, bytebilly commented on docs/reference/migration/migrate_8_0/indices.asciidoc
> +responses. Use {kib} or the associated feature's {es} APIs to manage the data
```suggestion
responses. If available, use {kib} or the associated feature's {es} APIs to manage the data
```

We may not have coverage for every feature, so we should mention to check availability.

2022-02-08 20:59 UTC, lockewritesdocs commented
@elasticmachine update branch

2022-02-08 20:59 UTC, elasticmachine commented
merge conflict between base and head

2022-02-08 21:48 UTC, lockewritesdocs commented
After battling with a  gnarly rebase, I applied these changes in #83688.

2022-02-08 21:48 UTC, closed without merging