Remove code related to Beats Central Management
elastic/elasticsearch pull request #80107
Opened 2021-10-29 20:36 UTC by justincr-elastic

2021-11-01 15:13 UTC, elasticmachine commented
Pinging @elastic/es-security (Team:Security)

2021-11-04 08:49 UTC, tvernum requested changes
Unfortunately, removing a builtin role is a breaking change, and we can't do that without a period of deprecation.

We need to keep the `beats_admin` role, but deprecate it.
We can remove the license related code.

2021-11-04 08:49 UTC, tvernum commented on client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/SecurityDocumentationIT.java
>              // 30 system roles plus the three we created
```suggestion
            // 29 system roles plus the three we created
```

2021-11-05 15:27 UTC, justincr-elastic commented on client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/SecurityDocumentationIT.java
>              // 30 system roles plus the three we created
I fixed the comment. Thank you.

2021-11-05 20:14 UTC, justincr-elastic commented
https://www.elastic.co/guide/en/beats/filebeat/8.0/configuration-central-management.html
"Starting in version 7.14, Beats central management has been removed."

@tvernum, since it has been removed from Kibana, is it ok to do ahead and remove it from Elasticsearch 8.x?

2021-11-08 03:11 UTC, tvernum commented
No, even though the functionality that it was intended to support has been removed from Kibana, the role itself exists in Elasticsearch and hasn't been marked as deprecated, nor was it ever marked as `beta` (which the Kibana functionality was).

We really do need to deprecate the role instead of removing it.

2022-05-12 15:52 UTC, closed without merging