Upgrade log4j to 2.16.0
elastic/elasticsearch pull request #81759
Opened 2021-12-15 13:38 UTC by arteam

We upgraded log4j to 2.15.0 in #81709 and we can do the next upgrade. It makes JNDI lookups opt-in and also fixes [CVE-2021-45046](https://github.com/advisories/GHSA-7rjr-3q55-vv33)

2021-12-15 13:38 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (Team:Core/Infra)

2021-12-15 14:28 UTC, arteam commented
@elasticmachine run elasticsearch-ci/part-1

2021-12-15 16:17 UTC, mark-vieira approved these changes
LGTM

2021-12-15 17:01 UTC, pgomulka requested changes
it looks good. I would prefer to split a revert and upgrade into separate PRs.
There should also be a revert of ef64808caf3902ea50014aebcd3026aa2ef4da0b before we upgrade to 2.16?

also it looks like there should be another log4j release very soon 
https://github.com/apache/logging-log4j2/commit/4456909#r61971917

2021-12-15 17:32 UTC, arteam commented on distribution/build.gradle
> -    all {
Let me extract the revert into a separate PR and then we can rebase this PR when the revert gets merged

2021-12-15 19:32 UTC, jasvinder1107 commented
@arteam  can you please look at why merging is blocked. This is high priority fix that we need to do  patch this before year end.

2021-12-15 20:21 UTC, arteam commented on distribution/build.gradle
> -    all {
Submitted as #81783

2021-12-15 20:35 UTC, jasvinder1107 commented
@arteam  thank you for so quick response. @pgomulka please give your blessing on this ps so this can be merged. :)

2021-12-16 19:22 UTC, jasvinder1107 commented
@arteam @pgomulka  I am sorry to being chatty here, can you please help us merging this asap ?

2021-12-16 23:01 UTC, jasvinder1107 approved these changes

2021-12-17 17:03 UTC, DJRickyB commented
closes #81867

2021-12-17 17:10 UTC, ChrisHegarty commented
We're already at 2.15.0 and have stripped JnidLookup.class, which is arguably more secure than 2.16.0. The stripping greatly outweighs the benefits of 2.16.0. The 2.16.0 release has a static dependency on JndiLookup.class. We're awaiting 2.6.1 where will be keep the stripping.

2021-12-17 17:12 UTC, ChrisHegarty requested changes
Please do not merge this PR, we're waiting for 2.16.1

2021-12-17 17:22 UTC, jasvinder1107 commented
@ChrisHegarty  so just to understand you correctly there will be stripping of the jndiclass from 2.16.1 also ?. Also can you please give us light on CVE in the 2.16.0 ?

2021-12-18 09:05 UTC, dionrhys commented
Log4j2 2.17.0 has now been released with a fix to CVE-2021-45105, opt-in system properties for JNDI, and removing support for LDAP(S) over JNDI.

- https://github.com/apache/logging-log4j2/blob/6b1581901ba7a107cdc4a2208ecec03655722b44/RELEASE-NOTES.md
- https://logging.apache.org/log4j/2.x/security.html

2021-12-18 18:39 UTC, costin commented
Superseded by https://github.com/elastic/elasticsearch/pull/81902 (Upgrade to Log4J 2.17.0)

2021-12-18 18:39 UTC, closed without merging