server instanceof pattern matching replacement
elastic/elasticsearch pull request #82074
Opened 2021-12-24 07:20 UTC by idegtiarenko

Switch to Java 17 instanceof pattern matching for server

Rel: #81820

2021-12-24 07:20 UTC, elasticmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2021-12-24 13:47 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (Team:Core/Infra)

2021-12-24 14:45 UTC, astefan requested changes
Looks good except the `final` variable casts where my proposal is to keep them as is, so that the original author's intention is kept intact.

2022-01-04 08:21 UTC, idegtiarenko commented on server/src/main/java/org/elasticsearch/action/admin/indices/analyze/TransportAnalyzeAction.java
> +                if (value instanceof BytesRef p) {
Looks like `identifier instanceof final Type otherIdentifier` is also a valid syntax. May be we should try that instead?

2022-01-04 09:10 UTC, astefan approved these changes
LGTM

2022-01-06 07:15 UTC, merged

2022-01-06 07:16 UTC, elasticsearchmachine commented
## 💔 Backport failed
| Status | Branch | Result |
|:------:|:------:|:------:|
| ❌ |  8.0  | Commit could not be cherrypicked due to conflicts |

You can use [sqren/backport](https://github.com/sqren/backport) to manually backport by running `backport --upstream elastic/elasticsearch --pr 82074`