FilterPathBasedFilter support match fieldname with dot
elastic/elasticsearch pull request #83178
Opened 2022-01-26 18:29 UTC by mushao999

Current `FilterPathBasedFilter` does not support match fieldName with dot.
This PR merges the changes of #83148 and #83152 together to add the ability of `matching fieldName with dot` to the `FilterPathBasedFilter`.

2022-01-26 18:30 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (Team:Core/Infra)

2022-01-27 17:08 UTC, nik9000 commented
@elasticmachine, test this please

2022-01-27 17:13 UTC, nik9000 requested changes
I think you've added two bits of my other PR that you should remove. I commented on the files. *I* think they are the right thing to change, but I want to get them reviewed by other folks. But I can review the xcontent change. I think it fine - though I'd prefer a non-recursive solution. I added a couple other test cases, one that blows up in a recursive solution.

I see now what you are doing with prefix matching - it's for if the pattern *fully* matches. That makes sense to me. I added some more test cases to the abstract filtering test case thingy for that too.

2022-01-28 10:26 UTC, mushao999 commented on server/src/main/java/org/elasticsearch/cluster/routing/IndexRouting.java
> +import org.apache.lucene.util.StringHelper;
upated

2022-01-28 10:30 UTC, mushao999 commented
@nik9000 I've rollback the changes you comment and add some tests for double wildcard in `AbstractXContentFilteringTestCase`.

2022-01-28 14:40 UTC, nik9000 commented
@elasticmachine, test this please

2022-01-28 14:42 UTC, nik9000 commented
Thanks for your changes so far! I think one of the tests is still going to fail because the solution is recursive, but otherwise I'm happy with it. Could you try running `JsonXContentFilteringTests` and see what that does? I *thought* the test I pushed would fail. At least, it did on my laptop yesterday.

2022-01-28 15:10 UTC, nik9000 commented
I talked with @mushao999 about the recursion here. He mentioned that the test that I added actually stack overflows on other code! Ooops. But he's going to zap his recursion to make me happy. I'm thankful for that.

2022-01-28 15:46 UTC, nik9000 commented
@elasticmachine, test this please

2022-01-28 15:47 UTC, nik9000 approved these changes
For now we're going to let the recursion live. We both want to zap it, but don't have any good ideas at the moment.

2022-01-28 16:44 UTC, merged