Upgrade Checkstyle to 9.3
elastic/elasticsearch pull request #83314
Opened 2022-01-31 10:42 UTC by pugnascotia

Checkstyle 9.3 has been released, and contains a fix for the memory problems we saw in previous versions. Upgrade to this version. 

Note that the IDEA config has also been updated, but the plugin doesn't yet have 9.3 as an option according to the release notes. This shouldn't be a problem.

2022-01-31 10:42 UTC, elasticmachine commented
Pinging @elastic/es-delivery (Team:Delivery)

2022-02-02 17:45 UTC, mark-vieira requested changes

2022-02-02 17:45 UTC, mark-vieira commented on .idea/checkstyle-idea.xml
> +        <entry key="active-configuration" value="PROJECT_RELATIVE:/Users/rory/src/elastic/elasticsearch/checkstyle_ide.xml:Elasticsearch" />
Looks like IntelliJ snuck this change in. We should still be using `$PROJECT_DIR$` here.

2022-02-02 21:39 UTC, mark-vieira approved these changes
LGTM

2022-02-03 12:01 UTC, pugnascotia commented
@elasticmachine update branch

2022-02-03 16:41 UTC, pugnascotia commented
@elasticmachine update branch

2022-02-04 16:39 UTC, pugnascotia commented
@elasticmachine update branch

2022-02-07 10:34 UTC, merged