Render Mappings more Compact in GET /_cluster/state
elastic/elasticsearch pull request #83846
Opened 2022-02-11 18:04 UTC by original-brownbear

This deduplicates index mappings in the `/_cluster_state` response by grouping them by the sha256 hash of the mapping.
This significantly reduces the response size for large cluster states,
making this debug API easier to read for humans (because understanding
whether or not mappings are duplicated across indices might be valuable)
and more importantly less ressource hungry as far as serialization goes.

Adds an undocumented parameter to get back to the old format if we actually have to in an unforeseen instance.

New rendering of an index:

```json
      "my-index-000001" : {
        "version" : 5,
        "mapping_version" : 2,
        "settings_version" : 1,
        "aliases_version" : 1,
        "routing_num_shards" : 1024,
        "state" : "open",
        "settings" : {
          "index" : {
            "routing" : {
              "allocation" : {
                "include" : {
                  "_tier_preference" : "data_content"
                }
              }
            },
            "number_of_shards" : "1",
            "provided_name" : "my-index-000001",
            "creation_date" : "1644601309989",
            "number_of_replicas" : "1",
            "uuid" : "9m19TP4DRsevoKkSG3DC0g",
            "version" : {
              "created" : "8020099"
            }
          }
        },
        "mappings" : "XinOY78Sl3l55aaFJrhIKDlniKVodszNHRmKhONrR/o=",
```

and then mappings at the same level as "indices":

```json
  "mappings" : {
      "5jySc/VOXLKC1itGKeilXwF6kCFL0i5Xe0DqJ0eDgwk=" : {
        "dynamic" : "strict",
        "_meta" : {
          "version" : "8.2.0"
        },
        "properties" : {
          "chunk" : {
            "type" : "integer"
          },
          "data" : {
            "type" : "binary"
          },
          "name" : {
            "type" : "keyword"
          }
        }
      },
      "XinOY78Sl3l55aaFJrhIKDlniKVodszNHRmKhONrR/o=" : {
        "properties" : {
          "@timestamp" : {
            "type" : "date"
          },
          "message" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "user" : {
            "properties" : {
              "id" : {
                "type" : "text",
                "fields" : {
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 256
                  }
                }
              }
            }
          }
        }
      }
    }
```

2022-02-11 18:04 UTC, elasticmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2022-02-11 18:04 UTC, elasticsearchmachine commented
Hi @original-brownbear, I've created a changelog YAML for you.

2022-02-14 07:59 UTC, idegtiarenko approved these changes

2022-02-14 08:31 UTC, DaveCTurner requested changes
Generally +1 from me but we still need to consider whether to treat this as a breaking change or not. We could alternatively _not_ change the default but start sending 429s to clients that request an unreasonably large response. Marking this as `Request changes` until these questions are resolved.

2022-02-24 12:31 UTC, henningandersen reviewed
Preparing for our discussion today, I read through this and provided a couple of comments.

2022-02-24 12:31 UTC, henningandersen commented on server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
> +                        builder.field(KEY_MAPPINGS, indexMetadata.mapping().getSha256());
I would prefer to pick a new name for the SHA256. `mappings_sha256` maybe or perhaps `shared_mappings_id`. Then we can also allow dumping both, which could provide a transitional path for clients.

2022-02-24 12:31 UTC, henningandersen commented on server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
> +                    builder.startObject("mappings");
Perhaps we can call this `shared_mappings` and then have a flag of the same name to the API as well as a cluster setting to disable dumping non-shared mappings?

2022-08-18 10:04 UTC, DaveCTurner reviewed
Henning and I discussed this again today. We're not confident enough that nobody would be affected by this change in the default behaviour, and we think with chunked-encoding we can protect Elasticsearch against harm at least, so we would prefer to make the desired behaviour opt-in today, deprecate the old default, and remove it in the next major version.

I'll raise a proposal to do this with the breaking changes committee.

2025-11-28 17:57 UTC, closed without merging

2026-01-08 23:17 UTC, pickypg commented
I see that this was closed because it lacked consensus on the breaking change. Why not take this in steps:

1. Add this as a feature behind a flag that can be opted into
2. In the next major (or at some arbitrary point where we agree the breaking change is worthwhile), make it the default

What do you think?