[DOCS] Re-add note about WKT and GeoJSON vertex order
elastic/elasticsearch pull request #84025
Opened 2022-02-16 13:04 UTC by jrodewig

Re-adds a note about WKT and GeoJSON vertex order to the polygon orientation docs.

This note was unintentionally removed as part of https://github.com/elastic/elasticsearch/pull/75888.

2022-02-16 13:37 UTC, elasticmachine commented
Pinging @elastic/es-docs (Team:Docs)

2022-02-16 13:37 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo (Team:Analytics)

2022-02-16 19:40 UTC, jrodewig commented
Thanks for the clarification @iverase. Rather than re-add the previous note as-is, I reworked the current polygon orientation docs to include the relevant content. Let me know what you think.

2022-02-17 08:07 UTC, iverase requested changes
We need to do just a small correction.

While we are here, should we update the Geojson examples so the types are properly capitalise? 

Check it here: https://en.wikipedia.org/wiki/GeoJSON

2022-02-17 08:07 UTC, iverase commented on docs/reference/mapping/types/geo-shape.asciidoc
> +document-level `orientation` parameter. For example, the following indexing
I don't think this is true for WKT as you cannot add a document level orientation, that's the reason you need to do it in the mapping. 

For GeoJson it os done as shown in the example

2022-02-17 14:56 UTC, iverase approved these changes
Thanks for your patience @jrodewig!

2022-02-17 14:59 UTC, jrodewig commented
Thanks @iverase!

2022-02-17 15:33 UTC, merged

2022-02-17 15:35 UTC, jrodewig commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.1|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/84130">](https://github.com/elastic/elasticsearch/pull/84130)|
|✅|8.0|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/84131">](https://github.com/elastic/elasticsearch/pull/84131)|
|✅|7.17|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/84132">](https://github.com/elastic/elasticsearch/pull/84132)|
|✅|7.16|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/84133">](https://github.com/elastic/elasticsearch/pull/84133)|
|✅|7.15|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/84134">](https://github.com/elastic/elasticsearch/pull/84134)|
|✅|7.14|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/84135">](https://github.com/elastic/elasticsearch/pull/84135)|


### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
<!--- Backport version: 7.0.1 -->