Remove LegacyCTRAListener from MetadataUpdateSettingsService
elastic/elasticsearch pull request #84985
Opened 2022-03-15 12:55 UTC by arteam

See #83784

2022-03-15 12:55 UTC, elasticmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2022-03-15 13:04 UTC, DaveCTurner requested changes
I would prefer we clean up this class's task/executor as part of this change, bring it more in line with how we think these things should be implemented. That's really the purpose of the `LegacyClusterTaskResultActionListener` marker.

 E.g. the task itself should mostly just be data (typically a `record`, and definitely not a subclass of `AckedClusterStateUpdateTask`) and the execution logic moved to the executor.

Ideally we'd not build a new cluster state each time round the loop too, although I tried that with this task and it seemed pretty tricky because of how we update the `Metadata.Builder`  before we've finished doing all the validation steps. I can live without that change here, but we should definitely do more cleanup than just this one thing.

2022-03-15 14:54 UTC, arteam commented
@elasticmachine update branch

2022-03-16 11:05 UTC, arteam commented
@elasticmachine run elasticsearch-ci/bwc

2022-03-16 12:13 UTC, arteam commented
@elasticmachine update branch

2022-03-16 15:15 UTC, DaveCTurner reviewed
Looks good.

I now realise that we didn't add tests when we made this API implement batching. I expect any problems would trip something somewhere but it would be good to have a test suite that focusses on this. See `MetadataIndexStateServiceBatchingTests` for some ideas about how to write this kind of test.

2022-03-16 15:15 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpdateSettingsService.java
> +            listener.onResponse(AcknowledgedResponse.of(false));
Just realised we have constants for these things:

```suggestion
            listener.onResponse(AcknowledgedResponse.FALSE);
```

2022-03-16 15:15 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpdateSettingsService.java
> +            listener.onResponse(AcknowledgedResponse.of(true));
```suggestion
            listener.onResponse(AcknowledgedResponse.TRUE);
```

2022-03-16 15:15 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpdateSettingsService.java
> +        ActionListener<AcknowledgedResponse> actionListener = wrapPreservingContext(listener, threadPool.getThreadContext());
Hmm I think this wrapping is very old and hasn't been necessary for ages. Could you add an `ESSingleNodeTestCase` test which sets up a thread context, calls the update settings API, and asserts that the context is passed through to the listener (even without this wrapping). See e.g. how `MasterServiceTests#testTaskFailureNotification` interacts with the thread context.

2022-05-16 13:27 UTC, closed without merging