Upgrade to JDK 18.0.0+36
elastic/elasticsearch pull request #85376
Opened 2022-03-28 07:59 UTC by pugnascotia

Upgrade to the latest Adoptium JDK for bundling with Elasticsearch.

2022-03-28 07:59 UTC, elasticmachine commented
Pinging @elastic/es-delivery (Team:Delivery)

2022-03-28 07:59 UTC, elasticsearchmachine commented
Hi @pugnascotia, I've created a changelog YAML for you.

2022-03-28 08:00 UTC, elasticsearchmachine commented
Hi @pugnascotia, I've updated the changelog YAML for you.

2022-04-13 15:38 UTC, pugnascotia commented on build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/JdkDownloadPlugin.java
> +                artifactPattern = "jdk-"
@mark-vieira there appears to have been a change since 18 in the binary URL, which this change addresses.

2022-04-13 15:40 UTC, mark-vieira requested changes

2022-04-13 15:40 UTC, mark-vieira commented on build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/JdkDownloadPlugin.java
> +                    + jdk.getMajor()
I think we don't need this, instead just definte the version in `version.properties` as `18+36` instead.

2022-04-13 15:42 UTC, mark-vieira commented on build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/JdkDownloadPlugin.java
> +                    + jdk.getMajor()
Going back and checking this is the pattern they use. For initial new major versions they omit the minor.patch bits for some odd reason.

2022-04-13 15:51 UTC, pugnascotia commented on build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/JdkDownloadPlugin.java
> +                    + jdk.getMajor()
Ha, it didn't occur to me to remove the `.0.0` bit 😅

2022-04-13 15:58 UTC, mark-vieira approved these changes
👍

2022-04-13 16:48 UTC, merged

2022-04-13 16:49 UTC, elasticsearchmachine commented
## 💚 Backport successful
| Status | Branch | Result |
|:------:|:------:|:------:|
| ✅ |  [8.2](https://github.com/elastic/elasticsearch/pull/85875)  | [<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/85875">](https://github.com/elastic/elasticsearch/pull/85875) |

2022-04-13 17:29 UTC, mark-vieira commented
@pugnascotia this should be backported to 8.1 and 7.17 as well.

2022-04-14 08:01 UTC, pugnascotia commented
Backported to `7.17` and `8.1` as well.

2022-04-14 08:08 UTC, pugnascotia commented
Note that this probably won't make it into `7.17.3`, so I removed the label.

2022-04-14 15:35 UTC, mark-vieira commented
> Note that this probably won't make it into 7.17.3, so I removed the label.

This is generally unnecessary as it's part of the release process to migrate labels for any PRs merged after the BC commit. This _will_ be in 7.17.4 and now there's no record of that.

2022-04-14 15:37 UTC, pugnascotia commented
Added v7.17.4.

2022-04-19 08:36 UTC, pugnascotia commented
We had to respin 7.17.3, so that now includes this PR.