Wait for tasks to finish
elastic/elasticsearch pull request #85683
Opened 2022-04-04 17:28 UTC by joegallo

We've seen a number of tests that fail because they expect there to be zero indices or shards in the cluster, but instead there is actually a `.tasks` index. We were never able to reproduce these failures on demand, and our theory was that there's some random internal cluster task that happens from time to time and that you had to win the unlucky test lottery for that task to happen at the right moment for one of these tests to catch it in the act and fail.

[That theory does not hold water.](https://www.youtube.com/watch?v=c0aU77BxdZE)

We're not getting unlucky and having a random cluster task happen, **rather** we're getting unlucky in the order in which the tests are executed and following a specific test:

```
[2022-04-04T11:15:04,954][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] There are still tasks running after this test that might break subsequent tests [indices:admin/auto_create, indices:admin/forcemerge, indices:data/write/index, internal:cluster/shard/started].
[2022-04-04T11:15:04,954][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=indices.forcemerge/10_basic/Force merge with wait_for_completion parameter] after test
[2022-04-04T11:15:05,008][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=nodes.stats/11_indices_metrics/Metric - blank for indices shard_stats] before test
[2022-04-04T11:15:05,028][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] Stash dump on test failure [{
[...]
```

It is random, because the order of the tests are random and also the timing is (somewhat) random. In order to fail, these tests that care about the number of indices or shards need to follow a test that leaks a task and it turns out that that test is `indices.forcemerge/10_basic/Force merge with wait_for_completion parameter`. See the following snippets from the full raw log of the associated test failures: https://github.com/elastic/elasticsearch/issues/83190#issuecomment-1087639207, https://github.com/elastic/elasticsearch/issues/83256#issuecomment-1087628037,  https://github.com/elastic/elasticsearch/issues/84975#issuecomment-1087628107, https://github.com/elastic/elasticsearch/issues/85670#issuecomment-1087627985. 

My first commit puts one of these failing tests right next to the problematic task-leaking test so that we can reproduce the failure reliably -- I got about 10 failures in 100 runs. My second commit adds a new arity of `waitForPendingTasks` and calls it from `cleanUpCluster`, with this commit in place, I was not able to reproduce the expected failure in 100 attempts. My last commit reverts the first commit.

Closes https://github.com/elastic/elasticsearch/issues/83190
Closes https://github.com/elastic/elasticsearch/issues/83256
Closes https://github.com/elastic/elasticsearch/issues/84975
Closes https://github.com/elastic/elasticsearch/issues/85670

2022-04-04 17:28 UTC, elasticmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2022-04-04 17:30 UTC, nik9000 commented
> Closes #83190
> Closes #83256
> Closes #84975
> Closes #85670

Heroic

2022-04-04 17:56 UTC, elasticmachine commented
Pinging @elastic/clients-team (Team:Clients)

2022-04-04 18:29 UTC, nik9000 approved these changes

2022-04-04 18:29 UTC, nik9000 commented
> ** [nik9000](/nik9000) ** approved these changes [ 11 minutes ago ](#pullrequestreview-930792388)

There are a lot of failing tests though! Hmmmm.

2022-04-04 18:32 UTC, nik9000 commented
> There are a lot of failing tests though! Hmmmm.

Those are real failures caused by this change. I think in the short term we might should ignore those tasks. But in the long term maybe we should shut down the things running them properly.

2022-04-04 18:35 UTC, nik9000 requested changes
Revoking my approval pending figuring out the sneaky failures in xpack. I don't know how to do that to be honest.

2022-04-04 19:14 UTC, joegallo commented
+1, I have a different approach in mind that limits the scope of the change and should still solve the problem (hopefully).

2022-04-04 20:53 UTC, joegallo commented
Rather than changing the cluster clean up logic for all tests, I’ve just made it so this one test doesn’t leak a task.

2022-04-04 21:03 UTC, nik9000 approved these changes
LGTM

I think it could be nice to assert that not tasks leak. But that's a bigger change. Are you willing to try and wrestle than one in later?

2022-04-04 21:03 UTC, nik9000 commented
> not tasks leak.

Or "only a specific list of tasks leak"

2022-04-04 21:25 UTC, joegallo commented
++, I see the value of that -- this fixes a subset of the problem, specifically the subset that was causing a problem for some of the data management tests, but the overall class of problems is still unsolved and it would be good to make sure that all tests in general are clean in that way. I'll a file a ticket and see if I can do some broad categorization.

2022-04-04 21:26 UTC, merged

2022-04-05 14:29 UTC, joegallo commented
> Are you willing to try and wrestle than one in later?

I filed https://github.com/elastic/elasticsearch/issues/85700 and I'll do the rounds to try to get some traction on it.