speed up ip v4 parser
elastic/elasticsearch pull request #86253
Opened 2022-04-28 08:51 UTC by idegtiarenko

Current implementation is using String#split that internally allocate
ArrayList that is later copied into array. It is possible to speed up
parser implementation by avoiding this extra allocations as we know
result array should have exactly 4 items in it.

```
Benchmark                         (ip)         Mode  Cnt    Score   Error  Units
InetAddressesBenchmark. current   192.168.0.1  avgt    5  146.564 ± 6.164  ns/op
InetAddressesBenchmark. new       192.168.0.1  avgt    5   29.605 ± 1.845  ns/op
```

This change is ported from a space time project focused on optimizing document parsing: https://github.com/elastic/elasticsearch/pull/85714

2022-04-28 08:51 UTC, elasticmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2022-04-28 08:51 UTC, elasticmachine commented
Pinging @elastic/es-core-infra (Team:Core/Infra)

2022-04-28 08:51 UTC, elasticsearchmachine commented
Hi @idegtiarenko, I've created a changelog YAML for you.

2022-04-29 04:47 UTC, rjernst requested changes
The change looks good, but I'm not sure there is complete test coverage for the edge cases in InetAddressesTests. Can you make sure all of these exist like empty octet, wrong number of octets, too large number, etc?

2022-04-29 06:21 UTC, idegtiarenko commented
Hello @rjernst , yes this was already very well covered by tests: https://github.com/elastic/elasticsearch/blob/92e8ba2e744568389d128136d4f55929fbd8cdbe/server/src/test/java/org/elasticsearch/common/network/InetAddressesTests.java#L33-L94

2022-04-29 14:04 UTC, rjernst approved these changes
Great, thanks! LGTM

2022-05-02 06:38 UTC, merged