[Test] Increase timeout.response setting to 10s to avoid test failures
elastic/elasticsearch pull request #87208
Opened 2022-05-30 10:51 UTC by slobodanadamovic

By default, [LDAP](https://www.elastic.co/guide/en/elasticsearch/reference/8.2/security-settings.html#ref-ldap-settings) and [Active Directory](https://www.elastic.co/guide/en/elasticsearch/reference/8.2/security-settings.html#ref-ad-settings)'s `timeout.response` is set to 5s.
This seems not to be enough when running AD and LDAP integration tests. 
Tests occasionally fail with `LDAPException`:
```
com.unboundid.ldap.sdk.LDAPException: A client-side timeout was encountered while waiting 5005ms for a response
 ```

Closes #86958

2022-05-30 10:51 UTC, elasticmachine commented
Pinging @elastic/es-security (Team:Security)

2022-06-08 02:18 UTC, ywangd requested changes
I believe the `ldapConnectoin` is created at

https://github.com/elastic/elasticsearch/blob/f615744512b0e90dbb019670a68848e7499ff47a/x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/GroupsResolverTestCase.java#L58

which means the new setting value should be set here

https://github.com/elastic/elasticsearch/blob/f615744512b0e90dbb019670a68848e7499ff47a/x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/LdapTestUtils.java#L52

In production code, the setting would be added under realmConfig like you did. But this test suite is not integration test and it does not go through the full realm config path.

2022-06-08 08:00 UTC, slobodanadamovic commented
> https://github.com/elastic/elasticsearch/blob/f615744512b0e90dbb019670a68848e7499ff47a/x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/LdapTestUtils.java#L52
> 
> In production code, the setting would be added under realmConfig like you did. But this test suite is not integration test and it does not go through the full realm config path.

You are absolutely right. I missed this completely. I was a bit misled by the ability to configure settings.
Thank you for catching this. I will make the suggested change.

2022-06-08 11:27 UTC, ywangd approved these changes
LGTM

2022-06-08 12:40 UTC, merged

2022-06-28 09:50 UTC, slobodanadamovic commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.3|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/88119">](https://github.com/elastic/elasticsearch/pull/88119)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.4.2 -->