Make the metric in the buckets_path parameter optional
elastic/elasticsearch pull request #87220
Opened 2022-05-30 14:51 UTC by salvatore-campagna

With this change the metric field name becomes optional if the
`bukets_path` is pointing to a multi-value aggregation with a single
metric field. Normally the full path would be required including
the aggregation name followed by the metric field.

If the metric is no specified in the path and the multi-value
aggregation computes more than one value an error is thrown.

The old notation is still supported for backward compatibility in case
the full path is specified and the target multi-value aggregation
computes a single value.

This addresses issue #72983.

2022-05-30 14:51 UTC, elasticmachine commented
Pinging @elastic/es-analytics-geo (Team:Analytics)

2022-05-30 14:52 UTC, elasticsearchmachine commented
Hi @salvatore-campagna, I've created a changelog YAML for you.

2022-05-31 09:48 UTC, salvatore-campagna commented
@not-napoleon According to my understanding those aggregations are the only ones where we can apply this kind of "shortcut" for the path. That is because they return an array as a result and specifying a metric might not be necessary. For those which return an object (like for instance extended stats) we still need the full path.

2022-05-31 18:26 UTC, elasticmachine commented
Pinging @elastic/clients-team (Team:Clients)

2022-06-03 14:35 UTC, not-napoleon requested changes
The yaml tests are good, but I'd like to see some java tests as well.  As noted, I'd like to confirm that putting a nonsense name in the last position fails.  I'd also like to test that if your percentile has e.g. 99 and you ask for 95, that fails correctly.  I think it will, but let's make sure we have a test.

Also, just as a note, if instead of "addresses issue #..." you say "resolves #...", github will automatically close the issue when the PR is merged.

2022-06-06 14:19 UTC, salvatore-campagna commented on server/src/main/java/org/elasticsearch/search/aggregations/metrics/AbstractInternalHDRPercentiles.java
> +            return value(Double.parseDouble(name));
Correct...I didn't realise we can just compare the name (parameter) to the aggregation name 🤦

2022-06-06 16:21 UTC, salvatore-campagna commented
@elasticmachine update branch

2022-06-06 16:48 UTC, salvatore-campagna commented
@elasticmachine update branch

2022-06-07 12:58 UTC, not-napoleon approved these changes
LGTM, thanks for addressing the changes.

2022-06-08 08:44 UTC, merged