[DOCS] Remove the sentence on deleting document in .tasks
elastic/elasticsearch pull request #87310
Opened 2022-06-02 03:13 UTC by Leaf-Lin

Before 8.0, one should run`DELETE .tasks/_doc/<node_id>:<task_id>` to reclaim the space. 
e restriction on system indices are tightened since 8.0, deleting old documents from `.tasks` is no longer possible. See 
https://github.com/elastic/elasticsearch/issues/77383

This PR only updates the documentation by removing the following sentence to avoid confusion, the automatic mechanism is still to be implemented.
~When you are done with a task, you should delete the task document so Elasticsearch can reclaim the space.~

2022-06-02 03:13 UTC, elasticmachine commented
Pinging @elastic/es-docs (Team:Docs)

2022-12-07 16:38 UTC, idegtiarenko commented on docs/reference/docs/reindex.asciidoc
> -{es} can reclaim the space.
Looks like the same sentence is present in `docs/reference/docs/update-by-query.asciidoc#L102-L103` should it be rmeoved as well?

2022-12-07 16:38 UTC, idegtiarenko approved these changes
Should somebody from docs approve as well?

2022-12-08 09:22 UTC, abdonpijpelink requested changes
LGTM. Let's also fix update-by-query.asciidoc before we merge this PR. The docs team can help with that.

2022-12-08 11:40 UTC, abdonpijpelink approved these changes

2022-12-12 09:06 UTC, merged