Add rollover permissions for remote_monitoring_agent
elastic/elasticsearch pull request #87717
Opened 2022-06-16 07:19 UTC by matschaffer

Fixes https://github.com/elastic/elasticsearch/issues/84161

2022-06-16 07:19 UTC, elasticmachine commented
Pinging @elastic/es-security (Team:Security)

2022-06-16 07:20 UTC, elasticsearchmachine commented
Hi @matschaffer, I've created a changelog YAML for you.

2022-06-17 05:38 UTC, matschaffer commented
retest

2022-06-17 07:19 UTC, ywangd requested changes
Can we add a test for the change please? It can be just a single assertion statement somewhere in this method:
https://github.com/elastic/elasticsearch/blob/4cd2fe0216668e611b8760adc284aff4ae05001d/x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStoreTests.java#L1292

Also, can we please have a more informational description instead of just "Fixes xxx"? The description most likely ends up to be the commit message. It would be nice if people can get basic context about the change by browsing through the git history without having to check the issue separately.

2022-06-17 08:30 UTC, ywangd approved these changes
LGTM

2022-06-20 16:25 UTC, klacabane commented
Works like a charm

```
http.enabled: true
http.port: 5066

metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts: [ "localhost:9200" ]
    username: "remote_monitoring_user"
    password: "changeme"

output.elasticsearch:
  hosts: [ "localhost:9200" ]
  username: "remote_monitoring_user"
  password: "changeme"
  allow_older_versions: true
```

```
[18:21:42] metricbeat git:(main*) $ curl -s -u elastic:changeme localhost:9200/_data_stream/metricbeat-'*' | jq '.data_streams | .[].indices'
[
  {
    "index_name": ".ds-metricbeat-8.4.0-2022.06.20-000001",
    "index_uuid": "oTgNhG57SgqTUkxgfY0G9A"
  },
  {
    "index_name": ".ds-metricbeat-8.4.0-2022.06.20-000002",
    "index_uuid": "-kqc8eMbRziQsH52TqGVOw"
  }
]
```

2022-06-20 16:26 UTC, klacabane approved these changes

2022-06-20 21:34 UTC, merged

2022-06-20 21:35 UTC, matschaffer commented
Thanks for the thorough review @klacabane !

2023-02-14 13:47 UTC, raulk89 commented
When this will be fixed.
I am on 8.6.0 (metricbeat-8.6.0-1.x86_64), and I have the same error:

`[2023-02-14T15:31:17,836][ERROR][o.e.x.i.IndexLifecycleRunner] [xxxxxxxx] policy [metricbeat] for index [.ds-metricbeat-8.5.2-2023.01.12-000001] failed on step [{"phase":"hot","action":"rollover","name":"set-indexing-complete"}]. Moving to ERROR step

Raul

`

2023-02-16 05:34 UTC, ywangd commented
The error for a different action `indices:admin/settings/update` than the one reported in the original issue `indices:admin/rollover`. @matschaffer Has there been any changes to metricbeat that would lead to it perform the UpdateIndexSettings action? It does not seem to be an issue in earlier versions?

@raulk89 Would you be able to provide the steps for reproduction? They would help us tracking down the issue quicker. Thanks!

2023-02-16 07:26 UTC, ywangd commented
@klacabane Would you be able to take a look from the metricbeat side? Sorry I just realised that Mat is not available.

2023-02-16 07:58 UTC, raulk89 commented
> @raulk89 Would you be able to provide the steps for reproduction? They would help us tracking down the issue quicker. Thanks!

The issue happens for me in every 10 minutes time. I do not know how I can reproduce it. Elastic is internally trying to do this every 10 minutes time. If you could give some hints, I can work with you on that issue.

Raul

2023-09-20 11:34 UTC, abitmore commented
Hi, can this be backported to ES 7?
Thanks.