Fixing a bug in testYellowWithTooManyMasterChanges
elastic/elasticsearch pull request #87865
Opened 2022-06-20 21:33 UTC by masseyke

After calling `heal()` on a node we were not doing anything to actually have it join the new master. So it would never receive a clusterChanged event with that new master. So its master history would be missing an entry. This means that sometimes it would appear that the master history was more stable than it really was, causing the stable_master status to be GREEN rather than yellow.
Closes #87768

2022-06-20 22:51 UTC, elasticmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2022-06-22 07:36 UTC, gmarouli approved these changes
LGTM, given the conflicts are resolved of course.

2022-06-22 07:49 UTC, DaveCTurner requested changes
I think it should be sufficient to call `stabilise` once after the loop, rather than calling it twice on each iteration as suggested here.

2022-06-22 16:52 UTC, DaveCTurner commented
I think you get that guarantee with just one final `stabilise()` call too:

```
leader1.disconnect()
stabilise() // guaranteed to choose a leader other than leader1 - call them leader2
leader1.heal()
leader2.disconnect()
stabilise() // guaranteed to choose a leader other than leader2 - call them leader3
leader2.heal()
⋮
leaderN.disconnect()
stabilise() // guaranteed to choose a leader other than leaderN
leaderN.heal()
// exit loop
stabilise() // bring leaderN back into the cluster
```

2022-06-22 16:55 UTC, DaveCTurner approved these changes
LGTM

2022-06-22 17:41 UTC, merged