Creating a transport action for the CoordinationDiagnosticsService
elastic/elasticsearch pull request #87984
Opened 2022-06-23 17:59 UTC by masseyke

This exposes the CoordinationDiagnosticsService (#87672) through a transport action so that it can be called remotely as
part of the health API in the event that: (1) there has been no master recently, (2) there are master-eligible nodes in the cluster, (3) none are elected, and (4) the current node is not master eligible. In the diagram below, this action will be used in the 1.2.2.3 branch (it is the long arrow back to branch 1). The logic that actually uses it will be within the CoordinationDiagnosticsService, and will be in a follow-up PR. Requests for this action will be sent directly to the remote node, and the assumption is that the cluster that likely does not have a master node.
![2022-04-18 Coordination health](https://user-images.githubusercontent.com/453603/175367360-a5cc7f80-ac1c-4266-8102-7c25665c473b.png)

2022-06-23 17:59 UTC, elasticsearchmachine commented
Hi @masseyke, I've created a changelog YAML for you.

2022-06-23 18:29 UTC, elasticmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2022-06-24 14:53 UTC, masseyke commented
@elasticmachine update branch

2022-06-28 09:24 UTC, andreidan requested changes
Thanks for adding this Keith.
Left a few suggestions

2022-06-28 09:24 UTC, andreidan commented on server/src/main/java/org/elasticsearch/action/admin/cluster/coordination/CoordinationDiagnosticsAction.java
> +     * This transport action calls the CoordinationDiagnosticsService on a remote node.
nit: This doc is rather misleading to me. The transport action exposes the functionality via the transport service (as opposed to calling a service on a remote node)

2022-06-28 14:39 UTC, masseyke commented on server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationDiagnosticsService.java
> +        private final byte value;
Huh. Somehow I didn't realize that those methods existed. Switching to use them now.

2022-06-28 14:46 UTC, masseyke commented on server/src/main/java/org/elasticsearch/action/admin/cluster/coordination/CoordinationDiagnosticsAction.java
> +                    new CoordinationDiagnosticsService(clusterService, coordinator, masterHistoryService).diagnoseMasterStability(
Yeah I think you're right -- I don't think there would be any thread-safety problems.

2022-06-28 14:50 UTC, masseyke commented on server/src/main/java/org/elasticsearch/action/admin/cluster/coordination/CoordinationDiagnosticsAction.java
> +                    new CoordinationDiagnosticsService(clusterService, coordinator, masterHistoryService).diagnoseMasterStability(
And on second look, I'm not sure why I wasn't injecting that in the first place.

2022-06-28 16:05 UTC, masseyke commented
@elasticmachine update branch

2022-06-29 14:00 UTC, andreidan approved these changes
LGTM, thanks for iterating on this Keith

Left a minor suggestion

2022-06-29 14:48 UTC, masseyke commented on server/src/main/java/org/elasticsearch/action/admin/cluster/coordination/CoordinationDiagnosticsAction.java
> +            listener.onResponse(new Response(coordinationDiagnosticsService.diagnoseMasterStability(request.explain)));
I think that's already handled for us in the parent class here right? https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/support/TransportAction.java#L79. I'll confirm that that is where it is called from.

2022-06-29 15:30 UTC, merged

2022-06-29 18:43 UTC, andreidan commented on server/src/main/java/org/elasticsearch/action/admin/cluster/coordination/CoordinationDiagnosticsAction.java
> +            listener.onResponse(new Response(coordinationDiagnosticsService.diagnoseMasterStability(request.explain)));
Ah you're right. TIL. Thanks for looking into this!