Delay task execution in AutoCreateAction untill reroute is complete
elastic/elasticsearch pull request #88648
Opened 2022-07-20 14:07 UTC by idegtiarenko

Related to: https://github.com/elastic/elasticsearch/issues/88647

2022-07-22 10:57 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2022-07-25 09:03 UTC, idegtiarenko commented
There are couple new test failures. I checked and they also fail on the feature branch. I added them to the list: https://github.com/elastic/elasticsearch/issues/86429

2022-07-25 10:30 UTC, DaveCTurner requested changes
Implementation looks good, I left a request for another test.

2022-07-25 10:30 UTC, DaveCTurner commented on server/src/test/java/org/elasticsearch/cluster/routing/allocation/allocator/AllocationActionMultiListenerTests.java
> +public class AllocationActionMultiListenerTests extends ESTestCase {
I think we should have a test that verifies it works correctly (e.g. no lost acks) when accessed from multiple threads too.

2022-07-25 13:00 UTC, DaveCTurner commented on rest-api-spec/build.gradle
> +  task.skipTest("indices.shrink/30_copy_settings/Copy settings during shrink index", "https://github.com/elastic/elasticsearch/issues/86429")
Was it a `rest-compatibility` job that was failing? This job runs the 7.17 test suite against these 8.x nodes, so muting tests in the 8.x test suite does nothing.

2022-07-25 13:15 UTC, idegtiarenko commented on rest-api-spec/build.gradle
> +  task.skipTest("indices.shrink/30_copy_settings/Copy settings during shrink index", "https://github.com/elastic/elasticsearch/issues/86429")
Yeah, it looks like that:

`./gradlew ':rest-api-spec:yamlRestTestV7CompatTest' --tests "org.elasticsearch.test.rest.ClientYamlTestSuiteIT" -Dtests.method="test {yaml=indices.split/30_copy_settings/Copy settings during split index}"`

2022-07-25 13:43 UTC, DaveCTurner approved these changes
LGTM

2022-07-25 15:14 UTC, merged