Use threadpool instead of mock in some Repository tests
elastic/elasticsearch pull request #89089
Opened 2022-08-03 15:06 UTC by pxsalehi

2022-08-03 15:50 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2022-08-03 15:58 UTC, kingherc commented
Thanks for adding me :100: 

> Using mocks in this tests causes NPEs on https://github.com/elastic/elasticsearch/pull/88209.

Any idea why? Would improving the mocks behavior somehow solve it, rather than using actual thread pools (so it's closer to a unit testing rather than integration testing)?

But LGTM :+1:

2022-08-03 15:58 UTC, kingherc approved these changes

2022-08-03 16:00 UTC, DaveCTurner reviewed
Seems reasonable, but this does make these tests multithreaded (potentially nondeterministic) now, and also a full `ThreadPool` is a pretty heavyweight thing.

 Does it work instead to create a `new DeterministicTaskQueue()` and then use its `getThreadPool()` method to get a deterministic single-threaded threadpool instead? That might require some test changes since you have to tell it to run the enqueued tasks at specific points.

2022-08-03 16:01 UTC, DaveCTurner requested changes
Going to call my previous comment "request changes" for now.

2022-08-03 16:08 UTC, kingherc commented
Ah didn't think so far @DaveCTurner , nice!

2022-08-03 16:19 UTC, DaveCTurner commented
Alternatively you could make a non-forking non-deferring threadpool mock like in `BlobStoreTestUtil#mockClusterService`. Or even a real object that does the same thing, if you think it's useful.

2022-08-04 09:58 UTC, pxsalehi commented
The threadpool is not used at all in those tests, so there are no behaviour changes. But it definitely is too heavy just for that. What is happening in `BlobStoreTestUtil#mockClusterService` is anyway a bit more mocking. I'll do that in my PR as well. I'll close this PR then. Thanks!

2022-08-04 09:58 UTC, closed without merging