Fix assertion for single-node cluster and periodic warning w/ seed hosts
elastic/elasticsearch pull request #89828
Opened 2022-09-06 16:07 UTC by tlrx

The test CoordinatorTests.testDoesNotPerformElectionWhenRestartingFollower
failed for a 2 nodes cluster after a follower node is restarted (the last
accepted cluster state has 1 node but no periodic checker, which looks OK
to me).

This commit changes the assertion to check the existence of the periodic
checker only when seed hosts have been configured.

Closes #89543

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2022-09-06 16:07 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2022-09-06 16:19 UTC, kingherc requested changes
> the last accepted cluster state has 1 node but no periodic checker, which looks OK to me

Hi @tlrx , this is weird. If the node is becoming a leader, we have the following code at the end of `becomeLeader()`:

```
        if (applierState.nodes().size() > 1) {
            cancelSingleNodeClusterChecker();
        } else if (singleNodeClusterChecker == null) {
            singleNodeClusterChecker = transportService.getThreadPool()
                .scheduleWithFixedDelay(() -> { checkSingleNodeCluster(); }, this.singleNodeClusterSeedHostsCheckInterval, Names.SAME);
        }
```

So I wonder why the invariant fails? It does not have to do with the settings (the settings are checked inside the checker function).

We may need to take a deeper look at the test failure to understand why it was null.

2022-09-06 18:46 UTC, kingherc commented
Hi @tlrx , may I actually take over the issue and make a new PR? I understood what's wrong and I can fix it. The problem is that I introduce the checker only when a node is becoming a leader in a single-node cluster, but there's also the case (as it's shown by the test) that it can become single-node cluster when a node leaves a two-node cluster.

2022-09-07 07:38 UTC, tlrx commented
> So I wonder why the invariant fails?

The invariant fails because the cluster consists of two nodes (cancelling the single node cluster checker) and later a follower node leaves the cluster and joins back. After reading again #88013 this morning I understand that we should also emit a warning in this situation.

I only noticed yesterday that the failure was related to a test you wrote recently, otherwise I would have transferred the issue to you :) Feel free to close this one and open a better fix.

2022-09-07 10:32 UTC, kingherc commented
Thanks @tlrx will takeover then and make another PR. Indeed, I should re-introduce the check if it goes from 2 nodes to 1 node again.

2022-09-07 10:32 UTC, closed without merging