Add parameter object to Aggregator Test Case
elastic/elasticsearch pull request #90320
Opened 2022-09-23 20:26 UTC by not-napoleon

I apologize for the huge, largely automated, refactoring PR.  This extends the refactoring from #90149 by applying the same parameter object to `AggregatorTestCase#testCase`, and extending it to include that method's parameters, which allows removing some useless wrapper functions.  By being a bit more explicit about type parameters, I was also able to remove some useless casting.  This should make it easier to write tests and extend the testing framework going forward.

2022-09-23 20:27 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytics-geo (Team:Analytics)

2022-09-23 21:15 UTC, nik9000 requested changes

2022-09-23 21:15 UTC, nik9000 commented on test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java
> +            );
Does this work?
```
public <V> AggTestCase withVerifier(Consumer<V> verifier) {
  Consumer<InternalAggregation> = i -> verifier((V) i);
  new Agg.....
```

2022-09-29 15:36 UTC, not-napoleon commented
Upon reflection, this doesn't seem like it will be worth the work at this point.

2022-09-29 15:36 UTC, closed without merging