Batch snapshot create tasks
elastic/elasticsearch pull request #90332
Opened 2022-09-26 05:56 UTC by original-brownbear

WIP, a number of rough edges here still but once fixed this nicely lowers the overhead of ILM moves to frozen.

2023-01-03 09:21 UTC, elasticsearchmachine commented
Hi @original-brownbear, I've created a changelog YAML for you.

2023-01-03 09:23 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2023-01-09 12:17 UTC, DaveCTurner commented
I think this is ok but it'd help me to see the refactoring as a separate PR from the behaviour change. Could you split them up?

2023-02-22 15:08 UTC, original-brownbear commented
Exctracted the refactoring of the consistent state update into https://github.com/elastic/elasticsearch/pull/94020 now, that should make this a lot easier to read.

2023-02-22 16:21 UTC, idegtiarenko commented on server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
> +                .build();
NIT: could be simplified using `ClusterState#copyAndUpdateMetadata`

2023-02-22 16:22 UTC, idegtiarenko commented on server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java
> +    @AwaitsFix(bugUrl = "foo")
Is it still failing?

2023-02-22 18:45 UTC, original-brownbear commented
Jenkins run elasticsearch-ci/part-1

2023-02-23 10:01 UTC, original-brownbear commented on server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java
> +    @AwaitsFix(bugUrl = "foo")
Nah my bad :)

2023-02-23 10:46 UTC, idegtiarenko approved these changes
:+1: from my side, but I would like somebody else with better `ClusterStateTaskExecutor` knowledge to approve as well

2023-02-23 11:10 UTC, DaveCTurner requested changes
I would rather we didn't use mutable fields on the task to pass information from `execute()` to `clusterStateProcessed()`, and I'm also suspicious about passing `newState` into `clusterStateProcessed()` because this will be the _final_ state at the end of the batch, not the state after processing each item, and that tends to be a source of bugs.

2023-02-23 11:53 UTC, original-brownbear commented
> I'm also suspicious about passing newState into clusterStateProcessed() because this will be the final state at the end of the batch, not the state after processing each item, and that tends to be a source of bugs.

This is what we want. The implicit assumption in all of this code at the moment is that the callback sees the final version of the state and triggers the next action based on it.

 > I would rather we didn't use mutable fields on the task to pass information from execute() to clusterStateProcessed()

That's probably something that I can fix ... let me try :)

2023-02-23 12:02 UTC, original-brownbear commented
Ok nevermind.

> I would rather we didn't use mutable fields on the task to pass information from execute() to clusterStateProcessed()

This isn't so trivial to fix. For cloning in particular we'd have to make some bigger changes here from how things work today. Maybe just do that in a follow-up that removes the use of `ClusterState` returns from these tasks in general like the TODO I added suggests?
I really need different tasks to work without the mutable fields :)

2023-02-23 12:47 UTC, DaveCTurner reviewed
I'm not sure I see the particular difficulty with the clone operation, we just have to pass the `newEntry` down the line don't we?

Also I didn't see any places where we really need to see the final cluster state, at least not if we fix the information flow. We're pulling out the latest `SnapshotsInProgress` in some places, but I reckon this makes more sense at the batch level than in a handler on each individual task. The other things we use are stuff like `.metadata()` and `.nodes()` that won't be changing during these tasks.

2023-02-23 12:56 UTC, original-brownbear commented
> Also I didn't see any places where we really need to see the final cluster state, at least not if we fix the information flow.

I really fail to see the value of changing the mechanics here tbh. We do actions in the callback based on the final cluster state. If we start doing actions based on some intermediary state that resulted from just the single update, things just become incredibly hard to reason about.

> I'm not sure I see the particular difficulty with the clone operation, we just have to pass the newEntry down the line don't we?

Yea it's not hard but then I can't just reuse the tasks as is and must work this into the executor in some form by returning the entry from the task and setting it as the task result later. I can do that here, but that's gonna be more changes. And we do have a couple of these spots in two cloning updates, in the repo generation setting etc. making this a bit of a bigger PR which I tried to avoid.

2023-02-23 13:00 UTC, DaveCTurner commented
> If we start doing actions based on some intermediary state that resulted from just the single update, things just become incredibly hard to reason about.

Sorry, I wasn't clear. I'm ok with deciding what to do based on the final state, but we should make those decisions in the executor when it reaches the end of the batch, rather than doing it on a task-by-task basis as proposed here.

I think we can/should make these changes to each task separately first, and then this change to add batching will be trivial and obviously correct.

2023-02-23 17:51 UTC, original-brownbear commented
> I think we can/should make these changes to each task separately first, and then this change to add batching will be trivial and obviously correct.

Hmm and then add a new separate executor per task but not batch to begin with? This sounds like it'll turn into quite the project :) Let me try.

> Sorry, I wasn't clear. I'm ok with deciding what to do based on the final state, but we should make those decisions in the executor when it reaches the end of the batch, rather than doing it on a task-by-task basis as proposed here.

Seems to me that's almost just more code with the way things work currently. Yes if we refactored things nicely and wouldn't be generating a series of states it may be nice to just handle the callback logic in the executor. But as things are now and without bigger changes, it's really just an excercise in adding more explicit fields to the tasks so that the executor can then run the code we have in the callback at present?

2023-02-23 18:07 UTC, original-brownbear commented
Then again, seems like this PR just got nuked by the changes to task submitting to a good degree :( -> closing here for now, I'll see if I can find the time to revisit this step by step.

2023-02-23 18:27 UTC, DaveCTurner commented
Ah yeah sorry about that. It shouldn't be too much of a big deal to fix it up for those changes - I can do the master merge if you'd like.

2023-02-23 19:47 UTC, DaveCTurner commented
Ah ok I see yes it's a bit of a pain to share the queue across the repositories service and the snapshots service. I can hack something in I reckon but maybe this needs a bit more of a rethink.

2023-02-23 19:48 UTC, original-brownbear commented
Yea this was though as a quick win but yea this got too complicated now ... I'll try something smaller for the time being.

2023-02-23 19:48 UTC, closed without merging