EQL: Allow sample queries without a timestamp field
elastic/elasticsearch pull request #90629
Opened 2022-10-04 08:19 UTC by luigidellaquila

Sample queries do not rely on time sequences, so they don't need a timestamp field to execute.
Since Samples were implemented within current EQL framework, they inherited all the checks for the presence or a timestamp field in the target index(es), even though it was not actually used. 
This PR removes this limitation.

2022-10-04 09:06 UTC, elasticsearchmachine commented
Pinging @elastic/es-ql (Team:QL)

2022-10-04 09:10 UTC, luigidellaquila commented on x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java
> +                    filters.set(i, new KeyedFilter(k.source(), joinKeyNotNull, k.keys(), k.timestamp(), k.tiebreaker()));
this looks like an oversight in the original implementation, not specifically related to this fix (I just took the chance to fix it)

2022-10-04 10:59 UTC, astefan requested changes
I agree with the solution but not with the tests. Also, the solution is fixing the timestamp_field part, but extrapolating this a bit, it doesn't cover the tiebreaker field as well.

At the moment, a very similar test, but specifying a "tiebreaker_field" results in the same error as the one for the timestamp_field.

Removing the `date` fields from the sample*.data files is not actually testing the fix. To make it more diverse, instead, you could keep sample1 and sample2 as is and remove the timestamp fields from sample3. Still, this doesn't test the fix, but it makes the IT tests more complex.

To test the fix you could probably test the verifier outcome for timestamp_field and tiebreaker_field presence.

2022-10-04 11:02 UTC, astefan commented on x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plan/logical/KeyedFilter.java
> +        if (Expressions.isPresent(timestamp)) {
Add a comment here for the scenario when the timestamp is not actually present, even though is a required request parameter.
Also, adjust the class level comment of this class which says "Used inside Join or Sequence".

2022-10-05 11:24 UTC, luigidellaquila commented
Thanks for the comments @astefan, adding a few notes below:

> At the moment, a very similar test, but specifying a "tiebreaker_field" results in the same error as the one for the timestamp_field.

Not sure if this case should be considered a user mistake (explicitly specify a tiebreaker field that does not exist), but the fix is easy, so I added it as well.

> Removing the date fields from the sample*.data files is not actually testing the fix. To make it more diverse, instead, you could keep sample1 and sample2 as is and remove the timestamp fields from sample3. Still, this doesn't test the fix, but it makes the IT tests more complex.

It's the opposite actually: if *at least one* index has the `@timestamp` field, the query succeeds. The only way to make it fail is to remove it from *all* the indexes in the pattern.
I agree with you on the usefulness of a unit test for the verifier, I just added it

2022-10-05 11:26 UTC, astefan approved these changes
LGTM

2022-10-05 11:58 UTC, bpintea approved these changes
Lgtm.

2022-10-05 12:01 UTC, luigidellaquila commented
@elasticmachine run elasticsearch-ci/rest-compatibility

2022-10-05 13:40 UTC, merged