EQL Samples: add support for multiple samples per key
elastic/elasticsearch pull request #91783
Opened 2022-11-22 08:32 UTC by luigidellaquila

By default EQL Samples queries return only one sample per key.
With this PR we add a `max_samples_per_key` option allows to return multiple samples for the same key.

eg. 

```
  sample by os with max_samples_per_key=2
    [alert where true]
    [alert where true]
```

2022-11-24 15:03 UTC, elasticsearchmachine commented
Hi @luigidellaquila, I've created a changelog YAML for you.

2022-12-05 07:39 UTC, elasticsearchmachine commented
Pinging @elastic/es-ql (Team:QL)

2022-12-05 13:43 UTC, astefan requested changes
This type of characteristic/setting/query hint I don't think it fits the `with` construct in the language. On one hand, `with` is used in combination with `maxspan` indicating the period of time the events in a sequence should fit into.
`with` is also with `runs` being more like a syntactic sugar for repeating the same condition more times.

On the other hand, EQL has body parameters like `fetch_size` (a setting that's being used internally by the sequence algorithm), `result_position` (changes the default recency aspect of events - earlier or later events to return) and `size` (the maximum number of events or sequences to return).

From the two available options above (inside the language itself or inside the body of the request), I think `max_samples_per_key` fits better in the body of the request because it's an aspect of the query that is not influencing the way the query runs, but more how the results are returned.

2022-12-05 13:43 UTC, astefan commented on x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/sample/SampleIterator.java
> +        this.maxSamplesPerKey = maxSamplesPerKey;
After `circuitBreaker`, please. Keep the same order as the one of the constructor's arguments.

2022-12-06 09:04 UTC, luigidellaquila commented on x-pack/plugin/eql/qa/common/src/main/resources/data/sample-multi.data
> +    "os": "reahat",
Just a typo (copy-pasted), fixing it with next commit.

2022-12-06 10:21 UTC, astefan commented
> @astefan thank you very much for your feedback. I thought a bit about it, but I dont' think I completely agree with your conclusions. I'll leave my observations here for further discussion:
> 
> * `with` is the way we define extensions to the language, so it seems the natural way to proceed.

It's not an extension where we can simply pop things in whenever the language needs a feature or setting. The construct using `with` needs to have a meaning, to be consistent with the way the language "feels" and works. And, as I mentioned in my review, there are aspects that break the consistency of the language.

> * The request body is only for transport, it should not contain query logic (the query logic should be in the EQL query itself).
>   Parameters like `fetch_size` are internal and can be considered as tuning options, while `max_samples_per_key` defines a query criterion (should one sample be returned or not?), so it's strict business logic.

I don't find this argument strong enough tbh.
> `max_samples_per_key` defines a query criterion (should one sample be returned or not?)

A query criterion (at language level) refers to something else and this setting is not defining that.

> so it's strict business logic

So is `size` and it's a request body parameter.

> * The REST API is one possible protocol, but not necessarily the only one (think of Endgame EQL CLI, today it doesn't support these features, but in future it could).
>   The language should support the feature regardless of the protocol.

There are features and characteristics that are different in these languages and each of them is making the best to accommodate the missing functionality but the use cases and the technical differences between them (Endgame EQL deployed as an agent that acts on a smaller data set realtime, ES EQL using ES to search a far larger dataset) make this goal to be complex and sometimes impossible to fulfill.

> * Moreover, the request body is generic for all the EQL queries, while `max_samples_per_key` is specific for Samples.
>   If we add it to the body, we will have to ignore it or to explicitly check it for all the other queries (eg. sequences) and throw errors.

`fetch_size` is a similar setting only used for sequences.

> * From a usability point of view, I think it's easier to define the query logic in EQL directly. The JSON body is much closer to machine protocol, it should be manipulated by the user as little as possible.
> * In some contexts, the end user could just not have access to the request body. Eg. Kibana dashboards provide a simple text area to write plain EQL. In this context, the user won't be able to use this feature.

I agree this is more user-friendly to be part of the language, but at the same time the construct (as I mentioned previously) needs to make sense and to be consistent with the rest of the language.

2022-12-12 18:07 UTC, sodhikirti07 commented
@luigidellaquila In my opinion, keeping the `max_samples_per_key` under the body of the `sample` query makes more sense. 

> In some contexts, the end user could just not have access to the request body. Eg. Kibana dashboards provide a simple text area to write plain EQL. In this context, the user won't be able to use this feature.

To my knowledge, I've only seen EQL being used for detection-rules in Kibana. In that case, I don't think we would need to set this parameter as the alerts are governed by time intervals. So any alert under an interval of 5m (let's say) would  show up under the alerts page.

2022-12-13 13:12 UTC, luigidellaquila commented
@sodhikirti07 do you mean the body of the JSON, eg.  

```
{ 
   "max_samples_per_key":10, 
   "query": "sample [ ... ]"}
```

or in the query language, eg.

```
{ 
   "query": "sample with max_samples_per_key=10 [...]"}
```


Sorry, we had problems with names and definitions as well...

2022-12-13 17:26 UTC, sodhikirti07 commented
I would say the first one similar to what we do in case of `size`. 

```
{ 
   "max_samples_per_key":10, 
   "query": "sample [ ... ]"}
```

2022-12-15 08:19 UTC, luigidellaquila commented
@elasticmachine update branch

2022-12-15 10:33 UTC, luigidellaquila commented
@elasticmachine update branch

2022-12-15 11:26 UTC, luigidellaquila commented
@elasticmachine test this please

2022-12-16 14:06 UTC, astefan reviewed
Left a first series of comments.

2022-12-16 14:06 UTC, astefan commented on x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/execution/sample/SampleIteratorTests.java
> +            matchSamples(asList(asSearchHitsList(1, 2, 3), asSearchHitsList(1, 3, 4), asSearchHitsList(1, 3, 4)), 3, 3)
These two tests are not enough. Incrementally increase maxSamplesPerKey to the maximum possible value and test the combinations please.

2022-12-16 14:06 UTC, astefan commented on x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/optimizer/OptimizerTests.java
> +    private static Sample sample(int maxSamplesPerKey, LogicalPlan... rules) {
Leftover.

2022-12-16 14:06 UTC, astefan commented on x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/optimizer/OptimizerTests.java
> +        Sample sample = sample(randomIntBetween(1, 10), rule1, rule2);
Leftover

2022-12-16 14:06 UTC, astefan commented on x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/optimizer/OptimizerTests.java
> +        LogicalPlan plan = sample(randomIntBetween(1, 10), accept(q));
Leftover

2022-12-16 14:06 UTC, astefan commented on x-pack/plugin/eql/src/test/resources/queries-supported.eql
> +sample by ?x with max_samples_per_key=6 [any where true] by y [any where true] by z
Leftover

2022-12-16 15:49 UTC, astefan commented on x-pack/plugin/eql/qa/common/src/main/resources/data/sample-multi.data
> +[
Add some empty join key values (`null`) or missing values and add some test queries that use optional fields as join keys. `sample by ?os [any where true] [any where true]`

2022-12-19 08:25 UTC, luigidellaquila commented on x-pack/plugin/eql/qa/common/src/main/resources/test_sample_multi.toml
> +]
Yes, it's all the possible combinations of N results per key.

2022-12-21 15:27 UTC, astefan approved these changes
LGTM

2022-12-23 11:43 UTC, merged

2022-12-27 21:35 UTC, szeitlin commented
yay! Thank you! Looking forward to trying this out!