Speed h3 library by using FastMath implementation for trigonometric functions
elastic/elasticsearch pull request #91839
Opened 2022-11-23 10:17 UTC by iverase

Currently, one of the bottlenecks of thee h3 implementation are the execution of trigonometric functions. This change propose to use a faster implementation for those function which trade speed for accuracy. After the change, all test still work and performance is greatly improved.

The FastMath implementations are forked from https://github.com/yannrichet/jmathplot/blob/f25426e0ab0e68647ad2b75f577c7be050ecac86/src/main/java/org/math/plot/utils/FastMath.java which is released under AL2 license.

2022-11-23 10:17 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytics-geo (Team:Analytics)

2022-11-23 10:17 UTC, elasticsearchmachine commented
Hi @iverase, I've created a changelog YAML for you.

2022-11-23 14:17 UTC, iverase commented
@elasticsearchmachine update branch

2022-11-23 15:22 UTC, craigtaverner approved these changes
Let's hope it is accurate enough that no customers/users notice results changing in 8.7!

2022-11-23 15:22 UTC, craigtaverner commented on libs/h3/src/test/java/org/elasticsearch/h3/FastMathTests.java
> +    public void doTest(DoubleUnaryOperator expected, DoubleUnaryOperator actual, DoubleUnaryOperator delta, DoubleSupplier supplier) {
Presumably this should be private?

2022-12-07 15:49 UTC, iverase commented
@elasticmachine update branch

2022-12-07 16:26 UTC, iverase commented
unrelated failure: https://github.com/elastic/elasticsearch/issues/92206

@elasticmachine run elasticsearch-ci/part-2

2022-12-15 16:33 UTC, gtback requested changes

2022-12-15 16:33 UTC, gtback commented on libs/h3/src/main/java/org/elasticsearch/h3/FastMath.java
> + * https://github.com/yannrichet/jmathplot/blob/f25426e0ab0e68647ad2b75f577c7be050ecac86/src/main/java/org/math/plot/utils/FastMath.java
```suggestion
 * https://github.com/jeffhain/jafama/blob/d7d2a7659e96e148d827acc24cf385b872cda365/src/main/java/net/jafama/FastMath.java
```

2022-12-15 16:34 UTC, gtback approved these changes
I didn't mean to "request changes", so my approval is just to prevent that from blocking a merge.

2022-12-15 17:26 UTC, jpountz approved these changes
Given the existing accuracy trade-off of our geo support, this change feels like it wouldn't make accuracy noticeably worse, while giving a significant performance boost. We're already using the same implementation for cos() and asin() in Lucene (via `org.apache.lucene.util.SloppyMath`) and no issues have been reported to my knowledge.

2022-12-16 06:38 UTC, iverase commented
@elasticmachine update branch

2022-12-19 15:37 UTC, iverase commented
open https://github.com/elastic/elasticsearch/issues/92454

@elasticmachine run elasticsearch-ci/part-3

2022-12-20 12:11 UTC, iverase commented
@elasticmachine update branch

2022-12-20 13:02 UTC, merged