Validate _id value while using a set within a processor (#91777)
elastic/elasticsearch pull request #91884
Opened 2022-11-24 11:09 UTC by HiDAl

Prevent the creation of processors which set the value of the `_id` field to a string longer than 512 bytes.

See also #16036

2022-11-24 12:04 UTC, HiDAl commented
```bash
PUT {{ES}}/_ingest/pipeline/fixed-value-2

{
  "processors": [
    {
      "set": {
        "field": "_id",
        "value": "Some_Server_name.thisisareallylongthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamethisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamethisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeat"
      }
    }
  ]
}

==== RESPONSE ====

HTTP/1.1 400 Bad Request
X-elastic-product: Elasticsearch
content-type: application/json;charset=utf-8
content-encoding: gzip
content-length: 255

{
  "error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "[value] _id [Some_Server_name.thisisareallylongthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamethisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamethisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeat] is too long, must not be longer than 512 bytes but was: 904",
        "property_name": "value",
        "processor_type": "set"
      }
    ],
    "type": "parse_exception",
    "reason": "[value] _id [Some_Server_name.thisisareallylongthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamethisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamethisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeat] is too long, must not be longer than 512 bytes but was: 904",
    "property_name": "value",
    "processor_type": "set"
  },
  "status": 400
}
```

2022-11-24 14:24 UTC, HiDAl commented
@elasticmachine retest this please

2022-11-24 15:39 UTC, joegallo requested changes
I don’t expect that this can be validated at pipeline creation time, it’s a runtime thing. That is, the _id isn’t going to be a String, it’s going to be a template or a copy_from.

2022-11-28 15:28 UTC, HiDAl commented
yes @joegallo , that's what I put in the [original issue](https://github.com/elastic/elasticsearch/issues/91777#issuecomment-1326466905). I'll bring this to the team's weekly meeting, so we can reach out to an agreement

2022-11-29 11:48 UTC, HiDAl commented
Closing this draft since it seems the solution will be validate the out document

2022-11-29 11:48 UTC, closed without merging