Validates IndexRequests after ingest pipelines (#91777)
elastic/elasticsearch pull request #92330
Opened 2022-12-13 14:50 UTC by HiDAl

This code change checks that the document generated/processed by all pipelines is still valid. If the document will be processed by either 1 or 2 pipelines (namely `pipeline` & `finalPipeline`), the validation would be executed only once per document (`IngestService` receives a "list" of requests, basically a bulk request)

closes #91777

2022-12-13 15:03 UTC, elasticsearchmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2022-12-13 15:12 UTC, joegallo commented on server/src/main/java/org/elasticsearch/ingest/IngestService.java
> +                    validateIndexRequestPostProcessing(requestSlot, indexRequest, onFailure);
`executePipelines` is (well, can be) asynchronous, you can't call  `validateIndexRequestPostProcessing` here like this.

2022-12-13 15:14 UTC, joegallo requested changes
Need to address issues with synchronous/asynchronous code, also I'm not absolutely sure the handler invocation is right (but I'm not sure it's wrong either!).

2022-12-20 11:50 UTC, HiDAl commented
PR waiting merge of #92455

2022-12-21 13:29 UTC, HiDAl commented
I've updated the PR to the latest version with the fix introduced in #92455. Although this fixes the original issue, it has also surfaced a different kinds of errors:

1. In case you send a `_bulk` request dong upserts **and** the index does not exist yet, the validation won't pass:

```
PUT _ingest/pipeline/lowercase-pipeline
{
  "processors": [
    {
      "lowercase": {
        "field": "my_field"
      }
    }
  ]
}

POST _bulk
{"update":{"_id":"1","_index":"test_index","pipeline":"lowercase-pipeline"}}
{"upsert":{"my_field":"UPPER"},"script":{"source":"ctx._source.my_field = ctx._source.my_field.toLowercase()"}}

{
  "took": 0,
  "ingest_took": 2,
  "errors": true,
  "items": [
    {
      "index": {
        "_index": null,
        "_id": null,
        "status": 400,
        "error": {
          "type": "illegal_argument_exception",
          "reason": "pipeline with id [lowercase-pipeline] does not exist"
        }
      }
    }
  ]
}
```

I'll continue trying to tackle this issue.

2023-02-08 19:55 UTC, elasticsearchmachine commented
Hi @HiDAl, I've created a changelog YAML for you.

2023-05-24 20:59 UTC, closed without merging