Allow different filters per DataStream in a DataStreamAlias
elastic/elasticsearch pull request #92407
Opened 2022-12-15 23:49 UTC by masseyke

Index aliases allow each index in the alias to have a different filter. Data stream aliases appear to do this, but in reality they do not. That is, if you ask to add two data streams to a data stream alias, each with a different filter, the API allows it but only keeps one of the filters. This PR makes it so that each DataStream in the cluster state metadata keeps its own copies of the DataStreamAliases that refer to it so that the different filters are respected.
Closes #92050

2022-12-15 23:49 UTC, elasticsearchmachine commented
Hi @masseyke, I've created a changelog YAML for you.

2022-12-19 22:51 UTC, elasticsearchmachine commented
Hi @masseyke, I've updated the changelog YAML for you.

2022-12-20 16:03 UTC, elasticsearchmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2023-01-04 00:01 UTC, dakrone requested changes
I left a few comments. I know we went this way because I had started, but I'm curious whether you thought there is a simpler way of expressing it? The complexity of some of the hoops we have to jump through makes me a little uneasy (if it's the only way, then we'll deal with it, just curious if there's a simpler way of expressing it.)

2023-01-04 15:45 UTC, masseyke commented on server/src/main/java/org/elasticsearch/action/admin/indices/alias/TransportIndicesAliasesAction.java
> +                                logger.debug("--> adding filter for {} with filter: {}", dataStreamName, action.filter());
Ohh I thought you had wanted all of these to be available. Removing them all.

2023-01-04 22:44 UTC, masseyke commented
> I left a few comments. I know we went this way because I had started, but I'm curious whether you thought there is a simpler way of expressing it? The complexity of some of the hoops we have to jump through makes me a little uneasy (if it's the only way, then we'll deal with it, just curious if there's a simpler way of expressing it.)

We went this way so that it was implemented analogously to the way index aliases are implemented. I've put up #92692 as an alternative. Instead of having each DataStream keep up with its DataStreamAliases, it changes DataStreamAlias to keep a map of which filter goes with which DataStream. It wound up being a lot simpler. The only downside that I see is that it's not implemented in the same way as index aliases.

2023-01-05 17:00 UTC, closed without merging