ses_account email_defaults
elastic/elasticsearch pull request #92453
Opened 2022-12-19 15:12 UTC by anmironov

for ses_account I see in some cases that
        email_defaults:
            from: <email address of service account>
is necessary (as in the example for Microsoft Exchange).

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2022-12-19 15:13 UTC, elasticsearchmachine commented
@anmironov please enable the option "Allow edits and access to secrets by maintainers" on your PR. For more information, [see the documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

2022-12-19 20:06 UTC, elasticsearchmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2022-12-23 07:45 UTC, elasticsearchmachine commented
Pinging @elastic/es-docs (Team:Docs)

2022-12-27 09:19 UTC, gmarouli requested changes
Hi @anmironov , thank you for improving the docs. I had 2 small comments, let me know what you think :).

2022-12-27 09:19 UTC, gmarouli commented on x-pack/docs/en/watcher/actions/email.asciidoc
> +    valid local email account.
What would you think about rephrasing this in a way that is inline with the comment below. For example, (this is just a suggestion):

```
<1> in certain cases `email_defaults.from` is validated by Amazon SES to ensure that it is a valid local email account.
```

2023-02-27 10:03 UTC, abdonpijpelink commented
@gmarouli After chatting with @anmironov , I have applied your suggestions.

2023-02-27 16:31 UTC, abdonpijpelink commented
@elasticmachine update branch

2023-03-28 19:26 UTC, gmarouli approved these changes
LGTM :) thank you for helping us out.

2023-03-30 08:39 UTC, merged