Omit master-ineligible nodes from initial_master_nodes
elastic/elasticsearch pull request #93131
Opened 2023-01-23 08:13 UTC by DaveCTurner

Today the `test-clusters` framework sets `cluster.initial_master_nodes` to the names of all the nodes in the cluster, but this only makes sense if they're all master-eligible. This commit filters this setting down to just the master-eligible node names.

2023-01-23 08:13 UTC, DaveCTurner commented
NB not sure this is the best way to identify the master-eligible nodes.

2023-01-23 08:13 UTC, elasticsearchmachine commented
Pinging @elastic/es-delivery (Team:Delivery)

2023-01-23 16:51 UTC, mark-vieira requested changes
This probably won't work as-is. `DefaultSetrtingsProvider` is exactly that, a "default". It won't see settings added later by the user or other settings providers. We'll have to defer to setup of `initial_master_nodes` until after any other settings have been configured. I can take a stab at this.

This is another item that's always historically been the case. Is this problematic now, or just non-optimal?

2023-01-23 17:10 UTC, DaveCTurner commented
I stumbled across it while wanting to run a stateless cluster with a dedicated master, a dedicated indexing node and a dedicated search node so I could attach the right debuggers to the right nodes. I can live with them all being master-eligible for now.

2023-01-23 17:12 UTC, mark-vieira commented
> I stumbled across it while wanting to run a stateless cluster with a dedicated master, a dedicated indexing node and a dedicated search node so I could attach the right debuggers to the right nodes. I can live with them all being master-eligible for now.

Will the cluster you describe fail to start as implemented today? Do all nodes _have_ to be configured master-eligible?

2023-01-23 17:18 UTC, DaveCTurner commented
> Will the cluster you describe fail to start as implemented today?

Yes.

> Do all nodes have to be configured master-eligible?

Technically it works if >½ of them are master-eligible.

2023-01-23 18:15 UTC, mark-vieira commented
Ok, we should definitely resolve this then. I'll take a look at the best way to pass this setting.

2023-01-24 21:05 UTC, mark-vieira commented
Closing in favor of https://github.com/elastic/elasticsearch/pull/93212

2023-01-24 21:05 UTC, closed without merging