Add a pattern bank cache to Grok Processors
elastic/elasticsearch pull request #93510
Opened 2023-02-06 11:28 UTC by HiDAl

Pattern banks are identical between different processors, making them highly cacheable and allowing us to save some memory bytes. Also, uses immutable maps, just to clearly indicate that the banks won't be changed later on.

To validate the change I've created a ingest pipeline with 100 processors in total, but only 4 different versions (the different combinations of `ecs_compatibility` values plus having and not having custom `pattern_definitions`):

```json
PUT _ingest/pipeline/grok-size
{
  "processors": [
    {
      "grok": {
        "field": "message",
        "patterns": [
          "%{WORD:grok.client}"
        ],
        "ecs_compatibility": "v1",
        "pattern_definitions": {
          "FAVORITE_DOG": "beagle",
          "RGB": "RED|GREEN|BLUE"
        }
      }
    },
    {
      "grok": {
        "field": "message",
        "patterns": [
          "%{WORD:grok.client}"
        ],
        "pattern_definitions": {
          "FAVORITE_DOG": "beagle",
          "RGB": "RED|GREEN|BLUE"
        }
      }
    },
    {
      "grok": {
        "field": "message",
        "patterns": [
          "%{WORD:grok.client}"
        ]
      }
    },
    {
      "grok": {
        "field": "message",
        "ecs_compatibility": "v1",
        "patterns": [
          "%{WORD:grok.client}"
        ]
      }
    },
    ...
  ]
}
```

taking a heap dump, we can see the amount of saved memory:

> before
> <img width="1049" alt="Screenshot 2023-02-06 at 12 16 11" src="https://user-images.githubusercontent.com/284537/216958335-6e073a37-e869-42c8-bd5c-c8ab6a3bfc6f.png">

> after
> <img width="1049" alt="Screenshot 2023-02-06 at 12 16 07" src="https://user-images.githubusercontent.com/284537/216958326-300c1057-c5ec-408a-9382-b417aa5fcc61.png">

The same pipeline went from `~1.33MB` to `91KB` of total resident memory used.

2023-02-06 11:28 UTC, elasticsearchmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2023-02-06 11:28 UTC, elasticsearchmachine commented
Hi @HiDAl, I've created a changelog YAML for you.

2023-02-06 22:18 UTC, joegallo requested changes
I'm not especially in favor of a cache here -- this seems like something that could perhaps be better solved by having a formal `PatternBank` construct. `PatternBank`s would be immutable. They could be built directly out of a bunch of patterns, or built via an extension mechanism where a bunch of patterns and also the PatternBank to be extended could be passed in.

From that I think the memory efficiency would all just drop out automatically as a consequence, with no need for a cache.

2023-02-23 08:46 UTC, HiDAl commented
Closing because we'll implement a full refactor around the pattern bank concept. Tracking issue https://github.com/elastic/elasticsearch/issues/93982

2023-02-23 08:46 UTC, closed without merging