Add TransportVersion to DiscoveryNode
elastic/elasticsearch pull request #93818
Opened 2023-02-15 11:29 UTC by thecoop

Add a `getTransportVersion` to `DiscoveryNode`, to be propagated alongside node version, to represent the transport version used to communicate with the node.

Migrate an initial set of callsites away from `Version.transportVersion`

2023-02-15 11:29 UTC, elasticsearchmachine commented
Pinging @elastic/es-core-infra (Team:Core/Infra)

2023-02-15 11:33 UTC, thecoop commented on server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java
> +    @Deprecated(forRemoval = true)
Eventually you will not be able to create a discoverynode without specifying node & transport versions explicitly

2023-02-15 11:41 UTC, pgomulka approved these changes
LGTM

2023-02-15 11:43 UTC, thecoop commented on server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java
> +        if (out.getTransportVersion().onOrAfter(TRANSPORT_VERSION_VERSION)) {
I *think* this recursive reference to transport version will Just Work, but if someone could confirm that would help

2023-02-15 11:45 UTC, DaveCTurner reviewed
Hmm this doesn't seem like the right approach to me. The transport version should be a property of the channel we're using to communicate with the remote node, which we should know from having completed a mutual handshake.

For instance:

- `JoinValidationService` and `PublicationTransportHandler` should collect up the channels we're intending to use for the transmission before we start to serialize anything.

- `Transport.Connection` should expose the transport version that the handshake negotiated

2023-02-15 11:46 UTC, DaveCTurner requested changes
Marking this as "request changes" until we finish discussing the content of my previous review.

2023-02-15 11:48 UTC, thecoop commented
So how do we get from a `DiscoveryNode` instance to the transport version needed to communicate with that node?

2023-02-15 11:49 UTC, DaveCTurner commented on server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java
> +            TransportVersion.writeVersion(transportVersion, out);
This means that every remote node will see the same `transportVersion` property for each `DiscoveryNode`, but they will not all be using the same transport protocol version.

2023-02-15 11:50 UTC, DaveCTurner commented
> So how do we get from a DiscoveryNode instance to the transport version needed to communicate with that node?

We get a channel from the `TransportService` (i.e. the `ConnectionManager`) and ask it what transport version it negotiated.

2023-02-15 13:05 UTC, DaveCTurner commented
Something _like_ that, yes. I'd prefer we only got the connection once in each case, using the same instance of `Transport.Connection` for retrieving the version and for sending the message.

2023-02-16 13:06 UTC, thecoop commented
Closed in favour of #93822

2023-02-16 13:06 UTC, closed without merging