Dry up additional spots of setting cluster settings in internal cluster tests
elastic/elasticsearch pull request #94243
Opened 2023-03-01 16:12 UTC by original-brownbear

Follow up to #94213 dealing with the remaining spots. This also moves some use of deprecated transient settings to persisted settings and deprecates the request builder methods for transient settings to hopefully prevent more use of transients.

2023-03-01 16:13 UTC, elasticsearchmachine commented
Pinging @elastic/es-core-infra (Team:Core/Infra)

2023-03-09 18:50 UTC, williamrandolph requested changes
Looks good overall, but there's one spot where I think this PR might have dropped an update. Let me know if there was a reason for it that I missed!

2023-03-09 19:16 UTC, original-brownbear commented on x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/ClassificationIT.java
> +            Settings.builder().putNull("logger.org.elasticsearch.xpack.ml.process").putNull("logger.org.elasticsearch.xpack.ml.dataframe")
We're still setting it to null, the formatter just moved both setting to a single line but functionally nothing changed?

2023-03-09 19:40 UTC, williamrandolph commented on x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/ClassificationIT.java
> +            Settings.builder().putNull("logger.org.elasticsearch.xpack.ml.process").putNull("logger.org.elasticsearch.xpack.ml.dataframe")
Whoops! I was deceived by my diff window and didn't see the whole line! Apologies, and now I will happily approve.

2023-03-09 19:40 UTC, williamrandolph approved these changes
Looks good to me!

2023-03-09 19:41 UTC, original-brownbear commented
Thanks William!

2023-03-09 19:41 UTC, merged