Improve FixedRounding#nextRoundingValue(...) performance.
elastic/elasticsearch pull request #94706
Opened 2023-03-23 20:43 UTC by martijnvg

This currently uses `JavaTimeRounding#nextRoundingValue(...)` to find the next rounding value, which functionally is correct, but is slow. Since FixedRounding only deals with fixed intervals, we should just be able to round the provided time and then add the fixed interval to it.

This is used during adding empty buckets if missing in date_histogram with a fixed interval. In case there are many buckets to overhead of using `JavaTimeRounding` is noticeable.

2023-03-23 23:05 UTC, martijnvg commented
Together with #94649, this change gives an additional nice speedup:

```
|                                                                                           Min Throughput |       cpu_usage_by_pod_last_3_hours |      0.803806    |     1.58826     |       0.78446 |  ops/s |  +97.59% |
|                                                                                          Mean Throughput |       cpu_usage_by_pod_last_3_hours |      1.14893     |     2.88635     |       1.73742 |  ops/s | +151.22% |
|                                                                                        Median Throughput |       cpu_usage_by_pod_last_3_hours |      1.18152     |     3.02432     |       1.8428  |  ops/s | +155.97% |
|                                                                                           Max Throughput |       cpu_usage_by_pod_last_3_hours |      1.19326     |     3.12353     |       1.93027 |  ops/s | +161.76% |
|                                                                                  50th percentile latency |       cpu_usage_by_pod_last_3_hours |    819.693       |   302.526       |    -517.166   |     ms |  -63.09% |
|                                                                                  90th percentile latency |       cpu_usage_by_pod_last_3_hours |    833.956       |   308.661       |    -525.296   |     ms |  -62.99% |
|                                                                                  99th percentile latency |       cpu_usage_by_pod_last_3_hours |    884.595       |   390.544       |    -494.051   |     ms |  -55.85% |
|                                                                                 100th percentile latency |       cpu_usage_by_pod_last_3_hours |   1238.06        |   624.702       |    -613.36    |     ms |  -49.54% |
|                                                                             50th percentile service time |       cpu_usage_by_pod_last_3_hours |    819.693       |   302.526       |    -517.166   |     ms |  -63.09% |
|                                                                             90th percentile service time |       cpu_usage_by_pod_last_3_hours |    833.956       |   308.661       |    -525.296   |     ms |  -62.99% |
|                                                                             99th percentile service time |       cpu_usage_by_pod_last_3_hours |    884.595       |   390.544       |    -494.051   |     ms |  -55.85% |
|                                                                            100th percentile service time |       cpu_usage_by_pod_last_3_hours |   1238.06        |   624.702       |    -613.36    |     ms |  -49.54% |
|                                                                                               error rate |       cpu_usage_by_pod_last_3_hours |      0           |     0           |       0       |      % |    0.00% |
|                                                                                           Min Throughput |    cpu_usage_by_pod_last_15_minutes |      9.7815      |    18.3098      |       8.52826 |  ops/s |  +87.19% |
|                                                                                          Mean Throughput |    cpu_usage_by_pod_last_15_minutes |     10.2726      |    19.3403      |       9.06767 |  ops/s |  +88.27% |
|                                                                                        Median Throughput |    cpu_usage_by_pod_last_15_minutes |     10.3287      |    19.5954      |       9.26673 |  ops/s |  +89.72% |
|                                                                                           Max Throughput |    cpu_usage_by_pod_last_15_minutes |     10.4426      |    19.8452      |       9.40259 |  ops/s |  +90.04% |
|                                                                                  50th percentile latency |    cpu_usage_by_pod_last_15_minutes |     93.207       |    47.9892      |     -45.2178  |     ms |  -48.51% |
|                                                                                  90th percentile latency |    cpu_usage_by_pod_last_15_minutes |     96.5802      |    49.8799      |     -46.7003  |     ms |  -48.35% |
|                                                                                  99th percentile latency |    cpu_usage_by_pod_last_15_minutes |    112.187       |    67.321       |     -44.866   |     ms |  -39.99% |
|                                                                                 100th percentile latency |    cpu_usage_by_pod_last_15_minutes |    122.819       |    86.384       |     -36.4348  |     ms |  -29.67% |
|                                                                             50th percentile service time |    cpu_usage_by_pod_last_15_minutes |     93.207       |    47.9892      |     -45.2178  |     ms |  -48.51% |
|                                                                             90th percentile service time |    cpu_usage_by_pod_last_15_minutes |     96.5802      |    49.8799      |     -46.7003  |     ms |  -48.35% |
|                                                                             99th percentile service time |    cpu_usage_by_pod_last_15_minutes |    112.187       |    67.321       |     -44.866   |     ms |  -39.99% |
|                                                                            100th percentile service time |    cpu_usage_by_pod_last_15_minutes |    122.819       |    86.384       |     -36.4348  |     ms |  -29.67% |
|                                                                                               error rate |    cpu_usage_by_pod_last_15_minutes |      0           |     0           |       0       |      % |    0.00% |
|                                                                                           Min Throughput |    cpu_usage_by_pod_last_15_seconds |     81.5801      |   134.469       |      52.8886  |  ops/s |  +64.83% |
|                                                                                          Mean Throughput |    cpu_usage_by_pod_last_15_seconds |     81.5801      |   134.469       |      52.8886  |  ops/s |  +64.83% |
|                                                                                        Median Throughput |    cpu_usage_by_pod_last_15_seconds |     81.5801      |   134.469       |      52.8886  |  ops/s |  +64.83% |
|                                                                                           Max Throughput |    cpu_usage_by_pod_last_15_seconds |     81.5801      |   134.469       |      52.8886  |  ops/s |  +64.83% |
|                                                                                  50th percentile latency |    cpu_usage_by_pod_last_15_seconds |     11.3033      |     6.72421     |      -4.57911 |     ms |  -40.51% |
|                                                                                  90th percentile latency |    cpu_usage_by_pod_last_15_seconds |     11.8042      |     7.55051     |      -4.25369 |     ms |  -36.04% |
|                                                                                  99th percentile latency |    cpu_usage_by_pod_last_15_seconds |     14.6318      |    11.5395      |      -3.09233 |     ms |  -21.13% |
|                                                                                 100th percentile latency |    cpu_usage_by_pod_last_15_seconds |     18.7047      |    15.8881      |      -2.81658 |     ms |  -15.06% |
|                                                                             50th percentile service time |    cpu_usage_by_pod_last_15_seconds |     11.3033      |     6.72421     |      -4.57911 |     ms |  -40.51% |
|                                                                             90th percentile service time |    cpu_usage_by_pod_last_15_seconds |     11.8042      |     7.55051     |      -4.25369 |     ms |  -36.04% |
|       [...]

2023-03-24 07:41 UTC, elasticsearchmachine commented
Hi @martijnvg, I've created a changelog YAML for you.

2023-03-24 07:41 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytics-geo (Team:Analytics)

2023-03-24 11:02 UTC, nik9000 approved these changes

2023-03-24 12:59 UTC, not-napoleon requested changes
I don't think this is correct, unfortunately.  Or at least, I need more testing to convince me.  The problem is that `fixed_interval` is actually supposed to be DST aware.  From [our docs](https://github.com/elastic/elasticsearch/issues/50139):

> Many time zones shift their clocks for daylight savings time. Buckets close to the moment when those changes happen can have slightly different sizes than you would expect from the calendar_interval or fixed_interval. For example, consider a DST start in the CET time zone: on 27 March 2016 at 2am, clocks were turned forward 1 hour to 3am local time. If you use day as the calendar_interval, the bucket covering that day will only hold data for 23 hours instead of the usual 24 hours for other buckets. The same is true for shorter intervals, like a fixed_interval of 12h, where you’ll have only a 11h bucket on the morning of 27 March when the DST shift happens.

I believe this would cause `fixed_interval` to not respect DST, which would be breaking based on that docs line.  We do have an open issue about this behavior being surprising: https://github.com/elastic/elasticsearch/issues/50139  and I'm pretty sure we don't have explicit tests for it.  

I don't think we should merge this without being sure this isn't breaking the current behavior.

2023-03-24 13:11 UTC, nik9000 commented
Yeah - that thing @not-napoleon said. It's correct in a fixed time zone. Or if you don't cross the tz bound. But if you do then fixed roundings are only fixed in a very particular, "funny" way that doesn't have to do with actual time and more to do with wall clocks.

2023-03-27 06:28 UTC, martijnvg commented
> I believe this would cause fixed_interval to not respect DST, which would be breaking based on that docs line. We do have an open issue about this behavior being surprising: https://github.com/elastic/elasticsearch/issues/50139 and I'm pretty sure we don't have explicit tests for it.

Ok, I didn't realise this and I don't want to introduce a breaking change here. I need to think about this. The reason that I opened this PR is that `JavaTimeRounding` still significantly showed up in flame graph even with #94649 merged in. Maybe there are ways we can detect that the `JavaTimeRounding` is needed or when we can just add the interval to the rounded timed?

2024-02-14 18:08 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytical-engine (Team:Analytics)

2025-01-17 15:38 UTC, closed without merging