Kover
elastic/elasticsearch pull request #94771
Opened 2023-03-27 11:07 UTC by pgomulka

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

2023-03-27 11:13 UTC, pgomulka commented on build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/precommit/transport/FindTransportClassesPlugin.java
> +        project.getPlugins().withType(JavaPlugin.class, javaPlugin -> {
perhaps because I apply this to all `JavaPlugin` this task wis becoming a dependency to things like JarHell?

2023-03-27 11:16 UTC, pgomulka commented on modules/ingest-geoip/src/internalClusterTest/java/org/elasticsearch/ingest/geoip/GeoIpProcessorNonIngestNodeIT.java
> +@AwaitsFix(bugUrl = "")
kover somehow triggers running integTests too.
How can I limit kover to unit tests only?

2023-03-27 13:21 UTC, breskeby commented on build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchJavaPlugin.java
> +        project.getPluginManager().apply(KoverPlugin.class);
The ElasticsearchJavaPlugin should not know anything about code coverage. This should be done in a complete separate plugin and only applied on build script level IMO

2023-03-27 14:07 UTC, breskeby requested changes
What is actually the goal of this PR? Could you elaborate? 

If we introduce code coverage to our elasticsearch build we should do it on broader level and ensure it also is compatible with sonarcube as we will integrate with sonarcube sooner or later. 

Why are you using kover here instead of the de facto standard jacoco?

Does this FindTransportTestClassesTask really need to be a precommit task and every developer needs to run this task before committing? Or would be a PR check be enough. Ideally we would just enable code coverage if a certain task is triggered as part of the build. 
The default should be to run all tests without coverage. 
Otherwise every test invocation pays the price of code instrumentation which likely slows down general test execution dramatically

2023-03-27 14:22 UTC, pgomulka commented
> What is actually the goal of this PR? Could you elaborate?

Apologies for lack of context. The goal of this PR was main to get help on the problem with gradle task depedendencies. I spoke with Mark last week and he recommended WIP to get better understanding.

> If we introduce code coverage to our elasticsearch build we should do it on broader level and ensure it also is compatible with sonarcube as we will integrate with sonarcube sooner or later.
> 
> Why are you using kover here instead of the de facto standard jacoco?

kover can use jacoco under the hood. The problem I found with gradle's jacoco plugin and jacoco on its own was that it fails upon the first class that violates the coverage rule. I wanted to get a failure with all classes that violate the coverage rule in a build. I could not find a way to work around this.
https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:jacoco_report_violation_rules
`The build fails if any of the configured rules are not met. JaCoCo only reports the first violated rule.`

> Does this FindTransportTestClassesTask really need to be a precommit task and every developer needs to run this task before committing? Or would be a PR check be enough. Ideally we would just enable code coverage if a certain task is triggered as part of the build.
> The default should be to run all tests without coverage.
> Otherwise every test invocation pays the price of code instrumentation which likely slows down general test execution dramatically.

Totally agreed. The precommit task is a remainder of the previous approach where I used this scanning during precommit. The PR check is totally enough. Any example to follow to have it set up as a PR check?

> In general it feels this should be at least broken up in two PRs. 1) to add general code coverage tracking in our build and 2) add report / check for coverage of Writeable implementation and their test coverage.

Also agree. I will happily split the PR in two as suggested. I wanted to make sure I can get the kover/jacoco to work first though.

2023-05-05 06:52 UTC, pgomulka commented
https://github.com/elastic/elasticsearch/pull/94956#issuecomment-1535795637

2023-05-05 06:52 UTC, closed without merging