Support Search Template API Explain Query String Argument
elastic/elasticsearch pull request #94832
Opened 2023-03-28 14:38 UTC by jackpan123

Closes #83363

2023-03-29 16:53 UTC, elasticsearchmachine commented
Pinging @elastic/es-search (Team:Search)

2023-03-29 17:40 UTC, benwtrent commented
@jackpan123 I like this change!

Could you add a test? Probably to `SearchTemplateIT` that ensures `explain` executes? This way we don't accidentally break it in the future :)

2023-03-30 04:46 UTC, jackpan123 commented
@benwtrent I have a problem where I am trying to add the 'testTemplateWithExplainQueryStringArgument' method into the 'SearchTemplateIT' class, but I am unsure of how to set the query string argument. If I call 'SearchTemplateRequestBuilder#setExplain' directly, it will not test my case. Could you give me some guidance? My test code looks like the following:
```
public void testTemplateWithExplainQueryStringArgument() throws Exception {
        SearchRequest searchRequest = new SearchRequest();
        searchRequest.indices("test");
        String query = """
            { "query": {"match_all": {}}, "size" : "{{my_size}}" }""";
        SearchTemplateResponse searchResponse = new SearchTemplateRequestBuilder(client()).setRequest(searchRequest)
            .setScript(query)
            .setScriptType(ScriptType.INLINE)
            .setScriptParams(Collections.singletonMap("my_size", 1))
            .setExplain(true)
            .get();

        assertThat(searchResponse.toString().contains("_explanation"), equalTo(true));

    }
```

2023-03-30 04:52 UTC, jackpan123 commented
@benwtrent I tried another test class called `RestSearchTemplateActionTests`. It allows me to add `explain` as a query string argument, but I am unsure how to retrieve the response for assertion. My test code is as follows:
```
public void testExplainInPath() {
      Map<String, String> params = new HashMap<>();
      params.put("explain", "true");

      RestRequest request = new FakeRestRequest.Builder(xContentRegistry()).withHeaders(
          Map.of("Content-Type", contentTypeHeader, "Accept", contentTypeHeader)
      ).withMethod(RestRequest.Method.GET).withPath("/some_index/_search/template").withParams(params).build();

      dispatchRequest(request);
  }
```

2023-03-30 13:21 UTC, benwtrent requested changes
Please add a yamlRestTest to `modules/lang-mustache/src/yamlRestTest/resources/rest-api-spec/test/lang_mustache/30_search_template.yml`

Here is what I think the test should look like. 

```yaml
---
"Test explain templated search":
  - skip:
      version: " - 8.7.99"
      reason: Bug fix for explain in search template added in 8.8.0

  - do:
      index:
        index:  test
        id:     "1"
        body:   { "text": "value1" }
  - do:
      index:
        index:  test
        id:     "2"
        body:   { "text": "value2" }
  - do:
      indices.refresh: {}

  - do:
      search_template:
        explain: true
        body: { "source" : { "query": { "term": { "text": { "value": "{{template}}" } } } }, "params": { "template": "value1" } }

  - is_true: hits.hits.0._explanation
 # Test consistency with _search API, where query parameter takes priority over body
  - do:
      search_template:
        explain: true
        body: { "explain": false, "source" : { "query": { "term": { "text": { "value": "{{template}}" } } } }, "params": { "template": "value1" } }

  - is_true: hits.hits.0._explanation

  - do:
      search_template:
        explain: false
        body: {"explain": true, "source" : { "query": { "term": { "text": { "value": "{{template}}" } } } }, "params": { "template": "value1" } }

  - is_false: hits.hits.0._explanation

```

2023-03-30 13:21 UTC, benwtrent commented on modules/lang-mustache/src/main/java/org/elasticsearch/script/mustache/RestSearchTemplateAction.java
> +        prepareRequest(searchTemplateRequest, request);
```suggestion
        // This param is parsed within the search request
        if (searchRequest.source().explain() != null) {
            searchTemplateRequest.setExplain(searchRequest.source().explain());
        }
```
We should take the parameter from there as it is already parsed, and check if its supplied.

2023-03-30 15:39 UTC, jackpan123 commented
@benwtrent Thanks! I already add the test!

2023-03-30 17:02 UTC, benwtrent reviewed
one more thing. Its looking good.

2023-03-30 17:02 UTC, benwtrent commented on modules/lang-mustache/src/main/java/org/elasticsearch/script/mustache/RestSearchTemplateAction.java
> +    }
```suggestion
```

No longer used.

2023-03-30 17:23 UTC, benwtrent commented
jenkins retest this please

2023-03-30 17:24 UTC, jackpan123 commented
@benwtrent I have a question: if I need to add more arguments to the query string, it would be more flexible to use a method for handling them, such as the `RestSearchAction#parseSearchSource` method.

2023-03-30 17:44 UTC, benwtrent commented
@jackpan123 

> if I need to add more arguments to the query string

Do you mean new URL parameters? It honestly depends on the parameter. I don't know of any new parameters we need or should add to template search.

`explain` is a unique case as it was already "supported" just not unified in usage with search.

2023-03-30 17:44 UTC, benwtrent commented
@elasticmachine update branch

2023-03-30 17:49 UTC, benwtrent commented
jenkins retest this please

2023-03-30 18:34 UTC, benwtrent approved these changes

2023-03-30 18:34 UTC, merged

2023-03-31 00:58 UTC, jackpan123 commented
> @jackpan123
> 
> > if I need to add more arguments to the query string
> 
> Do you mean new URL parameters? It honestly depends on the parameter. I don't know of any new parameters we need or should add to template search.
> 
> `explain` is a unique case as it was already "supported" just not unified in usage with search.

I got it now. Thanks for your patient explanation.