[Test] Skip some remote cluster tests on windows
elastic/elasticsearch pull request #94973
Opened 2023-04-03 03:52 UTC by ywangd

The API key creation can fail with request cancellation error on Windows. It is not clear what was the cause. But it fails consistently since the API key creation change was made. However some other test suites in the same module do not fail despite using the same setup.

This PR disables the tests on Windows and unmute them on other platforms so we don't lose entire coverage.

Relates: #94939

2023-04-03 03:52 UTC, elasticsearchmachine commented
Pinging @elastic/es-security (Team:Security)

2023-04-03 06:54 UTC, DaveCTurner requested changes
I think these are similar failures not on Windows:

- https://gradle-enterprise.elastic.co/s/ssvyx7xcnoa2k
- https://gradle-enterprise.elastic.co/s/oopv3w6pwdse4

So I think we shouldn't unmute these tests like this.

2023-04-03 07:17 UTC, ywangd commented
Thanks David. I certainly overlooked the failure history. Will take a second look into it.

2023-04-03 12:29 UTC, n1v0lg approved these changes
LGTM!

2023-04-03 13:13 UTC, DaveCTurner approved these changes
Ah great, that makes more sense. LGTM (one nearby nit)

2023-04-03 13:13 UTC, DaveCTurner commented on x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/AbstractRemoteClusterSecurityTestCase.java
>      public static void closeFulFillingClusterClient() throws IOException {
naming nit:

```suggestion
    public static void closeFulfillingClusterClient() throws IOException {
```

2023-04-03 22:19 UTC, ywangd commented
@elasticmachine run elasticsearch-ci/part-2-windows elasticsearch-ci/packaging-tests-windows-sample

2023-04-03 22:19 UTC, ywangd commented
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

2023-04-03 23:51 UTC, ywangd commented
@elasticmachine run elasticsearch-ci/part-2-windows

2023-04-04 00:48 UTC, ywangd commented
I am going to ignore the failure of `part-2-windows` and merge this PR. This pariticular job keeps failing due to missing checksum for jdk artefact `windows-8u302-x64`. 
```
> Dependency verification failed for configuration ':x-pack:qa:rolling-upgrade:checkstyle':
  - On artifact windows-8u302-x64.zip (adoptium_8:windows:8u302) in repository 'jdk_repo_adoptium_8u302+b08': checksum is missing from verification metadata.
```
The job is not part of the normal PR CI. I added it (along with a few other Windows related jobs) because I mistakenly thought the associated issue was Windows specific. Since we now understand it is not the case, having windows CI jobs running as part of the PR is no longer necessary.

2023-04-04 00:48 UTC, merged