[7.17] Align all usages of protobuf to be 3.21.9 (#92123)
elastic/elasticsearch pull request #95431
Opened 2023-04-20 22:51 UTC by gwbrown

# Backport

This will backport the following commits from `main` to `7.17`:
 - [Align all usages of protobuf to be 3.21.9 (#92123)](https://github.com/elastic/elasticsearch/pull/92123)

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

2023-04-24 22:26 UTC, masseyke commented
Looks like x-pack/snapshot-tool/build.gradle is referencing a couple of old versions in 7.17. I assume we could just upgrade those dependencies, too.

2023-04-27 18:36 UTC, masseyke requested changes
x-pack/snapshot-tool/build.gradle is referencing a couple of old versions of protobuf

2024-05-04 04:09 UTC, gwbrown commented
Finally got a bit of time to circle back around to this - grep says I got all of em this time.

2024-05-06 15:57 UTC, masseyke approved these changes

2024-05-08 20:59 UTC, merged