SIGTERM node shutdown type
elastic/elasticsearch pull request #95430
Opened 2023-04-20 22:25 UTC by stu-elastic

2023-04-24 16:59 UTC, elasticsearchmachine commented
Hi @stu-elastic, I've created a changelog YAML for you.

2023-04-24 22:18 UTC, gwbrown requested changes
Mostly looks good, left a couple nitpicks and one concern about serialization.

2023-04-25 15:56 UTC, stu-elastic commented on server/src/main/java/org/elasticsearch/cluster/metadata/SingleNodeShutdownMetadata.java
> +        SIGTERM; // local version of REMOVE
Updated.

2023-04-25 23:18 UTC, gwbrown approved these changes
LGTM, thanks!

2023-04-26 13:48 UTC, stu-elastic commented
Updated to `TransportVersion.V_8_9_0`

2023-04-26 14:33 UTC, merged