Attempt to fix delay allocation
elastic/elasticsearch pull request #95921
Opened 2023-05-08 15:51 UTC by idegtiarenko

As pointed in https://github.com/elastic/elasticsearch/issues/93993#issuecomment-1455125791 it is possible that desired balance is computed before delayed allocations are expired but reconciled after that. As a result delay markers are removed but shards are not allocated as their desired locations are not computed yet and follow up allocation is not scheduled as all markers might be expired and removed.

This change attempts to fix this bug by injecting time into reconciliation representing the time of the latest balance computed.

Close: #93993 and #93470

2023-05-08 15:52 UTC, elasticsearchmachine commented
Hi @idegtiarenko, I've created a changelog YAML for you.

2023-05-08 15:53 UTC, idegtiarenko commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalance.java
> +public record DesiredBalance(long lastConvergedIndex, long currentTimeNano, Map<ShardId, ShardAssignment> assignments) {
Time is captured here

2023-05-08 15:54 UTC, idegtiarenko commented on server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceShardsAllocator.java
> +        ClusterState apply(ClusterState clusterState, long currentTimeNano, Consumer<RoutingAllocation> routingAllocationAction);
And passed to the reconciler via this interface. The rest are mostly changes to accommodate new parameter.

2023-05-09 05:53 UTC, DaveCTurner requested changes
I would rather we fixed this as I suggested in https://github.com/elastic/elasticsearch/issues/93993#issuecomment-1455125791: remove the delay markers only in a full reroute and not in a reconcile.

2023-05-09 14:39 UTC, idegtiarenko commented
Updated to use a flag. Though I am not sure if it is a good idea. May be we should have a dedicated reconcile method on allocation service?

2023-05-16 14:59 UTC, DaveCTurner approved these changes
LGTM

2023-05-17 11:19 UTC, merged