Support minimum_should_match for terms_set query
elastic/elasticsearch pull request #96082
Opened 2023-05-13 20:35 UTC by Kiriakos1998

Support minimum_should_match for terms_set query. 

Closes(#94095)

2023-06-02 14:46 UTC, elasticsearchmachine commented
Pinging @elastic/es-search (Team:Search)

2023-07-21 14:48 UTC, benwtrent requested changes
Sorry for taking so long on a review. Please add BWC handling and then we can see where CI fails :)

2023-07-21 14:48 UTC, benwtrent commented on server/src/main/java/org/elasticsearch/index/query/TermsSetQueryBuilder.java
> +        out.writeOptionalString(minimumShouldMatch);
This needs to handle bwc serialization. 

There are multiple examples around the code base. 

Something like:
```
if (out.getTransportVersion().onOrAfter(TransportVersion.V_8_500_019)) {
```
^ Where you create the next transport version type in that class with a UUID

2023-07-21 14:48 UTC, benwtrent commented on server/src/main/java/org/elasticsearch/index/query/TermsSetQueryBuilder.java
> +        this.minimumShouldMatch = in.readOptionalString();
This needs to handle bwc serialization. 

There are multiple examples around the code base. 

Something like:
```
if (in.getTransportVersion().onOrAfter(TransportVersion.V_8_500_019)) {
..setvalue
}
```
^ Where you create the next transport version type in that class with a UUID

2023-07-21 17:13 UTC, Kiriakos1998 commented
Hello @benwtrent, just pushed the changes handling bwc serialization. Let me know if anything else is needed.

2023-07-21 17:22 UTC, benwtrent commented
Jenkins retest this please

2023-07-21 18:21 UTC, Kiriakos1998 commented
> Jenkins retest this please

It failed in changelog validation. I will fix it and push the changes.

2023-07-21 23:49 UTC, benwtrent commented
Jenkins retest this please

2023-07-25 13:01 UTC, benwtrent reviewed
OK, reviewed some more. I like the tests and the logic all seems good to me. 

Once you update the error message && the transport version conflict is fixed (it looks like `main` has a new version and you need to bump yours and handle the conflict) I think this is ready to merge.

2023-07-25 16:08 UTC, Kiriakos1998 commented on server/src/main/java/org/elasticsearch/index/query/TermsSetQueryBuilder.java
> +            throw new IllegalArgumentException("A field has already been specified. Cannot specify both a field and script");
So we need something like that: "A field or a script has already been specified. Cannot specify both a custom field and, a field or script" and accordingly for the other error messages.

2023-07-25 16:46 UTC, benwtrent commented on server/src/main/java/org/elasticsearch/index/query/TermsSetQueryBuilder.java
> +            throw new IllegalArgumentException("A field has already been specified. Cannot specify both a field and script");
The new minimum should match option isn't a field. It's just a value. So maybe say "value, field, or script"?

2023-07-25 18:51 UTC, Kiriakos1998 commented on server/src/main/java/org/elasticsearch/index/query/TermsSetQueryBuilder.java
> +            throw new IllegalArgumentException("A field has already been specified. Cannot specify both a field and script");
Just pushed the changes. Updated error messages and added new TransportVersion

2023-07-25 19:06 UTC, benwtrent commented
Jenkins retest this please

2023-07-25 19:28 UTC, Kiriakos1998 commented
> Jenkins retest this please

I think the version was updated that's why the tests are failing.  After rebasing with the main should be ok.

2023-07-25 19:49 UTC, benwtrent commented
@elasticmachine update branch

2023-07-28 13:40 UTC, benwtrent commented on server/src/main/java/org/elasticsearch/index/query/TermsSetQueryBuilder.java
> +    public static final TransportVersion MINIMUM_SHOULD_MATCH_ADDED_VERSION = TransportVersion.V_8_500_041;
```suggestion
    public static final TransportVersion MINIMUM_SHOULD_MATCH_ADDED_VERSION = TransportVersion.V_8_500_047;
```

2023-07-28 13:41 UTC, benwtrent commented
Jenkins retest this please

2023-07-28 13:47 UTC, benwtrent commented on server/src/main/java/org/elasticsearch/TransportVersion.java
> +    public static final TransportVersion V_8_500_047 = registerTransportVersion(8_500_041, "4b1682fe-c37e-4184-80f6-7d57fcba9b3d");
```suggestion
    public static final TransportVersion V_8_500_047 = registerTransportVersion(8_500_047, "4b1682fe-c37e-4184-80f6-7d57fcba9b3d");
```

2023-07-28 13:50 UTC, benwtrent commented
Jenkins retest this please

2023-07-28 14:35 UTC, benwtrent approved these changes

2023-07-28 14:35 UTC, merged

2023-07-28 14:36 UTC, benwtrent commented
PR merged!
🎉 🎉 🎉 @Kiriakos1998 🎉 🎉 🎉 

Thanks for your contribution!!!

2023-07-28 14:40 UTC, Kiriakos1998 commented
> PR merged! 🎉 🎉 🎉 @Kiriakos1998 🎉 🎉 🎉
> 
> Thanks for your contribution!!!

You are welcome.