Update histogram-aggregation docs
elastic/elasticsearch pull request #96974
Opened 2023-06-21 10:28 UTC by philippkahr

Without specifiying the mapping explicitly it will just be stored as longs and then the histogram function doesn't really show it's cool purpose.

If I just run the PUT command I get this:

```
{
  "metrics_index": {
    "aliases": {},
    "mappings": {
      "properties": {
        "latency_histo": {
          "properties": {
            "counts": {
              "type": "long"
            },
            "values": {
              "type": "long"
            }
          }
        },
        "network": {
          "properties": {
            "name": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        }
      }
    }
}
```

Also the documentation mentions `latency_histo`. as a field however the example answer uses a bucket called `price`, which makes even less sense...

I modified it to work as expected

2023-06-21 10:29 UTC, elasticsearchmachine commented
@philippkahr please enable the option "Allow edits and access to secrets by maintainers" on your PR. For more information, [see the documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

2023-06-21 10:36 UTC, philippkahr commented
Will recreate on main

2023-06-21 12:08 UTC, elasticsearchmachine commented
Pinging @elastic/es-analytics-geo (Team:Analytics)

2023-06-21 12:08 UTC, elasticsearchmachine commented
Pinging @elastic/es-docs (Team:Docs)

2023-06-21 12:22 UTC, abdonpijpelink requested changes
Thanks for fixing this @philippkahr !

I've left some suggestions.

2023-06-21 12:22 UTC, abdonpijpelink commented on docs/reference/aggregations/bucket/histogram-aggregation.asciidoc
> +      "latency_hist": {
```suggestion
      "latency_histo": {
```

2023-06-21 12:22 UTC, abdonpijpelink commented on docs/reference/aggregations/bucket/histogram-aggregation.asciidoc
> +}
```suggestion
         "type": "histogram"
      }
    }
  }
}
```

2023-06-21 12:22 UTC, abdonpijpelink commented on docs/reference/aggregations/bucket/histogram-aggregation.asciidoc
> +}
One closing curly bracket too many

2023-06-21 12:22 UTC, abdonpijpelink commented on docs/reference/aggregations/bucket/histogram-aggregation.asciidoc
>  // TESTRESPONSE[skip:test not setup]
I think we should add a test here. This response is incorrect, and that would have been caught by having a test. Let me know if you need a hand with that.

2023-06-22 09:15 UTC, abdonpijpelink approved these changes

2023-06-22 09:16 UTC, merged

2023-06-27 15:16 UTC, abdonpijpelink commented
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|8.9|Cherrypick failed because the selected commit (4ccc5a9c) is empty. Did you already backport this commit? |
|✅|8.8|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/elasticsearch/97151">](https://github.com/elastic/elasticsearch/pull/97151)|

### Manual backport
To create the backport manually run:
```
backport --pr 96974
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->