[Synthetics]Added privileges for synthetics API key generation
elastic/elasticsearch pull request #97510
Opened 2023-07-10 11:54 UTC by shahzad31

Extended kibana permission to generate API key automatically in case it goes invalid, it's deleted or permissions aren't updated any more.

We really need this to streamline user experience in synthetics app.

API key is a core feature needed to enable synthetics saas service. without it, users can face serious issues in production. 

Not being able to auto generate hinders user experience and user might not even know there monitors are broken, so once detected have to regenerate it auto without needing user input.

2023-07-10 17:56 UTC, elasticsearchmachine commented
Pinging @elastic/es-security (Team:Security)

2023-07-10 17:57 UTC, elasticsearchmachine commented
Hi @shahzad31, I've created a changelog YAML for you.

2023-07-12 00:16 UTC, ywangd requested changes
Can we have some tests for the newly added privileges? Thanks!

2023-07-13 12:38 UTC, shahzad31 commented
closing as it's not a viable option. Since API keys can't induce permission from internal system user

2023-07-13 17:27 UTC, closed without merging