translog.delete add routing
elastic/elasticsearch pull request #97894
Opened 2023-07-24 12:08 UTC by cenyanzhuo1

currently, the translog delete event of Elasticsearch does not store the routing information. If the user specifies routing of the document, Elasticsearch calculates internally the shard which the document belongs to, through the murmurmurl3 method. 
However, the user delete the document and specified the routing, the CCR, real-time data synchronization, fails to delete the corresponding document of the target Elasticsearch cluster, because lacking the routing of Translog.delete will cause the target Elasticsearch cluster to be unable to locate the correct shard.

2023-07-24 12:17 UTC, cenyanzhuo1 commented
currently, the translog delete event of Elasticsearch does not store the routing information. If the user specifies routing of the document, Elasticsearch calculates internally the shard which the document belongs to, through the murmurmurl3 method.
However, the user delete the document and specified the routing, the CCR, real-time data synchronization, fails to delete the corresponding document of the target Elasticsearch cluster, because lacking the routing of Translog.delete will cause the target Elasticsearch cluster to be unable to locate the correct shard.

2023-07-25 06:56 UTC, cenyanzhuo1 commented
@elasticsearchmachine @ncdc @dysinger 
How can my PR pass Checking assignee?
Current issue: Community PR requires an Elastic assignee

2023-07-25 07:12 UTC, DaveCTurner requested changes
Thanks for the contribution @cenyanzhuo1. I don't think we should approach this with the `tryRead...()` approach. Instead we should advance `org.elasticsearch.index.translog.TranslogHeader#CURRENT_VERSION` to indicate the new format.

Also you must add some tests. At least there should be a `CcrIntegTestCase` demonstrating the problem, but also I would expect various changes to the `Translog` test suite.

2023-07-25 07:13 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed (Team:Distributed)

2023-07-25 07:14 UTC, DaveCTurner requested changes
Also would you base your changes on `main` rather than `7.17`? I'm not sure this will be possible to backport to 7.17, although we will think about it.

2023-07-25 07:24 UTC, cenyanzhuo1 commented
> Thanks for the contribution @cenyanzhuo1. I don't think we should approach this with the `tryRead...()` approach. Instead we should advance `org.elasticsearch.index.translog.TranslogHeader#CURRENT_VERSION` to indicate the new format.
> 
> Also you must add some tests. At least there should be a `CcrIntegTestCase` demonstrating the problem, but also I would expect various changes to the `Translog` test suite.

2023-07-25 07:28 UTC, cenyanzhuo1 commented
@DaveCTurner Thank you very much. We will think about and adjust the code according to your advise, and add the TestCase later.

2024-11-28 10:05 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed-indexing (Team:Distributed Indexing)

2025-01-09 16:33 UTC, elasticsearchmachine commented
Pinging @elastic/es-distributed-obsolete (Team:Distributed (Obsolete))

2025-01-15 11:59 UTC, DaveCTurner commented
No movement in a long time here, closing.

2025-01-15 11:59 UTC, closed without merging