Optimize ContentPath#pathAsText
elastic/elasticsearch pull request #98244
Opened 2023-08-06 08:32 UTC by dorukguner

This pr optimizes calls to ContentPath#pathAsText through the following changes:
- When at the root we return the provided string directly
- When called on a sibling or child field the previously built path is maintained to prevent appending the same top-level fields again

The case in which fields that have been previously added to the path are removed is handled in ContentPath#remove by clearing the existing StringBuilder.

Tests for ContentPath#pathAsText have been added in a separate commit to the optimization to allow for easy validation that the tests are correct.

Addresses #94544

2023-08-14 12:20 UTC, elasticsearchmachine commented
Pinging @elastic/es-search (Team:Search)

2023-09-08 09:52 UTC, cbuescher requested changes
Hi @dorukguner, sorry for the delay in getting to this and thanks for picking it up.
I like the solution and the tests are great. Since we have tests now I would like to go a step further and optimize your solution even a bit more. I left a few suggestions for that, let me know what you think.

2023-09-08 09:52 UTC, cbuescher commented on server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java
> +    private int sbIndex = 0;
I think we can get rid of this additional index if we change the remove method so it resets the strin builder length according to the length of the element removed.

2023-09-08 09:52 UTC, cbuescher commented on server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java
> +        // Reset the StringBuilder if it includes a newly removed field
I think we can avoid a full reset here. We can determine the length of the removed path element before nulling it out, then reset the string builder length accordingly. Some special casing for index == 0 and the delimiters might be needed.

2023-09-08 09:52 UTC, cbuescher commented on server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java
> +        while (sbIndex < index) {
I think we can already keep the string builder current while we add / remove things and avoid the need to have a second index here

2023-09-08 09:52 UTC, cbuescher commented on server/src/test/java/org/elasticsearch/index/mapper/ContentPathPathAsTextTests.java
> +public class ContentPathPathAsTextTests extends ESTestCase {
Great tests, thanks for adding those, it makes code changes like these so much easier to check. 
Unfortunately there was another test class for ContentPath added with #98332 (ContentPathTests).
I would like to keep that one as the main test class. Would you mind to merge the test cases that are not covered to that unit test class? I think there might be some duplication now.

2023-09-11 05:36 UTC, dorukguner commented
Hi @cbuescher, thanks for the feedback.

I've merged the extra test cases I had into the new main test class and I've also optimised ContentPath a little further.

I realised we didn't need both an array of strings for the path and a string builder. We can have just a string builder while keeping track of the indexes in which the delimiters were added, and using the add and remove methods to modify the string builder directly. This has removed the need for any loops and any extra indexes.

Please let me know what you think about the new optimisations, I'm open to any other suggestions you may have.

2023-09-11 10:43 UTC, cbuescher reviewed
@dorukguner thanks a lot, I think the idea of just keeping one datastructure for the whole path and keeping around the pointers to the parts is great and the tests are also covering this nicely. I left two small comments but will prepare this PR for testing and merging while you address those.

2023-09-11 10:43 UTC, cbuescher commented on server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java
> +        sb.delete(delimiterIndexes.pop() + 1, sb.length());
Maybe we can check the stack size and throw a nicer exception than the EmptyStackException, maybe something that mentions an empty contentPath.

2023-09-11 10:44 UTC, cbuescher commented
Just running a check before the final changes to see if this breaks anything else.

@elasticsmachine test this please

2023-09-11 11:09 UTC, cbuescher commented
@dorukguner could you also run ./gradlew :server:spotlessApply to apply our formatting rules to the modified classes?

2023-09-13 08:18 UTC, cbuescher approved these changes
Thanks for the update, LGTM. Will need to run full test suite before merging.

2023-09-13 08:19 UTC, cbuescher commented
@elasticmachine test this please

2023-09-13 08:38 UTC, cbuescher commented
@elasticmachine test this please

2023-09-13 09:59 UTC, cbuescher commented
@elasticmachine update branch

2023-09-13 10:00 UTC, cbuescher commented
@elasticmachine test this please

2023-09-13 11:02 UTC, merged

2023-09-13 11:04 UTC, cbuescher commented
@dorukguner huzzah, all passed. Thanks for the change and the iterations, merged to main branch now. I think this is a great change that makes using this class a lot less wasteful.