More migrations of Version for index created version to IndexVersion
elastic/elasticsearch pull request #98495
Opened 2023-08-15 13:06 UTC by thecoop

More migrations of index created version from `Version` to `IndexVersion`. These ones are manual.

2023-08-15 13:06 UTC, elasticsearchmachine commented
Pinging @elastic/es-core-infra (Team:Core/Infra)

2023-08-15 13:07 UTC, thecoop commented on server/src/test/java/org/elasticsearch/index/analysis/PreConfiguredTokenFilterTests.java
> +        IndexVersion version2 = IndexVersion.fromId((beforeAll / 1_000_000) * 1_000_000);
This should be enough to capture 'version definitely before the first version', as we bump by 1,000,000 every major release

2023-08-16 15:17 UTC, williamrandolph requested changes
Looks good, though I have one small suggestion for clarity/maintainability.

2023-08-21 09:22 UTC, thecoop commented on server/src/test/java/org/elasticsearch/index/analysis/PreConfiguredTokenFilterTests.java
> +        IndexVersion version2 = IndexVersion.fromId((beforeAll / 1_000_000) * 1_000_000);
Good idea - spotted an existing method I could use

2023-08-21 15:40 UTC, williamrandolph approved these changes
LGTM!

2023-08-21 15:47 UTC, merged