Ensure that searcher.getReader() is used when using Lucene test searcher
elastic/elasticsearch pull request #98932
Opened 2023-08-28 12:19 UTC by benwtrent

Lucene test searcher will randomly wrap the passed reader. That means any usages that mix the two (the searcher and the previously reader), could cause tests to fail.

Some of these locations maybe don't strictly need the searcher.getReader, but I just wanted to make sure we didn't have flaky tests.

closes: https://github.com/elastic/elasticsearch/issues/98925

2023-08-28 12:20 UTC, elasticsearchmachine commented
Pinging @elastic/es-search (Team:Search)

2023-08-28 14:27 UTC, benwtrent commented on server/src/test/java/org/elasticsearch/index/search/nested/NestedSortingTests.java
> +        IndexSearcher searcher = new IndexSearcher(reader);
Dear reviewer, this fails randomly due to the reader getting randomly wrapped internally by `newSearcher`. We expect this type of reader and it cannot be wrapped. 

```
org.elasticsearch.index.search.nested.NestedSortingTests > testMultiLevelNestedSorting {seed=[4A3E25BDAA026372:B462EF24EC743438]} FAILED
    java.lang.IllegalStateException: Null shardId. If you got here from a test, you need to wrap the directory reader. see for example AggregatorTestCase#wrapInMockESDirectoryReader.  If you got here in production, please file a bug.
        at __randomizedtesting.SeedInfo.seed([4A3E25BDAA026372:B462EF24EC743438]:0)
        at org.elasticsearch.index.cache.bitset.BitsetFilterCache.getAndLoadIfNotPresent(BitsetFilterCache.java:149)
        at org.elasticsearch.index.cache.bitset.BitsetFilterCache$QueryWrapperBitSetProducer.getBitSet(BitsetFilterCache.java:224)
        at org.elasticsearch.index.fielddata.IndexFieldData$XFieldComparatorSource$Nested.rootDocs(IndexFieldData.java:141)
        at org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource.getNumericDocValues(LongValuesComparatorSource.java:90)
        at org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource$1$1.getNumericDocValues(LongValuesComparatorSource.java:109)
        at org.apache.lucene.search.comparators.NumericComparator$NumericLeafComparator.<init>(NumericComparator.java:106)
        at org.apache.lucene.search.comparators.LongComparator$LongLeafComparator.<init>(LongComparator.java:65)
        at org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource$1$1.<init>(LongValuesComparatorSource.java:106)
        at org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource$1.getLeafComparator(LongValuesComparatorSource.java:106)
        at org.apache.lucene.search.FieldValueHitQueue.getComparators(FieldValueHitQueue.java:176)
        at org.apache.lucene.search.TopFieldCollector$TopFieldLeafCollector.<init>(TopFieldCollector.java:64)
        at org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector$1.<init>(TopFieldCollector.java:198)
        at org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector.getLeafCollector(TopFieldCollector.java:198)
        at org.apache.lucene.search.FilterCollector.getLeafCollector(FilterCollector.java:38)
        at org.apache.lucene.tests.search.AssertingCollector.getLeafCollector(AssertingCollector.java:52)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:762)
        at org.apache.lucene.tests.search.AssertingIndexSearcher.search(AssertingIndexSearcher.java:78)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:694)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:688)
        at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:668)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:585)
        at org.elasticsearch.index.search.nested.NestedSortingTests.search(NestedSortingTests.java:823)
        at org.elasticsearch.index.search.nested.NestedSortingTests.testMultiLevelNestedSorting(NestedSortingTests.java:621)
```

2023-08-28 15:06 UTC, benwtrent commented on server/src/test/java/org/elasticsearch/index/search/nested/NestedSortingTests.java
> +        IndexSearcher searcher = newSearcher(reader, false);
This test fails when the reader is wrapped. So making it not `maybeWrap` :)

2023-08-29 02:18 UTC, iverase requested changes
oh, just before reviewing this PR I opened https://github.com/elastic/elasticsearch/pull/98960 which fixes the `FiltersAggregatorTests` in a different way. I feel the approach of my PR is more inline with the needs for that test. The reason is that we are moving on supporting concurrency and the lucene index searcher behavior is very different to the Elasticsearch one so we should be using the later.

I will ask you to revert the changes to that test (I will push the above Pr as soon as it is reviewed), otherwise looks good.

2023-08-29 12:14 UTC, benwtrent commented
@iverase reverted by filteraggs change and merged in main.

2023-08-29 12:31 UTC, iverase approved these changes
LGTM

2023-08-29 12:55 UTC, merged