Share field mapper tests with other modules
elastic/elasticsearch pull request #99142
Opened 2023-09-02 11:37 UTC by shans96

WIP PR to close issue #92947

My approach for solving this problem was to see if I could get `UnsignedLongMapperTests` to extend `NumberFieldMapperTests` by copying `NumberFieldMapperTests` over to the test framework (and then do the same for `ScaledFloatFieldMapperTests`). Once I've made `UnsignedLongMapperTests` extend `NumberFieldMapperTests`, my plan was to make it extend `WholeNumberFieldMapperTests` instead, as that seems more appropriate (and specialised) for the unsigned long type.

I have managed to make `UnsignedLongMapperTests` extend  `NumberFieldMapperTests` but there are now some test failures for:
-`testCoerce`
-`testOutOfRangeValues`
-`testAllowMultipleValuesField`
-`testIgnoreMalformedWithObject`
-`testScriptableTypes`

It looks like some wider changes are needed to fix the tests (e.g., `NumberFieldMapper` has to be updated with some code to support unsigned longs), but I'm not sure of whether this is the right decision or not from an architectural perspective, so I wanted to get some early feedback to make sure I'm on the right track.

Any insight on the above would be appreciated!

2023-09-04 14:29 UTC, elasticsearchmachine commented
Pinging @elastic/es-search (Team:Search)

2023-09-08 12:20 UTC, cbuescher reviewed
Hi @shans96, I took a quick look at this PR but didn't look into all the details because you still marked it as draft.
The general idea is right, I left some comments on some specifics.
I think the general ask with this issue is to move the testing code and put the two mentioned tests (UnsignedLongFieldMapperTests, ScaledFloatFieldMapperTests) under one of the more specific base tests. I think that when tests of the base class fail (e.g. "coerce" doesn't seem to be supported in UnsignedLongFieldMapper), we should overwrite or disable those tests in the inheriting test class. If only some assertions need to be fixed, that's okay of course, but I would like leave behavioural changes out of this refactoring PR as much as possible.
Hope that helps, let me know if you need more input.

2023-09-08 12:20 UTC, cbuescher commented on server/src/test/java/org/elasticsearch/index/mapper/NumberFieldMapperTests.java
> +            protected ScriptFactory emptyFieldScript() {
This class wouldn't bee needed in the "server" module after the move I think. Small changes in visibility are okay if needed, please comment them if you have questions.

2023-09-16 10:39 UTC, shans96 commented on modules/mapper-extras/src/test/java/org/elasticsearch/index/mapper/extras/ScaledFloatFieldMapperTests.java
> +    public void testCoerce() throws IOException {
Changed to make the method signature match how it is declared in `NumberFieldMapperTests`

2023-09-16 10:39 UTC, shans96 commented on test/framework/src/main/java/org/elasticsearch/index/mapper/IngestScriptSupport.java
> +public abstract class IngestScriptSupport {
Good point, thanks- don't think it was needed anymore

2023-09-16 10:39 UTC, shans96 commented on test/framework/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapperTests.java
> +    protected Object generateRandomInputValue(MappedFieldType ft) {
Needs to be made non-final so `UnsignedLongFieldMapperTests` and `ScaledFloatFieldMapperTests` can override it

2023-09-16 10:39 UTC, shans96 commented on modules/mapper-extras/src/test/java/org/elasticsearch/index/mapper/extras/ScaledFloatFieldMapperTests.java
> +    public void testIgnoreMalformedWithObject() {} // unimplemented
I've overridden the methods for now but I'm sure there's a cleaner way to write these. I've seen that some tests can be skipped in gradle, would that be cleaner, and if so, where should I look to find an example?

2023-09-16 10:39 UTC, shans96 commented on test/framework/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapperTests.java
> +    public static class OutOfRangeSpec {
Feedback appreciated on this one

2023-09-16 10:39 UTC, shans96 commented on x-pack/plugin/mapper-unsigned-long/src/test/java/org/elasticsearch/xpack/unsignedlong/UnsignedLongFieldMapperTests.java
> +    }
Still need to resolve this one as well, was thinking of making a new method that supports larger numbers but maybe there's an easier way to support this for unsigned longs?

2023-09-16 10:44 UTC, shans96 commented
Hi @cbuescher, thanks for the feedback. I've made changes based on your comments and think the PR is ready for a proper review; `UnsignedLongFieldMapperTests` now extends `WholeNumberFieldMapperTests` and `ScaledFloatFieldMapperTests` now extends `NumberFieldMapperTests`. I had some small questions on making the code cleaner where I've overridden the methods, and some other small questions, but hopefully they are quick to resolve :+1: 

Look forward to hearing from you!

2023-11-21 11:06 UTC, cbuescher requested changes
Sorry for the late reply. I left a few comments but nothing big, I think we should merge this and work on extending the tests to fill in the missing methods later. As it is, this already improves things by using the same base test class and doesn't remove any coverage. Can you update the branch and add the few things I suggested before I run our CI test suite please?

2023-12-12 16:48 UTC, cbuescher commented
@shans96 just checking in to see if you want to continue this PR, since the branch has gone stale a bit and would need updating. As I mentioned earlier in the comments I think there are only a few smaller changes left to address before we can merge this.

2023-12-12 22:02 UTC, shans96 commented
Hi @cbuescher, apologies for the delay in reply on this one. Keen to finish this PR and will make it a focus- I've updated the comments based on your feedback. I'm currently looking at making `OutOfRangeSpec` publicly accessible: adding a dependency on `elasticsearch.server.test` wouldn't make sense (and would cause a circular dependency I think). Thinking of moving the class to the test framework instead- would this make sense?

2023-12-18 10:01 UTC, cbuescher commented
> Thinking of moving the class to the test framework instead- would this make sense

It think so, yes. Maybe also make the name a bit more specific then, since that class seems tied to the number type tests, so maybe "NumberTypeOutOfRangeSpec" or something along those lines would be good. Please also try to update the branch, I can help with that if needed.

2023-12-20 10:13 UTC, cbuescher commented
Hi @shans96, I'll hand this over to @pmpailis while I'm out for a few weeks. I we only need updating the branch and move the shared "OutOfRangeSpec" code somewhere where it can be accessed by modules. That is, if all tests pass in CI.

2024-01-06 17:45 UTC, shans96 commented
Hi, apologies again for the delay in updates on this one- it's been a hectic holiday season. I've moved `OutOfRangeSpec` into the test framework under the name `NumberTypeOutOfRangeSpec`- not sure if the class location/name are ideal, so any feedback on this one would be appreciated. I've also updated this branch with the latest changes from `master` and everything builds successfully on my local machine, so I think it's ready for CI tests.

2024-01-11 11:20 UTC, pmpailis commented
Thanks for continuing this work @shans96 - changes LGTM! 
The only thing pending prior to running CI is to address the conflicts with `main` as some of the files above were changed recently (e.g. [here](https://github.com/elastic/elasticsearch/pull/103510/files#diff-1a110e1edc49686c15688a028b756a0a4d3cebffae59e5e3d85ae3e0ca76cf37R370)). Happy to help with addressing this if needed :)

2024-01-30 10:19 UTC, pmpailis commented
@shans96 happy to assist with merging/resolving conflicts to move this forward :)

2024-01-30 21:26 UTC, shans96 commented
Hi, thanks for the ping :+1: I've just merged the latest version of `main` into my branch, but haven't run into any merge conflicts. I was anticipating some, so I looked at the PR you linked and tried to search for the new method declarations in the latest version of `main`, but they don't seem to exist there either. Wondering if I missed something, or were there additional changes afterwards that kept the field mapper tests as they were originally?

2024-01-30 21:50 UTC, pmpailis commented
Thanks for taking a look @shans96 ! Yeah, actually it seems that some changes were reverted in [a later PR](https://github.com/elastic/elasticsearch/pull/104218/files#diff-031008a5bee59ebc302cdd947cd0259f5aa716cb49e4a69efd73cd968956b85dR385) a few days ago, so all seems fine now :)  Will proceed with running CI tests :)

2024-01-30 21:51 UTC, pmpailis commented
@elasticmachine test this please

2024-01-30 22:43 UTC, pmpailis commented
buildkite test this please

2024-02-01 10:01 UTC, pmpailis approved these changes

2024-02-01 10:13 UTC, pmpailis commented
Thank you for your effort & contribution @shans96 ! CI tests have all passed 🚀  so I'll proceed with merging :)

2024-02-01 10:14 UTC, merged