[DOC+][ILM][Troubleshooting] JQ for transient steps
elastic/elasticsearch pull request #99612
Opened 2023-09-16 19:21 UTC by stefnestor

👋 howdy, team!

Can we add these common JQ queries to the [ILM Troubleshooting Doc](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-lifecycle-error-handling.html) which check for indices not in "waiting" steps (as defined by me) of `[complete, check-rollover-ready]` and claiming the rest are "transient" steps.

Will still be helpful even after https://github.com/elastic/elasticsearch/issues/93859 .

2023-09-16 19:22 UTC, elasticsearchmachine commented
@stefnestor please enable the option "Allow edits and access to secrets by maintainers" on your PR. For more information, [see the documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

2023-09-16 19:22 UTC, elasticsearchmachine commented
Pinging @elastic/es-docs (Team:Docs)

2023-09-16 19:22 UTC, elasticsearchmachine commented
Pinging @elastic/es-data-management (Team:Data Management)

2023-09-16 19:46 UTC, DaveCTurner requested changes
The trouble with docs like this is that they aren't covered by tests so will fall out of date in time without anybody noticing. If these things are useful, let's include them in the ILM explain output directly.

2023-09-16 19:46 UTC, DaveCTurner commented on docs/reference/ilm/error-handling.asciidoc
> +$ cat ilm_explain.json | jq -c '.indices[]|select(.managed==true and .action!="complete" and .step!="check-rollover-ready")|.phase+"/"+.action+"/"+.step' | sort | uniq -c | sort -r
Needs to be a numeric sort I think:

```suggestion
$ cat ilm_explain.json | jq -c '.indices[]|select(.managed==true and .action!="complete" and .step!="check-rollover-ready")|.phase+"/"+.action+"/"+.step' | sort | uniq -c | sort -nr
```

2023-10-18 22:35 UTC, stefnestor commented
@DaveCTurner does this look good to merge? (Noted on pushing this type of data into ILM overview / ES internal health longer-term.)

2023-10-19 04:00 UTC, DaveCTurner commented
No - these commands need test coverage to avoid them going stale over time. I think the easiest way to achieve that will be to add these things to the ILM explain API, but maybe there are other ways if we really want to have `jq` commands in the docs.

2024-04-18 22:09 UTC, dakrone commented
I think we can close this, since we discussed it and decided adding columns to the cat indices would be a better solution.

2024-04-18 22:09 UTC, closed without merging

2024-06-13 23:23 UTC, stefnestor commented
👋  @dakrone @DaveCTurner  I would still prefer an aggregated summary on how ILM indices are doing if possible. Maybe my team's just used to the JQ query if we'd reconsider it. 

Alternatively, It looks like some ES Diags on more recent versions also have an `ilm` section under `internal_health.json` from [this code](https://github.com/elastic/support-diagnostics/blob/main/src/main/resources/elastic-rest.yml#L227-L234) but that's publicly undocumented AFAICT to share with users.

2024-06-17 22:01 UTC, dakrone commented
That is the ILM indicator of the health report API, which is documented at https://www.elastic.co/guide/en/elasticsearch/reference/current/health-api.html#health-api-response-details-ilm

2025-10-21 18:01 UTC, stefnestor commented
As follow-up to ongoing troubleshooting pain points of not documenting this JQ command
- "That is the ILM indicator" https://github.com/elastic/elasticsearch/issues/113553 is ongoing
- "decided adding columns to the cat indices" https://github.com/elastic/elasticsearch/issues/37499 is undone